### ISSUE TITLE
Can you port the project to STM32?

### ISSUE THREAD

**Issue by qwert1213131** [lvgl/lvgl#10]
stm32 is a powerful mcu,can you port to it ?
stm32f429-disco

**Comment by kisvegabor** [comment]
Hi!

There is no MCU specific code in the library so you can port  it easily to any microcontroller. Only a simple HAL (Hardware Abstraction Layer) has to be provided, like this: https://github.com/littlevgl/proj_pc/tree/master/hal In the HAL you can call your own display and touchpad drivers. That's all you have to do.
Read this  to learn more: http://littlev.hu/index.php/user-guide/system-overview/

**Comment by qwert1213131** [comment]
Thank you very much!
It's very useful!
