### ISSUE TITLE
Replacing the signal function on buttons in a list breaks lv_list_get_next_btn

### ISSUE THREAD

**Issue by fovea1959** [lvgl/lvgl#1010]
If buttons are created in a list, and the signal function for the buttons are replaced, then lv_list_get_next_btn will not find the buttons with the overridden signal function.

lv_list_get_next_btn uses the address of the signal function as a sanity check to see if the object is really a button. Might need a different way to check?

**Comment by fovea1959** [comment]
It is not a good practice to be adding something besides a button to a list, but in this case, I *am* adding a button; it just has a custom signal function (which calls the default signal function and does some additional processing).

**Comment by embeddedt** [comment]
@fovea1959 Your use of the button is the correct practice; I was saying that I don't see a need to have the check in there at all, since there is no need to accommodate the wrong practice.

**Comment by kisvegabor** [comment]
In [lv_list_btn_single_selected](https://github.com/littlevgl/lvgl/blob/master/lv_objx/lv_list.c#L955) it can cause issues if there is a non-button object on the list because it will try to set the button's state.

I can imagine 2 cases when users want to add custom objects to the list:
1. Separator line
2. A title for a group of buttons

I think the type should be checked to be at least a button. As @embeddedt suggested it can be done with `lv_obj_get_type`.

What do you think?

**Comment by embeddedt** [comment]
> In lv_list_btn_single_selected it can cause issues if there is a non-button object on the list because it will try to set the button's state.

I hadn't read that function. In that case we definitely need a check of some sort.

**Comment by embeddedt** [comment]
I created a PR for `dev-6.0` here: #1014 

Once it's merged I can cherry-pick the patch to `master` as well.

**Comment by kisvegabor** [comment]
@embeddedt I merged the PR, thank you. I needed to add fix after merge so please merge that too into master.

**Comment by embeddedt** [comment]
@kisvegabor Both have been cherry-picked to master.

@fovea1959 With the latest `master` branch does `lv_list_get_next_btn` now work as expected?

**Comment by kisvegabor** [comment]
@embeddedt  Great, thank you!

**Comment by fovea1959** [comment]
@embeddedt on latest master, lv_list_get_next_btn indeed works as expected.

**Comment by embeddedt** [comment]
@fovea1959 Great, then I'll close this issue. Thanks for the report!
