### ISSUE TITLE
[6.0] lv_obj_get_signal_func should be named lv_obj_get_signal_cb?

### ISSUE THREAD

**Issue by rreilink** [lvgl/lvgl#1011]
In 6.0, with changes to generic callbacks, `lv_obj_set_signal_func` was renamed to `lv_obj_set_signal_cb`. Should `lv_obj_get_signal_func` be renamed similarly since they are a pair?

**Comment by embeddedt** [comment]
(cc @kisvegabor)

**Comment by kisvegabor** [comment]
Good catch! Fixed by https://github.com/littlevgl/lvgl/commit/fb1ca3fb8771ddac3093976024e4f515cb96fd8e
