### ISSUE TITLE
suggest to extend lv_font to fully compatible with freetype

### ISSUE THREAD

**Issue by ganhailin** [lvgl/lvgl#1012]
It is possible that a truetype/opentype font has different height with different character ，and the origin point may place in the bitmap but not by the bitmap.
I think some argument can add in font , like "GetHeight" , "GetOffset"for a character,and it should be a function like "Contains" allow us call freetype function to check the character is in a font or not.

**Comment by kisvegabor** [comment]
We are just [reworking the Fonts](https://github.com/littlevgl/lvgl/issues/1006) for `v6.0` and we design the interface to make it possible to easily use with FreeType and to use its high level, complex features.

If you have remarks on this topic or you think that we have missed something please comment there.
