### ISSUE TITLE
lv_slider_set_knob_in bug

### ISSUE THREAD

**Issue by chenshijianworkgit** [lvgl/lvgl#102]
I add a line lv_slider_set_knob_in (slider5, true) to the end of the lv_test_slider_1 function, and then dragging the slider keycap will throw outside the bounds.

**Comment by kisvegabor** [comment]
Correct, fixed in `beta`.
Thank you!

**Comment by chenshijianworkgit** [comment]
Thank you,
      Tested in the latest version and found that the problem has been solved.
       The issue can be close.

**Comment by kisvegabor** [comment]
Thank you for the test!
