### ISSUE TITLE
quesiton for lv_txt.c in  lvgl_v5.3

### ISSUE THREAD

**Issue by blueice2019** [lvgl/lvgl#1025]
First, thank you for your greate gui project.
I have a question for lv_txt.c in lvgl_v5.3.
In function lv_txt_get_width(), line 327 like this:
   width += lv_font_get_width(font, letter);
When i use my font in chinese GBK code, it shows wrong.
I change this line to:
   width += char_width;
and then it works well.

In lvgl_v5.2, it has not this question.

**Comment by embeddedt** [comment]
(cc @kisvegabor)

**Comment by embeddedt** [comment]
We use GitHub issues for development related discussions.
Please use the [forum](https://forum.littlevgl.com/) to ask questions.

**Comment by embeddedt** [comment]
Topic moved: https://forum.littlevgl.com/viewtopic.php?f=4&t=96
