### ISSUE TITLE
How to set password by using littlevgl objects..

### ISSUE THREAD

**Issue by TejaswiGunti** [lvgl/lvgl#1034]
Hello, I am trying an application using littlevgl.. I would like to set password, when I touch one button it should pop up one message to enter the password.. If I enter the correct password then only it should perform button action.. Any suggestions please..

**Comment by embeddedt** [comment]
You can make a text area show dots/stars to hide the password with `lv_ta_set_pwd_mode(ta, true);`

Then you can use `lv_ta_get_text` which will give you the real text of the password, which you can then compare as you usually would.

----------------------
**We use GitHub issues for development related discussions.
Please use the [forum](https://forum.littlevgl.com/) to ask questions.**
