### ISSUE TITLE
Using LTDC with DMA2D STM32F7

### ISSUE THREAD

**Issue by KarolAbego** [lvgl/lvgl#104]
Hello. 
I have a problem with displaying data on display using lvgl library. To avoid screen flickering I'm using double buffer technique, it works but slows entire library (I mean that elements such as buttons sliders etc. are drew frame by frame, due to waiting for VSYNC flag on every invoke of "put_pixel(x,y,color)"(buffor) function. 
Is there any possibility to check, when the operation of element drawing is finished (moment to swap buffers)? Or maybe there is another option to implement LTDC and DMA2D with lvgl library.

In zip file i attached 2 movies with double buffer, without, and my lv_conf.h.
[LVGL.zip](https://github.com/littlevgl/lvgl/files/1698969/LVGL.zip)

Thank You in advance for your help.

**Comment by kisvegabor** [comment]
Hi,

For a reference with STM32, please check this post: https://littlevgl.com/blog/23/embedded-gui-using-linux-frame-buffer-device-with-littlevgl

I saw that you disabled VDB in lv_conf.h (LV_VDB_SIZE). It's an essential part of the library and responsible for fast and smooth drawing.
With VDB you need to implement only a `disp_flush` function which copies a pixel array to the frame buffer. It will be already double buffered. Learn more here: https://littlevgl.com/basics#drawing-and-rendering
