### ISSUE TITLE
[v6.0] Window ext->style_header seems unused?

### ISSUE THREAD

**Issue by rreilink** [lvgl/lvgl#1041]
@kisvegabor 

In lv_win.c, `ext->style_header` is only used in one line, in `lv_win_realign`:

```c
lv_obj_align(ext->title, NULL, LV_ALIGN_IN_LEFT_MID, ext->style_header->body.padding.left, 0);
```

Other statements in `lv_win_realign` use the style which is retrieved using `header_style = lv_win_get_style(win, LV_WIN_STYLE_HEADER)`

 `lv_win_set_style` modifies the header style via `lv_obj_set_style(ext->header, style);`.

Is this intended behavior? Or should that single line in `lv_win_realign` also use `header_style` which is retrieved using `lv_win_get_style` and should `ext->style_header` be removed?

**Comment by kisvegabor** [comment]
Good catch! It really should be deleted.

See 5e60002
