### ISSUE TITLE
How to insert our own images?

### ISSUE THREAD

**Issue by TejaswiGunti** [lvgl/lvgl#1043]
Hello,
     I am trying to insert my image on to my application infact it is our company logo which I want to get on my application.. Help me to get out of this.. Do not close the issue..

Thanks in advance for helping..

**Comment by embeddedt** [comment]
You should use the image convertor: https://littlevgl.com/image-to-c-array

It has a tutorial at the top explaining how to import your image.

**If you still require more help, please use the [forum](https://forum.littlevgl.com/).**

**Comment by TejaswiGunti** [comment]
Thanks for the help..
