### ISSUE TITLE
Please provide examples of sparse CJK fonts!

### ISSUE THREAD

**Issue by puzrin** [lvgl/lvgl#1044]
Hi all! If you use sparse CJK fonts, could you post your zipped sources here?

We are implementing new font format, and this info will be helpful to verify built-in optimizer and edge cases.

Also, see #995, and feel free to ask any question.

Initial reference: #78

**Comment by fallstool** [comment]
Hi:
I found a demo from website. [here](http://forum.armfly.com/forum.php?mod=viewthread&tid=86371&highlight=littlevgl)
you can download it here:[zip file](http://forum.armfly.com/forum.php?mod=attachment&aid=Mzc2NjR8OTQ5ZjJiNTd8MTU1NzI4NDQzMHwwfDg2Mzcx)

**Comment by puzrin** [comment]
Thanks! From that project:

- not so many glyphs (~30),
- bigger size (20px)
- kerning not needed
- all sparse

**Comment by kisvegabor** [comment]
> kerning not needed
> all sparse

I can confirm it. However, the number of glyphs and font size depends on the application.
It's easy to have a few thousand glyphs in CJK.

**Comment by kisvegabor** [comment]
CJK should be well supported in the new converter too. If something is not working please open a dedicated issue for it.
