### ISSUE TITLE
Message Box usage information

### ISSUE THREAD

**Issue by TejaswiGunti** [lvgl/lvgl#1045]
Hello,
I have a question regarding Message box.. In message box we have two buttons like yes and no.. Is there any option to call different function when we press each button? To be clear, I want one function to be called by clicking on Yes and call another function when I click on No.. 

We have buttons declared by **char * btns[] ={"\221Apply", "\221Close", ""};** how we can access those two buttons separately?
lv_mbox_add_btns(mbox1, btns, NULL);
In the above statement I will give some fuction name in the NULL position(3rd argument). What should be given in the second argument if I want to call different functions for different buttons?
Please help..  I have also gone through Message box usage question #383 and did not find any information related to my issue..

**Comment by embeddedt** [comment]
You have to call separate functions inside your callback: 

```c
static lv_res_t btnm_action(lv_obj_t * btnm, const char *txt) {
     if(!strcmp(txt, "Close"))
        close_action(btnm);
     else if(!strcmp(txt, "Apply"))
        apply_action(btnm);
}
```

----------------------
We use GitHub issues for development related discussions.
Please use the [forum](https://forum.littlevgl.com/) to ask questions.
