### ISSUE TITLE
How to only flush once after rendering text?

### ISSUE THREAD

**Issue by ripe909** [lvgl/lvgl#1046]
I'm not sure how to state the question properly, but hopefully it will make sense.

I have a screen with a lot of text elements that change frequently.  When I change the text, the disp_flush is called twice for each element, once to blank out the old area and then again to draw the new text.

Is there some way I can configure lvgl to only flush after the text area is completely redrawn in the VDB? In the majority of cases the area being drawn is exactly the same, so flushing twice generates quite a bit of redraw overhead.

**Comment by embeddedt** [comment]
----------------------
We use GitHub issues for development related discussions.
Please use the [forum](https://forum.littlevgl.com/) to ask questions.

It's possible to sign in to the forum with your GitHub account... you don't need to make a separate account.
