### ISSUE TITLE
Text color is incorrect when setting LV_COLOR_DEPTH is 8

### ISSUE THREAD

**Issue by PierreKao** [lvgl/lvgl#1051]
I use pc_simulator to develop.
I found the text color would be gray(like below image) when I configured the LV_COLOR_DEPTH to 8 and set text color as LV_COLOR_WHITE.
Is it normal ? or I miss something need to do?

I also set object background color as white or set some white image. I got normal behavior.
Could someone help me to clarify this issue?

Thank you.

![2019-05-02_175011](https://user-images.githubusercontent.com/20974824/57067887-c7258d80-6d02-11e9-8e2d-1ca13602f0ac.png)

**Comment by embeddedt** [comment]
@PierreKao Which PC simulator version are you using? The CodeBlocks one or the Visual Studio one?

If you're using the CodeBlocks one I haven't added `LV_COLOR_DEPTH == 8` color support yet.

----------------------
We use GitHub issues for development related discussions.
Please use the [forum](https://forum.littlevgl.com/) to ask questions.

It's possible to sign in to the forum with your GitHub account... you don't need to make a separate account.

**Comment by PierreKao** [comment]
Hi @embeddedt ,

I am not sure which version I used. (for eclipse)
I download from this github https://github.com/littlevgl/pc_simulator_sdl_eclipse.git

If I configure as LV_COLOR_DEPTH == 8 on dev board, would this issue happen?

Thank you

**Comment by embeddedt** [comment]
@PierreKao Please continue this discussion on the forum.
