### ISSUE TITLE
Different font sizes in same label

### ISSUE THREAD

**Issue by AlexNuravine** [lvgl/lvgl#1052]
# All enhancement requests or questions should be directed to the Forum.

Hi I would like to know the best way to have two different size fonts right next to each other. In my example for displaying temperature I would like something like 70 F. Where the 70 is big and the F is small. Thanks

We use GitHub issues for development related discussions.
Please use the [forum](https://forum.littlevgl.com/) to ask questions.

**Comment by embeddedt** [comment]
----------------------
We use GitHub issues for development related discussions.
Please use the [forum](https://forum.littlevgl.com/) to ask questions.

It's possible to sign in to the forum with your GitHub account... you don't need to make a separate account.
