### ISSUE TITLE
Use font from external SPI Flash

### ISSUE THREAD

**Issue by ShenRen** [lvgl/lvgl#1053]
new, I have to support all Chinese character in my MarlinUI Project for 3D printer. 
I use mcu stm32f103rct6 which has only 48kB RAM and 256 KB ROM for my PandaMini 
3D printer board. The board has a 16MB spi flash that using to storage big data , like image and bin file.  
    It is easy to read image from external SPI Flash. But I don't know how to deal with big font (microsoft_yahei_chinese_16.c size: 8MB) . So here's the middle way , I keep only the Chinese character that are used by MarlinUI .

Here is my project framework:

Marlin V2--------------------------------------------\\
LittlevGL V5.3-------->**LittlevGL_CPPPort** --------->**MarlinUI**-------> **PandaMini** 
**PandaScreen**------------>**PandaDriver**-------------/

ps: LittlevGL_CPPPort  is a lvgl c To C++ wrapper class.

Is there a way that using font from external SPI Flash.
Can someone help me ?  Thanks a lot.

**Comment by embeddedt** [comment]
----------------------
We use GitHub issues for development related discussions.
Please use the [forum](https://forum.littlevgl.com/) to ask questions.

It's possible to sign in to the forum with your GitHub account... you don't need to make a separate account.
