### ISSUE TITLE
Extra symbol

### ISSUE THREAD

**Issue by zavovi** [lvgl/lvgl#1059]
Hi,
please could you help me with extra symbols? I downloaded Font Awesome and generated fonts from 61440 to 63537. Now, I put instead of the lv_font_symbol_20 and I want use symbols form my extra fonts, but I don't know, how. I wanted change the defines as SYMBOL_AUDIO etc... But there should be something wrong in my definitions. I cannot find my symbols. 
Please, could you help me, what numbers should I put into this _SYMBOL_VALUE3(EF,A0,EE) and why ?

Thank you very much

**Comment by seyyah** [comment]
Maybe useful `php font_conv_for_lists.php` [1].

You need only Unicode value from Fontawesome v4.7,

![image](https://user-images.githubusercontent.com/263237/57524221-d83c5300-732f-11e9-967d-c6ded0fd539b.png)

Usage [3]

```sh
$ php font_conv_for_lists.php
[...]
USAGE

a. Define
#define LV_SYMBOL_THERMOMETER_EMPTY     "\xef\x8b\x8b"
#define LV_SYMBOL_TINT                  "\xef\x81\x83"
#define LV_SYMBOL_BALANCE_SCALE         "\xef\x89\x8e"
#define LV_SYMBOL_BARS                  "\xef\x83\x89"
#define LV_SYMBOL_MICROCHIP             "\xef\x8b\x9b"

b. Add font
lv_font_add(&font_symbol_extra_100, &lv_font_symbol_100);
static lv_style_t style;
lv_style_copy(&style, &lv_style_plain);
style.text.font = &lv_font_symbol_100;

c. Declare
LV_FONT_DECLARE(font_symbol_extra_100)

d. Use it;)
lv_obj_t * label = lv_label_create(scr, NULL);
lv_label_set_style(label, &style);
lv_label_set_text(label, LV_SYMBOL_THERMOMETER_EMPTY LV_SYMBOL_TINT              
  LV_SYMBOL_BALANCE_SCALE     LV_SYMBOL_BARS              LV_SYMBOL_MICROCHIP         );
```

---
We use GitHub issues for development related discussions.
Please use the forum to ask questions or suggest enhancements.

It's possible to sign in to the [forum](https://forum.littlevgl.com/) with your GitHub account... you don't need to make a separate account.

## :clipboard: Reference
1. https://github.com/littlevgl/lv_utils#list-parameter-specific-utility
2. https://fontawesome.com/v4.7.0/icon/free-code-camp
3. https://github.com/littlevgl/lv_utils/pull/26

**Comment by zavovi** [comment]
Hi, thank you, but I still cannot understand this:
Unicode: f2c5 (is it in hexadecimal?) and now this:
#define LV_SYMBOL_THERMOMETER_EMPTY     "\xef\x8b\x8b" 
Why 0xEF 0x8B 0x8B ?

And another question, when I downloaded version 5, then it is ok using unicode from version 5, right?

Thank you

**Comment by seyyah** [comment]
Please read this code part,

```c
  // https://fontawesome.com/v4.7.0/icons/
  // label: unicode
  $unicodes = array(
    "THERMOMETER_EMPTY" => "f2cb",
    "TINT             " => "f043",
    "BALANCE_SCALE    " => "f24e",
    "BARS             " => "f0c9",
    "MICROCHIP        " => "f2db"
  );
```
> And another question, when I downloaded version 5, then it is ok using unicode from version 5, right?

I use v4.7.0. I don't experience fontawesome v5.

## :clipboard: Reference
1. https://github.com/littlevgl/lv_utils/blob/master/font_conv_for_lists.php#L7-L15

**Comment by zavovi** [comment]
Oh thanks. I understand now. Solved my issue :-)

**Comment by embeddedt** [comment]
@zavovi Please note: for future questions like this, use the [forum](http://forum.littlevgl.com/).
