### ISSUE TITLE
Arabic Writing Support

### ISSUE THREAD

**Issue by AbdullahBatiran** [lvgl/lvgl#1060]
I recently started using your library, it is amazing and I love it,

Because I write in Arabic I added Arabic font and the process was quiet easy using the online ttf to C array converter tool.

But the problem was the space "lv_draw_label( )" function make between every charecter, in Arabic we need all letters to be connected.

I dig to find the problem, and I found it was exactly in the line 189 of file "lv_draw_label.c"
```C
188: if(letter_w > 0){
189:     pos.x += letter_w + style->text.letter_space;
190: }
```

Just by deleting "text.letter_space" variable every thing worked well...

To support both Arabic and English I made a conditional statement to check if the unicode for the letter is in the range of Arabic letters, if in the range delete the space if not add it.

```C
if(letter_w > 0){
    if ((letter >= 65136 && letter <= 65279) || (letter >= 1536 && letter <= 1791)) { 
        // Arabic Range
        pos.x += letter_w;
    }
    else {
        pos.x += letter_w + style->text.letter_space;
    }
}
```

**Comment by embeddedt** [comment]
----------------------
We use GitHub issues for development related discussions.
Please use the [forum](https://forum.littlevgl.com/) to ask questions or suggest improvements.

It's possible to sign in to the forum with your GitHub account... you don't need to make a separate account.
