### ISSUE TITLE
Problem with lv_obj_create(*parent, *copy) when copy parameter points to a screen object

### ISSUE THREAD

**Issue by barmaley70** [lvgl/lvgl#1062]
The function subsequently calls lv_obj_get_x(copy) and lv_obj_get_y(copy) that accessing parent->coords.x1 and parent->coords.y1 without checking the parent for NULL. In case if copy object is a screen and does not have a parent it leads to NULL pointer access.

**Comment by embeddedt** [comment]
Looks like a valid bug from a quick read of `lv_obj_create`.

(cc @kisvegabor)

**Comment by kisvegabor** [comment]
It's really a bug.

Fixed here: https://github.com/littlevgl/lvgl/commit/c8d1413eced815ae903b25e99c0500a459b9d85e
Please verify if it's work now.

I applied the same fix for `dev-6.0` too.

**Comment by kisvegabor** [comment]
@barmaley70 if it's still not working please comment here and reopen the issue.
