### ISSUE TITLE
[BUG] Font drawing and width discrepency

### ISSUE THREAD

**Issue by upbeat27** [lvgl/lvgl#108]
Depending on AA settings, you get different results with the actual font rendering vs. `lv_label_get_letter_pos`, for example.

As a result, in a text area object the location of the cursor is off.

With no AA or font AA:
`lv_label_get_letter_pos` won't get the right position, because the drawing function calculates the x differently.

To me it seems to all stem from this snippet in `lv_draw_label`:
```
/* Round error occurs in x position
 * When odd widths are scaled down the last 1 is lost. So the letters seems shorter.
 * Now calculate according to is to be consequent  */
if(letter_w & 0x01) pos.x--;
```

Without that line, everything works well (at least for me).
I understand the intent of that line, but in my opinion it makes things worse in either case (with or without AA).

**Comment by kisvegabor** [comment]
Hi,

you are right it's a bug. It should do the correction only with LV_ANTIALIAS or LV_FONT_ANTIALIAS.

However it is required with any type of anti aliasing. I just fixed it int `beta`

Thank you!
