### ISSUE TITLE
lv_img use bin file  is very performance-consuming

### ISSUE THREAD

**Issue by joy-shuang** [lvgl/lvgl#1084]
# All enhancement requests or questions should be directed to the Forum.

When using the bin image file in my project, i have to re-read the file every time when refresh the interface, which is very performance-consuming, what's the good way?

We use GitHub issues for development related discussions.
Please use the [forum](https://forum.littlevgl.com/) to ask questions.

**Comment by embeddedt** [comment]
----------------------
We use GitHub issues for development related discussions.
Please use the [forum](https://forum.littlevgl.com/) to ask questions.

It's possible to sign in to the forum with your GitHub account... you don't need to make a separate account.
