### ISSUE TITLE
Need define attribute for read only data (to save fonts, etc in QUAD SPI Flash)

### ISSUE THREAD

**Issue by XuanThiep** [lvgl/lvgl#1086]
# Need define attribute for read only data (to save fonts, etc in QUAD SPI Flash).

Hello every one. I am new in littlevGL library. I had succes porting this amazing lib to STM32F769I -Discovery. After build code, I see that internal flash of STM32 is conmuse so much. Using Build Analyzer of Atollic Studio a see that this primarily reason is read only data of littevGL Lib such as: fonts c array, const table, etc.. I think author need add attribute define in lv_conf.h to user custom place to address this read only data. Thanks !
![tempsnip](https://user-images.githubusercontent.com/22855726/58648108-27741300-8333-11e9-8653-0b847d8b7da5.png)

**Comment by embeddedt** [comment]
----------------------
We use GitHub issues for development related discussions.
Please use the [forum](https://forum.littlevgl.com/) to ask questions.

It's possible to sign in to the forum with your GitHub account... you don't need to make a separate account.
