### ISSUE TITLE
Clicking on an auto closing message box that has no buttons defined causes a memory fault.

### ISSUE THREAD

**Issue by pete-pjb** [lvgl/lvgl#1101]
Hi,

Dev-6.0 Branch.

If you click on an auto closing message box with a mouse pointer when there are no buttons assigned it causes a memory fault.  The crash appears to be caused by the calling of the function lv_btnm_get_active_btn() with NULL.

**To Reproduce**
Display an auto closing message box and click on it with mouse pointer...

Kind Regards,

Pete

**Comment by kisvegabor** [comment]
Hi,

I fixed it in 3abcf52. Is it working well now?

**Comment by pete-pjb** [comment]
Hi @kisvegabor ,

Yes I can confirm the problem is fixed...  Thank you.

Kind Regards,

Pete

**Comment by kisvegabor** [comment]
Thank you for the feedback!
