### ISSUE TITLE
info about the engine

### ISSUE THREAD

**Issue by HendrixString** [lvgl/lvgl#1103]
hello, 

I am considering using the library, it looks great !!!

BUT, I have some questions :

1. How do you achieve < 10kb RAM when doing alpha blending ?
2. do you maintain a display list ? caching views ?
3. does each view has a separate framebuffer ? 

I am trying to verify what are the optimization strategies taken with this library before I try it

all the best
Tomer

**Comment by kisvegabor** [comment]
We use GitHub Issues for development related discussions.

Please ask your question in the [Forum](https://forumtest.littlevgl.com/). You can simply log in with your GitHub account too.

Thank you!
