### ISSUE TITLE
lv_tabview.c erroneous comparison

### ISSUE THREAD

**Issue by BrianPugh** [lvgl/lvgl#1109]
I don't use tabview, so I don't know the intention, but these lines seem erroneous and throw compiler warnings; the evaluation is always false:

https://github.com/littlevgl/lvgl/blob/dev-6.0/src/lv_objx/lv_tabview.c#L929

https://github.com/littlevgl/lvgl/blob/dev-6.0/src/lv_objx/lv_tabview.c#L956

**Comment by embeddedt** [comment]
Thanks for the report. I fixed it here: https://github.com/littlevgl/lvgl/commit/ce7b183f509f5c87d9499b6ebf576c7205c662d2

**Comment by kisvegabor** [comment]
Thank you!
