### ISSUE TITLE
Compilation error: invalid conversion from 'void*' to 'lv_style_anim_dsc_t*' in lv_style.h

### ISSUE THREAD

**Issue by gesture1968** [lvgl/lvgl#1113]
When compiling with lvgl 6.0 (commit  d79df21) the following error is given in Arduino 1.8.9:

     In file included from C:\Users\xxx\Documents\onedrive\Arduino\libraries\lv_arduino/src/lv_core /lv_obj.h:24:0,

     from C:\Users\xxx\Documents\onedrive\Arduino\libraries\lv_arduino/lvgl.h:25,

     from C:\Users\xxx\Documents\OneDrive\Arduino\projects\STM32\V6.0\LittlevGL_Spinbox\LittlevGL_Spinbox.ino:1:

     C:\Users\xxx\Documents\onedrive\Arduino\libraries\lv_arduino/src/lv_core/lv_style.h: In function 'void lv_style_anim_set_ready_cb(lv_anim_t*, lv_anim_ready_cb_t)':

     C:\Users\xxx\Documents\onedrive\Arduino\libraries\lv_arduino/src/lv_core/lv_style.h:188:36: error: invalid conversion from 'void*' to 'lv_style_anim_dsc_t*' [-fpermissive]

     lv_style_anim_dsc_t * dsc = a->var;

Perhaps a cast is needed?

**Comment by embeddedt** [comment]
Just fixed it. Thanks: https://github.com/littlevgl/lvgl/commit/7f7034f50fd62b3a3335e72510e129dab4cc3745

C doesn't usually care, but C++ is picky about conversions from `void *` without casting.

**Comment by kisvegabor** [comment]
Thank you!
