### ISSUE TITLE
Small error in lv_canvas_copy_buf parameter

### ISSUE THREAD

**Issue by xiongyumail** [lvgl/lvgl#1117]
HI,

Please notice the small differences in w, h, x, y in the parameters.

<https://github.com/littlevgl/lvgl/blob/dev-6.0/src/lv_objx/lv_canvas.c>
```
void lv_canvas_copy_buf(lv_obj_t * canvas, const void * to_copy, lv_coord_t w, lv_coord_t h, lv_coord_t x, lv_coord_t y)
```

<https://github.com/littlevgl/lvgl/blob/dev-6.0/src/lv_objx/lv_canvas.h>
```
void lv_canvas_copy_buf(lv_obj_t * canvas, const void * to_copy, lv_coord_t x,
                        lv_coord_t y, lv_coord_t w, lv_coord_t h);
```

**Comment by embeddedt** [comment]
@xiongyumail Thanks for noticing! Strange that this happened. I've fixed it here: https://github.com/littlevgl/lvgl/commit/ff657882bc544374c372d086e9a9c3d4e2037648

**Comment by kisvegabor** [comment]
Thank you for pointing that out and for fix!
