### ISSUE TITLE
[v6.0] Message box delete event triggered twice

### ISSUE THREAD

**Issue by embeddedt** [lvgl/lvgl#1135]
**Describe the bug**

The `LV_EVENT_DELETE` event is triggered twice on a message box.

**To Reproduce**

Register an event callback on a message box and then call `lv_obj_del`.

**Expected behavior**

Only one delete event would be sent for the message box itself.

**Additional context**

The problem is occuring because the button matrix is sharing the event handler for the message box.

**Comment by kisvegabor** [comment]
> The problem is occuring because the button matrix is sharing the event handler for the message box.

That correct. The button matrix has `lv_obj_set_parent_event(ext->btnm, true);` so all events are sent to the parent message box. 

To solution could be to not use `lv_obj_set_parent_event` but add a custom event function to the button matrix which passes only the desired events. Similarly to lv_page https://github.com/littlevgl/lvgl/blob/6989a9c797e28d939e14aa92c32c8936390dd4e4/src/lv_objx/lv_page.c#L1077-L1088

**Comment by embeddedt** [comment]
@kisvegabor Okay. I will change it to do things that way then. Do we want that set of events plus `LV_EVENT_VALUE_CHANGED`?

**Comment by kisvegabor** [comment]
> Do we want that set of events plus LV_EVENT_VALUE_CHANGED?

Yes, I think that enough.

Thank you!

**Comment by kisvegabor** [comment]
It should be fixed [here]( https://github.com/littlevgl/lvgl/commit/5ae4b62f4db0b89b815697b9d1d1679bc568aa86#diff-ef6815498dbe8df10fd77252701d59adR533).

So can we close this issue?

**Comment by embeddedt** [comment]
Yes, sorry. I forgot to come back and close it.

**Comment by kisvegabor** [comment]
No worries :slightly_smiling_face:
