### ISSUE TITLE
Easy way to change the font of a button

### ISSUE THREAD

**Issue by xcqq** [lvgl/lvgl#1139]
I know we have these styles for button object:
- LV_BTN_STYLE_REL
- LV_BTN_STYLE_PR
- LV_BTN_STYLE_TGL_REL
- LV_BTN_STYLE_TGL_PR
- LV_BTN_STYLE_INA

But to change the font of a button by setting all these styles is so complicated. Is there an easy way to change the font of a button?
Thanks a lot!

**Comment by kisvegabor** [comment]
Unfortunately, there is no other way. You have to set the font in all the styles.

---

We use GitHub issues for development related discussions.  
To ask questions please use the Forum. You can easily log in with your GitHub account too.
https://forum.littlevgl.com/
