### ISSUE TITLE
How many layers in LTDC (STM32 ) should be used

### ISSUE THREAD

**Issue by KarolAbego** [lvgl/lvgl#114]
Hello.
I have a problem with ex_mem_blend ex_mem_fill functions. How many layers in LTDC configuration should I use? Does the lvgl supports two layers?
Thank You in advance.

**Comment by kisvegabor** [comment]
Hi,
Check this code as  a reference (it's for STM32F429): https://github.com/littlevgl/lv_boards/blob/master/stm32f429_discovery_no_os/hal_stm_lvgl/tft/tft.c

Basically you need only one layer for a simple frame buffer. It is the power of LittlevGL to work with only one frame buffer. 

In `mem_blend` you should use two layer of DMA2D: one for source and one for destination memory.
In `mem_fill` you need only one layer of DMA2D: to fill an area with a color.
