### ISSUE TITLE
How to get width of the label ?

### ISSUE THREAD

**Issue by TridentTD** [lvgl/lvgl#1147]
When I create a label like the following..

lv_obj_t *label = lv_label_create(lv_scr_act(), NULL);
lv_label_set_text(label, "Hello LittleVGL");

How can I receive the width of this label?
Thank you.

**Comment by xqdd** [comment]
https://docs.littlevgl.com/en/html/object-types/obj.html#_CPPv416lv_obj_get_widthPK8lv_obj_t

**Comment by embeddedt** [comment]
----------------------
We use GitHub issues for development related discussions.
Please use the [forum](https://forum.littlevgl.com/) to ask questions.

It's possible to sign in to the forum with your GitHub account... you don't need to make a separate account.
