### ISSUE TITLE
Bug in lv_img_decoder_built_in_info when using image source from filesystem

### ISSUE THREAD

**Issue by ghost** [lvgl/lvgl#1150]
Hi,

I try to load an image
`lv_img_set_src(sidebar_background, "S:/hintergrund.bin");`

1. lv_img_src_get_type sets type LV_IMG_SRC_FILE
2. lv_img_decoder_built_in_info gets called reads header correctly.
3. lv_img_cf_t cf = ((lv_img_dsc_t *)src)->header.cf; gets executed, src->header is bullshit
4. function fails with LV_RES_INV because cf contains garbage data from src->header.

Changing (in lv_img_decoder_built_in_info)
        `lv_img_cf_t cf = ((lv_img_dsc_t *)src)->header.cf;`
       ` if(cf < CF_BUILT_IN_FIRST || cf > CF_BUILT_IN_LAST) return LV_RES_INV;`
to
        `if(header->cf < CF_BUILT_IN_FIRST || header->cf > CF_BUILT_IN_LAST) return LV_RES_INV;`
fixes this problem and the image info in `lv_img_set_src` gets set correctly.

**Comment by embeddedt** [comment]
Looks like the right change to me. Can you send a PR?
