### ISSUE TITLE
Littlevgl & touchscreen(ADS7843) & freeRTOS & STM32F429IG

### ISSUE THREAD

**Issue by FutureOfAI** [lvgl/lvgl#1153]
# I met 2 bugs when applying LVGL to stm32f4 with freeRTOS.
Eva board layout by myself, Everything is ok if didn't use freeRTOS.

When I add freeRTOS to my project and put loop to task, initially everything is also fine including touchscreen, rtos and lvgl, but few minutes later I found  **touchpad_read** function never be called during debug mode (but stm32 exit interrupt happens during touching), does someone has any idea about this bug?

And also in freeRTOS mode I found It will enter **HardFault_error** founction when I tried to add 
text area in task. e.g.
```
/* add text area */ /* this will cause Hardfault error dont know why @@*/
//	sta_Value_total = lv_ta_create(parent, NULL);
//	lv_obj_set_size(sta_Value_total, 80, 40);
//	lv_ta_set_cursor_type(sta_Value_total, LV_CURSOR_NONE);
//	lv_ta_set_text(sta_Value_total, "0000");
//	lv_obj_align(sta_Value_total, label_total, LV_ALIGN_OUT_BOTTOM_MID, 0, 0);

```
if any idea about these bugs, pls tell me, I'll try my best to find the solution of these bugs. thank you.

We use GitHub issues for development related discussions.
Please use the [forum](https://forum.littlevgl.com/) to ask questions.

**Comment by embeddedt** [comment]
Two things:

* Are you calling LittlevGL APIs simultaneously in two threads? That is guaranteed to crash eventually.
* Check that you're not overflowing the stack.

----------------------
We use GitHub issues for development related discussions.
Please use the [forum](https://forum.littlevgl.com/) to ask questions.

It's possible to sign in to the forum with your GitHub account... you don't need to make a separate account.
