### ISSUE TITLE
How to change height of window's header?

### ISSUE THREAD

**Issue by TridentTD** [lvgl/lvgl#1154]
When I change font of window-widget's title. But the window's header height is not adjusted.
If I want to change window header's height, how to config it?

Thank you.

**Comment by embeddedt** [comment]
----------------------
We use GitHub issues for development related discussions.
Please use the [forum](https://forum.littlevgl.com/) to ask questions.

It's possible to sign in to the forum with your GitHub account... you don't need to make a separate account.
