### ISSUE TITLE
Real Values in Online simulator?

### ISSUE THREAD

**Issue by hackrid** [lvgl/lvgl#1163]
Hello,

imagine littlevgl running on a wifichip like esp32.

What would it take to use something like the demo-canvas on [this site ](https://littlevgl.com/demo-theme-night) to show real values and interact with the application like a real touch display?

what do you think about this idea in general?

best regards!

**Comment by embeddedt** [comment]
Are you suggesting running a webserver on the ESP32 that serves LittlevGL over HTTP? If so, it's definitely possible but it would need quite a bit of work on your end.

----------------------
We use GitHub issues for development related discussions.
Please use the [forum](https://forum.littlevgl.com/) to ask questions.

It's possible to sign in to the forum with your GitHub account... you don't need to make a separate account.
