### ISSUE TITLE
lv_button display strange stripes

### ISSUE THREAD

**Issue by d3veloper4u** [lvgl/lvgl#1171]
i'm using lvgl with this lcd [RK043FN02H-CT](https://www.mouser.it/datasheet/2/302/RK043FN02H-CT-1143386.pdf). Everythings works fine but while lvgl renders a button i got this unexpected behaviour

![photo_2019-08-12_08-31-00](https://user-images.githubusercontent.com/51754982/62848411-d6da4800-bcdb-11e9-8b43-5a23aafdfa26.jpg)
 
How can i solve it?

**Comment by embeddedt** [comment]
----------------------
We use GitHub issues for development related discussions.
Please use the [forum](https://forum.littlevgl.com/) to ask questions.

It's possible to sign in to the forum with your GitHub account... you don't need to make a separate account.
