### ISSUE TITLE
use png images in littlevgl 6.0 download

### ISSUE THREAD

**Issue by tnoergaard** [lvgl/lvgl#1172]
Hi I downloaded the most recent littlevgl 6.0 from the littlevgl website and am using the PC simulator project example to test. I needed the ability to load png files, so downloaded the png decoder library as well, however the api's used in the png library do not exist in the littlevGL lib downloadable online (the custom functions), etc. If there a compatible png library to the littlevGL lib online, or is there an older littlevGL library I have to use in order to be able to have the png file support? Thank you.

**Comment by embeddedt** [comment]
----------------------
We use GitHub issues for development related discussions.
Please use the [forum](https://forum.littlevgl.com/) to ask questions.

It's possible to sign in to the forum with your GitHub account... you don't need to make a separate account.
