### ISSUE TITLE
lv_sw_set_on should be lv_sw_on in documentation

### ISSUE THREAD

**Issue by w8jcik** [lvgl/lvgl#118]
https://littlevgl.com/object-types/switch-lv_sw

It seems to be renamed recently.

**Comment by kisvegabor** [comment]
Thank you, fixed!

**Comment by roslovets** [comment]
Not fixed **Switch (lv_sw) Example**.

**Comment by kisvegabor** [comment]
Thank you. I've just fixed it too.
