### ISSUE TITLE
lv_img set src not update

### ISSUE THREAD

**Issue by QQ1113845021** [lvgl/lvgl#1189]
parent: lv_btn *btton;
child: lv_img *img

click btton, img set src 123.png
click btton, img set src 234.png (Not the same as 123.png)

But img doesn't show 234.png

**Comment by embeddedt** [comment]
----------------------
We use GitHub issues for development related discussions.
Please use the [forum](https://forum.littlevgl.com/) to ask questions.

It's possible to sign in to the forum with your GitHub account... you don't need to make a separate account.

**Comment by embeddedt** [comment]
Use the **How-to** category and fill out the template completely. Otherwise we will not have enough information to solve your problem.
