### ISSUE TITLE
8 bit images to be converted to 24 bit for display on this LCD

### ISSUE THREAD

**Issue by Serenechiaa** [lvgl/lvgl#1199]
Hello ladies and gentleman,

I have this issue that I really can't seem to solve. My code is supposed to download an image, convert it to hexadecimal and then process those hexadecimal values with littlevgl's example code "load24bitsimages". However, my code generates the images in terms of a 1 byte (eg. 0x00 format) hexadecimal and the example codes is in 24bit(eg. 0x000000 format). How can I make them compatible? Is there something on Arduino that can convert images to 24 bits instead of the current 8 bits setting? Or is there any other way to link them up together? Thank you. Also, does SD card help in this process?

**Comment by embeddedt** [comment]
----------------------
We use GitHub issues for development related discussions.
Please use the [forum](https://forum.littlevgl.com/) to ask questions.

It's possible to sign in to the forum with your GitHub account... you don't need to make a separate account.
