### ISSUE TITLE
[QUESTION] RESIZING FREELY IMAGE

### ISSUE THREAD

**Issue by Anarakofona** [lvgl/lvgl#120]
Hi,

I want to resize an image but : 
   - it is repeated like mosaïque if the new size is big than the original size
   - it is clipped if the new size is little than the original size

Is there a way to resize the image freely (not scale) without these probleme?

Thank you very much

**Comment by kisvegabor** [comment]
Hi,

for example you have a 100x100 image. And you want it to occupy 200x200 place but keep the original 100x100 sized image on it?

**Comment by Anarakofona** [comment]
No,

For example I have 100 x 100 original image, but I want tu put it on the screen with 75 x 75 or 36 x 36 or 25 x 25 or 144 x 144  or (free sizing it) size. My goal is to resize the image and put it on the screen as resized.

I don't know if it's the same thing that you say in your comment above.

I tried to use lv_obj_set_width(img, 25) and lv_obj_set_height(img, 25) but it will clipp the image.

Thank you

**Comment by kisvegabor** [comment]
I see. Resizing the image to arbitrary size (upscale downscale) in real time is not implemented right now.

You should resize your image with an online or offline tool and use the resized image.
http://picresize.com/

**Comment by Anarakofona** [comment]
Okay, thank you for your help!!

:)

Thank you

**Comment by kisvegabor** [comment]
Your welcome :)

**Comment by Fuzzynetlogic** [comment]
Hi @kisvegabor ,
Is this feature of free scaling supported yet? While porting an application from windows to linux, I came across scaling of images, using stretchBlt function, in various factors. I was hoping zoom option might do the trick. But as mentioned above, it ended up clipping the image. Is there any other order of api function calls to achieve this?

**Comment by kisvegabor** [comment]
Yes, you can [scale the images](https://docs.lvgl.io/8.3/widgets/core/img.html) in the latest version of LVGL but note that it's a quite performance hungry operation.
