### ISSUE TITLE
Plan for the next version

### ISSUE THREAD

**Issue by jason-sophia** [lvgl/lvgl#1200]
hi~
Could you tell us your plan for the next version? 
Which features will be supported？
and when will the new version be released?

**Comment by embeddedt** [comment]
Duplicate of #1132

**Comment by embeddedt** [comment]
----------------------
We use GitHub issues for development related discussions.
Please use the [forum](https://forum.littlevgl.com/) to ask questions.

It's possible to sign in to the forum with your GitHub account... you don't need to make a separate account.
