### ISSUE TITLE
Font sizes

### ISSUE THREAD

**Issue by elgerg** [lvgl/lvgl#1202]
Hi,

Ive looked at:

https://github.com/littlevgl/lvgl/issues/609
https://github.com/littlevgl/lvgl/issues/354
and
https://github.com/littlevgl/lvgl/issues/247

but I'm still not sure what to do here.

I've enabled #define LV_FONT_ROBOTO_28    1 in lv_config.h and added the following into my code:

`    static lv_style_t st;
    lv_style_copy( &st, &lv_style_plain );

    st.text.color = LV_COLOR_WHITE;
    st.text.font = &lv_font_roboto_28;
    lv_label_set_text(label, "22:30");
    lv_obj_set_style( label, &st );
`

but my font size is still tiny. See attached photos.

![lv_font_roboto_16](https://user-images.githubusercontent.com/24628571/65449077-1eeb9f00-de32-11e9-8c2d-31b7694e9c83.jpg)
![lv_font_roboto_28](https://user-images.githubusercontent.com/24628571/65449080-1f843580-de32-11e9-9bfe-6a1c863f302f.jpg)

Is there any way to scale these up so they are 5x to 10x bigger?

Thanks in advance
Alex

**Comment by embeddedt** [comment]
----------------------
We use GitHub issues for development related discussions.
Please use the [forum](https://forum.littlevgl.com/) to ask questions.

It's possible to sign in to the forum with your GitHub account... you don't need to make a separate account.
