### ISSUE TITLE
Rotate image on a canvas with transparent background

### ISSUE THREAD

**Issue by reyno123456** [lvgl/lvgl#1205]
hi, gentleman

to achieve the rotation function, I look over the LittlevGL, found that can use the object “canvas“ to do it, because it have capbility to rotate, while all the object inside the canvas will rotate. in order to rotate the object inside the canvas, we should make the canvas background color same as ourside. while I tried, but still have some aberration, obviously the canvas color is not pure white.

can you help me ?

thanks
Reyno

![image](https://user-images.githubusercontent.com/10916647/65655383-a281d780-e04e-11e9-9afd-550251034b53.png)

**Comment by kisvegabor** [comment]
"Title" means the "Title of the issue" and not your "Job title". :slightly_smiling_face: 

---

The canvas and the image to rotate has to be `LV_IMG_CF_TRUE_COLOR_ALPHA` or `LV_IMG_CF_ALPHA_1/2/4/8BIT` color format.

Here are two example:

Original image: 
![icon](https://user-images.githubusercontent.com/7599318/65659039-57ee6400-e02a-11e9-8af7-4e8c5533c00d.png)

**TRE_COLOR_ALPHA**
![image](https://user-images.githubusercontent.com/7599318/65658863-b49d4f00-e029-11e9-9afd-77ebf1948385.png)
[icon_color.c.zip](https://github.com/littlevgl/lvgl/files/3655930/icon_color.c.zip)

```c
    LV_IMG_DECLARE(icon_color);
    lv_obj_t * canvas = lv_canvas_create(lv_scr_act(), NULL);
    static lv_color_t cbuf[LV_CANVAS_BUF_SIZE_TRUE_COLOR_ALPHA(100, 100)];
    memset(cbuf, 0x00, sizeof(cbuf));
    lv_canvas_set_buffer(canvas, cbuf, 100, 100, LV_IMG_CF_TRUE_COLOR_ALPHA);
    lv_canvas_rotate(canvas, &icon_color, 30, 25, 25, 25, 25);
``` 

**TRE_COLOR_ALPHA**
![image](https://user-images.githubusercontent.com/7599318/65659021-4a38de80-e02a-11e9-80a7-a2b96ddaf3d9.png)

[icon_mono.c.zip](https://github.com/littlevgl/lvgl/files/3655931/icon_mono.c.zip)

```c
    LV_IMG_DECLARE(icon_mono);
    lv_obj_t * canvas = lv_canvas_create(lv_scr_act(), NULL);
    static lv_color_t cbuf[LV_CANVAS_BUF_SIZE_ALPHA_2BIT(100, 100)];
    memset(cbuf, 0x00, sizeof(cbuf));
    lv_canvas_set_buffer(canvas, cbuf, 100, 100, LV_IMG_CF_ALPHA_2BIT);
    lv_canvas_rotate(canvas, &icon_mono, 30, 25, 25, 25, 25);
```

---
We use GitHub Issues for development related discussions.

Please ask your question in the [Forum](https://forumtest.littlevgl.com/). You can simply log in with your GitHub account too.

So I cloce this issue. If you have further question please open a topic in the Forum.
