### ISSUE TITLE
Subpixel rendering of texts

### ISSUE THREAD

**Issue by kisvegabor** [lvgl/lvgl#1210]
In continuation of the[ related topic](https://forum.littlevgl.com/t/subpixel-rendered-font-bitmaps/742) on the Forum.

cc @puzrin

**Comment by kisvegabor** [comment]
@puzrin I've noticed that `box_w` and `adv_w` are 3 times larger. Now I'd like to deal only with rendering and not with subpixel kerning. Do you think it's ok to simply round up the widths? 
E.g. `box_w = 11` :arrow_right: `box_w = 4`?

However, IMO the `ofs_x` should be rounded down.
 E.g. `ofs_x = 4` :arrow_right: `ofs_x = 1`.
What do you think?

**Comment by puzrin** [comment]
I'd suggest to keep things separate. Offsets in in glyphs are for "floating" bitmaps. Instead of inventing fractional offsets, it's enouth to shift bitmap's content (and increase bounding box if needed). Bounding box base corner position can be always integer.

When you receive font with subpixel data, the only difference is that bitmap has 3x density/pixels in selected direction. So, nothing to do with existing offset values.

Explanations above are in context of data structures, not depending on implementation. Is this what you asked about?

**Comment by kisvegabor** [comment]
> I'd suggest to keep things separate. Offsets in in glyphs are for "floating" bitmaps. Instead of inventing fractional offsets, it's enouth to shift bitmap's content (and increase bounding box if needed).

Still not fully clear. So do you suggest if `ofs_x = 4`, skip one pixel and skip the first color channel?

**Comment by puzrin** [comment]
Probably i did not understand your question. I replied about font data.

If you asking about algorythm - i have no experience with those. If you wish to render subpixel font as ordinary one - that's not good idea. 

Proper image downscale needs filtering to keep result sharp. There are tons of reading about such topic in imagemagick docs. I say so as author of https://github.com/nodeca/pica. In short - any simple approach will give bad result, just don't do that.

**Comment by kisvegabor** [comment]
Okay, thanks.
I can deal with it next week.

**Comment by kisvegabor** [comment]
Just quick hacky experiment:
![image](https://user-images.githubusercontent.com/7599318/66133651-51965400-e5f7-11e9-9da1-19c8c910d4ac.png)

![image](https://user-images.githubusercontent.com/7599318/66133672-59ee8f00-e5f7-11e9-8820-fdb1107a68b7.png)

![image](https://user-images.githubusercontent.com/7599318/66133680-5f4bd980-e5f7-11e9-8462-917106c8aef6.png)

**Comment by embeddedt** [comment]
I note that 2, 3, 5, and 6 appear out of place on the keyboard (i.e. too far to the right).

**Comment by kisvegabor** [comment]
> I note that 2, 3, 5, and 6 appear out of place on the keyboard (i.e. too far to the right).

Thank you! Probably I make 1-pixel error in some cases. I'll investigate.

**Comment by pete-pjb** [comment]
Also the spacing of abc button looks a little off.... 
If that is helpful...

**Comment by puzrin** [comment]
@kisvegabor 

I'm not sure it's correct to check subpixel rendering via screenshot. AFAIK a real photo with high resolution needed, to show how things look in your eyes.

Did result on your LCD improved significantly or not?

**Comment by embeddedt** [comment]
@puzrin As far as I know, screenshots captured on Linux simply retrieve the raw values of the logical RGB pixels. Therefore, it shouldn't affect the subpixel rendering.

Here's part of your comment scaled to 400% with no interpolation:

![Screenshot from 2019-10-03 14-40-03](https://user-images.githubusercontent.com/42941056/66154603-d8ddca80-e5eb-11e9-8055-847e364d0686.png)

You'll have to click it to see it at proper size.

**Comment by kisvegabor** [comment]
@embeddedt By zooming into the image the result really won't be better. At first, I just wanted to see the red-ish pixels on the left and blue-ish pixels on the right.

**Comment by kisvegabor** [comment]
@puzrin 
Here is something I don't understand with `ofs_x` in the generated font. 
Both snippets contain only the "ABC" letters.

Normal:
```
    {.bitmap_index = 0, .adv_w = 0, .box_w = 0, .box_h = 0, .ofs_x = 0, .ofs_y = 0} /* id = 0 reserved */,
    {.bitmap_index = 0, .adv_w = 160, .box_w = 11, .box_h = 12, .ofs_x = 0, .ofs_y = 0},   //A
    {.bitmap_index = 43, .adv_w = 160, .box_w = 9, .box_h = 12, .ofs_x = 1, .ofs_y = 0},   //B 
    {.bitmap_index = 77, .adv_w = 160, .box_w = 10, .box_h = 12, .ofs_x = 0, .ofs_y = 0}   //C
```

with LCD flag:
```
    {.bitmap_index = 0, .adv_w = 0, .box_w = 0, .box_h = 0, .ofs_x = 0, .ofs_y = 0} /* id = 0 reserved */,
    {.bitmap_index = 0, .adv_w = 160, .box_w = 33, .box_h = 12, .ofs_x = 1, .ofs_y = 0},
    {.bitmap_index = 106, .adv_w = 160, .box_w = 26, .box_h = 12, .ofs_x = 1, .ofs_y = 0},
    {.bitmap_index = 188, .adv_w = 160, .box_w = 29, .box_h = 12, .ofs_x = 1, .ofs_y = 0}
```

With LCD flag all letters have `ofs_x = 1`. I don't know whether `ofs_x` has 1 px (I guess it is) or 1/3 px resolution but the difference seems odd.

If I manually change the `ofs_x` values the letter spaces are correct.
Original:
![image](https://user-images.githubusercontent.com/7599318/66212499-52de8400-e6be-11e9-977f-a09ee283ddc7.png)

Manually fixed:
![image](https://user-images.githubusercontent.com/7599318/66212459-3cd0c380-e6be-11e9-978b-e9fe7f8c416f.png)

Do you have any idea?

**Comment by puzrin** [comment]
[Here](https://github.com/littlevgl/lv_font_conv/blob/master/lib/freetype/index.js#L167-L242) is main draw code.

We just extract bitmap & coords without change, those are integer. May be in subpixel mode we should care about `lsb_delta` & `rsb_delta`? I have no idea and would like to avoid diving into C api of FT. If you say exactly what should be done - that will be updated.

**Comment by puzrin** [comment]
May be `ofs_NN` of subpixel dimention is in `1/3` of pixels too?

**Comment by kisvegabor** [comment]
I have no idea. It might have 1/3 or 1 resolution but IMO it shouldn't be the same for the 3 gylphs. I've [asked](https://forum.littlevgl.com/t/subpixel-rendered-font-bitmaps/742/25?u=kisvegabor) *Jon_Smirl* from the Forum to comment on this.

**Comment by puzrin** [comment]
@kisvegabor please use version from master:

- There was a bug with missed X sign.
- AdvanceWidth missed fractional part (not fatal, but kerning could be affected).
- We added a lot of FreeType glyph properties into dump. That should help to check if something goes wrong or incorrect property used.

I hope, that should fix all issues you asked about. X seems to be in pixels.

**Comment by kisvegabor** [comment]
@puzrin 
Thank you for the update! It seems it has solved the issue!
![image](https://user-images.githubusercontent.com/7599318/66480266-9100ec80-ea9e-11e9-9656-fab98dc5a19a.png)

**Comment by kisvegabor** [comment]
I've pushed the code to `feat-subpixel`. Now I set the type of font manually in the [draw function](https://github.com/littlevgl/lvgl/blob/7f7abe9a9336aa681d8720e9db96d5b6654e6eb5/src/lv_draw/lv_draw_basic.c#L304).

@puzrin Can you add a flag to [lv_font_t](https://github.com/littlevgl/lvgl/blob/68c752ab5097433bba30fd08723f0d2fae288f1f/src/lv_font/lv_font_roboto_12.c#L1800)? E.g. `subpixel = 1`.

For backward compatibility, it might be useful to add this option only if it's `1`. (Fields are initialized to 0 by default)

**Comment by puzrin** [comment]
> Can you add a flag to [lv_font_t](https://github.com/littlevgl/lvgl/blob/68c752ab5097433bba30fd08723f0d2fae288f1f/src/lv_font/lv_font_roboto_12.c#L1800)? E.g. `subpixel = 1`.

What about vertical orientation? There are 2 options, `--lcd` & `--lcd-v`.

**Comment by kisvegabor** [comment]
Do you insists on `--lcd-v`? I'd be happy with only `--lcd` too.

**Comment by embeddedt** [comment]
@kisvegabor I think `--lcd-v` is necessary, because, depending on the orientation of the display, there might be a need to have vertical subpixel rendering.

**Comment by kisvegabor** [comment]
Correct me if I'm wrong but as I see there are two options:
1. "RGB" in lines: we can have subpixel rendering horizontally
2. "RGB" in columns: we can have subpixel rendering vertically (IMO not really important and more complicated because lines should be buffed)

So we cannot do horizontal sub-pixel rendering on vertical RGB display with `--lcd-v`.

**Comment by puzrin** [comment]
> Do you insists on `--lcd-v`? I'd be happy with only `--lcd` too.

I do not insist on implementation. But i would insist on reserving value in data design. Since it's technically possible to have at least 2 types of subpixels layout (+ none), this should be expressed in lvgl writer somehow.

For bin writer i planned store this info in "compression" byte, but now tend to add independent header field (this change will be breaking).

**Comment by embeddedt** [comment]
> So we cannot do horizontal sub-pixel rendering on vertical RGB display with `--lcd-v`.

Right. It would have to be vertical sub-pixel rendering.

**Comment by puzrin** [comment]
Landed non-breaking changes to 0.3.0 release of lv_convert, and pushed the rest to dev branch https://github.com/littlevgl/lv_font_conv/commits/dev

@kisvegabor, i need your decision about `subpixel` field size, to update lvgl writer. I'd suggest make it 2 bits wide at least.

**Comment by jonsmirl** [comment]
Don't confuse portrait and landscape mode LCDs, both of those want horizontal subpixel rendering. The only time you would use vertical subpixels is if you mounted the LCD wrong or if your display rotates. Vertical subpixel rendering has little visible impact.  Check your display with a microscope and make sure the color bars are running horizontally, if they are you have it mounted correctly.

**Comment by jonsmirl** [comment]
The current code is looking great. It should be sufficient for most users. As far as I know this is the first implementation of subpixel rendering for microcontrollers.

If you want to improve it more -- play around with higher order filtering functions. These help but the improvements are not huge.

Implement subpixel spacing and kerning. This doesn't improve legibility but it lets you pack more characters onto a tiny display without loss of legibility.

**Comment by jonsmirl** [comment]
I also recommend asking for help on the Freetype list. I just dabble in this stuff, the people on the Freetype list have PhD's in it.  For example the Freetype PhD's will tell you to set the gamma of your LCD panel into the filter function. The gamma is constant and it may be on the LCD datasheet. If the filter function knows the gamma it can do a much better filter.  When you see halos around the letters on the desktop, you probably have the gamma of the monitor set wrong in the Xserver. That problem is disappearing now with monitor EDIDs that contain the gamma, but embedded systems don't have EDIDs. Your code is at 90% performance, these are just details to take it up the highest possible levels of legibility, they are not required.

Random article on LCD gammas....
https://www.eizo.be/knowledge/monitor-expertise/gamma-values-of-lcd-monitors/

**Comment by kisvegabor** [comment]
@puzrin 
Let's use `.subpx = LV_FONT_SUBPX_NONE/HOR/VER/BOTH`. 
See the commit: 10b3463a

@jonsmirl 
Thank you for the hints!

**Comment by puzrin** [comment]
@kisvegabor please confirm final variants:

1. Nothing for no subpixels (rely on zero init by default)
2. Add `subpixel = LV_FONT_SUBPX_HOR` for `--lcd`
3. Add `subpixel = LV_FONT_SUBPX_VER` for `--lcd-v`

Correct?

**Comment by puzrin** [comment]
@kisvegabor https://github.com/littlevgl/lv_font_conv/commit/f95909bb67336b4c5f20c8caaeec838f898eaf63

Please check.

**Comment by kisvegabor** [comment]
@puzrin Works great using the `dev` branch of the converter. I updated `lvgl` and merged `feat-subpx` into `dev-6.1`.

As the feature is added I close this issue. Thank you very much for your contribution. :+1:

**Comment by puzrin** [comment]
@kisvegabor i had no chance to check subpixel rendering on device with LCD. What is your opinion? Did quality really improved, at least for black on white and white on black? What about perfomance? 3x slower?

**Comment by kisvegabor** [comment]
I've just tested it on STM32F429 Discovery. Here are some photos: 
[subpx.zip](https://github.com/littlevgl/lvgl/files/3746391/subpx.zip)

They have very high resolution so if you zoom in you can see the RGB channels.

To my eyes, the subpixel rendered font looked a little bit better but there wasn't a huge difference. However this display has a relatively large DPI (2.4", 320x240), so probably it's not a good target to demonstrate the advantages of subpixel rendering.

Regarding the speed, the UI shown in the images:
- normal rendering: 36 ms
- subpixel rendering: 56 ms

**Comment by puzrin** [comment]
Hm. It's strange, but difference is really not as big as expected. May be, difference should be more visible with  12 px font?

Hight DPI is 400+, your display is far from it. Should be good candidate to demonstrate subpixel rendering.

**Comment by kisvegabor** [comment]
Here are some more photos  with 10px and 6px fonts. Still can't see a huge difference
[sub_px_10.zip](https://github.com/littlevgl/lvgl/files/3746427/sub_px_10.zip)
[sub_px_6.zip](https://github.com/littlevgl/lvgl/files/3746429/sub_px_6.zip)

10px was readable in all cases.
6px was not readable in any of the cases.

By high DPI I meant compared to other displays in this class. I saw a lot of 320x240 display in 3.5" size (114 DPI) where you can easily see the pixels. On this display, it's very hard to spot the pixels.

**Comment by puzrin** [comment]
Hm... too many halos. Probably, better display gamma correction heeded on alpha blend.

Could you do last check? 10px negative - white letters on black background. May be that will hide some defects.

**Comment by kisvegabor** [comment]
Here it is. 
[black_bg.zip](https://github.com/littlevgl/lvgl/files/3746715/black_bg.zip)

Subpx looks better in some cases, especially where there is no space between letters. E.g. "sed" in the second line.

However in general -at least on this screen - not that much better.

**Comment by jonsmirl** [comment]
It is likely worthwhile to discuss this on the freetype list. Those guys do this stuff for their jobs and they are experts at it.  My guess is that the filter function on the subpixel display is not working quite right. The color halos on 'N' should not be visible.

There is a way to check your code. Have freetype generate fully subpixel rendered bitmaps of the same text. Then compare your pixel vales to theirs for random letters. That will show you where things aren't quite right.

The general algorithm appears to be working, you may simply have a bug somewhere. And where there is a bug the whole effect doesn't work.

Edit -- get a cheap USB microscope so that you can see the individual pixels.Something not right in 'N'.  Your Xserver is doing subpixel rendering, note that this 'N' does not have a color halo.

**Comment by puzrin** [comment]
@kisvegabor negative screen seems optimal for experiments. I remembered one more check. If you properly count fractional width (cursor position shift) and kerning - try `--autohint-strong`. If it will not break everything again, difference should be notable.

**Comment by kisvegabor** [comment]
@puzrin I can do it tomorrow.

**Comment by puzrin** [comment]
As far as i understand, with `--autohint-strong` there may be ~ 1 subpixel positioning error (1/3 px), because we do not process [lsb_delta](https://www.freetype.org/freetype2/docs/reference/ft2-base_interface.html#ft_glyphslotrec). Vusually, that may look as a bit broken kerning, but not as horrible as before subpixel mode (1 px error looks very bad).

If you find result worth to use, that error can be compensated almost to zero in convertor (instead of `lsb_delta` we can shift bitmap with 1/3 px precision)

**Comment by jonsmirl** [comment]
I just checked out the black background sample.  I zoomed in on the letter 'm' and I see a red band in front of the 'm'.  That can't be right. I should see a blue band, not a red one.  This display appears to look like this:  RxxRGB it should xxBRGB. in the photo.

What's the easiest way to build a sample program with this enabled? I have a USB microscope and I can take pictures at 50x magnification. For hardware I have ESP32 with ILI9341 display. Or Unix with framebuffer.

C app is fine. I using the micropython build for my main work which is why I have not closely tracked this.

I took picture of current code (not subpixel code)  which only dims full pixels and annotated it with approximate glyph outline. You can see that many sub-pixel are turned on that should not be on. I can take same picture using the new code.  This is from ILI9341 on ESP32. ![annotate](https://user-images.githubusercontent.com/14943/67301678-bbe73980-f4bd-11e9-9db5-7c66e57d0bbd.png)
When looking at this note that the subpixels are being use in RGB groups and all subpixels have same brightness in each group.  Background is dark blue so it is on a little. It is the button from the 'Hello World' example.

**Comment by kisvegabor** [comment]
@puzrin 
Here are the autohinted images: 
[autohint.zip](https://github.com/littlevgl/lvgl/files/3760647/autohint.zip)


@jonsmirl 
Just set [LV_SUBPX_BGR](https://github.com/littlevgl/lvgl/blob/dev-6.1/lv_conf_template.h#L368) to 1 in your lv_conf.h

**Comment by jonsmirl** [comment]
It worn't compile on ESP32

CC build/lvgl/src/lv_draw/lv_draw_basic.o
/home/jonsmirl/aosp/esp32_ili9341/components/lvgl/src/lv_draw/lv_draw_basic.c: In function 'lv_draw_letter':
/home/jonsmirl/aosp/esp32_ili9341/components/lvgl/src/lv_draw/lv_draw_basic.c:420:37: error: 'struct <anonymous>' has no member named 'green'
                         res_color.ch.green = (uint16_t)((uint16_t)txt_rgb[1] * font_rgb[1] + (bg_rgb[1] * (255 - font_rgb[1]))) >> 8;
                                     ^


Also my LCD is RGB, not BGR.

**Comment by puzrin** [comment]
> Here are the autohinted images:

I don't see expected difference. No ideas what to do. Anyway, kick me if need more convertor updates to support subpixels.

**Comment by jonsmirl** [comment]
I need to get this working and use the microscope on it. Once you see everything with microscope the bugs will be obvious. Right now I don't think it is working right due to those color halos in the photos.

**Comment by kisvegabor** [comment]
> It worn't compile on ESP32

@jonsmirl I've fixed it in `dev-6.1`.

**Comment by jonsmirl** [comment]
This look almost right. Something not quite right with background blend math.
![Webcam-1571921809](https://user-images.githubusercontent.com/14943/67487742-7735dc80-f63c-11e9-9c27-20fb7750def1.png)

See the areas I circled, those pixels should be on.
![Webcam-1571921809](https://user-images.githubusercontent.com/14943/67488636-258e5180-f63e-11e9-9adc-892c75bd80f1.png)

Let me recompile demo with black background, that may make it easier to see. That is the standard blue background.

With black background.
![Webcam-1571923452](https://user-images.githubusercontent.com/14943/67489778-1c9e7f80-f640-11e9-943e-611264b4761c.png)

**Comment by kisvegabor** [comment]
@jonsmirl 
The algorithm works like this:
```
 blue = (txt_blue * font_blue_opa + bg_blue * (255 - font_blue_opa)) >> 8;
```

Does it look correct?

It's a little bit hard to decide but it seems on your images only blue channels are missing. Am I see it right?

**Comment by jonsmirl** [comment]
Can you print out the subpixel values you compute for a white letter 'W' blended with a black background? They should match the input 3x expanded bitmap.

**Comment by jonsmirl** [comment]
This is white 'L' on black background. I don't understand why it is six subpixels at half brightness.
![Webcam-1571924816](https://user-images.githubusercontent.com/14943/67491709-558c2380-f643-11e9-8bf4-b737991aee6a.png)

Input bitmap should look something like:
RGBRGBRGB
001111100

How does that end up with half bright subpixels?

**Comment by puzrin** [comment]
@jonsmirl if your question is about convertor:

- use code from `dev` branch
- add `--lcd` key

**Comment by jonsmirl** [comment]
Isn't the 3X expanded font checked into the 6.1-dev branch? It is not obvious to me if it is.

**Comment by puzrin** [comment]
Those looks old (NOT 3x).

See https://github.com/littlevgl/lv_font_conv/blob/dev/lib/writers/lvgl/lv_table_head.js#L73. There should be line `.subpx = LV_FONT_SUBPX_HOR`

**Comment by jonsmirl** [comment]
That explains why it is not working.

**Comment by jonsmirl** [comment]
We probably need smarter font logic. Always compile in the subpixel code, it is tiny.  When displaying look at the header of each font. If the font is subpixel enabled, then use it with the subpixel code. Otherwise render normally.

**Comment by embeddedt** [comment]
@jonsmirl I think you need `dev-6.1` from https://github.com/littlevgl/lvgl and the `dev` branch from https://github.com/littlevgl/lv_font_conv.

**Comment by puzrin** [comment]
> I'll see if I can figure out how to add them to my build.

If you copy-pasted lib folder, you can replace font files with new ones. Dirty but simple.

**Comment by jonsmirl** [comment]
Now it is working, but something is inverted. 
![Webcam-1571935611](https://user-images.githubusercontent.com/14943/67507147-5e3d2380-f65c-11e9-91a4-c933b6527d71.png)
That is the opposite of what it should be doing. That's why you are seeing color halos
Text is "List" on black background. I made fonts like this...

jonsmirl@ares:/aosp/lv_font_conv$ ./lv_font_conv.js --font Roboto-Regular.ttf -r 0x20-0x7F  --size 22 --format lvgl --bpp 3 --lcd  -o lv_font_roboto_22.c
jonsmirl@ares:/aosp/lv_font_conv$ ./lv_font_conv.js --font Roboto-Regular.ttf -r 0x20-0x7F  --size 12 --format lvgl --bpp 3 --lcd  -o lv_font_roboto_12.c
jonsmirl@ares:/aosp/lv_font_conv$ ./lv_font_conv.js --font Roboto-Regular.ttf -r 0x20-0x7F  --size 16 --format lvgl --bpp 3 --lcd  -o lv_font_roboto_16.c
jonsmirl@ares:/aosp/lv_font_conv$

Is this code BGR and I have an RGB display?

**Comment by puzrin** [comment]
Convertor calls looks correct. If you have issues with speed regressions - try `--bpp 4 --no-compress --force-fast-kern-format`

Photo looks like everything except 0 & 255 is inverted.

**Comment by jonsmirl** [comment]
I figured out that I needed to remove #define LV_SUBPX_BGR 1
Here is subpixel 'W'
![Webcam-1571938151](https://user-images.githubusercontent.com/14943/67510194-7748d300-f662-11e9-9851-ca9b4c3e0844.png)

Here is non-subpixel 'W'
![annotate](https://user-images.githubusercontent.com/14943/67510216-80d23b00-f662-11e9-810b-2528553ab946.png)


List
![Webcam-1571938375](https://user-images.githubusercontent.com/14943/67510377-d4448900-f662-11e9-957c-31f1cc79bee9.png)

So it looks like it is working correctly! There are still some visible artifacts which can probably addressed with a higher order filter.

**Comment by puzrin** [comment]
@jonsmirl with what i see on screenshots, visual difference should be huge. Do you see it in normal scale?

**Comment by jonsmirl** [comment]
Here is photo from phone. This is cheapo 320x240 LCD. The word 'Chart' not in complete focus. It is  hard to get everything in perfect focus.

![IMG_20191024_134631](https://user-images.githubusercontent.com/14943/67512617-34d5c500-f667-11e9-8d03-de49ac377e5a.jpg)

**Comment by jonsmirl** [comment]
There is an obvious improvement vs non-subpixel. Here is not subpixel. The difference is much more visible to human eye than camera.  My cell phone camera is processing the picture and it looks better in photo than it does in real life.  Zoom in on "Write" and you can see how much clearer.

![IMG_20191024_141235](https://user-images.githubusercontent.com/14943/67513602-28eb0280-f669-11e9-9cd0-cf710698cae5.jpg)

**Comment by jonsmirl** [comment]
Don't draw an opinion based photos. The camera is making the non-subpixel version look better than it really is. The camera processing is removing the brightness variations in various parts of the letters. I can easily see on display, but it is missing in photo.

To my human eye, the subpixel display is far better than the old version. I do see some slight color fringing on 'i' which can be removed with a filter.The biggest change is that the brightness across the glyph is now uniform. With old code some parts of glyph were brighter than others and that was very noticeable.

**Comment by puzrin** [comment]
@jonsmirl yes, difference is notable. Could you add `--autohint-strong` (only in subpixel mode)? It controls `FT_LOAD_TARGET_LIGHT` & `FT_LOAD_TARGET_NORMAL` flags.

https://github.com/littlevgl/lv_font_conv/blob/master/lib/freetype/index.js#L194-L195

I'd like to understand, will difference be notable and will it break kerning significantly (without subpixel mode `FT_LOAD_TARGET_NORMAL` is not very useful)

**Comment by jonsmirl** [comment]
This is with strong autohint on 'W'. Not sure what is going on, I have to enable LV_SUBPX_BGR to get this one to display right.
![Webcam-1571943902](https://user-images.githubusercontent.com/14943/67517138-e842b780-f66f-11e9-98d6-1fa980127ceb.png)

I don't see in difference in 'W'.  Typically auto-hint does not reveal itself until font point size much lower.

**Comment by jonsmirl** [comment]
So in demo.c it makes a tabview with "Write List Chart" text.
How do I change the font size? Is default 12 or 16pt?

If I push the point down below 10 autohint will start to show up.

**Comment by jonsmirl** [comment]
What autohint does is start replacing the font glyphs with human designed specific pixels when the point size gets tiny. For example it ensures that the arm on an 'r' does not disappear.  And it makes sure a 'k' does not turn into an 'h'. Things like that.

**Comment by embeddedt** [comment]
> How do I change the font size? Is default 12 or 16pt?

You have to reconvert the font. You'll need to use the offline font converter as the online one hasn't been updated to support this feature.

**Comment by jonsmirl** [comment]
This is subpixel plus strong autohint and tiny points. Even tiny 7pt is still readable.
9pt
![IMG_20191024_165303](https://user-images.githubusercontent.com/14943/67525011-dc5ef180-f67f-11e9-8b40-efd401c8e568.jpg)
8pt
![IMG_20191024_165532](https://user-images.githubusercontent.com/14943/67525043-ebde3a80-f67f-11e9-8c6b-cadaceea40d3.jpg)
7pt
![IMG_20191024_165918](https://user-images.githubusercontent.com/14943/67525089-ff89a100-f67f-11e9-9347-bba01b6093e8.jpg)

**Comment by kisvegabor** [comment]
On my TFT there wasn't a huge difference. But good to know that it's not the case on other TFTs.

In `v6.1` I'll add a built-in font with subpixel rendering to show this feature.

Do you have any idea about updating filtering to avoid color bleeding?

**Comment by puzrin** [comment]
@kisvegabor https://github.com/littlevgl/lvgl/issues/1210#issuecomment-546060087 - it's strange why @jonsmirl had to enable `LV_SUBPX_BGR` (and in previous post he mentioned disabling that). Display on photos has RGB subpixels (as majority of displays).

**Comment by jonsmirl** [comment]
The lower the DPI of the display, the more subpixel rendering helps. The LCD I am using is 96DPI and it makes an obvious difference.

I only had to turn BGR on when I turned on strong autohint. Maybe the fonts not getting generated right?  Autohint is only needed on fonts below 10pt. Plus on below 10pt kerning doesn't really work so there is no conflict.

**Comment by puzrin** [comment]
I don't know how freetype output should be processed. I just send options and extract alpha bitmap. IMO if difference is not significant, we can forget about stronger autohinting and use light + subpixels.

In this scope it could be useful to optimize decompressor (fixing it will add notable value). [Here](https://github.com/littlevgl/lv_font_conv/issues/22#issuecomment-531277910) i explained details.

**Comment by jonsmirl** [comment]
Font's below 10pt are probably of limited usefulness on an embedded LCD. Main use would likely be displaying license info in tiny text so that it all fits. A font point is 1/72th in. So a 10pt font should be 10/72in high. If you don't know the DPI of the display you can't calculate this.

Also note that the way we are doing things, a 10pt font on a 200DPI screen is half the size of a 10pt font on a 100DPI screen.  Your desktop gets the screen DPI from the EDID. Since it knows the DPI it can make the 10pt font size consistent between the two screens. All of this is too complex for an embedded LCD that can't be swapped.  What we have now is fine.

When someone complains that 10pt is not the right size, now you have the answer - we are working in pixels instead of inches.

**Comment by kisvegabor** [comment]
> I only had to turn BGR on when I turned on strong autohint. Maybe the fonts not getting generated right? Autohint is only needed on fonts below 10pt. Plus on below 10pt kerning doesn't really work so there is no conflict.

I also don't know what might happen. It might be really worth a question on FreeType's mailing list.

> In this scope it could be useful to optimize decompressor (fixing it will add notable value). Here i explained details.

True, subpixel rendering makes compression effective for normal-sized fonts too. The current algorithm is working but probably can be optimized to make it faster. However, I'd like to immerse in other things now. I leave it open for contribution :slightly_smiling_face:

**Comment by jonsmirl** [comment]
If there are plans to make lvgl do auto layout, then it needs to learn about display DPI.  For example if you have two 6in square LCDs and one is 200DPI and the other is 100DPI, auto layout can not make them look the same without knowing the DPI.

**Comment by kisvegabor** [comment]
@jonsmirl 
There is an `LV_DPI` config in `lv_conf.h`. You can use it to set the paddings of layouts (e.g. `style.body.padding.hor = LV_DPI / 2`). You can also use it to set the sizes (e.g. `lv_obj_set_size(btn, LV_DPI * 2, LV_DPI)`). LittlevGL already uses `LV_DPI` to set the default sizes/values.

However, the fonts will be really smaller.

**Comment by jonsmirl** [comment]
LV_DPI needs to scale the point size too and then select the closest matching font.

How about swapping all of the default fonts for the subpixel ones in release 6 and see if anyone notices? This is trivial to undo, include the old fonts in the build and add a release note saying to copy them back if there are problems.

**Comment by kisvegabor** [comment]
using subpixel fonts has cost in two regards:
- they are 3 times larger in size
- they are ~50 % [slower to render](https://github.com/littlevgl/lvgl/issues/1210#issuecomment-544114457)

My idea is to add a subpixel version too for the 12px built-in font to make it easier for people to test.

**Comment by jonsmirl** [comment]
They are not three times larger if you are replacing an 8b gray scale with a 3b (x3=9b) subpixel.  And are they really 3X larger with compression?

A 2b subpixel (6b total) will likely look better than a 8b gray scale. And it should be smaller.

**Comment by embeddedt** [comment]
> LV_DPI needs to scale the point size too and then select the closest matching font.

@jonsmirl Fonts are not chosen by point size in LittlevGL; you manually have to choose the font you want. So we don't really operate in terms of point size (like FreeType and other libraries do).

**Comment by kisvegabor** [comment]
> They are not three times larger if you are replacing an 8b gray scale with a 3b (x3=9b) subpixel. And are they really 3X larger with compression?

@jonsmirl If you set bpp=3 in the font converter then it will generate "3b (x3=9b) subpixel" as you mentioned. However, it's really 3 times larger than 3b/px.

>  And are they really 3X larger with compression?

With fonts with more pixels, the compressor becomes more effective. However, decompressing increases rendering time further.

> A 2b subpixel (6b total) will likely look better than a 8b gray scale. And it should be smaller.

You can try it out by setting bpp=2

**Comment by jonsmirl** [comment]
You should compare 3bpp subpixel to 8bpp normal.  And then compare 1bpp subpixel to 3bpp normal. Those pairs have similar accuracy.  It is not a good comparison between 8bpp normal to 8bpp subpixel, doing that is gives much higher fidelity to the subpixel case -- it is not an equal comparison. 

I suspect the equivalent sub-pixel fonts may actually be a tiny bit smaller.

**Comment by puzrin** [comment]
> They are not three times larger if you are replacing an 8b gray scale with a 3b (x3=9b) subpixel.

Nobody uses 8b here. 4b max. > 4b does not give visual difference. 3b is enougth IMO.

> And are they really 3X larger with compression?

With compression those are ~ 2x larger. Compression ratio increases on size grow. To see almost exact size for your particular case - run convertor with binary output and try with and without `--no-compress`.

> A 2b subpixel (6b total) will likely look better than a 8b gray scale. And it should be smaller.

I would not recommend 2b. Too bad precision. IMO 3b is optimal.

**Comment by jonsmirl** [comment]
It is not really 2b of precision, it is 2b per subpixel or 6b for the whole pixel.

**Comment by embeddedt** [comment]
> 6b for the whole pixel.

That's still more than 4b for the whole pixel.
