### ISSUE TITLE
6.1 broken PIO build - bad paths in updated fonts

### ISSUE THREAD

**Issue by puzrin** [lvgl/lvgl#1215]
- in [6.0](https://github.com/littlevgl/lvgl/blob/master/src/lv_font/lv_font_roboto_12.c#L1) - relative, works in PIO
- in [6.1](https://github.com/littlevgl/lvgl/blob/dev-6.1/src/lv_font/lv_font_roboto_12.c#L1) - requires specific folders structure, doesn't work in PIO.

https://github.com/littlevgl/lvgl/blob/master/scripts/built_in_font/built_in_font_gen.py seems your build script misses `sed` call to replace path with correct one.

**Comment by embeddedt** [comment]
I think this was an intentional change. @kisvegabor?

**Comment by puzrin** [comment]
I think not. https://github.com/littlevgl/lv_font_conv/blame/master/lib/writers/lvgl/lv_font.js#L37 that's default from convertor, the same as from been added.

**Comment by kisvegabor** [comment]
It should be `../../lvgl.h` be ensure that the internal files can include what they need without any further project configuration.

`built_in_font_gen.py` should generate a font similar to built-in ones but used externally by the user. 
There `lvgl/lvgl.h` is fine.

**Comment by puzrin** [comment]
Switched to 6.1-dev. Now works.
