### ISSUE TITLE
[dev-6.1] `lv_win_content_size` is unimplemented

### ISSUE THREAD

**Issue by embeddedt** [lvgl/lvgl#1216]
**Describe the bug**

Self-explanatory. It seems that this function wasn't implemented fully.

https://github.com/littlevgl/lvgl/blob/c1e0faf440e40605f5e96cbe73d137fc21e322ba/src/lv_objx/lv_win.c#L251-L257

**To Reproduce**

Any code using this function and expecting it to work won't work properly, as the function won't have any noticeable effect on the window's size.

**Comment by kisvegabor** [comment]
Correct somehow I've missed adding `lv_obj_Set_size` at the end. :sweat_smile: 

Fixed in abb480f9
