### ISSUE TITLE
 the screen cannot be rotated by 90°

### ISSUE THREAD

**Issue by winny2809** [lvgl/lvgl#1222]
Trying to invert the coordinates, the screen is not rotated 90 °.
How can you go about getting vertical graphics?

> # Important: issues that don't use this template will be ignored/closed.

**Describe the bug**

**To Reproduce**

Please provide a small, independent code sample that can be used to reproduce the issue. Ideally this should work in the PC simulator unless the problem is specific to one platform.

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by embeddedt** [comment]
----------------------
We use GitHub issues for development related discussions.
Please use the [forum](https://forum.littlevgl.com/) to ask questions.

It's possible to sign in to the forum with your GitHub account... you don't need to make a separate account.
