### ISSUE TITLE
The Chinese font shows normal when the bpp set to 1. but when the bpp greater than 1, it shows abnormal

### ISSUE THREAD

**Issue by incity** [lvgl/lvgl#1223]
i use these two command:
    lv_font_conv --font chinese_ui.ttf -r 0x9009 --size 48 --format lvgl --bpp 1 -o stsong_30.c
    lv_font_conv --font chinese_ui.ttf -r 0x9009 --size 48 --format lvgl --bpp 2 -o stsong_30.c
![image](https://user-images.githubusercontent.com/7846605/66698557-8d28d080-ed11-11e9-9ee0-8ef69896889b.png)
![image](https://user-images.githubusercontent.com/7846605/66698579-b47f9d80-ed11-11e9-8a1d-7519dd73a5f3.png)
![image](https://user-images.githubusercontent.com/7846605/66698679-7afb6200-ed12-11e9-8c31-e520c9bfe177.png)
![image](https://user-images.githubusercontent.com/7846605/66698681-8189d980-ed12-11e9-8cfc-357425a88660.png)

**Comment by puzrin** [comment]
If you are on 6.0, add `--no-compress`, or switch to 6.1-dev. Convertor defaults are a bit ahead of lvgl releases.

**Comment by incity** [comment]
> If you are on 6.0, add `--no-compress`, or switch to 6.1-dev. Convertor defaults are a bit ahead of lvgl releases.

very thanks, i try it, it shows ok, but it works only in a small range of unicode. when i choose a big range(e.g. 0x4E00-0x9009 or 0x4E00-0x9FA5), it also shows abnormal.

here is my command line:
lv_font_conv --font chinese_ui.ttf -r 0x4E00-0x9009 --size 48 --format lvgl --bpp 2 --no-compress -o stsong_30.c

**Comment by puzrin** [comment]
Those effects are not related anyhow. I'd suggest you to create a reproducible sample, because described command is not enougth. Also try this things:

- use `--format dump` and check if dumped images are correct or not
- try narrow down your example to case when it still works and stop works after add one more glyph.

**Comment by incity** [comment]
thanks again, the dumped images are correct.

![image](https://user-images.githubusercontent.com/7846605/66725700-3f25e100-ee67-11e9-8b9d-96b579544b57.png)
![image](https://user-images.githubusercontent.com/7846605/66725712-5bc21900-ee67-11e9-9364-7280e436841d.png)
![image](https://user-images.githubusercontent.com/7846605/66725690-261d3000-ee67-11e9-87b2-6d90521ef9ff.png)

**Comment by puzrin** [comment]
Prepare a test repo please, with your font and commands to execute. Ideally, this ones:

- with max range, still working correctly
- with max range + 1, when glyph become bad (will in be only one bad glyph or all revious too?).

**Comment by incity** [comment]
> Prepare a test repo please, with your font and commands to execute. Ideally, this ones:
> 
> * with max range, still working correctly
> * with max range + 1, when glyph become bad (will in be only one bad glyph or all revious too?).

glyph become bad from 0x5669.  range 0x4e00-0x5668 is ok.

![image](https://user-images.githubusercontent.com/7846605/66726396-b8bfce00-ee6b-11e9-9f9e-ef4ca0931d87.png)
![image](https://user-images.githubusercontent.com/7846605/66726412-d55c0600-ee6b-11e9-8d41-9879706ec08e.png)
![image](https://user-images.githubusercontent.com/7846605/66726426-e4db4f00-ee6b-11e9-8fa6-ad7672c188bd.png)

**Comment by puzrin** [comment]
@incity please, create a test repo as requested, that's important, because we need reproduce situation locally.

**Comment by incity** [comment]
> @incity please, create a test repo as requested, that's important, because we need reproduce situation locally.


i just use the sample code in lvgl(lv_linux_frame_buffer\lv_examples\lv_tests\lv_test_theme)
and modify the code in lv_test_theme_2.c from line 135(sb_create function)
[lv_test_theme.zip](https://github.com/littlevgl/lvgl/files/3722756/lv_test_theme.zip)

**Comment by incity** [comment]
@puzrin there is a overflow in lv_font_fmt_txt_glyph_dsc_t struct. i remove the bit field. and it shows ok now.
![image](https://user-images.githubusercontent.com/7846605/66732748-b0798a00-ee8f-11e9-9f4c-e9914c1a96cd.png)
![image](https://user-images.githubusercontent.com/7846605/66732802-e0289200-ee8f-11e9-941d-c03ae20d6e63.png)

**Comment by embeddedt** [comment]
> BTW, if you have resources for such big fonts, why do you use lvgl then? Seems you can run qt + freetype.

It's probably for at least one of these reasons:

* LittlevGL is more lightweight (and therefore faster).
* It might be easier to work with for simple GUIs.
* Maybe @incity has already used LittlevGL on another platform before.

**Comment by incity** [comment]
i do like the ui style of the littlevgl, it more like android and ios, im not very familiar with QT, maybe it can also realize that, but, i dont know how much work it will take.
do u have any suggestions?

**Comment by puzrin** [comment]
> LittlevGL is more lightweight (and therefore faster).

This 2 statements are not related. For example, lvgl has no commands abstraction layer (see nuklear for example), which can be effectively done at gpu if exists. More simple != more fast.

> do u have any suggestions?

I can not decide what is better for you. In my current projects i use LVGL due memory constrains.

**Comment by kisvegabor** [comment]
@incity 
With a lot of characters, you should enable [LV_FONT_FMT_TXT_LARGE](https://github.com/littlevgl/lvgl/blob/master/lv_conf_template.h#L281).

**Comment by embeddedt** [comment]
> More simple != more fast.

You need more context to effectively make a statement like that.

On a platform without a dedicated GPU, something that does simpler graphics operations will be faster. On a platform with a GPU, there are probably advantages to the complexity (because it will be handled by the GPU).
