### ISSUE TITLE
Mouse scroll can not make an effect?

### ISSUE THREAD

**Issue by xsjqqq123** [lvgl/lvgl#1224]
Hi,
  I'm working for a video reocrd device, and now to find a suitable UI for it. 

  I test online web demo. Very impressive UI!  But some widgets can only drag( Page\Table), Our device have no touch screen, how can I replace it with mouse scroll?

  And, another problem confuse me : how can I make realize follow table?(add special checkbox)
![image](https://user-images.githubusercontent.com/8264121/66747559-6c01e480-eeb7-11e9-9e54-aa1cb8652ae7.png)

**Comment by embeddedt** [comment]
----------------------
We use GitHub issues for development related discussions.
Please use the [forum](https://forum.littlevgl.com/) to ask questions.

It's possible to sign in to the forum with your GitHub account... you don't need to make a separate account.
