### ISSUE TITLE
Nemo theme's bar widget show abnormal.

### ISSUE THREAD

**Issue by incity** [lvgl/lvgl#1235]
Nemo theme's bar widget show abnormal.
other widgets like switch button has the same problem during animation.

![image](https://user-images.githubusercontent.com/7846605/67470681-bc7bfd80-f680-11e9-8950-0372c2a44aaa.png)

**Comment by kisvegabor** [comment]
It's the known issue of the "bar-like" objects.

I'm thinking/working on a new draw system for LittelvGL which should address it too. 
The solution will be the same as for #1088

So let's use that issue to discuss it.
