### ISSUE TITLE
When will the 5.1  release approximately？

### ISSUE THREAD

**Issue by sirius65535** [lvgl/lvgl#124]
I can‘t wait for it   :P

**Comment by kisvegabor** [comment]
Hi,

Now I'm working to release the most important components:
- Sparse font support
- Faster anti aliasing

Your question came in  the right time: hopefully I will push these new updates on this weekend or next Monday.
I will open an issue to inform you and ask to test it.

What feature are the most important to you?

**Comment by sirius65535** [comment]
@kisvegabor  Hi！Thanks for your working!  the anti aliasing for the Sparse font is important to me.

**Comment by kisvegabor** [comment]
It was faster then I thought :)
Check:  #125

**Comment by kisvegabor** [comment]
As v5.1 is released I close this issue.
