### ISSUE TITLE
Set LV_MEM_ADD_JUNK in lv_mem.c default to 0

### ISSUE THREAD

**Issue by zeile218** [lvgl/lvgl#1240]
The releases and the master from github have the `#define LV_MEM_ADD_JUNK` in lv_mem.c set to 1. This should be default to 0 or moved to the config .h file.

This was a problem for us because the two additional memsets in combination with our external RAM slowed everything down. We got a 25% performance boost by setting the define in lv_mem.c to 0.

**Comment by kisvegabor** [comment]
I left it enabled to get feedback about there is no crashed related to using freed memory.

I set it to `0` in `dev-6.1`: 7f19fb53
