### ISSUE TITLE
Eliminating some warnings in dev-7.0

### ISSUE THREAD

**Issue by embeddedt** [lvgl/lvgl#1248]
@kisvegabor What happens here if `start_angle`/`end_angle` are 0, 180, or 360? The `if` statements don't handle those cases which will result in `start_side`/`end_side` being uninitialized.

https://github.com/littlevgl/lvgl/blob/9726e269abb84be93a0f4fd6d3aa60deb1b307fb/src/lv_draw/lv_draw_mask.c#L237-L249

**Comment by kisvegabor** [comment]
Fixed in 07317f77, thank you!

**Comment by embeddedt** [comment]
There are a number of warnings in `lv_img_buf.c` when `-Wmaybe-uninitialized` is enabled. All appear to be within `lv_img_buf_get_px_rotated`. 

I had a look but the function is a bit too complicated for me to understand what they should be initialized to.

**Comment by kisvegabor** [comment]
I've fixed the `-Wmaybe-uninitialized` and `-Wshadow` warnings.

**Comment by kisvegabor** [comment]
Please reopen if you find other warnings too.
