### ISSUE TITLE
 Please help me，font question

### ISSUE THREAD

**Issue by fzboffice** [lvgl/lvgl#1249]
In the master branch, use the TTF font to convert the C array, and then do everything according to the process completely. As a result, Chinese is not displayed. Please help me

**Comment by embeddedt** [comment]
Please open a question in the **How-to** category on the forum. Give specific details of what settings you used with the font converter, and provide a code sample which doesn't work. "Not displayed" is not enough information for us to help you effectively.

----------------------
We use GitHub issues for development related discussions.
Please use the [forum](https://forum.littlevgl.com/) to ask questions.

It's possible to sign in to the forum with your GitHub account... you don't need to make a separate account.
