### ISSUE TITLE
undefined reference to lv_init linker problem

### ISSUE THREAD

**Issue by 214370** [lvgl/lvgl#1254]
I am having a trouble linking lvgl 6 and esp-idf 4.1. I am calling just lv_init to make a connection, can you tell me where it is located, in which dir/file?

**Comment by 214370** [comment]
Found it. src/lv_core/lv_obj.c

**Comment by 214370** [comment]
May I reopen this issue? I am having trouble linking lvgl.

**Comment by kisvegabor** [comment]
If your question is related to ESP I suggest asking it either in the
- Forum: https://forum.littlevgl.com/
- or ESP32 repo: https://github.com/littlevgl/lv_port_esp32_ili9341

**Comment by 214370** [comment]
I have a solution finally. Should I write it here?

**Comment by kisvegabor** [comment]
Sure!

**Comment by 214370** [comment]
I followed instructions and put LVGL in my project folder. Then I tried to link the files using GNU MAKE what should be pretty straightforward but it did not work. Finally, I added LVGL to the IDF's components directory. I made directory called lvgl-gui, put everything in there, and added just one component.mk file with the following content:
COMPONENT_SRCDIRS := .
COMPONENT_ADD_INCLUDEDIRS = .
COMPONENT_ADD_INCLUDEDIRS += \
	lvgl/src/lv_core \
	lvgl/src/lv_hal \
	lvgl/src/lv_objx \
	lvgl/src/lv_font \
	lvgl/src/lv_misc \
	lvgl/src/lv_themes \
	lvgl/src/lv_draw	

COMPONENT_SRCDIRS += \
	lvgl/src/lv_core \
	lvgl/src/lv_hal \
	lvgl/src/lv_objx \
	lvgl/src/lv_font \
	lvgl/src/lv_misc \
	lvgl/src/lv_themes \
	lvgl/src/lv_draw

**Comment by kisvegabor** [comment]
Thanks.
There were quite a lot of changes in ESP32 repo in the past weeks, maybe it'd worth to try it again with it.

**Comment by 214370** [comment]
Here is the driver and example for ILI9488 display and LVGL 6.0 (ESP-IDF v.4.1).

https://github.com/ilijamr/esp-idf/tree/master/examples/ili9488_lvgl_example

**Comment by C47D** [comment]
@ilijamr, Is the project of your link working? Last week we have added a way to configure the [lv_port_esp32_ili9341](https://github.com/littlevgl/lv_port_esp32_ili9341) example project using the esp-idf menuconfig method.

@kisvegabor Maybe we can add the `lv_port_esp32_ili9341` project to the official esp-idf repo?

**Comment by kisvegabor** [comment]
@C47D 
> Maybe we can add the lv_port_esp32_ili9341 project to the official esp-idf repo?

Does it mean a Pull request to the esp-idf repo?

**Comment by 214370** [comment]
@C47D yes it's working.

**Comment by C47D** [comment]
@kisvegabor Yes, some sort of hello world project and another project with more features enabled.

@ilijamr Great, my kit have the ili9341 controller, but i will check your source code.

**Comment by kisvegabor** [comment]
> @kisvegabor Yes, some sort of hello world project and another project with more features enabled.

Great.
Unfortunately,  I'm absolutely not familiar with their workflow and requirements. Could you manage this?

**Comment by C47D** [comment]
@kisvegabor I will ask on the esp-idf repo what are the requirements to add example projects and add it if possible. I will let you know when i got their reply.

**Comment by kisvegabor** [comment]
Great, thanks!
