### ISSUE TITLE
[v6.1]: cpicker build fails

### ISSUE THREAD

**Issue by amirgon** [lvgl/lvgl#1257]
Build fails when `LV_COLOR_16_SWAP` set to 1 and `LV_COLOR_DEPTH` set to 16

The problem is that cpicker is trying to access `color.ch.green` explicitly.
It's incorrect in this case (since `lv_color_t` struct is different).

```
|| ../../lib/lv_bindings/lvgl/src/lv_objx/lv_cpicker.c: In function 'lv_cpicker_set_color':
/home/amirgon/esp/projects/lv_mpy/ports/esp32/../../lib/lv_bindings/lvgl/src/lv_objx/lv_cpicker.c|278 col 82| error: 'struct <anonymous>' has no member named 'green'
||      return lv_cpicker_set_hsv(cpicker, lv_color_rgb_to_hsv(color.ch.red, color.ch.green, color.ch.blue));
||                                                                                   ^
/home/amirgon/esp/projects/lv_mpy/ports/esp32/../../lib/lv_bindings/lvgl/src/lv_objx/lv_cpicker.c|279 col 1| error: control reaches end of non-void function [-Werror=return-type]
||  }
||  ^
|| cc1: all warnings being treated as errors
py/mkrules.mk|47| recipe for target 'build-GENERIC_SPIRAM/lib/lv_bindings/lvgl/src/lv_objx/lv_cpicker.o' failed
```

**To Reproduce**

Set `LV_COLOR_16_SWAP`  to 1 and `LV_COLOR_DEPTH` to 16 and build lvgl

**Additional context**

Needed for ESP32 build with pure micropython ILI9341 display driver

---

btw... it could really be useful if we had a CI system to build lvgl in all configuration combinations and alert when something like this happens.
Maybe reconsider #768?

**Comment by kisvegabor** [comment]
Fixed it 6f762bb.
Please verify if it works now.

**Comment by amirgon** [comment]
> Fixed it [6f762bb](https://github.com/littlevgl/lvgl/commit/6f762bb7c776894ca49f8143cf28dade4099d988).

@kisvegabor Does it make sense to add an `#if` on every line of code that access r/g/b?
Why not create accessor macros instead? (`GET_R(color)`, `GET_G(color)`, `GET_B(color)`)   
This way the ugly `#if`s and lo/hi shifts arithmetic would be contained in the accessors implementation instead of duplicated and spread out for each r/g/b access.  
Also it would make the code forward compatible if you ever change `lv_color_t` struct.

**Comment by kisvegabor** [comment]
> Does it make sense to add an #if on every line of code that access r/g/b?

It really doesn't make sense. I always forget the case of `LV_COLOR_16_SWAP`.

@embeddedt 
It might affect the [fixing of warnings](#1213) in `color.h`, right?
Probably it would be worth to add the macros or inline functions suggested by @amirgon before fixing the warnings. If you agree I'll add them,

**Comment by embeddedt** [comment]
> Probably it would be worth to add the macros or inline functions suggested by @amirgon before fixing the warnings. If you agree I'll add them.

I agree. That should simplify things.

**Comment by kisvegabor** [comment]
I've ad the macros to `dev-6.1`. Now `LV_COLOR_16_SWAP` is used only in `color.h` in some special cases.

**Comment by amirgon** [comment]
> I've ad the macros to `dev-6.1`. Now `LV_COLOR_16_SWAP` is used only in `color.h` in some special cases.

Looks good! I verified this on ESP32.

Since `LV_COLOR_GET/SET` are macros, they are not available on Micropython.
I'm not sure how important that is, we can always add some static inline function if we want them on Micropython.

**Comment by kisvegabor** [comment]
> Looks good! I verified this on ESP32.

Great!

> Since LV_COLOR_GET/SET are macros, they are not available on Micropython.

IMO it's not a problem if these low-level things are missing because they are shouldn't be used on the user directly. What do you think?

**Comment by amirgon** [comment]
> IMO it's not a problem if these low-level things are missing because they are shouldn't be used on the user directly. What do you think?

That's fine with me.  
And if we ever decide otherwise, we can always add inline functions.
