### ISSUE TITLE
lv_obj_set_hidden not possible with page object

### ISSUE THREAD

**Issue by harteware07** [lvgl/lvgl#1269]
I created a page to have a scroll option on some screens. I tried everything to hide the page object but nothing works, all otions crash the code. 
What i have tried:
- lv_obj_set_hidden
- lv_page_set_style (with invisible style)
- lv_page_set_sb_mode -> LV_SB_MODE_OFF
any ideas what i could do to use this feature?
Any hints are greatly appreciated!

**Comment by kisvegabor** [comment]
Please send a simple code to reproduce the issue in the simulator.

**Comment by harteware07** [comment]
i redefined the global label while creating the page. it was a typo. everthing works as expected. 
Thanks :)
