### ISSUE TITLE
Collection of minor issues

### ISSUE THREAD

**Issue by xennex22** [lvgl/lvgl#1292]
I'd rather someone else did these changes than making a PR.

lvgl\src\lv_draw\lv_draw_blend.c(54)
static inline lv_color_t color_blend_true_color_additive(lv_color_t bg, lv_color_t fg, lv_opa_t opa);
should be
static inline lv_color_t color_blend_true_color_additive(lv_color_t fg, lv_color_t bg, lv_opa_t opa);

lvgl\src\lv_font\lv_font_fmt_txt.c(83)
if(!gid) return false;
should be
if(!gid) return NULL;

lvgl\src\lv_objx\lv_line.c(249)
lv_coord_t r_corr = style->line.width & 1 ? 0 : 1;
some compilers prefer this:
lv_coord_t r_corr = (style->line.width & 1) ? 0 : 1;

lvgl\src\lv_themes\lv_theme_material.c(684)
indic.body.padding.inner = LV_DPI / 20;
indic.body.padding.inner = LV_DPI / 20;

lvgl\src\lv_themes\lv_theme_nemo.c(622)
list_pr.body.opa        = LV_OPA_TRANSP;
list_pr.body.opa        = LV_OPA_COVER;

lvgl\src\lv_objx\lv_ta.c(1710)
style_res->body.opa            = LV_OPA_COVER;
style_res->body.opa            = LV_OPA_COVER;

lvgl\src\lv_objx\lv_sw.h(150)
lv_sw_ext_t * ext = lv_obj_get_ext_attr(sw);
should be
lv_sw_ext_t * ext = (lv_sw_ext_t *)lv_obj_get_ext_attr(sw);

Finally there are a lot of functions which have a dead code return to prevent a warning.
eg lvgl\src\lv_objx\lv_roller.c(320)
```
const lv_style_t * lv_roller_get_style(const lv_obj_t * roller, lv_roller_style_t type)
{
    LV_ASSERT_OBJ(roller, LV_OBJX_NAME);

    switch(type) {
        case LV_ROLLER_STYLE_BG: return lv_obj_get_style(roller);
        case LV_ROLLER_STYLE_SEL: return lv_ddlist_get_style(roller, LV_DDLIST_STYLE_SEL);
        default: return NULL;
    }

    /*To avoid warning*/
    return NULL;
}
```

I'm not sure of the best approach.  Some compilers will give a warning because they recognize the dead code.  In the above switch statement the default 'return NULL' could be removed but some compilers will then complain about a missing default.  If it was me I'd declare a return variable lv_style_t * style = NULL; and then assign the variable in the switch statement with 'return style;' at the end of the function.  Then I don't think any compiler would issue warnings.
```
const lv_style_t * lv_roller_get_style(const lv_obj_t * roller, lv_roller_style_t type)
{
    const lv_style_t * style = NULL;
    LV_ASSERT_OBJ(roller, LV_OBJX_NAME);

    switch(type) {
	case LV_ROLLER_STYLE_BG: style = lv_obj_get_style(roller);
	case LV_ROLLER_STYLE_SEL: style = lv_ddlist_get_style(roller, LV_DDLIST_STYLE_SEL);
	default: style = NULL;
    }
    return style;
}
```

**Comment by kisvegabor** [comment]
Thank you, I'll examine them!

**Comment by kisvegabor** [comment]
I've fixed all the listed issues except this one:

> lvgl\src\lv_objx\lv_sw.h(150)
lv_sw_ext_t * ext = lv_obj_get_ext_attr(sw);
should be
lv_sw_ext_t * ext = (lv_sw_ext_t *)lv_obj_get_ext_attr(sw);

Why is it a problem? It's used without casting everywhere. Because it's in a header file?

**Comment by embeddedt** [comment]
> Why is it a problem? It's used without casting everywhere. Because it's in a header file?

Not sure what the original reason is, but anyone using a C++ file to include the LittlevGL headers will get a warning about that cast, because C++ forbids implicit casts from `void *` to another type.

**Comment by kisvegabor** [comment]
> Not sure what the original reason is, but anyone using a C++ file to include the LittlevGL headers will get a warning about that cast, because C++ forbids implicit casts from void * to another type.

I see. I've fixed it too.

**Comment by xennex22** [comment]
Thanks for looking at this.

**Comment by kisvegabor** [comment]
> Thanks for looking at this.

I also thank you for the report.

I close this issue. 
Feel free to reopen if you found similar issues.
