### ISSUE TITLE
a bug maybe in lv_tileview.c

### ISSUE THREAD

**Issue by fzboffice** [lvgl/lvgl#1294]
> # Important: issues that don't use this template will be ignored/closed.

**Describe the bug**
original:
lv_tileview_set_valid_positions()
{
    uint16_t i;
    for(i = 0; i < valid_pos_cnt; i++) {
        if(valid_pos->x == ext->act_id.x && valid_pos->y == ext->act_id.y) {
            return;
        }
    }
}

I think it should be like this:
lv_tileview_set_valid_positions()
{
    uint16_t i;
    for(i = 0; i < valid_pos_cnt; i++) {
        if((valid_pos + i)->x == ext->act_id.x && (valid_pos + i)->y == ext->act_id.y) {
            return;
        }
    }
}

**To Reproduce**

Please provide a small, independent code sample that can be used to reproduce the issue. Ideally this should work in the PC simulator unless the problem is specific to one platform.

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by kisvegabor** [comment]
Fixed in 6e8a4eee

Thank you!
