### ISSUE TITLE
Hardware connection and initialization

### ISSUE THREAD

**Issue by MyVanitar** [lvgl/lvgl#1295]
Hi,

I could not find documentation regarding the hardware connection between an LCD and an MCU, when I try to use your library.

for example, consider we have a 4.3 inch TFT an STM32F103 MCU. The LCD could be a bare RGB LCD or it might contain a Driver chip such as ILI9325 or whatever, A parallel connector or SPI for instance.

Where these modifications/initializations should be made?

**Comment by embeddedt** [comment]
Did you read the documentation? https://docs.littlevgl.com/en/html/porting/display.html

There are porting templates available. https://github.com/littlevgl/lvgl/tree/master/porting

----------------------
We use GitHub issues for development related discussions.
Please use the [forum](https://forum.littlevgl.com/) to ask questions.

It's possible to sign in to the forum with your GitHub account... you don't need to make a separate account.
