### ISSUE TITLE
How to attach two different actions on a button?

### ISSUE THREAD

**Issue by mimansamaheshwari** [lvgl/lvgl#1299]
I want to attach two different types of events on a button object. One event has to be called for short click on the button object and other event for the long click. How to proceed in this?

**Comment by embeddedt** [comment]
It's explained near the top of the [event documentation](https://docs.littlevgl.com/en/html/overview/event.html#events).

----------------------
We use GitHub issues for development related discussions.
Please use the [forum](https://forum.littlevgl.com/) to ask questions.

It's possible to sign in to the forum with your GitHub account... you don't need to make a separate account.
