### ISSUE TITLE
Label text missing after decimal point when style's letter_space is nagtive

### ISSUE THREAD

**Issue by magailee** [lvgl/lvgl#1306]
**Describe the bug**

I updated the lvgl this week from github , and my app made of lvgl got a problem as mentioned above. I wrote a test as below as my issue. 

**To Reproduce**

test src:

    #include "lvgl/lvgl.h"
    #include "lv_drivers/display/fbdev.h"
    #define DRAW_BUF_SIZE (LV_HOR_RES_MAX * LV_VER_RES_MAX / 4)
    int main ()
    {
        lv_color_t draw_buf0[DRAW_BUF_SIZE];
        lv_disp_buf_t disp_buf;
        lv_disp_drv_t disp_drv;

        lv_init(); // lvgl init
        fbdev_init();
        lv_disp_drv_init(&disp_drv);
        lv_disp_buf_init(&disp_buf, draw_buf0, NULL, DRAW_BUF_SIZE);
        disp_drv.buffer = &disp_buf;
        disp_drv.flush_cb = fbdev_flush;
        lv_disp_drv_register(&disp_drv);

        lv_style_t sty;
        lv_style_copy(&sty, &lv_style_plain);

        sty.text.font = LV_FONT_DEFAULT; // &lv_font_roboto_16
        sty.text.letter_space = -1; // !!! nagtive was ok before !!!

        lv_obj_t *lab, *labs[3];
        for (int i = 0; i < 3; i++)
        {
            lab = lv_label_create(lv_scr_act(), NULL);
            lv_label_set_style(lab, LV_LABEL_STYLE_MAIN, &sty);
            lv_obj_set_pos(lab, 40, (i + 1) * 30);
            labs[i] = lab;
        }

        lv_label_set_text(labs[0], "010101."); // decimal point missing in output
        lv_label_set_text(labs[1], "0101.01"); // missing tail after decimal point
        lv_label_set_text(labs[2], "01.0101");

        lv_task_handler();
        return 0;
    }

output in my device (linux framebuffer):

    010101
    0101.
    01.

**Comment by embeddedt** [comment]
What font are you using?

**Comment by magailee** [comment]
> 
> 
> What font are you using?

By this example, it's LV_FONT_DEFAULT (lv_font_roboto_16). And I've tried most of fonts like as lv_font_roboto_22, lv_font_roboto_28 ... and other fonts made by myself. All I got the same result.

**Comment by kisvegabor** [comment]
Hi,

I've fixed it in `master`. Can you confirm if it's working now?

**Comment by magailee** [comment]
> I've fixed it in `master`. Can you confirm if it's working now?

I'm sorry I can not update anything fresh from `master` to confirm, could you tell me which part of source fixed I should git it ? I've tried `git clone` all and tested, but it worked in the same way.

**Comment by kisvegabor** [comment]
Upps, sorry. It seems I haven't pushed it.
It should be here: https://github.com/littlevgl/lvgl/commit/f54ecc470cde598c56488809bac0e42f1fc5b58b

**Comment by magailee** [comment]
> 
> Upps, sorry. It seems I haven't pushed it.
> It should be here: [f54ecc4](https://github.com/littlevgl/lvgl/commit/f54ecc470cde598c56488809bac0e42f1fc5b58b)

It's working OK now 👍.
Thank you for early bug fixing :-)

**Comment by kisvegabor** [comment]
Great! 

Thank you for the report! :slightly_smiling_face:
