### ISSUE TITLE
why should i use static when i use [lv_event_cb_t] type?

### ISSUE THREAD

**Issue by YHAY** [lvgl/lvgl#1310]
hi, im a user of littlevgl. really thank you for making this.
i have a question. i use it as c/c++ mix up version.  then i had a problem.
why should i use "static" when i use [lv_event_cb_t] in [lv_obj_set_event_cb]?
i know it's defined [typedef void (*lv_event_cb_t)(struct _lv_obj_t * obj, lv_event_t event);]
but i can't understand why i must use it static function. i want to use it as just function. not static function.

can you give me some hint..?

**Comment by embeddedt** [comment]
There should be no need to make it a `static` function, unless you are using it within a class, where it would need to be static and not a class instance member.

----------------------
We use GitHub issues for development related discussions.
Please use the [forum](https://forum.littlevgl.com/) to ask questions.

It's possible to sign in to the forum with your GitHub account... you don't need to make a separate account.
