### ISSUE TITLE
[Bug] lv_disp_drv_register function bug

### ISSUE THREAD

**Issue by chenshijianworkgit** [lvgl/lvgl#132]
To see the implementation of the lv_disp_next function, we know that getting the next display gets started at disp_list-> next, but creating a new device in the lv_disp_drv_register function points to disp_list with the new device's next.

original:
      else {
             node->next = disp_list;
       }
change into：
       else {
	      disp_list->next = node;
	}

**Comment by kisvegabor** [comment]
Thank you, I fixed it as you suggested in `dev-5.1`
