### ISSUE TITLE
How could I modify the background color of the list?

### ISSUE THREAD

**Issue by jason-sophia** [lvgl/lvgl#1322]
the default background  color(the color under the buttons) of list is gradient from white to gray. What can I do to change the color ?

**Comment by embeddedt** [comment]
Have a look at the [style documentation for the list object](https://docs.littlevgl.com/en/html/object-types/list.html#style-usage). Adjusting the color of `LV_LIST_STYLE_BG` or `LV_LIST_STYLE_SCRL` should do what you're looking for.

----------------------
We use GitHub issues for development related discussions.
Please use the [forum](https://forum.littlevgl.com/) to ask questions.

It's possible to sign in to the forum with your GitHub account... you don't need to make a separate account.

**Comment by jason-sophia** [comment]
Thank you very much, the problem is solved.
