### ISSUE TITLE
Error 1 when adding lvgl to a project

### ISSUE THREAD

**Issue by huynguyennguyen** [lvgl/lvgl#1334]
> # Important: issues that don't use this template will be ignored/closed.

**Describe the bug**

I am working on adding lvgl to a project running on STM32CubeIDE. After I finished executing steps in this instruction:
https://github.com/littlevgl/lvgl

I met an error that "make: ***[makefile:41: Display_LittlevGL.elf] Error 1". (Display_LittlevGL is the name of my project. 

**To Reproduce**

To perform step 5 in the link, I set up a timer. With step 10, I put lv_task_handler()  in while(1) loop with HAL_Delay(5) after that. I did not perform step 9.

**Expected behavior**

 I intended to successfully build the project and load the project to the board STM32L4R9IDISC.

**Screenshots**

![](https://lh3.googleusercontent.com/-B1BHegz0IoM/XgXK6daqyhI/AAAAAAAAD0c/1toRmwyy7gwksXZs2bx4I_TbwGQM0EaiwCK8BGAsYHg/s0/2019-12-27.png)

**Additional context**
The full build log is here:
16:15:35 **** Incremental Build of configuration Debug for project Display_LittlevGL ****
make -j4 all 
arm-none-eabi-gcc -o "Display_LittlevGL.elf" @"objects.list"  -llvgl -mcpu=cortex-m4 -T"C:\Users\laptop88\STM32CubeIDE\workspace_1.1.0\Display_LittlevGL\STM32L4R9AIIX_FLASH.ld" --specs=nosys.specs -Wl,-Map="Display_LittlevGL.map" -Wl,--gc-sections -static -L"C:\Users\laptop88\STM32CubeIDE\workspace_1.1.0\Display_LittlevGL\lvgl" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -Wl,--start-group -lc -lm -Wl,--end-group
c:\st\stm32cubeide_1.1.0\stm32cubeide\plugins\com.st.stm32cube.ide.mcu.externaltools.gnu-tools-for-stm32.7-2018-q2-update.win32_1.0.0.201904181610\tools\arm-none-eabi\bin\ld.exe: cannot find -llvgl
collect2.exe: error: ld returned 1 exit status
make: *** [makefile:41: Display_LittlevGL.elf] Error 1
"make -j4 all" terminated with exit code 2. Build might be incomplete.

**Comment by embeddedt** [comment]
> `cannot find -llvgl`

There is no `liblvgl.a`, so you shouldn't be adding LittlevGL to the library section of your IDE. You should just compile the source files as though they were part of your project.

----------------------
We use GitHub issues for development related discussions.
Please use the [forum](https://forum.littlevgl.com/) to ask questions.

It's possible to sign in to the forum with your GitHub account... you don't need to make a separate account.
