### ISSUE TITLE
Build error with LV_USE_LOG 0

### ISSUE THREAD

**Issue by puzrin** [lvgl/lvgl#1342]
**Describe the bug**

If i set `#define LV_USE_LOG 0` (zero) in config, build is broken with message

```
.pio/build/emulator/lib070/lvgl/lv_core/lv_obj.o: In function `lv_deinit':
lv_obj.c:(.text+0xe5): undefined reference to `lv_log_register_print_cb'
```

vesion is from current master (7d25f66).

**To Reproduce**

See above

**Expected behavior**

Build should succeed.

**Comment by embeddedt** [comment]
Thanks for the report; I've fixed it.
