### ISSUE TITLE
Memory leak - lv_img

### ISSUE THREAD

**Issue by nwsetec** [lvgl/lvgl#1344]
**Describe the bug**
When repeatedly creating a lv_img object, rendering it and lv_obj_clean() the default screen on a button click a memory leak seems to be happening and eventually memory cannot be allocated.

**To Reproduce**
I've created a branch with a commit to reproduce the issue here:
https://github.com/nwsetec/lv_sim_eclipse_sdl.git

**Expected behavior**
If the button is clicked repeatedly eventually no memory can be allocated.

**Screenshots**
![mem_leak](https://user-images.githubusercontent.com/40375830/71800223-9bd21a00-30ab-11ea-8692-18c995934001.PNG)

**Additional context**
LittlevGL is configured for 1bit pixel depth.
Note that if the object isn't rendered then the memory leak doesn't happen, image cache issue?

**Comment by kisvegabor** [comment]
Hi,

I've found the issue. It was related to indexed images. A part of the palette was not freed. 
It should be fixed in f31ba6cf

**Comment by nwsetec** [comment]
Thanks Gabor!  This issue is now fixed for me.

**Comment by kisvegabor** [comment]
Great! :slightly_smiling_face:
