### ISSUE TITLE
PNG issues for Online Image Converter

### ISSUE THREAD

**Issue by imosts** [lvgl/lvgl#1345]
# PNG issues for Online Image Converter.

Hi, I use the Online Image Converter to convert a PNG image with alpha channel, the transparent part of the image is not transparent after conversion, but black. 
The color format I chose is **True color with alpha**, and output format I chose is **C array**.
I don't know if there is a problem with this PNG file format or with the Online Image Converter.

This is the PNG image: https://drive.google.com/file/d/14G0EYui4DUurA0jlo1o05xR1zc86BOxg/view?usp=sharing

This is the C array:
https://drive.google.com/file/d/1DEHbeNHWeu-oLflvxPtgMyTZrt_YYPmh/view?usp=sharing

Thanks,
imosts

We use GitHub issues for development related discussions.
Please use the [forum](https://forum.littlevgl.com/) to ask questions.

**Comment by kisvegabor** [comment]
Hi,

The image had indexed mode. I've opened it with GIMP and in Image/Mode I've changed it RGB. Now it works for me.

Here is the corrected image: 
[page_indicator.png.zip](https://github.com/littlevgl/lvgl/files/4041542/page_indicator.png.zip)

**Comment by imosts** [comment]
> Hi,
> 
> The image had indexed mode. I've opened it with GIMP and in Image/Mode I've changed it RGB. Now it works for me.
> 
> Here is the corrected image:
> [page_indicator.png.zip](https://github.com/littlevgl/lvgl/files/4041542/page_indicator.png.zip)

That great! Thank you very much!
