### ISSUE TITLE
CMake build for the library and examples repository

### ISSUE THREAD

**Issue by ValentiWorkLearning** [lvgl/lvgl#1346]
Hi
As the @kisvegabor suggested, I opened this issue to talk about the CMake-based build for the library or/and simulator repository.
Here is the list of questions:
- CMakeLists for lvgl library

- CMakeLists for examples

- CMakeLists for simulator( this achieves the possibility of using IDE's that support CMakeLists such as Qt Creator, CLion and other )

I've provided the sample of CMake-based bulild of Simulator in my repository:
https://github.com/ValentiWorkLearning/GradWork/tree/dev/lvgl_implementation/Simulator
https://github.com/ValentiWorkLearning/GradWork/blob/dev/lvgl_implementation/Simulator/graphics/CMakeLists.txt

So, if these options are acceptable, I can start from implementation of Simulator CMake-build.

**Comment by puzrin** [comment]
Cmake is instrument, not goal. Could you explain goal you wish to acheive?

**Comment by ValentiWorkLearning** [comment]
@puzrin I just want to achieve cross-platform build of LVGL without looking for any IDE-dependent and OS - dependent solutions. Also, it'll achieve possibility of using lvgl as subtarget of CMake-based projects.

**Comment by ValentiWorkLearning** [comment]
@puzrin also, CMake target for lvgl achieve auto-rebuild, integration with syntax navigators in popular IDE's and other cool things that can be achieved with single consistency of project build hierarchy.

**Comment by kisvegabor** [comment]
@ValentiWorkLearning 
We already have [CMakeList.txt](https://github.com/littlevgl/lv_sim_eclipse_sdl/blob/master/CMakeLists.txt) in [lv_sim_eclipse_sdl](https://github.com/littlevgl/lv_sim_eclipse_sdl) project. 

The current CMake file seems simpler because it doesn't require to list all the files. However, I'm not too familiar with CMake so I'm not aware of the advantages and disadvantages of the solutions. 

Instead of creating a new project we should add it to one of the existing simulators. `lv_sim_eclipse_sdl` is the most popular one, so I vote for this. Is it ok for you too?

**Comment by ValentiWorkLearning** [comment]
@kisvegabor Yes, I agree with you, that CMakeLists should be added for one of existing simultors. Eclipse is acceptable for me. I'll try to fork and implement it.

**Comment by kisvegabor** [comment]
Great! :+1:

**Comment by ValentiWorkLearning** [comment]
@kisvegabor it's better to implement CMake for lvgl 7.0 dev branch or for 6.1? Suppose it'll be several PR's - to LVGL main repository, to driver's repository, to example's and to Eclipse simulator.

**Comment by embeddedt** [comment]
Please send it to dev-7.0. 6.1 only receives bugfixes.

**Comment by ValentiWorkLearning** [comment]
@kisvegabor  @embeddedt started implementation here:
https://github.com/ValentiWorkLearning/lvgl/commit/eeef10cefec31cc0414864664a4f9a163d42bd32
Commits for example will be as soon as possible.

**Comment by kisvegabor** [comment]
@ValentiWorkLearning 
Thanks for the update!

Would it be possible to automatically search the source files instead of directly enumerate them?

**Comment by ValentiWorkLearning** [comment]
@kisvegabor suppose it's possible. I'll try to use the  ```aux_source_directory``` cmake command. That's a right way to supply the library.

**Comment by kisvegabor** [comment]
Great, thank you!
