### ISSUE TITLE
Web server is down?

### ISSUE THREAD

**Issue by amirgon** [lvgl/lvgl#1352]
https://forum.littlevgl.com/ and https://littlevgl.com/ are unreachable now....

**Comment by kisvegabor** [comment]
Probably just a temporal issue.

**Comment by jTecRepos** [comment]
nope - website is completely dead

**Comment by kisvegabor** [comment]
Do you mean lvgl.io? t's working here. Can you try from mobile too?

**Comment by jTecRepos** [comment]
no i mean littlevgl.com (see original comment) 
i think littlevgl.com was bought out and replaced with something else to collect site visits.
its a little bit offtopic here but a lot of older posts recommend littlevgl to generate fonts, so I wanted to leave that information here. 

for fonts generation use: [https://lvgl.io/tools/fontconverter](https://lvgl.io/tools/fontconverter)

**Comment by kisvegabor** [comment]
Ah, when we have change the LittleVGL name to LVGL I kept the littlevgl.com domain for a few years, but I wasn't playing for it anymore. It seems it was really taken by someone.
