### ISSUE TITLE
online image convert crash

### ISSUE THREAD

**Issue by arnold0kang** [lvgl/lvgl#1354]
> Fatal error: Allowed memory size of 201326592 bytes exhausted (tried to allocate 134217736 bytes) in /web/littlev/littlevgl.com/tools/img_conv_core.php on line 451

**Comment by embeddedt** [comment]
How big is the image you're trying to convert? We've received several reports lately about the web converter running out of memory.

**Comment by arnold0kang** [comment]
about 500K jpeg file, I have resolve it by use local tool . thanks sir

**Comment by embeddedt** [comment]
Great! We probably need to improve the script as the memory limit seems to be an issue for a lot of people.

It seems to be the same issue as https://github.com/littlevgl/lv_utils/issues/31, so let's continue the discussion there.
