### ISSUE TITLE
[BUG] Calendar header button signal behavior.

### ISSUE THREAD

**Issue by turoksama** [lvgl/lvgl#1358]
> # Important: issues that don't use this template will be ignored/closed.

**Describe the bug**
Hello there,
As mention above.
The action of pressing the header of Calendar will signal an user event callback, neat.
It seems caused by combinations of specific conditions.
**To Reproduce**

Please provide a small, independent code sample that can be used to reproduce the issue. Ideally this should work in the PC simulator unless the problem is specific to one platform.
```
static const char *day_names_char[]={"Su","Mo","Tu","We","Th","Fr","Sa",	""};
static const char *month_names_char[]=
{"Jan","Feb","Mar","Apr","May","Jun","Jul","Aug","Sep","Oct","Nov","Dec",""};
static void calendar_cb(lv_obj_t * obj, lv_event_t event)
{
		switch (event)
		{
			case LV_EVENT_PRESSED:
			{
				//Select
				lv_calendar_date_t *date_sel = lv_calendar_get_pressed_date(calendar);
				lv_calendar_set_today_date(calendar, date_sel);
			}break;
			case LV_EVENT_SHORT_CLICKED:
			{
			}break;
			case LV_EVENT_CLICKED:break;
			case LV_EVENT_LONG_PRESSED:break;
			case LV_EVENT_RELEASED:break;
			default:break;
		}
}

lv_obj_t *calendar_create(lv_obj_t * par)
{
	lv_obj_t *ca = calendar = lv_calendar_create(par, NULL);

	lv_calendar_set_day_names(ca, day_names_char);//
	lv_calendar_set_month_names(ca, month_names_char);//

	lv_obj_set_size(ca,350,380);
	lv_obj_align(ca, par, LV_ALIGN_CENTER, 0, 0);
	lv_obj_set_top(ca, true);

	lv_obj_set_event_cb(ca, calendar_cb);

        return ca;
}
```

**Expected behavior**

I think this kind of action is internal behavior of the object. 
Generate an EVENT may crash. In my case, it did.

**Screenshots**

**Additional context**

 lv_calendar_get_pressed_date(calendar);  will result NULL if not a date select condiction

A hack to solve this problem:

```
static void calendar_cb(lv_obj_t * obj, lv_event_t event)
{
              	switch (event)
		{
			case LV_EVENT_PRESSED:
			{
			}break;
			case LV_EVENT_SHORT_CLICKED:
			{				
				lv_calendar_date_t *date_sel = lv_calendar_get_pressed_date(calendar);
				if(NULL != date_sel) //don't trust it, neat.
					lv_calendar_set_today_date(calendar, date_sel);
			}break;
			case LV_EVENT_CLICKED:break;
			case LV_EVENT_LONG_PRESSED:break;
			case LV_EVENT_RELEASED:break;
			default:break;
		}
}
```

**Comment by embeddedt** [comment]
The basic input events are always triggered on the whole surface of an object (regardless of its type) so I don't think that is specifically the problem. They come directly from the input system, not from the object's signal handler.

> lv_calendar_get_pressed_date(calendar); will result NULL if not a date select condition

That makes sense to me. If you didn't touch a date, what would you expect it to return?

For your case, can't you just check whether the return value was NULL or not? That seems like the cleanest solution to me, and doesn't seem very odd. Or have I missed something?

**Comment by turoksama** [comment]
Well, it's a little bit different from version 5.3,fair enough,I figured it out. I realized that it is clean and logical.Thanks for your support.Happy days are back again. @embeddedt

**Comment by embeddedt** [comment]
No problem! :slightly_smiling_face:
