### ISSUE TITLE
lv_ta_set_cursor_blink_time doesn't work

### ISSUE THREAD

**Issue by imprego** [lvgl/lvgl#1361]
Good day.

I trying set spinbox/textArea non-blinking cursor, but lv_ta_set_cursor_blink_time(ta, 0) not worked. I've try this on stm32f429 and codeblocks_sim.

**Comment by kisvegabor** [comment]
Have you tried `lv_ta_set_cursor_type(ta, LV_CURSOR_NONE)`?

**Comment by imprego** [comment]
This is not what i want to see. I need a cursor, but it should not blink. I read description of the function lv_ta_set_cursor_blink_time in the doc: "time: blink period. 0: disable blinking" - but this is not work.

**Comment by kisvegabor** [comment]
Oh, got it. I've just fixed in `master`.
