### ISSUE TITLE
How can I exctract entire buffer to copy it via dma2d to the screen in my_flush_cb function.

### ISSUE THREAD

**Issue by KarolSABEGO** [lvgl/lvgl#1362]
Hi.

I would like to copy the entire buffer to the screen via dma2d in stm32f7 in my_flush_cb.

The buffer structure in memory buffer goes like this:
```c
uint32_t screenBuffer[480*272*4] = {pixelFromTheTopLeft, .... pixelFromTheBottomRight};  
```
The prototype of my buffer copying function looks like that:
```c
void dma2dCopy(uint32_t * source, uint32_t * destination, uint32_t xScreenSize, uint32_t yScreenSize);
```
I was trying to achive that using coordinates from lv_area_t variables, but with no success.
Could you tell me how to extrac desired buffer with coordinates from lv_area_t structure?

Thanks in advance

**Comment by embeddedt** [comment]
The [existing STM32F7 driver](https://github.com/littlevgl/lv_port_stm32f746_disco_sw4stm32/blob/master/hal_stm_lvgl/tft/tft.c) might be useful here.

----------------------
We use GitHub issues for development related discussions.
Please use the [forum](https://forum.littlevgl.com/) to ask questions.

It's possible to sign in to the forum with your GitHub account... you don't need to make a separate account.
