### ISSUE TITLE
chart clear serie  cause memory leak

### ISSUE THREAD

**Issue by tiangaomingjing** [lvgl/lvgl#1367]
> # Important: issues that don't use this template will be ignored/closed.

**Describe the bug**
chart clear serie  cause memory leak

**To Reproduce**
lv_chart_series_t * ser1;
int i = 0;
for(;i<100;i++)
{
  ser1 = lv_chart_add_series(chart, LV_COLOR_RED);
  lv_chart_set_next(chart, ser1, y);
  lv_chart_clear_serie(chart, ser1);
}

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by kisvegabor** [comment]
`lv_chart_clear_serie` only clears point visually and don't remove the created serie. We don't have function to remove a serie right now.  If you are interested you can add `lv_chart_del_serie(chart, serie)`

Please open a PR if you are interested in it.
