### ISSUE TITLE
DEV-7.0 has broken tileview animation

### ISSUE THREAD

**Issue by barbiani** [lvgl/lvgl#1378]
Lastest dev-7.0 tileview is not responding to LV_EVENT_RELEASED/LV_EVENT_DRAG_END.

Tile rests where I leave it instead of moving back to the parent (0, 0) coordinate.

Tileview drag_end_handler() seems to not be called when mouse is released in the visual studio simulator.

**Comment by rabbitsaviola** [comment]
Is it because "break" is missing in the [for loop](https://github.com/littlevgl/lvgl/blob/40e2da1905a20437aa66ca439ceb332841808eae/src/lv_objx/lv_tileview.c#L225) of function `lv_tileview_set_tile_act`  ?

**Comment by xennex22** [comment]
> 
> 
> Is it because "break" is missing in the [for loop](https://github.com/littlevgl/lvgl/blob/40e2da1905a20437aa66ca439ceb332841808eae/src/lv_objx/lv_tileview.c#L225) of function `lv_tileview_set_tile_act` ?

No. That is non optimal, but not a bug.

**Comment by rabbitsaviola** [comment]
> > Is it because "break" is missing in the [for loop](https://github.com/littlevgl/lvgl/blob/40e2da1905a20437aa66ca439ceb332841808eae/src/lv_objx/lv_tileview.c#L225) of function `lv_tileview_set_tile_act` ?
> 
> No. That is non optimal, but not a bug.

maybe it's not relevant to this issue, but without the `break` the `tile_id` passed to `lv_event_send` would be wrong?

**Comment by embeddedt** [comment]
@rabbitsaviola Good catch. I don't think that would fix this issue in particular, but it's definitely a bug.

Fixed here: https://github.com/littlevgl/lvgl/commit/36a4307930a858887030e79aecf5c9536c46a6c2

**Comment by rabbitsaviola** [comment]
It seems `set_drag_throw` should be set to true for tileview animation?
https://github.com/littlevgl/lvgl/blob/9d664b27ec9ce9e502755a577788a930689bf13d/src/lv_objx/lv_tileview.c#L116

**Comment by barbiani** [comment]
Tileview was working fine last week.

**Comment by xennex22** [comment]
> 
> 
> > > Is it because "break" is missing in the [for loop](https://github.com/littlevgl/lvgl/blob/40e2da1905a20437aa66ca439ceb332841808eae/src/lv_objx/lv_tileview.c#L225) of function `lv_tileview_set_tile_act` ?
> > 
> > 
> > No. That is non optimal, but not a bug.
> 
> maybe it's not relevant to this issue, but without the `break` the `tile_id` passed to `lv_event_send` would be wrong?

Yes, sorry, I missed that.

**Comment by kisvegabor** [comment]
Hi,

I've just fixed it. Somehow these [two lines](https://github.com/littlevgl/lvgl/commit/c00750d19f36f1df416712092e049944b23aac6d) have disappeared. (Probably during merging when solving conflicts)

**Comment by barbiani** [comment]
I can confirm that drag end restores the tile correctly.

Thank you.
