### ISSUE TITLE
angle mask is not removed after drawing

### ISSUE THREAD

**Issue by rabbitsaviola** [lvgl/lvgl#1379]
**Describe the bug**

Wrong mask parameters present in mask_list causes exception.

**To Reproduce**

create arc object with start_angle=0, and end_angle=360

**Expected behavior**

No exception happens

**Screenshots**
`lv_draw_mask_remove_id(mask_angle_id);`
should be added before return at following position?

https://github.com/littlevgl/lvgl/blob/9d664b27ec9ce9e502755a577788a930689bf13d/src/lv_draw/lv_draw_arc.c#L97

**Additional context**

**Comment by rabbitsaviola** [comment]
BTW, if start_angle=0, end_angle=360，the full ring has a gap as the screenshot shows.
![image](https://user-images.githubusercontent.com/26240242/74536246-a1f0cb80-4f72-11ea-8121-d5353a532968.png)

**Comment by kisvegabor** [comment]
Thank you for pointing this out!

I've just merged a [huge update](https://github.com/littlevgl/lvgl/issues/1243#issuecomment-586579395) into `dev-7.0` and it was already [fixed](https://github.com/littlevgl/lvgl/blob/332124f1f43136a362e55de8f7e02387c65906da/src/lv_draw/lv_draw_arc.c#L93-L101) in it.
