### ISSUE TITLE
Increase image rotation precision

### ISSUE THREAD

**Issue by rabbitsaviola** [lvgl/lvgl#1389]
Suggest to increase image rotation precison, e.g. 0.1 degree, such that the second hand on a watch face can be rotated more smoothly.

**Comment by C47D** [comment]
OT: rabbitsaviola por el conejito Saviola?

**Comment by kisvegabor** [comment]
It was already asked several times which is a clear indication of it really should be improved.

I see a good way to add it to the code but not sure about the API. Simply allow 0...3600 deg as input (for 0.1 deg resolution)?

**Comment by rabbitsaviola** [comment]
> It was already asked several times which is a clear indication of it really should be improved.
> 
> I see a good way to add it to the code but not sure about the API. Simply allow 0...3600 deg as input (for 0.1 deg resolution)?

0..3600 is ok for me. Our gpu inteface also uses this as input.

**Comment by kisvegabor** [comment]
Okay, I'll try it today or tomorrow.

**Comment by kisvegabor** [comment]
@rabbitsaviola 
I've just added it. See https://github.com/littlevgl/lvgl/commit/759c4ccb35d053e926e9aa7056614b9755ee2e15

**Comment by rabbitsaviola** [comment]
@kisvegabor 
I've just tried it. It works fine. :+1:

**Comment by kisvegabor** [comment]
Great!
