### ISSUE TITLE
QUESTION : AUTO REFRESH LABEL

### ISSUE THREAD

**Issue by Anarakofona** [lvgl/lvgl#140]
Hi,
I'm new in little VGL.

Is it possible to auto-refresh a label on the screen?
I'm working with PC-Simulator and I create file for every screen that I create. In these screen, I put date (that a get from the Windows OS).
Is there a way to auto refresh the date label? Because in my case it's not refreshed automaticaly when I launch the app.

Thank you very much

**Comment by curly-brace** [comment]
where do you put your date?
i believe there is no built-in way to do it. but may be i am wrong tho. i'm new to LVGL too.
but you can just create a function with which you will set new date in your app, and this function will not only set needed variable, but also update the label for you.
there is also another way, to update the label every ms, but it can produce (and will produce) flickering.

**Comment by kisvegabor** [comment]
Hi,

LittlevGL has a simple task system which can call functions periodically and also consider a priority. You can use this to periodically set the label's text to the new data/time.

```c
/*Call `my_refr_func` in every 1000 ms with a LOW priority, (NULL is an optional parameter to the function*/
lv_task_create(my_refr_func, 1000, LV_TASK_PRIO_LOW, NULL);

...

/*This function wil be called periodically to refresh the label*/
void my_refr_func(void* p)
{
    lv_label_set_text(my_label, "time and date");
}

```
 
Or you can create an `lv_task`.

**Comment by Anarakofona** [comment]
Ok, Thank you for your help

It work perfectly

**Comment by kisvegabor** [comment]
Awesome :)

**Comment by Techseeker-404** [comment]
> Hi,
> 
> LittlevGL has a simple task system which can call functions periodically and also consider a priority. You can use this to periodically set the label's text to the new data/time.
> 
> ```c
> /*Call `my_refr_func` in every 1000 ms with a LOW priority, (NULL is an optional parameter to the function*/
> lv_task_create(my_refr_func, 1000, LV_TASK_PRIO_LOW, NULL);
> 
> ...
> 
> /*This function wil be called periodically to refresh the label*/
> void my_refr_func(void* p)
> {
>     lv_label_set_text(my_label, "time and date");
> }
> ```
> 
> Or you can create an `lv_task`.

Hey noobie here ,facing a similar sort of issue . Is there any way to solve it in version 8.2.
Seems like tasks is not available in Version 8.2

**Comment by kisvegabor** [comment]
> Hey noobie here ,facing a similar sort of issue . Is there any way to solve it in version 8.2.

Sort of :slightly_smiling_face: 
Recently I use [lv_msg](https://docs.lvgl.io/master/others/msg.html) to create API for the UIs I'm working on. You can subscribe to any variables, and when the variable changes the subscribed objects will be notified.

**Comment by Techseeker-404** [comment]
> > Hey noobie here ,facing a similar sort of issue . Is there any way to solve it in version 8.2.
> 
> Sort of 🙂 Recently I use [lv_msg](https://docs.lvgl.io/master/others/msg.html) to create API for the UIs I'm working on. You can subscribe to any variables, and when the variable changes the subscribed objects will be notified.

Thanks a lot 😃 .This is something what I am looking for
