### ISSUE TITLE
7.0-dev roller selected value overwrite

### ISSUE THREAD

**Issue by mathisloge** [lvgl/lvgl#1401]
**Describe the bug**

If we dont have a keyboard or an encoder, the roller selected option would be set to 0, in case of a release event
https://github.com/littlevgl/lvgl/blob/dev-7.0/src/lv_widgets/lv_roller.c#L760
https://github.com/littlevgl/lvgl/blob/dev-7.0/src/lv_widgets/lv_roller.c#L783

**Expected behavior**

The behavior should not change to 0

**Proposed solution**

Move the lv_roller_set_selected into the if(lv_indev_get_type(indev) == LV_INDEV_TYPE_POINTER || lv_indev_get_type(indev) == LV_INDEV_TYPE_BUTTON) scope?

**Comment by embeddedt** [comment]
Thanks for the report! I've fixed it in the commit referenced above.
