### ISSUE TITLE
[dev 7.0] compressed fonts show warning when printing a space

### ISSUE THREAD

**Issue by xennex22** [lvgl/lvgl#1407]
If you generate fonts with compression on then you get a warning in lv_draw_letter() about a character bitmap not found.
Everything draw ok - a space just advances the x position without any drawing.

Here's my workaround in lv_draw_letter()
```
/* don't draw anything if the character is empty eg space */
if((g.box_h == 0) && (g.box_w == 0))
    return;
```

Also, can you make the font_dsc declaration const in the font generator?  I put fonts in SPIFI which requires the compiler to treat it as RO memory.

**Comment by kisvegabor** [comment]
I've fixed as you suggested.

Thank you!

**Comment by xennex22** [comment]
Thank you.
