### ISSUE TITLE
use 2 framebuffers

### ISSUE THREAD

**Issue by ArsBinarii** [lvgl/lvgl#1410]
Is there a way to use 2 framebuffers?

**Comment by embeddedt** [comment]
Have a look at the [display buffer documentation](https://docs.littlevgl.com/en/html/porting/display.html#display-buffer).

----------------------
We use GitHub issues for development related discussions.
Please use the [forum](https://forum.littlevgl.com/) to ask questions.

It's possible to sign in to the forum with your GitHub account... you don't need to make a separate account.

**Comment by ArsBinarii** [comment]
hey @embeddedt not really helpful  I want to use 2 framebuffers not use 2 buffers for the display. I literally want to init /dev/fb0 and /dev/fb1 and then draw on the 2 screens.

**Comment by C47D** [comment]
Maybe this (https://forum.littlevgl.com/t/linux-drm-raspberry-pi4b/1845) can help? I haven't used lvgl on linux based machines tho.

**Comment by embeddedt** [comment]
Ah, in that case you would need to tweak the `fbdev` driver to handle multiple `/dev/fb` devices being used (right now it assumes there is just one). Then you can just register a second display with LittlevGL.

**Comment by ArsBinarii** [comment]
hey, nope, I am working on the RPI zero I do have a /dev/fb0 which is the original output and a tft display on fb1 and due to some limitations of some sofware I need to draw and both framebuffers

**Comment by embeddedt** [comment]
I think what I suggested above will do what you want.

**Comment by kisvegabor** [comment]
As @embeddedt mentioned you can treat the 2 frame buffers as 2 displays. So LittlevGL multi-display support could be used here: https://docs.littlevgl.com/en/html/overview/display.html#
