### ISSUE TITLE
[dev7.0] Latest lv_draw_blend.c introduces artifacts

### ISSUE THREAD

**Issue by fvanroie** [lvgl/lvgl#1417]
**Describe the bug**

I have started testing the dev-7.0 local style system and have achieved good results. But commit https://github.com/littlevgl/lvgl/commit/f9edf0b341984dd28b1c3e162220b430cf6ee9ac introduces vertical artifacts in some of the the widgets. 

**To Reproduce**

I updated from 2a1db9ee to 523c9793 which introduced visible vertical artifacts. I traced it back to file `lv_draw\lv_draw_blend.c` and reverting to the previous version of that file fixes the issue.

**Expected behavior**

Get rid of the vertical artifacts.

**Screenshots**
On top is the previous version 2a1db9ee. And at the bottom the latest 523c9793 with the issue.
![image](https://user-images.githubusercontent.com/15969459/77377557-b7c48e00-6d73-11ea-8e6b-25f89e6bd633.png)

**Additional context**

I experienced the issue on ESP8266 and ESP32. It seems there is bug in the latest lv_draw_blend.c update. I haven't verified in the simulator, but if needed I can run a test there as well.

**Comment by barbiani** [comment]
Simulator @16bpp shows the same here.

**Comment by kisvegabor** [comment]
Thank you for the detailed report. I've just fixed it in ec57e921

Does it work well for you too?

**Comment by fvanroie** [comment]
I confirm the problem is indeed resolved now.
Thank you for the fast response @kisvegabor.

**Comment by kisvegabor** [comment]
Great! Thank you for the feedback!
