### ISSUE TITLE
[dev-7.0] lv_theme_material.c fails to compile in specific case

### ISSUE THREAD

**Issue by fvanroie** [lvgl/lvgl#1419]
**Description**

When `lv_conf.h`is defined with `LV_USE_WIN 1` and `LV_USE_TABVIEW 0` then lv_theme_material.c fails to compile.

lv_theme_material_apply() uses &tabview styles for Window style.

**To Reproduce**

In lv_conf.h:
```
#define LV_USE_TABVIEW 0
#define LV_USE_WIN 1
```

**Expected behavior**

Window style should not have a dependency on Tabview style.

**Screenshots**
![image](https://user-images.githubusercontent.com/15969459/77550409-61f60000-6eb1-11ea-8550-f4071aa97f69.png)

**Additional context**

There are references to `&tabview_btns`, `&tabview_btns_bg` and `&tabview_page_scrl`  here: https://github.com/littlevgl/lvgl/blob/242eaa708d447812e2062d56e61a38195c11e8ba/src/lv_themes/lv_theme_material.c#L1254-L1278

When LV_USE_WIN=1 and LV_USE_TABVIEW=0, the styles `tabview_btns`, `tabview_btns_bg` and `tabview_page_scrl` do not exist.

**Comment by kisvegabor** [comment]
Thanks for the report! I've just fixed it.
