### ISSUE TITLE
LV_INDEV_POINT_MARKER bug?

### ISSUE THREAD

**Issue by curly-brace** [lvgl/lvgl#142]
i'm not sure whether it is a bug, but i don't know how to check whether everything is working as expected (may be i missed something again).
currently i've managed to make my touchscreen working and i was testing its precession with this very useful debug feature that was drawing dots.
but i was always getting cropped output. dots weren't drawn lower then 230 pixels in y (strange that it is not cropped at 255 btw).
at first i double checked the calibration functions, because i was thinking that it needs more resolution (like 64 bits), but it was not the reason.
and i've added a label to display actual coords, and i saw that touchscreen readings are correct across the whole screen. it is only this debug feature that draws on cropped screen.
the only thing that came to my mind, that the size of the default screen was not right and i've set it to the size of my screen, but i did bot helped.
it does not actually looks like the orientation is wrong, because the width of the screen is 240, not 230.
but i'm not sure about orientation tho.. don't know where to check. but buttons and labels are drawn fine and buttons are getting input as expected even in the bottom of the screen. only dots aren't drawn there.

**Comment by kisvegabor** [comment]
Hi,

I checked it an really found a bug in the library! 
`LV_INDEV_POINT_MARKER` uses the `lv_rfill` function from *lv_draw/lv_draw_rbasic.c* . Here you will find this line: 
```c
        lv_area_set(&scr_area, 0, 0, LV_HOR_RES - 1, LV_HOR_RES - 1);
```

It should be:
```c
        lv_area_set(&scr_area, 0, 0, LV_HOR_RES - 1, LV_VER_RES - 1);
```

I never experienced this because typically I use landscape displays where LV_HOR_RES > LV_VER_RES.
I fixed this bug in `dev-5.1` branch for the upcoming 5.1 release.
