### ISSUE TITLE
Drag TabView On Any View？

### ISSUE THREAD

**Issue by ytm52513** [lvgl/lvgl#1426]
Tab3 has a lmeter view. It is now in the red area, You cannot slide to tab2. You can only drag outside the red area. How to set it to be draggable in the red area?
![QQ截图20200331192601](https://user-images.githubusercontent.com/11881904/78138224-2df28000-7459-11ea-892b-0d6c58c01767.png)

**Comment by ytm52513** [comment]
The red area is the size of the lmeter view.

**Comment by ytm52513** [comment]
![20200331192601](https://user-images.githubusercontent.com/11881904/78138628-d3a5ef00-7459-11ea-95d9-2b284bf4e631.png)

**Comment by embeddedt** [comment]
`lv_obj_set_click(lmeter, false)` should work. It will make all input events pass through the meter to the tabview surface.

----------------------
We use GitHub issues for development related discussions.
Please use the [forum](https://forum.littlevgl.com/) to ask questions.

It's possible to sign in to the forum with your GitHub account... you don't need to make a separate account.
