### ISSUE TITLE
long press the keyboard backspace key to delete char leads to segmentation fault.

### ISSUE THREAD

**Issue by incity** [lvgl/lvgl#1429]
long press the keyboard backspace key to delete char leads to segmentation fault.
![image](https://user-images.githubusercontent.com/7846605/78231806-f2fa5600-7505-11ea-83d0-4f8b9fcdb389.png)

**Comment by kisvegabor** [comment]
Have you found the issue? If so could you describe it to help others?

**Comment by incity** [comment]
> Have you found the issue? If so could you describe it to help others?

i just pull the latest code, and it's ok now.

i used this lv_sim_eclipse_sdl before, the lvgl @ 71be75b has this bug.

**Comment by kisvegabor** [comment]
Great, thank you!
