### ISSUE TITLE
Mono theme bug

### ISSUE THREAD

**Issue by incity** [lvgl/lvgl#1430]
OpenLV_THEME_LIVE_UPDATE, and switch to Mono theme:

![image](https://user-images.githubusercontent.com/7846605/78314406-72326d00-758c-11ea-9728-1074e821f0a9.png)

**Comment by kisvegabor** [comment]
Hi,

Thank you for the report. Do you see it if you normally use the mono theme? (i.e. not in the demo).

If it works well during normal usage I'd like to leave it because in the new version this dem will be removed.
