### ISSUE TITLE
Dev-7.0 Compiler warning

### ISSUE THREAD

**Issue by pete-pjb** [lvgl/lvgl#1431]
Hi Gabor,

Your most recent build of the Dev-7.0 code has introduced a compiler warning...

Upon inspection it seems you may have left a test define in lv_linemeter.c

I think you probably want to delete line 22 of this file:

```#define LV_LINEMETER_PRECISE    0      /*Draw line more precisely at cost of performance*/```

**To Reproduce**

Just build library...

**Expected behavior**

No warnings....

Sorry I am unable to do a pull request right now as I have a PC issue.

Hope this is helpful.

Kind Regards,

Pete

**Comment by kisvegabor** [comment]
Hi Pepe,

Thank you for the report.  I've just fixed it.

**Comment by pete-pjb** [comment]
You're Welcome :-)
