### ISSUE TITLE
OFFSETs

### ISSUE THREAD

**Issue by denruss** [lvgl/lvgl#1434]
Hi 

I have LH114T display. It is work fine on TFT_eSPI.
But the image is shifted if i use lvgl.
How to adjust the offsets? just as it is done in the library for Arduino

https://github.com/Bodmer/TFT_eSPI/blob/master/TFT_eSPI.cpp

#ifdef CGRAM_OFFSET
  tft_settings.r0_x_offset = colstart;
  tft_settings.r0_y_offset = rowstart;

**Comment by kisvegabor** [comment]
We use GitHub Issues for development-related discussions.

Please ask your question in the [Forum](https://forumtest.littlevgl.com/) to make it visible for a larger community. You can simply log in with your GitHub account.

A screenshot and codespippet from your driver would be helpful!
