### ISSUE TITLE
Help

### ISSUE THREAD

**Issue by sebulica** [lvgl/lvgl#1443]
Hi
I am new to programming and i just want to see that the display works with the stm32f103b6 as i have found here.I have a tft lcd shield 3.2" from open smart,and i guess it should work fine.I tested the display shield on a mega2560 and it's ok.Can you point me out how to wire up the stm32 with the lcd shield so i can test the lvgl_test.hex ?

I took a look inside the hx8352b.h and found how you defined the pins,but i can't find nowhere the pin asignation of gpio_pin_0.Sorry for being dumb but i need some help :).

**Comment by kisvegabor** [comment]
Hi,

We use GitHub Issues for development-related discussions.

Please ask your question in the [Forum](https://forumtest.littlevgl.com/) to make it visible for a larger community. You can simply log in with your GitHub account.
