### ISSUE TITLE
dev-7.0 color_blend_true_color_additive() 8-bit and 32 bit green channel

### ISSUE THREAD

**Issue by TGoyen** [lvgl/lvgl#1444]
color_blend_true_color_additive() contains an error in the Green channel

#if LV_COLOR_DEPTH == 8
    fg.ch.green = LV_MATH_MIN(tmp, 7);
#elif LV_COLOR_DEPTH == 16
#if LV_COLOR_16_SWAP == 0
    **tmp = bg.ch.green + fg.ch.green;**

should be

**tmp = bg.ch.green + fg.ch.green;**
#if LV_COLOR_DEPTH == 8
    fg.ch.green = LV_MATH_MIN(tmp, 7);
#elif LV_COLOR_DEPTH == 16
#if LV_COLOR_16_SWAP == 0

**Comment by kisvegabor** [comment]
Could you send a pull request?

**Comment by kisvegabor** [comment]
I've just noticed that you have already sent one.

Thank you!
