### ISSUE TITLE
Despite documentation, body opacity determines arc opacity

### ISSUE THREAD

**Issue by dykeag** [lvgl/lvgl#1451]
I am not sure if it is a bug or if it is intentional, but when drawing an arc (lv_draw_arc), the opactity from `style->body.opa` is used to determine the opacity of the line drawn. I has assumed that `style->line.opa` would have been used since the other parameters for the arc are taken from `style->line`

The real problem is that the [documentation for arcs](https://docs.littlevgl.com/en/html/object-types/arc.html) does not mention that this is the behaviour. 

Either the code or the documentation should be changed.

**Comment by embeddedt** [comment]
The style system is being rewritten in 7.0 and I'm not sure if this will still be an issue there, so I think updating the documentation makes more sense. @kisvegabor Do you agree?

**Comment by kisvegabor** [comment]
@embeddedt Yes, I agree. 
I've just updated the docs.
