### ISSUE TITLE
[Dev7.0] cpicker rectangle does not draw over 360 px

### ISSUE THREAD

**Issue by xennex22** [lvgl/lvgl#1464]
A cpicker of type `LV_CPICKER_TYPE_RECT` does not draw correctly if it is wider than 360 pixels.

![cpicker-quant](https://user-images.githubusercontent.com/25083624/79695845-ea0bc300-822d-11ea-85e9-edf63a06f82b.png)

The problem is that the loop to draw the graduated colors makes each color rectangle `i_step` wide which is unrelated to the actual pixel width of the widget.
```
rect_area.x2 = rect_area.x1 + i_step;
```

We could make the quantization 1.
```
uint16_t i_step = LV_MATH_MAX(1, 360 / grad_w);
```
![cpicker-quant-1](https://user-images.githubusercontent.com/25083624/79695932-74542700-822e-11ea-832e-5f5f685179e8.png)

But probably the idea is to reduce the rectangles so the loop x2 calculation needs to be changed
```
lv_coord_t xi2 = ((i+i_step) * grad_w) / 360;
rect_area.x2 = LV_MATH_MIN(grad_area.x1 + xi2, grad_area.x1 + grad_w - i_step);
```
![cpicker-quant-3](https://user-images.githubusercontent.com/25083624/79696226-41ab2e00-8230-11ea-9ec8-1ed999154144.png)

Also I think we need to look at the double click behavior, which I had to disable.

**Comment by embeddedt** [comment]
Can you send a pull request with the second fix?

**Comment by xennex22** [comment]
Ok.  Still learning with github and I'm trying to find a way to do this efficiently so I don't have to do endless offline diffs with the other changes I have made.

**Comment by xennex22** [comment]
Thanks.
