### ISSUE TITLE
[v7.0] 'struct <anonymous>' has no member named 'green';

### ISSUE THREAD

**Issue by KammutierSpule** [lvgl/lvgl#1466]
**Describe the bug**

Cannot build branch v7

**To Reproduce**

**Expected behavior**

**Screenshots**

**Additional context**

lvgl/src/lv_draw/lv_draw_blend.c:863:31: error: 'struct <anonymous>' has no member named 'green'; did you mean 'green_h'?

Is that related with #802 ?

**Comment by kisvegabor** [comment]
Just fixed it, thank you!

Also updated the build test, to cover this configuration too.
