### ISSUE TITLE
V7 fault at lv_debug_check_obj_type

### ISSUE THREAD

**Issue by KammutierSpule** [lvgl/lvgl#1467]
**Describe the bug**

System fault in function lv_debug_check_obj_type
line66: if(strcmp(types.type[i], obj_type) == 0) return true;
i = 4

should it be added:
`if(obj_type[i] == '\0') continue;`
?

**Screenshots**
![image](https://user-images.githubusercontent.com/1185982/79990940-91485e80-84a9-11ea-97b1-fca609dbd60d.png)

![image](https://user-images.githubusercontent.com/1185982/79991008-ab823c80-84a9-11ea-9b3f-3f38a2268c33.png)

**Additional context**

**Comment by embeddedt** [comment]
Should be fixed in `dev-7.0`.
