### ISSUE TITLE
Style animation activation and deactivation

### ISSUE THREAD

**Issue by EmrahAktas** [lvgl/lvgl#149]
Hi,
I have implemented style animation to label that fade in and fade out continuously.But I want to control this animation according to screen changes.For example when the next button clicked current label or image should fade out and invisible then next label or image should fade in.

Is that possible?

**Comment by kisvegabor** [comment]
Hi,

yes it is possible. You can start the style animation in the action function of a button.

**Comment by kisvegabor** [comment]
I hope the answer was useful for you.
Now I close this issue but is you have any remarks feel free to reopen it!
