### ISSUE TITLE
Crash when setting label dynamic text to same as prior static text

### ISSUE THREAD

**Issue by BillHargen** [lvgl/lvgl#1498]
**Describe the bug**

LVGL crashes when setting the text of a label to the same address as was used for setting static text.

**To Reproduce**

```c
lv_label_set_static_text(label_obj, "FOO");
lv_label_set_text(label_obj, "FOO");
```

**Additional context**

The `lv_label_set_text()` routine has some interesting logic to apparently allow modification of a previously set text value.  (This seems contrary to the API, but perhaps it is used in certain special cases.)  The problem is that this code block calls `lv_mem_realloc()` for the prior text address, which is a really bad thing to do if the prior text was set as static text.  In my case, it wasn't just statically allocated but also in flash memory.

Here is the code block from within `lv_label_setText()`:
```c
    if(ext->text == text) {
        /*If set its own text then reallocate it (maybe its size changed)*/
        ext->text = lv_mem_realloc(ext->text, strlen(ext->text) + 1);
        LV_ASSERT_MEM(ext->text);
        if(ext->text == NULL) return;
    } else {
```

The following fixes the problem:
```c
    if(ext->text == text && ext->static_txt == 0) {
```

Version 7 appears to have the same issue.  I will submit a pull request for version 6 with this change.

**Comment by embeddedt** [comment]
Merged into `dev-7.0` in https://github.com/littlevgl/lvgl/commit/6e1d53e11e4ca00331eb2b7aaf069b9a23f22190.
