### ISSUE TITLE
lvgl render object display abnormal

### ISSUE THREAD

**Issue by lgl88911** [lvgl/lvgl#1504]
I test in RGB565 LCD panel of embed platfrom, all lvgl object display abnormal.The same code is displayed normally on SDL of Emulator,  I think the two differ only in color format。
You can see this phenomenon from the picture below, it seems that the lvgl object is covered with some color bars
![1883524997](https://user-images.githubusercontent.com/3456246/82152483-10a43480-9894-11ea-8b31-9d3ede86bd85.jpg)

Can you give me some suggestions? I am using lvgl for the first time and there is no direction for debugging， Thanks so much!

**Comment by barbiani** [comment]
Check the invert 16 bit color for spi devices in the config file.

**Comment by lgl88911** [comment]
@barbiani  Thanks for your reply
I config below
```
#define LV_COLOR_16_SWAP 1
```
The graphics using lvgl color are not normal，I use the RGB interface LCD ，So there shouldn't be a problem invert 16 bit color for spi devices
![887384784](https://user-images.githubusercontent.com/3456246/82207894-27529600-993d-11ea-9f78-84032cc91981.jpg)

**Comment by kisvegabor** [comment]
@lgl88911 It's hard to decide but I'm not sure that the "working LV_COLOR_BLUE" is really the brightest blue. Can you draw a box next to "seems to be good" blue rectangle like this:
```c
for(i = 0; i < 0xffff; i+= 4) {
  your_box_draw(10, 10, 20, 20, i);
}
```

and see is there is a more blue color?

**Comment by lgl88911** [comment]
@kisvegabor Thanks for your reply！
I'm not too sure what you mean. LV_COLOR_BULE looks OK for me
The problem I encountered was that the object displayed abnormally. Can you tell me what kind of problem the experiment you want is to check?

I assume you want to see all the blue. For RGB565, I have drawn the colors 0x0000 ~ 0x001F. These cover all the blue. You can see this color bar in the middle of the picture below

![webwxgetmsgimg](https://user-images.githubusercontent.com/3456246/82330526-8e437e00-9a15-11ea-9c06-c18c860e5162.jpeg)

the test code is
```
for(int i = 0; i<0x01f; i++){

			for(int j=0; j<BUF_W*BUF_H; j++){
				color[j] = i;
			}

				desc.buf_size = 20 * 2U * 20;
				desc.width = 20;
				desc.pitch = 20;
				desc.height = 40;


				display_write(display_device, 50+i*20, 180, &desc, buf);
		}
```

**Comment by kisvegabor** [comment]
I meant it's hard to decide if its 100% blue or 80%. But your gradient image confirms that it's fine. Can you do the same with red and green too?

**Comment by lgl88911** [comment]
@kisvegabor Thanks so much! 
Thanks to your extensive experience, it seems that the problem has been found, RED is abnormal.
In order to distinguish red errors more clearly, I added a gap between each color.
I think this may be a problem with the driver or hardware connection. I am checking the related content. If you have further suggestions, I will be very grateful.

![1942993623](https://user-images.githubusercontent.com/3456246/82336446-2ee96c00-9a1d-11ea-8954-6e3ec5f6491f.jpg)


```
			u16_t *colorg = buf;
		for(int i = 0; i<0x3f; i++){

			for(int j=0; j<BUF_W*BUF_H; j++){
				colorg[j] = i<<5;
			}

				desc.buf_size = 10 * 2U * 20;
				desc.width = 10;
				desc.pitch = 10;
				desc.height = 40;


				display_write(display_device, 50+i*10, 230, &desc, buf);
		}

			u16_t *colorr = buf;
		for(int i = 0; i<0x01f; i++){

			for(int j=0; j<BUF_W*BUF_H; j++){
				colorr[j] = i<<11;
			}
				printf("r %04x\n", colorr[0]);
				desc.buf_size = 20 * 2U * 20;
				desc.width = 20;
				desc.pitch = 20;
				desc.height = 40;


				display_write(display_device, 50+i*22, 280, &desc, buf);
		}
```

**Comment by embeddedt** [comment]
Perhaps you have some parallel interface wires swapped? I don't know how your display connects to the main board.

**Comment by lgl88911** [comment]
@embeddedt 
Indeed, It's connects error, I have fixed it. Now work well, Thanks so much
![1144937728](https://user-images.githubusercontent.com/3456246/82342756-99ea7100-9a24-11ea-9882-6c698ec0d7a8.jpg)
![1056248697](https://user-images.githubusercontent.com/3456246/82342772-9d7df800-9a24-11ea-9e01-3dab6d2fc387.jpg)

**Comment by kisvegabor** [comment]
Great! :slightly_smiling_face:

**Comment by lgl88911** [comment]
@kisvegabor @embeddedt @barbiani Thanks for your help!
