### ISSUE TITLE
Invalid assertion in lv_keyboard_set_textarea

### ISSUE THREAD

**Issue by embig71** [lvgl/lvgl#1505]
**Describe the bug**

In lv_keyboard_set_textarea object name compared with "lv_ta"
```c
void lv_keyboard_set_textarea(lv_obj_t * kb, lv_obj_t * ta)
{
    LV_ASSERT_OBJ(kb, LV_OBJX_NAME);
    if(ta) LV_ASSERT_OBJ(ta, "lv_ta");

```
But in lv_text_area.c the object name is declared as: 
```c
#define LV_OBJX_NAME "lv_textarea"
```
The names of the objects must be the same. I.e:
```c
    LV_ASSERT_OBJ(kb, LV_OBJX_NAME);
    if(ta) LV_ASSERT_OBJ(ta, "lv_textarea");
```

**To Reproduce**

Enable LV_USE_DEBUG and LV_USE_ASSERT_OBJ

**Expected behavior**

Assert's correct behavior

**Screenshots**

**Additional context**

**Comment by kisvegabor** [comment]
Hi,

I fixed it here: 382f428a.
Thank you!
