### ISSUE TITLE
Link error (Makefile)

### ISSUE THREAD

**Issue by tritol** [lvgl/lvgl#1508]
> # Important: issues that don't use this template will be ignored/closed.

**Describe the bug**

Make build system doesn't work. Link fails with:
/usr/bin/ld: lv_txt_ap.o: in function `_lv_txt_ap_calc_bytes_cnt':
lv_txt_ap.c:(.text+0x0): multiple definition of `_lv_txt_ap_calc_bytes_cnt'; lv_txt_ap.o:lv_txt_ap.c:(.text+0x0): first defined here
/usr/bin/ld: lv_txt_ap.o:(.rodata+0x0): multiple definition of `ap_chars_map'; lv_txt_ap.o:(.rodata+0x0): first defined here
/usr/bin/ld: lv_txt_ap.o: in function `_lv_txt_ap_proc':
lv_txt_ap.c:(.text+0x100): multiple definition of `_lv_txt_ap_proc'; lv_txt_ap.o:lv_txt_ap.c:(.text+0x100): first defined here
collect2: error: ld returned 1 exit status

**To Reproduce**

`make` in actual pc_simulator_sdl_eclipse

**Expected behavior**

Link without error ;-)

**Screenshots**
N/A

**Additional context**

Error is in src/lv_misc/lv_misc.mk where lv_txt_ap.c is added twice

**Comment by kisvegabor** [comment]
I fixed it, thank you!
