### ISSUE TITLE
website/blog link issue

### ISSUE THREAD

**Issue by trollcop** [lvgl/lvgl#1512]
> # Important: issues that don't use this template will be ignored/closed.

Link to 'complete project' from lvgl blog is incorrect.

1. open https://blog.lvgl.io/2018-01-03/linux_fb#download-a-ready-to-use-project
2. click the In "lv_port_linux_frame_buffer" repository link
3. the link leads to https://github.com/lvgl/lv_port_linux_frame_bufferr (notice extra 'R' at end)
4. observe 404 error from github

Please provide a small, independent code sample that can be used to reproduce the issue. Ideally this should work in the PC simulator unless the problem is specific to one platform.

Same as above.

It should go to https://github.com/lvgl/lv_port_linux_frame_buffer as intended.

Thanks

**Comment by embeddedt** [comment]
Fixed in https://github.com/lvgl/blog/commit/84a99ce4053073993c8931a70e4a4fe0d466056d.

**Comment by multitab2022** [comment]
I was worried because the contents of the blog were not compiled.
https://blog.lvgl.io/2018-01-03/linux_fb
- main.c

Thank you for the information.

https://github.com/lvgl/lv_port_linux_frame_buffer
