### ISSUE TITLE
imgbtn have an out-of-bounds condition in function 'lv_imgbtn_set_src'

### ISSUE THREAD

**Issue by heyhachi0** [lvgl/lvgl#1517]
this statement : ext->img_src_mid[state] = src;
img_src_mid have an out-of-bounds condition while state value is LV_BTN_STATE_DISABLED(0x80)

**Comment by embeddedt** [comment]
This should have been solved in #1472, but the commit mentioned there (https://github.com/lvgl/lvgl/commit/4401ad874d3816e578122e36da587214bd336a6a) seems to be missing in all branches.

@kisvegabor Did this commit get lost through merging?

**Comment by kisvegabor** [comment]
I have no idea what happened. I've cherry-picked that commit and added again.

**Comment by heyhachi0** [comment]
ok. I will close this issue.
