### ISSUE TITLE
Add LV_CHART_PART_SERIES_BG to Docs

### ISSUE THREAD

**Issue by maxpromer** [lvgl/lvgl#1518]
**Describe the bug**

I needs to change division line width in chart widgets so i read it.

> The background of the series is called LV_CHART_PART_SERIES and it’s placed on the main background. The division lines, and series data is drawn on this part. Besides the typical background style properties the line style properties are used by the division lines. The padding values tells the space between the this part and the axis texts.

(from https://docs.lvgl.io/v7/en/html/widgets/chart.html)

so i use it code for test.

```c++
lv_obj_set_style_local_line_color(chart1, LV_CHART_PART_SERIES, LV_STATE_DEFAULT, lv_color_hex(0xEEEEEE));
lv_obj_set_style_local_line_width(chart1, LV_CHART_PART_SERIES, LV_STATE_DEFAULT, 10);
lv_obj_set_style_local_line_dash_width(chart1, LV_CHART_PART_SERIES, LV_STATE_DEFAULT, 40);
lv_obj_set_style_local_line_dash_gap(chart1, LV_CHART_PART_SERIES, LV_STATE_DEFAULT, 10);
```

but not work, not  things change. so i try to read you code in `lv_theme_material.c` i see it

https://github.com/lvgl/lvgl/blob/b10dece511a376f4f63460167eadfb17c8f9792a/src/lv_themes/lv_theme_material.c#L1278

i not found `LV_CHART_PART_SERIES_BG` in you docs.

i try use it code for test and it work !

```c++
    lv_obj_set_style_local_line_color(chart1, LV_CHART_PART_SERIES_BG, LV_STATE_DEFAULT, lv_color_hex(0xEEEEEE));
    lv_obj_set_style_local_line_width(chart1, LV_CHART_PART_SERIES_BG, LV_STATE_DEFAULT, 10);
    lv_obj_set_style_local_line_dash_width(chart1, LV_CHART_PART_SERIES_BG, LV_STATE_DEFAULT, 40);
    lv_obj_set_style_local_line_dash_gap(chart1, LV_CHART_PART_SERIES_BG, LV_STATE_DEFAULT, 10);
```

so plz add `LV_CHART_PART_SERIES_BG` to docs.

**To Reproduce**

.....

**Expected behavior**

.....

**Screenshots**

....

**Additional context**

Thank for work hard !

**Comment by kisvegabor** [comment]
I've fixed it, thank you for the report.
