### ISSUE TITLE
lvgl/src/lv_widgets/lv_cont.c:565:31: error: code will never be executed 

### ISSUE THREAD

**Issue by mharizanov** [lvgl/lvgl#1519]
> # Important: issues that don't use this template will be ignored/closed.

**Describe the bug**

Compilation error on mac, root cause seems to be an odd comparison "if(obj_num == 2 && 0)" making code unreachable:

```
lvgl/src/lv_widgets/lv_cont.c:565:31: error: 
      code will never be executed [-Werror,-Wunreachable-code]
            lv_obj_t * obj1 = child_rs;
                              ^~~~~~~~
lvgl/src/lv_widgets/lv_cont.c:564:28: note: 
      silence by adding parentheses to mark code as explicitly dead
        else if(obj_num == 2 && 0) {
                           ^
                           /* DISABLES CODE */ ( )
```

**To Reproduce**

https://github.com/lvgl/lvgl/blob/1c9830b7155191d030b7c5f9d82bf9f6c27023b2/src/lv_widgets/lv_cont.c#L564

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by kisvegabor** [comment]
Thanks, I've just removed it.
