### ISSUE TITLE
Online convert tools alternative

### ISSUE THREAD

**Issue by BenQoo** [lvgl/lvgl#153]
The image and font covert tools have been ported to website at v5.1.
Would you provide the corresponding offline tools in the future like the older versions?
Because some images and fonts are properties which are not suitable to upload to website.

**Comment by kisvegabor** [comment]
Hi,

I see your problem.
However I'm not planning to maintain an offline tool simultaneously I can add a note to website which states: "The images and fonts are not stored on the website". And really the uploaded images and fonts exist only during the converting process.

Besides if someone would like to create the offline version of the Font and/or Image converter I could provide the PHP scripts as a reference.

**Comment by hreichert** [comment]
@kisvegabor It would be great if you publish the PHP scripts in a git repository, so someone has also the chance to run them locally.

**Comment by WangZhihua1998** [comment]
@kisvegabor If will be helpful if you are willing to release a php script since we can manage to run a php script on *nix systems easily.

**Comment by kisvegabor** [comment]
Okay, if it helps I will publish the php scripts in [lv_utils](https://github.com/littlevgl/lv_utils) repo!

**Comment by kisvegabor** [comment]
I uploaded the scripts to lv_utils. They are not so well formatted like LittlevGL because I didn't ment to publish them :)

**Comment by kisvegabor** [comment]
I updated the scripts and readme to make offline conversion easier.
Please have a look at it!

**Comment by kisvegabor** [comment]
As the offline tools are available now I close this issue.
If you have any remarks feel free to reopen it!
