### ISSUE TITLE
Add radial gradient and gradient angle

### ISSUE THREAD

**Issue by kisvegabor** [lvgl/lvgl#1534]
Hi,

Now LVGL supports horizontal and vertical gradient. 

It'd be great to support radial gradient and angle for linear gradient. 
Here is a tool to generate these type of gradients in CSS gradients: https://angrytools.com/gradient/

Now the [grad_get](https://github.com/lvgl/lvgl/blob/ec5b10142f367ba204bc2bdb8ce867ef9969b34d/src/lv_draw/lv_draw_rect.c#L577) function is used to calculate gradient.

These are the steps I see now:
- [ ] How to describe the more complex gradient types in the styles?
- [ ] Implement linear rotated gradient
- [ ] Implement radial gradient

Contribution is very welcome in this feature. If you have any ideas or you are interested in contributing to this feature, feel free to comment here!

**Comment by embeddedt** [comment]
I suggest that a new enum property be added called `lv_gradient_type_t`. It can be set to `LV_GRADIENT_LINEAR` or `LV_GRADIENT_RADIAL`. There'd also need to be a new integer property for the angle, but it can be ignored for radial gradients.

**Comment by kisvegabor** [comment]
In CSS there are some properties for radial-gradient too:
- size: farthest-corner (default), closest-side, closest-corner, farthest-side
- position

I'm not sure we need to support all the size types but position would be nice.
Or we could do it differently by defining:
- position: center position in percentage of width and height?
- radius: somehow make possible to use px and %

What do you think?

**Comment by embeddedt** [comment]
> What do you think?

I like the second approach (position and radius).

For the issue of handling pixels vs percentages, I have an idea. Why don't we take advantage of the fact that `lv_coord_t` can be negative, and consider values that are less than 0 to be percentages? (We can `#define LV_COORD_PERCENT(x) (-(x))` to make it more understandable.)

**Comment by scvetic** [comment]
Hi,
I thing is best to using two point to define radius or linear vector.

Four month ago for one project I need to implement some radial and linear gauge on embedded platform, for that purpose me need gradient and polygon filling, similar to BeauGauge ActiveX control.
Two month ago I first time see LVGL library and start to test gradient and polygon functions. I'm using idea from cairo library.

![1](https://user-images.githubusercontent.com/66142993/83307512-2ce59100-a205-11ea-9914-6f795cbd2132.png)
![2](https://user-images.githubusercontent.com/66142993/83307514-2d7e2780-a205-11ea-9c01-11bb621fe3e1.png)
![3](https://user-images.githubusercontent.com/66142993/83307515-2e16be00-a205-11ea-89da-9b62d0348f2f.png)
![4](https://user-images.githubusercontent.com/66142993/83307516-2e16be00-a205-11ea-8a73-b15b8eaa901e.png)


![Screenshot_2020-05-29_23-06-51](https://user-images.githubusercontent.com/66142993/83306120-4df8b280-a202-11ea-95a0-a96b71780129.png)
![Screenshot_2020-05-29_23-07-39](https://user-images.githubusercontent.com/66142993/83306125-4f29df80-a202-11ea-93bd-399f728c0f97.png)
![Screenshot_2020-05-29_23-09-31](https://user-images.githubusercontent.com/66142993/83306126-4fc27600-a202-11ea-9348-3daf8c9ee38c.png)

**Comment by scvetic** [comment]
kisvegabor,
I can send to you codeon your mail, and maybe you can using some of that.

**Comment by kisvegabor** [comment]
That would be awesome!
But could you upload it to GitHub instead of sending it in email?

**Comment by planevina** [comment]
I want this....
