### ISSUE TITLE
lv_win: implement lv_win_add_btn_left()

### ISSUE THREAD

**Issue by kisvegabor** [lvgl/lvgl#1535]
Now `lv_win_add_btn` always adds a button to right. However, on smartphones it's quite common to have e.g. back button on the left. 
![image](https://user-images.githubusercontent.com/7599318/83128381-a2edd900-a0db-11ea-9b1b-10f6a1d703d3.png)

The tasks to make it ready:
- [ ] How to store in the button that it should be the left or right?
- [ ] Add lv_win_add_left based on lv_win_add_btn
- [ ] Update [lv_win_realign](https://github.com/lvgl/lvgl/blob/ec5b10142f367ba204bc2bdb8ce867ef9969b34d/src/lv_widgets/lv_win.c#L638) to position the buttons.

Contribution is very welcome in this feature. If you have any ideas or you are interested in contributing to this feature, feel free to comment here!

**Comment by C47D** [comment]
Hi,

I've started to work about this in [here](https://github.com/C47D/lvgl/tree/add_win_left_button), there's only the `lv_win_add_btn_left` function declaration for now.

> How to store in the button that it should be the left or right?

Do you mean like storing what side of it's parent the button should be aligned to?
If the button only aligns to right or left we could add a boolean or a bitfield into the button ext. property:
```c
/** Extended data of button*/
typedef struct {
    /** Ext. of ancestor*/
    lv_cont_ext_t cont;

    /** 1: Toggle enabled*/
    uint8_t checkable : 1;
   /** Which side of the base or container should the button align to.
    * 0: Align to right (default), 1: Align to left */
    uint8_t alignment_in_par : 1;
} lv_btn_ext_t;
```

Then the setter and getter for it:
```c
void lv_btn_set_alignment_in_par(lv_obj_t * btn, bool alignment_left)
{
    LV_ASSERT_OBJ(btn, LV_OBJX_NAME);

    lv_btn_ext_t * ext = lv_obj_get_ext_attr(btn);

    ext->alignment_in_par = alignment ? 1 : 0;
}

bool lv_btn_get_alignment_in_par(const lv_obj_t * btn)
{
    LV_ASSERT_OBJ(btn, LV_OBJX_NAME);

    lv_btn_ext_t * ext = lv_obj_get_ext_attr(btn);

    return ext->alignment_in_par != 0 ? true : false;
}
```

Update `lv_btn_create` to set the `alignment_in_par` property to the default:
```c
enum {
LV_BTN_ALIGNEMT_IN_PAR_RIGHT = 0,
LV_BTN_ALIGNEMT_IN_PAR_LEFT
}

lv_obj_t * lv_btn_create(lv_obj_t * par, const lv_obj_t * copy)
{
    LV_LOG_TRACE("button create started");

    lv_obj_t * btn;

    btn = lv_cont_create(par, copy);
    LV_ASSERT_MEM(btn);
    if(btn == NULL) return NULL;

    if(ancestor_signal == NULL) ancestor_signal = lv_obj_get_signal_cb(btn);
    if(ancestor_design == NULL) ancestor_design = lv_obj_get_design_cb(btn);

    /*Allocate the extended data*/
    lv_btn_ext_t * ext = lv_obj_allocate_ext_attr(btn, sizeof(lv_btn_ext_t));
    LV_ASSERT_MEM(ext);
    if(ext == NULL) {
        lv_obj_del(btn);
        return NULL;
    }

    ext->checkable = 0;
    ext->alignment_in_par = LV_BTN_ALIGNEMT_IN_PAR_RIGHT;

    lv_obj_set_signal_cb(btn, lv_btn_signal);
    lv_obj_set_design_cb(btn, lv_btn_design);

    /*If no copy do the basic initialization*/
    if(copy == NULL) {
        /*Set layout if the button is not a screen*/
        if(par) {
            lv_obj_set_size(btn, LV_DPI, LV_DPI / 3);
            lv_btn_set_layout(btn, LV_LAYOUT_CENTER);
        }

        lv_obj_set_click(btn, true); /*Be sure the button is clickable*/
        lv_obj_set_alignment_in_par(btn, LV_BTN_ALIGNEMT_IN_PAR_RIGHT); /*Be sure the button is aligned to parent right side*/

        lv_theme_apply(btn, LV_THEME_BTN);
    }
    /*Copy 'copy'*/
    else {
        lv_btn_ext_t * copy_ext = lv_obj_get_ext_attr(copy);
        ext->checkable             = copy_ext->checkable;
        ext->alignment_in_par  = copy_ext->alignment_in_par;

        /*Refresh the style with new signal function*/
        lv_obj_refresh_style(btn, LV_STYLE_PROP_ALL);
    }

    LV_LOG_INFO("button created");

    return btn;
}
```

Then `lv_win_realign` should check it to align the button into the header:
```c
static void lv_win_realign(lv_obj_t * win)
{
    lv_win_ext_t * ext = lv_obj_get_ext_attr(win);

    if(ext->page == NULL || ext->header == NULL) return;

    lv_obj_set_width(ext->header, lv_obj_get_width(win));

    lv_obj_t * btn;
    lv_obj_t * btn_prev = NULL;
    lv_coord_t btn_h = lv_obj_get_height_fit(ext->header);
    lv_coord_t btn_w = ext->btn_w != 0 ? ext->btn_w : btn_h;
    lv_style_int_t header_inner = lv_obj_get_style_pad_inner(win, LV_WIN_PART_HEADER);
    lv_style_int_t header_right = lv_obj_get_style_pad_right(win, LV_WIN_PART_HEADER);
    lv_style_int_t header_left = lv_obj_get_style_pad_left(win, LV_WIN_PART_HEADER);
    /*Refresh the size of all control buttons*/
    btn = lv_obj_get_child_back(ext->header, NULL);
    while(btn != NULL) {
        lv_obj_set_size(btn, btn_h, btn_w);
       
        /* is this the first button? */
        if(btn_prev == NULL) {
            if (LV_BTN_ALIGNEMT_IN_PAR_LEFT == lv_btn_get_alignment_in_par(btn)) {
                lv_obj_align(btn, ext->header, LV_ALIGN_IN_LEFT_MID, header_left, 0);
            } else {
                lv_obj_align(btn, ext->header, LV_ALIGN_IN_RIGHT_MID, -header_right, 0);
            }
        }
        else {
            lv_obj_align(btn, btn_prev, LV_ALIGN_OUT_LEFT_MID, - header_inner, 0);
        }
        btn_prev = btn;
        btn      = lv_obj_get_child_back(ext->header, btn);
    }

    lv_obj_set_pos(ext->header, 0, 0);

    lv_obj_set_size(ext->page, lv_obj_get_width(win), lv_obj_get_height(win) - lv_obj_get_height(ext->header));
    lv_obj_align(ext->page, ext->header, LV_ALIGN_OUT_BOTTOM_LEFT, 0, 0);
}
```

Untested code... are we on the right track? 😄

**Comment by C47D** [comment]
In `lv_win_realign` we should also track if the button is the first button on the left or in the right side of the header, isn't?

**Comment by kisvegabor** [comment]
> I've started to work about this in here, there's only the lv_win_add_btn_left function declaration for now.

Awesome! 

Instead of modifying `lv_btn_ext_t` we can create `lv_winbtn_ext_t` based on `lv_btn_ext_t`. Similarly as `lv_btn_ext_t` is based on `lv_cont_ext_t`.

`lv_winbtn_ext_t` can be local to `lv_win` and contain only an alignment field.

I suggest it because button alignment is not so general for a normal button. 

Regarding the API `lv_win_add_btn(win, img, alignment)` can work IMO.

What do you think?

**Comment by C47D** [comment]
It sounds pretty good, I will add another commit with your suggestions.

**Comment by C47D** [comment]
Hi @kisvegabor,

I've added `lv_win_btn_ext_t` and defined `lv_win_btn_create` in [here](https://github.com/C47D/lvgl/tree/add_win_left_button), I've used the window example and it's not crashing but I'm not sure if `lv_win_btn_create` is properly done, can you take a look at it? It's defined static so it's local in `lv_win`.

I've still have to update the `lv_win_realign` and add setter and getter for the `alignment_in_header` data.

**EDIT**
First implementation of `lv_win_realign` done. How many buttons the header can have?

**Comment by kisvegabor** [comment]
@C47D Let's continue in the PR.

> How many buttons the header can have?

I think we don't need to limit it. If the user adds too many they will overlap, but he needs to take care of it.

**Comment by C47D** [comment]
The PR was merged into the dev branch, should we keep this issue open?

**Comment by embeddedt** [comment]
It will close itself when 7.1 is released.

**Comment by kisvegabor** [comment]
@C47D, could you add few lines about it in the docs?
https://github.com/lvgl/docs/blob/master/v7/en/widgets/win.md

**Comment by C47D** [comment]
Sure, will do.
