### ISSUE TITLE
show png image

### ISSUE THREAD

**Issue by ghost** [lvgl/lvgl#1546]
Jpeg image can be saved as a C array and than lvlgl can show this image. Can we do the same for the png image. I want to add transparent image to the button. Is it also possible use png image for the RGB565 format?

**Comment by embeddedt** [comment]
Choose either "True color with alpha" or "True color chroma keyed" when you convert the PNG image (use the online [image converter](https://lvgl.io/tools/imageconverter)). It should then have a transparent background.

----------------------
We use GitHub issues for development related discussions.
Please use the [forum](https://forum.littlevgl.com/) to ask questions.

It's possible to sign in to the forum with your GitHub account... you don't need to make a separate account.
