### ISSUE TITLE
Add JPG decoder

### ISSUE THREAD

**Issue by kisvegabor** [lvgl/lvgl#1547]
Similarly to the [PNG decoder library based on lodepng](https://github.com/lvgl/lv_lib_lodepng) it'd be great to have a JPG decoder too for LVGL. 

If you are already familiar with a JPG library, it should be straightforward to add it based on the above mentioned PNG library.

A detailed description of LVGL's image decoder interface can be found [here](https://docs.lvgl.io/v7/en/html/overview/image.html#image-decoder).

[Tiny JPED Dec](http://elm-chan.org/fsw/tjpgd/00index.html) looks like a good candidate at first. 

Contribution is very welcome, feel free to comment here if yore interested in creating a JPG decoder interface for LVGL.

**Comment by xennex22** [comment]
Please structure this with STM32 hardware jpeg support in mind.

**Comment by kisvegabor** [comment]
> Please structure this with STM32 hardware jpeg support in mind.
Sure! If you already know it could you point to a minimal example code to see how it works?

**Comment by xennex22** [comment]
Sorry, don't have any working jpeg code yet.  I was thinking more to have a driver interface so that it would be easy to swap between a software driver and hardware driver.  Probably the answer is to make a software image decoder and also a hardware image decoder rather than another driver layer.

**Comment by kisvegabor** [comment]
> Probably the answer is to make a software image decoder and also a hardware image decoder rather than another driver layer.

I agree.

**Comment by kisvegabor** [comment]
@C47D 
Awesome! :slightly_smiling_face: 

Regarding the API: the highest level API should be the image decoder interface of LVGL. It looks like this in [PNG decoder](https://github.com/lvgl/lv_lib_lodepng/blob/master/lv_lodepng.c#L45-L51).
For the lower-level API which makes the decompression [TinyJPEG](http://elm-chan.org/fsw/tjpgd/00index.html)'s API seems quite flexible. It has a [data input function](http://elm-chan.org/fsw/tjpgd/en/input.html) which makes it easy hide how the data is read.
What do you think? Can we adopt it?

**Comment by C47D** [comment]
Hi,

I started working on this, I'm using the codeblocks simulator. Worked on it for about an hour and I'm able to get image information data from a file on the filesystem.

Do you want me to report my work on progress or only when it's done?

Regards

**EDIT 12/JUN/2020**
Hi,

Will share some updates on JPG decoding with TJPGD (this is WIP code, so it's messy). This is my test image:

![red](https://user-images.githubusercontent.com/11037705/84557321-aa260100-acef-11ea-8e51-1c32651898bb.jpg)

It's fully red so it's easy to validate decoded data, the red channel should be 0x1F, green and blue should be 0x00.

TJPGD expects a work buffer to work with, for now we allocate memory for it on the `lv_tjpgd_init` function:

```c

 /* User defined device identifier */
typedef struct {
    FILE *fp;          /* File pointer for input function */
    uint8_t *fbuf;     /* Pointer to the frame buffer for output function */
    uint16_t wfbuf;    /* Width of the frame buffer [pix] */
} IODEV;


#define TJPGD_WORK_BUFFER_SIZE  (20*1024)
void *work = NULL;
JDEC jdec;
JRESULT res;
IODEV devid;

uint8_t src[255] = {0};

/**
 * Register the JPG decoder functions in LVGL
 */
void lv_tjpgd_init(void)
{
    /* Allocate work area for tjpgd */
    work = malloc(TJPGD_WORK_BUFFER_SIZE);

    lv_img_decoder_t * dec = lv_img_decoder_create();

    /* Get information about the image */
    lv_img_decoder_set_info_cb(dec, decoder_info);
    /* Open the image, either store the decoded
     * image or set it to NULL to indicate
     * the image can be read line-by-line */
    lv_img_decoder_set_open_cb(dec, decoder_open);
    /* If open didn't fully open the image this
     * function should give some decoded data
     * (max 1 line) from a given position */
    lv_img_decoder_set_read_line_cb(dec, decoder_read);
    /* Close the opened image, free, the allocated
     * resources*/
    lv_img_decoder_set_close_cb(dec, decoder_close);
}
```

After trying to load some images and get information from them (using `jp_prepare`) we noticed that TJPGD expects JPG baseline images, once you feed it with the correct file format you can get the information about the image with this fuction (test code, we haven't done any work with images stored in memory):
```c
static lv_res_t decoder_info(struct _lv_img_decoder * decoder, const void * src, lv_img_header_t * header)
{
    (void) decoder; /*Unused*/
     lv_img_src_t src_type = lv_img_src_get_type(src);          /*Get the source type*/

     /*If it's a JPG file...*/
     if(src_type == LV_IMG_SRC_FILE) {
         const char * fn = src;

         /*Check the extension*/
         if(!strcmp(&fn[strlen(fn) - 3], "jpg")) {

             devid.fp = fopen(fn, "rb");
             if(!devid.fp) {
                return LV_RES_INV;
             }

             /* Prepare for decompress and get the image information */
             JRESULT res = jd_prepare(&jdec, in_func, work, TJPGD_WORK_BUFFER_SIZE, &devid);

            if (JDR_OK == res) {
                int bytes_used = TJPGD_WORK_BUFFER_SIZE - jdec.sz_pool; // usually 3096

                header->always_zero = 0;
                // Color format
                header->cf = LV_IMG_CF_RAW; // LV_IMG_CF_RAW

                // Image size
                header->w = (lv_coord_t) jdec.width;
                header->h = (lv_coord_t) jdec.height;

                return LV_RES_OK;
            } else {
                printf("Error ID: %d", (int) res);
                return LV_RES_INV;
            }
         }
     }
     /*If it's a file in a  C array...*/
     else if(src_type == LV_IMG_SRC_VARIABLE) {

        /* TODO */

        return LV_RES_OK;
     }

     return LV_RES_INV;
}
```

The information got from `jp_prepare` is validated with the test image feed into it, 100x100px.

Later on the image decoder calls the open callback, here's where we need to give LVGL the decoded data from the image. TJPGD does decode with the `jd_decomp` function, the second argument of this function is a function pointer where it spits out the decoded bitmap, click [here](http://elm-chan.org/fsw/tjpgd/en/output.html) for further info.

Here's where I have my first question:
LVGL image decoder expects me to give it an array of color data, this array should be of uint8_t's,
does LVGL expects the data in RGB order?

Related question:
TJPGD gives the user a bitmap and a rectangle with image coordinates, with the test image above the first time the coordinates are:
```c
rect->left = 0;
rect->right = 7;
rect->top = 0;
rect->bottom = 7;
```

I tried to fit the bitmap data from (0,0) to (0,7) into an array later assigned to `dsc->img_data` before returning from the open callback, but how to tell LVGL how many bytes, we got back from TJPGD?

```c

uint16_t out_func(JDEC* jd, void* bitmap, JRECT* rect)
{
    /* Does bitmap means bitmap[0] = red, bitmap[1] = green, bitmap[2] = blue? */
    IODEV *dev = (IODEV*) jd->device;

    // calculate the number of pixes on the rectangular region of the jpg image
    uint32_t pixels = (rect->right - rect->left) * (rect->bottom - rect->top);

    uint16_t * bitmap_u16 = (uint16_t *) bitmap;

    // TJPGD does spit out bitmap data fitted into rectangles,
    // LVGL expects to get an array with the decoded data, so we
    // need to make the rectangle linear.
    //
    // Test image: Red square of 100x100px
    //
    // bitmap[0] = 00h
    // bitmap[1] = f8h
    //
    // Generated output in RGB565 format
    // 00f8h = 0000_0000 1000_1111b

    return 1;    /* Continue to decompress, return 0 to abort */
}

/**
 * Open a JPG image and return the decoded image.
 * if dsc->img_data = NULL; the read_line callback will be called
 *
 * @param src can be file name or pointer to a C array
 * @param style style of the image object (unused now but certain formats might use it)
 * @return pointer to the decoded image or  `LV_IMG_DECODER_OPEN_FAIL` if failed
 */
static lv_res_t decoder_open(lv_img_decoder_t * decoder, lv_img_decoder_dsc_t * dsc)
{
    (void) decoder;

    lv_res_t retval = LV_RES_INV;
    JRESULT error = JDR_OK;

    /*If it's a JPG file...*/
    if(dsc->src_type == LV_IMG_SRC_FILE) {
        const char * fn = dsc->src;

        if(!strcmp(&fn[strlen(fn) - 3], "jpg")) {

            /* out_func will receive the bitstream of decoded data in
             * JD_FORMAT 0:RGB888 (3 BYTE/pix) or 1:RGB565 (1 WORD/pix) */
            error = jd_decomp(&jdec, out_func, 0 /* scale factor 1:1 */);

            if (JDR_OK != error) {
                printf("Error ID: %d", (int) error);
                retval = LV_RES_INV;
            } else {
                dsc->img_data = src;
                retval = LV_RES_OK;
            }

            return retval;
        }
    }
    /*If it's a JPG file in a  C array...*/
    else if(dsc->src_type == LV_IMG_SRC_VARIABLE) {

        /* TODO */

        return LV_RES_OK;     /*Return with its pointer*/
    }

    return LV_RES_INV;    /*If not returned earlier then it failed*/
}
```

So we are kind of stuck between TJPGD giving us data in rectangles and LVGL expecting data into a linear array, also from the documentation on Images I think, correct me if I'm wrong, that LVGL expects the open callback to decode the whole image, if not you need to assign `dsc->img_data = NULL;` so it can call the readline callback, but again we can't tell TJPGD what coordinates to decode.

Are missing something?
Any advice?

**Comment by kisvegabor** [comment]
Hi Carlos,

> LVGL image decoder expects me to give it an array of color data, this array should be of uint8_t's,
does LVGL expects the data in RGB order?

LVGL will treat `dsc->img_data` as `lv_color_t`. 

> I tried to fit the bitmap data from (0,0) to (0,7) into an array later assigned to dsc->img_data before returning from the open callback, but how to tell LVGL how many bytes, we got back from TJPGD?

As you found it in the docs there are 2 options: open the whole image in the `open` function, or line by line in `read_line` function. 

In case of the first option, the size of the buffer is known from `img_w x img_h x sizeof(lv_color_t)`.
In the `open` function you can allocate a large array with this size, decompress all pixels here, and set the address of this array in `dsc->img_data`. This is what the [PNG decoder](https://github.com/lvgl/lv_lib_lodepng/blob/master/lv_lodepng.c#L153) does as well. 

In the case of `read line` LVGL will give the buffer with the required size and you just need to add `width` number of pixels. As you can't tell from where to start decoding the file (JPG doesn't support decompressing arbitrary areas) you can always start from the beginning and buffer 8 lines. LVGL asks the lines in order, so you are good for the 8 first calls. If LVGL asks the 9th line, you need to decompress 8-15 lines, and so on.
You can store the current state in `dsc->user_data`.  Note that, it's not sure that first lines are required. It can happen that only the middle or bottom of the image needs to be redrawn. In this case, the first lines can be discarded. 
 It's a little bit trickier but would be great for smaller systems.
 > /* User defined device identifier */
typedef struct {
    FILE *fp;          /* File pointer for input function */
    uint8_t *fbuf;     /* Pointer to the frame buffer for output function */
    uint16_t wfbuf;    /* Width of the frame buffer [pix] */
} IODEV;

You can `alloc` an `IODEV` and store it in `dsc->user_data`. It allows dealing with multiple files at same time. 
Actually it's required to handle files simultaneously because LVGL always keeps the images open as long as possible. If you can handle one file at a time but have 2 images, thing will mess up.

**Comment by C47D** [comment]
Thanks for the explanation @kisvegabor, got something working on the simulator.
For now it only handles opening files and decoding everything in one `jp_decode` call.

![imagen](https://user-images.githubusercontent.com/11037705/84577655-e5720f80-ad83-11ea-8c63-91f93bb061d3.png)

Will upload the code after some cleanup.

**Comment by C47D** [comment]
@kisvegabor Some additional questions:

- Should we assume the user have access to functions such as `fread`, `fseek`, `fclose` when reading the image file from the file system?
- Can the library be configured to be used using only open or using readline callabacks?

**Comment by embeddedt** [comment]
> Should we assume the user have access to functions such as `fread`, `fseek`, `fclose` when reading the image file from the file system?

I don't think so. They could be using ChaN's FatFS, for instance.

**Comment by C47D** [comment]
Or a drive registered into lvgl file system?
I ask because the lv_lib_lodepng repo use the aforementioned functions.

But the docs mentions a registered driver in lvgl.

https://docs.lvgl.io/v7/en/html/overview/image.html#files

**Comment by C47D** [comment]
Also, how feasible would it be to add another callback to the image decoder that receives an array of decoded data and the area it corresponds to?

Now the decoder have a callback so the user can feed it with decoded data from a given line of the image.

**Comment by C47D** [comment]
@kisvegabor 

I've created a repo where to upload the work in progress [lv_lib_tjpgd](https://github.com/C47D/lv_lib_tjpgd), I'm working on the dev branch of it with the partial decoding of the image.

When calling `jp_decomp` it always starts to decode the image from the top, if you return 0 from the `outfunc` function it stops the decoding, and I assumed that it would remember where it was so if we call `jp_decomp` again it started from the last point it decoded, but no, it starts from the top again. Maybe I'm missing something, will check for more compatible jpg decoding libraries.

This is the decompression function, from what I understand it always start the horizontal decompression at 0 until `jd->height`.
```c
JRESULT jd_decomp (
	JDEC* jd,								/* Initialized decompression object */
	uint16_t (*outfunc)(JDEC*, void*, JRECT*),	/* RGB output function */
	uint8_t scale							/* Output de-scaling factor (0 to 3) */
)
{
	uint16_t x, y, mx, my;
	uint16_t rst, rsc;
	JRESULT rc;


	if (scale > (JD_USE_SCALE ? 3 : 0)) return JDR_PAR;
	jd->scale = scale;

	mx = jd->msx * 8; my = jd->msy * 8;			/* Size of the MCU (pixel) */

	jd->dcv[2] = jd->dcv[1] = jd->dcv[0] = 0;	/* Initialize DC values */
	rst = rsc = 0;

	rc = JDR_OK;
	for (y = 0; y < jd->height; y += my) {		/* Vertical loop of MCUs */
		for (x = 0; x < jd->width; x += mx) {	/* Horizontal loop of MCUs */
			if (jd->nrst && rst++ == jd->nrst) {	/* Process restart interval if enabled */
				rc = restart(jd, rsc++);
				if (rc != JDR_OK) return rc;
				rst = 1;
			}
			rc = mcu_load(jd);					/* Load an MCU (decompress huffman coded stream and apply IDCT) */
			if (rc != JDR_OK) return rc;
			rc = mcu_output(jd, outfunc, x, y);	/* Output the MCU (color space conversion, scaling and output) */
			if (rc != JDR_OK) return rc;
		}
	}

	return rc;
}
```

**Comment by kisvegabor** [comment]
I agree to use lvgl's files system if possible. POSIX IO handling was deeply routed in lodepng and in lack of time I haven't updated it yet. However, if we write these parts we should use the more generic option.  

> This is the decompression function, from what I understand it always start the horizontal decompression at 0 until jd->height.

I see, so it always wants to decompress the whole image. What I can imagine is to modify the lib. Fortunately, [jd_decomp](https://github.com/C47D/lv_lib_tjpgd/blob/master/tjpgd.c#L922) is quite simple and it's easy to see where a line is decompressed. 
At first look, adding a  `jd_decomp_line` function seems reasonable. What do you think?

**Comment by C47D** [comment]
> I agree to use lvgl's files system if possible. POSIX IO handling was deeply routed in lodepng and in lack of time I haven't updated it yet. However, if we write these parts we should use the more generic option.

Will try to send a PR, I'm getting familiar with lvgl fs with a toy project.

> I see, so it always wants to decompress the whole image. What I can imagine is to modify the lib. Fortunately, jd_decomp is quite simple and it's easy to see where a line is decompressed.
At first look, adding a jd_decomp_line function seems reasonable. What do you think?

I've sent a mail to Chan asking if is possible to do partial decoding, I'm 0% familiar on how JPGs are decoded. We can give it a try tho.

**Comment by kisvegabor** [comment]
> I've sent a mail to Chan asking if is possible to do partial decoding, I'm 0% familiar on how JPGs are decoded. We can give it a try tho.

Oh, great! I'm curious how it will go. If he can't help I can try to add the line decoding feature.

**Comment by tuupola** [comment]
In theory you should be able to track and save how many bytes was read when decompressing an `mcu` and then  later call `lseek()` with this information. Note that JPEGs decompression  is not a line by line operation. It is done in 8x8 blocks (minimum coded unit ie `mcu`) instead.

I had similar problem recently when implementing an MJPEG decoder with the same library.  In my case I had to search for the previous  `EOI` marker and `lseek()` back to that marker.

**Comment by kisvegabor** [comment]
@tuupola You are right. It really steps `jd->msx * 8` and `jd->msy * 8`

**Comment by tuupola** [comment]
Also good to note that compressing is done using a [zig zag pattern](https://en.wikipedia.org/wiki/JPEG#/media/File:JPEG_ZigZag.svg). I think this is because the algorithm is based on saving the difference to previous block and adjacent blocks are often are quite similar.

**Comment by C47D** [comment]
@kisvegabor An update on the jpg decoder, let me know if you see something wrong or if we are on the right track.

---

Thanks for the help @tuupola, I should had get familiar with how JPEG works before starting this, now with your suggestion and some online reading about JPEG I am a bit more familiar on how it works.

I'm currently "cheating" tjpgd telling it the test image is `width` * 8 pixels (we got the `width` value with `jp_prepare`), I've chosen 8 because of the MCU size as you noted on the comment above.

This is the output, I think we are on the right track:
![imagen](https://user-images.githubusercontent.com/11037705/84978661-1c815180-b0f3-11ea-8ff0-7d3b52de68f4.png)

This is the test image:
![imagen](https://user-images.githubusercontent.com/11037705/84978698-3884f300-b0f3-11ea-8510-0061bf1fe983.png)


The first time LVGL calls `decoder_read` it asks for 1 line of data, so we call `jp_decomp` when it returns we have the decompressed data stored in `user_ctx.frame_buffer` and we send LVGL the first line of the image (`len * BYTE_ON_PIXEL` bytes). After that we send the buffered data we have stored in chunks of `len * BYTE_ON_PIXEL` bytes, until we no longer have decompressed data.

```c
static lv_res_t decoder_read(lv_img_decoder_t * decoder, lv_img_decoder_dsc_t * dsc, lv_coord_t x, lv_coord_t y, lv_coord_t len, uint8_t *buf)
{
    lv_res_t retval = LV_RES_INV;

    static bool buffered_data = false;
    static uint8_t lines_sent = 0;

    if (buffered_data) {
        // Send LVGL data starting from the last byte we sent
        memcpy((void *) buf, (void *) user_ctx.lvgl_feeder_ptr, len * BYTES_ON_PIXEL);
        user_ctx.lvgl_feeder_ptr += (len * BYTES_ON_PIXEL);
        retval = LV_RES_OK;
        lines_sent++;

        // We already sent all the data we had
        if (7 < lines_sent) {
            buffered_data = false;
            lines_sent = 0;
            free(user_ctx.frame_buffer);
            user_ctx.frame_buffer = NULL;
        }

    } else {
        JRESULT error = JDR_OK;

        /* Allocate memory to store the decompressed data */
        uint32_t decoded_image_buffer_size = user_ctx.size.width * 8 * BYTES_ON_PIXEL;
        user_ctx.frame_buffer = (uint8_t *) malloc(decoded_image_buffer_size);

        size_t before_decompression = ftell(user_ctx.fp);

        jdec.height = 8; // <- Make TJPGD think the image is width * 8 px
        error = jd_decomp(&jdec, on_decoder_line_output_cb, LV_TJPGD_SCALING_FACTOR);

        size_t bytes_to_send = len * BYTES_ON_PIXEL; // bytes of decompressed data in 1 line
        memcpy((void *) buf, (void *) user_ctx.frame_buffer, bytes_to_send); // LVGL need us to put the decompressed data into buf
        lines_sent++; // Keep track of the number of lines sent to LVGL, user_ctx.frame_buffer stores 8 lines, we already sent 1
        user_ctx.lvgl_feeder_ptr = user_ctx.frame_buffer + bytes_to_send; // Keep track of the unsent decompressed data
        retval = LV_RES_OK;

        buffered_data = true; // We now have buffered data
    }

    return retval;
}
```

This is how we keep track of the "consumed" bytes:
```c
static uint16_t on_feed_decoder_cb(JDEC* jd, uint8_t* buff, uint16_t nbyte)
{
    uint16_t retval = 0;

    decoding_ctx_t *ctx = (decoding_ctx_t *) jd->device;
    ctx->fp_consumed_bytes += nbyte;

    if (buff) {
        retval = fread(buff, 1, nbyte, ctx->fp);
    } else {
        retval = fseek(ctx->fp, nbyte, SEEK_CUR) ? 0 : nbyte;
    }

    return retval;
}
```

If we check the value of `user_ctx.fp_consumed_bytes` when we are done sending data to LVGL (on the `decoder_read` function) we got the following, you can see marked in yellow a RST marker, one byte after the data pointer of TJPGD.
![imagen](https://user-images.githubusercontent.com/11037705/84978462-92d18400-b0f2-11ea-8318-131d29abefb9.png)

So my question is, should we `fseek` X bytes until we are on the RST marker? And then do another `jp_decompress`?
AFAIK the `EOI` marker is located at the end of the file, so we couldn't read more data from it, maybe I understand something wrong from your explanation above.

Regards and thanks again for the help @kisvegabor and @tuupola 😄

**Comment by kisvegabor** [comment]
@C47D 
Thanks for the update!

There are 2 things I don't understand (maybe there are related):
-  How do you tell to TJPGD to skip the first 8 lines when you go to the second 8 lines.
- How can `buff == NULL` in `on_feed_decoder_cb` to run the else branch?

**Comment by C47D** [comment]
> @C47D 
> Thanks for the update!
> 
> There are 2 things I don't understand (maybe there are related):
> -  How do you tell to TJPGD to skip the first 8 lines when you go to the second 8 lines.

This is where I'm stuck at the moment, I wanted to test decompressing the first 8 lines of the image, store them and give them to lvgl one line at the time. It seems to be working, we need to find out how to decompress the image in chunks of 8 lines. 

> - How can `buff == NULL` in `on_feed_decoder_cb` to run the else branch?

Buff is null when tjpgd needs to rewind on the stream buffer, that's part of tjpgd.

**Comment by tuupola** [comment]
> AFAIK the EOI marker is located at the end of the file, so we couldn't read more data from it, maybe I understand something wrong from your explanation above.

My problem was similar but not the same. I was implementing an [MJPEG player](https://appelsiini.net/2020/esp32-mjpeg-video-player/) with the tjpgd library. MJPEG is basically a bunch of JPG files concatenated together. My problem was that tjpgd was reading past the `EOI` marker which always caused the next frame to be broken. The solution was to rewind filepointer back to the `EOI` marker.

So you cannot use `EOI` in your case. Instead probably have to track read bytes yourself. I think `RST` is an optional feature and does not exist in all JPG files?

**Comment by kisvegabor** [comment]
@tuupola 
> I was implementing an MJPEG player with the tjpgd library.

A video player would be another great feature for LVGL. :sunglasses: 
Would you be interested in contributing with it?

@C47D 
I think the easiest would be to create `jd_decomp_line_init` and `jd_decomp_line_next` functions based on the original `jd_decomp`. 

I can try to add it tomorrow if you wish.

**Comment by C47D** [comment]
@tuupola Thanks for the link to your blog post, it's very neat to display video on such small system. Indeed the problem is not the same, as you said you have a bunch of JPEG images one after the other, that's why you can locate the `EOI` marker and call `jp_prepare` again on your while loop.

I think the problem we are facing here is that we can not allocate memory for the whole image, so we were thinking in decoding 8 lines at the time, but I'm stuck on how to continue the JPEG decoding after the 8 lines are being decoded.

~~Inside `jp_decom` we can wee the `RST` markers from 0 to 25 being identified, I'm stuck now, will need to clear my head for a bit lol. I think we need to find a `SOS` marker and start from there again.~~

@kisvegabor To be honest I'm stuck, I don't know how to continue the decompressing after tjpgd is done with the first call to `jp_decom`.

EDIT:
Just found [this](https://youtu.be/TlrNCT15NM4?t=1936) series of videos about JPEG, they explain the format while writing a decoder in C++, as @tuupola says, the `RST` markers are not always present on the bitstream.
I will investigate other JPEG decoders.

**Comment by tuupola** [comment]
IIRC tjpgd itself only needs around 3100 bytes for the work buffer. The output function for tjpgd needs 8 * 8 * 2 bytes if outputting one mcu at a time, less if outputting with putpixel. Does lvgl internals require to output more than one mcu at a time? You mention outputting eight lines.

Do not get fixated too much with the mentioning of the `EOI` marker. My problem was how to continue MJPEG decoding after a frame. This problem is how to continue JPG decoding after a mcu or bunch of mcus. Both have the same possible solution ie. `fseek()` the filepointer to correct position before continuing. Difference is what is the correct position.

That said, tjpgd was designed  so that `jd_decomp()` is called only once. It might be easier to to modify the output function so that it collects the mcu's you want to display and then flushes them to screen at once. Or if internals requires that `jd_decomp()` is called multiple times then do not `fclose()` the filepointer between calls. If the filepointer is not closed there is no need to call `fseek()` either.

**Comment by tuupola** [comment]
> A video player would be another great feature for LVGL. 😎 Would you be interested in contributing with it?

@kisvegabor I don't think my C is good enough yet :) I recently started to learn C by also doing an [embedded graphics library](https://github.com/tuupola/hagl). It is more low level thing which I use for my hobby projects. But I must say C is the only language I actually enjoy writing at the moment.

**Comment by kisvegabor** [comment]
@C47D I had a busy day so I can take look at it on Monday.

@tuupola 
No problem. Good luck with your library! :slightly_smiling_face:

**Comment by C47D** [comment]
@kisvegabor No problem, yesterday I realized that when `jp_decomp` returns the decompressor still have bitstream to decompress, narrowing down the new function we need to add.

I've also noticed that LVGL does not guaranty asking for lines starting from the line 0, it can ask for lines in the middle of the image so we need to take into consideration that.

Sorry if this is taking more time than expected, it was a new topic for me 😅

**Comment by kisvegabor** [comment]
@C47D I opened a PR with line decoding. It's nothing else then separating the decompress function into an init and a next function. 

> Sorry if this is taking more time than expected, it was a new topic for me sweat_smile


There is no expected time.  Just work on it when it feels comfortable.  :slightly_smiling_face:

**Comment by kisvegabor** [comment]
I think adding support to full decode only (skip `read_line_cb` for now) is still useful and much easier to complete.

What do you think?

**Comment by C47D** [comment]
Sorry, I've been away from my computer for a couple of weeks. Is this feature expected to be included on the next release? I think partial decoding is crucial for embedded targets.
Also we would need to pass the repo from my profile to the LVGL profile, isn't?

**Comment by kisvegabor** [comment]
No problem :slightly_smiling_face: 

It can be added independently from the releases.

I think it's better we have something working which can be simply extended later. Partial decoding is critical only on MCUs but some people use LVGL on Raspberry or similar platforms where there are plenty of resources.

If you agree yes. We can move it as `lv_lib_tjpgd` here.

**Comment by C47D** [comment]
The current implementation (master branch) uses malloc, would it make sense to use the LVGL malloc wrapper instead?

**Comment by kisvegabor** [comment]
Yes, it'd be great. 

Using LVGL's File system would be also a good direction. (lv_lib_lodepng still uses POSIX IO functions)

**Comment by C47D** [comment]
@kisvegabor Just to let you know, there's a new JPEG decoder being released soon, not mine but I saw it on Twitter being tested.

**Comment by kisvegabor** [comment]
Wow, can you link the tweet?

**Comment by C47D** [comment]
This is it https://twitter.com/fast_code_r_us/status/1293304567308976132?s=19

**Comment by kisvegabor** [comment]
Hm, it's not for LVGL, right?

**Comment by C47D** [comment]
No, it isn't, it is just another JPEG decoder, I think is fine to have multiple library options, work with both and choose the one that fits better on LVGL.
The creator told me he is documenting it (tjpgd lacks of comments) and it is targeting low end microcontrollers. They also did a GIF decoder library recently, does the LVGL image decoder can support this?

**Comment by kisvegabor** [comment]
> The creator told me he is documenting it (tjpgd lacks of comments) and it is targeting low end microcontrollers. They also did a GIF decoder library recently, does the LVGL image decoder can support this?

I've added a GIF decoder a few days ago: https://github.com/lvgl/lv_lib_gif

**Comment by vinodstanur** [comment]
Hi Kisvegabor, integrating jpeg to lvgl seems to be very interesting stuff. I got a chance to play around with the tjpeg library after seeing your comment over here. I am a big fan of elm-chan since long time. 

   Yesterday I modified tjpeg library to render the jpeg from any line (for now width * block_width, for me on my test images block width is 16) without the need of full image decomp. So basically I can jd_decomp  even a small part of jpeg from the middle of it as well. (Added few additional parameters to jd structure and some changes in few functions etc). Also to make it work, we have to run jd_decomp in training mode one time after opening the image, and later on we can call jd_decomp for a particular line and it will uncompress only that line_block, this reduces the jpeg's computational complexity height/16 times in a 16 block image. 
     Also now adding a jpeg_decoded_cache in expense of additional width * 16 * byte_per_pixel, but this is expensive and can keep as optional for fast line fetching. If enabled, average decompression complexity for a single width line will be reduced by height times. This might be the best especially in systems like esp32 etc where we cannot allocate too much memory.
![download_20200904_080106](https://user-images.githubusercontent.com/1061443/92193868-0039b900-ee87-11ea-93a0-fbb71a571a04.png)
![download_20200904_080104](https://user-images.githubusercontent.com/1061443/92193879-029c1300-ee87-11ea-9ef4-84300b26fee5.png)


First image I am rendering full image, second one I am rendering partial line blocks, basically partial jpeg uncompression and rendering.

**Comment by C47D** [comment]
This is great @vinodstanur, I didn't have time to continue this, I only had the chance to decode the whole image in one step and not in chunks.

Will you post the source of your project? Mine is two months old and it's very ugly.

**Comment by kisvegabor** [comment]
@vinodstanur 
Looks great! Are you interested in contributing with your code?  If so I can open a repo for the jpeg decoder. 

I see no problem with the width*16 (or 8) pixels cache. For a 320px wide image on 16 bit color depth, it's only 10k (5k for 8px blocks) A 320x240 image would be 150k.

**Comment by vinodstanur** [comment]
@kisvegabor  Yes, I am interested :)

**Comment by kisvegabor** [comment]
Awesome!
Here it is: https://github.com/lvgl/lv_lib_jpg

**Comment by kisvegabor** [comment]
With @vinodstanur's contribution, we have a great lib to use compressed images in a fast way. 

We still need a normal JPG decoder that can be used e.g. on Raspberry without any additional scripts. @C47D, what do you think, how far is your version from it? The goal is just to decompress the whole image in a large dynamically allocated array.

**Comment by C47D** [comment]
I think I only need to clean up my code a little bit.

**Comment by kisvegabor** [comment]
> I think I only need to clean up my code a little bit.

That's great! Do you have time and interest to polish it?

**Comment by vinodstanur** [comment]
> With @vinodstanur's contribution, we have a great lib to use compressed images in a fast way.
> 
> We still need a normal JPG decoder that can be used e.g. on Raspberry without any additional scripts. @C47D, what do you think, how far is your version from it? The goal is just to decompress the whole image in a large dynamically allocated array.

Hi @kisvegabor ,
 Thanks.
Also since sjpg is collection of multiple jpgs , If we consider the split factor as 1 (meaning no split), then with a very minimal changes to the lv_sjpg I can make it work with normal jpg as well but the disadvantage is that we have to allocate a complete decompressed image cache unlike the sjpg's  xres * 16 * 2 cache size.

-------
_Forgot to mention, 24 days ago I posted a working sample screenshot of decoding jpeg from middle of file by doing backup of few parameters from Jd and file back-seeking. But unfortunately those were not enough to make it work properly and  somehow on my test sample it worked but it didn't worked properly after I did complete test on it and later I realized that I even need to backup the work_buff (4KB) as well. So it doesn't make sense to backup a 4KB buffer for Xres *  2 * 16 unless the Xres is very large (say 1920 pix) or otherwise if we make 16 to yres/4 or something like that ._

**Comment by C47D** [comment]
> > I think I only need to clean up my code a little bit.
> 
> That's great! Do you have time and interest to polish it?

Yes, but I can do it tomorrow night.

**Comment by kisvegabor** [comment]
> Also since sjpg is collection of multiple jpgs , If we consider the split factor as 1 (meaning no split), then with a very minimal changes to the lv_sjpg I can make it work with normal jpg as well but the disadvantage is that we have to allocate a complete decompressed image cache unlike the sjpg's xres * 16 * 2 cache size.


Sounds good! Having 1 repo is clearly better. So if normal JPG (both as file or C array) work without any configuration with `spjg` I suggest going this way. 

@C47D don't you mind if we merge the normal JPG support to @vinodstanur's repo?

**Comment by C47D** [comment]
No, I don't, this is the repo I was working on https://github.com/C47D/lv_lib_tjpgd, maybe it helps someway

**Comment by jesse-schein** [comment]
I'm interested in working on this where I can. I tried to use your library @C47D, but I didnt have luck using it with an ESP32. I switched some things to using PS_MALLOC to use the available 4MB of ram.

I am working on a project to get thumbnails from homeassistant via websocket, the image is base64 encoded and I'm trying to put it on the screen. I am successfully decoding it but cant seem to get LVGL to put it on the screen.

**Comment by jesse-schein** [comment]
Oh I see @C47D your code does not work with variables. Maybe I will try to work on it.

**Comment by C47D** [comment]
@jesse-schein hi, I was using my pc to work on the library, so my allocation wasn't properly done for embedded. I think @vinodstanur library takes that into account, I'm not sure tho.

**Comment by kisvegabor** [comment]
The JPG library is added here:
https://github.com/lvgl/lv_lib_split_jpg

Thank you very much for your contribution!
