### ISSUE TITLE
Compilation fails

### ISSUE THREAD

**Issue by heyhachi0** [lvgl/lvgl#1548]
**Describe the bug**

use newest master branch Compilation fails

**To Reproduce**

In lv_mem_realloc function: syntax error

**Expected behavior**

NULL

**Screenshots**
![image](https://user-images.githubusercontent.com/48829484/83499029-4598c400-a4ef-11ea-9c59-d00c2291f609.png)

**Additional context**

NULL

**Comment by kisvegabor** [comment]
Thank you for the report.
I fixed, here: 140904e2
