### ISSUE TITLE
lv_tabview_set_btns_hidden not Working

### ISSUE THREAD

**Issue by HassegawaBR** [lvgl/lvgl#1554]
Hello!,

the lv_tabview_set_btns_hidden function, that is mentioned in the documentation was removed?
i cant get it to work, and the pdf docs dont mention it also, theres another way to do it?
My main objetive is to change screen using button, not tabs .

**Comment by embeddedt** [comment]
Solution here: https://forum.lvgl.io/t/request-dev7-0-is-there-the-lv-tabview-set-btns-hidden-api-in-dev7-0/1246

----------------------
We use GitHub issues for development related discussions.
Please use the [forum](https://forum.littlevgl.com/) to ask questions.

It's possible to sign in to the forum with your GitHub account... you don't need to make a separate account.
