### ISSUE TITLE
when input chars exceed the input editor area, and then delete all chars, it will raise Segmentation fault

### ISSUE THREAD

**Issue by incity** [lvgl/lvgl#1556]
seems related to the scrollbar of the input area.

[e8660d69e31f12cf0395ef2ab1842fea.zip](https://github.com/lvgl/lvgl/files/4728799/e8660d69e31f12cf0395ef2ab1842fea.zip)

**Comment by incity** [comment]
the attachment file has the video of reproduce method

**Comment by kisvegabor** [comment]
It crashes for me as well. Investigating.

**Comment by kisvegabor** [comment]
Should work now
