### ISSUE TITLE
The API here is different from the API on the official website, right?

### ISSUE THREAD

**Issue by LucasLiao123** [lvgl/lvgl#1559]
I used the library downloaded from the official website, compared the library here, and found that some API is different, which is the latest? Which is better?

**Comment by embeddedt** [comment]
GitHub is almost always more recent. In fact, I don't see any option to download straight from the website anymore: https://lvgl.io/

**Comment by kisvegabor** [comment]
The downloaded library should be still the previous version (v6).

**Comment by LucasLiao123** [comment]
Oh, thanks. The download is indeed Version 6.

**Comment by embeddedt** [comment]
I'm closing this as I believe the question is answered.
