### ISSUE TITLE
Indexed 1-bit image won't draw in v7.0.0 and in v7.0.1.

### ISSUE THREAD

**Issue by nchurly** [lvgl/lvgl#1570]
Indexed 1-bit image won't draw (non-initialized variable exception in VS 2017).

There is missing check for such image type in the lv_draw_img.c line 550, so the c.full wasn't initialized. 
In order to make the image draw working i had to add the following:

#if LV_COLOR_DEPTH == 1
	c.full = map_px[0];
#elif .....

**Comment by kisvegabor** [comment]
> Sorry, i just started to learn the lib (github also), not sure i can submit anything productive yet.

Let's give it a try, we help if something is not working. 
Take a look at this [guide](https://github.com/lvgl/lvgl/blob/master/docs/CONTRIBUTING.md#how-to-send-a-pull-request) to see how to send a PR.
