### ISSUE TITLE
Memory access issue during LVGL initialization `lv_init()`

### ISSUE THREAD

**Issue by rafaelcaricio** [lvgl/lvgl#1575]
**Describe the bug**

I imagine there is some issue to dereferencing uninitialized memory in the library bootstrap code `lv_init`.

**To Reproduce**

Code same:
```c
lv_init();
```

The error starts in this line: https://github.com/lvgl/lvgl/blob/master/src/lv_core/lv_obj.c#L160

**Expected behavior**

Library should initialize without errors.

**Screenshots**
The debugging session.

![lvgl_issue_image_init](https://user-images.githubusercontent.com/107613/84572604-6c7eb200-ad9b-11ea-89d3-256c27e810d0.png)

Where the error happens:
![lv_init_image_crash](https://user-images.githubusercontent.com/107613/84572610-89b38080-ad9b-11ea-858a-82887c36e387.png)

**Additional context**

I'm using latest master branch version `1ca1934d`. The target is a [nRF52832 device](https://wiki.pine64.org/index.php/PineTime#Specifications). 
I'm calling from Rust code, but that shouldn't matter for this issue.
Checking the fault in GDB:
```
print/x *(uint8_t*)0xE000ED29
$1 = 0x82
```

**Comment by rafaelcaricio** [comment]
Previously, I was hitting this issue #1557 which was causing same exception code. That's why I updated to use latest `master`.

**Comment by embeddedt** [comment]
Can you confirm that `_lv_img_cache_array` is zero before `lv_init` is called? Maybe you have [the same problem](https://github.com/lvgl/lvgl/issues/1557#issuecomment-638886762) (although I'd expect Rust to handle this properly).

**Comment by rafaelcaricio** [comment]
For some reason, I cannot reproduce it anymore. :thinking: The only difference is that I've updated to the latest Rust nightly release (`1.46.0-nightly (feb3536eb 2020-06-09)`).

**Comment by rafaelcaricio** [comment]
@embeddedt it is happening again now. :cry: 

The `_lv_img_cache_array` is not zeroed.

**Comment by rafaelcaricio** [comment]
Someone else was having the same issue. https://github.com/lvgl/lvgl/issues/1302 :thinking:

**Comment by embeddedt** [comment]
> The `_lv_img_cache_array` is not zeroed.

I think that would mean that your `.bss` area is not being zeroed. There's probably memory corruption happening somewhere.

**Comment by rafaelcaricio** [comment]
Ok, so it is some issue with my platform. Thanks for the pointer!

**Comment by rafaelcaricio** [comment]
If someone from internet gets here from searches, [this section of the embedonomicon](https://docs.rust-embedded.org/embedonomicon/main.html#life-before-main) will be helpful.

**Comment by rafaelcaricio** [comment]
I found the solution, it is a bug in `cortex-m-rt`, described here: https://github.com/rust-embedded/cortex-m-rt/issues/267#issue-609383169

**Comment by kisvegabor** [comment]
Thank you, for the link!
