### ISSUE TITLE
Gauge angle offset issue: the label and needles don't go with angle offset

### ISSUE THREAD

**Issue by ZhaoQiang-b45475** [lvgl/lvgl#1579]
I create a gauge and set its angle_offset with 90，found that the label and needles are not rotated with the angle_offset, is this normal？

<img width="174" alt="gauge-offset-90" src="https://user-images.githubusercontent.com/22284222/84635660-15f1af00-af26-11ea-91f3-d345b9c2e87e.PNG">
<img width="164" alt="gauge-without-offset" src="https://user-images.githubusercontent.com/22284222/84635664-17bb7280-af26-11ea-99ba-a050fab72447.PNG">

**Comment by embeddedt** [comment]
If I understand the [documentation](https://docs.lvgl.io/v7/en/html/widgets/gauge.html#scale) correctly, the `angle_offset` property only affects the scale (the gray lines) and not the needles.

----------------------
We use GitHub issues for development related discussions.
Please use the [forum](https://forum.littlevgl.com/) to ask questions.

It's possible to sign in to the forum with your GitHub account... you don't need to make a separate account.

**Comment by kisvegabor** [comment]
Actually I think it's a bug because can't image a case when only the ticks need to be moved.
I've fixed it `master`.
