### ISSUE TITLE
checkbox error

### ISSUE THREAD

**Issue by ZhaoQiang-b45475** [lvgl/lvgl#1583]
When I run my codes as below, I pressed checkbox from released state to checked state, the simulator quit and return an error "Segmentation fault"

	//Write codes cb0
	lv_obj_t *cb0 = lv_checkbox_create(lv_disp_get_scr_act(NULL), NULL);
	lv_checkbox_set_text(cb0, "checkbox");
	lv_obj_set_pos(cb0, 194, 107);
	lv_obj_set_size(cb0, 100, 40);

	//Write style LV_CHECKBOX_PART_BULLET for cb0
	static lv_style_t style_cb0_bullet;
	lv_style_init(&style_cb0_bullet);

	lv_style_set_bg_color(&style_cb0_bullet, LV_STATE_DEFAULT, lv_color_make(0x00, 0x40, 0x80));
	lv_style_set_bg_grad_color(&style_cb0_bullet, LV_STATE_DEFAULT, lv_color_make(0xff, 0x00, 0x80));
	lv_style_set_bg_grad_dir(&style_cb0_bullet, LV_STATE_DEFAULT, LV_GRAD_DIR_VER);

	lv_style_set_bg_color(&style_cb0_bullet, LV_STATE_CHECKED, lv_color_make(0xff, 0xff, 0xff));
	lv_style_set_bg_grad_color(&style_cb0_bullet, LV_STATE_CHECKED, lv_color_make(0xff, 0xff, 0xff));
	lv_style_set_bg_grad_dir(&style_cb0_bullet, LV_STATE_CHECKED, LV_GRAD_DIR_HOR);

	lv_obj_add_style(cb0, LV_CHECKBOX_PART_BULLET, &style_cb0_bullet);

**Comment by kisvegabor** [comment]
Thanks for the report!
I've fixed it. There was a bug when drawing a gradient to the same color.
