### ISSUE TITLE
Textarea is hard to drag

### ISSUE THREAD

**Issue by lilengqiang** [lvgl/lvgl#1593]
I created a Textarea, and it was very difficult for me to drag the control from the text section.
![图片](https://user-images.githubusercontent.com/52372001/85088332-7593d700-b212-11ea-95a4-993a8bc55591.png)

**Comment by kisvegabor** [comment]
If you want to move the whole text area (not only scroll the text in it) you can do this:
`lv_obj_set_drag_parent(lv_page_get_scrl(ta), true);` However, scrolling is not possible if it's enabled. 

---

Next time please send the code as text and fill the issue template.

**Comment by lilengqiang** [comment]
ok.  thanks
