### ISSUE TITLE
What is the way to attach an int to an object?

### ISSUE THREAD

**Issue by curly-brace** [lvgl/lvgl#1595]
LVGL 7.0.1

i need to use single callback for unlimited amount of buttons.
i see in documentation that there is `lv_obj_set_free_num` and `lv_obj_set_ext_attr` but they are not available for me. do i miss some setting for the library or they were removed?

anyways, what would be the best method to be able to assign an index to the buttons to be used with single callback?

**Comment by embeddedt** [comment]
Use [`lv_obj_set_user_data`](https://docs.lvgl.io/latest/en/html/widgets/obj.html#_CPPv420lv_obj_set_user_dataP8lv_obj_t18lv_obj_user_data_t) and `lv_obj_get_user_data`.

----------------------
We use GitHub issues for development related discussions.
Please use the [forum](https://forum.littlevgl.com/) to ask questions.

It's possible to sign in to the forum with your GitHub account... you don't need to make a separate account.
