### ISSUE TITLE
 lv_list_get_btn_index() will not work, if called with NULL instead of a list object

### ISSUE THREAD

**Issue by tehkillerbee** [lvgl/lvgl#1610]
https://github.com/lvgl/lvgl/blob/7af64df008c5abe4ef88ec766241052b9fe66b1d/src/lv_widgets/lv_list.c#L465

lv_list_get_btn_index() will not work, if called with NULL instead of a list object.

Commenting out "LV_ASSERT_OBJ(list, LV_OBJX_NAME)" fixes this issue.

**Comment by embeddedt** [comment]
Thanks; I've fixed it by moving the assertion to after the list object is retrieved.
