### ISSUE TITLE
STM32 DMA2D definitions conflict with STM32Cube

### ISSUE THREAD

**Issue by embeddedt** [lvgl/lvgl#1617]
The [DMA2D color formats declared in `lv_gpu_stm32_dma2d.h`](https://github.com/lvgl/lvgl/blob/3e8b39c4046cff57a9a211d0b572cdad74344f3f/src/lv_gpu/lv_gpu_stm32_dma2d.h#L23-L27) have the same name (and value) as those provided by the Cube library. This causes redefinition errors at compile time.

I think the best solution here is to simply prepend `LV_` to the names so they are in their own namespace.

@kisvegabor If you approve of this change I'll apply it to `master`.

(cc @microwavesafe)

**Comment by microwavesafe** [comment]
Sounds like a good idea to me. We actually don't need all those defines only a few are compatible with lvgl.

**Comment by kisvegabor** [comment]
I'm also okay with that.

**Comment by embeddedt** [comment]
Great; I've just applied the change.
