### ISSUE TITLE
chinese word use underline function

### ISSUE THREAD

**Issue by juice-man** [lvgl/lvgl#1618]
# It seem too close to the word ,when I use the underline function in chinese word.
for example:
![28095456](https://user-images.githubusercontent.com/67527595/85935751-b1235500-b926-11ea-9d9a-27db97788012.png)

**Comment by liangyongxiang** [comment]
What font do you use?
Can you test the characters g and |?

**Comment by juice-man** [comment]
![image](https://user-images.githubusercontent.com/67527595/85945965-c2df1980-b973-11ea-9b16-d2e91c80e401.png)

[chinese_ui.zip](https://github.com/lvgl/lvgl/files/4842129/chinese_ui.zip)

attachment is test result and font

**Comment by liangyongxiang** [comment]
How are your font information generated and what tools are used?
You need to provide a minimal example to reproduce.

In addition, you can use font editing software such as [fontforge](https://fontforge.org/en-US/) to open your font file. The following is an example:

<img width="352" alt="image" src="https://user-images.githubusercontent.com/8002634/85953249-917d4280-b9a1-11ea-8db6-30d6457eb162.png">

<img width="440" alt="image" src="https://user-images.githubusercontent.com/8002634/85953254-a2c64f00-b9a1-11ea-8ce1-4f2525b86726.png">

From [the code here](https://github.com/lvgl/lvgl/blob/41e65d9df1f45c7ecf296913190fd10eccaf6138/src/lv_draw/lv_draw_label.c#L345), you can see how the coordinates of the underline are calculated.

I think your underline is drawn on the baseline. You can try to modify the value of baseline, but I have not tested it.

**Comment by liangyongxiang** [comment]
I think the result you need is `text-underline-position: under;`

https://developer.mozilla.org/en-US/docs/Web/CSS/text-underline-position

under:
<img width="773" alt="image" src="https://user-images.githubusercontent.com/8002634/85954030-259dd880-b9a7-11ea-8b20-bb35b10a9909.png">

auto:
<img width="813" alt="image" src="https://user-images.githubusercontent.com/8002634/85954019-1454cc00-b9a7-11ea-9470-946607092749.png">

**Comment by incity** [comment]
> How are your font information generated and what tools are used?
> You need to provide a minimal example to reproduce.
> 
> In addition, you can use font editing software such as [fontforge](https://fontforge.org/en-US/) to open your font file. The following is an example:
> 
> <img alt="image" width="352" src="https://user-images.githubusercontent.com/8002634/85953249-917d4280-b9a1-11ea-8db6-30d6457eb162.png">
> 
> <img alt="image" width="440" src="https://user-images.githubusercontent.com/8002634/85953254-a2c64f00-b9a1-11ea-8ce1-4f2525b86726.png">
> 
> From [the code here](https://github.com/lvgl/lvgl/blob/41e65d9df1f45c7ecf296913190fd10eccaf6138/src/lv_draw/lv_draw_label.c#L345), you can see how the coordinates of the underline are calculated.
> 
> I think your underline is drawn on the baseline. You can try to modify the value of baseline, but I have not tested it.

I think the problem is the underline and the font glyph  are all drawn start from baseline. @kisvegabor

**Comment by juice-man** [comment]
I used freetype2 to generate font information and call "lv_style_set_text_decor(&style, LV_STATE_DEFAULT, LV_TEXT_DECOR_UNDERLINE);" set underline function。

the follow is my code:

`

    lv_freetype_init(64); 
    static lv_font_t font1;
    lv_freetype_font_init(&font1, "/system/res/font/chinese_ui.ttf", 22);
    
    /*Create style with the new font*/
    static lv_style_t style;
    lv_style_init(&style);
    lv_style_set_text_font(&style, LV_STATE_DEFAULT, &font1);
    lv_style_set_text_decor(&style, LV_STATE_DEFAULT, LV_TEXT_DECOR_UNDERLINE);

    /*Create a label with the new style*/
    lv_obj_t * label = lv_label_create(lv_scr_act(), NULL);
    lv_obj_add_style(label, LV_LABEL_PART_MAIN, &style);
    lv_obj_set_y(label, 100);
    //lv_label_set_text(label, "d");
    lv_label_set_text(label, "中文 world and g and |");
    lv_obj_set_drag(label, 1);
    lv_obj_add_protect(label,LV_PROTECT_PRESS_LOST);
`

**Comment by kisvegabor** [comment]
The underline is really drawn on the baseline of the font. The width is automatically calculated as `height / 10` and it's symmetrically drawn on the baseline. 

Probably it'd be better to draw it below the baseline (i.e. the top of the underline should be on the baseline) 

However, the best would be to extract it from the font. FreeType can tell it like [this](https://www.freetype.org/freetype2/docs/tutorial/step2.html).

**Comment by kisvegabor** [comment]
@puzrin Can we add this information to the font description?

**Comment by puzrin** [comment]
Sure. Please create issue with description, what should be generated in lvgl format.

**Comment by kisvegabor** [comment]
Let's continue in lvgl/lv_font_conv#40
