### ISSUE TITLE
Checkbox can't be checked & disabled at the same time

### ISSUE THREAD

**Issue by weixiongmei** [lvgl/lvgl#1621]
**Describe the bug**

The checkbox can't be checked & disabled at the same time because the limitation of the API in LVGL V7.0.2, Sometimes needed a checked and disabled checkbox.

```C
/**
 * Set the state of the check box
 * @param cb pointer to a check box object
 * @param checked true: make the check box checked; false: make it unchecked
 */
static inline void lv_checkbox_set_checked(lv_obj_t * cb, bool checked)
{
    lv_btn_set_state(cb, checked ? LV_BTN_STATE_CHECKED_RELEASED : LV_BTN_STATE_RELEASED);
}

/**
 * Make the check box inactive (disabled)
 * @param cb pointer to a check box object
 */
static inline void lv_checkbox_set_disabled(lv_obj_t * cb)
{
    lv_btn_set_state(cb, LV_BTN_STATE_DISABLED);
}
```

**Comment by pete-pjb** [comment]
Hi @weixiongmei,

Looking at the API, you should be able to call:

```c
lv_checkbox_set_checked(your_ch_box, false);
```

To re-enable the widget.

Kind Regards,

Pete

**Comment by weixiongmei** [comment]
@pete-pjb not to re-enable it, want to be checked & disabled at the same time, it can only checked **or** disabled, but can't be both.

**Comment by embeddedt** [comment]
I think a workaround in the meantime is to use `lv_btn_set_state(cb, LV_BTN_STATE_CHECKED_DISABLED)`.

**Comment by kisvegabor** [comment]
> I think a workaround in the meantime is to use lv_btn_set_state(cb, LV_BTN_STATE_CHECKED_DISABLED).

There really should be an `lv_checkbox_set_state(cb, LV_BTN_STATE...)` function.

@weixiongmei 
You can use the genereic `lv_obj_add/clear_state(cb, LV_STATE_DISABLED)` functions.

**Comment by pete-pjb** [comment]
Hi @kisvegabor ,

Would you like me to add the 

> lv_checkbox_set_state(cb, LV_BTN_STATE...) function.

If so which repo would you like me to add it to?

Kind Regards,

Pete

**Comment by kisvegabor** [comment]
> Would you like me to add the

It'd be great! Thanks!

> If so which repo would you like me to add it to?

Do you mean "which branch"? If so, it can go to the dev branch, as it's a new feature.

**Comment by pete-pjb** [comment]
Sorry yes I meant which branch, I am doing this now...

I have also fixed the function  ```lv_theme_set_base()``` renamed the variable clashing with c++ keyword 'new' to 'new_theme' with this PR, will send later...  This is from #1625

**Comment by pete-pjb** [comment]
I will close this now have added new functions here: #1630
