### ISSUE TITLE
Parameter name of 'new' in lv_theme_set_base is reserved word

### ISSUE THREAD

**Issue by xennex22** [lvgl/lvgl#1625]
C++ compilers do not like it

https://github.com/lvgl/lvgl/blob/43b69a88a9f91a1e469c65d1fe35d6764eebfcbd/src/lv_themes/lv_theme.h#L207

**Comment by pete-pjb** [comment]
@xennex22, I have fixed this in a pull-request I am doing on the dev branch later today along with some other work. Hopefully will get merged later today.

**Comment by pete-pjb** [comment]
Hi @xennex22, I have fixed this here #1630 for dev branch.  I will close now.

**Comment by xennex22** [comment]
Thanks.
