### ISSUE TITLE
Roller error when copy

### ISSUE THREAD

**Issue by zhwxChaos** [lvgl/lvgl#1628]
> # Important: issues that don't use this template will be ignored/closed.

**Describe the bug**

creat a roller  by copying another one,

**To Reproduce**

lv_obj_t * roll1 = lv_roller_create(par, NULL);
lv_obj_t * roll2 = lv_roller_create(par, roll1 );

error  in lv_roller_set_options  when lv_roller_create roll2

**Expected behavior**

**Screenshots**
![Roller Error](https://user-images.githubusercontent.com/64178411/86222309-a1bb3a80-bbb8-11ea-9643-4db81e50f858.png)

**Additional context**

LVGL 7.0

**Comment by kisvegabor** [comment]
Hi,

I've just fixed it. Thank you for the report!
