### ISSUE TITLE
there is a problem with lv_img's click area after transforming.

### ISSUE THREAD

**Issue by incity** [lvgl/lvgl#1631]
1. create 2 widgets and set them draggable : lv_label first and then lv_img. (i.e. lv_label is behind lv_img)
2. change the size of lv_img or rotate it.
3. press the image to drag(near the edge), but it will drag the label instead. (but label is behind the image).

**Comment by embeddedt** [comment]
This behavior is by design. Image rotation [does not affect input processing](https://forum.lvgl.io/t/how-to-update-the-coords-when-the-image-is-scaled/1464/2?u=embeddedt).

**Comment by incity** [comment]
@embeddedt before changing the size of the image, it can be dragged normally. but after changing the size on runtime, the image becomes hard to drag.

**Comment by embeddedt** [comment]
Can you provide a code sample?

**Comment by incity** [comment]
@embeddedt  just call lv_img_set_zoom

**Comment by kisvegabor** [comment]
Please create a short video about the issue and 
- send code example with the label and image creation and settings
- attack the converted image

**Comment by incity** [comment]
@kisvegabor @embeddedt base on the lv_demo_printer.c 👍 
![image](https://user-images.githubusercontent.com/7846605/86440796-b2e18400-bd3d-11ea-9318-70a7d3ff9451.png)

    lv_img_set_pivot(scan_img, 0, 0); // seems this cause the problem
    lv_img_set_zoom(scan_img, 512);
    lv_obj_set_drag(scan_img, true);

Video:
[WeChat_20200703150328.zip](https://github.com/lvgl/lvgl/files/4868218/WeChat_20200703150328.zip)

**Comment by kisvegabor** [comment]
I see. I improved it in `master` here: e9d3001d

**Comment by incity** [comment]
thanks
