### ISSUE TITLE
How to adjust the height of the tabview?(v7.xxx)

### ISSUE THREAD

**Issue by LusterWong** [lvgl/lvgl#1632]
# All enhancement requests or questions should be directed to the Forum.

LVGL was my first use and I lacked experience. Now I'm using the latest V7.0.2 and running emulation on a PC.

Since tabview required, and the display device resolution only 240x240, although the font of the tabview can be set, how should the height be adjusted? for example I'm using a 12-point font, but I want my TabView to be 20 pixels high. What should be done?

Thx.

We use GitHub issues for development related discussions.
Please use the [forum](https://forum.littlevgl.com/) to ask questions.

**Comment by kisvegabor** [comment]
See here: https://docs.lvgl.io/latest/en/html/widgets/tabview.html#parts-and-styles

---

The title from the issue template says: "All enhancement requests or questions should be directed to the Forum."

So I close this issue. If you have further question please ask them in the forum:
https://forum.lvgl.io/

**Comment by LusterWong** [comment]
> See here: https://docs.lvgl.io/latest/en/html/widgets/tabview.html#parts-and-styles
> 
> The title from the issue template says: "All enhancement requests or questions should be directed to the Forum."
> 
> So I close this issue. If you have further question please ask them in the forum:
> https://forum.lvgl.io/

Sorry, I was too hasty. I'm not talking about the height of the tabView, but the height of the built-in matrix buttons.
For example, in the PC emulator (800x480), the tabView's selection bar height is the same as the selection bar height I used on the small screen.

![1593697002(1)](https://user-images.githubusercontent.com/56709609/86365646-5bdf9e80-bcac-11ea-890a-9f9acdbeb2fd.png)


I need to adjust the height of this section, but I can't find the relevant place in the document

**Comment by embeddedt** [comment]
You can probably change the padding of `LV_TABVIEW_PART_TAB_BG`.

**Comment by kisvegabor** [comment]
> Sorry, I was too hasty. I'm not talking about the height of the tabView, but the height of the built-in matrix buttons.
For example, in the PC emulator (800x480), the tabView's selection bar height is the same as the selection bar height I used on the small screen.


I understood it this way, and liked the relevant part of the docs:
> LV_TABVIEW_PART_TAB_BG: The tab buttons which is a Button matrix. Clicking on a button will scroll LV_TABVIEW_PART_BG_SCRL to the related tab's content. The tab buttons can be accessed via LV_TABVIEW_PART_TAB_BTN. The height of the tab's button matrix is calculated from the font height plus padding of the background's and the button's style.

**Comment by LusterWong** [comment]
> > Sorry, I was too hasty. I'm not talking about the height of the tabView, but the height of the built-in matrix buttons.
> > For example, in the PC emulator (800x480), the tabView's selection bar height is the same as the selection bar height I used on the small screen.
> 
> I understood it this way, and liked the relevant part of the docs:
> 
> > LV_TABVIEW_PART_TAB_BG: The tab buttons which is a Button matrix. Clicking on a button will scroll LV_TABVIEW_PART_BG_SCRL to the related tab's content. The tab buttons can be accessed via LV_TABVIEW_PART_TAB_BTN. The height of the tab's button matrix is calculated from the font height plus padding of the background's and the button's style.

I have read this part, but I don't know how to change the height of this area. Could you provide an example?Thank you

**Comment by pete-pjb** [comment]
Hi @LusterWong,

I think to achieve a minimal height you would need to do something like this:

```c
	lv_obj_set_style_local_pad_top(tv, LV_TABVIEW_PART_TAB_BG, LV_STATE_DEFAULT, 1);
	lv_obj_set_style_local_pad_bottom(tv, LV_TABVIEW_PART_TAB_BG, LV_STATE_DEFAULT, 1);
	lv_obj_set_style_local_pad_top(tv, LV_TABVIEW_PART_TAB_BTN, LV_STATE_DEFAULT, 1);
	lv_obj_set_style_local_pad_bottom(tv, LV_TABVIEW_PART_TAB_BTN, LV_STATE_DEFAULT, 1);
```

Kind Regards,

Pete

**Comment by LusterWong** [comment]
> Hi @LusterWong,
> 
> I think to achieve a minimal height you would need to do something like this:
> 
> ```c
> 	lv_obj_set_style_local_pad_top(tv, LV_TABVIEW_PART_TAB_BG, LV_STATE_DEFAULT, 1);
> 	lv_obj_set_style_local_pad_bottom(tv, LV_TABVIEW_PART_TAB_BG, LV_STATE_DEFAULT, 1);
> 	lv_obj_set_style_local_pad_top(tv, LV_TABVIEW_PART_TAB_BTN, LV_STATE_DEFAULT, 1);
> 	lv_obj_set_style_local_pad_bottom(tv, LV_TABVIEW_PART_TAB_BTN, LV_STATE_DEFAULT, 1);
> ```
> 
> Kind Regards,
> 
> Pete

Thank you so much!It does reduce the height!
But I still don't understand why. Haha im stupid.

**Comment by kisvegabor** [comment]
Not stupid, you can't expect to know things without learning them. :slightly_smiling_face: 

Here is the description of padding: https://docs.lvgl.io/latest/en/html/overview/style.html#padding-and-margin-properties

**Comment by pete-pjb** [comment]
Hi @LusterWong, I'll close this issue now, please feel free to re-open it if you require further assistance 😄
