### ISSUE TITLE
memory leak if image file open fails

### ISSUE THREAD

**Issue by rabbitsaviola** [lvgl/lvgl#1638]
If image src type is file  and file open fails, code below would be executed and dsc is cleared. Then allocated string memory has no chance to be freed.
https://github.com/lvgl/lvgl/blob/9e56f750a7f424d0cd52ce5ba3d4ccfa82a97866/src/lv_draw/lv_img_decoder.c#L154

**Comment by kisvegabor** [comment]
Could you send a PR for `release/v6`?

**Comment by rabbitsaviola** [comment]
@kisvegabor It seems the error handling lines in `lv_img_decoder_open` could just be removed as `lv_img_cache_open` can handle it and free the memory correctly ?

**Comment by kisvegabor** [comment]
The PR is merged so I close this issue.

Thank you for your contribution.
