### ISSUE TITLE
Chart in circular mode doesn't draw below zero

### ISSUE THREAD

**Issue by DaPa** [lvgl/lvgl#1647]
**Describe the bug**

Have chart with data series in range 0 to 25 and chart points radius = 5. In "Shift" update mode the zero points are drawn properly (centred to zero). In "Circular" update mode they are cut to zero and any old drawings are not cleaned (please see recording). 

**To Reproduce**

Attached the example project.

**Expected behavior**

In circular mode the same area is drawn as in shift mode (a bit subzero if points radius > 0 and points gets close to zero).

**Screenshots**
Capture attached.

**Additional context**

LVGL 7.1.0 on Visual Studio simulator.
![chart_test](https://user-images.githubusercontent.com/4947697/86963294-f50b2b00-c16c-11ea-97be-cf877f8b66a5.gif)
[chart_test.zip](https://github.com/lvgl/lvgl/files/4892900/chart_test.zip)

**Comment by kisvegabor** [comment]
Hi,

Thanks for the report!

I've fixed it here: 416ef9e2

Can you confirm if it works well?

**Comment by DaPa** [comment]
![perfect](https://user-images.githubusercontent.com/4947697/87045505-a5763f00-c200-11ea-8a7b-dbc83e7eec9c.gif)
Perfect! :-)

**Comment by kisvegabor** [comment]
Thanks for the feedback! :slightly_smiling_face:
