### ISSUE TITLE
How to change the order of focus(LV_INDEV_TYPE_ENCODER)?

### ISSUE THREAD

**Issue by LusterWong** [lvgl/lvgl#1651]
My system has three keys, so I use encoder input mode(LV_INDEV_TYPE_ENCODER).

I set up a container with 2 switches and 4 buttons underneath, as shown below:
![1594372204(1)](https://user-images.githubusercontent.com/56709609/87138723-6ebc2980-c2d1-11ea-8f4b-d7c45576db79.png)
With the initial position at AAA, press the Next button to switch to the next object.The order I want is AAA-BBB-CCC-DDD-EEE-FFF.
But in a different order, is AAA-DDD-BBB-CCC-EEE-FFF.

Is there any way to change the default order?

**Comment by kisvegabor** [comment]
Hi,

The order determined by in which order you add the object to the group. 

To change the order you can remove all objects from the group and add them again in the new order.

**Comment by LusterWong** [comment]
> Hi,
> 
> The order determined by in which order you add the object to the group.
> 
> To change the order you can remove all objects from the group and add them again in the new order.
I made it. Thank you very much.
