### ISSUE TITLE
suggestion about lv_label_align_t

### ISSUE THREAD

**Issue by incity** [lvgl/lvgl#1656]
1. suggest to add LV_LABEL_ALIGN_JUSTIFY
2. suggest to remove LV_LABEL_ALIGN_AUTO, and do like this in Android(add ALIGN_START and ALIGN_END):
![image](https://user-images.githubusercontent.com/7846605/87282697-1ed6a000-c527-11ea-9be6-d35b9d64a594.png)
![image](https://user-images.githubusercontent.com/7846605/87282939-5d6c5a80-c527-11ea-8446-9ba02473595c.png)
![image](https://user-images.githubusercontent.com/7846605/87282956-62310e80-c527-11ea-8238-3cb4886747f2.png)

[https://developer.android.com/reference/kotlin/androidx/ui/text/style/TextAlign](url)

**Comment by kisvegabor** [comment]
Replacing AUTO with START/END sounds reasonable. It aligns well with the termes we are planning to use with the [new layouts](https://github.com/lvgl/lvgl/issues/1615#issuecomment-654981582).

JUSTIFY is also possible.

**Comment by kisvegabor** [comment]
There will be big updates for v8 and it can be adding in it.

**Comment by kisvegabor** [comment]
Finally, I added this as an idea to the [ROADMAP](https://github.com/lvgl/lvgl/blob/master/docs/ROADMAP.md).

Thanks for the suggestion.
