### ISSUE TITLE
Adding a cursor grabs all touch events - at least on touchscreen

### ISSUE THREAD

**Issue by BenHewson** [lvgl/lvgl#1664]
Creating a cursor object for a touchscreen (maybe mouse as the input is considered the same) results in the cursor grabbing all touch events as the cursor is at the touch location.

I have posted an issue I was having on the forum HowTo section about issues with event callbacks not being called.  I have finally figured out the it was the mouse cursor causing the issue. If I don't create one, everything works fine.  I only created the cursor in the first place to verify that LVGL was getting the correct screen position.

Now this can be fixed in the code by calling

lv_obj_set_click(cursor_obj, false);

Then you can have a cursor and everything stills works.  

This seems like a sane default for a cursor object so would it not be best to add that call in the  lv_indev_set_cursor() function ?

**Comment by kisvegabor** [comment]
Hi,

Thanks for the report.

I've just fixed in the `master` branch. Now `lv_indev_set_cursor` makes the cursor object not clickable by default.
