### ISSUE TITLE
Color Picker (LV Cpicker) edge serrated especially badly.

### ISSUE THREAD

**Issue by Accidentaly-across** [lvgl/lvgl#1668]
Hi 

I found that the running effect of the Color Picker control has obvious jagged edges. Can this problem be optimized?

**Comment by Accidentaly-across** [comment]
![1594891141(1)](https://user-images.githubusercontent.com/49856978/87653709-80497980-c788-11ea-92c5-7259f85ba687.jpg)

**Comment by embeddedt** [comment]
It's a limitation of the way the color picker is rendered.  I thought it was no longer an issue in 7.0 since the edges are masked anyways, but this appears not to be the case.

**Comment by pete-pjb** [comment]
Hi @Accidentaly-across,

I have improved the edges of the colour picker widget.  The changes have been added as a hot fix in the master branch of the LVGL repository.

Kind Regards,

Pete
