### ISSUE TITLE
lv_cont_layout_grid() misjudges when put widget in new row results in space waste in right side of lv_page

### ISSUE THREAD

**Issue by adamhan2** [lvgl/lvgl#1671]
**Describe the bug**

I use lv_page with pad_left and pad_inner configured and layout enabled in GRID mode. I can't make full use of the space in a page. Larger widget without enough space left in right side would result in moving to a new row. 

**To Reproduce**

I am sorry I can't submit code snippet for now. I believe it is easy to reproduce as per description. But I can figure out the route cause for this problem.  Please see in Additional Context. 

**Expected behavior**

It should allow to put widget as big as possible to make full use of the space in a container. 

**Screenshots**
![image](https://user-images.githubusercontent.com/26458031/87787875-47ff7500-c834-11ea-94d2-dcb76367f577.png)

**Additional context**
As shown in attached screenshot, I am expecting two widgets in a row. I have to make smaller widgets to achieve that with space waste for now. 

The Route Cause: 
  In function lv_cont_layout_grid(), the condition to check if move to a new row is as below, 
     if(act_x + inner + obj_w > w_fit) --- line 631 in lv_cont.c v7.1.0
 
 That is incorrect because of two reasons. 
    --  The width w_fit =  lv_obj_get_width_fit(cont) has already taken pad_left off, but the pad_left is included to compare.
         It results in space waster of pad_left of container in lv_page.

    -- Should not force to have a space 'inner' in right side
        It results in another pad_inner waste. 

Fix Candidate: 
   Change above logic to below,
       if(act_x + obj_w > w_fit + left)

**Comment by adamhan2** [comment]
I am sorry to report it in rush. I might come back to reopen it when I have more info

**Comment by adamhan2** [comment]
Update root cause and possible fix solution.

**Comment by embeddedt** [comment]
Can you send a pull request to the `master` branch?

**Comment by kisvegabor** [comment]
Merged, thank you!
