### ISSUE TITLE
Character's bitmap not found with empty characters

### ISSUE THREAD

**Issue by persello** [lvgl/lvgl#1674]
I use a custom compressed font in my program and whenever there is a space in a label the following warning is printed:
```
lv_draw_letter: character's bitmap not found
```

I have read issue #1407 and a quick fix was applied, but it doesn't work in my case. In my font the space character (32) has `g.box_w = 6`, and this prevents the fix from being correctly triggered.

Since having only one of the two properties set to zero represents an empty character, I suggest editing line 423 from this

```c
    if((g.box_h == 0) && (g.box_w == 0)) return;
```
to this:
```c
    if((g.box_h == 0) || (g.box_w == 0)) return;
```

This edit is correctly working for me, as the error message is no longer shown and all the labels get rendered correctly and in the same way as before, but I don't know if this change could have some negative consequences for other fonts.

**Comment by kisvegabor** [comment]
Sounds reasonable! I've fixed it the `master` branch.
