### ISSUE TITLE
Spinbox coordinate position deviation

### ISSUE THREAD

**Issue by Accidentaly-across** [lvgl/lvgl#1682]
hello ,

Does the x position start from Spinbox? If the setting position is: x:0 ,y:100, the small button of Spinbox is not displayed.

![1595497268(1)](https://user-images.githubusercontent.com/49856978/88272720-bb5d2700-cd0b-11ea-87f1-5ab13826ee11.jpg)

The following example code has a bias problem.

`void lv_ex_spinbox_1(void)
{
    spinbox = lv_spinbox_create(lv_scr_act(), NULL);
    lv_spinbox_set_range(spinbox, -1000, 90000);
    lv_spinbox_set_digit_format(spinbox, 5, 2);
    lv_spinbox_step_prev(spinbox);
    lv_obj_set_width(spinbox, 100);
	lv_obj_set_pos(spinbox, 0, 100);

    lv_coord_t h = lv_obj_get_height(spinbox);
    lv_obj_t * btn = lv_btn_create(lv_scr_act(), NULL);
    lv_obj_set_size(btn, h, h);
    lv_obj_align(btn, spinbox, LV_ALIGN_OUT_RIGHT_MID, 0, 0);
    lv_theme_apply(btn, LV_THEME_SPINBOX_BTN);
    lv_obj_set_style_local_value_str(btn, LV_BTN_PART_MAIN, LV_STATE_DEFAULT, LV_SYMBOL_PLUS);
    lv_obj_set_event_cb(btn, lv_spinbox_increment_event_cb);

    btn = lv_btn_create(lv_scr_act(), btn);
    lv_obj_align(btn, spinbox, LV_ALIGN_OUT_LEFT_MID, -0, 0);
    lv_obj_set_event_cb(btn, lv_spinbox_decrement_event_cb);
    lv_obj_set_style_local_value_str(btn, LV_BTN_PART_MAIN, LV_STATE_DEFAULT, LV_SYMBOL_MINUS);
}`

**Comment by embeddedt** [comment]
In the example you gave, you're trying to align the minus button to the left of a spinbox positioned at X: 0. Therefore, the button will be aligned outside the screen. If you don't want this behavior, you should ensure that there's enough space to the left of the textbox for the button to be visible.
