### ISSUE TITLE
btnmatrix buttons don't respond to border_color when in `LV_STATE_CHECKED` state

### ISSUE THREAD

**Issue by shadowninja69** [lvgl/lvgl#1687]
**Describe the bug**

Tried to set a LV_STATE_PRESSED style to button matrix buttons, nothing happened. Tried LV_BTN_STATE_PRESSED, didn't work either.

**To Reproduce**

Here's a simple style and a btnmatrix copied from the doc that reproduces this in `lv_demo_keypad_encoder`

```
    static style = {0};
    lv_style_init(&style);
    lv_style_set_border_color(&style, LV_BTN_STATE_PRESSED, LV_COLOR_RED);

    // example copied from lv btnmatrix docs
    selector_objs.btnm1 = lv_btnmatrix_create(parent, NULL);
    lv_btnmatrix_set_map(selector_objs.btnm1, btnm_map);
    lv_btnmatrix_set_btn_width(selector_objs.btnm1, 10, 2); /*Make "Action1" twice as wide as "Action2"*/
    lv_btnmatrix_set_btn_ctrl(selector_objs.btnm1, 10, LV_BTNMATRIX_CTRL_CHECKABLE);
    lv_btnmatrix_set_btn_ctrl(selector_objs.btnm1, 11, LV_BTNMATRIX_CTRL_CHECK_STATE);
    lv_obj_align(selector_objs.btnm1, NULL, LV_ALIGN_CENTER, 0, 0);
    lv_obj_add_style(selector_objs.btnm1, LV_BTNMATRIX_PART_BTN, &style);
```

This was what confused me about #1686

**Comment by kisvegabor** [comment]
In `lv_style_set_border_color(&style, LV_BTN_STATE_PRESSED, LV_COLOR_RED);` you should use `LV_STATE_PRESSED`.

**Comment by shadowninja69** [comment]
> In `lv_style_set_border_color(&style, LV_BTN_STATE_PRESSED, LV_COLOR_RED);` you should use `LV_STATE_PRESSED`.

Like I mentioned, neither worked. But it seemed the issues was I had to use `LV_STATE_FOCUSED | LV_STATE_PRESSED` instead. Which brings the question, do I have to manually set styles for all combined states?

**Comment by shadowninja69** [comment]
Reopening and re-titled the issue, as `LV_STATE_FOCUSED | LV_STATE_CHECKED` and `LV_STATE_FOCUSED | LV_STATE_DISABLED` combined states still doesn't seem to work

EDIT: `LV_STATE_FOCUSED | LV_STATE_CHECKED` works, but can't seem to set a border. `LV_STATE_FOCUSED | LV_STATE_DISABLED` doesn't seem to work

**Comment by kisvegabor** [comment]
> Like I mentioned, neither worked. 

Oh, sorry, my bad. 

I've fixed it in 06d7a6d0.

**Comment by shadowninja69** [comment]
Thanks! It worked!
The other issue I had was `LV_STATE_CHECKED` doesn't seem to allow setting a border. Would this also be fixable?

**Comment by kisvegabor** [comment]
In the default material theme the border width of checked state is zero. So e.g. `lv_obj_set_style_local_border_width(btnm1, LV_BTNMATRIX_PART_BTN, LV_STATE_CHECKED, 3); ` makes the border appear. 
`

**Comment by shadowninja69** [comment]
ah so that's why. thanks a lot!
