### ISSUE TITLE
Sponsor link is 404

### ISSUE THREAD

**Issue by lemmih** [lvgl/lvgl#1688]
Hi, the sponsor link (<https://littlevgl.com/donate>) appears to be dead.

**Comment by kisvegabor** [comment]
Hi,

Thanks for reporting it. 

This page was not created on the new website but I've modified the link of the button to a PayPal link. Does it work correctly for you?

**Comment by lemmih** [comment]
Yes, that works for me.

**Comment by kisvegabor** [comment]
Great, thank you for the feedback!

**Comment by embeddedt** [comment]
@kisvegabor I noticed on the new GitHub sidebar that the link seems to point to a generic PayPal page (`paypalme/my/profile`); there's nothing that points to a specific LVGL profile. Is this correct?

**Comment by kisvegabor** [comment]
Thanks, updated.

Unfortunately, paypal.me doesn't support changing your name so it's still littlevgl.
