### ISSUE TITLE
lv_obj_align_origo functions: "origo" has no meaning

### ISSUE THREAD

**Issue by upbeat27** [lvgl/lvgl#1698]
In the release notes for 7.2.0 I noticed the addition of some functions, ```lv_obj_align_origo``` and related.
It looks like this is intending to be related to "origin" but I have never seen it abbreviated as "origo".
I would suggest for the sake of readability and comprehension, that these function names be changed (sooner rather than later!)

**Comment by kisvegabor** [comment]
Hi,

They can be used to align the center point of the object. Can you suggest a good name (short, still descriptive)?

**Comment by upbeat27** [comment]
```lv_obj_align_origin```
I get what the functions do, it is the "origo", or more specifically the last "o" there that makes the naming weird.

**Comment by kisvegabor** [comment]
Oh god... In Hungarian, we call the center of a coordinate system "origo". I thought it's international... :sweat_smile: 
I wonder how it wasn't mentioned so far.

Anyway, even "origin" is misleading as the origin of the coordinate system is in the top left corner of the object. So it's better to look for a totally new name. What about `lv_obj_align_mid`?

**Comment by upbeat27** [comment]
Well that explains it 🙃
You're right about origin too. I thought that was where origo was coming from...
"Mid" is shorter than "center", which is probably the other option.

**Comment by kisvegabor** [comment]
"center" might be confusing because this work is used in `LV_ALIGN_CENTER` too. 

I'll rename them to mid soon.

**Comment by upbeat27** [comment]
OK.
While you're at it... I noticed a similar issue: ```lv_chart_clear_serie```. Should be ```lv_chart_clear_series```.

**Comment by kisvegabor** [comment]
I fixed both here: bd4db19a

Thanks!
