### ISSUE TITLE
[lv_font_conv] Using a large xxx.ttf file causes a memory exception error

### ISSUE THREAD

**Issue by SmartAnda** [lvgl/lvgl#1699]
**Using the lv_font_conv, I found an exception error(about the memory request exception), which occurs when the xxx.ttf file is large(e.g. 16MB)**

--------------------------------------------------------------------------------------------------------------------------------
collect_font_data.js ==> collect_font_data
fonts_freetype[source_path] = ft_render.fontface_create(source_bin, args.size);
index.js ==> fontface_create
  let error;
  let face = {
    ptr: 0,
    font: m._malloc(source.length) ==> My test info: source.length = 13457164, an exception is raised at this location.
  };
--------------------------------------------------------------------------------------------------------------------------------

![image](https://user-images.githubusercontent.com/18000231/89100487-e0e3e200-d429-11ea-9ea2-d32269d3a4d1.png)
![image](https://user-images.githubusercontent.com/18000231/89100510-125cad80-d42a-11ea-8e38-285cb5b38e56.png)

Looking forward to your reply. Thank you in advance. 

@kisvegabor @puzrin

**Comment by puzrin** [comment]
Please provide ALL details how to reproduce, step-by-step.

**Comment by SmartAnda** [comment]
Thank you very much for your quick reply.

The reproduce method:

node lv_font_conv.js --font C:\SourceHanSansK-Regular.ttf --range 0x20-0x7F --size 24 --format lvgl --bpp 4  -o lv_font_test.c

[lv_font_ttf_test.zip](https://github.com/lvgl/lvgl/files/5010295/lv_font_ttf_test.zip)

@puzrin

**Comment by puzrin** [comment]
@SmartAnda  Tried as you said. Can not reproduce in Ubuntu 18.04LTS (both with node 12 & 14). Please, do this things and tell me result:

- what convertor version do you use (upgrae if not laest)? Similar bug was fixed in 0.3.1 
- What node/win version do you use? (`node -v`)
- If node is not latest - upgrade to last v12 or v14.
- Try web convertor in Chrome/Firefox (with different webassenbly engine)

**Comment by SmartAnda** [comment]
@puzrin I just tested this on my another computer and it was fine (the node.exe version is v12.18.2, as the image shows)
![image](https://user-images.githubusercontent.com/18000231/89105045-84e08400-d450-11ea-9e71-ed727d972adb.png)

I will confirm again on next monday.

Best Regards.

**Comment by SmartAnda** [comment]
Hey, @puzrin 
I have solved this problem now.

I just updated the lv_font_conv from github repo, and I found that the ft_render.js file has been updated.
The important point => [ freetype: allow wasm memory growth, #29 ]

Now everything is good.

Best Regards.
