### ISSUE TITLE
Change focus on message box

### ISSUE THREAD

**Issue by wxd0216** [lvgl/lvgl#170]
I have five hardware keyboard and remaped to LV_GROUP_KEY_LEFT/RIGHT/UP/DOWN/ENTER.

In this context:
I have two button on a message box, and I want to switch the focus between them with LV_GROUP_KEY_PREV/NEXT. 

lvgl can navigate among the object in a group with LV_GROUP_KEY_PREV/NEXT, but message box is a objects.

Is there any feasible solution?

Thanks

**Comment by kisvegabor** [comment]
Hi,

`LV_GROUP_KEY_LEFT/RIGHT` should go to the next button on a message box. 

Is it working there?

**Comment by wxd0216** [comment]
Hi,
I found a mistake in my code.
My hardware keyboard looks like this:
     ↑
← OK →   
     ↓
![keyboard](https://user-images.githubusercontent.com/9604301/37706474-99ed156c-2d3a-11e8-8fe5-9fd3d4877553.jpg)

Previously, I remped my hardware keyboard to LV_GROUP_KEY_PREV/NEXT/UP/DOWN/ENTER.
After your answer， I changed my key mapping relationship (LV_GROUP_KEY_PREV/NEXT/LEFT/RIGHT/ENTER.). 
And now, they work very well.   But that changed their original function(UP/Down). 

That's not what I expected. So are there any other solutions?

Thanks!

**Comment by kisvegabor** [comment]
Hi,
You are right message box should change buttons with UP//DOWN keys too. I pushed an update to support it  into the `beta` branch. Can you test it?

**Comment by wxd0216** [comment]
Yes, I've already tested it. It works very well.

Thank you very much for your support.

**Comment by kisvegabor** [comment]
Great!

Your welcome!
