### ISSUE TITLE
[suggestion] add lv_obj_is_instanceof(lv_obj* obj, const char* typename)

### ISSUE THREAD

**Issue by incity** [lvgl/lvgl#1703]
![image](https://user-images.githubusercontent.com/7846605/89275661-2516f280-d675-11ea-8534-909b356801cd.png)
the code here can be optimized.

**Comment by kisvegabor** [comment]
I can't see what's the point here. Please describe the issue or your idea in more detail.

**Comment by embeddedt** [comment]
All three of them loop through the `lv_obj_type_t` struct looking for a particular string. That loop could potentially be optimized into a common function.

**Comment by incity** [comment]
@kisvegabor the code is used to check if an object is an instance of a type. So you can offer a common function named instanceof likes the java keyword instanceof.

**Comment by kisvegabor** [comment]
Ah, got it. Sounds reasonable. 
I also like the function name you suggest.

@incity 
Are you interested in adding it?

**Comment by incity** [comment]
@kisvegabor yes I'd like to try

**Comment by incity** [comment]
@kisvegabor i found a function lv_debug_check_obj_type(...) in lv_obj.c

**Comment by kisvegabor** [comment]
Really, it does quite the same. 

I suggest implementing `lv_obj_is_instanceof` and using it in `lv_debug_check_obj_type`.

**Comment by incity** [comment]
how about move lv_debug_check_obj_type and lv_debug_check_obj_valid from lv_obj.c to lv_debug.c

**Comment by kisvegabor** [comment]
`lv_debug.c` is in the `lv_misc` folder and I like to keep these parts free from objects, styles, widgets, etc. These are just helper stuff, independent of the core lvgl.
