### ISSUE TITLE
i find in document many function of lv_style_t, but i can't find it anywhere code, like lv_style_set_text_font

### ISSUE THREAD

**Issue by xuanchibkd14** [lvgl/lvgl#1707]

**Comment by embeddedt** [comment]
[Lots of examples](https://github.com/lvgl/lv_examples/tree/master/src/lv_ex_style) are available in the `lv_examples` repository.

----------------------
We use GitHub issues for development related discussions.
Please use the [forum](https://forum.littlevgl.com/) to ask questions.

It's possible to sign in to the forum with your GitHub account... you don't need to make a separate account.
