### ISSUE TITLE
Support asynchronous GPU operation

### ISSUE THREAD

**Issue by rabbitsaviola** [lvgl/lvgl#1708]
Request to add asynchronous GPU suppot as described by this [thread](https://forum.lvgl.io/t/add-asynchronous-gpu-interface/2838)
Our hack is to add code in `_lv_refr_get_disp_refreshing` to check whether GPU is done. If GPU is still running, this function would not return. Not sure whether it's a good place to avoid conflict.

**Comment by kisvegabor** [comment]
Thanks for opening this issue.

I didn't consider this when used `_lv_refr_get_disp_refreshing` during the rendering algorithm. So it might work, but it's pure luck. :slightly_smiling_face: 

I'd prefer adding a dedicated function for this. E.g. `lv_gpu_wait(disp_refr->driver)`.

What do you think?

**Comment by rabbitsaviola** [comment]
@kisvegabor it's ok to add `lv_gpu_wait`,  but where will this function be called?

**Comment by kisvegabor** [comment]
> it's ok to add lv_gpu_wait, but where will this function be called?

That's the difficult part. :slightly_smiling_face: 

As it's only about rendering we need to ensure that all GPU operations are finished when the next drawing occurs.

My initial guess it to add in after the initial `return`s in `_lv_blend_fill` and `_lv_blend_map`. If you agree can you test it?

**Comment by rabbitsaviola** [comment]
Is it necessary to call lv_gpu_wait also in lv_refr_vdb_flush before executing `flush_cb` to make sure gpu is done?

**Comment by kisvegabor** [comment]
That's correct! It's required there too.

**Comment by rabbitsaviola** [comment]
> That's correct! It's required there too.

ok， I'll try it.

**Comment by rabbitsaviola** [comment]
@kisvegabor I created a PR  #1736, could you review it?

**Comment by kisvegabor** [comment]
I close it as the PR is merged.
