### ISSUE TITLE
Table bug: crash if set row count before column count, crash if copying a table

### ISSUE THREAD

**Issue by upbeat27** [lvgl/lvgl#1716]
**Describe the bug**

Setting a table's row count before setting the column count results in a crash (NULL dereference).
Copying a table will always result in a crash, as the copy code calls ```lv_table_set_row_cnt``` before ```lv_table_set_col_cnt```.

**To Reproduce**

```c
	lv_obj_t *t1, *t2;
	t1 = lv_table_create(lv_scr_act(), NULL);
	lv_table_set_col_cnt(t1, 1);
	lv_table_set_row_cnt(t1, 2);
	t2 = lv_table_create(lv_scr_act(), t1);
```

**Expected behavior**

Copying a table should not crash.
You should be able to set the row count/column count in either order.
Possible fix: calling ```lv_table_set_row_cnt``` should force column count to one if it is zero. Maybe there is an even better solution, as I haven't looked too far into the table code.

**Screenshots**
N/A

**Additional context**

Bug exists in master and dev.

**Comment by kisvegabor** [comment]
Hi,

Thanks for the report. I've fixed it.
