### ISSUE TITLE
lvgl crashes when using lv_page_set_scrollable_fit() for a window

### ISSUE THREAD

**Issue by mahyar1284** [lvgl/lvgl#1725]
I want to fit the scrollable area of a window, to my LCD screen. but lvgl crashes with these errors:
`Error: lv_page_get_scrollable   (lv_page.c #275 lv_page_get_scrollable())
Error: Invalid object (0xE25D3728)      (lv_debug.c #127 lv_debug_log_error())`
the code to reproduce:
`t1_adv_duty_win = lv_win_create(lv_scr_act(), NULL);
 lv_win_set_title(t1_adv_duty_win, "Advanced Duty Control");
 lv_obj_t* t1_adv_duty_win_close_btn = lv_win_add_btn(t1_adv_duty_win, LV_SYMBOL_CLOSE); 
 lv_obj_set_event_cb(t1_adv_duty_win_close_btn, lv_win_close_event_cb);
 lv_page_set_scrollable_fit(t1_adv_duty_win, LV_FIT_PARENT);`

**Comment by kisvegabor** [comment]
Try this: 
`lv_page_set_scrollable_fit(lv_win_get_content(t1_adv_duty_win), LV_FIT_PARENT)`

The `lv_win` is not an `lv_page` directly. The page is part of the window.
