### ISSUE TITLE
[7.4] Tabview button does not show press overlay

### ISSUE THREAD

**Issue by embeddedt** [lvgl/lvgl#1728]
**Describe the bug**

The tab buttons on the tabview do not show a press overlay when clicked. I am using the light material theme.

**To Reproduce**

Run `lv_demo_widgets`. Press one of the tab buttons. Observe that the press overlay does not appear.

**Expected behavior**

A gray overlay should appear when the button is clicked.

**Additional context**

If you switch the theme to dark using the switch, the press overlay appears correctly. If you then switch the theme back to light, the press overlay still appears correctly.

**Comment by kisvegabor** [comment]
It works well for me with the latest master.

**Comment by embeddedt** [comment]
I'm using `dev`.

**Comment by kisvegabor** [comment]
Thanks, I've just fixed it.

**Comment by embeddedt** [comment]
Thanks for the quick fix!
