### ISSUE TITLE
Imgbtn using label lv_label_set_align does not work

### ISSUE THREAD

**Issue by Accidentaly-across** [lvgl/lvgl#1729]
I want to set imgbtn font left alignment using the label alignment method **Lv_ label_ set_ align** I found that this method doesn't work, but if you use label alone, it's OK

**To Reproduce**
`
		LV_IMG_DECLARE(imgbtn_green);
		LV_IMG_DECLARE(imgbtn_blue);

		/*Darken the button when pressed*/
		static lv_style_t style;
		lv_style_init(&style);
		lv_style_set_image_recolor_opa(&style, LV_STATE_PRESSED, LV_OPA_30);
		lv_style_set_image_recolor(&style, LV_STATE_PRESSED, LV_COLOR_BLACK);
		lv_style_set_text_color(&style, LV_STATE_DEFAULT, LV_COLOR_WHITE);

		/*Create an Image button*/
		lv_obj_t * imgbtn1 = lv_imgbtn_create(lv_scr_act(), NULL);
		lv_imgbtn_set_src(imgbtn1, LV_BTN_STATE_RELEASED, &imgbtn_green);
		lv_imgbtn_set_src(imgbtn1, LV_BTN_STATE_PRESSED, &imgbtn_green);
		lv_imgbtn_set_src(imgbtn1, LV_BTN_STATE_CHECKED_RELEASED, &imgbtn_blue);
		lv_imgbtn_set_src(imgbtn1, LV_BTN_STATE_CHECKED_PRESSED, &imgbtn_blue);
		lv_imgbtn_set_checkable(imgbtn1, true);
		lv_obj_add_style(imgbtn1, LV_IMGBTN_PART_MAIN, &style);
		lv_obj_align(imgbtn1, NULL, LV_ALIGN_CENTER, 0, -40);

		/*Create a label on the Image button*/
		lv_obj_t * label = lv_label_create(imgbtn1, NULL);
		lv_label_set_text(label, "Button");
		lv_label_set_align(label, LV_LABEL_ALIGN_LEFT);`

The last line of code is invalid

**Comment by embeddedt** [comment]
`lv_label_set_align` just aligns the text within the label's bounding box. By default (when outside a normal button), I think the label sets its bounding box to the size of your text, so `lv_label_set_align` does nothing.

Try tweaking the size of the label and see if that gives you the results you're looking for. Alternatively, you can use `lv_obj_align` on the label and align it relative to the image button.
