### ISSUE TITLE
repeatedly call the function of 'lv_img_set_src(obj, images[index]' simulator show with tear screen.

### ISSUE THREAD

**Issue by brilliantsong** [lvgl/lvgl#1738]
repeatedly call the function of 'lv_img_set_src(obj, images[index]' simulator show with tear screen.I fell what maybe multiply thread lead to conrupt,so the buffer can't clear before dirty-data.

**Comment by kisvegabor** [comment]
Do you increment `index` or always set the same image?

**Comment by brilliantsong** [comment]
Hi:
We use the increment index to show different picture. To be emulate the animation effect we must use the API of “lv_img_set_src”.
I can’t find any error when I checked the thread relative variable,Please tell me the reason when you solved!

Thank you very much!
Regards
hui

**Comment by kisvegabor** [comment]
Most probably it happens because refreshing the framebuffer is not synchronized with VSYNC.

**Comment by Xiaolin-He-private** [comment]
Has this issue been fixed, I find that set new image source with lv_img_set_src() won't clear the old image from display buffer, maybe we can add a new api to switch image source like lv_img_change_src().

**Comment by kisvegabor** [comment]
It seems like a bug in `lv_img_set_src()`. Does it work well if you add `lv_obj_invalidate(img);` this line to the beginning of `lv_img_set_src`?
