### ISSUE TITLE
Broken link on https://lvgl.io/tools/imageconverter

### ISSUE THREAD

**Issue by ValentiWorkLearning** [lvgl/lvgl#1740]
> # Important: issues that don't use this template will be ignored/closed.

**Describe the bug**

Broken link to the tutorial on the https://lvgl.io/tools/imageconverter. 
Now the only 404 page is visible and redirecting occurs to the https://github.com/lvgl/lv_examples/blob/master/lv_tutorial/6_images/lv_tutorial_images.c

**To Reproduce**

Try to open Tutorial hyperlink
**Expected behavior**

Tutorial opens
**Screenshots**

![image](https://user-images.githubusercontent.com/25596072/90823846-2f0c4700-e33f-11ea-85fa-c497b47f5460.png)

**Comment by kisvegabor** [comment]
Fixed, thank you!
