### ISSUE TITLE
tabview bug: memory access is out of bounds

### ISSUE THREAD

**Issue by zdatou** [lvgl/lvgl#1744]
**Describe the bug**

When using "LV_TABVIEW_TAB_POS_LEFT" or "LV_TABVIEW_TAB_POS_RIGHT", "\n" (non-dynamic memory) will be inserted into the odd position of "tab_name_ptr". However, when deleting'tabview', "lv_mem_free" will be used in odd positions of'tab_name_ptr', causing memory access out of bounds

**To Reproduce**

    lv_obj_t* tabview;
    tabview = lv_tabview_create(lv_scr_act(), NULL);
    lv_tabview_set_btns_pos(tabview, LV_TABVIEW_TAB_POS_LEFT);

    lv_obj_t* tab1 = lv_tabview_add_tab(tabview, "Tab 1");
    lv_obj_t* tab2 = lv_tabview_add_tab(tabview, "Tab 2");
    lv_obj_t* tab3 = lv_tabview_add_tab(tabview, "Tab 3");

    lv_obj_t* label = lv_label_create(tab1, NULL);
    lv_label_set_text(label, "This the first tab\n\n"
        "If the content\n"
        "of a tab\n"
        "become too long\n"
        "the it \n"
        "automatically\n"
        "become\n"
        "scrollable.");

    label = lv_label_create(tab2, NULL);
    lv_label_set_text(label, "Second tab");

    label = lv_label_create(tab3, NULL);
    lv_label_set_text(label, "Third tab");

    lv_obj_clean(lv_scr_act());

**Expected behavior**

Delete tabview

**Screenshots**
![image](https://user-images.githubusercontent.com/30486172/90959863-28610980-e4d0-11ea-8673-85048d1f37a2.png)
![image](https://user-images.githubusercontent.com/30486172/90960135-1e400a80-e4d2-11ea-9479-cdda4c3f8d85.png)
![image](https://user-images.githubusercontent.com/30486172/90960144-2dbf5380-e4d2-11ea-81c1-c06fb9f8e2d2.png)

**Additional context**

**Comment by kisvegabor** [comment]
Thanks for the report!

I've fixed it here: 54b3ba39
