### ISSUE TITLE
lv_keyboard unexpected input

### ISSUE THREAD

**Issue by incity** [lvgl/lvgl#1755]
when click the text_area which locates at the bottom of screen, popup a keyboard widget, but the keyboard also receives an unexpected click.

**Comment by embeddedt** [comment]
Please provide a code sample for testing.

**Comment by turoksama** [comment]
I think i know what he is talking about.
It is too "sensitive" for your touch device, as far as i know, may 2 ways help:
1.  make indev read period longer -->20? 30? test with it.
```
/* Input device read period in milliseconds */
#define LV_INDEV_DEF_READ_PERIOD          10
```
2. wait indev_is_released after clicked.

**Comment by kisvegabor** [comment]
> wait indev_is_released after clicked.

I think this is the issue.
 Try using `lv_indev_wait_release(lv_indev_act(())` when you open the keyboard in the event callback.

**Comment by incity** [comment]
ok thanks solved

lv_indev_wait_release(lv_indev_get_act(())
