### ISSUE TITLE
Roller widget crashes when LV_USE_GROUP = 0

### ISSUE THREAD

**Issue by Alex-I-B** [lvgl/lvgl#1760]
**Describe the bug**
If LV_USE_GROUP is set to 0, demo examples with Roller widget (lv_ex_roller_1, lv_demo_widgets) crash.
**To Reproduce**
Set in lv_conf.h 
`#define LV_USE_GROUP            0`
and start e.g. lv_ex_roller_1() in a PC simulator (QT Creator/Linux). 
```
lv_init();
hal_init();
lv_ex_roller_1();
```
GUI widget does not appear. Similar situation on STM32 Nucleo F303RE board with ILI9486 driven TFT display.
**Expected behavior**

Roller widget is visible and operable.

**Screenshots**
no screenshot but an error:
Error: lv_label_set_text        (lv_label.c line 183 lv_label_set_text())
Error: NULL pointer (0x00000000)        (lv_debug.c line 127 lv_debug_log_error())

**Additional context**
Presumably LV_USE_GROUP=0 blocks (at the line 589 of the lv_roller.c) backpropagation of the signals to the ancestors. However this is necessary for LV_SIGNAL_CHILD_CHG (to automatically move newly added child to the page's scrollable container) and LV_SIGNAL_GET_TYPE (for LV_USE_ASSERT_OBJ assertions) signals.
Similar issue can occur for other widgets as well.

**Comment by kisvegabor** [comment]
Thank you for the report.
I commented on the PR.

**Comment by kisvegabor** [comment]
The PR is merged so I close this issue.
