### ISSUE TITLE
multiline textarea raise unexpected LV_EVENT_DEFOCUSED event

### ISSUE THREAD

**Issue by incity** [lvgl/lvgl#1762]
![image](https://user-images.githubusercontent.com/7846605/91679591-5e128c00-eb7b-11ea-9b9e-3b5d43350ee8.png)

![image](https://user-images.githubusercontent.com/7846605/91679680-9ca84680-eb7b-11ea-8571-52fb295bc26b.png)

when click area 2 in the pic will raise a LV_EVENT_DEFOCUSED event

**Comment by kisvegabor** [comment]
As far as I remember it's already solved. Do you use the latest version of LVGL?

**Comment by incity** [comment]
yes, has pull the lastest version of lvgl and lvgl examples

**Comment by kisvegabor** [comment]
And is it working now or you already used it?

**Comment by incity** [comment]
it's not sloved

**Comment by incity** [comment]
![image](https://user-images.githubusercontent.com/7846605/92079152-0762b780-edf2-11ea-9953-c3389c9ced93.png)

when click area 2 print LV_EVENT_DEFOCUSED and LV_EVENT_FOCUSED at the same time as follows:

![image](https://user-images.githubusercontent.com/7846605/92078912-a804a780-edf1-11ea-9159-318bc755023e.png)

**Comment by kisvegabor** [comment]
I pushed a fix, it should work well now.

**Comment by incity** [comment]
@kisvegabor still has other problem

**Comment by incity** [comment]
and for single line textarea, there is no LV_EVENT_FOCUSED  now

**Comment by incity** [comment]
![image](https://user-images.githubusercontent.com/7846605/92298409-01e4a900-ef7b-11ea-8bfc-e4db1a3069f3.png)

**Comment by kisvegabor** [comment]
Thanks for the feedback!
I've pushed a fix.
