### ISSUE TITLE
New-fs-api branch don't compile

### ISSUE THREAD

**Issue by stetzanton** [lvgl/lvgl#1766]
I try to compile new-fs-api branch to use gif-decoder on stm32f407. With master branch all ok, but with new-fs-api i receive "too few arguments to function 'lv_fs_seek'" and "to many " to lv_fs_open in lv_font_loader.c
I use myself fonts in UI. With master branch all ok.

**Comment by kisvegabor** [comment]
Hi,

I've just updated the font loader `feat/new-fs-api` branch to use the new FS API. It should work now.

**Comment by stetzanton** [comment]
All ok, this problem is gone.
