### ISSUE TITLE
[Question]Will a widget like listview appear in the future version?

### ISSUE THREAD

**Issue by ChazJin** [lvgl/lvgl#177]
Hi, thanks for sharing littlevgl which helps us a lot and gives a way to study.

My question is as shown in the title.  I think a widget like listview is useful in many fields. Look forward to having a control like listview in the future version. Express my gratitude again!
![11](https://user-images.githubusercontent.com/37656088/38077025-11d8f11a-336a-11e8-853c-be49b3c48853.jpg)

**Comment by kisvegabor** [comment]
Hi,

I'm happy to hear that LittlevGL was helpful for you. :)

I can't see/open the image you uploaded.

**Comment by ChazJin** [comment]
I highly appreciate your immediate reply! And sorry about that, because I am a beginner.

May I make bold to ask is there a plan to develop a widget like listview in the future? :-)

**Comment by kisvegabor** [comment]
No problem! :)

In #137 we had a discussion about it. It is planned in v5.2. However I can't say an exact date when it will be released.

**Comment by ChazJin** [comment]
It's a pity. I didn't see this discussion. I'll close this issue and look forward to the future version.

More hearty thanks to you.

**Comment by kisvegabor** [comment]
Do you see it on this link? 
[https://github.com/littlevgl/lvgl/issues/137](https://github.com/littlevgl/lvgl/issues/137)
