### ISSUE TITLE
[suggesstion] refactor the name of lv_tabview_btns_pos_t

### ISSUE THREAD

**Issue by incity** [lvgl/lvgl#1773]
![image](https://user-images.githubusercontent.com/7846605/92355222-69832b80-f116-11ea-8867-207551d948c5.png)

1. in the enum, use TABVIEW_TAB, but the type use name tabview_btns, i think this is not a good name.
2. position(POS) that means you can set the coordinates of x and y, but actually you can't.

DOCK is more meaningful.

```
enum {
    LV_TABVIEW_TABS_DOCK_TOP,
    LV_TABVIEW_TABS_DOCK_BOTTOM,
    LV_TABVIEW_TABS_DOCK_LEFT,
    LV_TABVIEW_TABS_DOCK_RIGHT
};
```
typedef uint8_t lv_tabview_tabs_dock_t;

GRAVITY is also a good alternative

```
enum {
    LV_TABVIEW_TABS_GRAVITY_TOP,
    LV_TABVIEW_TABS_GRAVITY_BOTTOM,
    LV_TABVIEW_TABS_GRAVITY_LEFT,
    LV_TABVIEW_TABS_GRAVITY_RIGHT
};
typedef uint8_t lv_tabview_tabs_gravity_t;
```

https://developer.android.com/reference/com/google/android/material/tabs/TabLayout

**Comment by incity** [comment]
![image](https://user-images.githubusercontent.com/7846605/92470420-f9090700-f208-11ea-963f-3ff2e622f1d7.png)

**Comment by incity** [comment]
![image](https://user-images.githubusercontent.com/7846605/92470565-34a3d100-f209-11ea-87bf-ed38a971498c.png)

**Comment by embeddedt** [comment]
I agree with changing the last two (please send a PR); @kisvegabor should comment on the first one.

**Comment by kisvegabor** [comment]
Regarding the rename suggestion, the tabview will be reworked in v8. I'll consider it during this rework.

**Comment by incity** [comment]
@kisvegabor will the tabview support any number of tabs in v8?

**Comment by kisvegabor** [comment]
It supports any number of tabs in v7 too. Or what do you mean?

**Comment by incity** [comment]
> It supports any number of tabs in v7 too. Or what do you mean?

It will cover each other when add too many tabs or tabs name too long

**Comment by kisvegabor** [comment]
What would you expect instead? Multiple rows, or scrolling on the header part?

**Comment by incity** [comment]
it's more better to do a auto scroll as in android

**Comment by kisvegabor** [comment]
So scrolling on the buttons, and snap the active button to center?

**Comment by incity** [comment]
there is a demo here @kisvegabor 

https://material.io/components/tabs

![image](https://user-images.githubusercontent.com/7846605/93155021-add68300-f737-11ea-8f93-2c86c039d19a.png)

**Comment by kisvegabor** [comment]
Got it, thanks!

It can be demonstrated in a component.

**Comment by incity** [comment]
@kisvegabor  i found you will remove lv_page and make all object scrollable, im curious that if it's possible to make all object also support scalable(even the rotation) as Android's View(the base object of the widgets) does.
![image](https://user-images.githubusercontent.com/7846605/93184689-1ee55d00-f76f-11ea-802f-76ed760095f4.png)
![image](https://user-images.githubusercontent.com/7846605/93184713-2573d480-f76f-11ea-9c27-d44498d6ece2.png)

this can also help the canvas do scale transformation but not just do zoom transformation.

https://android.googlesource.com/platform/frameworks/base/+/master/core/java/android/view/View.java

**Comment by kisvegabor** [comment]
I'm planning for a long time to make it possible to create screenshots from objects (with all children) to allow transformations (zoom, scale, blur, etc). It should be an internal mechanism, so if LVGL sees that a child has changed, it updates the screenshot.

In the future please use the [Future request category](https://forum.lvgl.io/c/feature-request) of the forum for similar topics.
If you have comments to the scaling topic, please post it in the forum and continue there.
