### ISSUE TITLE
Button matrix button heights are not equal across all rows

### ISSUE THREAD

**Issue by upbeat27** [lvgl/lvgl#1776]
**Describe the bug**

The `lv_btnmatrix` object adjusts the height of each row of buttons to fit within the total height.
The last row always ends up taller than the rest.

**To Reproduce**

```c
lv_obj_t  * obj = lv_btnmatrix_create(main_page, NULL);
	
static const char *opts[] = {" ", "\n", " ", "\n", " ", "\n", " ", "\n", " ", "\n"," ", "\n", " ","\n", " ", "\n", " ", ""};
lv_obj_set_width(obj, 140);
lv_obj_set_height(obj, 520);
lv_btnmatrix_set_map(obj, opts);
```

**Expected behavior**

Each row should be the same height (+/- 1 pixel)

**Screenshots**

![image](https://user-images.githubusercontent.com/32659164/92625307-55a60980-f27d-11ea-94d1-e1d852c4f9cd.png)

**Additional context**

It _looks_ fixed if this line is removed from `lv_btnmatrix_set_map` in `lv_btnmatrix.c`:
```c
btn_h--; /*-1 because e.g. height = 100 means 101 pixels (0..100)*/
```

![image](https://user-images.githubusercontent.com/32659164/92625743-ea106c00-f27d-11ea-9aab-a8791fa7f6e6.png)

**Comment by kisvegabor** [comment]
Actually it was a rounding error. It's still not perfect but now I round the line height and it gives a much better result.
