### ISSUE TITLE
there is a problem with the round corner of the lv_cont.

### ISSUE THREAD

**Issue by incity** [lvgl/lvgl#1778]
![image](https://user-images.githubusercontent.com/7846605/92671940-21e4e580-f34a-11ea-961d-39f66b77c412.png)

**Comment by embeddedt** [comment]
`clip_corner` is usually disabled by default for performance reasons. If you enable that, and are still seeing the issue, it's likely a duplicate of #1777.

**Comment by incity** [comment]
oh ok, how to enable it?

**Comment by embeddedt** [comment]
I think this should work:

```c
lv_obj_set_style_local_clip_corner(cont, LV_STATE_DEFAULT, LV_CONT_PART_MAIN, true);
```
