### ISSUE TITLE
Symbol

### ISSUE THREAD

**Issue by Moo2017** [lvgl/lvgl#178]
Hi All,
I'd like to know how I can change and redraw the existing symbols shape or add new symbols? I should use font converter tools or change the existing files in lv_fonts?
Thanks

**Comment by kisvegabor** [comment]
Hi,

Yes you can use the font converter tool. 
To add new symbols: 
  - You can't use the current names (e.g. SYMBOL_OK) as they reference to the current symbols
  - You can use the UTF-8 code form your fonts. For example: Unicode: `U+2713` -> UTF-8: `"\xE2\x9C\x93"`
  - You can also define the new symbol names as you can see in : `lv_misc/lv_fonts/lv_symbol_defs.h`

**Comment by Moo2017** [comment]
@kisvegabor Thank you I'll try it. I have another question and it may not be relative to this topic . Assume that I have created an screen with some buttons there once user click on one of the button a keyboard object appears , after type the desired text and press ok button , the main screen should appears , In OK action I delete the keyboard obj but still text area has remained and I don't have access to that in OK action callback function, for now I created a global variable for text area so I am able to delete it in keyboard callback function  but I don't know what is the best way or there is other solutions  , I hope I have had some helps here. Thanks in advance

**Comment by kisvegabor** [comment]
Okay, I'm waiting for the results.

Please create a new issue for the new topic to keep the issues clear.

**Comment by Moo2017** [comment]
OK sure

**Comment by kisvegabor** [comment]
It seems the original question is answered so I close this issue. But if you have any remarks feel free to reopen it!

**Comment by Moo2017** [comment]
Hi,
Oh sorry I was busy with other stuff and couldn't test this, I still have problem with the original question. I got a little bit confused. I don't want to create new fonts I want to add more symbols in the existing symbol files. For example I want to add  the following photo in lv_font_symbol_30, would you please let me know what should be done? should I convert that first to TFT file? Would you please provide me with an example of how Font converter should be set up for that?
![link](https://user-images.githubusercontent.com/34062463/40192754-4f31c9c6-59d3-11e8-980d-f912c8212709.png)

**Comment by kisvegabor** [comment]
I suggest the following:
1. Convert only the required symbols using the [online font converter](https://littlevgl.com/ttf-font-to-c-array)
2. Define the new symbols like in lv_symbol_defs.h (use the UTF8 coded Unicode codes)
3. Create a new font by appending `lv_font_symbol_30` to your font: `lv_font_add(&my_font_30, &lv_font_symbol_30)`
4. After it when you use `&my_font_30` it will "see" `lv_font_symbol_30` too.

I used the FontAwesome font in the symbol fonts. It also has a "link" icon which you need.

**Comment by Moo2017** [comment]
Thank you very much. But my problem is I don't know how use the  "online font converter ". I have a .ipg file for that specific symbol, I converted that to .tft to attach as a TTF file in font converter. I chose 30 as height, 8 bit , I don't know what I should insert in Rang and list?!  I would really appreciate if you can provide me with an example for that specific symbol that I had sent you in the previous message.

**Comment by kisvegabor** [comment]
Here are the settings:
![image](https://user-images.githubusercontent.com/7599318/40240134-2ca8194c-5ab8-11e8-8dea-024bd581b530.png)

And the font file and the result C file:
[font.zip](https://github.com/littlevgl/lvgl/files/2017266/font.zip)

**Comment by Moo2017** [comment]
Thank you. where did you put the .jpg file? it's not in fontAwesone.ttf? sorry if my question seems very obvious but I don't know how put the icon's image??

**Comment by kisvegabor** [comment]
I just used the similar icon from FontAwesome :)
I you send your TTF file I can check it and try to generate the font with it. However because of consistency I suggest to use FontAwesome if you are happy with it's symbol.

**Comment by Moo2017** [comment]
I found a converter to convert to .tiff but I can not attach .tiff file here. Our customer wants some specific symbols unfortunately :(  
Maybe I should do some research and learn more about fonts . I got totally confused :(

**Comment by kisvegabor** [comment]
You can attache everything here if you compress it first to zip.

Once you have a TTF font you will be able to load it to LittlevGL. So the goal is to get TTF at the end.

**Comment by Moo2017** [comment]
[link (1).zip](https://github.com/littlevgl/lvgl/files/2018099/link.1.zip)

**Comment by kisvegabor** [comment]
The font converter needs a TTF font file but you sent a TIFF which is an image file.

I you  have image resource why don't you use `lv_img` instead of `lv_label`?

**Comment by Moo2017** [comment]
Because if I use image I have to match image background color  based on screen background and if I change the screen background I have to change img color again. I have an information bar at the top of my screen and I need to display some information as network connection status, WiFi status, battery level and ... . I created a container and wanted to add these  as symbols.

**Comment by kisvegabor** [comment]
You can use transparent image background. 
Please read this: https://littlevgl.com/object-types/image-lv_img

**Comment by Moo2017** [comment]
Thank you. I tried this but the output was not correct , should image have specific characteristic or specific background color? However, I changed the background image color in .c file from image converter manually ( changed to LV_COLOR_TRANSP ) and it worked fine but I don't know why image converter didn't recognize the background image and didn't convert to LV_COLOR_TRANSP .
For your information I added the image and also the .c file 
I selected "Chroma keyed" in image converter-  
color depth 24bits
linkIcon.c (output from image converter)
linkIcon_manuallychanged.c (output from image converter and then manually changed)

[files.zip](https://github.com/littlevgl/lvgl/files/2039449/files.zip)

**Comment by kisvegabor** [comment]
You should edit your image with an image editor program (e.g. Photo shop or GIMP):
- To use **chroma keying** you should set the background to `LV_COLOR_TRANSP`. It can't be done in the converter program because it's quite difficult to separate the background from the content and needs a human's eye and feel.
- Similarly  for **transparency** you can apply a transparent background in the editor software. It will result smoother edges.
