### ISSUE TITLE
How to achieve dimming of all objects except for focused object in a group

### ISSUE THREAD

**Issue by upbeat27** [lvgl/lvgl#179]
I've been trying to think of a way to show an object within a group as being "editable" vs. "focused".

**Background:**
Imagine a UI with only and encoder. So you have available only three actions - left, right, click.
You can use left/right to select an object within a group, and use the style modifier to highlight the focused object in some way. This is fine.
But, you don't have another set of two buttons - for example, up/down, to edit the focused object.
So instead, you use the click of the encoder to switch from _selecting an object_ to _editing an object_.
This functionality is implemented outside of lvgl, since there is nothing built in.
At this point there seems no easy way to further indicate the focused object is now editable (that is, turning the encoder will now edit the object as opposed to focusing the next/prev object).

**An attempt to handle this outside of lvgl:**
I want to do something like dim all objects other than the focused object when "edit" mode has been entered. This makes it very clear that this object is editable.
Let's say my GUI is always a page with some objects grouped in the page.
I'm thinking something like this:
When edit mode is entered, a new page is created to _cover_ the existing page, with some opacity so that the existing page appears dim.
At the same time, the focused object is moved from the original page to the new page, so that it remains _undimmed_.
Clicking again to leave edit mode, the object is moved back to its original page, and the new page is deleted.
The overall effect would just appear as if everything but the focused and editable object dimmed.

But... I'm having a hard time achieving this effect. The first problem is creating the page on top of the existing page, while having the exact same dimensions. This is necessary so that the object's position appears the same as it jumps from page to page.
The second problem is with the opacity. It seems like no matter how I style it, the new page fully covers the old instead of being semi-opaque.

If there are any ideas of how to achieve this effect, or just in general how to deal with focused vs editable with just an encoder as the UI, please chime in!

**Comment by upbeat27** [comment]
I managed to achieve something close to what I was imagining:

![image](https://user-images.githubusercontent.com/32659164/38146528-43b09514-3403-11e8-86f0-1dc613997ba5.png)

In the image the top slider is in "edit" mode and looks normal whereas everything else appears dim.

The outstanding issue is that for some reason the scrollbar of the page is not dimmed along with everything else.
As far as I can tell, it should be, because the "overlay" object is created on top of the page (the original page and the overlay have the same parent). Also the size of the "overlay" fills the whole screen.

But yeah, it's not a simple solution... a lot has to be handled. Moving the focused object to to new "overlay" object when editing and back to the original page when leaving edit mode is not as simple as it sounds at first, due to the way the x & y are determined in the scroll-able part of the page vs. the actual page. Also, when you move an object from the page to the "overlay" it will change the page size since there are fewer objects. So, you have to lock in the page scroll-able height after filling it with the objects you know will be inside it.

Anyway, it sorta works and is better than having no way of indicating an object is being edited vs. just being in focus.

I think some discussion around the original problem could maybe help reveal a better solution or something that can be done within lvgl so that an encoder controlled UI is feasible.

**Comment by BenArtes** [comment]
Is the scroll bar enabled on the new page?  What are the settings in the scroll bar style?

**Comment by upbeat27** [comment]
Actually instead of doing a new page for the "overlay" I just went with a base object. That made more sense since I really just needed a completely blank full-screen object with some opacity. So the scroll bar is definitely on the original page.

I don't think there is anything in the scroll bar style that could make it appear to be in the front even when an object is in front of the page. Maybe I'm wrong though, I have to take a look...

One interesting thing I just tested. If the "overlay" is set to 255 (fully opaque), everything goes black as you would expect, except for the object being edited of course.
Change the opacity to 254, and the scrollbar comes back at full intensity. So the scrollbar seems to be either there or not, without any regard for the opacity of an object in front of it.

**Comment by BenArtes** [comment]
Yeah, looking at the page design function in `lv_page.c`, it appears the scroll bar is draw after everything else.  I'm guessing to make sure it's drawn above all widgets on the page?

```c
static bool lv_page_design(lv_obj_t * page, const lv_area_t * mask, lv_design_mode_t mode)
{
    if(mode == LV_DESIGN_COVER_CHK) {
    	return ancestor_design(page, mask, mode);
    } else if(mode == LV_DESIGN_DRAW_MAIN) {
        /*Draw without border*/
        lv_style_t *style = lv_page_get_style(page, LV_PAGE_STYLE_BG);
        lv_coord_t border_width_tmp =  style->body.border.width;
        style->body.border.width = 0;
        lv_draw_rect(&page->coords, mask, style);
        style->body.border.width = border_width_tmp;

	} else if(mode == LV_DESIGN_DRAW_POST) { /*Draw the scroll bars finally*/

        /*Draw only a border*/
        lv_style_t *style = lv_page_get_style(page, LV_PAGE_STYLE_BG);
        lv_coord_t shadow_width_tmp =  style->body.shadow.width;
        uint8_t empty_tmp =  style->body.empty;
        style->body.shadow.width = 0;
        style->body.empty = 1;
        lv_draw_rect(&page->coords, mask, style);
        style->body.shadow.width = shadow_width_tmp;
        style->body.empty = empty_tmp;


		lv_page_ext_t * ext = lv_obj_get_ext_attr(page);

		/*Draw the scrollbars*/
		lv_area_t sb_area;
		if(ext->sb.hor_draw) {
		    /*Convert the relative coordinates to absolute*/
            lv_area_copy(&sb_area, &ext->sb.hor_area);
		    sb_area.x1 += page->coords.x1;
            sb_area.y1 += page->coords.y1;
            sb_area.x2 += page->coords.x1;
            sb_area.y2 += page->coords.y1;
			lv_draw_rect(&sb_area, mask, ext->sb.style);
		}

		if(ext->sb.ver_draw) {
            /*Convert the relative coordinates to absolute*/
            lv_area_copy(&sb_area, &ext->sb.ver_area);
            sb_area.x1 += page->coords.x1;
            sb_area.y1 += page->coords.y1;
            sb_area.x2 += page->coords.x1;
            sb_area.y2 += page->coords.y1;
			lv_draw_rect(&sb_area, mask, ext->sb.style);
		}
	}

	return true;
}
```

**Comment by upbeat27** [comment]
I saw that, but I think it is only supposed to draw after all of its children, not its siblings.
If it does indeed draw after its siblings as well, I think that is unintended or at least unexpected behavior. When a sibling is in front of a page, it should be in front of the scrollbar as well.
Hopefuly @kisvegabor can chime in on that.

**Comment by kisvegabor** [comment]
Hi,

The scrollbar is drawn when all the children of the page is drawn. 
If you created the opaque base object as the sibling of the page (e.g. `lv_obj_create(lv_scr_act(), NULL);`) then it should cover the scrollbar. If you send a simplified code of your GUI I could test it.

To the original issue (selected-edited mode): What about using a different `style mod` function in edit and selected modes. A "lighter" in selected and a "more visible" in edit?

**Comment by upbeat27** [comment]
The overlay is created by `overlay = lv_obj_create(lv_obj_get_parent(page), NULL)` so it should be a sibling of the page - it does cover everything except for the scrollbar.
Maybe it needs to be created on `lv_scr_act()` instead - I'll have to try that.

The problem with a different style mod function for selected vs. edited is that there is only so much you can do with a style to differentiate things. It is hard enough to differentiate focused vs. non-focused objects on a small, non-color display. To need a third variation that is easily distinguishable from the other two is not easy.

Another method I have investigated is to animate the object in "edit" mode. This is the least complicated solution I have tried, and it is very clear when you are in edit mode. Basically I just start an animation on the object to be edited that varies the border opacity, so the border sort of fades in/out. When leaving edit mode you just delete the animation. This is probably the way I'll end up going, it is easily handled outside of lvgl.

**Comment by kisvegabor** [comment]
Adding an animation in edit mode is a very good idea! I never thought about it but it really adds a new "dimmension". 

The scrollbar drawing is strange to me. Can you send a code where you experience this issue?
