### ISSUE TITLE
lv_list : why clear the last selected button when lv_list get defocused

### ISSUE THREAD

**Issue by incity** [lvgl/lvgl#1797]
![image](https://user-images.githubusercontent.com/7846605/93416877-45bfa280-f8d9-11ea-9dd7-c509b487808c.png)

It looks like that:

[WeChat_20200917110239.zip](https://github.com/lvgl/lvgl/files/5236127/WeChat_20200917110239.zip)

**Comment by kisvegabor** [comment]
Because `act_sel_btn` is only a visual highlight to navigate a button. If the list is not focused, you can't navigate there, so the highlight makes no sense.

**Comment by kisvegabor** [comment]
As the question was answered I close this issue.
