### ISSUE TITLE
textarea can not cancel selection when click the area out of the inputed chars.

### ISSUE THREAD

**Issue by incity** [lvgl/lvgl#1812]
![image](https://user-images.githubusercontent.com/7846605/94014897-c05b5700-fdde-11ea-8880-67d52666cbe3.png)

click area 2 can not cancel text selection.

by the way, how can i delete the selected chars?

**Comment by kisvegabor** [comment]
How did you try to cancel it?

**Comment by incity** [comment]
@kisvegabor click area 2 should cancel the selection, right?

**Comment by kisvegabor** [comment]
No, it shouldn't. The selection is managed by the user. 

However, I agree that the area can be improved to make these things automatic.

**Comment by kisvegabor** [comment]
I close this issue because it's not bug but the intended behavior.

If you have remarks about this topic feel free to comment here and reopen the issue.
