### ISSUE TITLE
Checkbox tick broken

### ISSUE THREAD

**Issue by tgillbe** [lvgl/lvgl#1813]
**Describe the bug**

The checkbox tick no longer shows up when the checkbox is checked.

**To Reproduce**

```
lv_checkbox_create(bg, NULL);
```

**Expected behavior**

The checkbox tick to appear when the checkbox is checked.

**Screenshots**

Example is with material theme.

Before:
![image](https://user-images.githubusercontent.com/6849866/94036348-1f5ba480-fdbc-11ea-9f27-c6e6831bd390.png)

After:
![image](https://user-images.githubusercontent.com/6849866/94036403-2da9c080-fdbc-11ea-90a2-f394e83d1cac.png)

**Additional context**

git bisect indicates the issue appeared in 81884401d236ff5cf47148ce307033e5d0c049ae

**Comment by kisvegabor** [comment]
Hi,

I've noticed a realted issue a few hours ago and fixed it master. Does it work with the latest master?

**Comment by tgillbe** [comment]
Yes, it's working. I was on v7.6.0, didn't think to try with master! Thanks!

**Comment by tgillbe** [comment]
Actually it's not entirely fixed - if a checkbox is programmatically set to checked then it shows as unchecked until you click it twice (once to uncheck, once to check again).

```
lv_obj_t *chk = lv_checkbox_create(background, NULL);
lv_checkbox_set_checked(chk, true);
```

**Comment by kisvegabor** [comment]
Ah, really. 
I've just pushed fix for it too.

**Comment by embeddedt** [comment]
@kisvegabor I don't see the fix. Was there a conflict? (I just updated the README to test a GitHub Action, so maybe your commit wasn't pushed.)

**Comment by kisvegabor** [comment]
@embeddedt Oh, yes. Now it's there.

**Comment by tgillbe** [comment]
It's now showing the correct checked state but the checked animation plays when the page loads. Not an issue for me because my theme doesn't use an animation but it looks bad on the material theme.

Unfortuantley there doesn't seem to be an lv_example with the checkbox checked by default, but lvgl/docs#154 would have been great for reporting this!

**Comment by kisvegabor** [comment]
I've fixed it as well.

**Comment by tgillbe** [comment]
All working now, thanks!

**Comment by kisvegabor** [comment]
Cool, thanks for the testing and feedback!
