### ISSUE TITLE
Image as a button

### ISSUE THREAD

**Issue by Moo2017** [lvgl/lvgl#182]
I was wondering if it is possible to have an image as an button or how can I add an image as a symbol and then assign that to the button text?

**Comment by xiaoxinda** [comment]
https://littlevgl.com/image-to-c-array
This page is a img to c array tools
if your button is a transparent background image, through it to convert to alpha channel

**Comment by kisvegabor** [comment]
It's a planned feature in v5.2 to have an object type similar to a button but show different images in each state.

**Comment by Moo2017** [comment]
@kisvegabor Sounds good , it can be a really useful feature. Thank you

**Comment by Moo2017** [comment]
@xiaoxinda Sorry I didn't get that, I am gonna use lvgl button object but add an image to the button, but since the image background might be different from the button ( button has two different background in press or release state) it doesn't look good.

**Comment by kisvegabor** [comment]
Hi,

I added the `lv_imgbtn` object to `dev-5.2` branch. You can set different images in each state with `lv_imgbtn_set_src()`. The add actions use `lv_imgbtn_set_action()`

If you update `lvgl` to `dev-5.2` you also should update `lv_examples` to `dev-5.2` and convert your images again with the [new image converter tool](http://www.test.littlevgl.com/image-to-c-array) .

For clearence I close this issue, but of tested it and something not works feel free to reopen it and comment here.
