### ISSUE TITLE
fbdev show error 

### ISSUE THREAD

**Issue by Layty** [lvgl/lvgl#1821]
I can use QT tu show the Fb, so I think My driver is ok.

when I show `123456789` ,It show monitor like that 
![image](https://user-images.githubusercontent.com/14368090/94662090-81775500-033a-11eb-8fe8-b2e6030bc5a1.png)

so  which config should I do  

my oled is 160*160, 1bpp

**Comment by Layty** [comment]
Now I have fix It  in  /lv_drivers/display/fbdev.c  



![image](https://user-images.githubusercontent.com/14368090/94664165-2abf4a80-033d-11eb-98df-0e1f006c4efd.png)

**Comment by kisvegabor** [comment]
Hi,

I don't know if it was ever tested with 1bpp frame buffers. 
It seems logical to map the MSB to the left pixel so we can update the driver like this. Can you send a Pull request?

**Comment by embeddedt** [comment]
It might be worth adding an option for this in `lv_drv_conf.h`, otherwise we'll get an issue opened in a few weeks mentioning that the driver is now broken for another 1bpp display we didn't know about. :wink:

**Comment by kisvegabor** [comment]
True. 
I think something like `FBDEV_1BPP_MSB_LEFT` can work.

**Comment by Layty** [comment]
I am a rookie, I suggess If any api about frambuf for app user to know  MSB or LSB?

**Comment by kisvegabor** [comment]
> I suggess If any api about frambuf for app user to know MSB or LSB?

Do you mean if the system tells the order?

**Comment by Layty** [comment]
yes ,  I think Qt works well my be it use some api to read fb driver info

**Comment by Layty** [comment]
mybe use  like
struct fb_bitfield {
	__u32 offset;			/* beginning of bitfield	*/
	__u32 length;			/* length of bitfield		*/
	__u32 msb_right;		/* != 0 : Most significant bit is */ 
					/* right */ 
};

**Comment by kisvegabor** [comment]
Please let us know if you find a related configuration.
