### ISSUE TITLE
Style transform_width/height with transition

### ISSUE THREAD

**Issue by jupeos** [lvgl/lvgl#1825]
**Describe the bug**
When using lv_style_set_transform_width/height in conjunction with a transition animation the time is not honoured for the pressed state.
Tested on simulator with a simple button, changing its width and height when pressed.

**To Reproduce**
The button pressed transition occurs immediately (ignoring transition time) but the reverse (released button) transitions correctly. Note: the transform is correct, just the time it takes is off.
```
static lv_style_t buttonStyle;
static const lv_style_int_t BUTTON_TRANSITION_TIME = 2000;
static const lv_style_int_t BUTTON_SIZE_OFFSET_ANIM = 10;

lv_obj_t* create_func( lv_obj_t* parent )
{
    lv_style_init( &buttonStyle );
    lv_style_set_transform_width( &buttonStyle, LV_STATE_PRESSED, BUTTON_SIZE_OFFSET_ANIM );
    lv_style_set_transform_height( &buttonStyle, LV_STATE_PRESSED, BUTTON_SIZE_OFFSET_ANIM );
    
    lv_style_set_transition_time( &buttonStyle, LV_STATE_PRESSED, BUTTON_TRANSITION_TIME );
    lv_style_set_transition_time( &buttonStyle, LV_STATE_DEFAULT, BUTTON_TRANSITION_TIME );

    lv_style_set_transition_prop_1( &buttonStyle, LV_STATE_PRESSED, LV_STYLE_TRANSFORM_WIDTH );
    lv_style_set_transition_prop_2( &buttonStyle, LV_STATE_PRESSED, LV_STYLE_TRANSFORM_HEIGHT );
    lv_style_set_transition_prop_3( &buttonStyle, LV_STATE_DEFAULT, LV_STYLE_TRANSFORM_WIDTH );
    lv_style_set_transition_prop_4( &buttonStyle, LV_STATE_DEFAULT, LV_STYLE_TRANSFORM_HEIGHT );

    lv_obj_t* testButton = lv_btn_create( gauge, NULL );
    lv_obj_reset_style_list( testButton, LV_CONT_PART_MAIN );
    lv_obj_add_style( testButton, LV_BTN_PART_MAIN, &buttonStyle );	
```

**Expected behavior**
Pressing the button should transform the width/height of the button to the new value over the specified time period.

**Additional context**
7.5.0-dev sync 14th Sept 20

**Comment by kisvegabor** [comment]
Hi,

Thanks for the report! I could reproduce the issue and pushed a fix the the `master` branch.

BTW, if you define a parameter in the default state it will be true in the pressed state too. So it's enough to write this:
```c
    lv_style_set_transition_prop_1( &buttonStyle, LV_STATE_DEFAULT, LV_STYLE_TRANSFORM_WIDTH );
    lv_style_set_transition_prop_2( &buttonStyle, LV_STATE_DEFAULT, LV_STYLE_TRANSFORM_HEIGHT );
```
