### ISSUE TITLE
[BUG] Messagebox Style Not Working If Buttons Added Afterward

### ISSUE THREAD

**Issue by weixiongmei** [lvgl/lvgl#1827]
If the style added for **LV_MSGBOX_PART_BTN_BG** & **LV_MSGBOX_PART_BTN** before **lv_msgbox_add_btns**, the style will not going to work.

**Comment by weixiongmei** [comment]
@kisvegabor, Yes, setting the background of the message box itself works fine. But should it also works even adding the buttons afterward? Because that way only one message box context is needed and can be reuse for all other purpose.

**Comment by kisvegabor** [comment]
Sorry, I don't really understand the issue. Can you send a code snippet to see what the problem is?
