### ISSUE TITLE
Minor bug in lv_disp_get_inactive_time

### ISSUE THREAD

**Issue by xennex22** [lvgl/lvgl#1836]
https://github.com/lvgl/lvgl/blob/6b24c949f1d904ccbcf730849e3f3aedafc5c94f/src/lv_core/lv_disp.c#L317-L337

Code after ```if(disp) return lv_tick_elaps(disp->last_activity_time);``` is never executed.  I'm not sure of the original intent so are not going to propose a fix, plus it looks like it is designed to cope with multiple displays.

It's a good example of how multiple return statements in one function hinder readability and hide bugs.  The classic ```if(param == NULL) return;``` is usually not a good sign.

**Comment by kisvegabor** [comment]
Hi, 

Thanks for reporting this.

Probably it was a copy-paste issue. The first lines are not required here because `disp` can be `NULL`. I've pushed a fix. 

I think the multiple vs single return statements question is an endless argument. :) I prefer single return point to avoid huge nested branches.

**Comment by embeddedt** [comment]
My approach is usually to evaluate what the function is doing. If it's the type of function that does something, then always has to call a cleanup/unlock function before returning (e.g. something with mutexes) I try to stick to a single return point. Duplicated `mutex_unlock` statements everywhere are often bug-prone and messy. If someone ever added another branch they could easily forget to unlock the mutex.

In simple functions I think it matters less.

**Comment by C47D** [comment]
Not an expert, but I would rather assert on NULL parameter when not expecting it.
