### ISSUE TITLE
RTL Dropdown selection problem

### ISSUE THREAD

**Issue by amirgon** [lvgl/lvgl#1842]
**Describe the bug**

On RTL dropdown list, element is correctly selected only when clicking on the text label.
When selecting the empty space of an option, the dropdown list closes, but the wrong element is selected.  

Here is an example trying to select "item 1", but item 2 keeps being selected until clicking on the "item 1" text label.

![Peek 2020-10-09 01-04](https://user-images.githubusercontent.com/11742638/95518559-ffd39700-09cb-11eb-8b0b-34fa88b02235.gif)

**To Reproduce**

```python
scr = lv.obj()
scr.set_style_local_text_font(scr.PART.MAIN, lv.STATE.DEFAULT, lv.font_dejavu_16_persian_hebrew)
scr.set_base_dir(lv.BIDI_DIR.RTL)

def dd_cb(obj, e):
    if e == lv.EVENT.VALUE_CHANGED:
        print("Selected " + str(obj.get_selected()))

dd = lv.dropdown(scr)
dd.set_width(400)
dd.set_options("item 1\nitem 2")
dd.set_event_cb(dd_cb)

lv.scr_load(scr)
```

**Expected behavior**

Clicking on any point of an option should change the selection to that option.

**Comment by kisvegabor** [comment]
Hi,

I've pushed a fix for it.

**Comment by amirgon** [comment]
Thanks!

Closing.
