### ISSUE TITLE
Montserrat 8 and 10px fonts are not available

### ISSUE THREAD

**Issue by gmarull** [lvgl/lvgl#1845]
**Describe the bug**

If Montserrat fonts for 8 and 10px sizes are enabled and used by the application they don't work as the sources for them are not available.

**To Reproduce**

Build an application that uses Montserrat 8 or 10px fonts.

**Expected behavior**

Application can use these fonts.

**Screenshots**

N/A

**Additional context**

N/A

**Comment by kisvegabor** [comment]
Hi,

Thanks for opening this issue.

I've just fixed it.
