### ISSUE TITLE
there are display issue for calendar

### ISSUE THREAD

**Issue by ZhaoQiang-b45475** [lvgl/lvgl#1850]
Hi,
I create a calendar with 200x180, it is ok when I run on screen with 480x272.
However, if I change LV_HOR_RES_MAX to 640 and LV_VER_RES_MAX to 480,
there will be display issue (as attached picture), is it a bug? or how could I get the relationship between LV_HOR_RES_MAX /LV_VER_RES_MAX and smallest size for calendar which has no display issue when I set the font size to montserret_12.
<img width="243" alt="Capture" src="https://user-images.githubusercontent.com/22284222/95962961-a63ef280-0e39-11eb-9e74-f8fd373d03ba.PNG">

**Comment by embeddedt** [comment]
It's happening because the material theme changes padding based on display size. Search for `lv_disp_get_size_category` in `lv_theme_material.c`.

Looks like a bug.

**Comment by ZhaoQiang-b45475** [comment]
Will it be fixed soon?

**Comment by kisvegabor** [comment]
@ZhaoQiang-b45475 
AS @embeddedt the material theme tries to set the values based on the display size and resolution. 
Be sure to set LV_DPI correctly as well.

**Comment by embeddedt** [comment]
While playing around with a custom theme I also ran into this problem. I decided to just disable line wrapping on day numbers and names, since it is broken anyways.

For future readers using newer versions: if your numbers look too squished you need to use a smaller font, increase the padding, or change the DPI.

**Comment by kisvegabor** [comment]
>  I decided to just disable line wrapping on day numbers and names, since it is broken anyways.

Good idea!
