### ISSUE TITLE
documentation error for lvgl/arduino debug

### ISSUE THREAD

**Issue by rpcy** [lvgl/lvgl#1859]
> # Important: issues that don't use this template will be ignored/closed.

**Describe the bug**

https://github.com/lvgl/lv_arduino section on Debugging says to edit lv_conf.h and change the log settings. The first line is a comment. The 2nd line says "#define USE_LV_LOG  1", and the 3rd line says "#if LV_USE_LOG". Surely that 3rd line should say "USE_LV_LOG" not "LV_USE_LOG"?

**To Reproduce**

**Expected behavior**

I think this is a documentation-only bug. I'm new here, if this is the wrong place to bring this up I hope somebody clues me in.

**Screenshots**

**Additional context**

**Comment by kisvegabor** [comment]
Updated, thank you!
See: https://github.com/lvgl/lv_arduino/commit/7bf3af5272febc3346529c77888afdff734026a5
