### ISSUE TITLE
How to use it with Arduino IDE?

### ISSUE THREAD

**Issue by albertomercurio** [lvgl/lvgl#1861]
Hello,
I installed this library from Arduino IDE, like the deprecated version lv_arduino. There are not examples, but i can see a .ino file in the directories of the library called LVGL_Arduino.ino. But when i try to compile it, it returns
```
In file included from /home/alberto/Arduino/libraries/lvgl/src/../src/lv_misc/lv_log.h:16:0,
                 from /home/alberto/Arduino/libraries/lvgl/src/../lvgl.h:26,
                 from /home/alberto/Arduino/libraries/lvgl/src/lvgl.h:17,
                 from /home/alberto/Arduino/libraries/lvgl/examples/LVGL_Arduino/LVGL_Arduino.ino:1:
/home/alberto/Arduino/libraries/lvgl/src/../src/lv_misc/../lv_conf_internal.h:24:101: fatal error: ../../lv_conf.h: No such file or directory
compilation terminated.
exit status 1
Errore durante la compilazione per la scheda ESP32 Dev Module.
```

**Comment by kisvegabor** [comment]
Hi,

Have you followed the guide here?
https://docs.lvgl.io/latest/en/html/get-started/arduino.html#configure-lvgl

**Comment by albertomercurio** [comment]
> Hi,
> 
> Have you followed the guide here?
> https://docs.lvgl.io/latest/en/html/get-started/arduino.html#configure-lvgl

Yes.

**Comment by kisvegabor** [comment]
And do you really have `lv_conf.h` next to the lvgl folder in the Arduino's library folder?

**Comment by albertomercurio** [comment]
Yes.

**Comment by kisvegabor** [comment]
Please send [tree view](https://www.codeproject.com/KB/tree/FileSystemTreeView/screenshot.gif) of the folders where lv_conf.h is located. 

And try to add this to lv_conf.h: `#error "seen by the compiler"`. Do you the error on compile?

**Comment by benjaminSchilling33** [comment]
@kisvegabor I have the same problem.
I added the #error directive but it is not shown in the compilation output.

-------------------------

Update: misunderstood `as lv_conf.h next to the lvgl folder.`, I copied it inside the lvgl directory, while it has to be copied OUTSIDE of the lvgl directory INSIDE the libraries directory.

@kisvegabor I created a pull reques to make it more clear, see https://github.com/lvgl/docs/pull/170

I think this can be closed now.

**Comment by kisvegabor** [comment]
Thanks for the update!

**Comment by daxliniere** [comment]
> Hi,
> 
> Have you followed the guide here? https://docs.lvgl.io/latest/en/html/get-started/arduino.html#configure-lvgl

This link goes to the docs for 7.11.0-dev instead of the actual latest.
Also, there are no instructions for v8.0 on how to configure demos, yet I get compilation error: **lv_demo_conf.h: No such file or directory. compilation terminated.**

LVGL looks great and I can't wait to start using it! 😃

**Comment by kisvegabor** [comment]
The URL has been changed meanwhile, see the latest version here: https://docs.lvgl.io/master/get-started/arduino.html

`lv_demos` should work the same way as lvgl. Have you copied `lv_demo_conf.h` next to the `lv_demos` folder?

**Comment by Hrishikesh46779** [comment]
I have added lv_config.h in arduio directory but still not working.

c:\users\hrishikesh\documents\arduino\libraries\lvgl\src\lv_conf_internal.h:41:100: fatal error: ../../lv_conf.h: No such file or directory

**Comment by Hrishikesh46779** [comment]
C:\Users\Hrishikesh\Documents\Arduino\libraries\lv_examples\src\lv_demo_widgets\lv_demo_widgets.c:1225:17: error: too few arguments to function 'lv_calendar_header_dropdown_create'
How to fix?

**Comment by kisvegabor** [comment]
Are you sure you use the latest lvgl with the latest lv_demos. There was a change in the calendar widget and it seems the 2 repos are not in sync.

**Comment by Hrishikesh46779** [comment]
I am installing lvgl and lv_examples libraries from arduino IDE.
![image](https://user-images.githubusercontent.com/46864647/144167815-b47cfdc0-af71-4561-aa1d-14374a5e11ee.png)

**Comment by Hrishikesh46779** [comment]
Now after downloading the both libraries from github i got another error-
undefined reference to `lv_demo_widgets'

**Comment by kisvegabor** [comment]
You should use lvgl 8.1.0 too.
