### ISSUE TITLE
How to remove the outline of the check box？

### ISSUE THREAD

**Issue by zq190kg** [lvgl/lvgl#1862]
![checkbox](https://user-images.githubusercontent.com/53965706/96986560-68864c00-1554-11eb-986b-fe4c721f761f.jpg)
hi，How to remove the outline of the check box？tks

**Comment by embeddedt** [comment]
I can't confirm this right now but this is how I would do it off the top of my head:

`lv_style_set_outline_opa(&style, LV_STATE_FOCUSED, LV_OPA_TRANSP);`

You would then need to add that style to the checkbox.

**Comment by zq190kg** [comment]
tks,i use lv_obj_set_style_local_outline_width  done it,Thank you。

**Comment by kisvegabor** [comment]
You can also use the `LV_THEME_MATERIAL_FLAG_NO_FOCUS` flag in `LV_THEME_DEFAULT_FLAG` in `lv_conf.h`.
