### ISSUE TITLE
Infinite loop in imgbtn

### ISSUE THREAD

**Issue by vinaychandra** [lvgl/lvgl#1867]
> # Important: issues that don't use this template will be ignored/closed.

**Describe the bug**

The following is the snippet in `lv_imgbtn.c`
```
void lv_imgbtn_toggle(lv_obj_t * imgbtn)
{
    lv_imgbtn_toggle(imgbtn);
    refr_img(imgbtn);
}
```
Doesn't calling this function result in an infinite loop?
Complains the same when using clang as the compiler

```
../src/lv_widgets/lv_imgbtn.c:189:1: warning: all paths through this function will call itself [-Winfinite-recursion]
{
```

**Expected behavior**

No infinite loop

**Comment by kisvegabor** [comment]
Thank you, I've just fixed it.
