### ISSUE TITLE
Problem with lv_img_set_offset_y in ver 7

### ISSUE THREAD

**Issue by ali-rostami** [lvgl/lvgl#1871]
**Describe the bug**

This issue is opened as a place to continue [this discussion](https://forum.lvgl.io/t/problem-with-lv-img-set-offset-y-in-ver-7/3330) in the forum.
This is the description:
In ver 6, I had no problem with lv_img_set_offset_y, but in ver 7, it seems that something has changed about it.
consider this picture as the source of the img object.
![image](https://user-images.githubusercontent.com/9710249/97269026-18540600-1842-11eb-99a0-9a2c336e2fda.png)

offset
Each part has a size of 170 * 50.
In ver 6, if I wanted to display part 6, I had to write sth like this:

lv_img_set_offset_x(img_power_status, 170);
lv_img_set_offset_y(img_power_status, 50);
But now this doesn’t work and instead shows part 6. and seems if I want to show it correctly I should write it like this:

lv_img_set_offset_x(img_power_status, 100);
lv_img_set_offset_y(img_power_status, -50);
Is it a bug or something else?

Is my expectation wrong?-As I said in ver 6 it worked like this expectation-
So @kisvegabor you wrote these lines:
```
lv_img_set_offset_x(img, 170);
lv_img_set_offset_y(img, 50);
```
 and saw the number 6 rectangle?

**Comment by kisvegabor** [comment]
Hi Ali,

In v7 it works well with this (shows 6):
```c
  LV_IMG_DECLARE(a);
  lv_obj_t * img = lv_img_create(lv_scr_act(), NULL);
  lv_img_set_src(img, &a);
  lv_obj_set_size(img, 170, 50);
  lv_img_set_offset_x(img, -170); //Make the image start at -170, so at 0 the 2nd column will start 
  lv_img_set_offset_y(img, -50);  //Make the image start at -5, so at 0 the 2nd row will start
```

This part has changed a little since v6 so some incompatibility might happen.

**Comment by ali-rostami** [comment]
Common😎, that's what I'm trying to tell you.
In ver 6 we should do this:
```
  lv_img_set_offset_x(img, 170); 
  lv_img_set_offset_y(img, 50); 
```
Right? 
If yes, I didn't see anywhere refer to this.
Anyway, it seems O.K and I think we can close the comment If you say.

**Comment by kisvegabor** [comment]
> Commonsunglasses, that's what I'm trying to tell you.

I see, but honestly don't know without immersing in how it worked in v6 :smile: 

It looks consistent in v7 with the negative coordinates. :slightly_smiling_face: 

> If yes, I didn't see anywhere refer to this.

Actually, I didn't know it's different hence it's not noted in the migration notes.
When v8 is released testing will have high priority so we will detect similar changes automatically.
