### ISSUE TITLE
Deleting objects in group can lead to crash

### ISSUE THREAD

**Issue by embeddedt** [lvgl/lvgl#1877]
@kisvegabor 

Relaying this from the forum as I know you've mentioned you check GitHub more frequently.

https://forum.lvgl.io/t/deleting-hidden-subobjs-in-groups-may-lead-to-crash/3590

**Comment by kisvegabor** [comment]
Thanks, I've fixed it here:
 https://github.com/lvgl/lvgl/commit/6d92d084f78600885cf478a84b91fcc142944526
