### ISSUE TITLE
checkbox has position issue

### ISSUE THREAD

**Issue by ZhaoQiang-b45475** [lvgl/lvgl#1879]
Hi, 
I create a checkbox and set its position with (0, 0), using font with lv_font_montserrat_48, then the widget is beyond the screen. please refer my code and capture as below:

        ui->screen = lv_disp_get_scr_act(NULL);
	ui->screen_cb0 = lv_checkbox_create(ui->screen, NULL);
	lv_checkbox_set_text(ui->screen_cb0, "checkbox");
	lv_obj_set_pos(ui->screen_cb0, 0, 0);
	lv_obj_set_style_local_text_font(ui->screen_cb0, LV_CHECKBOX_PART_BG, LV_STATE_DEFAULT, &lv_font_montserrat_48);

<img width="259" alt="Capture" src="https://user-images.githubusercontent.com/22284222/97964759-3c8c8580-1df4-11eb-8508-ac878e826fb7.PNG">

**Comment by upbeat27** [comment]
Did you try setting the font before setting the position?

**Comment by ZhaoQiang-b45475** [comment]
Hi, 
I try setting position after font, it works, thanks!

**Comment by kisvegabor** [comment]
Just a quick explanation of why it happens: when you change the font, the height of the checkbox is expanded symmetrically to both directions.

As it's normal and the proposed workaround should work, so I close this issue.
