### ISSUE TITLE
Dark bar for indicator when tabview location is set to LV_TABVIEW_TAB_POS_BOTTOM

### ISSUE THREAD

**Issue by acumartini** [lvgl/lvgl#1882]
As per @embeddedt 's suggestion I am moving this forum post to an Issue: https://forum.lvgl.io/t/dark-bar-for-indicator-when-tabview-location-is-set-to-lv-tabview-tab-pos-bottom/3613/4

**Describe the bug**

I really like the dark bar at the bottom of the tabview that holds the sliding tab indicator when the location is set to LV_TABVIEW_TAB_POS_TOP. It would be nice to have duplicate behavior for LV_TABVIEW_TAB_POS_BOTTOM. In fact I think I see the dark bar at the bottom fo the tabview when in the bottom position and it appears to be pushing the tabview up by roughly 4 pixels, so this might be considered a BUG report.

**To Reproduce**

```
lv_obj_t *tv = lv_tabview_create(pg, NULL);
lv_tabview_set_btns_pos(tv, LV_TABVIEW_TAB_POS_BOTTOM);

lv_obt_t *tb = lv_tabview_add_tab(tv, "TEST TAB");
```

**Expected behavior**

Rendering and stylization of tabview in all position should be the same with respect to the dark indicator background coloring and location. In addition, respective tabview dimensions should be the same for TOP and BOTTOM position in terms of total “height” of the rendered widget.

**Screenshots**

![IMG_20201103_075536](https://user-images.githubusercontent.com/2327751/98275956-1f69cb00-1f4a-11eb-987e-821d8ff08d3f.jpg)

**Comment by kisvegabor** [comment]
Hi,

Actually, it's a bottom border on tab buttons background. It really looks odd when the buttons are on the bottom. :slightly_frowning_face: 

You can get rid of it with 
`lv_obj_set_style_local_border_width(tabview, LV_TABVIEW_PART_TAB_BG, LV_STATE_DEFAULT, 0);`

**Comment by acumartini** [comment]
I mean we prob can move the overlaying tab_view obj down when in `LV_TABVIEW_TAB_POS_BOTTOM` mode to make it symmetrical with the top view?

I'm sure you all have bigger Issues to deal with. I pick away at this.

**Comment by embeddedt** [comment]
We'd need to dynamically adjust the object's style to permanently fix it; the border side would need to be adjusted whenever `lv_tabview_set_btns_pos` is called.

I think this would fix the problem for you (you would probably want to remove the line @kisvegabor suggested otherwise the border would still be invisible):

```c
lv_obj_set_style_local_border_side(tabview, LV_TABVIEW_PART_TAB_BG, LV_STATE_DEFAULT, LV_BORDER_SIDE_TOP);
```

**Comment by acumartini** [comment]
@embeddedt Confirmed definitely fixed the styling. Thanks!

**Comment by kisvegabor** [comment]
Finally, I fixed it by removing the border from the theme.
