### ISSUE TITLE
Why does 'No data' appear when loading images?

### ISSUE THREAD

**Issue by chcmq** [lvgl/lvgl#1885]
Tile view (lv_tileview)

Why does 'No data' appear when loading images?

![选区_022](https://user-images.githubusercontent.com/30547484/98380956-37456a00-2084-11eb-8a1c-f209bcf7deb9.png)

Ask for help, thank you

**Comment by kisvegabor** [comment]
Probably you forgot to set the `src` of the image.

We use GitHub Issues for development-related discussions.

Please ask your question in the [Forum](https://forum.lvgl.io) to make it visible for a larger community. You can simply log in with your GitHub account.
