### ISSUE TITLE
ButtonMatrix Bug with change number of buttons

### ISSUE THREAD

**Issue by lilengqiang** [lvgl/lvgl#1889]
**Describe the bug**
When I change the number of buttons in textArea, the reduced buttons will not be refreshed

**To Reproduce**

    static char mapbuf[6][10];
    static char *map[6];

    lv_obj_t *btm = lv_btnmatrix_create(lv_scr_act(), NULL);

    int i = 0;
    for(i = 0 ; i<5 ; i++){
        mapbuf[i][0] = 'a';
        mapbuf[i][1] = '\0';
        map[i] = mapbuf[i];
    }
    mapbuf[i][0] = '\0';
    map[i] = mapbuf[i];

    lv_btnmatrix_set_map(btm, (const char**)map);

    for(i = 0 ; i<2 ; i++){
        mapbuf[i][0] = '1';
        mapbuf[i][1] = '\0';
        map[i] = mapbuf[i];
    }
    mapbuf[i][0] = '\0';
    map[i] = mapbuf[i];

    map[i+1] = "";

    lv_btnmatrix_set_map(btm, (const char**)map);

**Expected behavior**

![1604885802(1)](https://user-images.githubusercontent.com/52372001/98491230-1f7e0980-226f-11eb-81f4-00ca7dd115c7.png)

**Screenshots**
![1604885870(1)](https://user-images.githubusercontent.com/52372001/98491269-44727c80-226f-11eb-99c4-705dc7812dcc.png)

**Additional context**

**Comment by kisvegabor** [comment]
Hi,

I've just fixed it in master.
