### ISSUE TITLE
add LV_EVENT_COORD_CHG event.

### ISSUE THREAD

**Issue by incity** [lvgl/lvgl#1897]
add a LV_EVENT_COORD_CHG event to help applications to listen the object's position and size change event.
 in my requirement, i need to show the position of a draggable object on a textarea.

**Comment by embeddedt** [comment]
You can use a custom signal handler for this.

https://github.com/lvgl/lvgl/blob/43771fa2f71d5323ef9dffc1ff0aee326d59f5ce/src/lv_core/lv_obj.c#L810-L814

**Comment by incity** [comment]
but if so i need to save old signal handler for all objects(different kind of objects), that means each object needs one function pointer to save the old handler.

as follow:

```
class LvObject {
public:
    LvObject() {
           //set signal handler here, need to save old signal handler
           ....
          //set event handler here
            lv_obj_set_event_cb(mLvObj, onEvent);
            lv_obj_set_user_data(mLvObj, this);
    }

    virtual void onSizeChanged(int w, int h, int oldw, int oldh) {
    }

    virtual void onClick() {
    }

    static void onEvent(lv_obj_t* obj, lv_event_t event) {
         // here will call onClick
    }

    static void onSignal(lv_obj_t* obj, lv_event_t event) {
         // here will call onSizeChanged

        // call old signal handler
    }

private:
    lv_obj_t* mLvObj;
    lv_signal_cb_t mOldSignalHandler; // that is not so good
};

```

and as i understand it, signal handler is used by widget itself, and event handler is used by widget's users. right?

**Comment by incity** [comment]
@kisvegabor please think about this~

**Comment by kisvegabor** [comment]
Hi,

I was also thinking about it but found that it's too low level for the user. As a reference I  checked Observers in JS:
- [IntersectionObserver.observe()](https://developer.mozilla.org/en-US/docs/Web/API/MutationObserver/observe)
- [MutationObserver.observe()](https://developer.mozilla.org/en-US/docs/Web/API/IntersectionObserver/observe)
- [ResizeObserver.observe()](https://developer.mozilla.org/en-US/docs/Web/API/ResizeObserver/observe)

**Comment by incity** [comment]
yes, but it's more better to give the users an ability(interface) to custom it.

**Comment by incity** [comment]
![image](https://user-images.githubusercontent.com/7846605/99506714-6b425880-29bd-11eb-8e91-f03ed0483f9e.png)
https://android.googlesource.com/platform/frameworks/base/+/a175a5b/core/java/android/view/View.java

**Comment by kisvegabor** [comment]
I'm afraid providing access to it will let the user to make infinite loops and performance costy stuff.

I haven't found a similar event in the link either.

**Comment by embeddedt** [comment]
+1, I think it's better to keep it hidden; there are ways of solving this without needing an event.

**Comment by incity** [comment]
in Android, users can listen the size changed event, in windows, there is also an WM_SIZE message.  
@embeddedt  yes, i know, i can solve it by override the signal handler and save the old one, but it seems sloppy.

**Comment by embeddedt** [comment]
It's sloppy, yes, but exposing an event handler will cause other harder-to-diagnose problems when users start overflowing their stack because of recursive coordinate changes. At least with the signal handler you have to think about the architecture more beforehand.

**Comment by incity** [comment]
change the size in the size changed handler will cause infinite loops, maybe user should know that, It's just a simple logic.

**Comment by kisvegabor** [comment]
My experience is that if something can cause issues it will cause issues. We need to keep in mind there is a lot of novice user of LVGL who has problems even with the basics of programming. By exposing such low-level control we will end up getting a lot of issues about it. 

I'm ok to expose something coordinate change-like but it should be something directly good for.  As the observers [here](https://github.com/lvgl/lvgl/issues/1897#issuecomment-729524641).

**Comment by embeddedt** [comment]
The only other option here is to not allow the event to be recursive, i.e. if the size changes inside the event handler, it will not be called again. This adds a code size penalty for tracking event recursion, however.

**Comment by kisvegabor** [comment]
I'm still in favor of adding dedicated "observers" instead of exposing low-level things (if really needed). Besides being error-prone it's still difficult to use.

I suggest waiting if other requests arrive on this topic. And if we will see how/what to develop.

**Comment by incity** [comment]
position changed event and size changed event is very common to application(users).

**Comment by embeddedt** [comment]
Let's close it for now and see if any new requests come in for this feature.
