### ISSUE TITLE
is lv_apps adapted to lvgl 7.6.1?

### ISSUE THREAD

**Issue by eleree** [lvgl/lvgl#1898]
[lv_apps]((https://github.com/lvgl/lv_apps/) seems to be only supported in lvgl 6, has it been adapted to lvgl 7？ 

And if there an example to show how to modify the lv_apps on lvgl 7?

Thansk!

**Comment by embeddedt** [comment]
I think `lv_apps` is deprecated now but the `v7-test` branch may have a working version for v7.

**Comment by kisvegabor** [comment]
Yes, it's really deprecated.  Most of the "apps" are added the `lv_examples`.
Do you miss something in particular?

**Comment by kisvegabor** [comment]
As it's not planned to port lv_apps to the new version I close this issue.
