### ISSUE TITLE
How to change tabel cell style

### ISSUE THREAD

**Issue by lxa520** [lvgl/lvgl#1899]
# All enhancement requests or questions should be directed to the Forum.

We use GitHub issues for development related discussions.
Please use the [forum](https://forum.littlevgl.com/) to ask questions.

**Comment by embeddedt** [comment]
Change the style of [`LV_TABLE_PART_CELLx`](https://docs.lvgl.io/latest/en/html/widgets/table.html#parts-and-styles) (where x is the cell type number to change).

----------------------
We use GitHub issues for development related discussions.
Please use the [forum](https://forum.littlevgl.com/) to ask questions.

It's possible to sign in to the forum with your GitHub account... you don't need to make a separate account.
