### ISSUE TITLE
Recolor on symbol and array in text

### ISSUE THREAD

**Issue by Moo2017** [lvgl/lvgl#190]
Hi All,
Is that possible to set recolor mode for symbol and  raw character array  in a label? I think this works only in text. It would be useful if we have this option otherwise for change the color always a new style has to be created.

**Comment by kisvegabor** [comment]
Hi,
I don't clearly understand what your goal is. Can you show a code example?

**Comment by Moo2017** [comment]
According to the document : It is possible to enable re-color parts of the text. For example: "Write a #ff0000 red# word". This feature can be enabled individually for each label by lv_label_set_recolor() function.
I was wondering if label's text is an array it's not possible to recolor using this feature?

**Comment by kisvegabor** [comment]
It worked for me:
```c
    const char buf[] = {"Write a #ff0000 red# word"};

    lv_obj_t * label = lv_label_create(lv_scr_act(), NULL);
    lv_label_set_recolor(label, true);
    lv_label_set_array_text(label, buf, strlen(buf));
```
![image](https://user-images.githubusercontent.com/7599318/38546857-02a2d416-3cae-11e8-8861-1ce37cab2723.png)

**Comment by Moo2017** [comment]
Thanks, sounds good . But if I wanted to display an array that is set somewhere else I have to edit the array and add the color command .

**Comment by kisvegabor** [comment]
Yes, you have to "insert" the command part manually an you also have to call `lv_label_set_array_text()` to refresh the size of the label.

**Comment by Moo2017** [comment]
How about symbols? there is no way to use recolor feature for them right?

**Comment by kisvegabor** [comment]
It is also valid:
```c
    const char buf[] = {"Write a #ff0000 "SYMBOL_OK"# word"};

    lv_obj_t * label = lv_label_create(lv_scr_act(), NULL);
    lv_label_set_recolor(label, true);
    lv_label_set_array_text(label, buf, strlen(buf));
```

![image](https://user-images.githubusercontent.com/7599318/38601309-5e7f0aca-3d67-11e8-8466-54e8e1e9f522.png)

**Comment by Moo2017** [comment]
@kisvegabor Thanks it worked fine.
