### ISSUE TITLE
how to switch other oject without tab key

### ISSUE THREAD

**Issue by Layty** [lvgl/lvgl#1901]
In the lastest example lv_demo_keypad_encoder, if I have no tab key, how can I switch  from  button to lists for example?
My project only have  up/down/left/right/enter/esc.

**Comment by Layty** [comment]
when I in a lists ,I think I can use esc+donw to do change to focse other object , so how can I make it possible?

**Comment by kisvegabor** [comment]
We use GitHub Issues for development-related discussions.

Please ask your question in the [Forum](https://forum.lvgl.io) to make it visible for a larger community. You can simply log in with your GitHub account.
