### ISSUE TITLE
How to get property value of style

### ISSUE THREAD

**Issue by lxa520** [lvgl/lvgl#1903]
use lv_obj_add_style function, add style to object; then how to get the property value of style;
lv_style_t* only contain  map  and sentinel

**Comment by kisvegabor** [comment]
See here: https://docs.lvgl.io/latest/en/html/overview/style.html#initialize-styles-and-set-get-properties

Unfortunately, it's not that the user-friendly. 

---

We use GitHub Issues for development-related discussions.

Please ask your question in the [Forum](https://forum.lvgl.io) to make it visible for a larger community. You can simply log in with your GitHub account.
