### ISSUE TITLE
Key input mechanism problem

### ISSUE THREAD

**Issue by zdp1994** [lvgl/lvgl#1908]
Now there are only three buttons on my device, but I found that the obj control switch of lvgl, and the different options of the same control (such as list) are different buttons

**Comment by kisvegabor** [comment]
Take a look at the encoder input type. https://docs.lvgl.io/latest/en/html/porting/indev.html#encoder

---

We use GitHub Issues for development-related discussions.

Please ask your question in the [Forum](https://forum.lvgl.io) to make it visible for a larger community. You can simply log in with your GitHub account.
