### ISSUE TITLE
Is that possible to set screen size?

### ISSUE THREAD

**Issue by Moo2017** [lvgl/lvgl#191]
I have written this code:

  lv_obj_t * InboxScreen=lv_obj_create(NULL, NULL);
      lv_obj_set_size(InboxScreen,LV_HOR_RES,LV_VER_RES-30);
        lv_obj_set_pos(InboxScreen,0,LV_VER_RES-30);
        lv_scr_load(InboxScreen);
  
but I've got an error in run time in setting object position.( seems that lv_obj_set_pos doesn't work pro parley, this issue title should be "set screen position" not "set screen size" )

**Comment by kisvegabor** [comment]
Hi,
You can't modify the screen size and position. But you can create an lv_obj on a screen and use it as a container.

**Comment by Moo2017** [comment]
Ok thank you Kisvegbor

**Comment by kisvegabor** [comment]
Your welcome!
