### ISSUE TITLE
Arduino Due support.

### ISSUE THREAD

**Issue by EliasA97** [lvgl/lvgl#1910]
Hi, the arduino due doesn't support the TFT_eSPI library. Is it possible to use the lvgl without the TFT_eSPI?

**Comment by kisvegabor** [comment]
It supports "any" library.  All you need to do is writing your `flush` function as described here: https://docs.lvgl.io/latest/en/html/porting/display.html#display-driver

In Arduino libs usually, `drawBitmap` or a similar function needs to be used. 

---
We use GitHub Issues for development-related discussions.

Please ask your question in the [Forum](https://forum.lvgl.io) to make it visible for a larger community. You can simply log in with your GitHub account.
