### ISSUE TITLE
 Boot animation

### ISSUE THREAD

**Issue by burtyu8756** [lvgl/lvgl#1912]
> # Important: issues that don't use this template will be ignored/closed.

**Describe the bug**

Dear author, is there a boot animation demo here?

**To Reproduce**

Please provide a small, independent code sample that can be used to reproduce the issue. Ideally this should work in the PC simulator unless the problem is specific to one platform.

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by embeddedt** [comment]
Not at the moment, however, you could make one easily by creating a spinner/label/image on the default screen, and loading a new screen once boot is complete.

----------------------
We use GitHub issues for development related discussions.
Please use the [forum](https://forum.littlevgl.com/) to ask questions.

It's possible to sign in to the forum with your GitHub account... you don't need to make a separate account.
