### ISSUE TITLE
Do we have APIs to stop and restart an animation?

### ISSUE THREAD

**Issue by ZhaoQiang-b45475** [lvgl/lvgl#1916]
Do we have APIs to stop and restart an animation? I didn't find under lv_anim.c.

**Comment by embeddedt** [comment]
You can [delete the animation](https://docs.lvgl.io/latest/en/html/overview/animation.html#delete-animations) and recreate it. There is no facility for pausing an animation.

----------------------
We use GitHub issues for development related discussions.
Please use the [forum](https://forum.littlevgl.com/) to ask questions.

It's possible to sign in to the forum with your GitHub account... you don't need to make a separate account.
