### ISSUE TITLE
dropdown list doesn't process arabic letter

### ISSUE THREAD

**Issue by ashrafkamel5** [lvgl/lvgl#1920]
## description
 the dropdown lists don't process Arabic letters.

```c
static char dd_months[] = "يناير\n"
"فبراير\n"
"مارس\n"
"أبريل\n"
"مايو\n"
"يونيو\n"
"يوليو\n"
"أغسطس\n"
"سبتمبر\n"
"أكتوبر\n"
"نوفمبر\n"
"ديسمبر";

lv_obj_t* ddlist_start_month = lv_dropdown_create(NULL, NULL);
lv_dropdown_set_options(ddlist_start_month, dd_months);

```
## output
![image](https://user-images.githubusercontent.com/38524812/99894783-34a36100-2c8f-11eb-9165-e581b1858266.png)

## solve
```c
static char dd_months[] = "يناير\n"
"فبراير\n"
"مارس\n"
"أبريل\n"
"مايو\n"
"يونيو\n"
"يوليو\n"
"أغسطس\n"
"سبتمبر\n"
"أكتوبر\n"
"نوفمبر\n"
"ديسمبر";

lv_obj_t* ddlist_start_month = lv_dropdown_create(NULL, NULL);
_lv_txt_ap_proc(dd_months, dd_months);
lv_dropdown_set_options(ddlist_start_month, dd_months);

```
## output 
![image](https://user-images.githubusercontent.com/38524812/99894906-8a780900-2c8f-11eb-9f44-4a9647b19ce5.png)

## same with the container name

![image](https://user-images.githubusercontent.com/38524812/99895150-273aa680-2c90-11eb-8aed-553aede1d9bb.png)

```c   
 lv_obj_set_style_local_value_str(h, LV_CONT_PART_MAIN, LV_STATE_DEFAULT, "الأساسيات");

```
## and trying This doesn't work
```c   
char ctx_text[40];
    _lv_txt_ap_proc("الأساسيات",ctx_text);

    lv_obj_set_style_local_value_str(container, LV_CONT_PART_MAIN, LV_STATE_DEFAULT, ctx_text);

```

## outputs garbage 
![image](https://user-images.githubusercontent.com/38524812/99895296-8e585b00-2c90-11eb-809d-1ff783a1b2ad.png)

**Comment by kisvegabor** [comment]
Hi,

I've fixed both in `master`. Please verify if they work correctly.

**Comment by ashrafkamel5** [comment]
![image](https://user-images.githubusercontent.com/38524812/99964615-3e66ba80-2d9c-11eb-8aa2-276077fcf6ee.png)

apparently that the container name is working,
but the whole example crashes now, :\ 
![image](https://user-images.githubusercontent.com/38524812/99964738-73730d00-2d9c-11eb-977b-338c7badccf7.png)

**Comment by ashrafkamel5** [comment]
it was working fine, just before replacing the lvgl folder.
that is quite an error for such a small fix.

**Comment by kisvegabor** [comment]
Can you see in Debug where it halts?

**Comment by ashrafkamel5** [comment]
![image](https://user-images.githubusercontent.com/38524812/100006801-bef4dd80-2dd3-11eb-93c7-e43da1345635.png)

the error was presented in codeblocks simulation.
I saved my work at VS and did the changes and it works fine there.
many thanks,
now it is time for me to add an Arabic keyboard.
can you help, where to start or if there is something I should watch out for?

**Comment by kisvegabor** [comment]
Great! 
I don't know what are the requirements for an Arabic keyboard. Could you describe it in a new issue?
