### ISSUE TITLE
Timers (tasks) clenup

### ISSUE THREAD

**Issue by puzrin** [lvgl/lvgl#1925]
Ref: https://github.com/lvgl/lvgl/issues/1839#issuecomment-722990641

IMO current "tasks" move to strange direction:

- Those are not tasks, those are periodic timers. Naming is confusing.
- Priorities are not effective for real needs and create illusion of correctness.

What is suggested:

- Recommend users to use protothreads for advanced things.
  - May be worth create "our lib", because i could not find "ideal" one.
- Rename "tasks" to "timers" everywhere.
- Drop priorities.

Changes are trivial, but breaking. Worth to sync with other big changes (land to v8 or v9).

Priority - not critical.

**Comment by kisvegabor** [comment]
I definitely agree to simplify it. 
It's easy to do so it can even add it to v8. @embeddedt, do you agree?

**Comment by embeddedt** [comment]
:+1: Sounds good; I don't rely on priorities when I make use of tasks and I doubt most other users do.

**Comment by puzrin** [comment]
One more note. Point implicit in docs: timers should NOT run in MCU over-load mode. Such cases should be solved via protothreas (yield-ing) or preemptive RTOS.

PS. That's a reason why priorities are pointless for periodic timers.

**Comment by kisvegabor** [comment]
I've done the update in `dev`.

**Comment by puzrin** [comment]
IMO shorting timer to tmr is not needed here.

**Comment by kisvegabor** [comment]
I was also thinking about it and thought tmr is a very conventional abbreviation so it's fine to use.

**Comment by puzrin** [comment]
IMO:

- typing saving is about zero (not the same as background => bg)
- readability (for novices) not improved

**Comment by kisvegabor** [comment]
IMO tmr is even more commonly written than timer in the embedded world but I think both are acceptable.

**Comment by puzrin** [comment]
Always use full words in api if you can. Shorcuts are better for local variables.

**Comment by kisvegabor** [comment]
Okay, so 1-1 :D 

@embeddedt Please, help us to decide. :slightly_smiling_face:

**Comment by embeddedt** [comment]
I vote "timer". The savings are negligible and "timer" is more readable for newer users.

As @puzrin mentioned `tmr` would be more appropriate for and is frequently used as a local variable name, not as an API name.

**Comment by kisvegabor** [comment]
Alright, I renamed it to timer.

**Comment by puzrin** [comment]
LGTM.

`lv_timer_create` has `user_data`. Is it really need? Does anyone actively create/destroy temporary timers?

**Comment by kisvegabor** [comment]
`user_data` is needed by the MicroPython binding. Adding it to the `create` function is not mandatory but task/therad creates usually have something like a user data:
- https://man7.org/linux/man-pages/man3/pthread_create.3.html
- https://www.freertos.org/a00125.html

A practical use case:  count on the label with a timer and pass the label as `user_data`.

**Comment by puzrin** [comment]
ок.
