### ISSUE TITLE
check conditions 

### ISSUE THREAD

**Issue by maddin200** [lvgl/lvgl#1930]
/src/lv_draw/lv_draw_arc.c line 400

These are identical assignments:

   int32_t rx_corr;
    int32_t ry_corr;

    if(angle > 90 && angle < 270) rx_corr = 0;
    else  rx_corr = 0; // <-- identical 

    if(angle > 0 && angle < 180) ry_corr = 0;
    else  ry_corr = 0; // <-- identical

**Comment by kisvegabor** [comment]
Thank you, I've just fixed it.
