### ISSUE TITLE
use  lv_canvas_set_buffer  API to display image,image occur error

### ISSUE THREAD

**Issue by juice-man** [lvgl/lvgl#1932]
I create a loop task that repeat call lv_canvas_set_buffer API to display image 

but it can't show correct image that I expected
in function  "_lv_img_cache_open"  ,
 `if(cache[i].dec_dsc.src == src && cache[i].dec_dsc.color.full == color.full) match = true;` 
cache is easy to match , though I set different buffer by lv_canvas_set_buffer API.
followed is my code:

![image](https://user-images.githubusercontent.com/67527595/100221202-50d72480-2f53-11eb-8293-4f3b215801c8.png)

![image](https://user-images.githubusercontent.com/67527595/100219476-ffc63100-2f50-11eb-9f0f-890ba7bd31ea.png)

![image](https://user-images.githubusercontent.com/67527595/100221429-a3184580-2f53-11eb-8c31-162458ef5a3a.png)

result :

![8f35dc5139586388b82e5010085bedd6](https://user-images.githubusercontent.com/67527595/100223015-e7a4e080-2f55-11eb-8539-44f05f56bc5e.gif)

**Comment by embeddedt** [comment]
If the cache is the problem you can [clean it for your buffer](https://docs.lvgl.io/latest/en/html/overview/image.html#clean-the-cache).
