### ISSUE TITLE
Scrollbars may ignore parent visibility?

### ISSUE THREAD

**Issue by embeddedt** [lvgl/lvgl#1933]
**Describe the bug**

A list's scrollbar seems to be visible even if the list is partially transparent/covered by another object.

**To Reproduce**

Go to https://lvgl.github.io/lv_examples/lv_demo_printer/index.html (or run `lv_demo_printer`). Click on Print. Click on USB.

Note that the list's scrollbar appears instantly, long before the animation has finished.

**Expected behavior**

The scrollbar should fade/animate in like the rest of the list.

**Screenshots**

![Peek 2020-11-25 12-08](https://user-images.githubusercontent.com/42941056/100260031-f28c5080-2f16-11eb-8542-9d587d1a0591.gif)

**Additional context**

I haven't looked into the code yet, but maybe the scrollbar is not taking the list's opacity into account?

**Comment by kisvegabor** [comment]
Thanks, I've just pushed a fix.

**Comment by embeddedt** [comment]
Great!

This may be a similar issue: https://forum.lvgl.io/t/bug-of-table-click-to-change-style/3842
