### ISSUE TITLE
esp32 IRAM usage should be optional and not set in CMakeLists.txt

### ISSUE THREAD

**Issue by liebman** [lvgl/lvgl#1937]
**Describe the bug**

`IRAM` space on esp32 is limited and LVGL as component in esp-idf puts many drawing routines there due to this in `CMakeLists.txt`:
```
target_compile_definitions(${COMPONENT_LIB} PUBLIC "-DLV_ATTRIBUTE_FAST_MEM=IRAM_ATTR")
```

This should be an opting in `Kconfig`

**To Reproduce**

Have code that uses some of the `IRAM` space already, compile and:
```
/.platformio/packages/toolchain-xtensa32/bin/../lib/gcc/xtensa-esp32-elf/8.2.0/../../../../xtensa-esp32-elf/bin/ld: region `iram0_0_seg' overflowed by 11376 bytes
```

**Expected behavior**

LVGL use of IRAM for anything except functions expected to be called from interrupt services should be optional.

**Comment by C47D** [comment]
I can add an option to use IRAM or not later this week.

**Comment by C47D** [comment]
@liebman can you check if #1939 fixes the issue for you?

**Comment by liebman** [comment]
@C47D yes it does indeed! 💯
