### ISSUE TITLE
lv_label_set_static_text causes out of memory error

### ISSUE THREAD

**Issue by embeddedt** [lvgl/lvgl#1938]
**Describe the bug**

See forum post [here](https://forum.lvgl.io/t/out-of-memory-error-with-lv-label-set-text-static-introduced-in-7-7-2/3838?u=embeddedt). The breaking change is [here](https://github.com/lvgl/lvgl/commit/07c63b8ad31bad0bf4a98787270c68a12bf5569c#diff-a3f6759fc6603fffb6dcda48e9db36a48e55fa2886bf7d5faae5b9f339dec48c).

**Expected behavior**

`lv_label_set_static_text` should not be using the heap and causing out of memory issues.

**Comment by kisvegabor** [comment]
I've answered in the Forum.

**Comment by kisvegabor** [comment]
The issue came from the textarea was used in an unintended way. See the forum post.
