### ISSUE TITLE
Handle opacity animations for images.

### ISSUE THREAD

**Issue by SyedFaisalAli** [lvgl/lvgl#194]
Hi,

Thanks for your efforts on this well-organized framework. I needed to fade in an image and found out the opacity of the image styling wasn't being handled.

I've added this line of code to lv_style.c (style_animator)

```c
static void style_animator(lv_style_anim_dsc_t * dsc, int32_t val)
{
...
    STYLE_ATTR_ANIM(image.intense, val);
    STYLE_ATTR_ANIM(image.opa, val)
...
}
```

Once again, thanks!

**Comment by kisvegabor** [comment]
Hi,

Thank you for pointing this out, I fixed it in the `beta` branch!
