### ISSUE TITLE
Setting lv_textarea_set_pwd_mode to true does not update the textarea

### ISSUE THREAD

**Issue by fvanroie** [lvgl/lvgl#1942]
**Describe the bug**

I experience an issue when setting `lv_textarea_set_pwd_mode` to `true`. The displayed characters are not replaced by bullets right away. Instead, the bullets only appear when you enter or delete a character.

**Screenshots**

![67vmL4WOPV](https://user-images.githubusercontent.com/15969459/100528599-108bd680-31df-11eb-9180-d3350f2f2e87.gif)

In this example, the characters are not hiden until a character ( e.g. `g`) is entered.

**To Reproduce**

I have implemented the 'Password Peek' button like this:

```c
static void peek_password_cb(lv_obj_t * obj, lv_event_t event)
{
    if(event == LV_EVENT_VALUE_CHANGED) {
        bool stat=lv_btn_get_state(obj);
        lv_obj_set_style_local_value_str(obj, LV_BTN_PART_MAIN, LV_STATE_DEFAULT,
                                         stat ? LV_SYMBOL_EYE_OPEN : LV_SYMBOL_EYE_CLOSE);
        lv_textarea_set_pwd_mode(pwd_ta, !stat);
    }
}
```

**Expected behavior**

Immediately update the textarea with bullets when calling `lv_textarea_set_pwd_mode(pwd_ta,true);`

**Additional context**

I found that adding `pwd_char_hider(ta)` to the following code in [textarea.c](https://github.com/lvgl/lvgl/blob/b1a7dbadcdf34c5a26f90a02ae7103c3a68a5d34/src/lv_widgets/lv_textarea.c#L740) fixes the issue:

```c
    ext->pwd_mode = en == false ? 0 : 1;
    if(en)pwd_char_hider(ta);    // immediately hide the characters
```

Now I see the correct behaviour:
![TtXwp30PUq](https://user-images.githubusercontent.com/15969459/100528580-e3d7bf00-31de-11eb-8907-038d8f3ee7b3.gif)

**Comment by embeddedt** [comment]
I believe this is what [this block of code](https://github.com/lvgl/lvgl/blob/b1a7dbadcdf34c5a26f90a02ae7103c3a68a5d34/src/lv_widgets/lv_textarea.c#L719-L731) is supposed to be doing.

**Comment by fvanroie** [comment]
Oh I see. Now I understand the intent of that part. But it seems to have no effect.

So, I set a breakpoint and stepped through that part of the code.

`pwd_char_hider(ta);` is indeed being called, but it returns without effect because `ext->pwd_mode` has not been updated at that point in time. If I add the second call after the update, it updates the textarea.

**Comment by embeddedt** [comment]
Okay, so it looks like what we should be doing is storing the previous value of `ext->pwd_mode`, then changing it, and finally going through that if statement. Do you want to make a PR with that change or would you like me to just apply it to `master` (credit will be given of course)?

**Comment by fvanroie** [comment]
I can create a PR, but for a one-liner it might be a lot of overhead... Feel free to update, no worries about credits.

**Comment by embeddedt** [comment]
Alright; thank you very much for the report and the investigation!

**Comment by fvanroie** [comment]
Great, I just tested the commit and confirm it's working as expected!
