### ISSUE TITLE
'LV_ROLLER_MODE_INIFINITE' undeclared If i use benchmark example.

### ISSUE THREAD

**Issue by Trackhe** [lvgl/lvgl#1946]
**Describe the bug**

'LV_ROLLER_MODE_INIFINITE' undeclared If i use benchmark example.

**To Reproduce**

Build with Arduino IDE. And i have installed lvgl and lvgl_examples via library manager.

**Expected behavior**

working demo

**Comment by embeddedt** [comment]
Update lvgl to `master` or change `INIFINITE` to `INFINITE`. This is a bug which we unfortunately caught hours after the release instead of before. It will be fixed in the next release.
