### ISSUE TITLE
cant run any demo on arduino ide

### ISSUE THREAD

**Issue by Trackhe** [lvgl/lvgl#1947]
**Describe the bug**

I cant Build lvgl demo with Arduino IDE. I use the newest Master branches of lv_example and the lvgl master.
then i get the build error no found lvgl/lvgl.h so i replace all lvgl/lvgl.h to lvgl.h the error appears but i get the following errors. that is not a good experience. 

```
libraries/lv_examples/lv_demo_benchmark/lv_demo_benchmark.c.o:(.literal.txt_small_compr_cb+0x0): undefined reference to `lv_font_montserrat_12_compr_az'
libraries/lv_examples/lv_demo_benchmark/lv_demo_benchmark.c.o:(.literal.txt_medium_compr_cb+0x0): undefined reference to `lv_font_montserrat_16_compr_az'
libraries/lv_examples/lv_demo_benchmark/lv_demo_benchmark.c.o:(.literal.txt_large_compr_cb+0x0): undefined reference to `lv_font_montserrat_28_compr_az'
libraries/lv_examples/lv_demo_benchmark/lv_demo_benchmark.c.o:(.literal.img_rgb_cb+0x0): undefined reference to `img_cogwheel_rgb'
libraries/lv_examples/lv_demo_benchmark/lv_demo_benchmark.c.o:(.literal.img_argb_cb+0x0): undefined reference to `img_cogwheel_argb'
libraries/lv_examples/lv_demo_benchmark/lv_demo_benchmark.c.o:(.literal.img_ckey_cb+0x0): undefined reference to `img_cogwheel_chroma_keyed'
libraries/lv_examples/lv_demo_benchmark/lv_demo_benchmark.c.o:(.literal.img_index_cb+0x0): undefined reference to `img_cogwheel_indexed16'
libraries/lv_examples/lv_demo_benchmark/lv_demo_benchmark.c.o:(.literal.img_alpha_cb+0x0): undefined reference to `img_cogwheel_alpha16'
```
dosnt work too
```
sketch/testlvgl.ino.cpp.o:(.literal._Z5setupv+0x28): undefined reference to `lv_demo_widgets'
```

i use already the latest master from github rn

To Reproduce

Build with Arduino IDE. And i have installed lvgl and lvgl_examples via library manager. and overwrite it with the master version of github

Expected behavior

working demo

**Comment by kisvegabor** [comment]
Hi,

I've just pushed a fix to `lv_examples`.

**Comment by Trackhe** [comment]
working

**Comment by el-samiyel** [comment]
Same issue here as of today.. 

`LVGL_Arduino.ino:122: undefined reference to `lv_demo_widgets'
collect2.exe: error: ld returned 1 exit status
Error compiling for board Teensy 4.0.
`

**Comment by kisvegabor** [comment]
Recently we made some changes to make the examples and demos easier to use with Arduino. See the updated docs: https://docs.lvgl.io/master/get-started/arduino.html

**Comment by phamvant** [comment]
I got the same issue even though i did exaclty the same thing in the docs 
May PlatformIO cause the issue?

**Comment by el-samiyel** [comment]
Even with the updated documents, the errors I posted above still exists. I
can’t compile not a single example...

**Comment by kisvegabor** [comment]
Have you copied the `demo` folder to `src`?
If so please send a screenshot about the directory layout.

**Comment by phamvant** [comment]
> Have you copied the `demo` folder to `src`? If so please send a screenshot about the directory layout.

![image](https://user-images.githubusercontent.com/44409501/148745597-5bbb0473-9754-4ff1-b32d-d1346d6f9ed9.png)

I already did

**Comment by kisvegabor** [comment]
Ok, looks good. Have you enabled `LV_USE_DEMO_WIDGET`s in `lv_conf.h`?

**Comment by phamvant** [comment]
> Ok, looks good. Have you enabled `LV_USE_DEMO_WIDGET`s in `lv_conf.h`?

Thank you it compiled. But it doesn't show any thing
![20220110_202351](https://user-images.githubusercontent.com/44409501/148773371-9edd3cd6-3793-4fd5-baa4-20e3f43a3d2f.jpg)

I can only run simple label
![20220110_202242](https://user-images.githubusercontent.com/44409501/148773503-2b5f461d-a184-442b-b53f-0164dad0dbe6.jpg)

**Comment by phamvant** [comment]
I also can run benchmark

**Comment by kisvegabor** [comment]
Probably `LV_MEM_SIZE` is too small.

**Comment by phamvant** [comment]
> Probably `LV_MEM_SIZE` is too small.

Thank you so much you my hero

**Comment by kisvegabor** [comment]
Cool! It seems everything is working now. :slightly_smiling_face:

**Comment by C47D** [comment]
Documenting the fix in a troubleshooting section of the docs might be a good idea, what do you think?

**Comment by kisvegabor** [comment]
@C47D 
I think we should rather add some comments in `lv_conf.h` when the demos are enabled because the user surely goes there and will see the notes.

I don't know how many people reads it but we have an [FAQ](https://docs.lvgl.io/master/intro/index.html#faq) part in the docs. There we can mention that if LVGL doesn't what you can try. 

Probably we can make the FAQ page more visible by adding links to in in issue and topic templates.

What do you think?

**Comment by C47D** [comment]
Sounds like a good idea!

**Comment by kisvegabor** [comment]
All done. 
I added [this section](https://docs.lvgl.io/master/intro/index.html#lvgl-doesn-t-start-nothing-is-drawn-on-the-display-what-can-be-the-problem) to the docs, linked the FAQ in the bug report issue template on GitHub, in the how-to and get started forum category's topic templates, and added comment to lv_conf.h. (86525c35b)

**Comment by phamvant** [comment]
Hi, can i just ask one more question

I want to use Edgeline so i downgrade to lvgl v7. I tried to run demos in lv_examples lib but it seems like freeze at the first frame (I tried benchmark and there is no animation). What should i do?

**Comment by kisvegabor** [comment]
It's independent from EdgeLine, right?

Form this info I can't tell much. Please enable logging to see what happens.
