### ISSUE TITLE
misspelled constant name causing warning on lv_theme_material

### ISSUE THREAD

**Issue by KammutierSpule** [lvgl/lvgl#1955]
**Describe the bug**

There is a misspelled name at the following line:

```
lvgl/src/lv_themes/lv_theme_material.c:319:60: warning: result of comparison of constant 50 with expression of type 'lv_disp_size_t' is always true [-Wtautological-constant-out-of-range-compare]
                           lv_disp_get_size_category(NULL) <= LV_DISP_MEDIUM_LIMIT ? LV_DPX(20) : LV_DPX(40));
                           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ ^  ~~~~~~~~~~~~~~~~~~~~
```

**To Reproduce**

**Expected behavior**

`v_disp_get_size_category(NULL) <= LV_DISP_MEDIUM_LIMIT`

should be

`lv_disp_get_size_category(NULL) <= LV_DISP_SIZE_MEDIUM`

**Screenshots**

**Additional context**

**Comment by embeddedt** [comment]
Thanks; I've fixed it in `master`.
