### ISSUE TITLE
Is there a plan to support ambiq  Apollo4's GPU?

### ISSUE THREAD

**Issue by byjfire** [lvgl/lvgl#1957]
Is there a plan to support ambiq  Apollo4's GPU?

**Comment by kisvegabor** [comment]
Hi,


Honesty this MCU was new to me (so the GPU was not on the ROADMAP) but it looks like a great product. 

Is the Apollo MCUs considered popular in some filelds?

**Comment by kisvegabor** [comment]
We use GitHub Issues for development-related discussions.

Please open a future request topic in the [Forum](https://forum.lvgl.io/t/border-on-polygon/4310) to make it visible for a larger community. You can simply log in with your GitHub account.
