### ISSUE TITLE
letter ى Arabic processing error

### ISSUE THREAD

**Issue by ashrafkamel5** [lvgl/lvgl#1959]
**Describe the bug**
when Having an Arabic font that covers only the Arabic Presentation Forms-B.
the letter ى produces a missing glyph error.
**explain**
I found an error in the table of Unicode at `ap_chars_map[]` at ` lv_txt_ap.c `file
**fix**
at line 72
add this
`    {39, 0xFEF0, 0, 0, -1,  {1, 0}},   // ى`

I didn't want to delete the line existing at 72. because even if I think it is a mistake and the Unicode there is a duplicate of the one at 74
but yet. it doesn't harm being there. 
and maybe it works fine with other forms for Persian writing, I don't know we should ask Mr. Hamid who wrote the file.
so just adding that line fixes it.
**Screenshots**
look at the keyboard and the missing letter.
before
![image](https://user-images.githubusercontent.com/38524812/102262453-c82d2200-3f1b-11eb-98d0-e7bee935888f.png)

after
![image](https://user-images.githubusercontent.com/38524812/102262480-d5e2a780-3f1b-11eb-88ea-11b0e8dbd41f.png)

**Comment by kisvegabor** [comment]
Thank you!
@hamidrm, could you take a look at this?

**Comment by hamidrm** [comment]
@ashrafkamel5 You are right! It was my mistake. I thought the glyph of 0x6CC and 0x649 are the same (Although, In the Persian, they are the same!). According to https://en.wikipedia.org/wiki/Arabic_script_in_Unicode, you are right.
So, we should replace your change (`{39, 0xFEF0, 0, 0, -1, {1, 0}}, //ی`), with current line 72.
Thank you!
![Capture](https://user-images.githubusercontent.com/11191119/102641003-9fea3100-4170-11eb-8e2a-1fd34da79394.PNG)

**Comment by ashrafkamel5** [comment]
It's great adding full Arabic support to the library

@kisvegabor there is a small bug at dropdown widget
`lv_dropdown_add_option`
Doesn't process Arabic letters.
You need to add the `lv_txt_ap_proc` there

**Comment by ashrafkamel5** [comment]
@kisvegabor 
and the window's name also needs the same fix 😆 
`lv_win_set_title`
it would be repetitive if I did an issue for both of them 
hope you just fix them ❤️ 
really hyped for the upcoming release!

**Comment by kisvegabor** [comment]
@ashrafkamel5 
I've fixed both the dropdown and window, thanks for the report. 

@hamidrm
Thanks for looking into it.
Could send a PR to fix that Arabic letter.
