### ISSUE TITLE
Build fails when LV_USE_GPU_NXP_PXP is enabled

### ISSUE THREAD

**Issue by jupeos** [lvgl/lvgl#1969]
**To Reproduce**

Set `LV_USE_GPU_NXP_PXP` to 1 in lv_conf.h
Build fails on line 760 of lv_draw_blend.c
Incorrect definition name.
`GPU_NXP_PXP_BLIT_SIZE_LIMIT` should be `LV_GPU_NXP_PXP_BLIT_SIZE_LIMIT`

**Comment by kisvegabor** [comment]
Thanks for the report! Could send a Pull request?

**Comment by jupeos** [comment]
https://github.com/lvgl/lvgl/pull/1982#issue-546560918

**Comment by embeddedt** [comment]
PR was merged; closing. Thank you for the fix!
