### ISSUE TITLE
Convert the picture with Alpha byte

### ISSUE THREAD

**Issue by sirius65535** [lvgl/lvgl#198]
Hi,
Long time no see! 
I was busy these days, now I run LVGL on the MIPS，last week I plan to display the picture with Transperency ，the picture is RGB565 ，after add the Alpha ，it is 3 Bytes on every pixel ， but the MIPS needs 4 Byte align ，so how to solve it？

Thanks！

**Comment by kisvegabor** [comment]
As there wasn't activity here for months I close this issue.
If it's not working properly feel free to comment here and reopen the issue!
