### ISSUE TITLE
Image rotation not working as expected

### ISSUE THREAD

**Issue by embeddedt** [lvgl/lvgl#1980]
**Describe the bug**

Images are not being rotated when `lv_img_set_angle` is used.

**To Reproduce**

The bug can be reproduced on the PC simulator.

```c
    LV_IMG_DECLARE(logo_lvgl);
    lv_obj_t * img = lv_img_create(lv_scr_act(), NULL);
    lv_img_set_src(img, &logo_lvgl);
    lv_obj_set_drag(img, true);
    lv_img_set_angle(img, 450);
```

This is the image file I'm using for testing: [logo_lvgl.zip](https://github.com/lvgl/lvgl/files/5743388/logo_lvgl.zip)

**Expected behavior**

The image should be rotated 45 degrees.

**Screenshots**

![Peek 2020-12-26 11-58](https://user-images.githubusercontent.com/42941056/103155912-ac264d80-4771-11eb-8bea-99be565d0cc5.gif)

**Comment by kisvegabor** [comment]
Hi,

It's because indexed images can't be rotated.

**Comment by embeddedt** [comment]
Okay. I think we need to update the documentation in that case. 

https://docs.lvgl.io/latest/en/html/widgets/img.html#transformations

> Therefore indexed images, alpha only images or images from files can be transformed.

I think the "can" needs to be changed to "can't" there?

**Comment by kisvegabor** [comment]
> I think the "can" needs to be changed to "can't" there?

Yes... typical me... :sweat_smile: 
I fixed it. The site should be updated in a few minutes.
