### ISSUE TITLE
How to change label text style？ 

### ISSUE THREAD

**Issue by a295656031** [lvgl/lvgl#1981]
In the lvgl-6.1.2 version，I can change the label text style,  but in the lvgl-7.8.1 version, I can't find the api which can change the text style.

**Comment by embeddedt** [comment]
```c
lv_obj_set_style_local_text_font(label, LV_LABEL_PART_MAIN, LV_STATE_DEFAULT, &lv_font_montserrat_48);
```

The available properties are listed in the [documentation](https://docs.lvgl.io/latest/en/html/overview/style.html#text-properties). The example above changes `text_font`.

----------------------
We use GitHub issues for development related discussions.
Please use the [forum](https://forum.littlevgl.com/) to ask questions.

It's possible to sign in to the forum with your GitHub account... you don't need to make a separate account.
