### ISSUE TITLE
lv_conf_internal: Some CONFIG_* symbols are lowercase

### ISSUE THREAD

**Issue by C47D** [lvgl/lvgl#1989]
> # Important: issues that don't use this template will be ignored/closed.

**Describe the bug**

Symbols generated by Kconfig are always uppercase, in `lv_conf_internal.h` `CONFIG_lv_snprintf` and `CONFIG_lv_vsnprintf` are not.

**To Reproduce**

See 
https://github.com/lvgl/lvgl/blob/f0c52b35112e7734d52a2e25101e0d58ff50cea7/src/lv_conf_internal.h#L1375-L1388

**Expected behavior**

`CONFIG_lv_snprintf` and `CONFIG_lv_vsnprintf` should be uppercase. This should require updating the `lv_conf_checker.py`.

**Comment by kisvegabor** [comment]
Sorry, I've seen your PR only when I pushed the fix. 
Thank you anyway! Now it should be fixed in aba10b0

I've added a new commit to use `upper()` as you did.

**Comment by C47D** [comment]
No problem, thanks for the quick fix.
