### ISSUE TITLE
needle not entirely erased

### ISSUE THREAD

**Issue by uraich** [lvgl/lvgl#1993]
**Describe the bug**

When using an image as needle with the gauge widget the needle from the old position is not entirely erased, when moving the needle

**To Reproduce**

Please provide a small, independent code sample that can be used to reproduce the issue. Ideally this should work in the PC simulator unless the problem is specific to one platform.
reproduce:

https://github.com/uraich/lv_mpy_examples/blob/main/st7735_demos/voltmeter/voltmeter2.py

See the needle move without traces from previous positions

**Screenshots**

![image](https://user-images.githubusercontent.com/1673533/103480398-66523080-4dd4-11eb-958e-d4795f04a9af.png)

You see the blue dots from previous needle positions

**Comment by kisvegabor** [comment]
Thanks for the report, I've fixed it in `master`.

**Comment by uraich** [comment]
Checked it. It works fine now. 
Thanks
