### ISSUE TITLE
[v8] Rename LV_SPRINTF_DISABLE_FLOAT to LV_SPRINTF_ENABLE_FLOAT

### ISSUE THREAD

**Issue by C47D** [lvgl/lvgl#1994]
**EDIT**
Basically rename `LV_SPRINTF_DISABLE_FLOAT` to `LV_SPRINTF_ENABLE_FLOAT` and set to 0 by default, @embeddedt suggested to take a look to other configuration options that are set to 1 by default, see https://github.com/lvgl/lvgl/pull/1988#issuecomment-753391032.

It's the only option I have checked, because of the issue related to it, I can check other configuration options as well.

I was thinking on the name of this configuration, maybe call it ENABLE (and set it to 0 by default) instead of DISABLE, but we can discuss about in the future.

_Originally posted by @C47D in https://github.com/lvgl/lvgl/issues/1988#issuecomment-753404659_

**Comment by kisvegabor** [comment]
What about `LV_SPRINTF_USE_FLOAT`? It doesn't feel perfect to me but we already use the `USE` word a lot in configs.

There are many config options with `1` default value but I think we are interested only in the ones with inverted logic. I.e. `1` means disabled.

**Comment by embeddedt** [comment]
> I think we are interested only in the ones with inverted logic. I.e. 1 means disabled.

Correct.

> What about LV_SPRINTF_USE_FLOAT?

`LV_SPRINTF_SUPPORT_FLOAT`?

**Comment by C47D** [comment]
> I think we are interested only in the ones with inverted logic. I.e. 1 means disabled.

Yes

> LV_SPRINTF_SUPPORT_FLOAT?

This sounds fine to me, it seems like Toradex use something along `SPRINTF_FLOAT_ENABLE`, see [here](https://www.toradex.com/community/questions/23762/enable-floating-point-support-sprintf.html).

**Comment by puzrin** [comment]
`LV_SPRINTF_FLOAT_ON`

**Comment by kisvegabor** [comment]
I'm ok with any of the suggested names.

**Comment by C47D** [comment]
Ok, will send a PR against `dev` later this week.

**Comment by kisvegabor** [comment]
It's fixed in v8. See https://github.com/lvgl/lvgl/blob/834e2177e7fd5c493abf92aa097f54d49e57917d/lv_conf_template.h#L205

So I close this issue.
