### ISSUE TITLE
When there is only one object in the group, it still leave edit mode.

### ISSUE THREAD

**Issue by udoudou** [lvgl/lvgl#1995]
**Describe the bug**

When I use the encoder as input and there is only one object in the group, long press LV_KEY_ENTER will still leave edit mode.

**Expected behavior**

Don't leave edit mode if there is only one object in the group.

**Solution**

1. Change [src/lv_core/lv_indev.c line 672](https://github.com/lvgl/lvgl/blob/master/src/lv_core/lv_indev.c#L672) from `if(_lv_ll_is_empty(&g->obj_ll) == false) {` to `if(_lv_ll_is_empty(&g->obj_ll) == false && _lv_ll_get_len(&g->obj_ll) > 1 ) {`
```
/*Don't leave edit mode if there is only one object (nowhere to navigate)*/
if(_lv_ll_is_empty(&g->obj_ll) == false && _lv_ll_get_len(&g->obj_ll) > 1 ) {
    lv_group_set_editing(g, lv_group_get_editing(g) ? false : true); /*Toggle edit mode on long press*/
}
```
2. Fix the bug that the long press release event isn't sent to the object in this case. Change [src/lv_core/lv_indev.c line 738](https://github.com/lvgl/lvgl/blob/master/src/lv_core/lv_indev.c#L738) from `if(!i->proc.long_pr_sent || _lv_ll_is_empty(&g->obj_ll)) {` to `if(!i->proc.long_pr_sent || _lv_ll_is_empty(&g->obj_ll) || _lv_ll_get_len(&g->obj_ll) <= 1) {`
```
/*Ignore long pressed enter release because it comes from mode switch*/
if(!i->proc.long_pr_sent || _lv_ll_is_empty(&g->obj_ll) || _lv_ll_get_len(&g->obj_ll) <= 1) {
    indev_obj_act->signal_cb(indev_obj_act, LV_SIGNAL_RELEASED, NULL);
    if(indev_reset_check(&i->proc)) return;

    lv_event_send(indev_obj_act, LV_EVENT_SHORT_CLICKED, NULL);
    if(indev_reset_check(&i->proc)) return;

    lv_event_send(indev_obj_act, LV_EVENT_CLICKED, NULL);
    if(indev_reset_check(&i->proc)) return;

    lv_event_send(indev_obj_act, LV_EVENT_RELEASED, NULL);
    if(indev_reset_check(&i->proc)) return;

    lv_group_send_data(g, LV_KEY_ENTER);
}
```

**Comment by kisvegabor** [comment]
Hi,

Thanks for the report!

Can you send a Pull request?
