### ISSUE TITLE
lv_dropdown bug: able to select a non-existent option after the last real option

### ISSUE THREAD

**Issue by upbeat27** [lvgl/lvgl#1996]
**Describe the bug**

It is possible to click below the last option in a dropdown which selects a non-existent option.

**To Reproduce**

Using V7.9.0 and lv_demo_widgets

**Expected behavior**

Well, you shouldn't be able to!

**Screenshots**
![lvgl_dropdown_bug](https://user-images.githubusercontent.com/32659164/103705802-8f9fc780-4f60-11eb-9d91-c9e6831012f7.gif)

**Additional context**

N/A

**Comment by kisvegabor** [comment]
Thanks, fixed.
