### ISSUE TITLE
Cannot build without FS interface

### ISSUE THREAD

**Issue by ajaybhargav** [lvgl/lvgl#2]
If I disable file system interface
`USE_FSINT = 0`

I am not able to build at all. So its not modular as such. Don't you think functions like:
lv_img_create_file should be protected with flags like

`#if USE_FSINT && USE_UFS`

**Comment by kisvegabor** [comment]
You are right! When you do not use images the file system is not necessary at all. I will fix it. Thanks!

**Comment by kisvegabor** [comment]
Fixed in version 2.1
