### ISSUE TITLE
Allow background colour (mcolor) for labels

### ISSUE THREAD

**Issue by scopa90** [lvgl/lvgl#20]
It might be good to allow the background colour of a label to be set via mcolor and inherit the parent object's mcolor if it's not supplied.

**Comment by kisvegabor** [comment]
Hi,
it is a good idea, thank you! 
Do you mean if the label's style is NULL (inherited from parent) use transparent background and use _mcolor_ as background color if label's style is explicitly set?  Maybe the *empty* style attribute can disable this feature.

**Comment by scopa90** [comment]
Or just keep it as transparent unless it's explcitly set?

**Comment by kisvegabor** [comment]
Currently there is no tracking for a unique style attribute (like *mcolor*) whether it is set or not. Only I can see the entire style is inherited or not.

**Comment by kisvegabor** [comment]
If we think it further the label can use all *backround related* style attributes like *mcolor*, *gcolor*, *bcolor*, *bopa* etc. but only if its style is set explicitly.  Else only use the inherited *font*, *ccolor*, *letter space* etc 

What do you think?

**Comment by kisvegabor** [comment]
I added the update to `beta`. Now if a label's style is set by *lv_obj_set_style()* to not NULL then background will be drawn. 
To avoid drawing background set *empty=1* and *bwidth=0* properties or copy LV_STYLE_TRANSP when initializing a new label style. 

Tests are still needed to see how it effect existing objects where labels are used.

**Comment by scopa90** [comment]
Just had chance to test this but only for a straight label.  Looks very good.

**Comment by kisvegabor** [comment]
Thanks for testing!
