### ISSUE TITLE
lv_msgbox_set_anim_time() always sets animation to zero

### ISSUE THREAD

**Issue by xennex22** [lvgl/lvgl#2008]
I think the fault is obvious. 
https://github.com/lvgl/lvgl/blob/7d3a6c8de4303f69582a3939d36405a06b376ed0/src/lv_widgets/lv_msgbox.c#L238-L250

At some point in the past the code was like this, but an update must have changed it
```
#if USE_LV_ANIMATION == 0
    anim_time = 0;
#endif
    ext->anim_time = anim_time;
```

**Comment by embeddedt** [comment]
Thanks!
