### ISSUE TITLE
Use window control btns action

### ISSUE THREAD

**Issue by Moo2017** [lvgl/lvgl#201]
Hi All,
I want to create a window and assign two control btn, one for close the window and another one to open another window. should I add the btns to the group (I am using hardware keyboard) or add the window to the group is enough? I already added the window to the group but nothing happened and seems that I have to add btns separately. I want to make sure that if I am doing right. 
Moreover, how can I scroll down the window if text is long using hardware keyboard? is it possible only by adding a software button ?

**Comment by kisvegabor** [comment]
Scrolling of `lv_page` is added to `dev-5.2`. For more details see: #282
