### ISSUE TITLE
how to fill circle in lvgl 7.x?

### ISSUE THREAD

**Issue by acer1204** [lvgl/lvgl#2018]
this is my draw circle code in lvgl 7.0.1, how to draw fill circle in lvgl 7.0.1?

`lv_color_t cbuf[LV_CANVAS_BUF_SIZE_TRUE_COLOR(100, 100)];`
`lv_obj_t * canvas = lv_canvas_create(lv_scr_act(), NULL);`
`lv_canvas_set_buffer(canvas, cbuf, 100, 100, LV_IMG_CF_TRUE_COLOR_ALPHA);`
`lv_obj_align(canvas, NULL, LV_ALIGN_CENTER, 0, 0);`
`lv_canvas_fill_bg(canvas, LV_COLOR_WHITE,LV_OPA_TRANSP);`
`lv_draw_line_dsc_t sytll;`
`lv_draw_line_dsc_init(&sytll);`
`sytll.color = LV_COLOR_RED;`
`sytll.width = 1;`
`sytll.opa = LV_OPA_COVER;`
`lv_canvas_draw_arc(canvas,20,20,20,0,360,&sytll);`

howerer, my lvgl not found this api.
`lv_canvas_flood_fill` 
`lv_canvas_draw_circle`

my lvgl just found this api.
`lv_canvas_draw_rect`
`lv_canvas_draw_text`
`lv_canvas_draw_img`
`lv_canvas_draw_line`
`lv_canvas_draw_polygon`
`lv_canvas_draw_arc`

how to fill the circle with green color in lvgl 7.0.1?

**Comment by ValentiWorkLearning** [comment]
@acer1204 
https://github.com/ValentiWorkLearning/GradWork/blob/dev/coroutine/Firmware/graphics/widgets_layer/widgets/pages_switch/gs_pages_switch.cpp

Take a look at this solution with LV_RADIUS_CIRCLE.

**Comment by kisvegabor** [comment]
We use GitHub Issues for development-related discussions.

Please ask your question in the [Forum](https://forum.lvgl.io) to make it visible for a larger community. You can simply log in with your GitHub account.
