### ISSUE TITLE
lv_list_add_btn：     How to change the content of the button to the right

### ISSUE THREAD

**Issue by chcmq** [lvgl/lvgl#2026]
lv_obj_t * list1 = lv_list_create(appWindow, NULL);
    lv_obj_set_size(list1, lv_obj_get_width(appWindow)/2-20, lv_obj_get_height(appWindow)-(lv_obj_get_height(appWindow)/3));

    lv_obj_align(list1, NULL, LV_ALIGN_IN_LEFT_MID, 10, 0);

    /*Add buttons to the list*/
    lv_obj_t * list_btn;

    list_btn = lv_list_add_btn(list1, LV_SYMBOL_FILE, "New");
    // lv_obj_add_style(list_btn,LV_BTN_PART_MAIN,&style);
    lv_obj_set_event_cb(list_btn, event_handler);

    list_btn = lv_list_add_btn(list1, LV_SYMBOL_DIRECTORY, "Open");
    // lv_obj_add_style(list_btn,LV_BTN_PART_MAIN,&style);
    lv_obj_set_event_cb(list_btn, event_handler);

![选区_025](https://user-images.githubusercontent.com/30547484/104806555-60684080-5813-11eb-89ee-347db19b95a4.png)

I want to put the content on the right, is there any good way?

**Comment by kisvegabor** [comment]
We use GitHub Issues for development-related discussions.

Please ask your question in the [Forum](https://forum.lvgl.io) to make it visible for a larger community. You can simply log in with your GitHub account.
