### ISSUE TITLE
arc fill angle mismatch with arc current value

### ISSUE THREAD

**Issue by jupeos** [lvgl/lvgl#2032]
### Describe the bug
When creating a simple arc using `lv_arc_set_angles` the arc is shown as filled (full) between the 2 angles. However the current value is 0 (obtained with `lv_arc_get_value`).
Aside: because of this, in order to set the value to 0 using `lv_arc_set_value` it is necessary to use:
```
lv_arc_set_value(arc, 1); // or some non-zero value
lv_arc_set_value(arc, 0);
```

### To Reproduce
```
    lv_obj_t* arc = lv_arc_create( lv_scr_act(), NULL );
    lv_obj_set_size( arc, 200, 200 );
    lv_obj_align( arc, NULL, LV_ALIGN_CENTER, 0, 0 );

    lv_arc_set_angles( arc, 135, 45 );
    int16_t currentValue = lv_arc_get_value( arc ); // this is 0
    lv_arc_set_value( arc, 0 );
```
Results in
![image](https://user-images.githubusercontent.com/5043387/105402918-dc300780-5bdc-11eb-93c4-b2b8321377fa.png)

### Expected behavior
The fill angle of the arc should be consistent with the current value (in this case 0), i.e. the arc should look like this
![image](https://user-images.githubusercontent.com/5043387/105401283-e05b2580-5bda-11eb-8ed2-4a5b5649c807.png)

**Comment by embeddedt** [comment]
Not sure that this will fix your issue, but I think you have the angles backwards in `lv_arc_set_angles`. Unless that is your intent?

**Comment by jupeos** [comment]
> Not sure that this will fix your issue, but I think you have the angles backwards in `lv_arc_set_angles`. Unless that is your intent?

This is what I intended and it makes no difference if you reverse the values other than the visual
![image](https://user-images.githubusercontent.com/5043387/105428115-8884e480-5c03-11eb-9f3c-490ce29da853.png)

**Comment by kisvegabor** [comment]
HI @jupeos,

At this moment there are some issues with using `value` and `angles` together. In short, you can control the arc either by the angle directly or let the arc control it by setting the `value`.

Note that,  `value` is mapped to angles relative to the `bg_angles`. `value == min` means `bg_start_angle` and `value == max` means `bg_end_angle`. 

So you should either remove `lv_arc_set_angles( arc, 135, 45 );` to leave the default value or use `lv_arc_set_bg_angles( arc, 135, 45 );` to set the "angular range" of the arc when `value` is used.

**Comment by jupeos** [comment]
Understood. In the interim it would be helpful to make this clear in the documentation to either use 1 approach or the other but not both.

**Comment by kisvegabor** [comment]
Added here: https://github.com/lvgl/docs/commit/518b99139dab84fcc772ab82e1fb4ee3a3ecd5f7

It will be visible when the docs are rebuilt.

**Comment by embeddedt** [comment]
Documentation rebuilding is now fixed (and automated) so this is now mentioned [here](https://docs.lvgl.io/latest/en/html/widgets/arc.html#range-and-values).
