### ISSUE TITLE
Detect UI Component / Update has been drawn to the display

### ISSUE THREAD

**Issue by andrewrt** [lvgl/lvgl#2035]
What is the proper way to tell if a UI Component / etc has been drawn / flushed to the display?

In my system I have FreeRTOS running an lv_redraw task with:
```c

void lv_redraw( void *pvParameters ) {
  //periodically every few milliseconds in the main while(1) loop, in Timer interrupt or in an Operation system task.
  //It will redraw the screen if required, handle input devices etc
  uint32_t millisec = 50;
  static uint8_t _100ms = 0;
  TickType_t ticks = millisec / portTICK_PERIOD_MS;

  for( ;; ){
    vTaskDelay(ticks);
    UI_TakeMutex();
    lv_task_handler();
    if (_100ms++ >= 5){
      _100ms = 0;
      status_refresh();
    }
    UI_GiveMutex();
  }
}
```

Sometimes with the above code, if there's a full screen update in `status_refresh`, and another task waits 350ms for the redraw task to update the screen before pausing LVGL, the screen redraw is not completed in time. 

Ideally instead of guessing the time it would take to update the UI, it'd be more precise to signal the other task that "LVGL has successfully updated the screen". I wasn't able to find such a feature, but maybe I'm missing something?

**Comment by embeddedt** [comment]
You are looking for the `monitor_cb` callback in the display driver - it is called whenever rendering has finished.

----------------------
We use GitHub issues for development related discussions.
Please use the [forum](https://forum.littlevgl.com/) to ask questions.

It's possible to sign in to the forum with your GitHub account... you don't need to make a separate account.
