### ISSUE TITLE
Double Buffer optimization for SPI interface screen

### ISSUE THREAD

**Issue by FASTSHIFT** [lvgl/lvgl#2038]
### Introcude the problem
When using the SPI screen, the benchmark score of two full-screen buffers is lower than that of using two half-screen buffers.

### Examples and cases
Two half-screen buffers:
![DFB614AFF3B80491FBDA84D25A1C94DB](https://user-images.githubusercontent.com/26767803/105718833-a1233080-5f5c-11eb-95c5-b6ad134fddce.jpg)

Two full-screen buffers:
![12947B8ABA7B786288C79300CE52519C](https://user-images.githubusercontent.com/26767803/105718853-a4b6b780-5f5c-11eb-9ca0-f57c3c0a7d3a.jpg)

### Suggested solution
I modified a function of lv_hal_disp.c, and the benchmark score of the two full-screen buffers has been improved.
```C
bool lv_disp_is_true_double_buf(lv_disp_t * disp)
{
    return false;
    /*uint32_t scr_size = disp->driver.hor_res * disp->driver.ver_res;

    if(lv_disp_is_double_buf(disp) && disp->driver.buffer->size == scr_size) {
        return true;
    }
    else {
        return false;
    }*/
}
```
![7F9CE941A9FAFC9BDF1605539BE7FC14](https://user-images.githubusercontent.com/26767803/105722028-2fe57c80-5f60-11eb-925f-4d749745804c.jpg)

Is it possible to add a macro switch to distinguish whether it is an SPI screen and give full play to the performance of the two full-screen buffers.

**Comment by kisvegabor** [comment]
I agree it'd be less confusing to add a config option. 

However, for backward compatibility, we should keep the current behavior in v7.

I'll add it in v8.

**Comment by FASTSHIFT** [comment]
@kisvegabor 
Does lvgl v8 support this feature now?
It is optimized for the dual full-screen buffer of the SPI screen.

**Comment by kisvegabor** [comment]
I've just added the `full_refresh` flag to the display driver. IF enabled the whole screen will be redrawn even if only 1 pixel has changed. 
By default it's false.
