### ISSUE TITLE
Custom Containers on Lists

### ISSUE THREAD

**Issue by margce** [lvgl/lvgl#204]
Hi all,

I'm working on implementing my first project with LVGL and was wondering the following. On other GUI libraries I've used there is usually an option to define a custom container. Having this custom container you would then create a list of them for the user to interact with them. You can do this for example when developing apps on Android.

Say that you define a container that holds a fixed label (Name) and a variable label (Value). This is what you can do on for example TouchGFX.
![image](https://user-images.githubusercontent.com/13647561/38716383-c29f36de-3f23-11e8-80d9-a7611ccf2f14.png)

On LGVL I see that the List object can only list Button objects and that the Container object is only for Text. 

Is there any way I could achieve what I mentioned?

**Comment by kisvegabor** [comment]
Hi,

You can create an `lv_page` and add any type of object to it. Here is an exemple:
```c

lv_obj_t * label;       /*It will be used to create some content*/

/*Create a page (the main container) */
lv_obj_t * page = lv_page_create(lv_scr_act(), NULL);
lv_obj_set_size(page, 150, 200);
lv_page_set_scrl_layout(page, LV_LAYOUT_COL_M);     /*Arrange elements automatically*/

/*First element*/
lv_obj_t * e1 = lv_btn_create(page, NULL);          /*Create a button as element*/
lv_obj_set_width(e1, lv_page_get_scrl_width(page)); /*Set the button's width to the page width (use the scrollable width)*/
lv_btn_set_fit(e1, false, true);                    /*Set height automatically*/
lv_page_glue_obj(e1, true);                         /*Glue to the page (enables the scrolling of the page with this object)*/
lv_btn_set_layout(e1, LV_LAYOUT_OFF);               /*Turn off the buttons default CENTER layout*/

label = lv_label_create(e1, NULL);
lv_label_set_text(label, "Custom\ncontent");

/*Second element*/
lv_obj_t * e2 = lv_btn_create(page, e1);            /*Copy the first element*/

label = lv_label_create(e2, NULL);
lv_label_set_text(label, "Other\ncustom\ncontent");

/*Third elemnt*/
lv_obj_t * e3 = lv_btn_create(page, e1);

label = lv_label_create(e3, NULL);
lv_label_set_text(label, "Third\ncustom\ncontent");
```
![image](https://user-images.githubusercontent.com/7599318/38749877-69c14fae-3f53-11e8-81f7-fafbc7b3422d.png)

It looks a little bit ugly by default but you can customize the appearance with styles.

Anyway a "generic list object" which do this would be useful.

**Comment by margce** [comment]
Thanks Gabor, I will give this a try.

**Comment by qwert1213131** [comment]
@kisvegabor 
I use pc_proj and lv_page, but in the process of using mouse, I find that touch sometimes fails.

![_ _20180416222135](https://user-images.githubusercontent.com/3905169/38815118-c786d91e-41c5-11e8-8b07-65d3acfdb778.png)

**Comment by kisvegabor** [comment]
@qwert1213131 How do you mean fail? The object is not reacting on click? If yes. do you know which parts or in which cases?

**Comment by qwert1213131** [comment]
For lv_page, when I use the mouse to do the slide  operation, it sometimes do not respond.

**Comment by qwert1213131** [comment]
Later, I will send the source code, thank you! I'm not sure if it's the problem of my code

**Comment by kisvegabor** [comment]
I have an idea. When you slide it is possible that the next point from mouse is already on the button above the pressed. In this case the button losses pressing and no slide happens.

Please apply it for every list element: `lv_obj_set_protect(element, LV_PROTECT_PRESS_LOST)`

If it helps it should be added to `lv_list_add` directly.

**Comment by qwert1213131** [comment]
that‘s the source code`：

static void gui_create(void)
{

	lv_theme_t *th = lv_theme_night_init(200, NULL);
	lv_theme_set_current(th);



	lv_obj_t * scr = lv_scr_act();
	//创建sys页面
	lv_obj_t * page_sys = lv_page_create(scr,NULL);
	lv_obj_set_size(page_sys,LV_HOR_RES,LV_VER_RES);
	lv_page_set_sb_mode(page_sys,LV_SB_MODE_AUTO);
	lv_obj_align(page_sys,scr,LV_ALIGN_CENTER,0,0);
	lv_page_set_scrl_layout(page_sys, LV_LAYOUT_COL_L);     /*Arrange elements automatically*/


	lv_obj_t * cont_sysinfo = lv_cont_create(page_sys,NULL);
	lv_obj_set_width(cont_sysinfo,LV_HOR_RES-25);
	lv_cont_set_fit(cont_sysinfo,false,true);


	lv_obj_t * cont_bluetooth = lv_cont_create(page_sys,cont_sysinfo);
	lv_obj_t * cont_sdcard = lv_cont_create(page_sys,cont_sysinfo);
	lv_obj_t * cont_battery = lv_cont_create(page_sys,cont_sysinfo);
	lv_obj_t * cont_bright = lv_cont_create(page_sys,cont_sysinfo);
	lv_obj_t * cont_time = lv_cont_create(page_sys,cont_sysinfo);


	lv_obj_t * label_sysinfo = lv_label_create(cont_sysinfo,NULL);
	lv_label_set_text(label_sysinfo," #0ff000 SysInfo#");
	lv_label_set_recolor(label_sysinfo,true);

	lv_obj_t * label_bluetooth = lv_label_create(cont_bluetooth,NULL);
	lv_label_set_text(label_bluetooth," #0ff000 Bluetooth#");
	lv_label_set_recolor(label_bluetooth,true);

	lv_obj_t * label_sdcard= lv_label_create(cont_sdcard,NULL);
	lv_label_set_text(label_sdcard," #0ff000 SDCard#");
	lv_label_set_recolor(label_sdcard,true);

	lv_obj_t * label_battery= lv_label_create(cont_battery,NULL);
	lv_label_set_text(label_battery," #0ff000 Battery#");
	lv_label_set_recolor(label_battery,true);

	lv_obj_t * label_bright= lv_label_create(cont_bright,NULL);
	lv_label_set_text(label_bright," #0ff000 Bright#");
	lv_label_set_recolor(label_bright,true);

	lv_obj_t * label_time= lv_label_create(cont_time,NULL);
	lv_label_set_text(label_time," #0ff000 Time#");
	lv_label_set_recolor(label_time,true);



	/*Create a style and use the new font*/
		static lv_style_t style1;
		lv_style_copy(&style1, &lv_style_pretty_color);
		style1.text.font = &lv_font_dejavu_10; /*Set the base font whcih is concatenated with the others*/
		style1.text.opa = 70;


	lv_obj_t * label_sysinfo_version = lv_label_create(cont_sysinfo,NULL);
	lv_label_set_text(label_sysinfo_version,"HW: 3.2.0\nSW: 0.0.1\nGUI: LittleVGL 5.1.0");
	lv_obj_align(label_sysinfo_version,label_sysinfo,LV_ALIGN_OUT_BOTTOM_LEFT,30,0);
	lv_label_set_style(label_sysinfo_version, &style1);

	lv_obj_t * label_bluetooth_mac = lv_label_create(cont_bluetooth,label_sysinfo_version);
	lv_label_set_text(label_bluetooth_mac,"mac:\nname:");
	lv_obj_align(label_bluetooth_mac,label_bluetooth,LV_ALIGN_OUT_BOTTOM_LEFT,30,0);

	lv_obj_t * sw_bluetooth = lv_sw_create(cont_bluetooth,NULL);
	lv_obj_align(sw_bluetooth,label_bluetooth,LV_ALIGN_OUT_LEFT_MID,190,0);
	lv_sw_on(sw_bluetooth);

	static uint32_t TF_TotalSize = 7000;
	static uint32_t TF_FreeSize = 6000;

	lv_obj_t *label_sdcard_cap = lv_label_create(cont_sdcard,label_sysinfo_version);
	char buffer[60];
	sprintf(buffer,"Total cap:%dMB\nFree cap :%dMB",TF_TotalSize,TF_FreeSize);
	lv_label_set_text(label_sdcard_cap,buffer);
	lv_label_set_recolor(label_sdcard_cap, true);
	lv_obj_align(label_sdcard_cap, label_sdcard, LV_ALIGN_OUT_BOTTOM_LEFT, 30, 0);


	lv_obj_t * bar_sdcard  = lv_bar_create(cont_sdcard,NULL);
	lv_bar_set_range(bar_sdcard,0,100);
	lv_obj_set_size(bar_sdcard,180,15);
	lv_bar_set_value(bar_sdcard,(TF_TotalSize-TF_FreeSize)*100/TF_TotalSize);
	lv_obj_align(bar_sdcard, label_sdcard_cap, LV_ALIGN_OUT_BOTTOM_LEFT, 0, 0);


	lv_obj_t *label_battery_percent = lv_label_create(cont_battery,label_sysinfo_version);
	lv_label_set_text(label_battery_percent,"70%");
	lv_obj_align(label_battery_percent, label_battery, LV_ALIGN_OUT_LEFT_MID,190, 0);
}`
I will have a try about **lv_obj_set_protect**

**Comment by margce** [comment]
Gabor, I tried qwerty's example and what I noticed is that when trying to slide down or up using the mouse it only works when you click outside of each container (light grey) it works fine. But if you trying sliding by clicking from a container it doesn't always respond to the gesture.

**Comment by kisvegabor** [comment]
Thank you for the review! It was very helpful.
It happens because @qwert1213131 forgot to apply `lv_page_glue_obj(cont_sysinfo, true); ` It "glues" the object to the list and make possible to scroll by dragging the object. 
It should help!

**Comment by qwert1213131** [comment]
@margce  @kisvegabor 
Try it，Thanks both of you!
Modify the code：，and need to add the lv_page_glue_obj() to many objects
```
//创建sys页面
lv_obj_t * page_sys = lv_page_create(scr,NULL);
lv_obj_set_size(page_sys,LV_HOR_RES,LV_VER_RES);
lv_page_set_sb_mode(page_sys,LV_SB_MODE_AUTO);
lv_obj_align(page_sys,scr,LV_ALIGN_CENTER,0,0);
lv_page_set_scrl_layout(page_sys, LV_LAYOUT_COL_L);     /*Arrange elements automatically*/


lv_obj_t * cont_sysinfo = lv_cont_create(page_sys,NULL);
lv_obj_set_width(cont_sysinfo,LV_HOR_RES-25);
lv_cont_set_fit(cont_sysinfo,false,true);
lv_page_glue_obj(cont_sysinfo , true);   
```

**Comment by qwert1213131** [comment]
@kisvegabor 
Yes,it worked well,Thanks！
I think it is great！just as the swipelist ! as follows.
![tim 20180419133420](https://user-images.githubusercontent.com/3905169/38973037-648a24ac-43d6-11e8-9b83-6b5297790232.png)
![tim 20180419133504](https://user-images.githubusercontent.com/3905169/38973078-89977d1c-43d6-11e8-95b6-603b0051f488.png)

Waht do you think？

**Comment by margce** [comment]
I like @qwert1213131 idea I see that really handy for navigation menus. I guess what I was looking for was being able to define the item (container) and then the list object should take care of displaying them in a list fashion.

**Comment by kisvegabor** [comment]
At @qwert1213131 Thank you for the great graphics!

I think it's something you could realize with the mentioned "generic list" which:
- gives you `lv_cont` object on `lv_list_add` where you can place custom content, add layout and/or auto fit
- automatically arrange the container below each other.
- provides swiping

Do you mean this as well?

**Comment by qwert1213131** [comment]
@kisvegabor
yes, I agree with you,that's a good solution!
THanks😊

**Comment by kisvegabor** [comment]
I was thinking about it this issue again and I realized that it can be implemented easily using an `lv_page` and `LV_LAYOUT_COL_M` or `LV_LAYOUT_COL_L`. This way you can add any object to the page which provides the highest flexibility.

If you feel something is missing with the proposed solution feel free to comment here.

**Comment by liangfei2021** [comment]
Hi @kisvegabor :
   Create multiple list_item on LCD(240*240), how to display the item whose state is focus in the center of the screen?

**Comment by kisvegabor** [comment]
We use GitHub Issues for development-related discussions.

Please ask your question in the [Forum](https://forum.lvgl.io) to make it visible for a larger community. You can simply log in with your GitHub account.
