### ISSUE TITLE
issue for cpicker

### ISSUE THREAD

**Issue by ZhaoQiang-b45475** [lvgl/lvgl#2041]
Hi,
I create a cpicker and set it to rect, met a issue shown as capture(for detail, please refer to zip which is a video).
The color selecting area become the same color sometimes and couldn't change back. Is it the issue of lvgl or system's cpicker?
<img width="306" alt="colorpicker" src="https://user-images.githubusercontent.com/22284222/105937873-6242c700-6091-11eb-8d39-5e57ac3ed492.PNG">
[color_media.zip](https://github.com/lvgl/lvgl/files/5877541/color_media.zip)

**Comment by embeddedt** [comment]
Are you referring to how it switches to saturation mode instead of the default hue mode? That is triggered by holding down the knob for a long time, and can be disabled using `lv_cpicker_set_color_mode_fixed(cpicker, true)`.

**Comment by ZhaoQiang-b45475** [comment]
Thanks for your explanation!

**Comment by kisvegabor** [comment]
As the issue seems to be solved I close it.

If it's still not working please reopen the issue and comment here.
