### ISSUE TITLE
Does this Gui support touch gestures slide?

### ISSUE THREAD

**Issue by qwert1213131** [lvgl/lvgl#205]
As stated in the title

**Comment by kisvegabor** [comment]
Some object supports it. For example in `lv_tabview` you can change between tabs with slides.

Try this:
```c
    lv_theme_t * th = lv_theme_alien_init(210, NULL);
    lv_test_theme_1(th);
```

`lv_examples` will be required.

**Comment by qwert1213131** [comment]
Referring to #204, I find lv_page is more suitable for my needs. Thank you.
