### ISSUE TITLE
set drag parent conflict with textarea??

### ISSUE THREAD

**Issue by incity** [lvgl/lvgl#2053]
as the code below:

1. create a page
2. add a textarea and a button.
3. set drag parent for the button.
4. run the program and click the button, it will get an object error report.

![image](https://user-images.githubusercontent.com/7846605/106562117-cdded580-6564-11eb-8bd9-55a724d17269.png)

note : if i change textarea to la abel or other controls, it runs ok.
          if i remove lv_obj_set_drag_parent, it runs ok.
          if i set the size of textarea to 90*90, it also runs ok.
Code to produce:

```
static void test_test(lv_task_t *param) {
    printf("--->\n");
    lv_obj_del(tv);
    lv_demo_widgets();
}
bool i = 0;
void lv_demo_widgets(void)
{
    tv = lv_page_create(lv_scr_act(), NULL);

    lv_obj_set_size(tv, 1024, 800);
    if (i == 0) {
        lv_task_create(test_test, 100, LV_TASK_PRIO_MID, NULL);
        i = 1;
    }
    lv_obj_t * ta = lv_textarea_create(tv, NULL);
    lv_obj_set_size(ta, 70, 30);

    ta = lv_btn_create(tv, NULL);
    lv_obj_set_pos(ta, 400, 500);
    lv_obj_set_drag(ta, true);
    lv_obj_set_size(ta, 70, 100);
    lv_obj_set_drag_parent(ta, true);

    return;
}
```

**Comment by kisvegabor** [comment]
Fixed in 0631b17
