### ISSUE TITLE
Use freetype to report an error？？

### ISSUE THREAD

**Issue by chcmq** [lvgl/lvgl#2057]
I am sure I have installed freetype

* Framework Arduino
* Build tool PlatformIO
* Uses LVGL from platformIO

=================================================
libs/lv_lib_freetype/lv_freetype.h:16:22: fatal error: ft2build.h: No such file or directory

******************************************************************
* Looking for ft2build.h dependency? Check our library registry!
*
* CLI  > platformio lib search "header:ft2build.h"
* Web  > https://platformio.org/lib/search?query=header:ft2build.h
*
******************************************************************

=================================================

**Comment by kisvegabor** [comment]
Do you link freetype with your program?
See https://github.com/lvgl/lv_lib_freetype#add-freetype-to-your-project

**Comment by chcmq** [comment]
I used apt-get install to install it.
```bash
$apt-get install libfreetype6-dev
```
- System  Linux

**Comment by kisvegabor** [comment]
You also need to add the library and its include path to platformio.ini.

**Comment by chcmq** [comment]
- Can you help me to see where I configured wrong?
![选区_029](https://user-images.githubusercontent.com/30547484/107209925-6df19e80-6a3e-11eb-9b80-601f603d1f76.png)
![选区_030](https://user-images.githubusercontent.com/30547484/107209958-78ac3380-6a3e-11eb-87ed-4a1c058c8551.png)

**Comment by kisvegabor** [comment]
I'm not so experienced with PIO. Maybe @puzrin can help with that.

**Comment by kisvegabor** [comment]
I just saw that you have opened a [topic](https://forum.lvgl.io/t/how-to-add-freetype-to-esp32/4515) in the forum.

Let's continu there. 

But in order to get help easier, please fill teh template.

**Comment by puzrin** [comment]
There are no `freetype` package in PIO registry. Since this is not lvgl-specific, it's better to search help on PIO forum.

**Comment by chcmq** [comment]
Thank you very much @puzrin @kisvegabor
