### ISSUE TITLE
Redraw an an object 

### ISSUE THREAD

**Issue by Moo2017** [lvgl/lvgl#206]
I that any way to redraw an object after being created? Assume that I create a keyboard, then  once user type the text and insert Enter key, a message box including two option "Edit" and "Save" pops up, if Edit is pressed user is returned to the keyboard , Is that any way to redraw the keyboard?

**Comment by kisvegabor** [comment]
If you mean by "Enter" the "Ok" button then yes. Clicking the "Ok" or "Hide" button will delete the keyboard by default but if you assign an `ok_action` then you can control what to happen on click. You can hide the keyboard or animate it out.

Use: `lv_kb_set_ok_action()`

**Comment by Moo2017** [comment]
@kisvegabor Oh no I mean assume that I create an object which has common area with the previous object. Once I delete the second object , the common area will be cleared so I have to redraw the previous one. I was looking for a way not to delete and create the previous object.

**Comment by Moo2017** [comment]
@kisvegabor I found that! I should focus on the previous object only right?! 
what happened if I focus on an object that I haven't add to the group?

**Comment by kisvegabor** [comment]
The managing of redrawing should be done by the library automatically. Please send an example code to see what happens.

**Comment by kisvegabor** [comment]
It seems the issue is solved so I close it. 
If you have any remarks in this topic feel free to reopen it!
