### ISSUE TITLE
How to support LVGL symbol icons in all fonts

### ISSUE THREAD

**Issue by MouriNaruto** [lvgl/lvgl#2077]
### Introduce the problem

I had written the Windows GDI font engine for getting the font glyph at the runtime like the way of lv_lib_freetype.

But I found we can't use the LVGL symbol icons.

### Examples and cases

![image](https://user-images.githubusercontent.com/10867563/107890997-f5677200-6f56-11eb-8335-89e67fe2cf34.png)

### Suggested solution

N/A

**Comment by embeddedt** [comment]
That's a smart approach!

I'm not sure, but I think you might need to add logic to translate from FontAwesome symbols to Windows equivalents, as the glyph codes we use are specific to [FontAwesome](https://fontawesome.com/).

**Comment by kisvegabor** [comment]
> I'm not sure, but I think you might need to add logic to translate from FontAwesome symbols to Windows equivalents, as the glyph codes we use are specific to FontAwesome.

Furthermore, the built-in symbols are used from this [font file](https://lvgl.io/assets/others/FontAwesome5-Solid+Brands+Regular.woff). It's a single file merged from 3 FontAwesome font files.

The symbols defined in LVGL are the UTF8 coded Unicode codes from the linked font file.

**Comment by MouriNaruto** [comment]
> > I'm not sure, but I think you might need to add logic to translate from FontAwesome symbols to Windows equivalents, as the glyph codes we use are specific to FontAwesome.
> 
> Furthermore, the built-in symbols are used from this [font file](https://lvgl.io/assets/others/FontAwesome5-Solid+Brands+Regular.woff). It's a single file merged from 3 FontAwesome font files.
> 
> The symbols defined in LVGL are the UTF8 coded Unicode codes from the linked font file.

@kisvegabor 

I have download the font file and edit it to make it only have the symbols the LVGL needed.

I also want to ask permission for a new repo for Windows application port because most people lv_sim_visual_studio should keep the same behavior as the old simulator. But I want to add some features to make people can use LVGL to develop Windows desktop applications. It makes users confused. (I had met a user ask me about that.) So I ask for the permission, I will keep the lv_sim_visual_studio like the simulator. (Or rename the repo like lv_port_windows, and I maintain two flavors(simulator and desktop application).)

**Comment by kisvegabor** [comment]
@MouriNaruto Permission granted :slightly_smiling_face: 

It'd be great to ensure that LVGL can work smoothly with the Windows ecosystem. Thank you very much for working on this!

I'm creating the repo.

**Comment by kisvegabor** [comment]
Created https://github.com/lvgl/lv_port_windows/
And I also sent you an invitation for "Maintain" access. (almost like Admin)

**Comment by MouriNaruto** [comment]
@kisvegabor Thank you very much.

**Comment by MouriNaruto** [comment]
![image](https://user-images.githubusercontent.com/10867563/109948255-1c72c180-7d15-11eb-896c-b7d786273d53.png)

@kisvegabor @embeddedt  I have solved the issue. I use the font that @kisvegabor provided, reduce the font glyphs for less binary size, embedded into the source code.

This is the font file I finally used. 
[Font Awesome 5 Free for LVGL.zip](https://github.com/lvgl/lvgl/files/6082668/Font.Awesome.5.Free.for.LVGL.zip)

**Comment by kisvegabor** [comment]
>  I have solved the issue. I use the font that @kisvegabor provided, reduce the font glyphs for less binary size, embedded into the source code.

Great!

The smaller binary size was important for you for performance reasons? 

For general purpose usage, I prefer the font with all symbols to allow users to add symbols not included in the build-in list.

**Comment by MouriNaruto** [comment]
@kisvegabor 

> The smaller binary size was important for you for performance reasons?

I am interested in writing the most compact implementations by using the least syntaxes and third-party libraries. And I worked for the project team which need for compact implementations.

**Comment by MouriNaruto** [comment]
@kisvegabor 

> For general purpose usage, I prefer the font with all symbols to allow users to add symbols not included in the build-in list.

I have provided two versions of Font Awesome 5 Free font. (One is for optimized size, other is for full symbols.)

https://github.com/lvgl/lv_port_windows/blob/master/LVGL.Windows/LVGL.Resource.FontAwesome5Free.h
https://github.com/lvgl/lv_port_windows/blob/master/LVGL.Windows/LVGL.Resource.FontAwesome5FreeLVGL.h

I hope you will like it.
