### ISSUE TITLE
slider draws incorrectly if vertical and type=symmetrical

### ISSUE THREAD

**Issue by hammockman** [lvgl/lvgl#2082]
### Perform all steps below and tick them with [x]
- [x] Check the related part of the [Documentation](https://docs.lvgl.io/)
- [x] Update lvgl to the latest version
- [x] Reproduce the issue in a [Simulator](https://docs.lvgl.io/latest/en/html/get-started/pc-simulator.html)

### Describe the bug
Vertical slider with LV_SLIDER_TYPE_SYMMETRICAL behaves incorrectly

### To Reproduce
The micropython simulator exhibits the same mis-behaviour as the PC simulator (CodeBlocks) and the Arduino port:

https://sim.lvgl.io/v7/micropython/ports/javascript/bundle_out/index.html
```python
import imp, sys
sys.path.append('https://raw.githubusercontent.com/littlevgl/lv_binding_micropython/master/lib')
import display_driver
import lvgl as lv
scr = lv.obj()
s = lv.slider(scr)
s.set_width(20)
s.set_height(100)
s.set_range(-100,100)
s.set_value(0,0)
s.set_type(1)
s.align(scr, lv.ALIGN.CENTER, 0, 0)
lv.scr_load(scr)
```

### Expected behavior

If either the slider is horizontal or the slider type is not symmetrical then the slider behaves as expected.
![image](https://user-images.githubusercontent.com/6187172/108132282-71101d00-7117-11eb-8453-f4837c6a9828.png)

### Screenshots or video

![image](https://user-images.githubusercontent.com/6187172/108132188-4faf3100-7117-11eb-9b44-d05f185c23db.png)

Micropython simulator:

![image](https://user-images.githubusercontent.com/6187172/108132132-39a17080-7117-11eb-95e2-94e2805d64e2.png)

**Comment by kisvegabor** [comment]
@embeddedt You are the most familiar with the news slider (bar) drawer. Could you take a look?

**Comment by embeddedt** [comment]
Will investigate when I have a chance.

**Comment by embeddedt** [comment]
This should be fixed in #2085.

**Comment by kisvegabor** [comment]
Worked well for me!

**Comment by hammockman** [comment]
Brilliant, that seems to have resolved the issue. Thanks very much for the prompt attention.
