### ISSUE TITLE
 global-buffer-overflow

### ISSUE THREAD

**Issue by incity** [lvgl/lvgl#2089]
![image](https://user-images.githubusercontent.com/7846605/108796942-eb7fe780-75c4-11eb-91b9-94339fe1c7a8.png)

**Comment by kisvegabor** [comment]
How can we reproduce it? What is the content of teh text area?

**Comment by incity** [comment]
for multi-line textarea, input multi-line text and delete chars will produce it.

**Comment by kisvegabor** [comment]
It works well here:

![Peek 2021-02-24 13-18](https://user-images.githubusercontent.com/7599318/108999654-e09b8480-76a2-11eb-9692-d31ce6d2889b.gif)

```

WARNINGS ?= -Werror -Wall -Wextra \
  -Wshadow -Wundef -Wmaybe-uninitialized -Wmissing-prototypes -Wno-discarded-qualifiers \
  -Wno-unused-function -Wno-error=strict-prototypes -Wpointer-arith -fno-strict-aliasing -Wno-error=cpp -Wuninitialized \
  -Wno-unused-parameter -Wno-missing-field-initializers -Wno-format-nonliteral -Wno-cast-qual -Wunreachable-code -Wno-switch-default  \
  -Wreturn-type -Wmultichar -Wformat-security -Wno-ignored-qualifiers -Wno-error=pedantic -Wno-sign-compare -Wno-error=missing-prototypes -Wdouble-promotion -Wclobbered -Wdeprecated  \
  -Wempty-body -Wshift-negative-value -Wstack-usage=20048 \
  -Wtype-limits -Wsizeof-pointer-memaccess -Wpointer-arith \
  -fsanitize=address -fno-omit-frame-pointer
            
CFLAGS ?= -O0 -g3 -I$(LVGL_DIR)/ $(WARNINGS)
LDFLAGS ?= -lSDL2 -lm  -fsanitize=address  -fno-omit-frame-pointer
```

**Comment by incity** [comment]
my lv_examples is not the latest, but i think it is not the problem??

**Comment by embeddedt** [comment]
@incity Can you reproduce it using one of the examples or a slightly modified version and post the exact code here? Otherwise it will be difficult to debug.

**Comment by incity** [comment]
@embeddedt I just use the lv_examples, and do not change any code.

**Comment by incity** [comment]
my lv_examples version is the commit a5015dbb38dd56d49bbf7a96bd2e4bd56c10bf29 and lvgl version is the commit af98c9a9c0a8601d47dec2e88f1c88b2b49bb0f0

**Comment by kisvegabor** [comment]
Could you try with the latest lvgl and lv_examples?

**Comment by incity** [comment]
when i input text, there are some warnings(i has use latest lvgl and lv_exampes) 
![image](https://user-images.githubusercontent.com/7846605/109008628-87564400-76e8-11eb-9184-df40d19e310b.png)

**Comment by incity** [comment]
the attachment is my config 


[lv_conf.zip](https://github.com/lvgl/lvgl/files/6036377/lv_conf.zip)

**Comment by kisvegabor** [comment]
It happens because you have enabled `LV_USE_ARABIC_PERSIAN_CHARS` but font doesn't have Persian characters. 
In the last line on the left there is an empty button. There should be persian character to switch to the persian page.

Do you still see the issue with disabled `LV_USE_ARABIC_PERSIAN_CHARS`.

I can't see it even with your lv_conf.h.

**Comment by incity** [comment]
i disable LV_USE_ARABIC_PERSIAN_CHARS, but still has this issue

**Comment by incity** [comment]
![image](https://user-images.githubusercontent.com/7846605/109409919-8d427280-79d1-11eb-8dcf-df15ec66064b.png)

**Comment by kisvegabor** [comment]
Just guessing: what if you change `lv_txt_utf8_get_byte_id` like this:
```c
static uint32_t lv_txt_utf8_get_byte_id(const char * txt, uint32_t utf8_id)
{
    uint32_t i;
    uint32_t byte_cnt = 0;
    for(i = 0; i < utf8_id && txt[byte_cnt] != '\0'; i++) {    //CHANGED HERE
        uint8_t c_size = _lv_txt_encoded_size(&txt[byte_cnt]);
        byte_cnt += c_size > 0 ? c_size : 1;
    }

    return byte_cnt;
}
```

**Comment by incity** [comment]
> Just guessing: what if you change `lv_txt_utf8_get_byte_id` like this:
> 
> ```c
> static uint32_t lv_txt_utf8_get_byte_id(const char * txt, uint32_t utf8_id)
> {
>     uint32_t i;
>     uint32_t byte_cnt = 0;
>     for(i = 0; i < utf8_id && txt[byte_cnt] != '\0'; i++) {    //CHANGED HERE
>         uint8_t c_size = _lv_txt_encoded_size(&txt[byte_cnt]);
>         byte_cnt += c_size > 0 ? c_size : 1;
>     }
> 
>     return byte_cnt;
> }
> ```

use this can fix the problem

but im curious that why you don't have this problem?? 
what is your gcc version?? (mine is gcc version 5.4.0 20160609 )

**Comment by kisvegabor** [comment]
I've applied the fix.

I have this version of GCC: (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0
