### ISSUE TITLE
[Question] Is it possible to use the pc eclipse project to simulate monochrome displays?

### ISSUE THREAD

**Issue by C47D** [lvgl/lvgl#209]
Hi,

I'm getting familiar with this project, i plan to use it mostly with monochrome displays, right now i'm waiting for the refactor of the drivers sub project so meanwhile i would like to test what can i achieve with this project on monochrome displays.

I'm not familiar with SDL, so: is it possible to simulate monochrome displays with it?

Regards,
Carlos

**Comment by C47D** [comment]
Well, it was easy to do it, this is the early result of my test project:
![imagen](https://user-images.githubusercontent.com/11037705/38772103-b1b372b4-3ff4-11e8-9324-503230fcd47e.png)

I only changed to 1 (before it was 24) the following line on the lv_config header:
#define LV_COLOR_DEPTH    1

Now i need to get familiar with the lib (buttons style first) 😄 , sorry for the noise.

Regards,
Carlos

**Comment by kisvegabor** [comment]
Hi,

You were doing it correctly. `LV_COLOR_DEPTH    1` is the easiest way to simulate monochrome display on PC. :)
