### ISSUE TITLE
Object group management (buttons + btnmatrix)

### ISSUE THREAD

**Issue by imprego** [lvgl/lvgl#2099]
Is it possible to control the focus of a btnmatrix together with other objects (for example, buttons) in one group, wich controlled by encoder?
I added to the group one btnmatrix and 2-3 buttons. With the encoder configured for this group, I normally switch between the buttons, but the individual buttons of the btnmatrix do not switch. 
The code is smth like this:
`lv_obj_t *screen = lv_cont_create(NULL, NULL);
lv_cont_set_layout(screen, LV_LAYOUT_ROW_MID);

lv_obj_t *navigation = lv_btnmatrix_create(screen, NULL);
lv_btnmatrix_set_map(navigation, {LV_SYMBOL_CLOSE, LV_SYMBOL_HOME, ""});
lv_obj_set_size(navigation, 100, 100);
lv_group_add_obj(encoderGroup, navigation);

for(int i = 0; i < 4; ++i)
{
	lv_obj_t *btn = lv_btn_create(cont, NULL);
	lv_obj_set_size(btn, 100, 100);
	lv_group_add_obj(encoderGroup, btn);
}`

**Comment by kisvegabor** [comment]
You need to "click the encoder" on the button matrix to change to "edit mode" in which individual buttons can be selected.
See the more [here](https://docs.lvgl.io/latest/en/html/porting/indev.html#encoder).

---
We use GitHub Issues for development-related discussions.

Please ask your question in the [Forum](https://forum.lvgl.io) to make it visible for a larger community. You can simply log in with your GitHub account.
