### ISSUE TITLE
label anim speed 1, jumping whole screen length

### ISSUE THREAD

**Issue by sdalu** [lvgl/lvgl#210]
Using `lv_label_set_anim_speed(label_alert, 1)`, I've got a strange behaviour: the screen jump from the first whole screen to the last whole screen about every 15s. For value greater than 1 behaviour follows documentation. 

Trying with another font, I need to increase anim speed to 16, to find again the standard behavious

Also when scrolling long text, a pause seems present at both end, but I haven't found a function to set this wait time.

**Comment by kisvegabor** [comment]
Hi,

Can you send a code example to reproduce the issue?

You are correct, now there is pause break after both sides.   We had a discussion about it here: #188
In the next release there will be a function to adjust it.

**Comment by sdalu** [comment]
That's the code I use
~~~c
    lv_obj_t *root = lv_scr_act();
    lv_obj_clean(root);

    lv_obj_t *label_alert = lv_label_create(root, NULL);
    lv_label_set_style(label_alert, &style_unscii_16);
    lv_label_set_long_mode(label_alert, LV_LABEL_LONG_SCROLL);
    lv_label_set_anim_speed(label_alert, 16);
    lv_label_set_text(label_alert,  "guierguier erer gr oeihf idgui regui ergh erugheruihgurhgue g heru ghuerh guer kh!");
    lv_obj_align(label_alert, root, LV_ALIGN_CENTER, 0, 0);
~~~

**Comment by kisvegabor** [comment]
Thank you!

I fixed it in `beta` branch. There was an overflow in an animation related function. Now the the max animation time is limited to 65,535 ms =~ 65 sec.
