### ISSUE TITLE
Use  Littlevgl  lib to display rgb888 3 Bytes

### ISSUE THREAD

**Issue by libingqiu** [lvgl/lvgl#211]
Hi, I ported Littlevgl lib to New  MCU arch, and now I want to display a rgb888 picture. My AMOLED driver IC only supports  three bytes of rgb888, but the Littlevgl lib request 4 bytes for RGB888,  So  can I modify Littlevgl lib code to support rgb888 3 bytes ?

**Comment by kisvegabor** [comment]
I see. Then I see two options:
1. Is it possible to use 16 bit colors? If yes then it could solve the issue at the cost of a minor quality loss (depending on GUI design).
2. If you are not using DMA to automate the flushing then you can just send the bytes you need:
```c
    uint32_t i;
    uint8_t * color_buf_u8;
    for(i = 0; i < area_size; i++) {
        color_buf_u8 = color_p;
        qspi_send(*(color_buf_u8 + 0));
        qspi_send(*(color_buf_u8 + 1));
        qspi_send(*(color_buf_u8 + 2));
    }
```
