### ISSUE TITLE
lv_label_set_align() documentation

### ISSUE THREAD

**Issue by wek3** [lvgl/lvgl#2110]
https://github.com/lvgl/lvgl/blob/2618326f24bf0ff3e4c00cd4076f9fe8568c3483/src/lv_widgets/lv_label.h#L158 - probably should be one of the LV_LABEL_ALIGN_... enum

**Comment by kisvegabor** [comment]
Fixed here https://github.com/lvgl/lvgl/commit/b8b66c6929bda8e19d4d4488326efd162ea72bfa
Thanks!
