### ISSUE TITLE
Is the lv_chart can change dotted line color?

### ISSUE THREAD

**Issue by acer1204** [lvgl/lvgl#2118]
my version is 7.8.1.
I can use style to change line chart line color.
Is the lv_chart can change dotted line color?
[problem](https://www.dropbox.com/s/c4bc0bs5d6rxkpj/FF.png?dl=0)
i try create a limit line in line line chart by use dotted line...
it this dotted line can change color?

**Comment by kisvegabor** [comment]
Do you mean changing the color only of the uppermost line?

**Comment by turoksama** [comment]
Here I have a solution instead: Use cursor as limiting line you mentioned.
You can change the color by:
```
lv_chart_cursor_t *limit_line= lv_chart_add_cursor(chart, COLOR, LV_CHART_CURSOR_LEFT);
```
What do you think?

**Comment by acer1204** [comment]
> Do you mean changing the color only of the uppermost line?

yes

**Comment by kisvegabor** [comment]
In v8 you can modify the style of any division line. See this example: https://github.com/lvgl/lvgl/blob/master/examples/widgets/chart/lv_example_chart_2.c

I think it solves the issue so I close it now.
