### ISSUE TITLE
[Question]Is there a quantity restriction for 【lv_list_add】 function?

### ISSUE THREAD

**Issue by qwert1213131** [lvgl/lvgl#212]
@kisvegabor 
I want to add the filename in SD to list, but the number is limited. How do I deal with it?
Thank you！

**Comment by kisvegabor** [comment]
Hi,

The quantity is limited only by the memory. You should increase LV_MEM_SIZE in lv_conf.h.

How much list elements do you need approximately?

**Comment by qwert1213131** [comment]
I add 70 list items,it fails.
I will change the  LV_MEM_SIZE,and try it
Thanks

**Comment by qwert1213131** [comment]
@kisvegabor 
yes，I increase the LV_MEM_SIZE,it succeeded!
Thans!

**Comment by kisvegabor** [comment]
Great! :)
