### ISSUE TITLE
Clear a list

### ISSUE THREAD

**Issue by shlsyc** [lvgl/lvgl#213]
Is that any way to clear a list? I've found in  Issues; But won't work

**Comment by kisvegabor** [comment]
Hi,

We added an update to `dev-5.2` where `lv_page_clean` was introduced.

Is it working for you?

**Comment by shlsyc** [comment]
Thank you,I will test it

**Comment by kisvegabor** [comment]
As it is supported in `dev-5.2` I close this issue.
If you something it's not working properly feel free to comment here and reopen the issue.
