### ISSUE TITLE
littlev task locks?

### ISSUE THREAD

**Issue by 8bit-meiko** [lvgl/lvgl#215]
Just wondering, does the lvgl task have locks (semaphores/mutexes)?

Looking at the code, I assume not. 

Would be nice to have for io port busy flags and wait for other tasks to complete

**Comment by kisvegabor** [comment]
Hi,

If you mean by semaphore:
1. Lock a task if the semaphore is taken
2. Stop the task running
3. Continue running from the "lock" when the semaphore become free

then it could be already a full featured OS. The `lv_task` system is very light weighted and can only call functions periodically but call the higher priority functions earlier.
If you need so sophisticated management I can suggest use e.g. FreeRTOS. (LittlevGL can be integrated easily)

But if you mean: Check the semaphore and just return if it is taken, then it is possible to provide an API for it.

**Comment by kisvegabor** [comment]
As there wasn't activity here for months I close this issue.
If you have a similar question feel free to comment here and reopen the issue!
