### ISSUE TITLE
lvgl label long mode(LV_LABEL_LONG_DOT) bug

### ISSUE THREAD

**Issue by FlyLu** [lvgl/lvgl#2150]
### Perform all steps below and tick them with [x]
- [x] Check the related part of the [Documentation](https://docs.lvgl.io/)
- [x] Update lvgl to the latest version
- [x] Reproduce the issue in a [Simulator](https://docs.lvgl.io/latest/en/html/get-started/pc-simulator.html)

### Describe the bug

![DeepinScreenshot_select-area_20210320164508](https://user-images.githubusercontent.com/10245147/111864492-272b8880-899c-11eb-87e2-29a99646a7c4.png)

How can I fix this isssue

### To Reproduce

```C
void lv_label_test(void)
{
    lv_obj_t *label = lv_label_create(lv_scr_act(), NULL);

    char text[] = "l ongmodetest";

    lv_label_set_long_mode(label, LV_LABEL_LONG_DOT);
    lv_obj_set_size(label, 100, 20);
    lv_label_set_text(label, text);
}
```

### Expected behavior

l ongmod...

**Comment by hnsqlisai** [comment]
I met same problem

**Comment by embeddedt** [comment]
Which version are you using: 7.11.0 or 8.0 prerelease?

Try setting the text before changing the long mode and size.

**Comment by FlyLu** [comment]
> Which version are you using: 7.11.0 or 8.0 prerelease?
> 
> Try setting the text before changing the long mode and size.

Hi， version 7.7.2 (info "dev")，**lv_sim_vscode_sdl** project

I tried what you said

![DeepinScreenshot_select-area_20210322171041](https://user-images.githubusercontent.com/10245147/111966371-ce8df400-8b31-11eb-90b1-369c96fbc2a1.png)

**Comment by kisvegabor** [comment]
It happens below the "DOT" works like this:
1. LVGL uses the current width of the label the "calculates" the lines the text with line wrapping 
2. Checks which letter is on the x2,y2 coordinate of the label
3. Trun 3 characters into dots from the found letter.

Illustration (`|` and `-` shows the size of the label):
```
--------------
| hello this |
| is a long  |  
--------------
| text
```

turns into:
```
--------------
| hello this |
| is a l...  | 
--------------
```
In your case:
```
--------
| l    |
--------
| modet|
| est  |
```
turns into:
```
--------
| l... |
--------
```

To handle this, it would require a tricky line wrapping algorithm: wrap normally, except in the last line where there should be no wrapping.

**Comment by FlyLu** [comment]
@kisvegabor Thank you for your reply

I am a little confused, why the following string display is expected

```C
char text[] = "l ong mode test";

lvgl show:  l ong mode...
```

![DeepinScreenshot_select-area_20210324213046](https://user-images.githubusercontent.com/10245147/112319193-c7f5ad00-8ce8-11eb-86a6-4830f710a781.png)

**Comment by embeddedt** [comment]
You're setting the label width to 100px; I suspect this is not wide enough for that string to fit.

**Comment by kisvegabor** [comment]
Unfortunately, I can't imagine a simple fix for it at this moment so I close this issue for now. :slightly_frowning_face:
