### ISSUE TITLE
Remove copy parameter from all create functions

### ISSUE THREAD

**Issue by xiaoxiang781216** [lvgl/lvgl#2155]
### Introduce the problem

The copy parameter is not working yet in the create functions for the current mainline. And the community agree to drop this argument in v8 release, instead to v9.

### Suggested solution

So let's remove this argument now.

**Comment by kisvegabor** [comment]
> And the community agree to drop this argument in v8 release, instead to v9.

@mair, are you ok with this approach?

**Comment by Mair** [comment]
@xiaoxiang781216 and @kisvegabor If it needs to happen then OK but, there is going to be some cross over where the videos aren't going to make sense. We may need to pull the plug on the course until the videos are redone

**Comment by kisvegabor** [comment]
> We may need to pull the plug on the course until the videos are redone

Isn't it enough to inform the users that the videos are about v7?

**Comment by kisvegabor** [comment]
Done.

**Comment by Mair** [comment]
@kisvegabor 
> Isn't it enough to inform the users that the videos are about v7?

I suppose you're right. but I can imagine that once v8 is released people will hold off buying an outdated course

**Comment by kisvegabor** [comment]
Yes, maybe. But  I think it's still better than closing the academy at all.
