### ISSUE TITLE
Web site issue

### ISSUE THREAD

**Issue by DeonMarais64** [lvgl/lvgl#217]
Hi,
I am having a problem using the font converter on littlevgl.com

Once I have selected a .ttf file and made/selected all the settings and press "Convert", I get a blank web page. If after that I try to open up any page at littlevgl.com, I get the following error message on the browser page,
"
Forbidden
You don't have permission to access / on this server.
Additionally, a 403 Forbidden error was encountered while trying to use an ErrorDocument to handle the request.
"
This error then persists until I try connecting to littlevgl.com after resetting my ADSL line (IE, new IP address I am guessing). However once I try to use the font converter again am back to square one.

I have tried using both firefox as well as MS Edge with the same result.

I would appreciate any assistance you are willing to offer.

If I should be reporting this somewhere else, then I apologise.

**Comment by kisvegabor** [comment]
Hi,

Thank you for reporting the issue.
Can you create a screen shoot about your settings in the font converter and also send you TTF file to test it?

Thank you in advance!

**Comment by DeonMarais64** [comment]
![image](https://user-images.githubusercontent.com/1963675/38967942-a2a2fdec-4389-11e8-9829-5913de634e82.png)

Thanks for your response, 
I obtained the .ttf file from 
https://www.dafont.com/digital-7.font?text=0123456789&psize=l

Also I have tried various settings/options on the dialog, all with he same result.

Could you possibly provide an offline version of the utility ?

**Comment by kisvegabor** [comment]
Thank you! I will examine it!

The offline version of the scripts are here: https://github.com/littlevgl/lv_utils
I hope it helps!

**Comment by kisvegabor** [comment]
Hi,

Sorry for the late answer. 
Finally I figured it out! The TTF file was suspicious for an anti-virus tool of the server.
Now it works!
