### ISSUE TITLE
line width is 0 by default for widget line

### ISSUE THREAD

**Issue by ZhaoQiang-b45475** [lvgl/lvgl#2177]
### Describe the bug

Hi,
The default line width of line is 0, so if user create a line and don't set line width,
the widget will not be shown which will make them confused.

### To Reproduce

lv_obj_t * line = lv_line_create(lv_scr_act(), NULL);
static lv_point_t screen_line_shdr6jeo[] ={{0,0},{60,60}};
lv_line_set_points(line,screen_line_shdr6jeo,2);
int lineWidth = lv_obj_get_style_line_width(line, LV_LINE_PART_MAIN);
printf("line width by default is %d\n", lineWidth);

**Comment by kisvegabor** [comment]
Do you use v7 or v8 from `master`?

**Comment by ZhaoQiang-b45475** [comment]
Hi Kisvegabor,
I am using tag v7.11.0

**Comment by kisvegabor** [comment]
Thanks, fixed here: 30251017

**Comment by kisvegabor** [comment]
As the issue should be fixed I close it.

If it's still not working as expected please comment here and reopen the issue.
