### ISSUE TITLE
Margin and Padding Documentation is confusing

### ISSUE THREAD

**Issue by cebrax** [lvgl/lvgl#2178]
### Bug Description

_The documentation, API documentation and code comments for "lv_obj_set_width_margin", "lv_obj_set_height_margin", "lv_obj_set_width_fit" and "lv_obj_set_height_fit" are not matching._

### **In the documentation page [https://docs.lvgl.io/latest/en/html/widgets/obj.html](https://docs.lvgl.io/latest/en/html/widgets/obj.html):**

![m](https://user-images.githubusercontent.com/1615524/113106390-6616d500-920b-11eb-9e60-288590e23e07.png)

![p](https://user-images.githubusercontent.com/1615524/113106398-6a42f280-920b-11eb-8d8b-836395e2ccd9.png)

**In summary they are explained as:**
```
new_width = left_margin + object_width + right_margin
new_width = left_pad + object_width + right_pad
```

### **However, in code lv_core\lv_obj.c:**

line 939: ``The object width will be obj_w = w - margin_left - margin_right``
line 953: ``The object height will be obj_h = h - margin_top - margin_bottom``

### **And also in API documentation:**

![api](https://user-images.githubusercontent.com/1615524/113107085-27354f00-920c-11eb-8f0d-c5f9a2c27e12.png)

LVGL version: 

```
/***************************
 * CURRENT VERSION OF LVGL
 ***************************/
#define LVGL_VERSION_MAJOR 7
#define LVGL_VERSION_MINOR 11
#define LVGL_VERSION_PATCH 0
#define LVGL_VERSION_INFO ""
```

**Comment by kisvegabor** [comment]
It really sounds complicated but looks correct.

Form:
> Styles can add Margin to the objects. Margin tells that "I want this space around me". To set width or height reduced by the margin lv_obj_set_width_margin(obj, new_width) or lv_obj_set_height_margin(obj, new_height). In more exact way: new_width = left_margin + object_width + right_margin.
![image](https://user-images.githubusercontent.com/7599318/113409194-0ce8a600-93b1-11eb-83eb-747f8d5aafc3.png)

```
new_width = left_margin + object_width + right_margin

Can be rearranged as:
object_width = new_width - left_margin - right_margin;
```
![image](https://user-images.githubusercontent.com/7599318/113409149-f9d5d600-93b0-11eb-8dcb-d219fa0eeed8.png)
Tells teh same:
```
obj_w = w - margin_left - margin_right
```

The difference is one tells how the `object_width` is calculated, and the other tells how the width you are set is composed.

**Comment by cebrax** [comment]
Oh, I see that now.. But shouldn't this be consistent across different documentation sources?

**Comment by kisvegabor** [comment]
I agree it'd be better to follow the same way of thinking in both places.
Could you send a Pull request with to `widgets/obj.html`?

**Comment by embeddedt** [comment]
@kisvegabor I haven't disabled the v7 build script yet so it will be necessary to update the Markdown files.
