### ISSUE TITLE
Change Mbox btn size

### ISSUE THREAD

**Issue by Moo2017** [lvgl/lvgl#218]
Hi ,
I was wondering how I can change the mbox btn size? using control character I am able to adjust btn width related to the other btns but I need to set my desired width.

**Comment by Moo2017** [comment]
@kisvegabor Thank you but I need to change the button width and also it comes from text width. Assume that I want to display "Message sent successfully" and add one one confirmation "OK" button , the width of confirmation button would be quite big and I like to make it smaller. Also same in Button Matrix , I don't know how change the Button width individually ( not related to the other buttons in the row)

**Comment by kisvegabor** [comment]
You can do it with a trick by adding hidden buttons. (\21x control byte)

**Comment by Moo2017** [comment]
@kisvegabor Thank you good idea!

**Comment by Moo2017** [comment]
@kisvegabor The problem using left and right key , hidden key also is selected and seems that cursor goes beyond the keys.

**Comment by kisvegabor** [comment]
Yes, really it also "selects" the hidden buttons which seems to be a bug or at least not intended.

Button matrix supports only relative width adjusting. 

Can you send a simple sketch about the desired result? Likely it can be reached with the Button matrix.

**Comment by Moo2017** [comment]
I want to have a message box with a confirmation btn. If I use mbox and add a btn to mbox , btn width would be as big as mbox width whereas I am looking for something similar to the following picture which I have used button  object so I was able to change width and height independently. 
![temp](https://user-images.githubusercontent.com/34062463/40236128-7ea34534-5a7a-11e8-90fe-d96c3a292eb7.jpg)

**Comment by kisvegabor** [comment]
I see. To reach this you can modify the `LV_MBOX_STYLE_BTN_BG`

```c
	static lv_style_t mbox_btns_bg;
	lv_style_copy(&mbox_btns_bg, &lv_style_plain_color);
	mbox_btns_bg.body.padding.hor = 50;

	const char * btns_str[] = {"Ok", ""};
	lv_obj_t * mb = lv_mbox_create(lv_scr_act(), NULL);
	lv_mbox_add_btns(mb, btns_str, NULL);
	lv_mbox_set_style(mb, LV_MBOX_STYLE_BTN_BG, &mbox_btns_bg);
```

I intentionally used a non-transparent style to see what happens. 
![image](https://user-images.githubusercontent.com/7599318/40239591-c247717a-5ab6-11e8-9c71-c111428f9cfb.png)

**Comment by Moo2017** [comment]
Oh great, thanks!

**Comment by Moo2017** [comment]
I have some problem to use control character. For example if I want to have 3 buttons as "Send", "Attach", "Cancel" in the mbox, what would be the best control character for each ( I am using lv_font_dejavu_30 and with this font size the button's text is out of the box and I couldn't adjust it)  ? I don't understand this part in the document and the provided example: "bit 7..6 Button relative width in the row  (1..7). " and then in the example you have this "The octal number always starts with 2 (bit 7..6)" .

**Comment by kisvegabor** [comment]
I checked the documentation and it was mistyped, sorry. I corrected it. https://littlevgl.com/object-types/button-matrix-lv_btnm

So if the control character is in octal format (`\xxx` in C) then it must start with `\2xx`.
By default all buttons have the width of "1 unit". But with the last number in the control byte you can modify it. E.g.  3  unit: `\2x3`. It will make the button 3 time wider the the others. It always proportional so doesn't matter how much button you have in row the relative width will remain. 
  
Here is an example:
```c
    static const char * btns[] = {"\203Triple","\202Double","Simple",""};
    lv_obj_t * mb = lv_mbox_create(lv_scr_act(), NULL);
    lv_mbox_add_btns(mb, btns, NULL);
    lv_obj_set_width(mb, 300);
    lv_obj_align(mb, NULL, LV_ALIGN_CENTER, 0, 0);
```
![image](https://user-images.githubusercontent.com/7599318/41117690-073b10d4-6a8e-11e8-8568-219045906984.png)

**Comment by Moo2017** [comment]
Hi, thank you very much. This issue can be closed too.

**Comment by kisvegabor** [comment]
Your welcome!
