### ISSUE TITLE
The style function names are too long

### ISSUE THREAD

**Issue by guoweilkd** [lvgl/lvgl#2182]
The style function names are too long,It's not easy to use.can we simplify it?
eg:lv_obj_get_style_pad_bottom() -> lv_gs_pad_boottom()

and Parameter LV_PART_MAIN is used frequently, Can we wrap it up again?

**Comment by embeddedt** [comment]
@guoweilkd The name is still quite long, but the parameters have changed, so you no longer need to specify `LV_PART_MAIN`. See @kisvegabor's comment [here](https://github.com/lvgl/lvgl/issues/2144#issuecomment-811296449).
