### ISSUE TITLE
Linemeter - rectangle width setting

### ISSUE THREAD

**Issue by lollopes** [lvgl/lvgl#2183]
Would it be possible to change the width of the rectangle in the linemeter ? I am able to change de width only for the animation part but not for when a value is not being set.

**Comment by kisvegabor** [comment]
Which rectangle do you mean? Please send an image and mark the rectangle.

**Comment by lollopes** [comment]
Hi Gabor, 

The red lines you can see are created during the animation when the set_value method is called. I have done this by applying a style with a line_width of 2 to the linemeter. Nevertheless, it only changes it when the value is set but not for the default status. In other words, in the picture below I would like to have the grey rectangle as small as the red lines. 

![snap](https://user-images.githubusercontent.com/46981565/113278475-41416100-92e2-11eb-9eb0-10cd8a6a46db.png)

Thanks for the fast reply

**Comment by kisvegabor** [comment]
You can do it with 
```c
    lv_obj_set_style_local_scale_end_line_width(lmeter, LV_LINEMETER_PART_MAIN, LV_STATE_DEFAULT, 1);
```

Or 
```c
    lv_style_set_scale_end_line_width(&style, LV_STATE_DEFAULT, 1);
```

**Comment by lollopes** [comment]
That's perfect. I guess you can close the issue. Thank you for your time

**Comment by kisvegabor** [comment]
You are welcome :)
