### ISSUE TITLE
lv_linemeter don't show value 0 correctly

### ISSUE THREAD

**Issue by asypost** [lvgl/lvgl#2184]
### Perform all steps below and tick them with [x]
- [x] Check the related part of the [Documentation](https://docs.lvgl.io/)
- [x] Update lvgl to the latest version v7.11.0
- [x] Reproduce the issue in a [Simulator](https://docs.lvgl.io/latest/en/html/get-started/pc-simulator.html)

### Describe the bug

lv_linemeter don't show value 0 correctly.
![image](https://user-images.githubusercontent.com/1658213/113276562-84b3c380-9312-11eb-9b0c-f3458b5d6f10.png)
you can see a  block on the left bottom which should not be there. 

### To Reproduce

lv_conf.h
```c
#define LV_HOR_RES_MAX          (128)
#define LV_VER_RES_MAX          (64)
#define LV_COLOR_DEPTH     1
```

main.c
```c
meter = lv_linemeter_create(lv_scr_act(), NULL);
lv_obj_set_width_fit(meter, LV_HOR_RES_MAX);
lv_obj_set_height(meter, LV_VER_RES_MAX - 18);
lv_linemeter_set_scale(meter, 142, 12);
lv_linemeter_set_range(meter, 0, 800);
lv_obj_set_y(meter, -15);
lv_obj_set_x(meter, 13);
lv_linemeter_set_value(meter, 0);
```

### Expected behavior

The meter should not show any block  when the value set to zero.

### Screenshots or video
See the picture provided up.

**Comment by kisvegabor** [comment]
I've fixed it in `release/v7`

**Comment by asypost** [comment]
But I'm using v7.11.0

**Comment by kisvegabor** [comment]
You can safely update lvgl from relase/v7. There are only a few bug fixes.

**Comment by asypost** [comment]
OK,thanks.I was confused by the meaning of release/v7,now I know that is a branch not a RELEASE in github releases page.

**Comment by kisvegabor** [comment]
Just to be sure, I meant this branch: https://github.com/lvgl/lvgl/tree/release/v7

**Comment by asypost** [comment]
> Just to be sure, I meant this branch: https://github.com/lvgl/lvgl/tree/release/v7

Thanks a lot.

**Comment by asypost** [comment]
BTW,when will it be available as stable release?

**Comment by kisvegabor** [comment]
See here https://github.com/lvgl/lvgl/issues/2144#issuecomment-822327936
