### ISSUE TITLE
png not rendering properly

### ISSUE THREAD

**Issue by lollopes** [lvgl/lvgl#2188]
Hi, 

I have been using https://lvgl.io/tools/imageconverter to conver a png image to a .c file. 

The image I want to load is shown below:

![front_arrow (1)](https://user-images.githubusercontent.com/46981565/113732417-db961000-96f9-11eb-93b4-04574a2d687f.png)

When I load the image in my c file I end up with the following result 

![result_arrow](https://user-images.githubusercontent.com/46981565/113732495-ef417680-96f9-11eb-897d-8900af4b6730.png)

Do you have any suggestions of why this is happening ?

**Comment by embeddedt** [comment]
The PHP converter currently in use on the website doesn't handle indexed PNGs properly. Converting with this converter should work: https://embeddedt.github.io/lv_img_conv/

**Comment by kisvegabor** [comment]
@embeddedt 
What's the current state of your converter? It seems only the binary format is missing.
Does dithering work?

**Comment by embeddedt** [comment]
Everything (including dithering) should be working, except for binary support. At the moment there are a number of assumptions that the output is going to be to a C file, so I need to refactor things a bit for binary output to work (haven't had a chance to yet).

**Comment by lollopes** [comment]
Hi, I used the converter suggested by embeddedt but nothing changed at first. I was trying to render a black and white arrow as you could see from the start of the thread, I managed to produce the right .c file by selecting "indexed 2 colors" for the color format and by allowing dithering. I believe we can close the issue. 

Thank you for your fast answers and support.
