### ISSUE TITLE
Label type with bold character 

### ISSUE THREAD

**Issue by lollopes** [lvgl/lvgl#2189]
Is it possible to have the full text within a label in a bold format ? 

Thanks in advance.

**Comment by embeddedt** [comment]
Yes, but you will need to convert a font which is bold. The default fonts just have a normal weight.

----------------------
We use GitHub issues for development related discussions.
Please use the [forum](https://forum.littlevgl.com/) to ask questions.

It's possible to sign in to the forum with your GitHub account... you don't need to make a separate account.
