### ISSUE TITLE
Question about release schedule

### ISSUE THREAD

**Issue by C47D** [lvgl/lvgl#219]
Hi,

I was wondering what's your release schedule, i mean, do you release a new version once every month? or when you finish a important improvement?
When do you consider the release a major versions?

Thanks for your impressive work in the library :)

**Comment by kisvegabor** [comment]
Hi,

I use the "milestone" feature of GitHub keep track with the planned features.  https://github.com/littlevgl/lvgl/milestones
Once they are ready the new version will be released.

However for bugfix releases I don't maintain such a "list" but release the minor version if there are several updates. It should happen soon.

As the major versions can affect the API I try to release them as rarely as possible. And for this reason I would like to be sure as much API related thing is done in them as possible. 
To answer you question there in no planned release data for a major version now. Still collecting the ideas :)
