### ISSUE TITLE
Linux framebuffer sometime show part of blue background

### ISSUE THREAD

**Issue by choujayyl** [lvgl/lvgl#2193]
### Perform all steps below and tick them with [x]
- [x] Check the related part of the [Documentation](https://docs.lvgl.io/)
- [x] Update lvgl to the latest version
- [ ] Reproduce the issue in a [Simulator](https://docs.lvgl.io/latest/en/html/get-started/pc-simulator.html)

### Describe the bug

I use lvgl7.11 with linux framebuffer.But sometimes the screen display part of blue backgrond in place not refresh realtime.

### To Reproduce
I dont konw,but when exit app,it sometime show full blue backgrond.

### Expected behavior

I dont konw,but when exit app,it sometime show full blue backgrond.
### Screenshots or video

![IMG_20210409_090938](https://user-images.githubusercontent.com/28703422/114346068-657c2800-9b95-11eb-8883-64fbd7cc45c9.jpg)

**Comment by embeddedt** [comment]
Please try with 7.11; 7.0 is old and has a number of bugs which have since been fixed.

**Comment by choujayyl** [comment]
> Please try with 7.11; 7.0 is old and has a number of bugs which have since been fixed.

Sorry,I just tried with 7.11(the latest release).The above is wrong.

**Comment by kisvegabor** [comment]
It seems like another app (e.g. window manager) is also using the frame buffer. LVGL draws the screen, the other app overwrites it with blue, LVGL renders the changed areas and they remain visible.

**Comment by choujayyl** [comment]
> It seems like another app (e.g. window manager) is also using the frame buffer. LVGL draws the screen, the other app overwrites it with blue, LVGL renders the changed areas and they remain visible.

Yes,It is linux kernel virtual terminal sometime clear the screen.You need to changed it mode to KD_GRAPHICS that only LVGL can use it.
So close issue.
