### ISSUE TITLE
How to create a windows without title?

### ISSUE THREAD

**Issue by mokemars** [lvgl/lvgl#220]
I want to creat a window without title.any body can help me?

**Comment by qwert1213131** [comment]
You can use lv_page easily.

**Comment by mokemars** [comment]
Thanks for you!
i create two windows in the project.if i use page instead of windows.when open the second page in button action,the second page does not cover the first page.the first page object is also in the second page!

**Comment by qwert1213131** [comment]
could you show the source code?

**Comment by kisvegabor** [comment]
As the solution of @qwert1213131 (use ``lv_page) should work I close this issue.

@mokemars 
If the issue is not solved yet, please post your relevant code snippet here.
