### ISSUE TITLE
lv_disp_drv_init  calling error in lv_canvas_draw_rect function

### ISSUE THREAD

**Issue by linuxdrv** [lvgl/lvgl#2204]
hi all,

in **lv_canvas_draw_rect** function (_lv_canvas.c_), after calling   
    **lv_memset_00(&disp, sizeof(lv_disp_t));**
disp.driver = NULL;
   then calling **lv_disp_drv_init(disp.driver);** will cause an error.
same issues in function **lv_canvas_draw_text**, **lv_canvas_draw_img**,**lv_canvas_draw_line**,**lv_canvas_draw_polygon** and **lv_canvas_draw_arc**.

Cheers,

### Perform all steps below and tick them with [x]
- [x] Check the related part of the [Documentation](https://docs.lvgl.io/)
- [x] Update lvgl to the latest version
- [x] Reproduce the issue in a [Simulator](https://docs.lvgl.io/latest/en/html/get-started/pc-simulator.html)

**Comment by embeddedt** [comment]
Oops; that looks like an oversight from the API change in v8. Thanks for reporting!

**Comment by embeddedt** [comment]
This should be fixed now.
