### ISSUE TITLE
lvgl built-in memory allocator becomes very slow after lots of lv_obj create and destory.

### ISSUE THREAD

**Issue by incity** [lvgl/lvgl#2206]
In my lv_conf.h : 

`#define LV_MEM_CUSTOM      0`

when i use 0: use the built-in `lv_mem_alloc` and `lv_mem_free`. it will been very slow after i  repeatedly delete and create objects.

**Comment by xiaoxiang781216** [comment]
Do you use v8 or the old version?

**Comment by incity** [comment]
i use the latest version of release-v7

**Comment by xiaoxiang781216** [comment]
Ok, it's known issue and fixed in v8: https://github.com/lvgl/lvgl/pull/2129
you can either backport to v7 or upgrade to v8.
