### ISSUE TITLE
[v7]lv_tabview memory leak when set LV_TABVIEW_TAB_POS_RIGHT

### ISSUE THREAD

**Issue by incity** [lvgl/lvgl#2208]
LV_TABVIEW_TAB_POS_RIGHT lv_tabview has memory leak after object delete.(tab_name malloc at lv_tabview.c line226 is not been freed)

**Comment by kisvegabor** [comment]
Thanks, could you send a PR?

**Comment by kisvegabor** [comment]
Let's continue in https://github.com/lvgl/lvgl/pull/2223
