### ISSUE TITLE
Update for ESP32 v8.0

### ISSUE THREAD

**Issue by Miguel0101** [lvgl/lvgl#2209]
Update to version 8.0.0 compatible with ESP32.

**Comment by Miguel0101** [comment]
Will version 8.0 be compatible with ESP32?

**Comment by embeddedt** [comment]
There are no plans to drop support for any of the currently supported platforms, however, the ESP32 projects have not been updated yet, as 8.0 has not been officially released.

-------

Please do not post duplicate issues on multiple repositories unless necessary. Thanks!

**Comment by Miguel0101** [comment]
Ok, thanks.
