### ISSUE TITLE
a typo mistake of the comment in the lv_arc.h:84

### ISSUE THREAD

**Issue by CristXu** [lvgl/lvgl#2219]
### Perform all steps below and tick them with [x]
- [x ] Check the related part of the [Documentation](https://docs.lvgl.io/)
- [x ] Update lvgl to the latest version
- [x ] Reproduce the issue in a [Simulator](https://docs.lvgl.io/latest/en/html/get-started/pc-simulator.html)

### Describe the bug
Found a type mistake in lv_arch.h:84

### To Reproduce
Do not need

### Expected behavior
rectify the mistake

### Screenshots or video
![image](https://user-images.githubusercontent.com/49855018/115990477-04713d00-a5f6-11eb-91ac-11abd3437feb.png)

**Comment by embeddedt** [comment]
Thanks; I've just fixed it.
