### ISSUE TITLE
Recent changes in V8 break simulator

### ISSUE THREAD

**Issue by uraich** [lvgl/lvgl#2226]
### Perform all steps below and tick them with [x]
- [x ] Check the related part of the [Documentation](https://docs.lvgl.io/)
- [ x] Update lvgl to the latest version
- [x ] Reproduce the issue in a [Simulator](https://docs.lvgl.io/latest/en/html/get-started/pc-simulator.html)

### Describe the bug
change of parameters in
lv_img_create
lv_theme_default_init
break the simulator
Same is true for the change LV_COLOR_PALETTE_LIGHT_BLUE -> LV_PALETTE_LIGHT_BLUE 

### To Reproduce
Run the simulator with the newest V8 incarnation

**Comment by kisvegabor** [comment]
Probably I missed that conversation but v8 is already ported to the online MixroPython simulator? On https://sim.lvgl.io I see only v7 and v6.

**Comment by uraich** [comment]
Sorry, I expressed myself badly. I meant lv_sim_eclipse_sdl.

**Comment by kisvegabor** [comment]
I've just updated lv_sim_eclipse_sdl.

**Comment by uraich** [comment]
Thanks! Working fine again.
In order to translate the example programs from C to Python it is good to see the original C code in action.

**Comment by kisvegabor** [comment]
Great! :)
