### ISSUE TITLE
lv_example_get_started_2 not working

### ISSUE THREAD

**Issue by uraich** [lvgl/lvgl#2229]
### Perform all steps below and tick them with [x]
- [ x] Check the related part of the [Documentation](https://docs.lvgl.io/)
- [ x] Update lvgl to the latest version
- [ x] Reproduce the issue in a [Simulator](https://docs.lvgl.io/latest/en/html/get-started/pc-simulator.html)

### Describe the bug
 lv_obj_remove_style_all breaks the program

### To Reproduce
run lv_example_get_started_2 in  lv_sim_eclipse_sdl

### Expected behavior
Get 2 buttons. This works if  lv_obj_remove_style_all is commented

### Screenshots or video
with  lv_obj_remove_style_all
![image](https://user-images.githubusercontent.com/1673533/116533021-32e66500-a8e1-11eb-8a5b-f309e3bb5011.png)
without  lv_obj_remove_style_all
![image](https://user-images.githubusercontent.com/1673533/116533117-4b567f80-a8e1-11eb-8deb-6bf0376b4ad2.png)

**Comment by kisvegabor** [comment]
Thanks, fixed.

See the added comment for the explanation of the issue.

**Comment by uraich** [comment]
Ok, understood. Thanks! The Python version works correctly as well now.

**Comment by kisvegabor** [comment]
Great! 
It's awesome that you create the PYthon examples! :heart:
