### ISSUE TITLE
I cannot print images via SD Card with ESP32

### ISSUE THREAD

**Issue by Miguel0101** [lvgl/lvgl#2230]
When I use `lv_img_set_src(img, "/sd/image.png");` I received a "No data" error.

**Comment by embeddedt** [comment]
Which LVGL port are you using? Usually you also need to specify the drive letter in front of the path (e.g. `S:/sd/image.png`, but the drive letter depends on your specific platform).

**Comment by Miguel0101** [comment]
There, but it shows nothing.

**Comment by Miguel0101** [comment]
I tried to use lv_fs_if but to no avail.

**Comment by embeddedt** [comment]
There's still not enough information to help. Which project are you using (`lv_port_esp32`, something custom based on ESP-IDF, etc.)? Does it provide any info about what drive letter to use? Can you open the file with its API (bypassing LVGL)? Please provide more details.

**Comment by Miguel0101** [comment]
I don't use lv_port_esp32

**Comment by Miguel0101** [comment]
I don't use lv_port_esp32

**Comment by Miguel0101** [comment]
I use lvgl / lvgl 7.11.0

**Comment by Miguel0101** [comment]
> I don't use lv_port_esp32

Is that the problem?

**Comment by embeddedt** [comment]
I don't know. :slightly_smiling_face: Without knowing more information there is really not much I can help with, as the filesystem implementation is project-specific. LVGL defines the API but the actual behavior is almost entirely decided by whatever glue code you are using.

**Comment by Miguel0101** [comment]
I will try to use the port `lv_port esp32`

**Comment by Miguel0101** [comment]
I used a 200x150x16 image.

**Comment by Miguel0101** [comment]
RAM: 520 KB.
Flash: 4MB with Huge APP.

Library: lv_lib_png.

**Comment by embeddedt** [comment]
Can you enable logging and post the resulting log?

**Comment by Miguel0101** [comment]
> Can you enable logging and post the resulting log?

Yes, but I get "error 83: memory allocation failed"

**Comment by Miguel0101** [comment]
I don't believe it's memory.

**Comment by embeddedt** [comment]
I mean LVGL's logging (`LV_USE_LOG` in `lv_conf.h`).

**Comment by Miguel0101** [comment]
```
/*1: Enable the log module*/
#define LV_USE_LOG      1
#if LV_USE_LOG
/* How important log should be added:
 * LV_LOG_LEVEL_TRACE       A lot of logs to give detailed information
 * LV_LOG_LEVEL_INFO        Log important events
 * LV_LOG_LEVEL_WARN        Log if something unwanted happened but didn't cause a problem
 * LV_LOG_LEVEL_ERROR       Only critical issue, when the system may fail
 * LV_LOG_LEVEL_NONE        Do not log anything
 */
#  define LV_LOG_LEVEL    LV_LOG_LEVEL_ERROR

/* 1: Print the log with 'printf';
 * 0: user need to register a callback with `lv_log_register_print_cb`*/
#  define LV_LOG_PRINTF   1
#endif  /*LV_USE_LOG*/
```

**Comment by Miguel0101** [comment]
I'll compile

**Comment by Miguel0101** [comment]
```
error 83: memory allocation failed
WARNING: File: C:\Users\migue\OneDrive\Documentos\Arduino\libraries\lvgl\src\lv_draw\lv_img_cache.c
#128: _lv_img_cache_open: Image draw cannot open the image resource
WARNING: File: C:\Users\migue\OneDrive\Documentos\Arduino\libraries\lvgl\src\lv_draw\lv_draw_img.c
#88: lv_draw_img: Image draw error
```

**Comment by Miguel0101** [comment]
I received this LOG

**Comment by Miguel0101** [comment]
Sorry for the delay.

**Comment by Miguel0101** [comment]
I still think I'm missing something, but I don't know which one.

**Comment by Miguel0101** [comment]
> ```
> error 83: memory allocation failed
> WARNING: File: C:\Users\migue\OneDrive\Documentos\Arduino\libraries\lvgl\src\lv_draw\lv_img_cache.c
> #128: _lv_img_cache_open: Image draw cannot open the image resource
> WARNING: File: C:\Users\migue\OneDrive\Documentos\Arduino\libraries\lvgl\src\lv_draw\lv_draw_img.c
> #88: lv_draw_img: Image draw error
> ```

I think the stack is overflowing.

**Comment by Miguel0101** [comment]
How many kilobytes does the `lv_lib_png` library use?

**Comment by embeddedt** [comment]
Are you asking about stack or heap?

- Stack - typically 4-8KB is a good rule of thumb for most LVGL applications. You can always optimize later if you see that a portion is never touched.
- Heap - unfortunately lodepng needs at least as much RAM as the size of the PNG you're decoding. In your case that's 60K plus the overhead for decoding and LVGL, so perhaps try with a 96KB heap.

**Comment by Miguel0101** [comment]
> Are you asking about stack or heap?
> 
> * Stack - typically 4-8KB is a good rule of thumb for most LVGL applications. You can always optimize later if you see that a portion is never touched.
> * Heap - unfortunately lodepng needs at least as much RAM as the size of the PNG you're decoding. In your case that's 60K plus the overhead for decoding and LVGL, so perhaps try with a 96KB heap.

Okay, thanks.

**Comment by Miguel0101** [comment]
How to change the heap?

**Comment by embeddedt** [comment]
That will again depend on your target platform and configuration. If you are using LVGL's heap (`LV_MEM_CUSTOM == 0`), it can be adjusted by changing `LV_MEM_SIZE` in `lv_conf.h`.

**Comment by Miguel0101** [comment]
I used (`LV_MEM_CUSTOM = 1`)

**Comment by embeddedt** [comment]
You will have to look it up for your project then - `LV_MEM_CUSTOM == 1` means that LVGL is using your project's heap implementation, not its own.

**Comment by Miguel0101** [comment]
> You will have to look it up for your project then - `LV_MEM_CUSTOM == 1` means that LVGL is using your project's heap implementation, not its own.

I will change to (LV_MEM_CUSTOM = 0)

**Comment by Miguel0101** [comment]
`#  define LV_MEM_SIZE    (32U * 1024U)`

**Comment by Miguel0101** [comment]
> `# define LV_MEM_SIZE (32U * 1024U)`

Do I need to put more RAM?

**Comment by embeddedt** [comment]
The current heap size you have in there is 32K. That won't be big enough.

**Comment by Miguel0101** [comment]
> The current heap size you have in there is 32K. That won't be big enough.

Ok, I put # define LV_MEM_SIZE (64U * 1024U)

**Comment by Miguel0101** [comment]
Do I need to put more RAM?

**Comment by embeddedt** [comment]
I recommended trying 96K in my earlier post.

**Comment by Miguel0101** [comment]
Ok

**Comment by Miguel0101** [comment]
Oops, on compilation I got this error "```
c: /users/migue/appdata/local/arduino15/packages/esp32/tools/xtensa-esp32-elf-gcc/1.22.0-97-gc752ad5-5.2.0/bin/. ./lib/gcc/xtensa-esp32-elf/5.2.0/../../../../xtensa-esp32-elf/bin/ld.exe: C: \ Users \ migrue \ AppData \ Local \ Temp \ arduino_build_831633 / userPage.ino.elf section `.dram0.bss 'will not fit in region` dram0_0_seg'
c: /users/migue/appdata/local/arduino15/packages/esp32/tools/xtensa-esp32-elf-gcc/1.22.0-97-gc752ad5-5.2.0/bin /../ lib / gcc / xtensa- esp32-elf / 5.2.0 /../../../../ xtensa-esp32-elf / bin / ld.exe: DRAM segment data does not fit.
c: /users/migue/appdata/local/arduino15/packages/esp32/tools/xtensa-esp32-elf-gcc/1.22.0-97-gc752ad5-5.2.0/bin /../ lib / gcc / xtensa- esp32-elf / 5.2.0 /../../../../ xtensa-esp32-elf / bin / ld.exe: region `dram0_0_seg 'overflowed by 29224 bytes
collect2.exe: error: ld returned 1 exit status 
```"

**Comment by Miguel0101** [comment]
> Oops, on compilation I got this error "```
> c: /users/migue/appdata/local/arduino15/packages/esp32/tools/xtensa-esp32-elf-gcc/1.22.0-97-gc752ad5-5.2.0/bin/. ./lib/gcc/xtensa-esp32-elf/5.2.0/../../../../xtensa-esp32-elf/bin/ld.exe: C: \ Users \ migrue \ AppData \ Local \ Temp \ arduino_build_831633 / userPage.ino.elf section `.dram0.bss 'will not fit in region` dram0_0_seg'
> c: /users/migue/appdata/local/arduino15/packages/esp32/tools/xtensa-esp32-elf-gcc/1.22.0-97-gc752ad5-5.2.0/bin /../ lib / gcc / xtensa- esp32-elf / 5.2.0 /../../../../ xtensa-esp32-elf / bin / ld.exe: DRAM segment data does not fit.
> c: /users/migue/appdata/local/arduino15/packages/esp32/tools/xtensa-esp32-elf-gcc/1.22.0-97-gc752ad5-5.2.0/bin /../ lib / gcc / xtensa- esp32-elf / 5.2.0 /../../../../ xtensa-esp32-elf / bin / ld.exe: region `dram0_0_seg 'overflowed by 29224 bytes
> collect2.exe: error: ld returned 1 exit status

This means that ESP32 does not have enough memory.

**Comment by Miguel0101** [comment]
Even with 520 KB of RAM, ESP32 partitions use a lot of RAM.

**Comment by embeddedt** [comment]
Does it have a partition for its heap? You could reduce that since LVGL won't be needing it with LV_MEM_CUSTOM disabled.

**Comment by Miguel0101** [comment]
> Does it have a partition for its heap? You could reduce that since LVGL won't be needing it with LV_MEM_CUSTOM disabled.

Yes, it has a partition, but I am trying to shrink it. Thanks.

**Comment by Miguel0101** [comment]
I managed to reduce the ESP32 partition, compiled (and loaded) successfully, but still displays "No data".

**Comment by embeddedt** [comment]
Does the log show the same memory allocation error? If so, if you have a debugger, it would probably be worth stepping through `lv_img_design` (probably [this section](https://github.com/lvgl/lvgl/blob/e08ecffca94623727ef7a8d7ae9f620e15cf7784/src/lv_widgets/lv_img.c#L662-L716)).

**Comment by Miguel0101** [comment]
`#include <lvgl.h>
#include "lv_png.h"
#include <TFT_eSPI.h>
#include <TouchScreen.h>
#include <SD.h>

const int XP = 12, XM = 15, YP = 33, YM = 13;
const int TS_LEFT = 167, TS_RT = 927, TS_TOP = 988, TS_BOT = 105;

#define MINPRESSURE 1
#define MAXPRESSURE 1000

TouchScreen ts = TouchScreen(XP, YP, XM, YM, 300);
TSPoint tp;

TFT_eSPI tft = TFT_eSPI(); /* TFT instance */

static lv_disp_buf_t disp_buf;
static lv_color_t buf[LV_HOR_RES_MAX * 5];

LV_IMG_DECLARE(user_icon);

void my_log_cb(lv_log_level_t level, const char * file, uint32_t line, const char * fn_name, const char * dsc)
{
  /*Send the logs via serial port*/
  if(level == LV_LOG_LEVEL_ERROR) Serial.print("ERROR: ");
  if(level == LV_LOG_LEVEL_WARN)  Serial.print("WARNING: ");
  if(level == LV_LOG_LEVEL_INFO)  Serial.print("INFO: ");
  if(level == LV_LOG_LEVEL_TRACE) Serial.print("TRACE: ");

  Serial.print("File: ");
  Serial.println(file);

  char line_str[8];
  sprintf(line_str,"%d", line);
  Serial.print("#");
  Serial.print(line_str);

  Serial.print(": ");
  Serial.print(fn_name);
  Serial.print(": ");
  Serial.print(dsc);
  Serial.println("");
}

void my_print(lv_log_level_t level, const char * file, uint32_t line, const char * dsc)
{

  Serial.printf("%s@%d->%s\r\n", file, line, dsc);
  Serial.flush();
}

/* Display flushing */
void my_disp_flush(lv_disp_drv_t *disp, const lv_area_t *area, lv_color_t *color_p)
{
  uint64_t w = (area->x2 - area->x1 + 1);
  uint64_t h = (area->y2 - area->y1 + 1);

  tft.startWrite();
  tft.setAddrWindow(area->x1, area->y1, w, h);
  tft.pushColors(&color_p->full, w * h, true);
  tft.endWrite();

  lv_disp_flush_ready(disp);
}

/*Read the touchpad*/
bool my_touchpad_read(lv_indev_drv_t * indev_driver, lv_indev_data_t * data)
{
  uint64_t touchX, touchY;

  tp = ts.getPoint();

  pinMode(XM, OUTPUT);
  pinMode(YP, OUTPUT);

  if (tp.z > MINPRESSURE && tp.z < MAXPRESSURE) {
    touchX = map(tp.y, TS_TOP, TS_BOT, 0, tft.width());
    touchY = map(tp.x, TS_RT, TS_LEFT, 0, tft.height());

    if ((touchX) || (touchY))
    {
      data->state = LV_INDEV_STATE_PR;
      data->point.x = touchX;
      data->point.y = touchY;
    } else
    {
      data->point.x = touchX;
      data->point.y = touchY;
      data->state = LV_INDEV_STATE_REL;
    }
  }

  return 0;
}

void setup() {
  // put your setup code here, to run once:
  Serial.begin(115200); /* prepare for possible serial debug */

  lv_init();

  tft.init(); /* TFT init */
  tft.setRotation(1); /* Landscape orientation */

  if (!SD.begin()) {
    Serial.println("Error: SD Card");
  } else {
    Serial.println("Ok: SD Card");
  }

  lv_png_init();

  lv_log_register_print_cb(my_log_cb);

  lv_disp_buf_init(&disp_buf, buf, NULL, LV_HOR_RES_MAX * 5);

  /*Initialize the display*/
  lv_disp_drv_t disp_drv;
  lv_disp_drv_init(&disp_drv);
  disp_drv.hor_res = 480;
  disp_drv.ver_res = 320;
  disp_drv.flush_cb = my_disp_flush;
  disp_drv.buffer = &disp_buf;
  lv_disp_drv_register(&disp_drv);

  /*Initialize the (dummy) input device driver*/
  lv_indev_drv_t indev_drv;
  lv_indev_drv_init(&indev_drv);
  indev_drv.type = LV_INDEV_TYPE_POINTER;
  indev_drv.read_cb = my_touchpad_read;
  lv_indev_drv_register(&indev_drv);

  lv_main();
}

void loop() {
  // put your main code here, to run repeatedly:
  lv_task_handler();
}

static lv_obj_t * user_img_block, * user_name, * user_img, * pwd_ta, * kb;
const char * usr_name = "Miguel Magno";
const char * password = "Pontes.33";

static void lv_main() {
  user_img_block = lv_obj_create(lv_scr_act(), NULL);
  lv_obj_set_size(user_img_block, 100, 100);
  lv_obj_set_style_local_radius(user_img_block, LV_OBJ_PART_MAIN, LV_STATE_DEFAULT, LV_RADIUS_CIRCLE);
  lv_obj_align(user_img_block, NULL, LV_ALIGN_CENTER, 0, -45);

  user_img = lv_img_create(lv_scr_act(), NULL);
  lv_img_set_src(user_img, "/sd/image.png");
  lv_obj_align(user_img, NULL, LV_ALIGN_CENTER, 0, 0);

  user_name = lv_label_create(lv_scr_act(), NULL);
  lv_label_set_text(user_name, usr_name);
  lv_obj_set_style_local_text_font(user_name, LV_OBJ_PART_MAIN, LV_STATE_DEFAULT, &lv_font_montserrat_18);
  lv_obj_align(user_name, NULL, LV_ALIGN_CENTER, 0, 20);

  pwd_ta = lv_textarea_create(lv_scr_act(), NULL);
  lv_textarea_set_text(pwd_ta, "Password");
  lv_textarea_set_one_line(pwd_ta, true);
  lv_textarea_set_cursor_hidden(pwd_ta, true);
  lv_obj_set_size(pwd_ta, LV_HOR_RES - 200, 40);
  lv_obj_align(pwd_ta, NULL, LV_ALIGN_CENTER, 0, 55);
  lv_obj_set_event_cb(pwd_ta, ta_event_cb);
}

static void ta_event_cb(lv_obj_t * ta, lv_event_t event) {
  if (event == LV_EVENT_CLICKED) {
    lv_obj_align(user_img_block, NULL, LV_ALIGN_IN_TOP_MID, 0, 0);
    lv_obj_align(user_name, NULL, LV_ALIGN_CENTER, 0, -45);
    lv_obj_align(pwd_ta, NULL, LV_ALIGN_CENTER, 0, -10);
    lv_textarea_set_text(pwd_ta, "");
    lv_textarea_set_pwd_mode(pwd_ta, true);

    kb = lv_keyboard_create(lv_scr_act(), NULL);
    lv_obj_set_height(kb, 140);
    lv_obj_align(kb, NULL, LV_ALIGN_IN_BOTTOM_LEFT, 0, 0);
    lv_keyboard_set_textarea(kb, ta);
    lv_obj_set_event_cb(kb, kb_pwd_event_cb);
  }
}

static void kb_pwd_event_cb(lv_obj_t * keyboard, lv_event_t event) {
  lv_keyboard_def_event_cb(keyboard, event);
  if (event == LV_EVENT_APPLY) {
    lv_keyboard_set_textarea(keyboard, NULL); /*De-assign the text area to hide it cursor if needed*/
    lv_obj_del(keyboard);
    pwd();
  } else if (event == LV_EVENT_CANCEL) {
    lv_obj_align(user_img_block, NULL, LV_ALIGN_CENTER, 0, -45);
    lv_obj_align(user_name, NULL, LV_ALIGN_CENTER, 0, 20);
    lv_obj_align(pwd_ta, NULL, LV_ALIGN_CENTER, 0, 55);
    lv_keyboard_set_textarea(keyboard, NULL); /*De-assign the text area to hide it cursor if needed*/
    lv_obj_del(keyboard);
  }
}

void pwd() {
  if (!strcmp(lv_textarea_get_text(pwd_ta), password) == 0) {
    lv_textarea_set_text(pwd_ta, "Incorrect password!");
    lv_textarea_set_pwd_mode(pwd_ta, false);
    lv_obj_set_style_local_text_color(pwd_ta, LV_OBJ_PART_MAIN, LV_STATE_DEFAULT, LV_COLOR_RED);
  } else if (strcmp(lv_textarea_get_text(pwd_ta), password) == 0) {
    lv_textarea_set_text(pwd_ta, "Correct password!");
    lv_textarea_set_pwd_mode(pwd_ta, false);
    lv_obj_set_style_local_text_color(pwd_ta, LV_OBJ_PART_MAIN, LV_STATE_DEFAULT, LV_COLOR_GREEN);
  }
}`

This is the code.

**Comment by Miguel0101** [comment]
> Does the log show the same memory allocation error? If so, if you have a debugger, it would probably be worth stepping through `lv_img_design` (probably [this section](https://github.com/lvgl/lvgl/blob/e08ecffca94623727ef7a8d7ae9f620e15cf7784/src/lv_widgets/lv_img.c#L662-L716)).

Ok

**Comment by Miguel0101** [comment]
How to use `lv_img_design`?

**Comment by Miguel0101** [comment]
@embeddedt Can I try to use the lodepng library?

**Comment by Miguel0101** [comment]
Does the "lodepng" library work?

**Comment by kisvegabor** [comment]
I recommend trying it out with a very small file, e.g. 10x10 resolution.

**Comment by Miguel0101** [comment]
> I recommend trying it out with a very small file, e.g. 10x10 resolution.

Ok.

**Comment by Miguel0101** [comment]
it worked, thanks @kisvegabor and @embeddedt

**Comment by Miguel0101** [comment]
How do I get more memory? Should I add an external PSRAM?

**Comment by Miguel0101** [comment]
[](https://docs.espressif.com/projects/esp-idf/en/latest/esp32/api-guides/external-ram.html)

ESP32 supports external memory.

**Comment by Miguel0101** [comment]
https://docs.espressif.com/projects/esp-idf/en/latest/esp32/api-guides/external-ram.html

**Comment by kisvegabor** [comment]
`lodepng` uses the standard `malloc` so it's an ESP-related question of how to use the external RAM for memory allocation.

All I can help with that if you have PSRAM you can use `ps_malloc/free/realloc` in [lodepng.c](https://github.com/lvgl/lv_lib_png/blob/master/lodepng.c#L73-L92).

**Comment by Miguel0101** [comment]
> `lodepng` uses the standard `malloc` so it's an ESP-related question of how to use the external RAM for memory allocation.
> 
> All I can help with that if you have PSRAM you can use `ps_malloc/free/realloc` in [lodepng.c](https://github.com/lvgl/lv_lib_png/blob/master/lodepng.c#L73-L92).

Okay, is LVGL compatible with external memories?

**Comment by embeddedt** [comment]
LVGL is platform-independent. If your external RAM is mapped in address space normally, it works.

**Comment by embeddedt** [comment]
Note that, while I've never used ESP32, I have heard that the performance of external RAM can be noticeably worse compared to internal RAM. If I recall correctly it's something to do with ESP32 having too small of a cache size compared to the size of the RAM.

**Comment by Miguel0101** [comment]
> Note that, while I've never used ESP32, I have heard that the performance of external RAM can be noticeably worse compared to internal RAM. If I recall correctly it's something to do with ESP32 having too small of a cache size compared to the size of the RAM.

Okay, thanks.
