### ISSUE TITLE
Do you has the plan to complete api_map for v7 migrate to v8?

### ISSUE THREAD

**Issue by Hpbbs** [lvgl/lvgl#2231]

**Comment by kisvegabor** [comment]
It's not possible in many cases. I'd rather make a "clean start" instead of a bunch of hacks to support old methods. 

Note that v7 will be supported for a year so you don't have to migrate your project to v8 but it's recommended to start the new ones with it.

**Comment by embeddedt** [comment]
To add to @kisvegabor's point - older major releases of LVGL (5.3, 6.1) are usable and stable even after support ends. It's just that we don't have the resources as a project to continue to answer questions and fix bugs regarding them. So if someone's hypothetical project works well with 6.1 - no need to upgrade. :slightly_smiling_face:

**Comment by kisvegabor** [comment]
As the questions answered I close this issue.
