### ISSUE TITLE
lv_obj_spec_attr_t::ext_click_pad can be negtive val in v7, will it support negtive val in v8?

### ISSUE THREAD

**Issue by Hpbbs** [lvgl/lvgl#2232]
### Suggested solution
The design that divide draw coord and event coord is good, but i cant understand why its must be negtive; 
in v7 time, there no bubble mechenism, I use the smaller click pad for aquire golable screen border event such as globle return

**Comment by kisvegabor** [comment]
I've updated `ext_click_area` to have `lv_coord_t` type: 9c962303
