### ISSUE TITLE
[ESP32-IDF] LVGL Image: No chroma keying for imgs with indexed colors

### ISSUE THREAD

**Issue by sieren** [lvgl/lvgl#2233]
### Introduce the problem
I am unable to use Chroma Keying on ESP32 IDF due to the dependency on `LV_COLOR_SCREEN_TRANSP` which is dependent on `LV_COLOR_DEPTH_32` in `KConfig`.
However, removing the first dependency (`LV_COLOR_TRANSP_HEX` on `LV_COLOR_SCREEN_TRANSP`) solves the issue and chroma keying works with images with indexed colors, which makes me wonder why this dependency is there in the first place? Potentially an oversight when this was made compatible with ESP32-IDF's components system?

### Examples and cases
In my case I am using a few images directly from DRAM, switching to 32 Bit is using too much memory which is why I'd rather stick to 16 bit and use this feature there.

### Suggested solution
I'm happy to do a PR (one-liner) that removes this dependency from KConfig.

**Comment by kisvegabor** [comment]
`LV_COLOR_SCREEN_TRANSP` is really not required for Chroma keying. Could you send a PR with the removed dependency?

**Comment by embeddedt** [comment]
@kisvegabor A PR was already opened: #2234

**Comment by kisvegabor** [comment]
Oh shame on me. I could have seen the link above my comment :smile: 

Thank you!
