### ISSUE TITLE
Dropdown hides label when the dropdown has no symbol

### ISSUE THREAD

**Issue by ataweg** [lvgl/lvgl#2235]
In my dropdown list I don't want to have a symbol on the right side. With `lv_dropdown_set_symbol( obj, 0 );` I can do this. But then the label of the dropdown list is not shown. The causefor this is a wrongly set closed brace.
Fix: In **lv_dropdown.c** move the closed brace from line 839 ( after `lv_draw_label(&txt_area, clip_area, &label_dsc, opt_txt, NULL); `) before line 817 ( before l`v_point_t size;`) and everything should be fine.

**Comment by kisvegabor** [comment]
Thank you, fixed as you suggested.
