### ISSUE TITLE
The text in the selected area of the roller is not centered

### ISSUE THREAD

**Issue by alec-2018** [lvgl/lvgl#2239]
### Perform all steps below and tick them with [x]
- [ ] Check the related part of the [Documentation](https://docs.lvgl.io/)
- [ ] Update lvgl to the latest version
- [x] Reproduce the issue in a [Simulator](https://docs.lvgl.io/latest/en/html/get-started/pc-simulator.html)

### Screenshots or video

The text in the selected area of the roller is not centered，
It can be reproduced using the following lv_ex_roller_1() program
![微信图片_20210506105711](https://user-images.githubusercontent.com/40708750/117235745-e14a5700-ae59-11eb-935e-27ffa0b46bc8.png)

void lv_ex_roller_1(void)
{

      lv_obj_t *roller1 = lv_roller_create(lv_scr_act(), NULL);

      lv_roller_set_options(roller1,
                        "January\n"
                        "February\n"
                        "March\n"
                        "April\n"
                        "May\n"
                        "June\n"
                        "July\n"
                        "August\n"
                        "September\n"
                        "October\n"
                        "November\n"
                        "December",
                        LV_ROLLER_MODE_INFINITE);

    lv_roller_set_visible_row_count(roller1, 4);
    lv_obj_align(roller1, NULL, LV_ALIGN_CENTER, 0, 0);
    lv_obj_set_style_local_text_font(roller1, LV_ROLLER_PART_BG, LV_STATE_DEFAULT, &lv_font_montserrat_12);
    lv_obj_set_style_local_text_font(roller1, LV_ROLLER_PART_SELECTED, LV_STATE_DEFAULT, &lv_font_montserrat_30);
    lv_obj_set_event_cb(roller1, event_handler);
}

Solution：
I think this is because the roller_part obtained by mode LV_DESIGN_DRAW_POST in lv_roller_design() is LV_ROLLER_PART_SELECTED instead of LV_ROLLER_PART_BG

![微信图片_20210506111606](https://user-images.githubusercontent.com/40708750/117237014-8f570080-ae5c-11eb-8f89-36aa586e069d.png)
![微信图片_20210506111821](https://user-images.githubusercontent.com/40708750/117237132-d7762300-ae5c-11eb-8b8d-6ad80c9fa1d5.png)

Do you think it can be modified like this? @kisvegabor

**Comment by embeddedt** [comment]
This looks like the correct solution to me; would you like to open a PR for `release/v7`?

**Comment by alec-2018** [comment]
I am very happy, but I don’t have the energy to maintain it now, but I will feed back the problems and solutions I currently encounter, hoping to contribute to the open source project

**Comment by embeddedt** [comment]
Sounds good; I've applied your fix here: https://github.com/lvgl/lvgl/commit/708272c37cacc190e327373f1972dadccbf137e9
