### ISSUE TITLE
Is v8 api design to compatible CSSDOM DOM and Box Model from W3C? if so, Why there have no margin attribute

### ISSUE THREAD

**Issue by Hpbbs** [lvgl/lvgl#2242]

**Comment by kisvegabor** [comment]
Right now we differ from `border-box` in two points:
1. border has no "size". I.e. its size is not added to the padding to move the children further from the edge of the parent. Do you think the standard `border-box` is better? 
2. no margin, but it can be added later if v8 becomes stable

**Comment by Hpbbs** [comment]
Hi, thanks for attention

I think standard `border-box` have some advantages:
1. front-end and Android developer use this model，It`s economy for other developer to learn and understand lvgl layout design
2. I learned that the lvgl style and theme is designed to compatible CSS, use CSS box model is very natrual and fluent
3. for embedded situation, lvgl should has our own optimise just like android can use bitmap to fill border etc. but standard can deduce many cost when standard principle did not differ from you design goal

**Comment by kisvegabor** [comment]
@FASTSHIFT 
> Will v8 add stretch support in align-items?

It's supported on grid and planned on flexbox too after v8 release. Is there anything else where we can use it?
