### ISSUE TITLE
"Hello World" in LVGL/MicroPython simulator: "ImportError: module not found"

### ISSUE THREAD

**Issue by ropg** [lvgl/lvgl#2245]
### Perform all steps below and tick them with [x]
- [x] Check the related part of the [Documentation](https://docs.lvgl.io/)
- [x] Update lvgl to the latest version
- [x] Reproduce the issue in a [Simulator](https://docs.lvgl.io/latest/en/html/get-started/pc-simulator.html)

### Describe the bug

"Hello World" python demo says "ImportError: module not found" (on imp.py ?)

### To Reproduce

Click the second link under "How can I use it" on [this page](https://docs.lvgl.io/dev/en/html/get-started/micropython.html#how-can-i-use-it)

### Expected behavior

Some Hello World example that does not complain about a module

### Screenshots or video

![Screenshot 2021-05-09 at 05 44 44](https://user-images.githubusercontent.com/343196/117559926-b21a2c80-b089-11eb-9428-354fd0ba87cc.png)

**Comment by embeddedt** [comment]
Thanks for reporting! That's an old link; I've just updated it.

https://sim.lvgl.io/v7/micropython/ports/javascript/bundle_out/index.html
