### ISSUE TITLE
fluid chart

### ISSUE THREAD

**Issue by F5Key** [lvgl/lvgl#2247]
...
### Introduce the problem

...
### Examples and cases

Create a cont or an obj which set radius size with LV_RADIUS_CIRCLE,and then create an png picture with animation.The png picture move by position(x++)  LV_ANIM_REPEAT_INFINITE,like water in tank waving,the water level show percent as a chart,but it's not perfect,the png picture shall show only in the cycle cont.
![fluid](https://user-images.githubusercontent.com/32559209/117602931-69936980-b184-11eb-9a9b-606b67dd99a6.gif)
![flut1](https://user-images.githubusercontent.com/32559209/117603138-f0e0dd00-b184-11eb-9896-49002ff97f44.png)
### Suggested solution

...

### Code
![code](https://user-images.githubusercontent.com/32559209/117603504-d78c6080-b185-11eb-8d83-ecb37b53d364.png)

**Comment by kisvegabor** [comment]
Hi,

Just enable the `clip_corner` style proeprty. 

---

We use GitHub Issues for development-related discussions.

Please ask your question in the [Forum](https://forum.lvgl.io) to make it visible for a larger community. You can simply log in with your GitHub account.
