### ISSUE TITLE
example lv_example_textarea_1

### ISSUE THREAD

**Issue by uraich** [lvgl/lvgl#2248]
### Introduce the problem

Action when newline is pressed in lv_example_textarea_1.c
When newline is pressed in lv_example_textarea_1.c a newline is added to the 1 line text area, which has no effect. Would it not be better to erase the content of the text area in this case?

**Comment by kisvegabor** [comment]
Enter has a meaning in "one line" text area. It sends `LV_EVENT_READY`. I've updated the example with it.

**Comment by kisvegabor** [comment]
@uraich Can we close this issue?

**Comment by uraich** [comment]
Sorry, no we cannot. There is still the problem that I do not see the READY events when pressing the <nl> key on the lv_keyboard. If I use the hardware keyboard, then I can enter any character (not just numbers) and the READY event is seen.
When running the Python version the program only reacts on the lv_keyboard and pressing keys on the hardware keyboard is not seen at all. So in that version I never see the READY event.

**Comment by kisvegabor** [comment]
> There is still the problem that I do not see the READY events when pressing the key on the lv_keyboard. If I use the hardware keyboard, then I can enter any character (not just numbers) and the READY event is seen.

The was a conceptual issue in the example. Sorry I've just fixed it. 9d3d2420

> When running the Python version the program only reacts on the lv_keyboard and pressing keys on the hardware keyboard is not seen at all. So in that version I never see the READY event.

Does the keyboard driver added/enable in MP?

**Comment by uraich** [comment]
I did not check the hardware keyboard issue yet but the software keyboard now works as expected (also in the Python case!)

**Comment by kisvegabor** [comment]
Great, thanks!

**Comment by kisvegabor** [comment]
@uraich Is there anything else for this issue?

**Comment by uraich** [comment]
I think we can close it. Thanks.
