### ISSUE TITLE
lv_example_textarea_2: focus not working correctly

### ISSUE THREAD

**Issue by uraich** [lvgl/lvgl#2249]
### Perform all steps below and tick them with [x]
- [x ] Check the related part of the [Documentation](https://docs.lvgl.io/)
- [x] Update lvgl to the latest version
- [x] Reproduce the issue in a [Simulator](https://docs.lvgl.io/latest/en/html/get-started/pc-simulator.html)

### Describe the bug
lv_example_textarea_2 uses 2 textareas, a password area and a normal text area.
The naming "oneline_ta" is misleading because a multi-line textarea is created.
When you click on the normal text area the cursor starts blinking there but when using the keyboard below, the text still goes into the password area.
If you use the hardware keyboard the text appears in the correct textarea

To Reproduce
Try in the simulator

**Comment by kisvegabor** [comment]
Thanks!
I've fixed it in 1899fdff
