### ISSUE TITLE
The size of the button？

### ISSUE THREAD

**Issue by fiend520** [lvgl/lvgl#225]
How to set the size of the button, I want to use the round button, the size can be customized.

**Comment by fiend520** [comment]
![image](https://user-images.githubusercontent.com/36784982/39308560-5992fe76-4998-11e8-8e37-06e30b2848ec.png)
like this

**Comment by qwert1213131** [comment]
可以使用lv_img 和lv_btn 结合创建圆形ICON，
其中btn使用透明style
img使用圆形icon
——————————————————————————————————
The translation is as follows
You can use the combination of lv_img and lv_btn to create circular ICON.
In which BTN uses transparent style
IMG uses circular Icon
[参考网址](http://forum.armfly.com/forum.php?mod=viewthread&tid=86371&extra=page%3D1%26filter%3Dtypeid%26typeid%3D144)

**Comment by kisvegabor** [comment]
The suggested answer should solve the issue. In the next release will be a dedicated object type for it.

Now I close this issue, but if you have any remarks feel free to open it!
