### ISSUE TITLE
ESP32 with LVGL with 8 bit Parallel Interface to Display with xpt2046 touchscreen reader

### ISSUE THREAD

**Issue by 3mc2** [lvgl/lvgl#2258]
I am hoping there is a way to use a third party library to provide the touch functionality to lvgl.

### Perform all steps below and tick them with [x]
- Compile sample with parallel interface enabled in tft_espi 
- 

### Describe the bug
It appears that the tft_espi display driver does not support spi touch controllers such as xpt2046 when running in parallel mode.
In order to get the best performance, SPI is not an option for this project.

### To Reproduce
Compile the LVGL_Ardunio sample program.

### Expected behavior
I would expect there is some way to configure the xpt2046 on an spi connection to operate independent of the tft_espi library.

### Screenshots or video
![image](https://user-images.githubusercontent.com/5133562/118586020-01d2b500-b768-11eb-9e09-041cce758a8f.png)

**Comment by kisvegabor** [comment]
We use GitHub Issues for development-related discussions.

Please ask your question in the [Forum](https://forum.lvgl.io) to make it visible for a larger community. You can simply log in with your GitHub account.
