### ISSUE TITLE
how to hide the buttons on tabview?

### ISSUE THREAD

**Issue by liubingyan123** [lvgl/lvgl#226]
as the titile says, I created a tabview consist of three tab, shown as following pictures, I want to hide the tab buttons or make them invisiable, and also the slider on yhe right side, but failed, please offer me some advices,thank you!
 
![img_20180427_093247](https://user-images.githubusercontent.com/14269886/39340670-fe9ee4e8-4a01-11e8-8202-a46f35d18bd8.jpg)
![img_20180427_093252](https://user-images.githubusercontent.com/14269886/39340671-00a06a78-4a02-11e8-9078-3350ddb72b3a.jpg)

**Comment by kisvegabor** [comment]
Hi,

Now you can't hide the "header". It's height comes from the **font height + body.padding.ver attributes of LV_TABVIEW_STYE_BTN_BG and LV_TABVIEW_STYE_BTN_REL **
As a workaround I can suggest to set a bigger height for the tabview and set negative y position to adjust the header out of the screen or parent object.
  
To hide the scrollbar you can apply this for every page you add to the tabview:
 ```c
    lv_obj_t * p1 = lv_tabview_add_tab(tv, "first");
    lv_page_set_sb_mode(p1, LV_SB_MODE_OFF);
```

**Comment by liubingyan123** [comment]
ok, I'll try it, thank you very much!

**Comment by zhangshengping** [comment]
@kisvegabor  Are you planning to add this feature?

**Comment by kisvegabor** [comment]
See https://github.com/littlevgl/lvgl/issues/628#issuecomment-470959880
