### ISSUE TITLE
add interfaces to get style attributes

### ISSUE THREAD

**Issue by guoweilkd** [lvgl/lvgl#2262]
The current get style interface is either through the obj layer function (eg:`lv_obj_get_style_text_decor()`)or through the base style function `lv_style_get_prop()`. 
Why not add get style interfaces that looks like set-style interface (eg: `lv_style_set_text_decor`)? 
Because sometimes,we need to manipulate styles in the style layer, not in the obj layer. but `lv_style_get_prop()` not convenient enough. 
eg: in lv_span.c, need to get style directly.

**Comment by kisvegabor** [comment]
Making a "full API" for `lv_style_get_<prop_name>` would add ~100 extra functions. 
We try to keep the API smaller mainly because in the Micropython binding every function declaration consumes flash.

Therefore only the most frequently used style-related functions have a full API.
