### ISSUE TITLE
Get obj's size

### ISSUE THREAD

**Issue by xaowang96** [lvgl/lvgl#2265]
### Cannot get obj's width and height right
When I set the size of obj, I cannot get its width or height correctly by using lv_obj_get_width/height.

```C
lv_obj_t *obj = lv_obj_create(parent);
lv_coord_t width = lv_obj_get_width(obj);
```
After executing the above code, width is 0, which is not the real width of obj.
So which api should I use to get the size, after creating obj or setting its size.

**Comment by codingFoxy** [comment]
An object is stored as a structure with some field holding the height and width values. As far as I know, creating an object with `lv_obj_create()` initalizes this structure with standard values. For height and width, that would be 0. 
Try manually setting width and height like
```C
lv_obj_set_size(obj, width, height);
``` 
or 
```C
lv_obj_set_width(obj, width);
lv_obj_set_height(obj, height);
```
and see if the result is the same.

**Comment by xaowang96** [comment]
> An object is stored as a structure with some field holding the height and width values. As far as I know, creating an object with `lv_obj_create()` initalizes this structure with standard values. For height and width, that would be 0.
> Try manually setting width and height like
> 
> ```c
> lv_obj_set_size(obj, width, height);
> ```
> 
> or
> 
> ```c
> lv_obj_set_width(obj, width);
> lv_obj_set_height(obj, height);
> ```
> 
> and see if the result is the same.

**Comment by xaowang96** [comment]
Yes, the result is the same.No matter whether these functions are called or not, the result is the same.

**Comment by kisvegabor** [comment]
See the explanation here http://docs_compiled.lvgl.io/8.0/overview/coords.html#postponed-coordinate-calculation
