### ISSUE TITLE
a question about lv_tabview 

### ISSUE THREAD

**Issue by rongyunxiang** [lvgl/lvgl#2271]
### Introduce the problem
I have a question, when I create a tabview ,How to resize the size and pos of  tabview page?

### Examples and cases

lv_obj_t *tabview_example = lv_tabview_create(NULL, NULL);
lv_obj_t *page_example = lv_tabview_add_tab(tabview, NULL);
lv_page_set_scrollbar_mode(page , LV_SCROLLBAR_MODE_OFF);
we know the size of 'page_example' equals 'tabview_example', 
how could I change the pos page_example?
does lv_obj_set_pos(page, 0, 100);  works?

**Comment by kisvegabor** [comment]
The position of pages is handled by the tabview so I can't why would you like to change it manually? 

But we use GitHub Issues for development-related discussions. 

Please ask your question in the [Forum](https://forum.lvgl.io) to make it visible for a larger community. You can simply log in with your GitHub account.

Please also answer my quesion in the Forum post.
