### ISSUE TITLE
"lv_obj_set_style_local_bg_color" function seems to be lost

### ISSUE THREAD

**Issue by DanielSH-2io** [lvgl/lvgl#2275]
### Perform all steps below and tick them with [x]
- [X] Check the related part of the [Documentation](https://docs.lvgl.io/)
- [X] Update lvgl to the latest version
- [X] Reproduce the issue in a [Simulator](https://docs.lvgl.io/latest/en/html/get-started/pc-simulator.html)

### Describe the bug

I've recently upgrade to v8.0. Everything works fine excepting the function "lv_obj_set_style_local_bg_color". The compiler does not find the function. I have searched for the code and I do not find it either.
Here the message from the compiler:
error: ‘lv_obj_set_style_local_bg_color’ was not declared in this scope; did you mean ‘lv_obj_set_style_outline_color’?
|       lv_obj_set_style_local_bg_color(dummy, lv_color_make(0xFF, 0x00, 0x00), 0);

### To Reproduce

Here a simple code to reproduce the error:

lv_obj_t *dummy = lv_obj_create(lv_scr_act());
lv_obj_set_style_local_bg_color(dummy, lv_color_make(0xFF, 0x00, 0x00), 0);

### Expected behavior

Is clearly expected the compiler to find the function and the the function to work properly

**Comment by kisvegabor** [comment]
Hi,

The function's name has slightly changed to `lv_obj_set_style_bg_color(dummy, lv_color_make(0xFF, 0x00, 0x00), 0);` (the `local` word is removed).
