### ISSUE TITLE
CHANGELOG link shows 404 Error

### ISSUE THREAD

**Issue by asypost** [lvgl/lvgl#2277]
### Perform all steps below and tick them with [x]
- [X] Check the related part of the [Documentation](https://docs.lvgl.io/)
- [X] Update lvgl to the latest version
- [X] Reproduce the issue in a [Simulator](https://docs.lvgl.io/latest/en/html/get-started/pc-simulator.html)

### Describe the bug

In the github release page,click CHANGELOG will show a 404 page.
### To Reproduce

Go to github release page,and click a changelog link.for example:the changelog of Release v8.0.0 [CHANGELOG](https://github.com/lvgl/lvgl/blob/master/CHANGELOG.md)

### Expected behavior

Show the content of changelog file,which is important for migrating.

**Comment by kisvegabor** [comment]
Thanks, I've fixed the links.
