### ISSUE TITLE
Draw circle

### ISSUE THREAD

**Issue by peng-fan** [lvgl/lvgl#228]
How to draw a circle at position of an object?

**Comment by kisvegabor** [comment]
Hi,

To draw a circle set `LV_RADIUS_CIRCLE` as radius in the object's style:

```c
my_style.body.radius = LV_RADIUS_CIRCLE;
```

**Comment by peng-fan** [comment]
Thanks, I can't seem to figure out how to set two different fillStyles for two different arcs. I just wanna be able to draw different color circles, like that.
![771842-20151020161517583-980352157](https://user-images.githubusercontent.com/14306529/39509199-f21444ce-4e17-11e8-9126-f4795c465984.png)

**Comment by peng-fan** [comment]
I can use the "border" of style, right? but how to draw 1%?

**Comment by kisvegabor** [comment]
Unfortunately LittlevGL doesn't support arc drawing at this moment. (There are plans to add this feature)
And now the border is mono-color.

To crate sophisticated arcs and don't need high resolution (e.g. 10 states is okay) then I suggest to build it from small images and hide which is not required.

**Comment by peng-fan** [comment]
Thanks, I will try.

**Comment by kisvegabor** [comment]
Arc drawing become a planned feature in an upcoming release.

We can continue the discussion about it here: #255
