### ISSUE TITLE
strange effect on lv_example_btnmatrix_3

### ISSUE THREAD

**Issue by uraich** [lvgl/lvgl#2281]
### Perform all steps below and tick them with [x]
- [ x] Check the related part of the [Documentation](https://docs.lvgl.io/)
- [ x] Update lvgl to the latest version
- [ x] Reproduce the issue in a [Simulator](https://docs.lvgl.io/latest/en/html/get-started/pc-simulator.html)

### Describe the bug
When you start the example, the first element is selected. When you press the right arrow button for the first time the selection jumps immediately to "3". When coming back to "1" with the left arrow and trying again, everything works as expected.
### To Reproduce
Just try lv_example_btnmatrix_3

**Comment by kisvegabor** [comment]
Thanks, I've fixed it. See https://docs.lvgl.io/8.0/widgets/core/btnmatrix.html#example
