### ISSUE TITLE
[v8.0] In nxp pxp driver  `LV_COLOR_TRANSP` undeclared 

### ISSUE THREAD

**Issue by gdf8gdn8** [lvgl/lvgl#2289]
### Perform all steps below and tick them with [x]
- [x] Check the related part of the [Documentation](https://docs.lvgl.io/)
- [x] Update lvgl to the latest version
- [ ] Reproduce the issue in a [Simulator](https://docs.lvgl.io/latest/en/html/get-started/pc-simulator.html)

### Describe the bug
While compiling with NXP pxp enabled the macro `LV_COLOR_TRANSP` is not found.
```
/lvgl/src/gpu/lv_gpu_nxp_pxp.c:122:30: error: 'LV_COLOR_TRANSP' undeclared (first use in this function); did you mean 'LV_OPA_TRANSP'?
  122 |     colorKey = lv_color_to32(LV_COLOR_TRANSP);
      |                              ^~~~~~~~~~~~~~~
      |                              LV_OPA_TRANSP
```

### To Reproduce
Compile with MCUXpresso NXP sdk for imxrt1064 evk

### Expected behavior
Compiling

My suggestion is to use `LV_COLOR_CHROMA_KEY` instead.

**Comment by kisvegabor** [comment]
Thanks, fixed!
