### ISSUE TITLE
Confusing link to driver init example

### ISSUE THREAD

**Issue by jupeos** [lvgl/lvgl#2294]
[V8] The link in [v8.0.0 is released](https://blog.lvgl.io/2021-06-01/release_v8.0.0) refers to V7 code. Not helpful when porting.
## Driver changes
- `...disp_buf...` is renamed to `draw_buf`. See an initialization example [here](https://github.com/lvgl/lv_sim_eclipse_sdl/blob/e164e3591c3e1e3bf3464d19e0dcdc67b2e6a791/main.c#L87-L97).

**Comment by kisvegabor** [comment]
Thanks, I've just fixed it.
