### ISSUE TITLE
Delete its child during parent scrolling causing scroll error

### ISSUE THREAD

**Issue by xaowang96** [lvgl/lvgl#2297]
### Something was wrong in scrolling
I need delete its child during obj scrolling, but this will cause obj scrolling errors. It will automatically stroll  back to the (0, 0), because the following code is in lv_obj_del.
```C
/*Call the ancestor's event handler to the parent to notify it about the child delete*/
if(par) {
    /*Just to remove scroll animations if any*/
    lv_obj_scroll_to(par, 0, 0, LV_ANIM_OFF);
    if(par->spec_attr) {
            par->spec_attr->scroll.x = 0;
            par->spec_attr->scroll.y = 0;
        }
    lv_event_send(par, LV_EVENT_CHILD_CHANGED, NULL);
}
```
So i want to know why to do this, and what can i do to resolve it.

**Comment by kisvegabor** [comment]
Hi,

I've pushed a fix for it to the `master`. 
See 52edbb46
