### ISSUE TITLE
Sorted data in list

### ISSUE THREAD

**Issue by scopa90** [lvgl/lvgl#23]
Would it be possible to add a sort function to the lv_list_add function or create a new lv_list_add_sorted function?

**Comment by kisvegabor** [comment]
Sure! I will be on a holiday for a week. After that I can deal with it!

**Comment by kisvegabor** [comment]
Recently I was thinking about this suggestion and found that it's very complicated to solve inside LittelvGL. 
It seems much easier and flexible to do it outside of the library using `lv_lsit_clean` and adding the buttons again.

Now, I close this issue but feel free to comment here and reopen it if you have any remarks.
