### ISSUE TITLE
Is there any manual books of the GUI?

### ISSUE THREAD

**Issue by turoksama** [lvgl/lvgl#231]
Hi, are there any pdf **# manual** books of the GUI?

**Comment by turoksama** [comment]
Hi,
    Well, a "book" means a hands-on real paper document. I think it is a more effective way to learn(notes, compares at the same time, real-view, mostly do not need a 32 inch screen that makes you fuzzy).
Thanks for the tool you've mentioned. I manually collected the documents and put it together into a pdf, I would share if you like.

**Comment by kisvegabor** [comment]
It would be great if you shared your pdf! 
I think a lot of people would be grateful for It! :)

**Comment by turoksama** [comment]
Well, I am sending you a copy, please check for it in your email box.

**Comment by kisvegabor** [comment]
I got it thank you very much.
I saw that you collected the documentation of the object types. If it helps I can do it with a HTML->PDF converter using a PHP script. Maybe it's better to generate with a script and also easier to update :)
