### ISSUE TITLE
help, 18bits

### ISSUE THREAD

**Issue by Leadrive** [lvgl/lvgl#2312]
Hi, my lcd is LH280QV010-40.pdf, [https://github.com/Leadrive/temp/blob/master/LH280QV010-40.pdf](https://github.com/Leadrive/temp/blob/master/LH280QV010-40.pdf)
LVGL display not fine.
OS: linux 3.4
CPU: V3S 1.2Ghz
[https://github.com/Leadrive/temp/blob/master/18bits_lvgl.png](https://github.com/Leadrive/temp/blob/master/18bits_lvgl.png)

And the QT 4.8 display ok.
[https://github.com/Leadrive/temp/blob/master/18bits_qt.png](https://github.com/Leadrive/temp/blob/master/18bits_qt.png)

I use the framebuffer to display in LVGL. such as the example lv_port_linux_frame_buffer.
I think maybe modify the color_p in fbdev_flush() function, it will display ok.
````c++
    /*32 or 24 bit per pixel*/
    if(vinfo.bits_per_pixel == 32 || vinfo.bits_per_pixel == 24) {
        uint32_t * fbp32 = (uint32_t *)fbp;
        int32_t y;
        for(y = act_y1; y <= act_y2; y++) {
            location = (act_x1 + vinfo.xoffset) + (y + vinfo.yoffset) * finfo.line_length / 4;
            memcpy(&fbp32[location], (uint32_t *)color_p, (act_x2 - act_x1 + 1) * 4);
            color_p += w;
        }
    }
````
the system report is 32bpp.

I don't know how to convert color_p from 18bits to 32bits. Please help me.
Thank you very much.

**Comment by kisvegabor** [comment]
Hi,

with 18 bits all channels (r,g,b) are represented on 6 bits but you have 8 bits per channel. You need to know exactly how the bits are packed but probably you need something like:
```c
color_p[i]->ch.red = color_p[i]->ch.red >> 2;  //Drop the 2 LSB
color_p[i]->ch.green = color_p[i]->ch.green >> 2;  //Drop the 2 LSB
color_p[i]->ch.blue = color_p[i]->ch.blue >> 2;  //Drop the 2 LSB
```

To be sure how the color is formatted I suggest trying to draw pure red, green, and blue rectangles without LVGL by directly calling the `flush_cb`.

---

We use GitHub Issues for development-related discussions.

If you have further questions please open a topic in the [Forum](https://forum.lvgl.io) to make it visible for a larger community. You can simply log in with your GitHub account.
