### ISSUE TITLE
Version confusion with PlatformIO library registry

### ISSUE THREAD

**Issue by maxgerhardt** [lvgl/lvgl#2315]
### Perform all steps below and tick them with [x]
(none of these are relevant)
- [X] Check the related part of the [Documentation](https://docs.lvgl.io/)
- [X] Update lvgl to the latest version
- [X] Reproduce the issue in a [Simulator](https://docs.lvgl.io/latest/en/html/get-started/pc-simulator.html)

### Describe the bug

The library versions as uploaded and described on https://platformio.org/lib/show/6598/lvgl do not match, by content and date, the versions uploaded in this repository.

Take e.g. the 8.0.0 version from the PlatformIO library registry

![grafik](https://user-images.githubusercontent.com/26485477/122032410-e5aa4e00-cdcf-11eb-959d-d6bbfd6c9d76.png)

It says that version was uploaded on the 16th March, so pretty much 3 months ago. Looking at your branch https://github.com/lvgl/lvgl/tree/v8.0.0, the latest commit says "Release v8.0.0", from 14 days ago (20th May, https://github.com/lvgl/lvgl/commit/c597d257984e2cd3a1c883dc97a26d4512b5e60a). How does that work out? A pre-release version was uploaded there, tagged as 8.0.0? Does the 8.0.0 releaseversion keep changing over time?
 
When people use PlatformIO with the library version expression

```ini
lib_deps =
     lvgl/lvgl @ 8.0.0
```

they are getting some 3-month old "8.0.0" version and ask us on what in the world that library version is and why it doesn't match the repo (see: ["Strange version being installed by library manager?"](https://community.platformio.org/t/strange-version-being-installed-by-library-manager/21992)).

### To Reproduce

Create a PlatformIO project and add the above shown [`lib_deps`](https://docs.platformio.org/en/latest/projectconf/section_env_library.html#lib-deps) expression to the `platformio.ini`, build the project, then compare the contents of `.pio\libdeps\<env>\lvgl` with what is in the repo for version 8.0.0

### Expected behavior

The versions uploaded to the PlatformIO library manager should be the same as in this repo. Tags should be frozen.

BTW, if you need help with removing existing versions from the PlatformIO library, you probably need assistance from the PlatformIO staff, so let us know in the forum or here. 

### Screenshots or video
\<none applicable\>

**Comment by embeddedt** [comment]
https://forum.lvgl.io/t/v8-0-is-released/5668/9?u=embeddedt

8.0.0 was mistakenly released to PlatformIO before the actual release. 8.0.1 is just a patch release, so the simplest solution is probably to just remove 8.0.0 from PlatformIO.

@kisvegabor Do you agree?

**Comment by kisvegabor** [comment]
Yes, I agree, but for some reason v8.0.1 is not listed:
![image](https://user-images.githubusercontent.com/7599318/122114450-94c44500-ce23-11eb-9580-68c4fbbe6d37.png)


BTW, how to remove a release from PIO?

**Comment by embeddedt** [comment]
If I had to guess, I would say that it's because PIO is only checking the `master` branch, not the release branches. I think it would actually prevent this issue in the future if it did the opposite, but I'm not sure that's possible.

**Comment by kisvegabor** [comment]
I've tried manually `pio package publish` from `release/v8.0` Let's see what happens. (Needs 24 hours)

On a sidenote: [Arduino](https://www.arduinolibraries.info/libraries/lvgl) picked it up correctly.
![image](https://user-images.githubusercontent.com/7599318/122118983-f9ce6980-ce28-11eb-8bcd-b8a875af55bd.png)

**Comment by kisvegabor** [comment]
Oh, it was updated immediately. But it was only v8.0.1.

I've published master too and now it looks like this:
![image](https://user-images.githubusercontent.com/7599318/122120811-2aaf9e00-ce2b-11eb-960f-c2b49691af0f.png)

EDIT:
I'm sure what has happened... Anyway, it seems this way we can publish releases one by one but the release date is the date of manual publishing. So probably if we publish v7.11.0 it will be the latest release.

**Comment by maxgerhardt** [comment]
>I've tried manually pio package publish from release/v8.0 Let's see what happens. (Needs 24 hours)
>Oh, it was updated immediately. But it was only v8.0.1.

Yes I would expect that too because the `version` field of the `library.json` in the `release/v8.0` branch says `8.0.1`. 

https://github.com/lvgl/lvgl/blob/release/v8.0/library.json#L3

I think re-publishing the repo exactly as seen in the `v8.0.0` tag would work out though, since its version field is 

https://github.com/lvgl/lvgl/blob/c597d257984e2cd3a1c883dc97a26d4512b5e60a/library.json#L3

(on a sidenote though I wasn't actually aware of that you could re-publish the library under the same version multiple times).

Again, if you need a specific version deleted from the PIO registry, I can tag ivankravets here (PlatformIO CEO).

**Comment by kisvegabor** [comment]
I'm still confused. PIO picked up releases automatically so far. Or someone published them manually?

**Comment by embeddedt** [comment]
I suspect PIO is scanning `master` on a regular basis and using whatever release data is there.

**Comment by maxgerhardt** [comment]
>I suspect PIO is scanning master on a regular basis and using whatever release data is there.

They way I have read it in the community forums is that a repository can either use the 'legacy' autocrawler, which scans for new releases or the default branch, or is setup for manual publishing. 

Maybe @ivankravets can assist here with a better library version cleanup.

**Comment by kisvegabor** [comment]
Thank you, Ivan!

I've published the master branch (`v8.1.0-dev`) and the `v8.0.1` tag of `lvgl` and `lv_drivers`.
The `library.json` file was incorrect for `lv_driver` on `v8.0.0` but was correct for `lvgl`, so `lvgl` `v8.0.0` is also published.

The only issue is the release dates are incorrect. Is it possible to set them manually?

I'm not sure what policy fits best to PIO. Shall/Can we publish the `master` branches periodically where we have the latest unreleased features and fixes or publish on the releases?

**Comment by ivankravets** [comment]
> I've published the master branch (v8.1.0-dev)

I removed again all DEV versions. We don't recommend publishing unstable packages into the registry. If someone needs the latest upstream version, he can use GIT re[psitory directly.

> The only issue is the release dates are incorrect. Is it possible to set them manually?

Thanks, I fixed them manually.

>  Shall/Can we publish the master branches periodically 

Please publish new package versions when you make final release.

**Comment by kisvegabor** [comment]
Thank you @ivankravets. We will do it as you suggested.

As the versions are cleaned up I close this issue.
