### ISSUE TITLE
lvgl how to create custom progress bar

### ISSUE THREAD

**Issue by nguyenan-ble** [lvgl/lvgl#2316]
Hi  All,
I am creating a progress bar like attached picture on GUI guider but nothing like this.
I am very glad if receive solution from you.
this bar can run from 0-100%
normal state is white and green is in active.

![image](https://user-images.githubusercontent.com/85942359/122080654-65b8ce00-ce39-11eb-9e68-e8e98e0fe5a4.png)

Thanks alot!

**Comment by nguyenan-ble** [comment]
@kisvegabor 
I knew you via many your answers, so I tag you for question.
Thanks!

**Comment by kisvegabor** [comment]
Hi,

I can't perfectly imagine how the progress bar should look like. Please add a few more images with 0%, 30%, 60%, 100% states.

But let's continue on the Forum. Please open a topic in the "How to" category.

We use GitHub for development-related discussions.
