### ISSUE TITLE
undefined reference to `lv_example_tabview_2'

### ISSUE THREAD

**Issue by Johnxjj** [lvgl/lvgl#2318]
When I try to use the lv_example_tabview_2() example, a compilation error is reported. Is it because the file lv_example_tabview_2.py is missing.

**Comment by Johnxjj** [comment]
![image](https://user-images.githubusercontent.com/18185301/122173524-6478b700-ceb4-11eb-8d68-186e251ba692.png)

**Comment by kisvegabor** [comment]
`lv_example_tabview_2` was added a few days ago.

Be sure to update lvgl to the latest version and Refresh the Eclipse project.

**Comment by kisvegabor** [comment]
As the [lv_example_tabview_2](https://github.com/lvgl/lvgl/blob/master/examples/widgets/tabview/lv_example_tabview_2.c) is really there I close this issue.

**Comment by Johnxjj** [comment]
@kisvegabor I am not referring to lv_example_tabview_2.c, but lv_example_tabview_2.py. Whether this file is useful for emulation on PC.

**Comment by kisvegabor** [comment]
Oh, thanks.
@uraich Could you take a look at this example?

**Comment by uraich** [comment]
@kisvegabor @Johnxjj :
For the moment, I uploaded it to https://github.com/uraich/lv_mpy_examples_v8/tree/main/widgets/tabview
If you are happy with it, I can create a PR to integrate it into lvgl. To me, it looks like it behaves the same way as the C original.

**Comment by kisvegabor** [comment]
Thank you @uraich.

Yes, please send a PR :slightly_smiling_face:

**Comment by uraich** [comment]
It is already merged into master.

**Comment by kisvegabor** [comment]
I'm catching up with my email, it seems I didn't get there yet :slightly_smiling_face:
