### ISSUE TITLE
Flex layout in row with many objects fails

### ISSUE THREAD

**Issue by grarup** [lvgl/lvgl#2323]
### Perform all steps below and tick them with [x]
- [x ] Check the related part of the [Documentation](https://docs.lvgl.io/)
- [ x] Update lvgl to the latest version
- [ x] Reproduce the issue in a [Simulator](https://docs.lvgl.io/latest/en/html/get-started/pc-simulator.html)

### Describe the bug

Adding many elements to a flex layout setup with flow to row, gives ends up in a layout loop, and nothing is shown in the window.

### To Reproduce
```c
  lv_obj_t * root = lv_obj_create(NULL);

  lv_obj_set_layout(root, LV_LAYOUT_FLEX);
  lv_obj_set_flex_flow(root, LV_FLEX_FLOW_ROW);

  char_t szTmp[20];

  for (size_t i = 0; i < 200; i++)
  {
    lv_obj_t * label = lv_label_create(root);
    sprintf(szTmp, "test %i", i);
    lv_label_set_text(label, szTmp);
  }

  lv_scr_load(root);
```

### Expected behavior
It either can show all the elements or stops when i reaches som kind of limit and only shows the element before.

### Screenshots or video
```
[Info]  (597018.171, +0)         lv_obj_update_layout: Layout update begin      (in lv_obj_pos.c line #302)
[Info]  (597018.171, +0)         flex_update: update 0x234e068 container        (in lv_flex.c line #206)
[Info]  (597018.171, +0)         lv_obj_update_layout: Layout update begin      (in lv_obj_pos.c line #302)
[Info]  (597018.171, +0)         flex_update: update 0x234e068 container        (in lv_flex.c line #206)
[Info]  (597018.171, +0)         lv_obj_update_layout: Layout update begin      (in lv_obj_pos.c line #302)
[Info]  (597018.171, +0)         flex_update: update 0x234e068 container        (in lv_flex.c line #206)
[Info]  (597018.171, +0)         lv_obj_update_layout: Layout update begin      (in lv_obj_pos.c line #302)
[Info]  (597018.171, +0)         flex_update: update 0x234e068 container        (in lv_flex.c line #206)
```

**Comment by kisvegabor** [comment]
Thanks for the report. I've pushed a fix it. I've tested it with 2000 objects.

Note that you need to enable `LV_USE_LARGE_COORD` in `lv_conf.h`.
