### ISSUE TITLE
the `LV_TXT_BREAK_CHARS` macro should be more flexible

### ISSUE THREAD

**Issue by guoweilkd** [lvgl/lvgl#2324]
in current, `LV_TXT_BREAK_CHARS   " ,.;:-_"` is friendly for english. but it's not good for chinese and other language. Because every word in Chinese can be used break char. so, We also need a range of judgment , like this:`letter >= 0x4E00 && letter <= 0x9FA5` . 

The final code like this,

```
#define LV_LETTER_IS_BREAK_CHARS(letter)  \
    ({\
        char* str = " ,.;:-_";\
        bool ret = false;\
        if (letter >= 0x4E00 && letter <= 0x9FA5) {\
            ret = true;\
        } else {\
            for(int i = 0; str[i] != '\0'; i++) {\
                if(letter == (uint32_t)str[i]) {\
                    ret = true;\
                    break;\
                }\
            }\
        } \
        ret;\
    })
```
But I don't think it's a good implementation, maybe you have a better idea.

**Comment by kisvegabor** [comment]
It sounds reasonable. 

It can be easily added here https://github.com/lvgl/lvgl/blob/master/src/misc/lv_txt.c#L908

Could you send a Pull request? :slightly_smiling_face:
