### ISSUE TITLE
add action to clickable label

### ISSUE THREAD

**Issue by Moo2017** [lvgl/lvgl#233]
Hi, if label clicking get enabled , how we can add an action once get clicked?

**Comment by kisvegabor** [comment]
Hi,

You should create the label on a button.
 The "clickable" attribute for a label is not really useful.

**Comment by Moo2017** [comment]
Thanks

**Comment by AbdullahBatiran** [comment]
So does that means I can't use labels as buttons?

Are not all objects have the same basic events?

**Comment by embeddedt** [comment]
This is a very old issue. As of at least v7, you can make labels clickable and register an event on them.

**Comment by AbdullahBatiran** [comment]
Thanks
