### ISSUE TITLE
Switch sends value changed two times.

### ISSUE THREAD

**Issue by grarup** [lvgl/lvgl#2330]
### Perform all steps below and tick them with [x]
- [x ] Check the related part of the [Documentation](https://docs.lvgl.io/)
- [x ] Update lvgl to the latest version
- [ x] Reproduce the issue in a [Simulator](https://docs.lvgl.io/latest/en/html/get-started/pc-simulator.html)

### Describe the bug
When clicking the a switch the LV_EVENT_VALUE_CHANGED is send two times.

Once from line 634 in lv_obj.c
```code
    else if(code == LV_EVENT_RELEASED) {
        lv_obj_clear_state(obj, LV_STATE_PRESSED);
        void * param = lv_event_get_param(e);
        /*Go the checked state if enabled*/
        if(lv_indev_get_scroll_obj(param) == NULL && lv_obj_has_flag(obj, LV_OBJ_FLAG_CHECKABLE)) {
            if(!(lv_obj_get_state(obj) & LV_STATE_CHECKED)) lv_obj_add_state(obj, LV_STATE_CHECKED);
            else lv_obj_clear_state(obj, LV_STATE_CHECKED);

            lv_res_t res = lv_event_send(obj, LV_EVENT_VALUE_CHANGED, NULL);
            if(res != LV_RES_OK) return;
        }
    }
```
and once from line 116 in lv_switch.c

```code
    else if(code == LV_EVENT_CLICKED) {
        uint32_t v = lv_obj_get_state(obj) & LV_STATE_CHECKED ? 1 : 0;
        res = lv_event_send(obj, LV_EVENT_VALUE_CHANGED, &v);
        if(res != LV_RES_OK) return;

        lv_obj_invalidate(obj);
    }

```
### Expected behavior
LV_EVENT_VALUE_CHANGED is only fired once.
### Screenshots or video
termincal up
´´´
switch changed to 28, 1 
switch changed to 28, 1
switch changed to 28, 0
switch changed to 28, 0
switch changed to 28, 1
switch changed to 28, 1
switch changed to 28, 0
switch changed to 28, 0
´´´´

**Comment by kisvegabor** [comment]
Thanks, I fixed it.
