### ISSUE TITLE
src/extra/layouts/flex/lv_flex.c(line:263):null pointer passed as argument 2

### ISSUE THREAD

**Issue by guoweilkd** [lvgl/lvgl#2331]
occur runtime error:null pointer passed as argument 2, which is declared to never be null. in lv_flex.c(line:263) if open asan.

The reasons is The first loop`t->grow_dsc = NULL`, so, we need add the judgment ,like this:
```
if (t->grow_dsc) {
     lv_memcpy(new_dsc, t->grow_dsc, sizeof(grow_dsc_t) * (t->grow_item_cnt - 1));
     lv_mem_buf_release(t->grow_dsc);
}

```

**Comment by kisvegabor** [comment]
Thanks, fixed as have you suggested.
