### ISSUE TITLE
When do you plan to support LV_ STATE_ HOVERED??

### ISSUE THREAD

**Issue by hurryboylqs** [lvgl/lvgl#2333]
If you implement this state, the mouse experience is better!

**Comment by embeddedt** [comment]
We typically prioritize the touchscreen experience (as these are much more popular than mice), so I think this is probably a lower priority. Hovering only makes sense on a touch screen if you are tracking the position of a pen being held above it.

**Comment by kisvegabor** [comment]
I added as plan [in to v8.2](https://github.com/lvgl/lvgl/blob/master/docs/ROADMAP.md#v82).

**Comment by kisvegabor** [comment]
I close this issue as the feature is added to the ROADMAP.
