### ISSUE TITLE
setting style on textarea in one line mode does not update.

### ISSUE THREAD

**Issue by grarup** [lvgl/lvgl#2335]
### Perform all steps below and tick them with [x]
- [x] Check the related part of the [Documentation](https://docs.lvgl.io/)
- [x] Update lvgl to the latest version
- [x] Reproduce the issue in a [Simulator](https://docs.lvgl.io/latest/en/html/get-started/pc-simulator.html)

### Describe the bug
If applying a style to a textarea after a it is set to one line, it will not update its size.

### To Reproduce
```c
    lv_obj_t * root = lv_obj_create(NULL);

    lv_obj_set_layout(root, LV_LAYOUT_FLEX);
    lv_obj_set_flex_flow(root, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(root, LV_ALIGN_CENTER, LV_ALIGN_CENTER, LV_ALIGN_CENTER);

    static lv_style_t style;
    lv_style_init(&style);
    lv_style_set_height(&style, 50);
    lv_style_set_text_font(&style, &lv_font_montserrat_22);

    lv_obj_t * textarea1 = lv_textarea_create(root);
    lv_textarea_set_placeholder_text(textarea1, "Line 1");
    lv_textarea_set_one_line(textarea1, true);
    lv_obj_add_style(textarea1, &style, 0);

    lv_obj_t * textarea2 = lv_textarea_create(root);
    lv_textarea_set_placeholder_text(textarea2, "Line 2");
    lv_textarea_set_one_line(textarea2, true);

    lv_scr_load(root);
```
### Expected behavior
size can be set with style and update when you change font.

### Screenshots or video
![image](https://user-images.githubusercontent.com/12280620/123655318-2756e200-d82f-11eb-916e-c5c0b354e02b.png)

**Comment by kisvegabor** [comment]
Thanks, I've fixed it.
