### ISSUE TITLE
Scroll on focus without animation

### ISSUE THREAD

**Issue by boraozgen** [lvgl/lvgl#2342]
### Introduce the problem

In case `LV_OBJ_FLAG_SCROLL_ON_FOCUS` is set, the object scrolls into view when focused:

https://github.com/lvgl/lvgl/blob/77cedfa08f3f8aec67c6a2fe8e5ae9bab5a0e7c7/src/core/lv_obj.c#L671-L673

Here, the scroll animation is on by default and cannot be turned off.

### Examples and cases

Turning off these animations could be important for resource-constrained, keypad based systems, where the animations are slow, yet scrolling is desired.

### Suggested solution

We can make this configurable, the place and switch name are up to the maintainers.

**Comment by kisvegabor** [comment]
Thanks for the suggestion.

A similar issue came up once to disable to scroll animation when the tabview changes tab. The use case was the same: animations are ugly on a slow screen.

The idea of mimicking CSS's [prefers-reduced-motion](https://css-tricks.com/introduction-reduced-motion-media-query/) also came up but finally, we found a [local solution](https://docs.lvgl.io/master/widgets/extra/tabview.html#tabs-on-the-left-styling-and-no-scrolling) to it.

Thinking about it again `prefers-reduced-motion` as a display driver option seems like a flexible solution.

@embeddedt @boraozgen What do you think?

**Comment by embeddedt** [comment]
I think `LV_EVENT_SCROLL_BEGIN` bubbles to parent objects, so can't animations be disabled simply by adding [this event handler](https://github.com/lvgl/lvgl/blob/ebb9ce913e604055724fd5f72562c9de0933ff73/examples/widgets/tabview/lv_example_tabview_2.c#L4-L11) to `lv_scr_act()`?

**Comment by boraozgen** [comment]
Attaching it to the screen doesn't seem to call the event handler. It is not in the bubbled list anyway:

https://github.com/lvgl/lvgl/blob/ebb9ce913e604055724fd5f72562c9de0933ff73/src/core/lv_event.c#L405

Attaching it to the scrollable object gets the handler called, but does not seem to disable the animation for me. I'm running v8.0.1, if that makes any difference.

Edit: I just checked `lv_anim_start` and the animation seems to be copied, so how should modifying the original animation time affect the already started animation?

> Thinking about it again `prefers-reduced-motion` as a display driver option seems like a flexible solution.

This should not disable animations completely, as animations with small objects usually run OK. I think I would prefer switches/configurations for each use case, providing more flexibility.

**Comment by embeddedt** [comment]
> This should not disable animations completely, as animations with small objects usually run OK. I think I would prefer switches/configurations for each use case, providing more flexibility.

I agree; that's why I suggested the bubbling approach. I'll need to test it to find out why it's not being bubbled; the list in `event_is_bubbled` is a blacklist of which events should not be bubbled, from my understanding.

> I just checked `lv_anim_start` and the animation seems to be copied, so how should modifying the original animation time affect the already started animation?

`LV_EVENT_SCROLL_BEGIN` is fired before `lv_anim_start` gets called:

https://github.com/lvgl/lvgl/blob/ebb9ce913e604055724fd5f72562c9de0933ff73/src/core/lv_obj_scroll.c#L274-L276

**Comment by boraozgen** [comment]
> `LV_EVENT_SCROLL_BEGIN` is fired before `lv_anim_start` gets called:

Not for y direction :) is there a particular reason or is it a bug?

> the list in `event_is_bubbled` is a blacklist of which events should not be bubbled, from my understanding.

True. I checked again, my object seems to have `LV_OBJ_FLAG_EVENT_BUBBLE` not set. Does it have to be set explicitly?

**Comment by embeddedt** [comment]
> Not for y direction :) is there a particular reason or is it a bug?

That is indeed a bug. I see no reason why the two axes should behave differently. Thank you for pointing it out, and sorry that I missed it when you mentioned it earlier. :slightly_smiling_face: 

Fixed here: https://github.com/lvgl/lvgl/commit/b1589326d41924292fbc2c62b474dec288bc9da5

> I checked again, my object seems to have LV_OBJ_FLAG_EVENT_BUBBLE not set. Does it have to be set explicitly?

I thought it was enabled by default, but upon a closer look, it appears that you do have to set it manually. That makes my solution much more cumbersome, as you would essentially have to enable this flag on all your objects.

**Comment by boraozgen** [comment]
The `LV_EVENT_SCROLL_BEGIN` seems to solve it, however it's still kind of hacky.

BTW I noticed another issue: It looks weird when the scrollbar lights up when the animation is disabled. It flashes once as the scrolling takes just a moment. Can we disable this too?

**Comment by boraozgen** [comment]
> Fixed here: [b158932](https://github.com/lvgl/lvgl/commit/b1589326d41924292fbc2c62b474dec288bc9da5)

Thanks. Are the fixes going to be cherry picked into v8 during release? Did you consider another branch model?

**Comment by embeddedt** [comment]
Yes. As of v8, minor versions receive fixes for 1 year as well, so 8.0.2 should arrive sooner rather than later.

**Comment by kisvegabor** [comment]
The scroll events are not bubbled as it'd mean a huge amount of `LV_EVENT_SCROLL`s.

> BTW I noticed another issue: It looks weird when the scrollbar lights up when the animation is disabled. It flashes once as the scrolling takes just a moment. Can we disable this too?

You can disable the scroll "effect" with
```c
    lv_obj_remove_style(cont, NULL, LV_PART_SCROLLBAR | LV_STATE_SCROLLED);
```

**Comment by boraozgen** [comment]
Thanks. Then my issue is resolved, you can close the issue or leave it open depending on whether you think it makes sense to add a configuration for this.

**Comment by kisvegabor** [comment]
Great!

Let's see if we get other related issues. If so we can find a more generic solution.  So I close this issue for now.

**Comment by boraozgen** [comment]
I came up with an idea while I was trying to disable the animations for `lv_roller`. There, we can set the `anim_time` style to zero, which basically disables the animations. Could this be applied to the scrollbars, i.e. when the style is applied to the container object, the scrollbar animation time changes accordingly?

**Comment by kisvegabor** [comment]
By the scrollbar animation do you mean
1. the opacity animation of the scrollbar?
2. the movement of the scrollbar and scrolling in general?

**Comment by boraozgen** [comment]
I mean the movement of the scrollbar.

**Comment by kisvegabor** [comment]
I'd find it a little bit misleading as not really to scrollbar is moving. It's just an indicator of the moving content.

**Comment by 36221768** [comment]
problems using LV_OBJ_FLAG_SCROLL_ON_FOCUS, I'm trying to auto-scroll objects, but the flag doesn't seem to work:         // Create a text area for logging
        ui_text_area = lv_textarea_create(ui_pnlMain);
        lv_obj_set_x(ui_text_area, 0);
        lv_obj_set_y(ui_text_area, lv_pct(15));
        lv_obj_set_width(ui_text_area, lv_pct(100));
        lv_obj_set_height(ui_text_area, lv_pct(75));
        lv_obj_set_align(ui_text_area, LV_ALIGN_TOP_LEFT);
        // make object unclickable by input devices
        lv_obj_clear_flag(ui_text_area, LV_OBJ_FLAG_CLICKABLE);
        // 
        lv_obj_add_flag(ui_text_area, LV_OBJ_FLAG_SCROLLABLE);
        lv_obj_add_flag(ui_text_area, LV_OBJ_FLAG_SCROLL_ON_FOCUS);

**Comment by kisvegabor** [comment]
This issue is quite old. Please open a new one.
