### ISSUE TITLE
DROPDOWN border Color cannot be set when  "LV_STATE_PRESSED"

### ISSUE THREAD

**Issue by zq190kg** [lvgl/lvgl#2344]
LVGL 7.1.0
lv_obj_set_style_local_border_color(ddlist, LV_DROPDOWN_PART_MAIN, LV_STATE_PRESSED, LV_COLOR_WHITE); this funtion unwork.

  but the bg_color is ok.
lv_obj_set_style_local_bg_color(ddlist, LV_DROPDOWN_PART_MAIN, LV_STATE_PRESSED, LV_COLOR_RED);

**Comment by kisvegabor** [comment]
Is it really v7.1? Not v7.11?
