### ISSUE TITLE
Occasional hardfault in lv_group_add_obj

### ISSUE THREAD

**Issue by kiwih** [lvgl/lvgl#236]
I noticed that occasionally my microcontroller was hardfaulting when calling `lv_group_add_obj`.

I traced the error to `lv_group_focus_next` calling `focus_cb` on an uninitialised callback function.

Fix: In `lv_group_create`, add the line `group->focus_cb = NULL;`

**Comment by kisvegabor** [comment]
Hi,

Thank you very much for reporting the issue! 

This issue is already fixed in the `beta` branch and will be released soon as part of v5.1.1.
