### ISSUE TITLE
Getting too many errors while compiling after enabling "lv_port_indev" 

### ISSUE THREAD

**Issue by jojomojo93** [lvgl/lvgl#2361]
### Perform all steps below and tick them with [x]
- [x ] Check the related part of the [Documentation](https://docs.lvgl.io/)
- [x ] Update lvgl to the latest version
- [x ] Reproduce the issue in a [Simulator](https://docs.lvgl.io/latest/en/html/get-started/pc-simulator.html)

### Describe the bug

After enabling lv_port_indev.c file by changing the if value from 0 to 1 I get too many errors while compiling
I'm compiling using cmake and make commands on RPi using LVGL PC simulator files. 

### Screenshots or video

![image](https://user-images.githubusercontent.com/31178063/124944809-4d8e3600-e016-11eb-84ae-677c5dc7b788.png)

**Comment by kisvegabor** [comment]
Thanks, I've just fixed it.
