### ISSUE TITLE
issue for pos

### ISSUE THREAD

**Issue by ZhaoQiang-b45475** [lvgl/lvgl#2362]
I create a btn and set pos to (100, 200).
then get_x from btn and print, the value is 0.
   
    lv_obj_t *btn = lv_btn_create(lv_scr_act());
    lv_obj_set_pos(btn, 100, 200);
    printf("=====pos x: %d\n", lv_obj_get_x(btn));

**Comment by kisvegabor** [comment]
See the docs [here](https://docs.lvgl.io/master/overview/coords.html#postponed-coordinate-calculation)
