### ISSUE TITLE
Getting errors when enabling "lv_port_invdev.c" on my RPi 3B+

### ISSUE THREAD

**Issue by jojomojo93** [lvgl/lvgl#2363]
### Perform all steps below and tick them with [x]
- [x ] Check the related part of the [Documentation](https://docs.lvgl.io/)
- [x ] Update lvgl to the latest version
- [x ] Reproduce the issue in a [Simulator](https://docs.lvgl.io/latest/en/html/get-started/pc-simulator.html)

### Describe the bug
After enabling the "lv_port_invdev.c" file by changing the "if statement" at the begining  from 0 to 1, I get some errors related to some functions arguments and declaration conflicts - see below screenshot.

### To Reproduce
1-Use the PC simulator files
2-Might need to "#include "../../lvgl.h" as it seems to be missing in "lv_port_invdev.c" file
3-cmake .
4-make all and you'll get the below errors
"
### Screenshots or video
![image](https://user-images.githubusercontent.com/31178063/125154061-baade280-e160-11eb-9e7f-9d29bcbbf340.png)

**Comment by embeddedt** [comment]
Thanks; this should be fixed in latest `master` (and will be backported to 8.0).
