### ISSUE TITLE
LVGL slows down with more widgets, even if hidden

### ISSUE THREAD

**Issue by fredbar** [lvgl/lvgl#2370]
### Perform all steps below and tick them with [x]
- [x ] Check the related part of the [Documentation](https://docs.lvgl.io/)
- [ x] Update lvgl to the latest version 
- [x ] Reproduce the issue in a [Simulator](https://docs.lvgl.io/latest/en/html/get-started/pc-simulator.html)

### Describe the bug

I have an interface with lots of objects. (homemade keyboards, tab-like panels filled with widgets and styles). Only one is visible at a time and i play with the "hidden" attribute to display the one i really want at any moment. The more i add, the sluggish the interface becomes. (pool is 64KB actually and just fits)
Not creating a keyboard (about 40 buttons, a few styles and some images) accelerates the display by 30%, although the keyboard is hidden.

This is 7.11, can not go 8.0 because it is a contracted project where time is running out. We are near release of the project and it will not be ported. (to my despair)

### To Reproduce

I can not share original code and slowdown is only really visible on "already slow" mcu. So, simulator is not a way to see the bug, still i tried. I can however (happily) write code that creates a bunch of containers and widgets inside but i am really not sure that would be of any help. I do believe those who know the code already see where to check for tree transversal that forgot to check for the hidden state. (very wild guess, but logical to me) Tried to find that part but failed.

### Expected behavior

Hidden objects and their children should not consume any cpu when display is being refreshed.

### Screenshots or video
no video available.

**Comment by kisvegabor** [comment]
Some code to see the issue would be great even if they are only containers. 

What is sluggish? The rendering or the reaction to button presses?

**Comment by fredbar** [comment]
Hi.

RIght, i'll send code that got tested on my stm32 in a moment. 

Both get slower, by the way.

**Comment by fredbar** [comment]
ok, please check the code below. There is a define for the count of panes added. 
I also made a video with two pane count; 1 and 5. That should make it more clear.
Event code might not work, i had to embed the code in my program and it was not happy with the interface change, causing it to hang without me having a chance to test that. So this part is pretty untested.

video:
https://youtu.be/O-KyST3Ox4M

code:
```
#define LVGLISSUE_1_PANECOUNT 5

lv_obj_t *painPanes[LVGLISSUE_1_PANECOUNT];

void lvglIssue_1_btnCB(lv_obj_t *obj, lv_event_t event) {
// on a button press, go to next pane.
	static uint8_t pageIndex = 0;
	lv_obj_set_hidden(painPanes[pageIndex], true);
	pageIndex++;
	pageIndex %= LVGLISSUE_1_PANECOUNT;
	lv_obj_set_hidden(painPanes[pageIndex], false);
}

void lvglIssue_1_createStyles() {
	lv_style_init(&buttonStyle);
	lv_style_init(&bgStyle);

	lv_style_set_text_color(&buttonStyle, LV_STATE_DEFAULT,
			lv_color_make(0x00, 0x00, 0x00));
	lv_style_set_image_recolor(&buttonStyle, LV_STATE_DEFAULT,
	LV_COLOR_WHITE);
	lv_style_set_image_recolor_opa(&buttonStyle, LV_STATE_DEFAULT, 255);
	lv_style_set_image_opa(&buttonStyle, LV_STATE_DEFAULT, 255);
	lv_style_set_bg_opa(&buttonStyle, LV_STATE_DEFAULT, LV_OPA_COVER);
	lv_style_set_bg_color(&buttonStyle, LV_STATE_CHECKED, LV_COLOR_BLUE);
	lv_style_set_bg_color(&buttonStyle, LV_STATE_DEFAULT, LV_COLOR_SILVER);
	lv_style_set_radius(&buttonStyle, LV_STATE_DEFAULT, 5);
	lv_style_set_clip_corner(&buttonStyle, LV_STATE_DEFAULT, true);
	lv_style_set_border_width(&buttonStyle, LV_STATE_DEFAULT, 2);
	lv_style_set_border_color(&buttonStyle, LV_STATE_DEFAULT,
	LV_COLOR_WHITE);
	lv_style_set_bg_color(&bgStyle, LV_STATE_DEFAULT, bgBlue);
}

void lvglIssue_1_createwidgets() {
	lvglIssue_1_createStyles();
	for (int index = 0; index < LVGLISSUE_1_PANECOUNT; index++) {
		painPanes[index] = lv_obj_create(lv_scr_act(), NULL);

		lv_obj_t *pane = painPanes[index];
		lv_obj_set_pos(pane, 0, 0);
		lv_obj_set_size(pane, 800, 480);				//yeah...:)
		lv_obj_add_style(pane, LV_OBJ_PART_MAIN, &bgStyle);
		lv_obj_set_hidden(pane, true);
		for (int yPos = 10; yPos < 480 - 60; yPos += 60) {
			for (int xPos = 10; xPos < 800 - 60; xPos += 60) {
				lv_obj_t *btn = lv_btn_create(pane, NULL);
				lv_obj_set_pos(btn, xPos, yPos);
				lv_obj_set_size(btn, 50, 50);				//yeah...:)
				lv_obj_add_style(btn, LV_BTN_PART_MAIN, &buttonStyle);
				lv_obj_set_event_cb(btn, lvglIssue_1_btnCB);
			}
		}
	}
	lv_obj_set_hidden(painPanes[0], false);
  lv_scr_load(painPanes[0]);
}

```

**Comment by fredbar** [comment]
I also tried moving the hidden panes far out of the display in case there was a bounding box elimination but that did not help.

**Comment by kisvegabor** [comment]
I've checked the source code of v7 and haven't found anything obvious at first look.

But there is something strange in your code. You use `lv_scr_load(painPanes[0]);` but `painPanes[0]` is not screen as it was created with `painPanes[index] = lv_obj_create(lv_scr_act(), NULL);`. To create it as a screen use `painPanes[index] = lv_obj_create(NULL, NULL);`. But in this case you don't need to hide the panes as the screens are "separated" from eachother very well.

**Comment by fredbar** [comment]
Yes, i somewhat fumbled here. In my application, i have a single pane that then references all other panes.
Sorry for the misleading representation.

However, in the end that makes no difference. There is still a slowdown depending on the count of created buttons only, not on those that are displayed.

**Comment by fredbar** [comment]
I thought about only creating panes when i have to display them and dispose them when i swap, but then i have an other problem with the app freezing two seconds when i create the keyboard. Not really user friendly.
And also i worried about memory fragmentation if going that route. Not sure how LVGL reacts  on that point.

**Comment by kisvegabor** [comment]
> However, in the end that makes no difference. There is still a slowdown depending on the count of created buttons only, not on those that are displayed.

You have fixed the screen creation issue, right? 

If you are using STM32 you can use SWV as a profiler to see which functions take so much time. Can you give it a try?

Memory fragmentation is usually not an issue in normal use cases.  So you can create the panes on demand.

**Comment by fredbar** [comment]
Screen creation is okay. I just did not do exactly what i had in my original program.

Anyway, i did some tracing. Sampling is done from right before creating styles to right after the call to LV_task_handler(). Idea behind that was to get profiling for both construction and a single rendering. 

216Mhz, 256 ticks per samples. Took values over 0.1% only.

1 pane
```
"_lv_memset_00()";"7.97%";"285";"0x8048bdd";"0x102"
"get_style_prop()";"7.72%";"276";"0x8037db5";"0x3e"
"HAL_GetTick()";"7.41%";"265";"0x80054d5";"0x18"
"get_prop_size()";"6.82%";"244";"0x8037e33";"0x54"
"get_property_index()";"5.76%";"206";"0x8037c05";"0xe0"
"obj_valid_child()";"5.45%";"195";"0x80347ad";"0x58"
"memcpy()";"5.37%";"192";"0x8056d7d";"0x1c"
"HAL_Delay()";"4.31%";"154";"0x80054ed";"0x48"
"get_next_prop_index()";"4.11%";"147";"0x8037e87";"0x22"
"_lv_ll_get_head()";"4.05%";"145";"0x8047ca5";"0x26"
"lv_obj_get_type()";"3.61%";"129";"0x803238d";"0xf0"
"get_style_prop_id()";"3.47%";"124";"0x8037df3";"0x1e"
"I2C_WaitOnFlagUntilTimeout()";"3.16%";"113";"0x800ace3";"0x80"
"_lv_ll_get_next()";"2.88%";"103";"0x8047cf1";"0x34"
"lv_debug_check_obj_valid()";"2.46%";"88";"0x80331d3";"0x6e"
"ent_get_next()";"2.32%";"83";"0x8048df5";"0x58"
"lv_debug_check_obj_type()";"1.98%";"71";"0x8033153";"0x80"
"lv_obj_handle_get_type_signal()";"1.76%";"63";"0x8032639";"0x44"
"lv_debug_check_null()";"1.26%";"45";"0x80477c3";"0x20"
"strcmp()";"1.15%";"41";"0x8000241";"0x14"
"_lv_obj_get_style_int()";"1.09%";"39";"0x80314d1";"0x57a"
"lv_obj_signal()";"1.03%";"37";"0x8033755";"0x174"
"lv_cont_signal()";"0.92%";"33";"0x8053975";"0xf8"
"_lv_style_list_get_int()";"0.89%";"32";"0x8037721";"0x124"
"ent_alloc()";"0.78%";"28";"0x8048e4d";"0x4e"
"lv_disp_get_next()";"0.70%";"25";"0x8046085";"0x30"
"lv_btn_signal()";"0.64%";"23";"0x8053395";"0x150"
"lv_mem_test()";"0.56%";"20";"0x804832d";"0x60"
"lv_style_list_get_style()";"0.50%";"18";"0x8036569";"0x6a"
"_lv_area_intersect()";"0.48%";"17";"0x8046b0d";"0xa2"
"lv_obj_get_state()";"0.45%";"16";"0x80321d5";"0x8c"
"fill_normal()";"0.39%";"14";"0x8038511";"0x64a"
"lv_debug_check_style()";"0.36%";"13";"0x8037b9d";"0x34"
"wait_finish()";"0.34%";"12";"0x8045c71";"0x44"
"_lv_style_get_int()";"0.31%";"11";"0x8037331";"0xb0"
"lv_obj_get_parent()";"0.31%";"11";"0x803102d";"0x64"
"lv_mem_alloc()";"0.28%";"10";"0x80480a5";"0x94"
"lv_obj_get_style_list()";"0.25%";"9";"0x8031489";"0x46"
"_lv_memcpy_small()";"0.25%";"9";"0x802dc29";"0x44"
"lv_color_fill()";"0.25%";"9";"0x8047661";"0x102"
"lv_draw_mask_radius()";"0.22%";"8";"0x803e4e9";"0x810"
"_lv_sqrt()";"0.22%";"8";"0x8047fad";"0x60"
"lv_debug_check_style_list()";"0.20%";"7";"0x8037bd1";"0x34"
"_lv_style_list_get_ptr()";"0.20%";"7";"0x8037a81";"0x11c"
"SysTick_Handler()";"0.17%";"6";"0x8025af9";"0x48"
"_lv_style_list_get_opa()";"0.17%";"6";"0x8037965";"0x11c"
"_lv_obj_get_style_opa()";"0.17%";"6";"0x8031b23";"0x186"
"_lv_memcpy_small()";"0.14%";"5";"0x803d5e1";"0x44"
"I2C_IsAcknowledgeFailed()";"0.14%";"5";"0x800ae5d";"0xcc"
"lv_color_mix()";"0.14%";"5";"0x8037ea9";"0xa4"
"lv_area_get_width()";"0.11%";"4";"0x8038031";"0x2e"
"lv_obj_area_is_visible()";"0.11%";"4";"0x802f4f9";"0x130"
"Unknown function";"0.11%";"4";"0x0";"0x0"
"draw_bg()";"0.11%";"4";"0x803f0a1";"0x7ca"
"_lv_obj_get_style_ptr()";"0.11%";"4";"0x8031ca9";"0x180"
"_lv_memcpy_small()";"0.11%";"4";"0x8036525";"0x44"
"update_style_cache()";"0.11%";"4";"0x8034b7d";"0x422"
"_lv_blend_fill()";"0.11%";"4";"0x803808d";"0x1a2"
"_lv_style_get_opa()";"0.11%";"4";"0x80373e1";"0xb0"
```

5 panes
```
"obj_valid_child()";"14.05%";"2175";"0x80347cd";"0x58"
"_lv_ll_get_next()";"7.84%";"1214";"0x8047d11";"0x34"
"_lv_ll_get_head()";"7.35%";"1137";"0x8047cc5";"0x26"
"_lv_memset_00()";"6.79%";"1050";"0x8048bfd";"0x102"
"get_style_prop()";"6.68%";"1033";"0x8037dd5";"0x3e"
"get_prop_size()";"6.45%";"998";"0x8037e53";"0x54"
"ent_get_next()";"5.19%";"803";"0x8048e15";"0x58"
"get_property_index()";"4.86%";"752";"0x8037c25";"0xe0"
"get_next_prop_index()";"4.05%";"626";"0x8037ea7";"0x22"
"lv_obj_get_type()";"3.42%";"530";"0x80323ad";"0xf0"
"get_style_prop_id()";"3.20%";"495";"0x8037e13";"0x1e"
"HAL_GetTick()";"2.68%";"415";"0x80054ed";"0x18"
"lv_debug_check_obj_valid()";"2.59%";"401";"0x80331f3";"0x6e"
"lv_debug_check_obj_type()";"1.99%";"308";"0x8033173";"0x80"
"lv_obj_handle_get_type_signal()";"1.93%";"298";"0x8032659";"0x44"
"HAL_Delay()";"1.91%";"296";"0x8005505";"0x48"
"ent_alloc()";"1.54%";"238";"0x8048e6d";"0x4e"
"memcpy()";"1.42%";"220";"0x8056d9d";"0x1c"
"lv_mem_alloc()";"1.34%";"207";"0x80480c5";"0x94"
"lv_mem_test()";"1.24%";"192";"0x804834d";"0x60"
"strcmp()";"1.20%";"185";"0x8000241";"0x14"
"lv_debug_check_null()";"0.92%";"142";"0x80477e3";"0x20"
"lv_cont_signal()";"0.89%";"137";"0x8053995";"0xf8"
"lv_obj_signal()";"0.87%";"134";"0x8033775";"0x174"
"_lv_obj_get_style_int()";"0.82%";"127";"0x80314f1";"0x57a"
"_lv_style_list_get_int()";"0.75%";"116";"0x8037741";"0x124"
"lv_btn_signal()";"0.63%";"97";"0x80533b5";"0x150"
"lv_disp_get_next()";"0.55%";"85";"0x80460a5";"0x30"
"_lv_style_get_int()";"0.40%";"62";"0x8037351";"0xb0"
"lv_debug_check_style()";"0.39%";"61";"0x8037bbd";"0x34"
"lv_obj_get_state()";"0.34%";"52";"0x80321f5";"0x8c"
"lv_style_list_get_style()";"0.33%";"51";"0x8036589";"0x6a"
"_lv_memcpy_small()";"0.32%";"50";"0x802dc49";"0x44"
"_lv_area_intersect()";"0.29%";"45";"0x8046b2d";"0xa2"
"fill_normal()";"0.25%";"38";"0x8038531";"0x64a"
"lv_draw_mask_radius()";"0.21%";"33";"0x803e509";"0x810"
"lv_obj_get_style_list()";"0.20%";"31";"0x80314a9";"0x46"
"lv_debug_check_style_list()";"0.19%";"29";"0x8037bf1";"0x34"
"lv_color_fill()";"0.18%";"28";"0x8047681";"0x102"
"_lv_obj_get_style_opa()";"0.17%";"27";"0x8031b43";"0x186"
"_lv_blend_fill()";"0.16%";"24";"0x80380ad";"0x1a2"
"_lv_sqrt()";"0.14%";"21";"0x8047fcd";"0x60"
"lv_obj_area_is_visible()";"0.13%";"20";"0x802f519";"0x130"
"lv_obj_get_parent()";"0.12%";"19";"0x803104d";"0x64"
"_lv_style_list_get_opa()";"0.12%";"18";"0x8037985";"0x11c"
"_lv_obj_get_style_ptr()";"0.11%";"17";"0x8031cc9";"0x180"
"update_style_cache()";"0.10%";"15";"0x8034b9d";"0x422"
```

**Comment by kisvegabor** [comment]
Ah, I think I see the problem. Be sure the `LV_USE_DEBUG` is `0` is `lv_conf.h`.

**Comment by fredbar** [comment]
Of course, that was it.. What an idiot i am.
Speed, not only the one of this use case but  the speed in general, increased tenfolds.
Thanks a huge bunch, all is nice and shiny now.

**Comment by kisvegabor** [comment]
I made this mistake several times as well. :slightly_smiling_face: 
In v8 I added warnings if slow asserts are enabled so I hope it will happen less often.

Anyway, glad to hear it's fast now :tada:
