### ISSUE TITLE
How to use 2 styles in a button, use style1 on the left half and style2 on the right half

### ISSUE THREAD

**Issue by Johnxjj** [lvgl/lvgl#2378]

**Comment by Johnxjj** [comment]
When the button is pressed, the styles of a/b, a and b can be switched.

**Comment by kisvegabor** [comment]
Do you mean to split the button like this?
```
---------------------
| A style | B style |
---------------------
```

If so it's not possible this way. Styles are related to the whole object.
However, you can use the [draw events](https://docs.lvgl.io/master/overview/drawing.html#hook-drawing) to make something.really custom

**Comment by Johnxjj** [comment]
@kisvegabor yeah, i mean it. Thanks! I will think about other methods.

**Comment by kisvegabor** [comment]
Okay. :slightly_smiling_face: 
I close it then.
