### ISSUE TITLE
line_2d_blur

### ISSUE THREAD

**Issue by dmabl** [lvgl/lvgl#238]
lv_draw.c
In function lv_draw_shadow_full()

```
lv_opa_t line_2d_blur[radius + swidth]; // 0 +11 in my proj
...
for(col = 1; col < radius + swidth + 10; col++) {
...
line_2d_blur[col] = ...
}

```
It's out of borders( 21 in my demo_create() ). Why +10?

And maybe change this file  to remove dinamic arrays? For portability.
For example:
`lv_opa_t line_2d_blur[radius + swidth];`
to
```
lv_opa_t * line_2d_blur = lv_mem_alloc((radius + swidth) * sizeof(lv_opa_t));
...
lv_mem_free(line_2d_blur );
```
and so on.

**Comment by kisvegabor** [comment]
Hi,

Thank you for the great remark!
 
I checked and it seems the +10 left there during development. I fixed it in the beta `branch`

In the new v5.1.1 release  there will be an option in lv_conf.h to not use VLA. You can already see it in the `beta` branch.
