### ISSUE TITLE
lv_label_set_text get dead loop

### ISSUE THREAD

**Issue by 791136190** [lvgl/lvgl#2386]
### Perform all steps below and tick them with [x]
- [√ ] Check the related part of the [Documentation](https://docs.lvgl.io/)
- [√ ] Update lvgl to the latest version
- [ √] Reproduce the issue in a [Simulator](https://docs.lvgl.io/latest/en/html/get-started/pc-simulator.html)

### Describe the bug

When I generate a large number of obj (about 160) and generate the corresponding label obj. When I use lv_label_set_text to set the text, whenever I set the 17th label text, the system enters the loop. I use gdb to test and find that the nanosleep function is at the end.

**Comment by kisvegabor** [comment]
Please send a code snippet to reproduce.
