### ISSUE TITLE
Area being invalidated is larger than expected when redrawing Line component

### ISSUE THREAD

**Issue by AfflatusX** [lvgl/lvgl#2391]
### Describe the bug
We're on LVGL 7.4 since we can't upgrade at this moment. The issue is that we have a rotating line (think of it as a second hand in a watch), we rotate that every second, the line starts at 12 o'clock direction.

We added code to record on each tick which area of the screen is being invalidated - and the area is much larger than it should be. It always starts from 0,0 for some reason. This is very different from a label component or simply using canvas to do it.

### To Reproduce
lv_obj_t* line = lv_line_create(0);
lv_point_t *line_points_1 = (lv_point_t *)malloc(sizeof(lv_point_t) * 2);
line_points_1[0].x = 160;
line_points_1[0].y = 160;

line_points_1[1].x = 160;
line_points_1[1].y = 0;
lv_line_set_points(obj, line_points_1, 2);

// wait for 1 sec
lv_point_t *line_points_2 = (lv_point_t *)malloc(sizeof(lv_point_t) * 2);
line_points_2[0].x = 160;
line_points_2[0].y = 160;

line_points_2[1].x = 165;
line_points_2[1].y = 10;
lv_line_set_points(obj, line_points_2, 2);

### Expected behavior
The invalidated area should start from (160,0) to (165, 160)

**Comment by kisvegabor** [comment]
This size of the widget is set automatically to involve all the points and on invalidation the widget's size is invalidated not the line's coordinates.

However, you can improve `lv_line_set_points` to find the min/max x and y coordinates of the old and new points and invalidate only that coordiantes.
