### ISSUE TITLE
demo stops

### ISSUE THREAD

**Issue by liubingyan123** [lvgl/lvgl#240]
Hi, I am workong on porting lvgl to stm32f413 discovery board, and it works. but the picture stops when I slide from "Write" tab to "List" tab, shown as flowing picture, I cheak the heap and stack(demo runs on FreeRTOS),  but find nothing abnormal， how does it happen? what will cause it? please offer me some advices, thank you!
![img_20180508_201031](https://user-images.githubusercontent.com/14269886/39757135-7fbc0a88-52fe-11e8-9e02-856a028e42ba.jpg)

**Comment by kisvegabor** [comment]
Does it solved meanwhile?

**Comment by liubingyan123** [comment]
yes,  I have solved this problem, and lvgl works well in STM32F413 discovery board.

**Comment by kisvegabor** [comment]
Can you tell us what was the problem? Just to learn from it.
