### ISSUE TITLE
LVGL doesn't link when added to non-main ESP-IDF component

### ISSUE THREAD

**Issue by sidwarkd** [lvgl/lvgl#2403]
### Perform all steps below and tick them with [x]
- [x] Check the related part of the [Documentation](https://docs.lvgl.io/)
- [x] Update lvgl to the latest version
- [ ] Reproduce the issue in a [Simulator](https://docs.lvgl.io/latest/en/html/get-started/pc-simulator.html)

### Describe the bug
Using lvgl as an ESP-IDF component from within another ESP-IDF component that is not the main component fails to link. Throws multiple undefined reference errors.

### To Reproduce
Instead of adding lvgl code to main.c or main.cpp try using the library in another ESP-IDF component and calling that component from main. It will fail to link.

### Expected behavior
Using lvgl from ESP-IDF components other than `main` should link properly.

### Suggested Fix
The [CMakeLists.txt file for lvgl `REQUIRES main`](https://github.com/lvgl/lvgl/blob/105bf24318a6d70d758223bb87ac44c5521cc341/CMakeLists.txt#L7) which it should not to be a true component. This seems to create a circular dependency issue. Removing the REQUIRES fixed the issue for me.

**Comment by kisvegabor** [comment]
cc @tore-espressif, @C47D

**Comment by tore-espressif** [comment]
Related:
https://github.com/lvgl/lv_port_esp32/issues/274
https://github.com/espressif/esp-idf/issues/6932

@sidwarkd thank you for the troubleshooting. Do you want to file a PR? Or should we take over?

**Comment by sidwarkd** [comment]
@tore-espressif I'm happy to submit a PR but want to make sure I at least have some time to test it in both the out-of-box main component config as well as in a custom component to make sure it doesn't cause a major regression. Super busy right now but I'll try to get to it in the next couple of days. Otherwise I'll let you know.

**Comment by C47D** [comment]
Hi @sidwarkd , sorry for the late reply, I've seen in the referenced issues by @tore-espressif that your patch does seems to fix the issue, are you planning to submit a PR?

**Comment by sidwarkd** [comment]
@C47D Yes, I will get a PR submitted this weekend

**Comment by kisvegabor** [comment]
Thanks, I merged the PR.
