### ISSUE TITLE
Events

### ISSUE THREAD

**Issue by Miguel0101** [lvgl/lvgl#2405]
### It's not a problem, just a question.

When using two events on an object for example `LV_EVENT_CLICKED `and `LV_EVENT_LONG_PRESSED `and long press and release both events are executed. Is there a way to fix this?

**Comment by embeddedt** [comment]
I think you are looking for `LV_EVENT_SHORT_CLICKED`.

----------------------
We use GitHub issues for development related discussions.
Please use the [forum](https://forum.littlevgl.com/) to ask questions.

It's possible to sign in to the forum with your GitHub account... you don't need to make a separate account.

**Comment by Miguel0101** [comment]
> I think you are looking for `LV_EVENT_SHORT_CLICKED`.
> 
> We use GitHub issues for development related discussions.
> Please use the [forum](https://forum.littlevgl.com/) to ask questions.
> 
> It's possible to sign in to the forum with your GitHub account... you don't need to make a separate account.

Ok, thanks!
