### ISSUE TITLE
Error on the meter widget

### ISSUE THREAD

**Issue by uraich** [lvgl/lvgl#2407]
### Perform all steps below and tick them with [x]
- [x] Check the related part of the [Documentation](https://docs.lvgl.io/)
- [x] Update lvgl to the latest version
- [x] Reproduce the issue in a [Simulator](https://docs.lvgl.io/latest/en/html/get-started/pc-simulator.html)

### Describe the bug
The tick marks on the meter are wrong in example lv_example_meter_1

### To Reproduce
Run lv_example_meter_1

### Expected behavior
Short tick marks

### Screenshots or video
![image](https://user-images.githubusercontent.com/1673533/127004261-52f8a83c-cae1-4c88-87f9-ae46762c2d9e.png)

**Comment by kisvegabor** [comment]
Thanks, I've just fixed it.
