### ISSUE TITLE
lv_img

### ISSUE THREAD

**Issue by Miguel0101** [lvgl/lvgl#2416]
### It's not a problem just a suggestion.

Is there any way to resize images per pixels(WIDTH x HEIGHT), for example a 320x240 image and resize to 300x200?

**Comment by embeddedt** [comment]
You can calculate the ratio between the two sizes, multiply it by 256, and use `lv_img_set_zoom(img, <the result>)`. See [the docs](https://docs.lvgl.io/master/widgets/core/img.html#transformations) for more information.

**Comment by Miguel0101** [comment]
> You can calculate the ratio between the two sizes, multiply it by 256, and use `lv_img_set_zoom(img, <the result>)`. See [the docs](https://docs.lvgl.io/master/widgets/core/img.html#transformations) for more information.

In width and height?

So would it be W/H * 256?

**Comment by embeddedt** [comment]
No. I mean the ratio between the area of the images. `(w2/w1)*256`

As far as I know you cannot set the scaling amount for individual axes.

**Comment by Miguel0101** [comment]
> No. I mean the ratio between the area of the images. `(w2/w1)*256`
> 
> As far as I know you cannot set the scaling amount for individual axes.

So i have calculate the image area?

**Comment by embeddedt** [comment]
Yes, but that’s just width times height.

**Comment by Miguel0101** [comment]
> Yes, but that’s just width times height.

Okay, thanks @embeddedt.

**Comment by kisvegabor** [comment]
> As far as I know you cannot set the scaling amount for individual axes.

It really isn't but in some cases, I found that an `aspect ratio` property would be great. E.g. if a flexbox sets a width for a container it'd be great to automatically make it a square.
