### ISSUE TITLE
Drop-down list, list not closing when losing focus by scrolling container

### ISSUE THREAD

**Issue by JefkeB** [lvgl/lvgl#2417]
### Perform all steps below and tick them with [x]
- [x] Check the related part of the [Documentation](https://docs.lvgl.io/)
- [x] Update lvgl to the latest version
- [x] Reproduce the issue in a [Simulator](https://docs.lvgl.io/latest/en/html/get-started/pc-simulator.html)

### Describe the bug
Using latest V8 of the library.
When adding a drop-down list to a scrollable container and opening the list by clicking the dropdown it will show the list as expected. But when the container is dragged the list part for the ddl is also moving away.

### To Reproduce
run this in the simulator
```c
void lv_ddl()
{
  lv_obj_t * page = lv_obj_create(lv_scr_act());
  lv_obj_set_size(page, LV_PCT(100), 200);

  lv_obj_t * container = lv_obj_create(page);
  lv_obj_set_size(container, 500, 1000);
  lv_obj_set_flex_flow(container, LV_FLEX_FLOW_COLUMN);
  lv_obj_clear_flag(container, LV_OBJ_FLAG_SCROLLABLE);


  lv_obj_t * ddl;
  ddl = lv_dropdown_create(container);
  ddl = lv_dropdown_create(container);
  ddl = lv_dropdown_create(container);
}
```

### Expected behavior
The list part should close when losing focus while dragging the container

### Screenshots or video
![2021-07-29 20_52_58-Ubuntu-dev](https://user-images.githubusercontent.com/37012100/127549767-bafd6e95-d8f9-43ed-bf78-316243061227.png)

**Comment by kisvegabor** [comment]
Thanks for the report. If found that this issue was introduced by 76a82933

I couldn't see a better way than reverting that commit.
