### ISSUE TITLE
highlighted row in kb obj

### ISSUE THREAD

**Issue by Moo2017** [lvgl/lvgl#242]
Hi,
I created a keyboard object and I want to have predict dictionary. since I am using hardware keyboard and I only have navigation and select key , to select the predicted text I want to use up/down keys as if the first row of the keyboard is selected and user presses the up key ( or the last row and down key) the predict list is selected but I don' know how can I do that and where this is handled ? maybe if I know that which row in the keyboard has been highlighted I can do this.

**Comment by kisvegabor** [comment]
Hi,

It's a quite special thing which is difficult to handle by only external buttons.
Exactly which keys do you have?

**Comment by Moo2017** [comment]
I have only up/down/left/right and OK key. now I want to have a keyboard and once user typed a character I should search from a table and display a list of options that matches with the character ( same as address book) , see the below photo:
predict
![predict](https://user-images.githubusercontent.com/34062463/40194948-08c6d7fe-59da-11e8-9fd2-80aea3723eba.jpg)

once options are displayed user may wanted to selected from them , but all the keys are assigned to the keyboard. One solution can be using up/down key if one of the btns from the first row of the keyboard or last row have been selected ( if for example "`1#" is selected form keyboard pressing UP key do nothing) . I need to know which btn from the keyboard or at least which row currently has been selected and if it's the first row and user presses UP arrow key , I can focus other object rather than keyboard and user can move among them using Left/Right arrow keys and also retuns back to the keyboard.

**Comment by kisvegabor** [comment]
Just to keep the threads consistent:

Similarly to Button matrix you can set a new map for the keyboard as well. Your new map should have an extra row on the top with the suggestions.
Maybe it would be better to use a Button matrix instead of the Keyboard because the Button matrix is more flexible.

**Comment by Moo2017** [comment]
Ok Thanks  I'll try this.

**Comment by kisvegabor** [comment]
As there wasn't activity here for months I close this issue.
If you have a similar question feel free to comment here and reopen the issue!
