### ISSUE TITLE
The default font cannot be changed through Kconfig file

### ISSUE THREAD

**Issue by DaMiBear** [lvgl/lvgl#2422]
On the esp32 platform, I added lvgl to the component, but I couldn't use menuconfig to change the default font. Then I found that CONFIG_LV_FONT_DEFAULT is never defined.
````
/*Always set a default font*/
#ifndef LV_FONT_DEFAULT
#  ifdef CONFIG_LV_FONT_DEFAULT
#    define LV_FONT_DEFAULT CONFIG_LV_FONT_DEFAULT
#  else
#    define  LV_FONT_DEFAULT &lv_font_montserrat_8
#  endif
#endif
```

**Comment by DaMiBear** [comment]
I changed 
```
#  ifdef CONFIG_LV_FONT_DEFAULT
#    define LV_FONT_DEFAULT CONFIG_LV_FONT_DEFAULT
```

 to 
```
#  ifdef CONFIG_LV_THEME_DEFAULT_FONT
#    define LV_FONT_DEFAULT CONFIG_LV_THEME_DEFAULT_FONT
```
near line 923 of lv_conf_internal.h file, so that I can use menuconfig to change the default font.

**Comment by kisvegabor** [comment]
[CONFIG_LV_FONT_DEFAULT](https://github.com/lvgl/lvgl/blob/master/Kconfig#L409) should be declared here in Kconfig.

**Comment by DaMiBear** [comment]
Thank you for your correction. I just started learning lvgl. I need to learn the syntax of Kconfig before making changes.
