### ISSUE TITLE
issue for dropdown

### ISSUE THREAD

**Issue by ZhaoQiang-b45475** [lvgl/lvgl#2429]
### Perform all steps below and tick them with [x]
I want to set the style for list of dropdown, and found the list is null.
the code is as below, when the list is opened, the event will not be triggered.
 
static void event_handler(lv_event_t *e)
{
	lv_event_code_t code = lv_event_get_code(e);
	lv_obj_t *obj = lv_event_get_target(e);
	if (code == LV_EVENT_VALUE_CHANGED)
	{
		lv_obj_t *list = lv_dropdown_get_list(obj);
		if (list != NULL)
		{
			/* code */
			printf("list is not null\n");
		}
		else
		{
			printf("list is null\n");
		}
	}
}
void setup_scr_screen(lv_ui *ui)
{
	/*Create a normal drop down list*/
	lv_obj_t *dd = lv_dropdown_create(lv_scr_act());
	lv_dropdown_set_options(dd, "Apple\n"
								"Banana\n"
								"Orange\n"
								"Cherry\n"
								"Grape\n"
								"Raspberry\n"
								"Melon\n"
								"Orange\n"
								"Lemon\n"
								"Nuts");
	lv_obj_align(dd, LV_ALIGN_TOP_MID, 0, 20);
	lv_obj_add_event_cb(dd, event_handler, LV_EVENT_ALL, NULL);
}

**Comment by kisvegabor** [comment]
There were some changes on this: https://docs.lvgl.io/master/widgets/core/dropdown.html#list
