### ISSUE TITLE
How do I use new features(v8.0) at v7.11

### ISSUE THREAD

**Issue by wanglemao** [lvgl/lvgl#2431]
I want to use chart scrolling and zooming
Upgrade from 7 to 8, Too many pages, upgrade trouble

**Comment by kisvegabor** [comment]
Unfortunately, v8 had many breaking changes. [Here](https://github.com/lvgl/lvgl/blob/master/docs/CHANGELOG.md#migrating-from-v7-to-v8) we have collected to most important steps for migration.

---

We use GitHub Issues for development-related discussions.

Please ask your question in the [Forum](https://forum.lvgl.io) to make it visible for a larger community. You can simply log in with your GitHub account.
