### ISSUE TITLE
lv_obj

### ISSUE THREAD

**Issue by Miguel0101** [lvgl/lvgl#2432]
### Just a question

Is there a way to drag an object without scrolling?

**Comment by kisvegabor** [comment]
See this example: https://docs.lvgl.io/master/widgets/obj.html#make-an-object-draggable

---

We use GitHub Issues for development-related discussions.

Please ask your question in the [Forum](https://forum.lvgl.io) to make it visible for a larger community. You can simply log in with your GitHub account.

**Comment by Miguel0101** [comment]
> See this example: https://docs.lvgl.io/master/widgets/obj.html#make-an-object-draggable
> 
> We use GitHub Issues for development-related discussions.
> 
> Please ask your question in the [Forum](https://forum.lvgl.io) to make it visible for a larger community. You can simply log in with your GitHub account.

When I try to drag the object, it is scrolled at the same time.

**Comment by kisvegabor** [comment]
Adding this to the dragable object should do the job:
```
lv_obj_clear_flag(obj, LV_OBJ_FLAG_SCROLL_CHAIN);
```

**Comment by Miguel0101** [comment]
> Adicionar isso ao objeto arrastável deve fazer o trabalho:
> 
> ```
> lv_obj_clear_flag(obj, LV_OBJ_FLAG_SCROLL_CHAIN);
> ```

Sounds good
