### ISSUE TITLE
Add video player widget

### ISSUE THREAD

**Issue by donny681** [lvgl/lvgl#2433]
### Introduce the problem
Do you plan to add video player widget.I want to play video on lvgl,but I cannot find interface.

**Comment by Miguel0101** [comment]
Must be a third-party library

**Comment by kisvegabor** [comment]
> Must be a third-party library

I agree, there are too many ways to get the frames of a video. From LVGL's point of view lv_canvas can be used to display the frames.

Anyway, an implementation with a 3rd party library (as demonstration) would be great!

**Comment by Rajssss** [comment]
> > Must be a third-party library
> 
> I agree, there are too many ways to get the frames of a video. From LVGL's point of view lv_canvas can be used to display the frames.
> 
> Anyway, an implementation with a 3rd party library (as demonstration) would be great!

An example will be great too, with basic OSD :)
