### ISSUE TITLE
API to return messagebox text and title not working correctly when msgbox has no buttons

### ISSUE THREAD

**Issue by jacquesdmernok** [lvgl/lvgl#2436]
### Perform all steps below and tick them with [x]
- [x] Check the related part of the [Documentation](https://docs.lvgl.io/)
- [x] Update lvgl to the latest version
- [x] Reproduce the issue in a [Simulator](https://docs.lvgl.io/latest/en/html/get-started/pc-simulator.html)

### Describe the bug

When a messagebox doesnt have buttons, using lv_msgbox_get_title and lv_msgbox_get_text returns the same pointer.

### To Reproduce
Provide a small, independent code sample that can be used to reproduce the issue.
Ideally this should work in the PC simulator unless the problem is specific to a platform.
Format the code like this:
```c
		lv_obj_t * lv_messageBoxtemp = lv_msgbox_create(NULL, "Welcome to my message box", "Any important information will be displayed here", NULL, false);

		lv_obj_t * title = lv_msgbox_get_title(lv_messageBoxtemp);
		lv_obj_t * content = lv_msgbox_get_text(lv_messageBoxtemp);
		lv_label_set_text(title, "Change title to this");
		lv_label_set_text(content, "Change content to this.");
```

### Expected behavior

Two pointers should be returned, pointing to the title and text.

**Comment by kisvegabor** [comment]
Thanks, fixed.
