### ISSUE TITLE
Error dragging object with align center

### ISSUE THREAD

**Issue by Miguel0101** [lvgl/lvgl#2438]
https://user-images.githubusercontent.com/56565368/128512602-eec4b43e-78bf-4d00-8072-caa0ed12d786.mov

**Comment by embeddedt** [comment]
Hmm... I think this is invalid. You cannot simultaneously change an object's position with `set_pos` and also align it, as only one of those can be respected at a time.

**Comment by Miguel0101** [comment]
> Hmm... I think this is invalid. You cannot simultaneously change an object's position with `set_pos` and also align it, as only one of those can be respected at a time.

How like?

**Comment by kisvegabor** [comment]
Actually it's valid. `lv_obj_set_pos` setc X and Y by respecting the set `align`. But there is an inconsistency in LVGL and I still don't know how to resolve it (ideas are welcome :slightly_smiling_face:  )

The problem is that `lv_obj_get_x/y` doesn't respect `align` and always returns the distance of the top left corner. E.g.if you align the object to the center and `lv_obj_get_x/y` will return e.g. 100, 200 instead of 0,0. If you apply 100, 200 it will move the object away from the enter with 100, 200.

Maybe we need functions like `lv_obj_get_x/y_aligned`.

**Comment by Miguel0101** [comment]
Could it be like this `x/y -= lv_obj_get_style_align(parent, LV_PART_MAIN)`?

**Comment by Miguel0101** [comment]
> Maybe we need functions like `lv_obj_get_x/y_aligned`.

I agree.

**Comment by kisvegabor** [comment]
I've added them.

**Comment by Miguel0101** [comment]
> I've added them.

Can we rename lv_obj_get_x/y_aligned to lv_obj_get_x/y? Because it works with non-aligned objects.

**Comment by embeddedt** [comment]
I'm pretty sure that would be backwards-incompatible.

**Comment by Miguel0101** [comment]
> I'm pretty sure that would be backwards-incompatible.

How like?

**Comment by embeddedt** [comment]
The [current implementation of `get_x`/`get_y`](https://github.com/lvgl/lvgl/blob/51a82a17ffe938d07d94660f49fd18962060943a/src/core/lv_obj_pos.c#L481-L497) takes other factors into account like scrolling and padding, whereas [`get_x_aligned`/`get_y_aligned`](https://github.com/lvgl/lvgl/blob/98bc1fe09e12a64333e91b4c25327c283a700af5/src/core/lv_obj_style.h#L225-L233) are just returning the X/Y style property, which is what you [previously set with `set_x`/`set_y`](https://github.com/lvgl/lvgl/blob/98bc1fe09e12a64333e91b4c25327c283a700af5/src/core/lv_obj_pos.c#L63).

**Comment by Miguel0101** [comment]
> The [current implementation of `get_x`/`get_y`](https://github.com/lvgl/lvgl/blob/51a82a17ffe938d07d94660f49fd18962060943a/src/core/lv_obj_pos.c#L481-L497) takes other factors into account like scrolling and padding, whereas [`get_x_aligned`/`get_y_aligned`](https://github.com/lvgl/lvgl/blob/98bc1fe09e12a64333e91b4c25327c283a700af5/src/core/lv_obj_style.h#L225-L233) are just returning the X/Y style property, which is what you [previously set with `set_x`/`set_y`](https://github.com/lvgl/lvgl/blob/98bc1fe09e12a64333e91b4c25327c283a700af5/src/core/lv_obj_pos.c#L63).

Ok, thanks for your reply.
