### ISSUE TITLE
Display Revert On My Lcd Screen

### ISSUE THREAD

**Issue by BFDX** [lvgl/lvgl#244]
i ported lvgl to my board by followed the official guide,  it did show the demo image but the image's orientation is invert on the horizon, for example string "Open" shows out to be “nepO” 
what's wrong?

**Comment by kisvegabor** [comment]
Hi,

Are you using a display controller (like ILI9341) or the MCU's LCD driver periphery?

**Comment by kisvegabor** [comment]
AS there wasn't activity here for months I close this issue.
If you have a similar question feel free to comment here  and reopen the issue!
