### ISSUE TITLE
/*clang-format off*/ not recognized

### ISSUE THREAD

**Issue by higaski** [lvgl/lvgl#2441]
Various headers (e.g. [lv_conf_template.h](https://github.com/lvgl/lvgl/blob/50ea6fb3fefb3a6edc958154c575dcdcacbfdb3a/lv_conf_template.h)) use 

`/*clang-format off*/`

to supposedly disable clang-format. This however does not work, at least not with clang-format 12.0.1.
According to the clang-format [documentation](https://clang.llvm.org/docs/ClangFormatStyleOptions.html) there are two whitespaces missing and this should be changed to 

`/* clang-format off */`

**Comment by embeddedt** [comment]
Thanks! These are leftovers from the brief period (v6) where we used clang-format. I have corrected the directive in `lv_conf_template.h` (since this file is customized by downstream projects) and removed it from all other human-made headers.

**Comment by higaski** [comment]
May I further suggest to move the clang-format off comment up a little?
At the position it currently stands at it still allows clang-format to indent the first preprocessor directives.

**Comment by kisvegabor** [comment]
> May I further suggest to move the clang-format off comment up a little?
At the position it currently stands at it still allows clang-format to indent the first preprocessor directives.

Done here 3c86d777
