### ISSUE TITLE
Calendar set today date bug

### ISSUE THREAD

**Issue by b2connected** [lvgl/lvgl#2445]
### Perform all steps below and tick them with [x]
- [ ] Check the related part of the [Documentation](https://docs.lvgl.io/)
- [ ] Update lvgl to the latest version
- [ ] Reproduce the issue in a [Simulator](https://docs.lvgl.io/latest/en/html/get-started/pc-simulator.html)

### To Reproduce
 This bug also occurs in the example.

### Expected behavior
 I found a bug in the calendar widget in both Ver. master and Ver. 8.0. I Guess, This is if the first day starts on the first Sunday of the week, {lv_calendar_set_today_date()}function behaves abnormally.
The border style is displayed in the line below the clicked.

### Screenshots or video

![스크린샷 2021-08-10 오후 1 04 04](https://user-images.githubusercontent.com/46847697/128806609-76536b10-11fe-4c2b-b04b-d48f9ec06a09.png)

You can test 2021. 8 or 2022. 5

**Comment by kisvegabor** [comment]
It seems like the same issue as https://github.com/lvgl/lvgl/issues/2446
Let's continue there.
