### ISSUE TITLE
calendar issue

### ISSUE THREAD

**Issue by ZhaoQiang-b45475** [lvgl/lvgl#2446]
Hi, 
As capture below shows, today and highlight day display incorrectly for 2020 March.
In addition, how could I set style for header?
![image](https://user-images.githubusercontent.com/22284222/128817084-0b47ee67-3bdf-4477-9d9f-41193adc260d.png)

**Comment by kisvegabor** [comment]
Thanks for the report. I've pushed a fix.

> In addition, how could I set style for header?

By header do you mean the day names or the dropdowns?
