### ISSUE TITLE
Removing style of bar is delete text of button of list widget and bar

### ISSUE THREAD

**Issue by ercanersoy** [lvgl/lvgl#2448]
### Perform all steps below and tick them with [x]
- [x] Check the related part of the [Documentation](https://docs.lvgl.io/)
- [x] Update lvgl to the latest version
- [x] Reproduce the issue in a [Simulator](https://docs.lvgl.io/latest/en/html/get-started/pc-simulator.html)

### Describe the bug

Removing style is delete text of button of list widget and bar.

### To Reproduce

```c

lv_obj_t *menu_list;
lv_obj_t *menu_bar;

void menu_create()
{
    menu_list = lv_list_create(lv_scr_act());

    lv_obj_set_size(menu_list, 300, 220);

    lv_obj_align(menu_list, LV_ALIGN_CENTER, 0, 0);

    lv_list_add_text(menu_list, "Deneme");
}

void menu_item_slider_add()
{
    // Create button of menu item slider
    lv_obj_t *menu_button = lv_list_add_btn(menu_list, LV_SYMBOL_DIRECTORY, "Button");

    // Create bar of menu item slider
    menu_bar = lv_bar_create(menu_button);

    // Set size of bar of menu item slider
    lv_obj_set_size(menu_bar, 100, 20);

    // Menu bar main style variable
    static lv_style_t menu_bar_main_style;

    // Initialization of menu bar main style
    lv_style_init(&menu_bar_main_style);

    // Set menu bar main style color
    lv_style_set_bg_color(&menu_bar_main_style, lv_color_make(0, 128, 64));

    // Set menu bar main style opacity
    lv_style_set_bg_img_opa(&menu_bar_main_style, LV_OPA_50);

    // Apply menu bar main style to menu bar
    lv_obj_add_style(menu_bar, &menu_bar_main_style, LV_PART_MAIN);
}

void menu_item_slider_update()
{
    // Remove all styles of menu bar
    lv_obj_remove_style_all(menu_bar);

    // Menu bar main style variable
    static lv_style_t menu_bar_main_style;

    // Initialization of menu bar main style
    lv_style_init(&menu_bar_main_style);

    // Set menu bar main style color
    lv_style_set_bg_color(&menu_bar_main_style, lv_color_make(0, 128, 64));

    // Apply menu bar main style to menu bar
    lv_obj_add_style(menu_bar, &menu_bar_main_style, LV_PART_MAIN);
}

void menu()
{
    menu_create();
    menu_item_slider_add();
    menu_item_slider_update();
}
```

### Expected behavior

Removing style of bar is not delete text of button of list widget and bar.

Removing style of bar and adding style of bar must change style of bar.

### Screenshots or video

Screenshots or video is not available.

**Comment by kisvegabor** [comment]
Hi,

Please send a minimal code snippet to demonstrate only the issue.

This line seems incorrect: `lv_bar_set_value(0, LV_ANIM_OFF);`
It should be lv_bar_set_value(menu_bar, 0, LV_ANIM_OFF);`

There should be at least a warning about it but be sure there are no warnings.

**Comment by ercanersoy** [comment]
I have updated my demonstration code.

I cannot share my originial code.

Thanks.

**Comment by kisvegabor** [comment]
No need for the original code but only a few lines as example to show what the problem is. 

In your above example some variables are not declared, the list is not created, etc. We need something that we can simply copy paste to the simulator to see the issue.

**Comment by ercanersoy** [comment]
I have updated my demonstration code.

You could call `menu_item_slider()` to seeing this issue.

**Comment by ercanersoy** [comment]
I have updated my demonstration code again. Sorry for confusion.

**Comment by kisvegabor** [comment]
Thanks. The problem is that if you remove the styles `bg_opa` will be `0`. You need to set it too with 
`lv_style_set_bg_opa(&menu_bar_main_style, LV_OPA_COVER);`

Also note that removing the styles [will remove the set sizes](https://docs.lvgl.io/master/overview/coords.html#removing-styles) too.

**Comment by ercanersoy** [comment]
Thanks. But, it does not work properly. The text of button of list widget does not remove now and the bar does remove now.

**Comment by ercanersoy** [comment]
I have updated my demonstration code.

You could call menu() to seeing this issue.

**Comment by ercanersoy** [comment]
> Thanks. But, it does not work properly. The text of button of list widget does not remove now and the bar does remove now.

My new demonstrate code was given below and test it in a simulator.

You could call menu() to seeing this issue.

```c
lv_obj_t *menu_list;
lv_obj_t *menu_bar;

void menu_create()
{
    menu_list = lv_list_create(lv_scr_act());

    lv_obj_set_size(menu_list, 300, 220);

    lv_obj_align(menu_list, LV_ALIGN_CENTER, 0, 0);

    lv_list_add_text(menu_list, "Deneme");
}

void menu_item_slider_add()
{
    // Create button of menu item slider
    lv_obj_t *menu_button = lv_list_add_btn(menu_list, LV_SYMBOL_DIRECTORY, "Button");

    // Create bar of menu item slider
    menu_bar = lv_bar_create(menu_button);

    // Set size of bar of menu item slider
    lv_obj_set_size(menu_bar, 100, 20);

    // Menu bar main style variable
    static lv_style_t menu_bar_main_style;

    // Initialization of menu bar main style
    lv_style_init(&menu_bar_main_style);

    // Set menu bar main style color
    lv_style_set_bg_color(&menu_bar_main_style, lv_color_make(0, 128, 64));

    // Set menu bar main style opacity
    lv_style_set_bg_img_opa(&menu_bar_main_style, LV_OPA_COVER);

    // Apply menu bar main style to menu bar
    lv_obj_add_style(menu_bar, &menu_bar_main_style, LV_PART_MAIN);
}

void menu_item_slider_update()
{
    // Remove all styles of menu bar
    lv_obj_remove_style_all(menu_bar);

    // Set size of bar of menu item slider
    lv_obj_set_size(menu_bar, 100, 20);

    // Menu bar main style variable
    static lv_style_t menu_bar_main_style;

    // Initialization of menu bar main style
    lv_style_init(&menu_bar_main_style);

    // Set menu bar main style color
    lv_style_set_bg_color(&menu_bar_main_style, lv_color_make(0, 128, 64));

    // Set menu bar main style opacity
    lv_style_set_bg_img_opa(&menu_bar_main_style, LV_OPA_COVER);

    // Apply menu bar main style to menu bar
    lv_obj_add_style(menu_bar, &menu_bar_main_style, LV_PART_MAIN);
}

void menu()
{
    menu_create();
    menu_item_slider_add();
    menu_item_slider_update();
}
```

**Comment by ercanersoy** [comment]
Given screenshot as before style removing
![before](https://user-images.githubusercontent.com/15850068/129138021-4a19ada9-edda-43a0-b1a0-03e3d201c35e.png)

Given screenshot as after style removing
![after](https://user-images.githubusercontent.com/15850068/129138017-8b2b0351-e4f2-453b-80b0-a800eb269964.png)

**Comment by kisvegabor** [comment]
In your example tehre is `lv_style_set_bg_img_opa` instead of `lv_style_set_bg_opa`.
