### ISSUE TITLE
Typo in flex grow docs

### ISSUE THREAD

**Issue by higaski** [lvgl/lvgl#2449]
There is a teeny tiny typo in the [flex grow](https://github.com/lvgl/lvgl/blob/master/docs/layouts/flex.md#flex-grow) documentation.

In the last sentence of this paragraph the function referred to is
`lv_obj_set_flex_flow(child, value)`

But should be
`lv_obj_set_flex_grow(child, value)`

**Comment by embeddedt** [comment]
Thanks; fixed here: https://github.com/lvgl/lvgl/commit/e5fafc412214ab01d46ebd37e272e3ffc3164ea4
