### ISSUE TITLE
Calendar bug

### ISSUE THREAD

**Issue by b2connected** [lvgl/lvgl#2450]
### Perform all steps below and tick them with [x]
- [ ] Check the related part of the [Documentation](https://docs.lvgl.io/)
- [ ] Update lvgl to the latest version
- [ ] Reproduce the issue in a [Simulator](https://docs.lvgl.io/latest/en/html/get-started/pc-simulator.html)

### Describe the bug
 Fixed a calendar bug and got a new bug. Now the first line of every month works fine, but when the first day doesn't start at the beginning, the second line behaves strangely. please confirm.

### To Reproduce

    /*Reset the focused button if the days changes*/
    if(lv_btnmatrix_get_selected_btn(obj) != LV_BTNMATRIX_BTN_NONE) {
        lv_btnmatrix_set_selected_btn(obj, day_first + 7);
    }

         uint8_t tmp = calendar->today.day + day_first;
        if(tmp >= 7) tmp -= 7;  /*Do not leave an empty line*/
        lv_btnmatrix_set_btn_ctrl(obj, tmp + 7, LV_CALENDAR_CTRL_TODAY);

**Comment by kisvegabor** [comment]
I reviewed it again and  found some "strange" parts in the code. 
I've pushed a new fix and tested with various inputs and all looked good to me.
