### ISSUE TITLE
How to make a curved progress bar?

### ISSUE THREAD

**Issue by b2connected** [lvgl/lvgl#2451]
### Introduce the problem
  I want to make a curved progress bar. Which one can I apply? 

### Examples and cases

I want to do it like the video below. But the code in this video is not efficient.

https://user-images.githubusercontent.com/46847697/128969752-a2e01315-d4ba-4013-9d23-c49049429213.mp4

Bar: Unbent
line: cannot be parent

Please advise.

**Comment by kisvegabor** [comment]
It's an interesting question and I'd be happy to help, but please open a topic for it in the [Forum](https://forum.lvgl.io/) and link it here. 

We use GitHub for development related discussion.
