### ISSUE TITLE
btnmatrix *_all functions documentation

### ISSUE THREAD

**Issue by higaski** [lvgl/lvgl#2455]
The documentation of the functions

```
lv_btnmatrix_set_btn_ctrl_all
lv_btnmatrix_clear_btn_ctrl_all
```

says that those functions take a _btn_id_ as second parameter.

I guess that's a copy/paste error since that would kinda defeat the purpose of those. :grin:

Of course the actual signatures do not take a _btn_id_
```
void lv_btnmatrix_set_btn_ctrl_all(lv_obj_t * obj, lv_btnmatrix_ctrl_t ctrl)
void lv_btnmatrix_clear_btn_ctrl_all(lv_obj_t * obj, lv_btnmatrix_ctrl_t ctrl)
```

**Comment by embeddedt** [comment]
Entirely! It's now fixed; thanks.
