### ISSUE TITLE
Problems caused by lv_obj_set_style_clip_corner

### ISSUE THREAD

**Issue by qinshijing** [lvgl/lvgl#2457]
### Perform all steps below and tick them with [x]
- [x] Check the related part of the [Documentation](https://docs.lvgl.io/)
- [x] Update lvgl to the latest version
- [x] Reproduce the issue in a [Simulator](https://docs.lvgl.io/latest/en/html/get-started/pc-simulator.html)

### Describe the bug
When clip conner is set to true, if the opacity of the parent and children background is not 100%, the color mixing area will be abnormal.

### To Reproduce
static void test(void)
{
    lv_obj_set_style_bg_color(lv_scr_act(), lv_color_black(), 0);
    lv_obj_t* obj = lv_obj_create(lv_scr_act());
    lv_obj_set_style_bg_opa(obj, LV_OPA_20, 0);
    lv_obj_set_style_pad_all(obj, 0, 0);
    lv_obj_set_style_border_width(obj, 0, 0);
    lv_obj_set_style_clip_corner(obj, true, 0);
    lv_obj_set_style_radius(obj, 50, 0);
    lv_obj_set_size(obj, 400, 300);
    lv_obj_center(obj);
    lv_obj_t* obj1 = lv_obj_create(obj);
    lv_obj_set_style_bg_opa(obj1, LV_OPA_20, 0);
    lv_obj_set_style_border_width(obj1, 0, 0);
    lv_obj_set_style_radius(obj1, 0, 0);
    lv_obj_set_size(obj1, 400, 100);
    lv_obj_align(obj1, LV_ALIGN_BOTTOM_MID, 0, 0);
}

### Expected behavior
![image](https://user-images.githubusercontent.com/51692568/129737837-74a2342d-bcfe-4066-90fd-66b379eb254a.png)

### Screenshots or video
![image](https://user-images.githubusercontent.com/51692568/129737952-962546bf-ad10-429b-b320-aa672ccc7a8c.png)

**Comment by kisvegabor** [comment]
Thanks, I've just pushed a fix.

**Comment by qinshijing** [comment]
Thanks, it's working normally.
