### ISSUE TITLE
Objects aren't being draw if they have smaller width than screen

### ISSUE THREAD

**Issue by pe-nelopes** [lvgl/lvgl#246]
Hello,
I'm trying to port the library to my project, and the screen is being cleared correctly.
I configured the screen size as 100x100 on lv_conf.hand tried some example code for the base object:

```
lv_obj_t * obj1;
obj1 = lv_obj_create(lv_scr_act(), NULL);
lv_obj_set_size(obj1, 100, 50);
lv_obj_set_style(obj1, &lv_style_plain_color);
lv_obj_align(obj1, NULL, LV_ALIGN_CENTER, 0, 0);
```
This worked fine, I got a blue band in the middle of the white screen. If i change the object height, like lv_obj_set_size(obj1, 100, 20) it still works, but if I change the width like lv_obj_set_size(obj1, 80, 50) the screen is full white.
If I set the screen size as 80x100, and use lv_obj_set_size(obj1, 80, 50) I get the blue band again like expected.

Any idea as what I'm doing wrong?

**Comment by kisvegabor** [comment]
Hi,

Is it solved? If yes please tell us the solution to learn from it! :)
