### ISSUE TITLE
lv_obj_swap does not change the focus order

### ISSUE THREAD

**Issue by glueckm** [lvgl/lvgl#2462]
### Describe the bug
When ```lv_obj_swap``` is used on a ```lv_list``` to swap two items of the list, the order of the focus is not changed.

### To Reproduce
Here is an exaple showing the problem. When I use mouse wheel, the focus jumps form Item 1 (which is the last in the list) to Item 2 (which is the seconf in the list).
And from Item 4 (the second to last) it jumps to Item 5 (which is the frist after the swap).

```c
#include <Windows.h>

#if _MSC_VER >= 1200
// Disable compilation warnings.
#pragma warning(push)
// nonstandard extension used : bit field types other than int
#pragma warning(disable:4214)
// 'conversion' conversion from 'type1' to 'type2', possible loss of data
#pragma warning(disable:4244)
#endif

#include "lvgl.h"
#include "win32drv/win32drv.h"
#if _MSC_VER >= 1200
// Restore compilation warnings.
#pragma warning(pop)
#endif

int main(int argc, char** argv) {
    lv_init();

    if (!lv_win32_init(
        GetModuleHandleW(NULL),
        SW_SHOW,
        320,
        240,
        nullptr))
    {
        return -1;
    }
    lv_win32_add_all_input_devices_to_group(NULL);
    lv_obj_t* list = lv_list_create(lv_scr_act());
    lv_list_add_btn(list, NULL, "Item 1");
    lv_list_add_btn(list, NULL, "Item 2");
    lv_list_add_btn(list, NULL, "Item 3");
    lv_list_add_btn(list, NULL, "Item 4");
    lv_list_add_btn(list, NULL, "Item 5");
    lv_obj_swap(lv_obj_get_child(list, 0), lv_obj_get_child(list, 4));
    while (!lv_win32_quit_signal) {
        lv_task_handler();
    }
}
```

**Comment by glueckm** [comment]
https://user-images.githubusercontent.com/1733529/129915526-6b878135-5d5a-4a97-9f63-9e72611e0cd9.mp4

**Comment by kisvegabor** [comment]
Good catch. The position in the group needs to be swapped too. 

I'll add a fix tomorrow.

**Comment by kisvegabor** [comment]
I've pushed a fix.

**Comment by glueckm** [comment]
First of all thanks for the quick fix. Unfortunately, i have to reopen the issue, becasue there seems to be a problem if you swap the item which currently has the focus:
Internal, the system thinjs the new item is the focused, but the old item is drawn as focued.
Once the focus chanin moves to the "old" first, the screen looks correct.
It's easier to see I guess:

https://user-images.githubusercontent.com/1733529/130103207-d8afc422-cec1-4de8-99d7-667f6b4fa40c.mp4

**Comment by kisvegabor** [comment]
Thanks for the report, I haven't thought of that. I leave this issue open until your confirm it's working well. :slightly_smiling_face:

**Comment by glueckm** [comment]
Perfect. Now it works as expected.
Thanks again for the quick fix!

**Comment by kisvegabor** [comment]
Great, thank you for the feedback!
