### ISSUE TITLE
issue for calendar

### ISSUE THREAD

**Issue by ZhaoQiang-b45475** [lvgl/lvgl#2464]
As the capture below, I use lv_calendar_header_arrow_create to create a header for calender and set the 
bg_color, but seems mismtach, there are gaps between the bg_color and the button.
BTW, is there any way to set style of the button?
![image](https://user-images.githubusercontent.com/22284222/130036674-891a6147-4b9c-4dc5-8060-b1da26dc898c.png)

In addition, according to the description of LV_PART_ITEMS, I have no idea how to set the style for day names/previous-next month days/todays and highlight days.
![image](https://user-images.githubusercontent.com/22284222/130037587-b89e0a1c-eb41-4112-84be-b29b119934ba.png)

**Comment by kisvegabor** [comment]
By default, there is a shadow below the buttons. 

I've pushed a fix to make behave better on non-white backgrounds.

**Comment by kisvegabor** [comment]
> In addition, according to the description of LV_PART_ITEMS, I have no idea how to set the style for day names/previous-next month days/todays and highlight days.

I've forgot to answer these. As there are to many config options here the calendar uses a "custom drawer" to modify the appearance of the text and buttons. You can add an other draw event to do something similar. 
See https://github.com/lvgl/lvgl/blob/master/src/extra/widgets/calendar/lv_calendar.c#L261

**Comment by ZhaoQiang-b45475** [comment]
Hi kisvegabor,
do you mean, I could define a cb function like draw_part_begin_event_cb, then add it to my calendar instance?
such as:

static void draw_custom_event_cb(lv_event_t * e)
{ ... }

lv_objt_t *calendar = lv_calendar_create(lv_src_act());
lv_obj_add_event_cb(obj, draw_custom_event_cb, LV_EVENT_DRAW_PART_BEGIN, NULL);

**Comment by kisvegabor** [comment]
Yes, exactly.
