### ISSUE TITLE
Arc gradient

### ISSUE THREAD

**Issue by qinshijing** [lvgl/lvgl#2469]
### Introduce the problem
Hello, I need to implement a circular arc gradient, but I can't seem to find the relevant API. How can I achieve similar functions?

### Examples and cases
![arc](https://user-images.githubusercontent.com/51692568/130194479-dbd82065-7385-44b5-832e-7e35a1764bf4.jpeg)

**Comment by kisvegabor** [comment]
You can use an background image for the arc and the arc will be masked out from that image. 
See  https://docs.lvgl.io/master/overview/style-props.html#arc-img-src

**Comment by qinshijing** [comment]
Yes. But this seems to only solve the background of arc, not the indicator of arc.

**Comment by kisvegabor** [comment]
You can set it for the indicator too

```c
lv_obj_set_style_arc_img_src(arc, &img1, LV_PART_INDICATOR)
```

**Comment by qinshijing** [comment]
Maybe the arc gradient I want is a gradient similar to a rectangular background, given a bg_color and grad_color, grad_dir (clockwise, counterclockwise) and then arc automatically follows an arc gradient. Now LVGL doesn't seem to support this feature. If it does, I think this is pretty cool.

**Comment by kisvegabor** [comment]
This kind of radial gradient is really not supported because it's very slow to calculate them (or at least I couldn't imagine a fast way so far)

**Comment by qinshijing** [comment]
Okay, Thanks.
