### ISSUE TITLE
calendar style issue

### ISSUE THREAD

**Issue by ZhaoQiang-b45475** [lvgl/lvgl#2470]
is there any way to set the style of year_dd/month_dd, when create dropdown header for calendar.
the same to arrow header.

![image](https://user-images.githubusercontent.com/22284222/130212527-f9f6fe25-8abb-4b2e-8f85-1028cf51651f.png)

**Comment by kisvegabor** [comment]
You can get the children of the header with `lv_obj_get_child(header, 0 or 1)` to get the dropdowns. Then you can style them.

But note that it's a little bit tricky to style the dropdown's "list". 
See https://docs.lvgl.io/master/widgets/core/dropdown.html#list
