### ISSUE TITLE
LV_STATE_HOVERED

### ISSUE THREAD

**Issue by Miguel0101** [lvgl/lvgl#2478]
Is the hover state already developed?

**Comment by embeddedt** [comment]
It's currently on the [roadmap for v8.2](https://github.com/lvgl/lvgl/blob/a38fcf2c7aa5fd156d3f2b6965ec4f81d7ff5503/docs/ROADMAP.md#v82).

**Comment by Miguel0101** [comment]
When I try to use `LV_STATE_HOVERED`, nothing happens.

**Comment by embeddedt** [comment]
That's because it is not implemented yet. Only the enum value exists.

**Comment by Miguel0101** [comment]
Ok thanks @embeddedt
