### ISSUE TITLE
When will the python binding of lvgl be provided?

### ISSUE THREAD

**Issue by china-zhangdj** [lvgl/lvgl#2481]
I use lvgl in the embedded linux environment to replace the huge x11 to achieve fast response gui. Now I use the micropython version of lvgl. Due to the limitations of micropython, it lacks many high-level libraries (such as opencv, tensorflow, scrapy) , Flask, etc.), I desperately need the python binding of lvgl. I believe that implementing edge artificial neural network applications in embedded linux through lvgl+python+opencv is a very exciting thing.

**Comment by kisvegabor** [comment]
I agree that it'd be great and I believe the the micropython binding would be a good starting point. 

IMO the main issue that should be addressed is the garbage collection and memory management differences between Python and MicroPython.

**Comment by amirgon** [comment]
If you would consider a "quick and dirty" solution, you can try hosting Micropython in Python.
Your machine is capable enough to run fully fledged Python so it would easily run Micropython as well in the background. Then you only need some wrapper to delegate calls from/to Micropython. You could either run it in a separate process or try to embed it as a library.
