### ISSUE TITLE
Expose LV_LED_BRIGHT_MIN and LV_LED_BRIGHT_MAX

### ISSUE THREAD

**Issue by higaski** [lvgl/lvgl#2485]
The two definitions LV_LED_BRIGHT_MIN and LV_LED_BRIGHT_MAX should be exposed in the header [lv_led.h](https://github.com/lvgl/lvgl/blob/9b92885f83bf3e9158f15bccef0a704573e59a28/src/extra/widgets/led/lv_led.h) since they are also documented in the interface.

```c
/**
 * Set the brightness of a LED object
 * @param led pointer to a LED object
 * @param bright LV_LED_BRIGHT_MIN (max. dark) ... LV_LED_BRIGHT_MAX (max. light)
 */
void lv_led_set_brightness(lv_obj_t * led, uint8_t bright);
```

Currently users would have to browse to the implementation to look up those values.

**Comment by kisvegabor** [comment]
Sounds reasonable, I've just added it.
