### ISSUE TITLE
Typo in text area documentation

### ISSUE THREAD

**Issue by higaski** [lvgl/lvgl#2487]
There is an easy to overlook typo in the [text area](https://github.com/lvgl/lvgl/blob/master/docs/widgets/core/textarea.md) documentation. The section about "accepted characters" has two letters twisted:
```c
lv_textarae_set_accepted_chars // spells arAE
```

instead of 
```c
lv_textarea_set_accepted_chars
```

Really only an issue when copy/pasting. :smile:

**Comment by kisvegabor** [comment]
Thanks, could you send  a pull request?

**Comment by kisvegabor** [comment]
It seems it's already fixed. I close this issue.
