### ISSUE TITLE
Unwanted Artifacts/Dots in Glyphs

### ISSUE THREAD

**Issue by elTeriblePacman** [lvgl/lvgl#2489]
### Perform all steps below and tick them with [x]
- [x] Check the related part of the [Documentation](https://docs.lvgl.io/)
- [x] Update lvgl to the latest version
- [x] Reproduce the issue in a [Simulator](https://docs.lvgl.io/latest/en/html/get-started/pc-simulator.html)

### Describe the bug

Unwanted artifacts or dots seen on glyphs of compressed fonts loaded from a file system.

### To Reproduce

```c
lv_obj_t * label_01 = lv_label_create(lv_scr_act());
  lv_label_set_long_mode(label_01, LV_LABEL_LONG_WRAP);     /*Break the long lines*/
  lv_label_set_recolor(label_01, true);                      /*Enable re-coloring by commands in the text*/
  lv_label_set_text(label_01, "#0000ff Monserrat 16 # \nAa Bb Cc Dd Ee Ff Gg Hi Jj Kk Ll Mm Nn Oo Pp Qq Rr Ss Tt Uu Vv Ww Xx Yy Zz 0123456789.\n#ff0000 Compressed. #");
  lv_obj_set_width(label_01, 150);  /*Set smaller width to make the lines wrap*/
  lv_obj_set_style_text_align(label_01, LV_TEXT_ALIGN_CENTER, 0);
  lv_obj_align(label_01, LV_ALIGN_OUT_TOP_LEFT, 0, 200);

  static lv_font_t * my_font_01 = NULL;
  printf("Loading font Compressed font from drive...\r\n");
  my_font_01 = lv_font_load("S:/fonts/Montserrat_16_compressed.bin");
  if(my_font_01 != NULL){
    printf("font load OK!\r\n");
    lv_obj_set_style_text_font(label_01, my_font_01, LV_PART_MAIN | LV_STATE_DEFAULT);
  }
  else{
    printf("Loading Compressed font from drive failed!\r\n");
  }
```

### Expected behavior

I would like to have the unwanted dots/artifacts in compressed fonts removed.

### Screenshots or video

Highlighted in yellow are the offending artifacts.
![ed939fc31adcb9884c467be905cd28288044d090](https://user-images.githubusercontent.com/86652749/130624346-1b14cda7-74f2-4e6d-a502-51ff99429c00.png)

Please refer to this repository:
https://github.com/elTeriblePacman/lv_sim_vscode_sdl

One of the examples was modified to demonstrate the issue:
https://github.com/elTeriblePacman/lvgl/commit/7b9ac3980661a989ca3d9fbe20260eaadd76fa26

The fonts used and the parameters used with the offline LVGL font converter are here:
https://github.com/elTeriblePacman/lv_sim_vscode_sdl/tree/master/fonts

The commands used with the offline LVGL font converter are in “fonts/lv_font_conv_cmds.txt”.

Montserrat was copied from the official LVGL repo. The rest of the fonts are from Windows.

**Comment by kisvegabor** [comment]
Do you also see the issue if the fonts are converted to C array?

**Comment by elTeriblePacman** [comment]
Hello,
No I wasn't able to replicate the issue when using C array as the output format. Please see below image for reference (highlighted in yellow):

<img width="402" alt="Unwanted Dots Artifacts 01 using C arrays" src="https://user-images.githubusercontent.com/86652749/130744985-beee10fa-04f3-4694-985a-f3d985b4c61e.png">

The repo I linked above was updated.
I used the lines below to generate the fonts in C array format:

With compression, C array
env DEBUG=* lv_font_conv --font BAUHS93.TTF -r 0x20-0x7F --size 16 --format lvgl --bpp 4 -o bauhaus_16_compressed_array.c

Without compression,  C array
env DEBUG=* lv_font_conv --no-compress --font BAUHS93.TTF -r 0x20-0x7F --size 16 --format lvgl --bpp 4 -o bauhaus_16_notcompressed_array.c

**Comment by kisvegabor** [comment]
Thanks. I think I found the problem. Please try adding this line to `lv_font_loader.c`:
```diff
--- a/src/font/lv_font_loader.c
+++ b/src/font/lv_font_loader.c
@@ -454,6 +454,8 @@ static int32_t load_glyph(lv_fs_file_t * fp, lv_font_fmt_txt_dsc_t * font_dsc,
                 }
             }
             glyph_bmp[cur_bmp_size + bmp_size - 1] = read_bits(&bit_it, 8 - nbits % 8, &res);
+            /*The last fragment should be on the MSB but read_bits() will place it to the LSB*/
+            glyph_bmp[cur_bmp_size + bmp_size - 1] = glyph_bmp[cur_bmp_size + bmp_size - 1] << (nbits % 8);
             if(res != LV_FS_RES_OK) {
                 return -1;
             }
```

**Comment by elTeriblePacman** [comment]
Hello @kisvegabor ,
I confirm that the fix has resolved issue. I tested using the simulator as well as on my actual target devices (using NXP RT1050 processors).

Before I close this issue, can you kindly link here the official commit for the above fix? Thanks in advance.

**Comment by kisvegabor** [comment]
Great! I've pushed the fix :slightly_smiling_face: 

(I've mentioned the issue's ID in the commit so it was closed automatically)
