### ISSUE TITLE
Apply color filter failed in outline/arc/line etc color

### ISSUE THREAD

**Issue by qinshijing** [lvgl/lvgl#2491]
### Introduce the problem
When I use color filtered in the line properties, it doesn't work. After checking the code, I found that used lv_obj_get_style_line_color to get the color. Why not use lv_obj_get_style_line_color_filtered? I'm not sure if this was done intentionally.

### Examples and cases
![image](https://user-images.githubusercontent.com/51692568/130730913-b38cb0f7-0ad5-451d-b5bf-b47a2611c1d1.png)

### Suggested solution
![image](https://user-images.githubusercontent.com/51692568/130730951-34246d75-3500-4bc3-abb6-659c0a9c222e.png)

**Comment by kisvegabor** [comment]
Thanks for the report,  it wasn't intentional.
I pushed a fix.  

Glad to see that color filter is being used :slightly_smiling_face:
