### ISSUE TITLE
forget freeing _lv_obj_t.styles when deleting obj

### ISSUE THREAD

**Issue by lee88688** [lvgl/lvgl#2497]
### Perform all steps below and tick them with [x]
- [x] Check the related part of the [Documentation](https://docs.lvgl.io/)
- [x] Update lvgl to the latest version
- [x] Reproduce the issue in a [Simulator](https://docs.lvgl.io/latest/en/html/get-started/pc-simulator.html)

### Describe the bug
when I remove a obj using `lv_obj_del` api. it will call `obj_del_core`  and then call `lv_obj_destructor` to destruct obj. when `lv_obj_destructor` removing styles(actually calling `lv_obj_remove_style`), it will remove trans and local styles.
```c
if(obj->styles[i].is_trans) {
    trans_del(obj, part, LV_STYLE_PROP_ANY, NULL);
}

if(obj->styles[i].is_local || obj->styles[i].is_trans) {
    lv_style_reset(obj->styles[i].style);
    lv_mem_free(obj->styles[i].style);
    obj->styles[i].style = NULL;
}

/*Shift the styles after `i` by one*/
uint32_t j;
for(j = i; j < (uint32_t)obj->style_cnt - 1 ; j++) {
    obj->styles[j] = obj->styles[j + 1];
}

obj->style_cnt--;
obj->styles = lv_mem_realloc(obj->styles, obj->style_cnt * sizeof(_lv_obj_style_t));
```
and then obj memory will be free. but the pointer `obj.styles`'s memory will not be free. why it is designed as this?
if I create and destroy obj with custom styles freequently, it would lead to memory leak.
I think user's style memory is managed by himself, just free `obj.styles`.

### To Reproduce
```c
lv_style_t style;
lv_style_init(&style);

lv_obj_t *obj = lv_obj_create(lv_scr_act());
lv_obj_add_style(obj, &style, 0);
lv_obj_del(obj);
```

**Comment by kisvegabor** [comment]
Have you really experienced  memory leak or is it a theoretical issue?

I'm asking because
```c
obj->styles = lv_mem_realloc(obj->styles, obj->style_cnt * sizeof(_lv_obj_style_t));
``` 

will allocate a zero sized memory when all styles are removed. In this special case `lv_mem_alloc` returns a pointer to a `zero_mem`  variable, so there is no memory leak here.

**Comment by lee88688** [comment]
I'm sorry for my mistake😥. I do some test and `lv_mem_realloc` will remove the memory.

**Comment by kisvegabor** [comment]
No problem, glad to see that people reading the code so deeply :slightly_smiling_face:
