### ISSUE TITLE
Function to delete item from lv_list_t

### ISSUE THREAD

**Issue by scopa90** [lvgl/lvgl#25]
It would be good to have way to delete a list item.

**Comment by kisvegabor** [comment]
The return value of `lv_list add` is the button on the list. You can delete it with `lv_obj_del(list_element_1)`

**Comment by scopa90** [comment]
Of course I can! Thanks.

**Comment by kisvegabor** [comment]
I updated the online documentation to make it clear.

http://www.gl.littlev.hu/object-types/list-lv_list

(Ctrl + F5 to refresh with cache clear.)
