### ISSUE TITLE
touch event is a little slow, what 's the matter.

### ISSUE THREAD

**Issue by thepolygongo** [lvgl/lvgl#250]
I ported lvgl on arm9 (400MHz). then click button is slow.  what is the reason?

**Comment by kisvegabor** [comment]
Hi,

It an have two main reasons:
1. when you call `lv_tick_inc(x)` `x` should be elapsed time from the last call in milliseconds.
2. you should wait only a few milliseconds between two call of `lv_task_handler()`

**Comment by as564335sa** [comment]
Put the read() read point function in the thread and share it with the global variable to lvgl.

**Comment by thepolygongo** [comment]
Thank you for everybody's attention.
I solved this problem, I set like this on conf.h file.
#define LV_INDEV_READ_PERIOD            20   
thank you again
