### ISSUE TITLE
Unable to call lv_scr_load_anim before the previous animation started

### ISSUE THREAD

**Issue by pdgendt** [lvgl/lvgl#2502]
- [x] Check the [related part](https://docs.lvgl.io/latest/en/html/overview/display.html?highlight=lv_scr_load_anim#_CPPv416lv_scr_load_animP8lv_obj_t18lv_scr_load_anim_t8uint32_t8uint32_tb) of the Documentation
- [x] Update lvgl to the latest version (release/v7)
- [ ] Reproduce the issue in a [Simulator](https://docs.lvgl.io/latest/en/html/get-started/pc-simulator.html)

### Describe the bug
Directly loading 2 different screens using animations (because of some application logic), will result in an invalid state. The first screen will be showed however it won't be the actual screen.

The main issue is that the call to `scr_load_anim_start` is never done for the first screen.

### To Reproduce
```c
lv_obj_t *screen1 = lv_obj_create(NULL, NULL);
lv_obj_t *screen2 = lv_obj_create(NULL, NULL);
// add widgets to both screens
lv_scr_load_anim(screen1, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, false);
lv_scr_load_anim(screen2, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, false);
```

### Expected behavior

The second screen load animation should override the first.

**Comment by kisvegabor** [comment]
Thanks for the report!

I wonder what should be the expected behavior in case of
```c
lv_scr_load_anim(screen1, LV_SCR_LOAD_ANIM_FADE_ON, 2000, 0, false);
lv_scr_load_anim(screen2, LV_SCR_LOAD_ANIM_FADE_ON, 2000, 1000, false);
```

I.e. the first screen is half loaded and then the other starts. It'd be simple to finish pending screen load at the beginning of `lv_scr_load_anim` but it resulted in a fully loaded `screen1` for 1 second. 

What do you think?

**Comment by pdgendt** [comment]
I didn't even consider that use case, smart!

It's even more complex if different animation types were to be used (fade vs move).

It would be nice if these animation could be chained in some way, but I agree that this is not an easy task.

**Comment by kisvegabor** [comment]
I suggest for now - to not leave it broken - fix it by finishing all animation at the beginning of `lv_scr_load_anim`.

**Comment by kisvegabor** [comment]
Please confirm if it's working well if you modify the beginning of `lv_scr_load_anim` like this:
```c
    lv_disp_t * d = lv_obj_get_disp(new_scr);
    lv_obj_t * act_scr = lv_scr_act();

    if(d->scr_to_load && act_scr != d->scr_to_load) {
        lv_disp_load_scr(d->scr_to_load);
        lv_anim_del(d->scr_to_load, NULL);
        lv_obj_set_pos(d->scr_to_load, 0, 0);
        lv_style_remove_prop(lv_obj_get_local_style(d->scr_to_load, LV_OBJ_PART_MAIN), LV_STYLE_OPA_SCALE);

        if(d->del_prev) {
            lv_obj_del(act_scr);
        }
        act_scr = d->scr_to_load;
    }

    d->scr_to_load = new_scr;
```

**Comment by pdgendt** [comment]
> Please confirm if it's working well if you modify the beginning of `lv_scr_load_anim` like this

A quick test seems to work! I'll report in a new issue if something else broke.

**Comment by kisvegabor** [comment]
Thanks!

Please report back in a few days if it works well and I will push the fix.

**Comment by pdgendt** [comment]
No issues found, you can push!

**Comment by kisvegabor** [comment]
Thank you for the feedback. I've just pushed it.
