### ISSUE TITLE
How to dynamically add button (or item) to list (or table)

### ISSUE THREAD

**Issue by cyberadio** [lvgl/lvgl#2506]
### Introduce the problem

Recently I am working on an email notification project on an ESP32 with TFT9341.
Now I have realized the email read function through the ESP Mail Client library. And also I could present part of the read information on one label now.
But now I have a problem dynamically presenting the information. My thoughts are dynamically adding buttons into a list, which could display the title and presents a message box if I click the corresponding button. I am not sure if it is possible to do this. If not, please tell me what to use for this function… Thank you guys for helping…: )

### Examples and cases

I even add one add_btn with an event. But I failed to use a timer to trigger it by lv_event_send

### Suggested solution

Totally out of my hand

**Comment by cyberadio** [comment]
@kisvegabor Please help... Thank you

**Comment by kisvegabor** [comment]
It seems doable. You can simply add items to a list in events, lv_timers, etc.

We use GitHub for development related discussion so please open a topic in the Forum (and tag me) and add a code snippet to demonstrate the problem.
