### ISSUE TITLE
Fast update on Discovery STM32F4/STM32F7 with mbedOS

### ISSUE THREAD

**Issue by bkht** [lvgl/lvgl#251]
Hi,

I just discovered lvgl, it is very great!
Using Discovery STM32F, below is my code for transferring the pixels to a discovery board.
But I would like to use DMA (or DMA2D) to speed it up, and to offload the MCU.
Is there some example code to use DMA with this?

    static void ex_disp_flush(int32_t x1, int32_t y1, int32_t x2, int32_t y2, const lv_color_t * color_p)
    {
        // In the flush function you can use DMA or any hardware to do the flushing in the
        // background, but when the flushing is ready you have to call lv_flush_ready();

        /*The most simple case (but also the slowest) to put all pixels to the screen one-by-one*/

        int32_t x;
        int32_t y;
        for(y = y1; y <= y2; y++) {
            for(x = x1; x <= x2; x++) {
                /* Put a pixel to the display. For example: */
                /* put_px(x, y, *color_p)*/
                uint32_t pixelColor = 0xff000000 |
                        color_p->red << 16 |
                        color_p->green << 8 |
                        color_p->blue;
                lcd.DrawPixel(x, y, pixelColor);
                color_p++;
            }
        }

        /* IMPORTANT!!!
        * Inform the graphics library that you are ready with the flushing*/
        lv_flush_ready();               /*Call 'lv_fluh_ready()' when ready*/
    }

BTW, I'm Running mbed-os on the platform and board drivers (BSP_DISCO_F469NI, LCD_DISCO_F469NI)

**Comment by bkht** [comment]
OK, thank you very much. Performance is not super, but about OK. :-)
I'm not sure what AC6 is, which STM32 template was used?
I would like try the AC6 path, is there an example or how-to for that?

**Comment by kisvegabor** [comment]
Hi,

AC6 (or SystemWorkbranch) is an Eclipse based IDE from STM MCUs. There are lot of example project for AC6 from STM. This post contains a getting started too:  https://littlevgl.com/blog/8/embedded-gui-on-stm32-discovery-board-with-littlev-graphics-library

However I don't know mbed-os but there are some STM32 project for AC6  in [lv_boards](https://github.com/littlevgl/lv_boards) repo.  All od them uses DMA to transfer pixels.

**Comment by bkht** [comment]
Hi Gabor, thank you very much for pointing me to this. I use eclipse with the mbed and ARM_GCC.
But I have update problems with it, not finding the update repositories, so it needs fixing sooner or later anyway. Now I'm also diving into m2m DMA with interrupt on mbed, but I need to write some code using HAL (or maybe CMSIS). Starting with AC6 would certainly help me learning and finding a solution for mbed, I hope. I enjoy your library :-) Thanks to using AA, it looks very good.

**Comment by SnifMyBack** [comment]
For people that start a new project for these boards (without the help of the mBed platform), use Atollic TrueStudio. AC6 need more configuration to make a project compile and from what I saw from my class mates, Atollic look simpler.

**Comment by kisvegabor** [comment]
@bkht  Then good luck with the DMA. :) I hope the example will help!
 
@caveman1996 Yes, Atollic is a very popular alternative. However I didn't faced any configuration difficulties with AC6.

**Comment by bkht** [comment]
Hi, lots to learn here! Thank you very much! I will check out AC6 and Atollic TrueStudio.

**Comment by bkht** [comment]
Hi Gabor,
I tested a simple memory-to-memory DMA with interrupt in mbed, using HAL functions, and got this working very quickly.
If for updating the display we use DMA, instead of plotting all the pixels, do we use m2m DMA to update the display?
Or how does this look like?
Kind regards,
Jack.

**Comment by kisvegabor** [comment]
Here I used `HAL_DMA_Start_IT` in `disp_flush`: https://github.com/littlevgl/lv_boards/blob/master/stm32f429_discovery_no_os/hal_stm_lvgl/tft/tft.c#L191

Yes, I'm interested in such a project! However I never used mbed-os so far I'm curious about it!

**Comment by bkht** [comment]
Hi Gabor,
for me, the code above gave some scattered horizontal lines, evenly spread over the vertical height on the display. I probably overlooked something.

Now use DMA without interrupt and wait for the transfer to complete.
It is a lot faster than without using DMA. 
For every horizontal line in the rectangular region, a DMA transfer is used, as we need to
increment the address of the frame buffer by the horizontal resolution of the LCD, which
makes it a non-contiguous space.
DMA with interrupt would be better, to free the
MCU to do better things than waiting, I will try it later.

    /**
    * @brief  Updates just a region of the screen containing an object
    * @note   It configures DMA for memory to memory transfers
    * @retval None
    */
    static void tft_flush(int32_t x1, int32_t y1, int32_t x2, int32_t y2, const lv_color_t * color_p)
    {
        // Updates just a rectangular region of the screen containing an object
        // such as a button, meter, or chart, that needs to be updated.
        // In the flush function you can use DMA to do the flushing in the background.
        // Each transfer is a contiguous part of source and destination,
        // basically a horizontal line, so that an DMA transfer can handle it.
        // For every new vertical position we first need to calculate the address
        // for the destination frame buffer.
        // Because color_p just only holds the data of the rectangular region,
        // it just needs to increment that pointer by the DMA size for every line.
        // Once the flushing is ready we have to call lv_flush_ready();

        /*Return if the area is out the screen*/
        if(x2 < 0) return;
        if(y2 < 0) return;
        if(x1 > TFT_HOR_RES - 1) return;
        if(y1 > TFT_VER_RES - 1) return;

        /*Truncate the area to the screen*/
        int32_t act_x1 = x1 < 0 ? 0 : x1;
        int32_t act_y1 = y1 < 0 ? 0 : y1;
        int32_t act_x2 = x2 > TFT_HOR_RES - 1 ? TFT_HOR_RES - 1 : x2;
        int32_t act_y2 = y2 > TFT_VER_RES - 1 ? TFT_VER_RES - 1 : y2;

        x1_flush = act_x1;
        y1_flush = act_y1;
        x2_flush = act_x2;
        y2_fill = act_y2;
        y_fill_act = act_y1;
        buf_to_flush = color_p;

        // A faster than the pixel-by-pixel approach is to put all pixels to the
        // screen using DMA
        static const uint32_t *ptrFBStart = lcd.GetFBStartAdress();
        uint32_t dmaSize = ((x2_flush-x1_flush) + 1);
        while(y1_flush <= y2_fill) {
            uint32_t FBIndex = (uint32_t)&ptrFBStart[y1_flush * TFT_HOR_RES + x1_flush];

            // Start the DMA transfer using polling mode
            if (HAL_DMA_Start(&hdma_memtomem_dma2_stream0,
                    (uint32_t)color_p,
                    (uint32_t)FBIndex,
                    dmaSize) != HAL_OK)
            {
                while(1);    // Halt on error
            }
            // Polling for transfer complete, if not using the interrupt
            HAL_DMA_PollForTransfer(&hdma_memtomem_dma2_stream0,
                                    HAL_DMA_FULL_TRANSFER, 1000);
            color_p += dmaSize;
            y1_flush++;
        }



        // The most simple case (but also the slowest) to update the screen
        // pixel-by-pixel
    //    for(int32_t y = y1; y <= y2; y++) {
    //        for(int32_t x = x1; x <= x2; x++) {
    //            // Put a pixel to the display.
    //            // For example: put_px(x, y, *color_p)
    //            lcd.DrawPixel(x, y, color_p->full);
    //            color_p++;
    //        }
    //    }


        // Inform the graphics library that you are ready with the flushing,
        // by calling 'lv_fluh_ready()' when ready
        lv_flush_ready();
    }

    /**
    * Enable DMA controller clock
    * Configure DMA for memory to memory transfers
    *   hdma_memtomem_dma2_stream0
    */
    static void MX_DMA_Init(void)
    {
        // DMA controller clock enable
        __HAL_RCC_DMA2_CLK_ENABLE();

        NVIC_ClearPendingIRQ(DMA2_Stream0_IRQn);
        HAL_NVIC_DisableIRQ(DMA2_Stream0_IRQn); 	// DMA IRQ Disable

        // Configure DMA request hdma_memtomem_dma2_stream0 on DMA2_Stream0
        hdma_memtomem_dma2_stream0.Instance = DMA2_Stream0;
        hdma_memtomem_dma2_stream0.Init.Channel = DMA_CHANNEL_0;
        hdma_memtomem_dma2_stream0.Init.Direction = DMA_MEMORY_TO_MEMORY;
        hdma_memtomem_dma2_stream0.Init.PeriphInc = DMA_PINC_ENABLE;
        hdma_memtomem_dma2_stream0.Init.MemInc = DMA_MINC_ENABLE;
        hdma_memtomem_dma2_stream0.Init.PeriphDataAlignment = DMA_PDATAALIGN_WORD;
        hdma_memtomem_dma2_stream0.Init.MemDataAlignment = DMA_MDATAALIGN_WORD;
        hdma_memtomem_dma2_stream0.Init.Mode = DMA_NORMAL;
        hdma_memtomem_dma2_stream0.Init.Priority = DMA_PRIORITY_LOW;
        hdma_memtomem_dma2_stream0.Init.FIFOMode = DMA_FIFOMODE_ENABLE;
        hdma_memtomem_dma2_stream0.Init.FIFOThreshold = DMA_FIFO_THRESHOLD_FULL;
        hdma_memtomem_dma2_stream0.Init.MemBurst = DMA_MBURST_SINGLE;
        hdma_memtomem_dma2_stream0.Init.PeriphBurst = DMA_PBURST_SINGLE;

        // Set the transfer complete interrupt callback function
        hdma_memtomem_dma2_stream0.XferCpltCallback = XferCpltCallback;
        hdma_memtomem_dma2_stream0.XferErrorCallback = XferErrorCallback;

        if (HAL_DMA_Init(&hdma_memtomem_dma2_stream0) != HAL_OK)
        {
            _Error_Handler(__FILE__, __LINE__);
        }

        // DMA interrupt init
        // DMA2_Stream0_IRQn interrupt configuration
        NVIC_SetVector(DMA2_Stream0_IRQn, (uint32_t )my_irq_handler);
        HAL_NVIC_SetPriority(DMA2_Stream0_IRQn, 1, 0);  // IRQn_Type, uint32_t, uint32_t
        HAL_NVIC_EnableIRQ(DMA2_Stream0_IRQn);  // DMA IRQ Enable
    }

I hope this helps others.

**Comment by kisvegabor** [comment]
Hi,

What happens if you change `LV_VDB_SIZE` (in lv_conf.h). Let's half it! Do you see twice as much "lines"?

**Comment by bkht** [comment]
Hi Gabor,

When I half it like

    #define LV_VDB_SIZE         (10 * LV_HOR_RES)

I have about doubled the number of horizontal lines (about 48 lines), where I can better see the graphical items in place. Note how this correlates to the vertical resolution of the display, which is 480.

When I half it like

    #define LV_VDB_SIZE         (5 * LV_HOR_RES)

I have again doubled the number of horizontal lines, where I can even better see the graphical items in place.

If I make it 1, if I reduce LV_VDB_SIZE to 1, it draws every line.
But reducing this value makes updates to the screen slower.
Updates to some of the graphical items appear distorted.

The used code:

    /**
    * @brief  Updates just a region of the screen containing an object
    * @note   It configures DMA for memory to memory transfers
    * @retval None
    */
    static void tft_flush(int32_t x1, int32_t y1, int32_t x2, int32_t y2, const lv_color_t * color_p)
    {
        // Updates just a region of the screen containing an object
        // such as a button, meter, or chart, that needs to be updated.
        // In the flush function you can use DMA to do the flushing in the background.
        // Each transfer is a contiguous part of source and destination,
        // basically a horizontal line, so that an DMA transfer can handle it.
        // For every horizontal line in the rectangular region, a DMA transfer is used,
        // as we need to increment the address of the frame buffer by the
        // horizontal resolution of the LCD, which makes it a non-contiguous space.
        // For every new vertical position we first need to calculate the address
        // for the destination frame buffer.
        // Because color_p just only holds the data of the rectangular region,
        // it just needs to increment that pointer by the DMA size for every line.
        // Once the flushing is ready we have to call lv_flush_ready();

        /*Return if the area is out the screen*/
        if(x2 < 0) return;
        if(y2 < 0) return;
        if(x1 > TFT_HOR_RES - 1) return;
        if(y1 > TFT_VER_RES - 1) return;

        /*Truncate the area to the screen*/
        int32_t act_x1 = x1 < 0 ? 0 : x1;
        int32_t act_y1 = y1 < 0 ? 0 : y1;
        int32_t act_x2 = x2 > TFT_HOR_RES - 1 ? TFT_HOR_RES - 1 : x2;
        int32_t act_y2 = y2 > TFT_VER_RES - 1 ? TFT_VER_RES - 1 : y2;

        x1_flush = act_x1;
        y1_flush = act_y1;
        x2_flush = act_x2;
        y2_fill = act_y2;
        y_fill_act = act_y1;
        buf_to_flush = color_p;



        // Start the DMA transfer using the interrupt mode
        // Configure the source, destination and buffer size DMA fields and start
        // the DMA Stream transfer
        // Enable All the DMA interrupts
        static const uint32_t *my_fb = lcd.GetFBStartAdress();
        HAL_StatusTypeDef err;
        if (HAL_DMA_Start_IT(&hdma_memtomem_dma2_stream0,
                            (uint32_t)buf_to_flush,
                            (uint32_t)&my_fb[y_fill_act * TFT_HOR_RES + x1_flush],
                            (x2_flush - x1_flush + 1)) != HAL_OK)
        {
            while(1);	/*Halt on error*/
        }

        // Inform the graphics library that you are ready with the flushing,
        // by calling 'lv_fluh_ready()' when ready
        // lv_flush_ready();
    }

    /**
    * @brief  DMA transfer complete callback
    * @note   This function is executed when the transfer complete interrupt
    *         is generated
    * @retval None
    */
    static void XferCpltCallback(DMA_HandleTypeDef *DmaHandle)
    {
        if (DmaHandle->Instance == DMA2_Stream0)
        {
            ;
        }
        lv_flush_ready();               /*Call 'lv_fluh_ready()' when ready*/

    }

Note the 'lv_flush_ready();' on the end, it is called in a callback.

Kind regards,
Jack.

**Comment by kisvegabor** [comment]
It seems somehow you don't flushes the last line. However you code seems fine because you wrote  `while(y1_flush <= y2_fill) `

**Comment by bkht** [comment]
Hi Gabor, thank you for the quick response! The code where I wrote above, 3 days ago, actually works just fine, but it doesn't use interrupts.
I tried to implement a DMA with interrupt approach, but that gives some trouble so far.
With the code I posted this morning, I have those limited number of lines across the screen, as that code is missing to keep track where it left off, I think.
Somehow I have to create multiple DMA transfers to update the graphics in horizontal lines, in order to be able to use DMA over some contiguous frame buffer space.
So I need to trigger DMA transfers until the object has been entirely repainted and keep track when the last part has been written and then lv_flush_ready can be called.
But I wasn't successful in that approach, yet. Once I manage to do that, I will post the code here.

**Comment by bkht** [comment]
Hi, it works fine now, the above piece was indeed missing.
Note, I had to make my_fb an uint32_t.
This works using mbed-os on a DISCO-F469NI with 800x480 TFT.
Soon, I will also test this on a discovery DISCO-F746NG with 480x272 TFT.
If somebody want the code of the demo, I'm happy to post it.

In the main loop, I have to include both

	lv_tick_inc(1);
	lv_task_handler();

to get an image.
Is that correct?

**Comment by kisvegabor** [comment]
Congratulation! :)

`lv_tick_inc(1);` should go to a 1 ms Timer interrupt and `lv_task_handler()` to a loop called in every 3..30 ms (no so critical).

**Comment by effeci** [comment]
@bkht I would like to know if you have any news on a f746 demo. Thanks!

**Comment by bkht** [comment]
@effeci Hi, de demo works very well, thanks to Gabor, who pointed me to some directions.
Note, I use Mbed-OS, and DMA with interrupt for littlevgl.
It is just a screen with some widgets on it.
The buttons control LEDs and the slider does move a point in the chart.
Just discovering littlevgl.
I hope to contribute to it later as well, if I find some time.

**Comment by effeci** [comment]
Glad to eat you back! Is it possible to have any access to this demo?

**Comment by bkht** [comment]
Sure! I'm learning from people here and I like to help other people as well. :-)
Just uploaded, here you go:
https://github.com/bkht/DISCO-F469NI_LCD_Demo2

**Comment by effeci** [comment]
Thank you! Is this compatible with the f746ng development board? I agree with you but, in my case I feel a little bit ashamed of not having nothing to share !

**Comment by kisvegabor** [comment]
@bkht Thank you for sharing your project! I'm sure it will help others who also uses mbedOS!

I close this issue because the goal seems to be reached. If you have further questions or remarks feel free to comment here and reopen this issue.

**Comment by nmathon** [comment]
Hi everyone. Did you test it on F746NG ? 
Thanks

**Comment by embeddedt** [comment]
@effeci @nmathon In general you will need to make some changes in order to get an F4 demo running on an F7, due to pin changes and possible hardware incompatibilities.
