### ISSUE TITLE
The object has a strange border after opening the shadow

### ISSUE THREAD

**Issue by FASTSHIFT** [lvgl/lvgl#2519]
### Perform all steps below and tick them with [x]
- [x] Check the related part of the [Documentation](https://docs.lvgl.io/)
- [x] Update lvgl to the latest version
- [x] Reproduce the issue in a [Simulator](https://docs.lvgl.io/latest/en/html/get-started/pc-simulator.html)

### Describe the bug
After opening `style_shadow`, a strange border appears on the edge of the object. When the `style_radius` is set to be greater than 1, the shadow can be displayed normally.

### To Reproduce
```c
void shadow_test()
{
    lv_obj_t* cont = lv_obj_create(lv_scr_act());
    lv_obj_remove_style_all(cont);
    lv_obj_center(cont);

    lv_obj_set_style_bg_opa(cont, LV_OPA_60, 0);
    lv_obj_set_style_bg_color(cont, lv_color_black(), 0);
    lv_obj_set_style_shadow_color(cont, lv_color_black(), 0);
    lv_obj_set_style_shadow_width(cont, 10, 0);
    //lv_obj_set_style_radius(cont, 10, 0);
}
```
### Expected behavior
The shadow can be displayed normally.

### Screenshots or video
`style_radius` = 0
![image](https://user-images.githubusercontent.com/26767803/131809038-de464d81-e583-467f-9e9e-bb49da0f9b12.png)

`style_radius` = 10
![image](https://user-images.githubusercontent.com/26767803/131809099-4edcfd91-58f7-4c10-b297-0bf812de7fe1.png)

**Comment by kisvegabor** [comment]
Do you use the latest version from master? The border with no radius was 1 px ticker but it's already fixed.

**Comment by FASTSHIFT** [comment]
> Do you use the latest version from master? The border with no radius was 1 px ticker but it's already fixed.

Yes, I am sure I am using the latest master.I didn’t enable the border.

**Comment by kisvegabor** [comment]
I've found the bug and fixed it.

**Comment by FASTSHIFT** [comment]
thank you
