### ISSUE TITLE
Bug with LV_ARC_MODE_REVERSE

### ISSUE THREAD

**Issue by jadonmmiller** [lvgl/lvgl#2522]
### Describe the bug
It seems when I use LV_ARC_MODE_REVERSE with lv_arc_set_bg_angles and lv_arc_set_value the arc gets drawn erratic ways. It starts the indicator in the middle of the background and draws it off the background.

If I drag the arc handle to the left of its default position, the indicator flips around full circle and draws off the background (see the last screenshot).

Check out the [forum post](https://forum.lvgl.io/t/bug-with-lv-arc-mode-reverse/6655) (so far no responses).

### To Reproduce
```c
        static lv_obj_t* arcBlack;
        arcBlack = lv_arc_create(lv_scr_act());
        lv_arc_set_mode(arcBlack, LV_ARC_MODE_REVERSE);
        lv_arc_set_bg_angles(arcBlack, 0, 90);
        lv_arc_set_value(arcBlack, 40);
```

### Expected behavior
An arc exactly like the non-reversed image below (the first one) but with the indicator on the opposite side of the background.

### Screenshots or video
The code above without the reverse line:
![Working without reverse mode](https://forum.lvgl.io/uploads/default/original/2X/6/64bbbe87758b5948e8a90bcb0b78190caa803d2f.png)

The unmodified arc in reverse mode:
![The arc in reverse mode](https://forum.lvgl.io/uploads/default/original/2X/e/e81ea18a472c3f3ea70c8e80845ee4de2afa4368.png)

The reversed arc above, but dragged backwards:
![Reversed and dragged backwards](https://forum.lvgl.io/uploads/default/original/2X/4/4d393d281e4da78bbc02a31b206a19df8b51affc.png)

**Comment by kisvegabor** [comment]
Thank you for the report. I've pushed a fix.
