### ISSUE TITLE
lv_chart_set_type() - invalid conversion from int to lv_chart_type_t

### ISSUE THREAD

**Issue by bkht** [lvgl/lvgl#253]
Hi,
I found a minor issue, when trying the Chart example, with this line:

    lv_chart_set_type(chart, LV_CHART_TYPE_POINT | LV_CHART_TYPE_LINE);

Error: invalid conversion from 'int' to 'lv_chart_type_t' [-fpermissive]

**Comment by kisvegabor** [comment]
Hi,

Thank you!

With my settings it didn't cause warning but is should be fixed!
 
Introducing an `LV_CHART_TYPE_LINE_AND_POINT` type should solve it. What do you think?

**Comment by bkht** [comment]
Hi Gabor,
I think the OR operation isn't the issue here, as the toolchain complains about the conversion from 'int' to 'lv_chart_type_t'.
It seems I just can't pass an int to the function.
I tried casting using (lv_chart_type_t), but same result.
I'm a bit puzzled, about this one... :-)
Just modifying the function so it can pass an int or enum could possibly be a solution, do you think?
And if you introduce LV_CHART_TYPE_LINE_AND_POINT you may end up with lots of combinations in the future. :-)
And it may not solve this problem.

**Comment by kisvegabor** [comment]
Hi,
It's strange. I googled on this warning and found some C++ related topics. Are you using C++?

**Comment by bkht** [comment]
Yes, I'm using C++. I will try to figure this out. Thanks!

**Comment by kisvegabor** [comment]
I found this: https://stackoverflow.com/questions/11452920/how-to-cast-int-to-enum-in-c

So maybe it works:
```cpp
    static_cast<lv_chart_type_t>(LV_CHART_TYPE_LINE | LV_CHART_TYPE_POINT)
```

**Comment by bkht** [comment]
Hi Gabor, you are awesome! This works!
I saw something similar on stackoverflow, but didn't test it yet, as I'm quite busy these days.
Because you have put your effort in finding a solution for me, I wanted to thank you and give you giveback :-)
So to help other people who use C++, I confirm your finding is the solution, Gabor!
We do now have the dots in the graph:

    lv_chart_type_t type = static_cast<lv_chart_type_t>(LV_CHART_TYPE_POINT | LV_CHART_TYPE_LINE);
    lv_chart_set_type(chart, type);   /*Show lines and points too*/

Or just:

    lv_chart_set_type(chart, static_cast<lv_chart_type_t>(LV_CHART_TYPE_POINT | LV_CHART_TYPE_LINE));   /*Show lines and points too*/

I hope, I don't bother you too much, though... :-)

**Comment by kisvegabor** [comment]
Awesome!

Bother? The opposite! I'm always happy to see so enthusiastic people like you! Keep this great work! :)

As the issue seems solved I close this issue.
