### ISSUE TITLE
Lighter images

### ISSUE THREAD

**Issue by Alasknnj** [lvgl/lvgl#254]
Hi,

First of all, great library! I would just like to leave an enhancement idea, which I did not find as a suggestion here.

We were going to use this library for our project, we even started porting, but then I found out that the image files need to be either in RAM or in a file system, defined by a driver that we could write. 

The problem was only that the binary format for the images is too large, we can't rely on such large files for our embedded device, our current image format solution occupies less than 1/4 of your image format size. 

I can think of 2 ways to help in that regard:
* A more obvious one is to use other image formats, maybe rely on PNG format, or use palettes to encode pixels with less bits.
* Allow users to register other functions to "build" the image, instead of the lv_img_set_src() function, which would make the user have to do more low level stuff, but in our case, would solve the problem easily.

For an embedded library, it would be expected for lightweight resources to be used. If only for that, we would have opted for this library. With that done, it would be the perfect call for our needs.

Cheers. Keep up the good work.

**Comment by kisvegabor** [comment]
Hi,

Thank you!

It's a very reasonable requirement. 
Both options are possible:
1. Adding a PNG decoder could be enough in almost all cases
2. If you could provide a function like`get_image_data(x1,y1,x2,y2, data)` then it would be easy to add this functionality to LittlevGL. 

What do you think about it?

**Comment by kisvegabor** [comment]
Besides image decoder interface to enable the use of lighter images I'm planning to add support for indexed images with 1, 2, 4 or 8-bit colors and/or 1, 2, 4, 8-bit alpha. 
For example, a 2-bit image (4 colors) has 1/8 size compared to a 16-bit image!

**Comment by kisvegabor** [comment]
A new image converter tool is added with a lot of new features including 1,2,4,8 bit color formats. For test available here: http://www.test.littlevgl.com/image-to-c-array

It is compatible with the `dev-5.2` branch.

If you have questions or remarks please open a new for them!
