### ISSUE TITLE
Enable new functions in lv_micropython

### ISSUE THREAD

**Issue by Karijn** [lvgl/lvgl#2540]
### Introduce the problem
I see that the new functions i added to lvgl are in the latest lv_micropython version. 
But how can i enable them in micropython (I don't find them in the lv_mpy_example.c file)

### Examples and cases
i created a PR for lv_obj_move_to_index() and others, now i would like to use them in micropython.

### Suggested solution
probably add something to gen_mpy.py ?

**Comment by embeddedt** [comment]
Ensure that you have checked out the latest `master` commit from lv_micropython and that you ran `git submodule update --recursive` afterwards.

**Comment by amirgon** [comment]
I can confirm `move_to_index` is working on Micropython.
[Here is an example on the online simulator ](https://sim.lvgl.io/v8.1/micropython/ports/javascript/index.html?script_startup=https://raw.githubusercontent.com/lvgl/lvgl/eb6ae526432453e4b9dbc7a760cd65d164050548/examples/header.py&script=https://raw.githubusercontent.com/lvgl/lvgl/eb6ae526432453e4b9dbc7a760cd65d164050548/examples/widgets/list/lv_example_list_1.py&script_direct=42801b5758b3fc863827d1c4bb49a21dea43c927)

**Comment by Karijn** [comment]
Hmmm, i couldn't find the functions in code after building, but they do work

**Comment by amirgon** [comment]
> Hmmm, i couldn't find the functions in code after building, but they do work

`lv_mpy_example.c` is just an example (for user reference) and not really used for anything.

The actual lvgl module is automatically generated as part of the build process so you can find it under the "build" directory (it's called `lv_mpy.c`).
