### ISSUE TITLE
Stack-overflow when i use lv_obj_move_foreground in LV EVENT CHILD_CHANGED event callback

### ISSUE THREAD

**Issue by qinshijing** [lvgl/lvgl#2541]
### Perform all steps below and tick them with [x]
- [x] Check the related part of the [Documentation](https://docs.lvgl.io/)
- [x] Update lvgl to the latest version
- [x] Reproduce the issue in a [Simulator](https://docs.lvgl.io/latest/en/html/get-started/pc-simulator.html)

### Describe the bug
Stack-overflow when i use lv_obj_move_foreground in LV EVENT CHILD_CHANGED event callback.

### To Reproduce
static void child_changed_event_cb(lv_event_t* e)
{
    lv_event_code_t code = lv_event_get_code(e);
    lv_obj_t* obj = lv_event_get_current_target(e);
    lv_obj_t* sb = lv_event_get_user_data(e);
    if (code == LV_EVENT_CHILD_CHANGED) {
        lv_obj_t* p = lv_event_get_param(e);
        if (sb && p) {
            lv_obj_move_foreground(sb);
        }
    }
}
static void test(void)
{
    lv_obj_t* cont = lv_obj_create(lv_scr_act());
    lv_obj_set_size(cont, 400, 400);
    lv_obj_center(cont);
    /* I want obj1 to always be on top */
    lv_obj_t* obj1 = lv_obj_create(cont);
    lv_obj_add_event_cb(cont, child_changed_event_cb, LV_EVENT_ALL, obj1);
    lv_obj_set_size(obj1, 200, 200);
    lv_obj_center(obj1);
    lv_obj_t* label = lv_label_create(obj1);
    lv_label_set_text(label, "I am foreground obj");
    /* Obj created after */
    lv_obj_t* obj2 = lv_obj_create(cont);
    lv_obj_set_size(obj2, 200, 200);
    lv_obj_center(obj2);
}

### Expected behavior
In the lv_obj_move_to_index() function, I think that in the process of exchanging children, the LV_EVENT_CHILD_CHANGED event should not be sent to the outside, because there will be two identical children at this time, which may cause problems.

**Comment by kisvegabor** [comment]
You are right, I've just pushed a fix. 

As many children might change now it send only one event at the end with `NULL` parameter. 

cc @Karijn
