### ISSUE TITLE
There are two branches for LV_EVENT_SCROLL_END in the function of lv_obj_event，and the second branch cannot be executed. Is there a problem?

### ISSUE THREAD

**Issue by Johnxjj** [lvgl/lvgl#2547]
，

**Comment by kisvegabor** [comment]
Please fill the issue template to provide enough information about your issue.

**Comment by Johnxjj** [comment]
![image](https://user-images.githubusercontent.com/18185301/134796234-6416f88e-8bf0-4b58-ace1-6c0e2c4a1e35.png)

**Comment by Johnxjj** [comment]
@kisvegabor

**Comment by Johnxjj** [comment]
I've marked it in red

**Comment by kisvegabor** [comment]
@Johnxjj 
Thanks for pointing it out, I've just fixed it.
