### ISSUE TITLE
lv_arc: Using uninitialized variable

### ISSUE THREAD

**Issue by C47D** [lvgl/lvgl#2548]
`angle` can be used without being initialized (if we fall in the default switch case) in here `arc->last_angle = angle;`

https://github.com/lvgl/lvgl/blob/37a5d0c85ac28718f4f32eadff3ddaf6b474cf75/src/widgets/lv_arc.c#L821-L851

Is this expected? I tried to catch the issue using cppcheck but I haven't been able to do so.

Another question, Should we assert using a valid `arc->type` at the beginning of the `value_update` API? Something like this:

```diff
diff --git a/src/widgets/lv_arc.c b/src/widgets/lv_arc.c
index 4c971dc25..afbd1dc3d 100644
--- a/src/widgets/lv_arc.c
+++ b/src/widgets/lv_arc.c
@@ -812,6 +812,8 @@ static void value_update(lv_obj_t * obj)
     LV_ASSERT_OBJ(obj, MY_CLASS);
     lv_arc_t * arc = (lv_arc_t *)obj;

+    LV_ASSERT(LV_ARC_MODE_NORMAL <= arc->type && LV_ARC_MODE_REVERSE >= arc->type);
+
     /*If the value is still not set to any value do not update*/
     if(arc->value == VALUE_UNSET) return;
```

**Comment by embeddedt** [comment]
The default switch case returns early (line 848), so I don't think it is possible for `angle` to be used uninitialized, unless I've read the code incorrectly.

**Comment by C47D** [comment]
You're right, it does return when falling in the default case. I totally missed that.

What about asserting the arc type at the beginning of the function?
