### ISSUE TITLE
Chat style

### ISSUE THREAD

**Issue by Moo2017** [lvgl/lvgl#257]
Hi,
I'd like to create a chat style menu, same as messaging applications like Whatsup and ... , any idea which object is the best option for that? I was thinking of using list object but the problem is I can not move buttons in the list .
I can change btns size in the list individually but I wasn't able to move them.
I am looking for an object to create the following style:
![chatsample](https://user-images.githubusercontent.com/34062463/40205099-d039b806-59f8-11e8-87ff-70bdba97d37e.png)

**Comment by kisvegabor** [comment]
Hi,

You can create an `lv_page` (to have a scrollable parent) and add labels to it. The label's `lv_label_set_body_draw()` feature can draw a background for the labels.

As it's a quite specific layout you should set the positions manually. However it's not so difficult because you just can align to the previous label.

**Comment by Moo2017** [comment]
Hi, thanks
But I can not select the labels and add call back function to that, user should be able to select its desired message and be able to do delete , resend or reply operation .That is the reason I wanted to use list object. What if I add some buttons in the page ? Also I should mention that I am using hardware keyboard , can I scroll them if all buttons can not be displayed in the screen? There is not limit to add objects to a group?
It's not possible to set the x position for the list's items individually so this can be done only with list object.

**Comment by kisvegabor** [comment]
I see. Then you really should use buttons instead of simple labels. 
But the list object is too strict for this purpose. I suggest to use a simple page where you can position the objects freely. The list will align the buttons in one column. 

The number of objects ina group is not limited.

**Comment by Moo2017** [comment]
- How can scroll among the objects? I think I should implement my own function . for example if I have 10 messages but only 5 can be fit in the screen once user selects 5th item and presses next key items should scroll up and I think this is not done automatically? 
- I can not change this in the code "The list will align the buttons in one column" ?
- One more question, Is that possible to scroll the page using hardware key?

**Comment by kisvegabor** [comment]
1. You can set a **focus callback** for the group (`lv_group_set_focus_cb`). This function will be called after changing focus. In this function you can apply `lv_page_focus(page, btn, anim_time)` to bring the new button into the visible area. 
2. You can change the layout of the list but there is no layout to put the objects to left and right alternately.
3. Right now there is no way to scroll the page via hardware key but it's planned feature for the next minor release.

**Comment by Masi2017** [comment]
I created a page and then added some buttons there . In lv_group_set_focus_cb callback function I called lv_page_focus(page, btn, anim_time) but it didn't work . I attached the code , would you please see if I am doing something wrong there? 
[chatStyleCode.txt](https://github.com/littlevgl/lvgl/files/2039764/chatStyleCode.txt)

**Comment by Moo2017** [comment]
Thank you very much it worked only I had to enable lv_page_set_scrl_fit to true otherwise it didn't bring the selected obj to visible area ( it's the same with list and dropdown list too) and on the other hands if I enable this I can not set the position of children in x and y direction freely but as per the document I should align them together .

**Comment by kisvegabor** [comment]
Great!

How did you enabled `lv_page_set_scrl_fit`? I mean with which parameter?

**Comment by Moo2017** [comment]
lv_page_set_scrl_fit(page,false,true)
In order to be able to move the selected obj to visible area if it's not in the visible area you have to set ver_en to true. Same story for List object.

**Comment by Moo2017** [comment]
Hi
 I created a linked list for messages information, I'd like to show text from a static array in  the created labels for the buttons . I have a receive task which receive messages from server, receive task may delete the oldest message from the liked list if max message number exceed , so I have to add a mutex since both tasks are using linked list at the same time and they might try to change that but I don't know how this can be added in littlevgl since as soon as keypad is pressed , prev or next object will be shown automatically and cursor will move to that button ( I am not sure even if object is not in the visible area this causes a problem or not?) , any idea bout this? can I handle this situation?

**Comment by kisvegabor** [comment]
Hi,

`lv_page_set_scrl_fit(page,false,true)` should be the default setting.

Mutex:
Please open a new issue for it as it's a different topic.

**Comment by Moo2017** [comment]
Ok thanks, I think we can close this ticket since I created the chat style screen as per your suggestions. Thank you!

**Comment by kisvegabor** [comment]
Okay!

**Comment by Moo2017** [comment]
Hi @kisvegabor 
As you can see here , I had to create a chat style menu using page and button objects. Now I had to enable touch input. I don't know how I can scroll on the page using touch ( also same for other objects like drop down list , list , roller and any objects needs to be scrolled) ? I have 20 buttons on the page and only 5 are visible , so user needs to be able to scroll and select them and then send or delete them and does other stuffs.

**Comment by kisvegabor** [comment]
Hi,

The scrolling should work on `lv_page` by default. Can't you scroll it like a list?

A screenshot and a simplified code would help.

**Comment by Moo2017** [comment]
@kisvegabor Thank you very much, I did some changes in my touch driver and problem is resolved.
