### ISSUE TITLE
Errors (19 Items) undefined reference SDL...

### ISSUE THREAD

**Issue by epikao** [lvgl/lvgl#259]
Hello, I try to build pc_simulator project, but I get follow 19 errors, what do I wrong??:

Description	Resource	Path	Location	Type
undefined reference to `SDL_CreateRenderer'	monitor.c	/pc_simulator/lv_drivers/display	line 211	C/C++ Problem
undefined reference to `SDL_CreateTexture'	monitor.c	/pc_simulator/lv_drivers/display	line 212	C/C++ Problem
undefined reference to `SDL_CreateThread'	main.c	/pc_simulator	line 105	C/C++ Problem
undefined reference to `SDL_CreateThread'	monitor.c	/pc_simulator/lv_drivers/display	line 70	C/C++ Problem
undefined reference to `SDL_CreateWindow'	monitor.c	/pc_simulator/lv_drivers/display	line 207	C/C++ Problem
undefined reference to `SDL_Delay'	main.c	/pc_simulator	line 117	C/C++ Problem
undefined reference to `SDL_Delay'	monitor.c	/pc_simulator/lv_drivers/display	line 245	C/C++ Problem
undefined reference to `SDL_DestroyRenderer'	monitor.c	/pc_simulator/lv_drivers/display	line 249	C/C++ Problem
undefined reference to `SDL_DestroyTexture'	monitor.c	/pc_simulator/lv_drivers/display	line 248	C/C++ Problem
undefined reference to `SDL_DestroyWindow'	monitor.c	/pc_simulator/lv_drivers/display	line 250	C/C++ Problem
undefined reference to `SDL_Init'	monitor.c	/pc_simulator/lv_drivers/display	line 203	C/C++ Problem
undefined reference to `SDL_PollEvent'	monitor.c	/pc_simulator/lv_drivers/display	line 234	C/C++ Problem
undefined reference to `SDL_Quit'	monitor.c	/pc_simulator/lv_drivers/display	line 251	C/C++ Problem
undefined reference to `SDL_RenderClear'	monitor.c	/pc_simulator/lv_drivers/display	line 228	C/C++ Problem
undefined reference to `SDL_RenderCopy'	monitor.c	/pc_simulator/lv_drivers/display	line 229	C/C++ Problem
undefined reference to `SDL_RenderPresent'	monitor.c	/pc_simulator/lv_drivers/display	line 230	C/C++ Problem
undefined reference to `SDL_SetEventFilter'	monitor.c	/pc_simulator/lv_drivers/display	line 205	C/C++ Problem
undefined reference to `SDL_UpdateTexture'	monitor.c	/pc_simulator/lv_drivers/display	line 217	C/C++ Problem
undefined reference to `SDL_UpdateTexture'	monitor.c	/pc_simulator/lv_drivers/display	line 227	C/C++ Problem

**Comment by epikao** [comment]
windows 10, and yes I have followed the steps, but I have not the folder "/x86_64-w64-mingw32" so I have include the SDL2 folder and files in C:\MinGW\include and lib additional in C:\MinGW\mingw32\include and lib

**Comment by kisvegabor** [comment]
Maybe you copied the files into a wrong place. Please have look at this: https://github.com/littlevgl/lvgl/issues/123#issuecomment-371322117

It seems somehow the directory structure of mingw is not same for everyone.

**Comment by epikao** [comment]
should I create the follow two folder? -> 
 /.../x86_64-w64-mingw32/

is "..." really a folder or does it stand for something else?

**Comment by kisvegabor** [comment]
No you shouldn't. 

"..." means some folder which might be different. 

What if you search for "x86_64-w64-mingw32" folder? Is there any result?

**Comment by epikao** [comment]
>What if you search for "x86_64-w64-mingw32" folder? Is there any result?

no result, I also tried to create that folder with required content "C:\MinGW\x86_64-w64-mingw32\include and lib - but without success.

>/.../

how looks your folder for example?

or should I try/download MinGW-w64 instead of MinGW??
http://mingw-w64.org/doku.php/download

**Comment by kisvegabor** [comment]
If you have a 64-bit Windows you should choose 64 bit MinGW with 64 bit SDL libraries.

It looks like this for me:
![mingw](https://user-images.githubusercontent.com/7599318/40348767-dc5ca922-5da4-11e8-9508-0b96fc565818.png)

**Comment by epikao** [comment]
> If you have a 64-bit Windows you should choose 64 bit MinGW with 64 bit SDL libraries.

I am a little bit confused about that, because there is no choice on the homepage, respectively there is only one download, one file (no 32 and 64bit version)....
https://sourceforge.net/projects/mingw/files/

and probably I should try another mingw like below link, but I think that is another and not same mingw as required for littlevgl pc simulator...:
http://mingw-w64.org/doku.php/download

**Comment by kisvegabor** [comment]
I suggest to try the latter (http://mingw-w64.org/doku.php/download)

LittlevGL doesn't depend too much on the compiler (I mean it doesn't use compiler specific features) so it should work with the other MinGW too. 

If you will confirm that the MinGW from the link above works well I will suggest it in on LittlevGL's website!

**Comment by epikao** [comment]
>I suggest to try the latter (http://mingw-w64.org/doku.php/download)

I did it now (install x86 architectur) and now I can find the mentioned folder as follow:
C:\MiniGW\mingw64\x86_64-w64-mingw32\

but at the moment I have another problem, respectively two errors with gcc and g++? I think I must be a setup something in the environment variables... but I don't know how, what??

Description	Resource	Path	Location	Type
Program "g++" not found in PATH	pc_simulator		Project Properties, C++ Preprocessor Include.../Providers, [CDT Cross GCC Built-in Compiler Settings] options	C/C++ Scanner Discovery Problem
Program "gcc" not found in PATH	pc_simulator		Project Properties, C++ Preprocessor Include.../Providers, [CDT Cross GCC Built-in Compiler Settings] options	C/C++ Scanner Discovery Problem

**Comment by kisvegabor** [comment]
Have you tried to restart your PC?

**Comment by kisvegabor** [comment]
If the restart doesn't work please try this: https://stackoverflow.com/questions/11703432/eclipse-c-program-g-not-found-in-path

And be sure the path to "gcc" is really in your PATH variable.

**Comment by epikao** [comment]
ok. now the two errors (gcc, g++) have disappeared.
I think follow did help:
- in windows - system - advanced system setting - environment variable  => in "Path" follow path: C:\MiniGW\mingw64\bin
- Additional the same in eclipse. 
- In toolchain I chosed MinGW GCC.
- Delete log-file in .metadata from workspace
- Import the project new + follow guide: https://littlevgl.com/pc-simulator 
- Clean project + build.
- Add SDL2.dll in Debug folder from pc-simulator

now it works :-) 👍  thank you very much

**Comment by kisvegabor** [comment]
Super! Well done! :)

Just to be sure: finally you used this link, right? http://mingw-w64.org/doku.php/download

**Comment by epikao** [comment]
> Just to be sure: finally you used this link, right? http://mingw-w64.org/doku.php/download

YES. Thanks

**Comment by kisvegabor** [comment]
I updated https://littlevgl.com/pc-simulator 
Thank you!
