### ISSUE TITLE
Transparent screen background

### ISSUE THREAD

**Issue by ngsann** [lvgl/lvgl#262]
I am trying to draw a simple object onto the Linux framebuffer. The object does not takes up the whole screen. When the object is drawn to the screen, the background is always white. Is there a way to make the background of the screen transparent? The color space used is argb and the "a" is always the same value (0xff) regardless of the transparency set.

**Comment by kisvegabor** [comment]
Hi,

I think I'm not clearly understand.
The screen is the most bottom object and there is not other object behind it. So it's pointless to make it transparent.

What is your goal? What do expect to see with a transparent screen?

**Comment by ngsann** [comment]
I'm using it to draw a menu over a video image, essentially an OSD. I need the screen background to be transparent to see the video behind the menu.

**Comment by kisvegabor** [comment]
Hm, I never tried to use LittlevGL this way.
But I have an  idea how to realize transparency for this purpose. At the end of  `fbdev_flush` do this:
```c
    memset(color_p, 0x00, sizeof(lv_color_t) * LV_VDB_SIZE);
```
It will always initialize LittlevGL's internal graphics buffer with `alpha == 0` so the pixels where LittelvGL doesn't draw will remain transparent.

In your GUI you still have to set you screen's style to transparent (else LittlevGL will draw it)
```c
    lv_obj_set_style(lv_scr_act(), &lv_style_transp);
```
I never tested it, so I'm also very curious how it will work. :)

But there is an other thing: LittlevGL draws/redraws only if something has changed. So the movie will overwrite the OSD in every frame, right? Or do you have two buffer (one for the movie and one for the OSD) which will be blended together?

**Comment by ngsann** [comment]
I have 2 buffer, one for the osd. I will try out your suggestion and post back the result. Thanks.

**Comment by kisvegabor** [comment]
Meanwhile I also tested it and found a  mistake in my suggestion:
Please replace the `memset` part with:
```c
    lv_vdb_t * vdb = lv_vdb_get();
    memset(vdb->buf, 0x00, sizeof(lv_color_t) * LV_VDB_SIZE);
```

This way it worked for me.

**Comment by ngsann** [comment]
I have tested it your suggestion and it is working well.
Thank you.

**Comment by ngsann** [comment]
I only have a simple menu now, nothing much, as I still just trying out the library. 

![menu osd](https://user-images.githubusercontent.com/18682407/40541958-957e6be0-6050-11e8-9f77-a2319e9b0365.jpg)

**Comment by kisvegabor** [comment]
Looks good! Really like an OSD menu!

If you want I happily share a screenshot about this project on the www.littlevgl.com

**Comment by ngsann** [comment]
I have no issue if you want to share it. Thanks for the great library.

**Comment by kisvegabor** [comment]
I also thank you!
Then please post a screenshot if you are in that stage you wanna share.

**Comment by OhtokaniPinzon** [comment]
Hi @kisvegabor 

I am trying to make an LVGL GUI using wayland, that overlays on top of a video stream (which will be playing in a separate wayland window), I need to set transparency to my LVGL GUI in a way sucj that the video would be visible all the time, and only some buttoms of my GUI would be displayed on top of the video and all the GUI background would be transparent.

I tried your suggestion:

    lv_vdb_t * vdb = lv_vdb_get();
    memset(vdb->buf, 0x00, sizeof(lv_color_t) * LV_VDB_SIZE);

but lv_vdb_t and lv_vdb_get are not defined in my LVGL repo, I am using LVGL V8.3.2
Is there a special branch I have to use to enable this transparency feature?
Is it possible to do this in LVGL v8.3.2?

Best Regards!
Ohtokani

**Comment by kisvegabor** [comment]
Hi,

`vdb` is a very old LVGL concept and it was removed many years ago. Is it an option for you to update to LVGL v9? @daniel-rossier is working on a Wayland driver which will be built in LVGL so it will have better support.
