### ISSUE TITLE
How is the value for lv_roller set if control by keyboard?

### ISSUE THREAD

**Issue by ngsann** [lvgl/lvgl#263]
When controlling the lv_roller by keyboard, LV_GROUP_KEY_LEFT, LV_GROUP_KEY_RIGHT, LV_GROUP_KEY_UP, LV_GROUP_KEY_DOWN controls the selection of the roller and LV_GROUP_KEY_ENTER calls the callback but when the roller is defocus, the value is reverted to the original value. How do I set the value?

In lv_roller.c, the sel_opt_id is saved when the roller gets focus and is reverted when it lost focus because sel_opt_id != sel_opt_id_ori 

```
else if(sign == LV_SIGNAL_FOCUS) 
{
        ext->ddlist.sel_opt_id_ori = ext->ddlist.sel_opt_id;
}
else if(sign == LV_SIGNAL_DEFOCUS) 
{
        /*Revert the original state*/
       if(ext->ddlist.sel_opt_id != ext->ddlist.sel_opt_id_ori) 
       {
            ext->ddlist.sel_opt_id = ext->ddlist.sel_opt_id_ori;
            refr_position(roller, true);
        }
}
```

LV_GROUP_KEY_ENTER does not set sel_opt_id_ori. Is this intentional? If so, how is sel_opt_id_ori set?

```
else if (c == LV_GROUP_KEY_ENTER || c == LV_GROUP_KEY_ENTER_LONG) 
{
            if(ext->ddlist.action)
                ext->ddlist.action(roller);
}
```

**Comment by kisvegabor** [comment]
Hi,

It was a bug. It should have update `sel_opt_id_ori`.
I fixed it in the `beta` branch.

Thank you for reporting the issue!
