### ISSUE TITLE
Probably an erroneous remembering of the previously clicked object when changing the focus by keyboard

### ISSUE THREAD

**Issue by yuriy-menchinskiy** [lvgl/lvgl#2647]
### Perform all steps below and tick them with [x]
- [x] Check the related part of the [Documentation](https://docs.lvgl.io/)
- [x] Update lvgl to the latest version
- [x] Reproduce the issue in a [Simulator](https://docs.lvgl.io/latest/en/html/get-started/pc-simulator.html)

### Describe the bug
If you select a textarea with the mouse/touchpad and then switch focus to the next textarea with the keyboard, it becomes impossible to select the first textarea again with the mouse/touchpad

### To Reproduce
1. Run the simulator without changing the code
2. Use mouse to click on the 'user name' field, the 'user name' field will get the focus
3. Press TAB to switch the focus to the 'password' field
4. Try switching back to the 'user name' field with the mouse. Unfortunately, you will not be able to select 'user name' field again unless you first click on some other object

### Expected behavior
Сhanging the focus using the keyboard should not affect the ability to change the focus using the mouse and vice versa

**Comment by kisvegabor** [comment]
Which demo/example do you use?

**Comment by yuriy-menchinskiy** [comment]
lv_sim_visual_studio.
This problem is also present in v8.1.0 on the real device.

**Comment by kisvegabor** [comment]
I mean you have mentioned the "user name" field. In which LVGL example do you see it?

**Comment by yuriy-menchinskiy** [comment]
![lvgl8](https://user-images.githubusercontent.com/92181628/137907720-57ac3b04-a4c7-450c-9ffc-4cb3de0ddeb4.png)

**Comment by kisvegabor** [comment]
Got it now, thanks. 

I've fixed it in https://github.com/lvgl/lv_demos/commit/17848c991620e39d5d87e6ca4abedea2347c64a3
