### ISSUE TITLE
compile error/crash when using lv_page_get_scrl and styles in combination

### ISSUE THREAD

**Issue by T94T** [lvgl/lvgl#2650]
I try to run this code with 7.11.0. Unfortunately this let my ESP32S2 reboot. The emulator also quits compilation with `Error -11`.

```
lv_obj_t* screen;
lv_obj_t* page;
page = lv_page_create(screen, NULL);
lv_obj_t *cont = lv_page_get_scrl(page);
lv_cont_set_layout(cont, LV_LAYOUT_COLUMN_MID);

lv_style_t buttonStyle;
lv_style_init(&buttonStyle);
lv_style_set_bg_color(&buttonStyle, LV_STATE_DEFAULT, LV_COLOR_BLACK);
  
lv_obj_t *btn = lv_btn_create(cont, NULL);
lv_obj_add_style(btn, LV_BTN_PART_MAIN, &buttonStyle); // comment this line out and it works
lv_obj_set_size(btn, 64, 64);
```

When not assigning the style (`buttonStyle`) to the button it works without a problem.

**Comment by embeddedt** [comment]
Is `buttonStyle` a global variable? If it's just inside your function, you probably need to make it `static`.

**Comment by T94T** [comment]
Thank you so much, you saved my day! Declaring the style as `static` works.
