### ISSUE TITLE
[Feature Request] Right align label

### ISSUE THREAD

**Issue by upbeat27** [lvgl/lvgl#266]
Right now a label can be left or center aligned.
A right align option should exist, I would think.

**Comment by kisvegabor** [comment]
Hi,

Yes, it absolutely should exist.
v5.2 will support Right-to-left writing as well. With this I will implement this as well!

**Comment by kisvegabor** [comment]
I added "Right aligned text" support to `dev-5.2`

It works like this:
```c
    lv_obj_t * label = lv_label_create(lv_scr_act(), NULL);
    lv_label_set_text(label, "Very long line\n"
                             "a\n"
                             "two words");
    lv_label_set_align(label, LV_LABEL_ALIGN_RIGHT);
``` 

![image](https://user-images.githubusercontent.com/7599318/43227349-c7037988-905e-11e8-881c-693962fe5746.png)

A quick test would be welcome :)

I mentioned Right to left support as well, but release v5.2 quicker I delayed this feature. If somebody needs Right-to-left support, please tell it here: https://github.com/littlevgl/lvgl/issues/46

**Comment by kisvegabor** [comment]
To see the progress of `dev-5.2` I close this issue. 
If you have any remarks don't hesitate to reopen it! :)

**Comment by mbratch** [comment]
I take it `lv_label_set_align` was never released? At least the current LVGL documentation doesn't mention it.

**Comment by AndreCostaaa** [comment]
Hi @mbratch 

You're looking for lv_obj_set_style_text_align() or lv_style_set_text_align()

Docs here https://docs.lvgl.io/master/widgets/label.html#text-alignment
