### ISSUE TITLE
arc obj:color display error when color opa was used

### ISSUE THREAD

**Issue by guoweilkd** [lvgl/lvgl#2668]
### Describe the bug

arc color display error when arc color opa was used: like this:
```c
    lv_obj_t * arc = lv_arc_create(lv_scr_act());
    lv_obj_remove_style(arc, NULL, LV_PART_KNOB);
    lv_obj_set_style_arc_color(arc, lv_palette_main(LV_PALETTE_RED), LV_PART_MAIN);
    lv_obj_set_style_arc_opa(arc, LV_OPA_10, LV_PART_MAIN);
    lv_obj_set_style_arc_color(arc, lv_palette_main(LV_PALETTE_BLUE), LV_PART_INDICATOR);
    lv_obj_set_style_arc_opa(arc, LV_OPA_50, LV_PART_INDICATOR);

    lv_obj_set_size(arc, 150, 150);
    lv_arc_set_rotation(arc, 135);
    lv_arc_set_bg_angles(arc, 0, 270);
    lv_arc_set_value(arc, 40);
    lv_obj_center(arc);
```
The result:
![image](https://user-images.githubusercontent.com/35251456/137432588-fe7188a5-49a8-4264-a318-7262f3f544fc.png)

The reason for this is the overlapping blending that occurs when drawing rounded corners. I made some fixes, see #2669 , But the results are still not good. The result after repair is as follows:
![image](https://user-images.githubusercontent.com/35251456/137433293-1f0ac98e-741e-42a6-8ade-ac54063baa35.png)

There will still be color errors at both ends of the angle mask.I found some clues in [lv_draw_mask_angle](https://github.com/lvgl/lvgl/blob/master/src/draw/lv_draw_mask.c#L893~#L990).The point (abs_y == p->cfg.vertex_p.y) may or may not contains  to the mask, We should make it consistent, either include it or not. besides, we need to be able to control whether edge points are included in the mask.

**Comment by kisvegabor** [comment]
Thanks, let's continue in the PR.
