### ISSUE TITLE
There is a problem getting the size of the widget

### ISSUE THREAD

**Issue by alec-2018** [lvgl/lvgl#2670]
### Perform all steps below and tick them with [x]
- [x] Check the related part of the [Documentation](https://docs.lvgl.io/)
- [x] Update lvgl to the latest version
- [x] Reproduce the issue in a [Simulator](https://docs.lvgl.io/latest/en/html/get-started/pc-simulator.html)

### Describe the bug

lv_obj_set_width/heighwt, obj->coords is not assigned, when using lv_obj_get_coords/width/heigh to read the size, the value read is obj->coords, which leads to a read result of 0, so similar to the lv_label_get_letter_pos() function result error
### To Reproduce

This problem can be reproduced using the simulator
```c
    lv_point_t pos;
    int pos_char = 0, i = 0;

    lv_obj_t* obj = lv_obj_create(lv_scr_act());
    lv_obj_set_size(obj, 100, 100);
    lv_label_t* label_text;
    lv_obj_t * label1 = lv_label_create(obj);
    lv_label_set_long_mode(label1, LV_LABEL_LONG_WRAP);
    label_text = (lv_label_t*)label1;
    lv_label_set_text(label1, "Re-color words of a l1ew222222222222222222w");
    lv_obj_set_width(label1, 50);
    lv_obj_set_height(label1, LV_SIZE_CONTENT);
    lv_obj_set_style_text_align(label1, LV_TEXT_ALIGN_LEFT, 0);
    lv_obj_align(label1, LV_ALIGN_TOP_MID, 0, 0);
    printf("lv_obj_get_width(label1) = %d.\n", lv_obj_get_width(label1));
   
    while (label_text->text[i] != '2') {
        _lv_txt_encoded_next(label_text->text, &i);
        pos_char++;
    }
    lv_label_get_letter_pos(label1, pos_char, &pos);
    printf("------------->%d, %u, %u.\n", pos_char, pos.x, pos.y);
```
### Expected behavior

![5C1AFBE1-240B-4426-843B-FD42A247D562](https://user-images.githubusercontent.com/40708750/137439996-ef2b559a-e181-493d-82b6-0f44a22efc35.png)

### Screenshots or video

Wrong result
![87695A5D-6B48-4aba-8064-0492093A1B46](https://user-images.githubusercontent.com/40708750/137439791-5cf7991b-dc84-401b-bc02-ce0b18b821fe.png)

**Comment by kisvegabor** [comment]
See here: https://docs.lvgl.io/master/overview/coords.html#postponed-coordinate-calculation
