### ISSUE TITLE
`grow_sum` is written to in find_track_end but never read from

### ISSUE THREAD

**Issue by embeddedt** [lvgl/lvgl#2672]
This was caught when I tried compiling with Emscripten 2.0.31.

Is this a typo or is the variable really not needed?

https://github.com/lvgl/lvgl/blob/6d15cb9698508fc3ae171213b865c71c0f4b2ee2/src/extra/layouts/flex/lv_flex.c#L330

**Comment by kisvegabor** [comment]
I also found it while fighting with Emscripten 2.0.31 :smile: 

It's not needed, I just haven't fixed it yet.

**Comment by kisvegabor** [comment]
Fixed.
