### ISSUE TITLE
Need Kconfig entry for LV_FS_POSIX_PATH

### ISSUE THREAD

**Issue by steprun** [lvgl/lvgl#2678]
### Introduce the problem
Need Kconfig entry for LV_FS_POSIX_PATH

### Examples and cases
We couldn't configure this define but in lv_conf.h

### Suggested solution
Add string Kconfig entry for LV_FS_POSIX_PATH

**Comment by xiaoxiang781216** [comment]
@steprun do you see this patch:
https://github.com/lvgl/lvgl/pull/2662/files#diff-7c9693e9c5e61a1d80e09769377d47bb415ec39ca5aeaa85d13581b0105d6359R775-R780
