### ISSUE TITLE
Use Mutex

### ISSUE THREAD

**Issue by Moo2017** [lvgl/lvgl#268]
Hi
I created a linked list for messages information, I'd like to show text from a static array in the created labels for the buttons . I have a receive task which receive messages from server, receive task may delete the oldest message from the liked list if max message number exceed , so I have to add a mutex since both tasks are using linked list at the same time and they might try to change that but I don't know how this can be added in littlevgl since as soon as keypad is pressed , prev or next object will be shown automatically and cursor will move to that button ( I am not sure even if object is not in the visible area this causes a problem or not?) , any idea bout this? can I handle this situation?

**Comment by MiSimon** [comment]
Hi,
can you move the list operations from the receive task into its own lvgl task (create it with `lv_task_create`)?
Since the input handling is also a lvgl task, there should be no need for a mutex, since the two task will not be called in parallel.

**Comment by kisvegabor** [comment]
I agree with @MiSimon 
I also think that it's the most simple and robust way!

**Comment by Moo2017** [comment]
Thanks for the comments,  I'll try it.

**Comment by Moo2017** [comment]
Another question, is there any way to know that when lvgl is idle? I mean my_disp_flush is done completely?

**Comment by kisvegabor** [comment]
Please give us feedback about the previous topic. 

Now you can use the `lv_task_get_idle` to see how much percentage of time is spent in `lv_task_handler`.

However it would be possible to add function which can tell when will be the next task called.

**Comment by Moo2017** [comment]
Thanks, About the previous topic, I decided not to use static array for now since I can not move list operations to lvgl task.

**Comment by kisvegabor** [comment]
I see, thank you.

And have you found a solution?

**Comment by kisvegabor** [comment]
As the issue is solved I close it.
If you have some time, please let us know how did you solve it.
