### ISSUE TITLE
Text not centered in Roller

### ISSUE THREAD

**Issue by StephanSy** [lvgl/lvgl#269]
Hi!
I noticed that the text label of roller object type (and ddlist, too) is not really centered. It seems there is some fixed offset on the left. You can see this in the 2nd example on the webpage, too. When the text is longer, the offset does not stand out, but when there is only one letter in each option, it looks ugly.

Is this offset intentional and is there anything one can do to remove the offset?

Thanks!

**Comment by StephanSy** [comment]
Sorry: the offset is on the right side, of course.

**Comment by kisvegabor** [comment]
Hi,

Thank you for pointing this out! 
I fixed in the `beta`. Can you test it?

**Comment by StephanSy** [comment]
Hi! 
Looks nice. Thanks!
BR,
Stephan
