### ISSUE TITLE
#define LV_COLOR_SCREEN_TRANSP    1 ,Without adding any targets, the screen is always white, not transparent.

### ISSUE THREAD

**Issue by liuy-Kuder** [lvgl/lvgl#2696]

**Comment by kisvegabor** [comment]
You need to set `lv_obj_set_style_bg_opa(scr, 0, 0)`.

---

We use GitHub Issues for development-related discussions.

Please ask your question in the [Forum](https://forum.lvgl.io) to make it visible for a larger community. You can simply log in with your GitHub account.
