### ISSUE TITLE
lv_ta with lv_ta_set_one_line and FONT_ANTIALIAS sets height to full font size

### ISSUE THREAD

**Issue by scopa90** [lvgl/lvgl#27]
Don't know if I'm doing something wrong but switching FONT_ANTIALIAS and doubling the font size means that the default height of an lv_ta doubles as well, despite the text displaying at half size.  Is there a way around this?

**Comment by kisvegabor** [comment]
Hi,
it was bug. I fixed it the `beta` branch.
Thank you for reporting these issues. You help a lot!

**Comment by scopa90** [comment]
Fixed - thanks.
Thank YOU for creating littlevgl!
