### ISSUE TITLE
JavaScript simulator resolution

### ISSUE THREAD

**Issue by leidto** [lvgl/lvgl#2710]
### Introduce the problem
The simulator is running inside an iframe. We'd like to change the resolution of the simulator on the web application. (I've changed the canvas and the iframe size already, but the canvas size always resets to 420x320.)

How can we do that?  Is there any simple method?

**Comment by embeddedt** [comment]
It can be done without any code changes by replacing `import display_driver` in the Python code with this more verbose version:

```py
# Initialize 

from display_driver_utils import driver
drv = driver(width=800,height=600)
```

As long as the Display pane is at least 800x600, the canvas will be rendered at exactly that size without any downscaling.

([Live example](https://sim.lvgl.io/v8.1/micropython/ports/javascript/index.html?script_direct=7f7570fd338acb0b3b23b912d9c4f53cbe21c21a))
