### ISSUE TITLE
lv_label underline with freetype show bad underlien thickness

### ISSUE THREAD

**Issue by seasonyuu** [lvgl/lvgl#2711]
### Perform all steps below and tick them with [x]
- [x] Check the related part of the [Documentation](https://docs.lvgl.io/)
- [x] Update lvgl to the latest version
- [x] Reproduce the issue in a [Simulator](https://docs.lvgl.io/latest/en/html/get-started/pc-simulator.html)

### Describe the bug

That is a bug which lv_liv_freetype repo had fixed. please merge to src/extra/libs/freetype

https://github.com/lvgl/lv_lib_freetype/commit/aa85d97474eaecdc6db88fd322af8657a760594d

**Comment by kisvegabor** [comment]
Thanks, fixed.
