### ISSUE TITLE
An abnormal drawing appears in the rounded rectangle created.

### ISSUE THREAD

**Issue by qinshijing** [lvgl/lvgl#2717]
### Perform all steps below and tick them with [x]
- [x] Check the related part of the [Documentation](https://docs.lvgl.io/)
- [x] Update lvgl to the latest version
- [x] Reproduce the issue in a [Simulator](https://docs.lvgl.io/latest/en/html/get-started/pc-simulator.html)

### Describe the bug

An abnormal drawing appears in the rounded rectangle created.
### To Reproduce

static void test(void)
{
    lv_obj_set_style_bg_color(lv_scr_act(), lv_color_black(), 0);
    lv_obj_t* line = lv_obj_create(lv_scr_act());
    // lv_obj_set_size(line, 100, 32); // normal
    lv_obj_set_size(line, 100, 31); // unnormal
    lv_obj_set_style_bg_color(line, lv_color_white(), 0);
    lv_obj_set_style_radius(line, LV_RADIUS_CIRCLE, 0);
    lv_obj_set_style_bg_opa(line, LV_OPA_30, 0);
    lv_obj_set_style_border_width(line, 0, 0);
    lv_obj_center(line);
}
### Screenshots or video

![image](https://user-images.githubusercontent.com/51692568/138391442-53c86188-a8da-4555-ab96-61cddb704f7a.png)

**Comment by kisvegabor** [comment]
It's the scrollbar :slightly_smiling_face: 

If the height is smaller then `pad_top + pad_bottom` a scrollbar will appear. 

You can add this to make the widget non scrollable:
```c
       lv_obj_clear_flag(obj, LV_OBJ_FLAG_SCROLLABLE);
```

Or this to hide the scrollbar:
```c
       lv_obj_set_scrollbar_mode(obj, LV_SCROLLBAR_MODE_OFF);
```

**Comment by qinshijing** [comment]
Oh, I'm so sorry, I turned this low-level mistake.
