### ISSUE TITLE
lv_example_dropdown_3:  img_caret_down image not displayed correctly

### ISSUE THREAD

**Issue by higaski** [lvgl/lvgl#2728]
### Describe the bug
The img_caret_down image used in the lv_example_dropdown_3 isn't shown correctly.

### To Reproduce
Run lv_example_dropdown_3.

### Expected behavior
The expected  behavior can be seen in the [dropdown example](https://docs.lvgl.io/master/examples.html#dropdown).

### Screenshots or video
![Screenshot_MSlvgl_1](https://user-images.githubusercontent.com/13762516/138665588-460f4e8c-e4cb-409d-af7e-935d625c92d3.png)

**Comment by kisvegabor** [comment]
It work well for me locally and looks good in the [online demo](https://docs.lvgl.io/master/examples.html#menu) too.

Is there any special in your setup?

**Comment by higaski** [comment]
I don't think so. I've just copied the config files over from [lv_sim_vscode_sdl](https://github.com/lvgl/lv_sim_vscode_sdl) and still get this error.

Ok weird, this seems to have something todo with changes to my build system. I've thought about this before, but there is an object file for img_caret_down in my build directory so I dismissed this at first...
