### ISSUE TITLE
Why can't the position of the first control be modified when the parent object is cont?

### ISSUE THREAD

**Issue by as564335sa** [lvgl/lvgl#279]
Why can't the position of the first control be modified when the parent object is cont?

in the test:
lv_obj_t * cont2 = lv_cont_create(lv_scr_act(), cont1);
    lv_cont_set_fit(cont2, true, true);

    lv_obj_t * obj2_1 = lv_label_create(cont2, NULL);
    lv_obj_set_pos(obj2_1, 100, 30);
    lv_label_set_text(obj2_1, "Short");

    lv_obj_t * obj2_2 = lv_label_create(cont2, NULL);
    lv_label_set_text(obj2_2, "A longer text");
    lv_obj_set_pos(obj2_2, 180, 30);

The position of “Short”does not change?

**Comment by kisvegabor** [comment]
Hi,

I updated the documentation of the container to explain it. See the "Notes" section here: https://littlevgl.com/object-types/container-lv_cont
