### ISSUE TITLE
How to change the font of a single ddlist object?

### ISSUE THREAD

**Issue by StephanSy** [lvgl/lvgl#280]
Hi!
I would like to change the font size of individual objects (not the default font size).
I tried the code below to change from default font size 20 to 10, but it seems I also need to change the spacing somehow.
Can you please help me?
BR, 
Stephan

```c
lv_obj_t * ddlist = lv_ddlist_create(lv_scr_act(), NULL);
lv_ddlist_set_options(ddlist, "Low\nMedium\nHigh");
lv_obj_set_pos(ddlist, LV_DPI / 4, LV_DPI / 4);
lv_group_add_obj(g, ddlist);                    /*Add the object to the group*/

lv_style_copy( &bg_style, lv_ddlist_get_style( ddlist, LV_DDLIST_STYLE_BG ));
lv_style_copy( &sel_style, lv_ddlist_get_style( ddlist, LV_DDLIST_STYLE_SEL ));

bg_style.text.font = &lv_font_dejavu_10;
sel_style.text.font = &lv_font_dejavu_10;

lv_ddlist_set_style( ddlist, LV_DDLIST_STYLE_BG, &bg_style );
 lv_ddlist_set_style( ddlist, LV_DDLIST_STYLE_SEL, &sel_style );
```

Before:

![image](https://user-images.githubusercontent.com/40055012/41410212-0647638a-6fd9-11e8-990c-6fb95d992fb3.png)

After:

![image](https://user-images.githubusercontent.com/40055012/41410129-b5b853ac-6fd8-11e8-98dd-baf3d322bcd5.png)

**Comment by kisvegabor** [comment]
Hi Stephan,

First of all then you for persistent work on reporting these issues!

Your code is fine it was tricky bug in the library. When the ddlist came to focus it started an "open" animation which modified its height. Meanwhile the style change also changed the height but animation overwritten it.

I fixed it in `beta`.

**Comment by StephanSy** [comment]
Thank you! I have tested it and it works now also for me.
BR
Stephan
