### ISSUE TITLE
Strange Colors on HX8357D

### ISSUE THREAD

**Issue by AGlass0fMilk** [lvgl/lvgl#285]
Hi,

I'm working on porting LVGL over to ARM mbed-os and I'm working on the STM32F407-DISC1 board. I am using an Adafruit 3.5" TFT LCD breakout with an HX8357D driver IC.

I have gotten to the point where the display has the right shapes being printed out, but I cannot get the colors to be correct. I have tried configuring the display driver to accept RGB(5/6/5) and BGR(5/6/5) as well as inverting the colors to no avail. It still looks very... messed up (see picture below).

Any idea on what I'm doing wrong? Any hints would be great. Looking forward to working with lvgl :)

Thanks!

![img_1144](https://user-images.githubusercontent.com/350500/41819774-37f21264-7794-11e8-8e0b-9ff01ee0b3e0.JPG)

**Comment by AGlass0fMilk** [comment]
I think I fixed it by making sure the color was written out in the proper format (RGB 5/6/5):

```
uint8_t pix_color = 0;
pix_color = (color_p->red << 3) | ((color_p->green & 0x38) >> 3);
write_byte_to_display(pix_color);
pix_color = ((color_p->green & 0x7) << 5) | (color_p->blue);
write_byte_to_display(pix_color);
```

You can find the port I'm working on over at my lvgl fork:
https://github.com/AGlass0fMilk/lvgl

**Comment by kisvegabor** [comment]
Great!

Thank you for sharing you code!

I would like add more blog post to littelvgl.com. If you are interested in writing about your porting, please write me to: kisevegabor@gmail.com

**Comment by tomtristan** [comment]
It seems that I've the same issue, colors distorted like the picture above. Where exactly did you put these code lines to fix the problem?

**Comment by embeddedt** [comment]
@tomtristan Are LittlevGL and the display configured to accept the same color depth?

**Comment by kisvegabor** [comment]
You can enable `LV_COLOR_16_SWAP` in lv_conf.h. It internally swaps the 2 bytes

**Comment by tomtristan** [comment]
![53112146_257114841883243_7465089868427689984_n](https://user-images.githubusercontent.com/47831098/53681416-14c94e00-3cf2-11e9-9010-0471fd6ecf69.jpg)
![52963068_336853233704283_4000880731940192256_n](https://user-images.githubusercontent.com/47831098/53681417-15fa7b00-3cf2-11e9-8322-e2454f779dfe.jpg)
![53067835_2253888514663729_6491022432797720576_n](https://user-images.githubusercontent.com/47831098/53681418-16931180-3cf2-11e9-90eb-85f40d80a37d.jpg)
![53034407_990516151336811_7027667670036119552_n](https://user-images.githubusercontent.com/47831098/53681420-172ba800-3cf2-11e9-9993-a72e51ba039a.jpg)

I attached several picture of my progress so far - demo seems to be working, but there are issues with colors overall and pixels around the letters.
The LTDC is initialized for ARGB8888, and the lv_conf color depth is 32(when changed to 16 everything goes downhill, very distorted everything), so the configure should be fine. To my eye it seems that some color pixels are swapped in the STM32F746 disco kit ported no os atollic and has an issue somewhere in the tft.c file. There exists a possibility that there is a bad solder on a certain pin, but the second revision of the pcb is arriving soon, if the problem exists after soldering and testing it, it most probably is software related.

**Comment by kisvegabor** [comment]
@tomtristan We have just launched a [Forum](https://forum.littlevgl.com). This topic is more like a question than development so please open a topic on the forum for it.
