### ISSUE TITLE
image converter generates wrong type of struct

### ISSUE THREAD

**Issue by zbigos** [lvgl/lvgl#288]
When converting a .bmp file, the converter gives a struct of lv_img_t type. That type is not defined and produces a compilation error while compiling the code 

I am running version 5.0.2 of library and current version of converter

**Comment by kisvegabor** [comment]
Hi,

Please copy here the compiler log.

Oh, I forget, the image's structure was updated in v5.1. So please update lvgl to the latest version.

**Comment by hesamsadiri** [comment]
There is similar problem. lv_img_t is not defined and produces a compilation error while compiling the code. I am compiling the code in keil v5

I am running version 5.3 of library.

**Comment by embeddedt** [comment]
@hesamsadiri Some type names were changed during the 5.x release series. If your image files are old you might need to regenerate them. I think `lv_img_t` may have been renamed to `lv_img_dsc_t`.

@kisvegabor This is unrelated to the issue, but for some reason GitHub thinks you commented in the future :laughing: :

![Capture](https://user-images.githubusercontent.com/42941056/57383090-30caef00-717c-11e9-8e4c-469fec17837b.PNG)
