### ISSUE TITLE
Make `lv_fonts` folder sibling of other `lv_*` folders, not child of `lv_misc`

### ISSUE THREAD

**Issue by hydra** [lvgl/lvgl#293]
Reminder issue as per discussion here:

https://github.com/littlevgl/lvgl/issues/291#issuecomment-401374319

Additionally, the relocation can also simplify Makefile and increase compilation speed when default fonts are not used along with PR #292 by excluding the files from the list of files to be built.

**Comment by kisvegabor** [comment]
I moved `lv_fonts` next to `lv_misc` .
Thank you for the suggestion!
