### ISSUE TITLE
Something wrong with Online Image to C Array Converter?

### ISSUE THREAD

**Issue by ChazJin** [lvgl/lvgl#295]
Hi gabor,

When using Online Image to C Array Converter to convert a 1024*600 24-bit jpg image  which is shown in the attach file to C array, the last part of the data is garbled character. 

Thanks!
![test1024_600](https://user-images.githubusercontent.com/37656088/42162521-88520e28-7e31-11e8-851d-528f58ca7113.jpg)

![Uploading FaultConvertResult.jpg…]()

**Comment by ChazJin** [comment]
In other words, is there any restrictions while using Online Image to C Array Converter? For example, the size of the picture can't exceed a certain value?

**Comment by kisvegabor** [comment]
Hi,

I tested it the PC simulator and it worked for me.
I attached a screenshot when using the image and a "C" file which is the converted image. The "C" file different for you? Or does it work with the attached C file?

[img_conv_test.zip](https://github.com/littlevgl/lvgl/files/2156082/img_conv_test.zip)

**Comment by ChazJin** [comment]
Thanks for your response. And I have tested this two pictures using Online Image to C Array Converter, the results show that the parsed data of "img_conv_test.png" is incorrect which is the same as I tested the 1024*600 24-bit jpg image before, while the picture "test.png" of a smaller size is converted correctly. 

I thought there might be related to the size of the converted file. The size of "img_conv_test.png" after the conversion reaches 44.87MB. So would you test "img_conv_test.png" with the Online way to see if we have the same situation when you are free? Thanks a lot!

![img_conv_test_result](https://user-images.githubusercontent.com/37656088/42194049-9e84d81a-7ea4-11e8-95be-e384253a2829.jpg)

**Comment by ChazJin** [comment]
I seem to have found the reason which is related to the network. The size of the converted C array by Online method is about 44MB, while the size of the file I download is smaller than the 44MB even I have tried many times, so that the last part of the .c file is garbled character. Um...I have no other way of doing this for the time being. But thank you all the same!

**Comment by kisvegabor** [comment]
It's very strange.
On my server, I increased the memory size dedicated to PHP scripts. Hopefully, it will help.

And the converter scrips are available here too: https://github.com/littlevgl/lv_utils
You can try to run the scrips offline in a terminal.

**Comment by kisvegabor** [comment]
I new image converter is released. Hope your issue is solved in it.

If don't or you find other issues just reopen this issue.
