### ISSUE TITLE
Missing header file img_conf.h

### ISSUE THREAD

**Issue by ajaybhargav** [lvgl/lvgl#3]
img_add.c reporting error of a missing file
`#include "img_conf.h"`

I think there is no template file img_conf_tmpl.h which can tell what goes in img_conf.h

**Comment by kisvegabor** [comment]
Thanks for the report!
In lv_conf.h set LV_APP_USE_INTERNAL_ICONS to 0. Dose it help?

**Comment by kisvegabor** [comment]
True. Please add an empty img_conf.h to the root folder of the project. I will add template in the next release.

**Comment by ajaybhargav** [comment]
I already did that. Thanks!
The sample project is not updated with the current lvgl. There are some missing defines e.g. "LV_DISPI_LONG_PRESS_REP_TIME"

**Comment by kisvegabor** [comment]
In version 2.1
img_conf_templ.h added in lvgl.
lv_conf_temp.h is updated
