### ISSUE TITLE
Clicking object with mouse does not focus it

### ISSUE THREAD

**Issue by aenchevich** [lvgl/lvgl#301]
At present clicking an obj (with the mouse) activates it, for example it changes the state of a checkbox, but it does not focus it. Only the Tab and Shift-Tab move the focus (the yellow border around an object). 

This does not seem correct to me, because the logic should IMO be identical:

 With kbd:
 - tab until you arrive at the desired object --> Result: The object is now selected.
 - Trigger the object action (ENTER) --> Result: object's actoin f-n is called.

With mouse:
 - click object (which equates to "Select"+"Action-trigger" the object) --> Result:  object is selected and then immediately activated.

**Comment by kisvegabor** [comment]
Hi,

It sounds reasonable as an option. For example, the `lv_group` can have a property to behave like this. What do you think?

**Comment by aenchevich** [comment]
My thinking was that if an object's is activated (by the user) then it is the currently active (selected) object. I understand that other objects in the GUI can be activated by other events (for example an MP3 player can have an equalizer LED array which will change as music is being played but this will not make it the active/selected GUI component). Is this correct? 

If yes, then, IMO, if the theme/style/etc is using some way of showing a selection around the object (e.g. the yellow border in the 10_keyboard tutorial) then it does not matter whether the object became active via the keyboard or via the mouse.

As far as your suggestion about using lv_group I did not exactly understand whether you are saying: "the proper way to do it is in lv_group" or "let's have an option in lv_group which governs how the selection indicator works (e.g. only keyboard, only mouse, both or none)"?

**Comment by kisvegabor** [comment]
Speaking about touchpad/mouse control there is no "active" object. If an object has a "click" event it will be called if it's clicked. You can adjust a slider, change a checkbox etc.

However, speaking about keyboard control the library need to know where (to which object) to "send" button presses. So it this case need to have an active (in other words "focused") objects. 

I meant "let's have an option in lv_group which governs how the selection indicator works (e.g. only keyboard, only mouse, both or none)". So it's a good feature idea to add a flag to the groups, which makes the elements object focused if it is clicked by mouse/touchpad!

**Comment by aenchevich** [comment]
Yes, having such an option in lv_group is definitely better than not having it!  :)

I still think it is confusing if focus follows only keyboard and not mouse so I will make one last effort to prove my case  :)

I am attaching a simple menu demo (based on the FIle...WiFi list from demo.c): 

[issue_301_focus_with_mouse.tar.gz](https://github.com/littlevgl/lvgl/files/2187543/issue_301_focus_with_mouse.tar.gz)

If you run it (press ENTER to show the menu and ESC to hide it) you will see that you can have this situation...
![301-focus-with-mouse-01](https://user-images.githubusercontent.com/12744872/42618977-53672d66-85bf-11e8-854d-ba8aea455ae1.png)

... where one item ('New') remains selected while another one ('Edit') is being clicked. And worse - after you release the click,  'Edit does not become the selected item. You can actually alternate pressing ENTER and clicking the Edit and the menu will activate the actions for New / Save respectively without changing the focused item. 

If this is the effect you want in lvgl - then ok, no problem, it's working like you want it..  :) 
I personally can not think of a real-life software example which behaves like this...?  For example if you open the file menu in your browser you can see that:
  - as soon as you enter a menu with the mouse the focus follows the mouse;
  - as soon as you move the keyboard the focus follows the keyboard.
Nothing says of course that lvgl can not be different... and there may be reasons why you want it to be different.. but if there aren't any such reasons then perhaps following some standard GUI behaviour would be the best course of action?

**Comment by kisvegabor** [comment]
I'm totally convinced now. The "For example if you open the file menu in your browser..." part lightened it to me.

My initial thought was nobody will use LittelvGL with mouse and keyboard at the same time. But why not?! It's really more realistic. And if only a keyboard or a mouse/touchpad is used then they won't bother each other.

I still feel important to keep both the options but I will make you suggested one as default!

Thank you!

**Comment by kisvegabor** [comment]
I added the first attempt of this feature to `dev-5.2`. 

I tested it in `lv_test_group_1()`. It seems to it works as expected. Can you test it?

**Comment by aenchevich** [comment]
wow... that was fast!  :) Thanks! I will do my best to test it this weekend!

**Comment by kisvegabor** [comment]
Great! Thanks! :)

**Comment by aenchevich** [comment]
I tested your feature on dev-5.2. As far as I can see it works exactly as expected! Sweeeeet! Thanks :)
- - - 
There are lot's of compile warnings and one compile error on this branch, mostly related to missing defines... I don't know if you also see them in your build? And whether the warnings on this branch are expected? I could provide more info if you're interested?

In particular the error I got was:

```
In file included from lvgl/lv_core/lv_style.h:20:0,
                 from lvgl/lv_core/lv_obj.h:24,
                 from lvgl/lvgl.h:22,
                 from main.c:13:
lvgl/lv_core/../lv_misc/lv_anim.h:36:1: error: expected ‘=’, ‘,’, ‘;’, ‘asm’ or ‘__attribute__’ before ‘struct’
 struct _lv_anim_t;
```
What is really happening here is that LV_FONT_CUSTOM_DECLARE, which is suggested in lv_conf_tmpl.h as:

```
/* Optionally declare your custom fonts here.
 * You can use these fonts as defult font too
 * and they will be avialale globally. E.g.
 * #define LV_FONT_CUSTOM_DECLARE LV_FONT_DECLARE(my_font_1) \
 *						          LV_FONT_DECLARE(my_font_2) \
 */
#define LV_FONT_CUSTOM_DECLARE
```

.. should really be:
#define LV_FONT_CUSTOM_DECLARE ;

... because otherwise we have a statement with a missing ';' in lv_conf.h which manifests itself as an error on lv_anim.h  :)

And like I said - if you don't see the warnings and would like to fix them I can provide more info on that too.

Aside from that, like I said - based on my little test the focus following the mouse events works great, thank you!

**Comment by aenchevich** [comment]
Oh, I see now that the  LV_FONT_CUSTOM_DECLARE problem is fixed on branch 'beta', commit 4773dfd53f5847885220ec96c085a12aaa719062 ...

**Comment by kisvegabor** [comment]
Great! :+1: 

Do you still see warnings?

**Comment by kisvegabor** [comment]
According to your test, this feature seems working thus I close this issue.

Thank you very much for the good idea :)
