### ISSUE TITLE
teensy 3.2 with littlevgl (Arduino IDE), setup problem?

### ISSUE THREAD

**Issue by epikao** [lvgl/lvgl#304]
Hello, I'm trying to compile the lvgl_test.ino from littlevgl arduino library and program it to my teensy 3.2.

Unfortunately I have follow first errors:
![image](https://user-images.githubusercontent.com/26655950/42572685-4c75f32a-851a-11e8-9e15-3f64220d82c7.png)
after change  #include <lvgl.h> to #include "lvgl.h" I have follow errors:
![image](https://user-images.githubusercontent.com/26655950/42572661-3a700094-851a-11e8-9cfd-74acea96ed31.png)

**BTW:** 
Is it correct that in the "my_disp_flush" function, I have to write the x/y and color data directly to the Interface of my Display (via SPI) ? So for example follow code:

```
	writecommand(0x2A); //x pixel-position 
	writedata(x); //start-position
	writedata(x); //start-position

	writecommand(0x2B); //y pixel-positon 
	writedata(y); //start-position
	writedata(y); //start-position
  
	writedata(color-data); //
	writedata(color-data);  //
```
I think the "my_disp_flush" is not a function which is called for every pixel? 
How is the structure of the "color_p" function/variable?
Where do I place the whole initialization of the Display? (in my case "init_ST7789V()"?

**Comment by kisvegabor** [comment]
Hi,

Have you copied the `littlevgl` folder from [here](https://github.com/littlevgl/lv_boards/tree/master/arduino_library) to your library folder?

**disp_flush**
Here you can see how should a `disp_flush` look like: https://github.com/littlevgl/lv_examples/blob/master/lv_tutorial/0_porting/lv_tutorial_porting.c. 
Basically it should copy the `color_p` array to the specified area.

**Comment by epikao** [comment]
> Have you copied the littlevgl folder from here to your library folder?

that's how my folder looks at the moment:

![image](https://user-images.githubusercontent.com/26655950/42593793-c2b632a6-854d-11e8-85ed-5547f0902bd5.png)

> disp_flush
> Here you can see how should a disp_flush look like: https://github.com/littlevgl/lv_examples/blob/master/lv_tutorial/0_porting/lv_tutorial_porting.c.
> Basically it should copy the color_p array to the specified area.

I need only 16bit Color values per Pixel...
so what is the data typ of "color_p", is it already a 16bit, or 24bit Value?
thank you

**Comment by epikao** [comment]
> lv_conf.h should be NEXT TO the src folder (as the example shows in the lv_boards repo)

I already check that, also your tutorial... it's difficult for me to understand.
I have no clue why I always get the error that "lvgl.h" is not found?!!

**Comment by kisvegabor** [comment]
At first time, your error was "No such file or director: ../../lv_conf.h". It was because of the misplaced lv_conf.h.

What is your error message now?

**Comment by epikao** [comment]
> What is your error message now?

![image](https://user-images.githubusercontent.com/26655950/42597859-8a3d6180-855a-11e8-832a-a9e1719fbe55.png)

thank you

**Comment by epikao** [comment]
lvgl.h error only disappears if I change to "lvgl.h" instead of <lvgl.h>.
but than or now I still have follow error:
![image](https://user-images.githubusercontent.com/26655950/42616370-4f43d736-85ae-11e8-8683-c711801ef480.png)

**Comment by epikao** [comment]
so now I solved the problem of lv_conf.h and lvgl.h..., the problem is because I didn't read the "README.md" carefully, sorry to these circumstances :-/ 

![image](https://user-images.githubusercontent.com/26655950/42617007-81f7c14a-85b0-11e8-8235-9962b56c3da2.png)

**Comment by epikao** [comment]
Hello, I cannot find a solution for the errors above :-( ? (undefined reference to 'lv_flush_ready' etc...

**Comment by kisvegabor** [comment]
I put together a working Ardunio project for Teensy 3.2
Here you can see the directory structure.

[Teensy_LittlevGL.zip](https://github.com/littlevgl/lvgl/files/2190245/Teensy_LittlevGL.zip)

**Comment by epikao** [comment]
ok. thank you, now it works :-D
Follow Item in a "README" confused me: 
> 5. In your *main.c*: #include "lvgl/lvgl.h"

**Comment by epikao** [comment]
now I finished the code, but it looks that function "my_disp_flush" is not called:

```
void my_disp_flush(int32_t x1, int32_t y1, int32_t x2, int32_t y2, const lv_color_t *color_array)
{
  /*TODO copy 'color_array' to the specifed coordinats of your disaply.*/
  writecommand(0x2A); //x pixel-position anfahren
  writedata(x1>>8); //start-position
  writedata(x1); //start-position
  writedata(x2>>8); //end-position
  writedata(x2); //end-position

  writecommand(0x2B); //y pixel-positon anfahren
  writedata(y1>>8); //start-position
  writedata(y1); //start-position
  writedata(y2>>8); //end-position
  writedata(y2); //end-position

  writecommand(0x2C); //RAM Daten senden
  digitalWrite(CS0, 0);
  digitalWrite(DC, 1); //Command = 0, Data = 1

  //SPI.transfer(color_array, 0, sizeof(color_array));
  SPI.transfer(0xA0);

  digitalWrite(CS0, 1);
  /*Tell the flushing is ready*/
  lv_flush_ready();
}
```

**Comment by epikao** [comment]
now all is compiled without errors but  function "my_disp_flush" is never called..why that??

```
void my_disp_flush(int32_t x1, int32_t y1, int32_t x2, int32_t y2, const lv_color_t *color_array)
{

  /*TODO copy 'color_array' to the specifed coordinats of your disaply.*/
  writecommand(0x2A); //x pixel-position 
  writedata(x1>>8); //start-position
  writedata(x1); //start-position
  writedata(x2>>8); //end-position
  writedata(x2); //end-position

  writecommand(0x2B); //y pixel-positon 
  writedata(y1>>8); //start-position
  writedata(y1); //start-position
  writedata(y2>>8); //end-position
  writedata(y2); //end-position

  writecommand(0x2C); //RAM Data
  digitalWrite(CS0, 0);
  digitalWrite(DC, 1); //Command = 0, Data = 1

  //SPI.transfer(color_array, 0, sizeof(color_array));
  SPI.transfer(0xA0);

  digitalWrite(CS0, 1);
  /*Tell the flushing is ready*/
  lv_flush_ready();
}
```
```

void loop() {
  // put your main code here, to run repeatedly:

  lv_task_handler();
  /*If 'lv_tick_inc(5)' is not called in a Timer then call it here*/
  lv_tick_inc(5);
  delay(5);             /*Wait a little*/
}
```

**Comment by kisvegabor** [comment]
Glad to hear it compiles!

Are you sure it's not called? Can you verify it by printing to the console something in `my_disp_flush`?

**Comment by epikao** [comment]
I just verified: The problem is that the program crashs :-( 
If I do the "lv_tick_inc(5)" without timer (in the loop) and add a delay of about 1000ms the program calls the loop aprox 10 times and than it crashs.
If I remove the 1000ms nothing more works.
The same if I do the "lv_tick_inc(5)" with Timer...

If I remove the "lv_tick_inc(5)" handling, the program does not crash anymore. What's wrong?

According your porting Infos "lv handler, and tick" should called every 1...5ms, but is that not very stressful for the CPU?

thank you.

**Comment by kisvegabor** [comment]
It's not so stressful because it calls tasks only if their period time is over.

Please attach you `ino` file to check what might be wrong.

**Comment by epikao** [comment]
thank you for your support, see attached file:
[lvgl_test - Kopie.txt](https://github.com/littlevgl/lvgl/files/2200492/lvgl_test.-.Kopie.txt)

see line 126, if I activate it, serial monitor(debug) shows follow:
setup
loop
.. nothing more (crashed)

if line 126 deactivated:
setup
loop
loop
loop
loop etc. (every 500ms)

**Comment by kisvegabor** [comment]
At first look, it seems correct. 
Please, post the summary of the crash issue to this thread: https://github.com/littlevgl/lvgl/issues/189
Here @rbultman also had a crash issue using Arduino. Join our forces to figure out what's going on :)

As the original question (set up)  is solved I close this issue. Let's continue in the other topic.
