### ISSUE TITLE
Ink effect added to buttons (give feedback)

### ISSUE THREAD

**Issue by kisvegabor** [lvgl/lvgl#305]
Hi,

I added an ink effect to buttons. It similar to the one in Android: when you press a button a circle starts to grow to re-color the button with  pressed color.

In LittlevGL a growing circle will be drawn with `LV_BTN_STYLE_PR` or `LV_BTN_STYLE_TGL_PR`.

Example code:
```c
    lv_obj_t * btn = lv_btn_create(lv_scr_act(), NULL);
    lv_btn_set_ink_fill_time(btn, 300);
    lv_btn_set_ink_wait_time(btn, 100);

    lv_obj_t * label = lv_label_create(btn, NULL);
    lv_label_set_text(label, "Button");
```

[btn_ink.mp4.zip](https://github.com/littlevgl/lvgl/files/2185723/btn_ink.mp4.zip)

This feature is in the `dev-5.2` branch.

Please test it if you are curious, and let me know what do think about it!

**Comment by seyyah** [comment]
This is good idea.

This effect's another name is ripple effect,

- https://codepen.io/madshaakansson/pen/ykode
- https://codepen.io/lehollandaisvolant/pen/dMQXYX
- https://materializecss.com/buttons.html

**Comment by kisvegabor** [comment]
Thanks for the links! 
Especially the first looks awesome. I will check it what it does exactly.

**Comment by kisvegabor** [comment]
I updated the ink effect according to the demos. 
It is already in v5.2.

Thank you!
