### ISSUE TITLE
sparse function of font converter doesn't work nowadays.

### ISSUE THREAD

**Issue by thepolygongo** [lvgl/lvgl#307]
I use this lgvl from two months ago.
but nowadays font converter doesn't work correctly.

I did like this:
![capture](https://user-images.githubusercontent.com/31526289/42634300-6c5a6bc0-8615-11e8-8d6e-98c1c592770f.PNG)
convert result:
![image](https://user-images.githubusercontent.com/31526289/42634374-a49ff810-8615-11e8-8649-74c1fabe3df0.png)

**Comment by kisvegabor** [comment]
Oh my god, I left some test code in it...

Sorry, fixed now.
Please verify it!

**Comment by thepolygongo** [comment]
Thank you, gabor.
It works well.
Regards

**Comment by kisvegabor** [comment]
Great!
Thanks for the feedback!
