### ISSUE TITLE
How can I change default screen direction from horizon to vertical?

### ISSUE THREAD

**Issue by relliktei** [lvgl/lvgl#325]
Does littlevgl support some simple settings to do this?

**Comment by BesitzeRuf** [comment]
Hi **relliktei**, 

did you mean this - #47 ?

**Comment by hydra** [comment]
See #329

**Comment by relliktei** [comment]
@hydra
Your new api is great.
I am expecting for that.

**Comment by kisvegabor** [comment]
Let's continue the discussion in #329
