### ISSUE TITLE
Alignment of lv_mem_alloc() wrong for LV_MEM_CUSTOM==1 on 64bit architectures

### ISSUE THREAD

**Issue by StephanSy** [lvgl/lvgl#330]
Hi!

I had tried arround with `LV_MEM_CUSTOM==1` and using generic malloc/free, and the address sanitizer found the following problem:

At least on 64bit architectures, malloc returns 8 byte aligned memory blocks such that the memory can be cast to any built-in type. But because of the `lv_mem_ent_t` header struct that is allocated inside `lv_mem_alloc()` in front of the block, the return pointer is only 4 byte aligned.

When you compile with the undefined behavior sanitizer `-fsanitize=undefined -lubsan`) and run the simulator on a 64 PC, you will get lots of warnings like this:
``
[...] runtime error: member access within misaligned address 0x60d0000cfd34 for type 'struct lv_style_t', which requires 8 byte alignment
``

I am not sure if this header has any useful purpose. But if you want to have it, you must ensure that the pointer, lv_mem_alloc returns, has the correct alignment depending on the architecture. Otherwise  "defined behavior" can occur...

**Comment by kisvegabor** [comment]
Hi,

Thank you for the report and the great description.

I pushed an update to `dev-5.2` branch.
