### ISSUE TITLE
Allow the screen object to be transparent

### ISSUE THREAD

**Issue by aenchevich** [lvgl/lvgl#331]
[Feature Request] 
This Feature Request is to allow the body.opa field of lv_style to control the screen transparency, such that, if it is set to LV_OPA_TRANSP, and another graphics plane is used for some other video output (e.g. a Digital TV stream) it would be visible in the background.

The "screen" here means the 'def_scr' object created inside `lvgl/lv_core/lv_obj.c : lv_init()` :

```
    /*Create the default screen*/
    lv_ll_init(&scr_ll, sizeof(lv_obj_t));
    def_scr = lv_obj_create(NULL, NULL);
```
 - - - - - -
There are many cases where one would like their base lv_obj (the "screen" object) to be transparent - usually when we want something else visible on the main screen all the time, and the GUI to only be visible from time to time, or when invoked: 
  - a digital camera software;
  - a TV set-top box application;
  - a hardware emulator;
  - some sort of an OSD application.

At present LittlevGL **has** the provisions to set the screen object transparency (via the `lv_style::body::opa` property in the `lv_style_scr` object), but the drawing is not handled properly. The screen shots below show a simple menu and what the screen looks like after it is hidden:

1. Menu drawn, all looks nice:
![transp-correct](https://user-images.githubusercontent.com/12744872/43144011-caba7432-8f64-11e8-8c0d-52ac0f32f0e6.png)

2. if we move the selection with the keyboard and then hide the menu the screen looks like this:
![transp-bad-01](https://user-images.githubusercontent.com/12744872/43144016-cd7ac94c-8f64-11e8-939f-1b0cca51e811.png)

3. If we click some buttons and then hide the menu it looks like this:
![transp-bad-02](https://user-images.githubusercontent.com/12744872/43144018-d15674e4-8f64-11e8-9cbd-3760cdbba474.png)

4. If we don't click anything and immediately hide the menu it looks like this
![transp-bad-03](https://user-images.githubusercontent.com/12744872/43144025-d3fa3596-8f64-11e8-8720-c003c6326843.png)

Note that some areas of the screen which should not have been refreshed (in scr shots 2 and 3) are being draw to... this may be some bug which did not manifest itself on a non-transparent screen?

**Comment by BesitzeRuf** [comment]
Hi aenchevich,

did you try to "wrap" everything" by container/object? (I mean create parent object with WxH of the screen and then, put new object to in, not to the screen). For now I know 4 ways how to hide objects:

1) apply transparent style to objects you want to hide.
2) apply hide attribute
3) move objects outside of the visible area
4) dynamically delete/create objects

How you are hiding the menu?

**Comment by kisvegabor** [comment]
@aenchevich 
I agree, there are use cases where this feature is important. 
This feature requires to define the opacity of every pixel and (right now) only `LV_COLOR DEPTH 
   24` is able to handle this because it really uses ARGB888 colors. So I think the solution could be to set the pixel's alpha to `LV_OPA_TRANSP` by default instead of `LV_OPA_COVER`.

**Comment by kisvegabor** [comment]
Implemented n `dev-5.2`.
To enable this feature set `LV_COLOR_SCREEN_TRANSP     1` in lv_conf.h. After it the screen can have opacity.

**Comment by embeddedt** [comment]
@kisvegabor I tried to make the screen transparent with the following code (from #718):

```c
    lv_obj_t *label = lv_label_create(lv_scr_act(), NULL);

    // Set screen to transp style
    lv_obj_set_style(lv_scr_act(), &lv_style_transp);

    lv_label_set_text(label, "Hello world");
    lv_obj_align(label, NULL, LV_ALIGN_CENTER, 0, 0);
```

`LV_COLOR_SCREEN_TRANSP` is enabled, and I am using 32-bit color. Did I miss something?

**Comment by kisvegabor** [comment]
@embeddedt  I've answered here: https://github.com/littlevgl/lvgl/issues/718#issuecomment-454412300
