### ISSUE TITLE
Has the support for new colour format RGB565A8 been added?

### ISSUE THREAD

**Issue by GorgonMeducer** [lvgl/lvgl#3319]
### Introduce the problem
In previous discussion #3142, we agreed that a new colour format RGB565A8 is planned to be added. 
Has the support been added ?

From the code https://github.com/lvgl/lvgl/blob/6560c792ca314b2226aa94fcea25acdc9890eb27/src/draw/sw/lv_draw_sw_img.c#L98-L99

and 

https://github.com/lvgl/lvgl/blob/6560c792ca314b2226aa94fcea25acdc9890eb27/src/draw/sw/lv_draw_sw_img.c#L223-L247

It appears that the native support for RGB565A8 isn't ready. 

Will it be introduced in v8.3.x?

**Comment by kisvegabor** [comment]
It's not added yet, but I implemented the new image related features to make it easy to support. Two things are missing:
1. Update the image converter to work to support this format. We have an [open issue](https://github.com/lvgl/lv_img_conv/issues/19) about new color formats, I'll comment about there in a few minutes. 
2. Actually support it in LVGL. I can do it quickly once the converter is updated.

**Comment by GorgonMeducer** [comment]
> 2. Actually support it in LVGL. I can do it quickly once the converter is updated.

I am working on the transform. I have many to say, especially when I see issue #3304.

You will soon see my solution which is ugly, an elegant solution should only rely on the transform interface, but the current structure makes it hard to release the potential of a GPU. 

 My suggestion is, please mark the transform interface as "experimental", so others won't spend time before it is settled down.

**Comment by kisvegabor** [comment]
Looking forward to your feedback! It's a pleasure that someone like you who is working so close to the hardware is participating the development of LVGL.

> My suggestion is, please mark the transform interface as "experimental", so others won't spend time before it is settled down.

`master` is no stable.  Everything in `master` which is not released yet is experimental and can be changed before the release.

**Comment by GorgonMeducer** [comment]
@kisvegabor  my first thoughts about the transform (and img_decoded) are:

- Current solution only uses transform to do transform work and perform recolour and/or other blend work later.
- A GPU usually can do all those work together. 

Further more, 
I don't understand the `mask_buf` passed to `lv_draw_transform()`

```c
if(transform) {
    lv_draw_transform(draw_ctx, &transform_area, src_buf, src_w, src_h, src_w,
                      draw_dsc, cf, rgb_buf, mask_buf);
}
else {
    convert_cb(&transform_area, src_buf, src_w, src_h, src_w, draw_dsc, cf, rgb_buf, mask_buf);
}
```

Before this part of the function, mask_buf is an empty array:

```c
        lv_opa_t * mask_buf = lv_mem_buf_get(buf_size);
        blend_dsc.mask_buf = mask_buf;
        blend_dsc.mask_area = &blend_area;
        blend_dsc.mask_res = LV_DRAW_MASK_RES_CHANGED;
```
My initial understanding was that if you want to rotate an RGBA8888 image, the mask_buf should contain the alpha mask as INPUT.

**Comment by kisvegabor** [comment]
> Current solution only uses transform to do transform work and perform recolour and/or other blend work later.

The transform API is for transformation. If you want to or can do other stuff by the GPU it's better to replace the whole `draw_img_decoded` callback. But if the GPU cannot handle e.g. LVGL masks (which is likely) you can still speed up the transformation part.

> I don't understand the mask_buf passed to lv_draw_transform()

`rgb_buf` and `mask_buf` are output buffers and `src_buf` is the input buffer. I found this "cut" the most efficient. That is once the transformation needs to process all the pixels (and probably handle RGB and alpha differently) it can also separate the color and alpha channels into 2 buffers. From what I understood from the ARM GPU implementation something like this might work (speaking about ARGB8888):
1. Transform the ARGB channels in to `rgb_buf`,
2. copy the alpha channel into `mask_buf`
3. set the alpha channel to 0xff in `rgb_buf`.

The gist is that rgb and alpha needs to be separated somewhere and I moved this task to the `transform_cb` to let the GPU do some magic on it. :slightly_smiling_face: 

Let me know if you see a faster and more convenient API.

**Comment by GorgonMeducer** [comment]
Now it is clear to me, `lv_draw_transform()` is purely used to transform the source img, here : 
> rgb_buf and mask_buf are output buffers and src_buf is the input buffer.

Thank you very much.

>If you want to or can do other stuff by the GPU it's better to replace the whole draw_img_decoded callback. 

That's the method I currently used. Based on what you said, then my current implementation is not that 'ugly' I used to believe.

**Comment by kisvegabor** [comment]
> Based on what you said, then my current implementation is not that 'ugly' I used to believe.

I'm not sure it's a good news. :smile:

**Comment by GorgonMeducer** [comment]
@kisvegabor my solution is here:

https://github.com/lvgl/lv_port_an547_cm55_sim/blob/developing/lv_gpu_arm2d.c

https://github.com/lvgl/lv_port_an547_cm55_sim/blob/f2c5491ac96c5904b27092048e15330e36d7bc58/lv_gpu_arm2d.c#L794-L1090

**Comment by kisvegabor** [comment]
[Here](https://github.com/lvgl/lv_port_an547_cm55_sim/blob/7b9d8f249d73f253f01ba0babbc2c15435502c52/lv_gpu_arm2d.c#L1035) why don't you simply call `lv_draw_sw_img_decoded()` instead of reimplementing it?

**Comment by GorgonMeducer** [comment]
> [Here](https://github.com/lvgl/lv_port_an547_cm55_sim/blob/7b9d8f249d73f253f01ba0babbc2c15435502c52/lv_gpu_arm2d.c#L1035) why don't you simply call `lv_draw_sw_img_decoded()` instead of reimplementing it?

I haven't clean them. 

Now, since I will accelerate the recolor part inside the loop, it is hard to use the original one. 

To solve this problem, I am considering introducing a dedicated low level interface for accelerating the recolor. If you think this is acceptable, then it is possible to call `lv_draw_sw_img_decoded()` at the place you mentioned.

**Comment by kisvegabor** [comment]
At first look, abstracting image recoloring seems a little bit too specific to me but it can be used in [another place](https://github.com/lvgl/lvgl/blob/master/src/draw/sw/lv_draw_sw_blend.c#L260) too. Can you imagine other use cases?

Generally, it's mixing a color to an image with a given opacity, right?

**Comment by GorgonMeducer** [comment]
@kisvegabor Well, I don't know what's other use case, in fact, the whole recolor looks strange from my perspective. 

The only reason I propose to have a dedicated interface is by doing so, I can call the default sw implementation. As you can see now, It is impossible, I have to keep some code copied from the sw implementation.

**Comment by kisvegabor** [comment]
> the whole recolor looks strange from my perspective.

Yes, it's really not a standard feature. I introduced it many years ago to make it simple and memory efficient to use the same image as a button for released, pressed and inactive state by recoloring it.

> As you can see now, It is impossible, I have to keep some code copied from the sw implementation.

Copying this 10 lines of recoloring is better IMO than adding a new callback. At least until we find a more generic use case for this feature. 

Or we can create a public function from that short recoloring loop that you can call as well. 

What do you think?

**Comment by GorgonMeducer** [comment]
@kisvegabor For now, I think the current copy-modify-keep method is OK. I will keep my eyes on any change in the sw_draw_img function. 

If you find PR related to this one, please ping me.

**Comment by kisvegabor** [comment]
Okay! I started to implement the RGB565A8 support but it seems there is some problem with the image converter. We are tracking it here: https://github.com/lvgl/lv_img_conv/issues/19

**Comment by kisvegabor** [comment]
RGB565-A8 support is added here: https://github.com/lvgl/lvgl/tree/feat/rgb565a8

**Comment by kisvegabor** [comment]
I've merged the [feat/rgb565a8](https://github.com/lvgl/lvgl/tree/feat/rgb565a8) branch to master. I close this issue. Please comment here if you find any issues.

**Comment by GorgonMeducer** [comment]
@kisvegabor  I will add the arm-2d support by end of May.
By the way, do you consider adding a dedicated scene in the benchmark for RGB565A8?
