### ISSUE TITLE
lv_label_set_text memory allocation issue.

### ISSUE THREAD

**Issue by nameofuser1** [lvgl/lvgl#332]
Here are lines 156 and 157 of `lv_label.c`:

    ext->text = lv_mem_alloc(len);
    strcpy(ext->text, text);

As you can see if memory is not allocated there is no check for NULL and therefore `strcpy` will likely cause a crash like it is in my case.

**Comment by kisvegabor** [comment]
Hi,

I pushed an update to `dev-5.2` branch to handle memory allocation failures in the library.
See: https://github.com/littlevgl/lvgl/blob/dev-5.2/lv_objx/lv_label.c#L161

I will extend the `lv_mem_assert` macro to add log if the memory allocation is failed.

**Comment by nameofuser1** [comment]
Thanks! That will do.

Also please check these `lv_mem_realloc` outputs they miss memory validation too:

https://github.com/littlevgl/lvgl/blob/2e17562e51e5b0a058abbd0be19dc10d1d1b5cf8/lv_objx/lv_label.c#L114

https://github.com/littlevgl/lvgl/blob/2e17562e51e5b0a058abbd0be19dc10d1d1b5cf8/lv_objx/lv_label.c#L150

https://github.com/littlevgl/lvgl/blob/2e17562e51e5b0a058abbd0be19dc10d1d1b5cf8/lv_objx/lv_label.c#L593

**Comment by kisvegabor** [comment]
Thanks, I forget the realloc-s. I pushed the update.

**Comment by nameofuser1** [comment]
Thanks!
