### ISSUE TITLE
Increase scale rendering accuracy in lv_meter

### ISSUE THREAD

**Issue by hard-cat** [lvgl/lvgl#3361]
Please tell me, is it possible to somehow improve the accuracy of drawing the scale?

![image](https://user-images.githubusercontent.com/87597134/168806886-4303cf0c-d554-4817-9e12-b1a7f74bdae7.png)

    lv_obj_t * meter = lv_meter_create(backgrd);
    lv_obj_center(meter);
    lv_obj_set_size(meter, 230, 230);
    lv_obj_align(meter, LV_ALIGN_CENTER, 0, 0);

    /*Remove the circle from the middle*/
    lv_obj_remove_style(meter, NULL, LV_PART_INDICATOR);

    lv_meter_scale_t * scale = lv_meter_add_scale(meter);
    lv_meter_set_scale_ticks(meter, scale, 150, 2, 16, lv_palette_main(LV_PALETTE_GREY));

**Comment by kisvegabor** [comment]
I made some experiments and could improve it. Please try thins patch:
```diff
diff --git a/src/extra/widgets/meter/lv_meter.c b/src/extra/widgets/meter/lv_meter.c
index 6f12a567..1ddd43fa 100644
--- a/src/extra/widgets/meter/lv_meter.c
+++ b/src/extra/widgets/meter/lv_meter.c
@@ -404,7 +404,7 @@ static void draw_ticks_and_labels(lv_obj_t * obj, lv_draw_ctx_t * draw_ctx, cons
     _LV_LL_READ_BACK(&meter->scale_ll, scale) {
         part_draw_dsc.sub_part_ptr = scale;
 
-        lv_coord_t r_out = r_edge + scale->r_mod;
+        lv_coord_t r_out = r_edge;
         lv_coord_t r_in_minor = r_out - scale->tick_length;
         lv_coord_t r_in_major = r_out - scale->tick_major_length;
 
@@ -473,29 +473,17 @@ static void draw_ticks_and_labels(lv_obj_t * obj, lv_draw_ctx_t * draw_ctx, cons
                 }
             }
 
-            /*`* 256` for extra precision*/
-            int32_t angle_upscale = ((i * scale->angle_range) << 8) / (scale->tick_cnt - 1);
-
-            int32_t angle_low = (angle_upscale >> 8);
-            int32_t angle_high = angle_low + 1;
-            int32_t angle_rem = angle_upscale & 0xFF;
-
-            /*Interpolate sine and cos*/
-            int32_t sin_low = lv_trigo_sin(angle_low + scale->rotation);
-            int32_t sin_high = lv_trigo_sin(angle_high + scale->rotation);
-            int32_t sin_mid = (sin_low * (256 - angle_rem) + sin_high * angle_rem) >> 8;
-
-            int32_t cos_low = lv_trigo_cos(angle_low + scale->rotation);
-            int32_t cos_high = lv_trigo_cos(angle_high + scale->rotation);
-            int32_t cos_mid = (cos_low * (256 - angle_rem) + cos_high * angle_rem) >> 8;
+            /*`* 10` for extra precision*/
+            int32_t angle_upscale = ((i * scale->angle_range) * 10) / (scale->tick_cnt - 1) +  + scale->rotation * 10;
 
             line_dsc.color = line_color;
             line_dsc.width = line_width;
             /*Use the interpolated angle to get the outer x and y coordinates.
              *Draw a little bit longer lines to be sure the mask will clip them correctly*/
             lv_point_t p_outer;
-            p_outer.x = (int32_t)(((int32_t)cos_mid * (r_out + line_width) + 127) >> (LV_TRIGO_SHIFT)) + p_center.x;
-            p_outer.y = (int32_t)(((int32_t)sin_mid * (r_out + line_width) + 127) >> (LV_TRIGO_SHIFT)) + p_center.y;
+            p_outer.x = p_center.x + r_out + LV_MAX(100, r_out);
+            p_outer.y = p_center.y;
+            lv_point_transform(&p_outer, angle_upscale, 256, &p_center);
 
             part_draw_dsc.p1 = &p_outer;
             part_draw_dsc.p1 = &p_center;
@@ -507,8 +495,9 @@ static void draw_ticks_and_labels(lv_obj_t * obj, lv_draw_ctx_t * draw_ctx, cons
                 lv_draw_mask_remove_id(outer_mask_id);
                 uint32_t r_text = r_in_major - scale->label_gap;
                 lv_point_t p;
-                p.x = (int32_t)((int32_t)((int32_t)cos_mid * r_text + 127) >> LV_TRIGO_SHIFT) + p_center.x;
-                p.y = (int32_t)((int32_t)((int32_t)sin_mid * r_text + 127) >> LV_TRIGO_SHIFT) + p_center.y;
+                p.x = p_center.x + r_text;
+                p.y = p_center.y;
+                lv_point_transform(&p, angle_upscale, 256, &p_center);
 
                 lv_draw_label_dsc_t label_dsc_tmp;
                 lv_memcpy(&label_dsc_tmp, &label_dsc, sizeof(label_dsc_tmp));
``` 

The performance might be slightly worse. I can fix it later if the changes look good.

Before:
![image](https://user-images.githubusercontent.com/7599318/168889747-5dd55e05-a831-4e9e-a6fa-a25a85e3a641.png)


After:
![image](https://user-images.githubusercontent.com/7599318/168889670-7ea86c53-23f8-4942-8e93-aa81430e2b23.png)

Still not perfect, but the current line drawer is a trade off between quality, speed and memory usage.

**Comment by hard-cat** [comment]
@kisvegabor 

Thanks, I've applied these fixes.
Could you help me with the arrow too? I would like the arrow to start not from the center (1), but indented from the center (2).

![image](https://user-images.githubusercontent.com/87597134/168950190-2628fe1b-7c79-4058-b89d-5c97089cf192.png)

**Comment by hard-cat** [comment]
I tried to display the arrow as a picture, but it is not displayed correctly, it seems to me ...

        lv_obj_t * meter_l = lv_meter_create(backgrd);
        lv_obj_center(meter_l);
        lv_obj_set_size(meter_l, 240, 240);
        lv_obj_align(meter_l, LV_ALIGN_CENTER, 0, 0);
        //Remove the circle from the middle
        lv_obj_remove_style(meter_l, NULL, LV_PART_INDICATOR);
        
        lv_meter_scale_t * scale_l = lv_meter_add_scale(meter_l);
        lv_meter_set_scale_range(meter_l, scale_l, 0, 40, 90, 135);	
        lv_meter_set_scale_ticks(meter_l, scale_l, 40, 2, 21, lv_color_hex(0x3D3D3D));
        
        lv_meter_indicator_t * indic = lv_meter_add_needle_line(meter_l, scale_l, 4, lv_palette_main(LV_PALETTE_GREY), -10);
        lv_meter_set_indicator_end_value(meter_l, indic, 0);
        
        LV_IMG_DECLARE(arrow)
        lv_meter_indicator_t * indic_min = lv_meter_add_needle_img(meter_l, scale_l, &arrow, -70, -70);
        lv_meter_set_indicator_end_value(meter_l, indic_min, 0);

![image](https://user-images.githubusercontent.com/87597134/168963853-c2950338-ba6b-4d48-a25d-a40d47f61195.png)


original picture of the arrow
![Arrow 27](https://user-images.githubusercontent.com/87597134/168963912-68dcb33b-9332-40f9-8e28-cc4405b814ec.png)

PS: my bad, I'm trying to make another image of the arrow

**Comment by kisvegabor** [comment]
> Thanks, I've applied these fixes.

And does it look acceptable on the device?

**Comment by hard-cat** [comment]
this is a photo with a patch
![image](https://user-images.githubusercontent.com/87597134/168970544-a5a77a69-91b6-401e-8e0e-fa2831b7e543.png)

this photo is without patch
![image](https://user-images.githubusercontent.com/87597134/168970685-1e6d6ceb-e964-4976-990b-3251663d5b85.png)

there is a difference, but not much
discrepancies are visible at the beginning and end of the scale (3 elements at the bottom and at the top)

I made an arrow in the form of a picture and it works. But another problem appeared - smoothing the line on the image will not work. Can you please tell me if this can be discussed here, or should I open a new topic?

**Comment by kisvegabor** [comment]
> Can you please tell me if this can be discussed here, or should I open a new topic?

Feel free to describe it here. Let's see the issues of the meter in one place :slightly_smiling_face:

**Comment by hard-cat** [comment]
Fine :-)
Could you add a shift to the arrow like it's done in the arrow image function?

 * @param pivot_x       the X pivot point of the needle
 * @param pivot_y       the Y pivot point of the needle

**Comment by kisvegabor** [comment]
Which function do you mean?

**Comment by hard-cat** [comment]
Arrow display function

lv_meter_indicator_t * indic = lv_meter_add_needle_line(meter_l, scale_l, 4, lv_palette_main(LV_PALETTE_GREY), -10);

![image](https://user-images.githubusercontent.com/87597134/169231444-31ef843b-9924-4d67-91e8-6aa04295b8e9.png)
I would like to get the indent of the arrow from the center, as in Figure 2.

**Comment by kisvegabor** [comment]
For this I suggest using a small line-like image and `lv_meter_add_needle_img()`.

**Comment by hard-cat** [comment]
Yes, right now I'm using a picture, but there is a problem. The arrow has anti-aliasing and looks good. When using an image and rotating it, it looks grainy.

red line - picture (lv_meter_add_needle_img)
![image](https://user-images.githubusercontent.com/87597134/169284553-c4b9a4ba-0dcd-4b16-aafd-a145c02e9547.png)

**Comment by hard-cat** [comment]
red line - picture (lv_meter_add_needle_img)

![image](https://user-images.githubusercontent.com/87597134/169284377-8ae520d1-0a1e-428f-909f-77423b63f209.png)

**Comment by kisvegabor** [comment]
Hm, rotation should  be anti aliased. 

Can you check [here](https://github.com/lvgl/lvgl/blob/master/src/extra/widgets/meter/lv_meter.c#L629) if `img_dsc.antialias == 1`?

**Comment by hard-cat** [comment]
i checked, img_dsc.antialias is equal to 1
maybe something is wrong with my picture?
[red_line.txt](https://github.com/lvgl/lvgl/files/8751519/red_line.txt)

**Comment by kisvegabor** [comment]
I've checked it and it was really anti-aliased but with a bad quality. It's because the SW rotate algorithm can do better job if there is at least 1px transparent "border" around the image. I added it manually to the C array and it look like this now:
![image](https://user-images.githubusercontent.com/7599318/169751235-918026a0-2e3f-452b-b541-1e04c8b83456.png)

**Comment by hard-cat** [comment]
I added a transparent outline, now anti-aliasing works. thank!

**Comment by hard-cat** [comment]
Can I have one more question about lv_meter?)

I want the last element (lv_meter_add_scale_lines) to be with a label. I added the following code to lv_meter.c

![image](https://user-images.githubusercontent.com/87597134/169768220-1a6fba93-2969-42d9-a3a4-aebac4186da8.png)

This works, but not for all values. For some values, 2 labels appear.
How to correctly determine the last tick in this cycle?

![image](https://user-images.githubusercontent.com/87597134/169768946-bb4cc89c-7a5c-4956-bc42-ab45230697f7.png)

**Comment by hard-cat** [comment]
I did, maybe crooked, but it works)

![image](https://user-images.githubusercontent.com/87597134/170057116-ed7ad0da-9f70-4c9e-9a07-d3e46adbc514.png)
![image](https://user-images.githubusercontent.com/87597134/170057232-ddef0a65-7b57-45ee-8747-21f410953198.png)

**Comment by kisvegabor** [comment]
It seems working for me:
![image](https://user-images.githubusercontent.com/7599318/170565290-7e0eb4b9-76a2-4883-8a25-445627ffb5cd.png)

**Comment by hard-cat** [comment]
this works with integers, you are using int32_t. When the number of ticks is, for example, 40, and the range is from 0 to 100, then there are problems with some values. If the range is equal to the number of indicator ticks, then there is no problem.

**Comment by kisvegabor** [comment]
True. In this case I have no better idea than what you already did. 

One optimization point I see though: you save the previous value of line in a `value_of_line_prev` variable, instead of always calculating the next value.

**Comment by kisvegabor** [comment]
Are there any other remained here? If not I'll add the discussed improvement to master.

**Comment by hard-cat** [comment]
hi,
I didn't do anything else, that's enough for my project

**Comment by kisvegabor** [comment]
I pushed the fix to improve the line drawing precision.
