### ISSUE TITLE
Whether the “ta” object can limit the length of the input text

### ISSUE THREAD

**Issue by as564335sa** [lvgl/lvgl#345]
Hi，
Whether the “ta” object can limit the length of the input text , i think it is very useful ,and add enhancements that can set the text input type , such as letters or numbers；

**Comment by kisvegabor** [comment]
Hi,

I agree both would be useful features. So I added them to `dev-5.2` branch. :)

You can try them with
```c
lv_ta_set_accepted_chars(ta, "0123456789");
lv_ta_set_max_length(ta, 8)
```

**Comment by as564335sa** [comment]
Hi,
I update to the `dev-5.2`  branch and test it  , these two functions are good and worked well，but have some issues:
this the code:
```c
lv_obj_t *ta = lv_ta_create(win, NULL);
lv_ta_set_cursor_type(ta, LV_CURSOR_LINE);
lv_ta_set_cursor_pos(ta,LV_TA_CURSOR_LAST);
lv_ta_set_one_line(ta,true);
lv_ta_set_accepted_chars(ta,"0123456789");
lv_ta_set_max_length(ta,5);
lv_ta_set_text(ta,"1\n2aaaaaa");
lv_group_add_obj(g, ta);
```
I got this:
![err](https://user-images.githubusercontent.com/35949162/43749038-08becb50-9a25-11e8-9a29-05713b6a3376.jpg)
![err2](https://user-images.githubusercontent.com/35949162/43749368-64ef17da-9a26-11e8-8cf6-e04e0a9f7c1e.jpg)

you can see:
1、The line is correct when use "enter" key , but is error  when use `lv_ta_set_text`；
2、The max length is correct when input some keys , but is error when use `lv_ta_set_text` ；
3、The letter is error when use `lv_ta_set_text` ; 
3、I del all texts and reinput , it worked well;

**Comment by kisvegabor** [comment]
Hi,

I fixed it and now it worked fine for me with every input.

How is it working there?

**Comment by as564335sa** [comment]
Great！The issues is solved,thank you!

**Comment by kisvegabor** [comment]
Thank you for the test!
