### ISSUE TITLE
Issues about "ta" when "USE_LV_ANIMATION" is set to 0

### ISSUE THREAD

**Issue by as564335sa** [lvgl/lvgl#346]
Hi,
In order to save space and make it run fast，i set  `#define USE_LV_ANIMATION        0`
there are two issues;
1、The cursor will not show，i think it should be show, but not blink；
2、see the code:
```c
passwd_ta = lv_ta_create(cont,NULL);
lv_ta_set_one_line(passwd_ta,true);
lv_obj_align(passwd_ta,cont,LV_ALIGN_CENTER,0,0);
lv_obj_set_size(passwd_ta,200,20);
lv_ta_set_style(passwd_ta,LV_TA_STYLE_BG,&cont_style);
lv_ta_set_pwd_mode(passwd_ta,true);
lv_ta_set_text(passwd_ta,"000000");
```
Because the animation is closed，the "ta" will show "000000" instead of "******" ； If I delete all text and use a keyboard input some text，the last character will not show ‘\*‘；

**Comment by kisvegabor** [comment]
Hi,

I fixed both of them in `dev-5.2`. Please test it.

**Comment by as564335sa** [comment]
Great! It worked well!

**Comment by kisvegabor** [comment]
Thanks for the test! :)
