### ISSUE TITLE
How to integrate with FreeRTOS, etc

### ISSUE THREAD

**Issue by ghost** [lvgl/lvgl#347]
Hi,

I've been working with LVGL (amazing project!) and I am wondering how to integrate it with an RTOS. The README mentions that OS support is available, and I see that you have tested it with FreeRTOS. However, I don't see any locking mechanisms. Is this required or does it "Just Work (TM)?"

**Comment by Zaltora** [comment]
I use lvgl with FreeRTOS. I will do a PR soon on the project `esp-open-rtos` for the esp8266.
Example link with ssd1306 example: [example](https://github.com/Zaltora/esp-open-rtos/tree/lvgl/examples/lvgl_ssd1306)
i use:
lv_drivers => new_api branch
lvgl => dev-5.2 branch

Hope it is help.

**Comment by DeonMarais64** [comment]
This is how I do it.

```C
static SemaphoreHandle_t uiMutex;

V UI_TakeMutex ( V )
{
	while( xSemaphoreTake( uiMutex, portMAX_DELAY ) != pdTRUE )
		;
}

V UI_GiveMutex ( V )
{
	xSemaphoreGive( uiMutex );
}

static V TaskLVGL( PV p )
{
	for( ; ; )
	{
		vTaskDelay( pdMS_TO_TICKS(10) );

		UI_TakeMutex();
		lv_task_handler();
		UI_GiveMutex();
	}
}

static V TaskUiEvery200ms ( PV p )
{
	UF8 _400ms, _1000ms;

	for( ; ; )
	{
		vTaskDelay( pdMS_TO_TICKS(200) );

		if( ++_400ms >= 2 )
		{
			_400ms = 0;
			Screens_Every400ms();
		}
		if( ++_1000ms >= 5 )
		{
			_1000ms = 0;
			Screens_Every1000ms();
		}
	}
}
```
Screens_Every400ms() and Screens_Every1000ms() call UI_TakeMutex and UI_GiveMutex as and if lvgl API functions are called.

**Comment by kisvegabor** [comment]
@markyi370 It seems your question is answered so I close this issue.
If you have further question, feel free to reopen it!

**Comment by ghost** [comment]
@kisvegabor Yes, my question is answered. Thank you for the quick responses everyone!
