### ISSUE TITLE
User define keyboard event

### ISSUE THREAD

**Issue by heyingjie** [lvgl/lvgl#349]
HI
    in some cases,we need deal keyboard event by user application,so that we need throw out key code to user application.but in obj signal,key code is not trans to action.
![image](https://user-images.githubusercontent.com/11901953/43674476-2890d650-9807-11e8-8ba8-f06434155e45.png)
    so,change 
![image](https://user-images.githubusercontent.com/11901953/43674482-4cdd82ec-9807-11e8-8fc9-7f9a3dbea7ca.png)
to 
![image](https://user-images.githubusercontent.com/11901953/43674490-80f30084-9807-11e8-9e95-5bfde8267e16.png)
Is that a reasonable modification?

**Comment by BesitzeRuf** [comment]
On other hand you can assign your each button with key_code by your own table... also there is free_num and free_ptr variable, which you can set and read for/from any object.

**Comment by kisvegabor** [comment]
I added `lv_indev_get_key` in `dev-5.2` branch.

In the action, you can use: 
```c
lv_indev_t * indev = lv_indev_get_act();
uint32_t last_key = lv_indev_get_key(indev);
```
I hope it also helps.
