### ISSUE TITLE
Cursor disapear on one-line mode

### ISSUE THREAD

**Issue by BenQoo** [lvgl/lvgl#35]
1. set a non-empty string without newline to `lv_ta`.
1. enable `lv_ta_set_one_line`
1. take `lv_ta_cursor_right`  to move cursor from left to right .
1. cursor will disappear once it reach the right-most character.

**Comment by kisvegabor** [comment]
Hi,
thank you! 
Fixed in `beta`!

**Comment by BenQoo** [comment]
Hi,
After testing, it fix in `beta` now, thank you!

**Comment by kisvegabor** [comment]
Your welcome!
