### ISSUE TITLE
Table function requirements

### ISSUE THREAD

**Issue by bishuilongyuan** [lvgl/lvgl#358]
Hello, author.
      Thank you very much for your littlevGL, which has brought convenience to our study. I would like to make a suggestion and hope to provide the form components in the new version. Many times, we need to use a table to display the data and refresh the data in the table in real time.
      Thanks again.
Congratulations!

**Comment by kisvegabor** [comment]
Hi,

I'm happy to hear that you found LittlevGL useful! 

We already have a thread about adding a "table" object here: https://github.com/littlevgl/lvgl/issues/137

Please, write a few lines there to show your interest. Unfortunately, right now there are other things to do with higher priority. However, if more people is interested in this object type it's more probable that I or somebody will implement it.
