### ISSUE TITLE
dev_5_2 How to solve this problem?

### ISSUE THREAD

**Issue by GddWuliu** [lvgl/lvgl#367]
#337 
![_20180816135707](https://user-images.githubusercontent.com/40491234/44191104-4e04ec80-a119-11e8-9100-73b3317c0141.png)

**Comment by BesitzeRuf** [comment]
What are your settings of project in KEIL environment (C, C++)?

**Comment by kisvegabor** [comment]
Check this: http://www.keil.com/forum/18454/cast-to-structure-not-working/
As the last but one comments says: "After adding --c99 in "Misc Controls" on "C/C++" Options, it compiles."

**Comment by GddWuliu** [comment]
### ![_20180816193701](https://user-images.githubusercontent.com/40491234/44206261-c20ab900-a148-11e8-842a-fbd20b86975b.png)

**Comment by GddWuliu** [comment]
So if I add c99, it still doesn't work

**Comment by GddWuliu** [comment]
thanks!
problem was solved .
 After adding --gnu --c99 in "Misc Controls" on "C/C++" Options, it compiles

**Comment by GddWuliu** [comment]
thanks!
 problem was solved .
 After adding --gnu  in "Misc Controls" on "C/C++" Options, it compiles
