### ISSUE TITLE
lv_obj_prot_t type is  not defined in the library.

### ISSUE THREAD

**Issue by mrkvtrs** [lvgl/lvgl#382]
The type is not defined in the library but there is a text that says that the type is  defined somewhere.

` * @param prot 'OR'-ed values from lv_obj_prot_t`
` */`
`void lv_obj_set_protect(lv_obj_t * obj, uint8_t prot)`

**Comment by mrkvtrs** [comment]
I found this :
`lv_protect_t`

Looks like I found a typo.

**Comment by kisvegabor** [comment]
Hi,

Thank you! Fixed!

I'm working on the `img_decoder` branch now and I pushed the fix there. It will be part of `v5.2`
