### ISSUE TITLE
change color on a simple objects? (Additional: circle objects?, variable in a text label?)

### ISSUE THREAD

**Issue by epikao** [lvgl/lvgl#387]
Hello, 
I just have difficults with I think a very simple issue... I can't find an example how to change the color of an simple object (square, rectangle). 
Follow code gives me an error:
 ```
  static lv_style_t style_obj1;
  style_obj1.obj.color = LV_COLOR_MAKE(0xFF, 0x00, 0x00);
  //style_obj1.body.main_color = LV_COLOR_MAKE(0xFF, 0x00, 0xF0);

  lv_obj_t * obj1 = lv_obj_create(lv_scr_act(), NULL);/*Create an object */
  lv_obj_set_size(obj1, 50, 50);            /*Set the size of the object*/
  lv_obj_set_style(obj1, &style_obj1);
  lv_obj_set_pos(obj1, 10, 10);               /*Set the position of the  object*/
```

**Additional two questions:**
1) Can I also create circles?

2) I have an variable and want show the value in a text (label) - is that possible, or how to do that?
uint16_t variable = 3460;
lv_label_set_text(label, "Hello %variable?? Arduino!");

**Comment by kisvegabor** [comment]
Hi,

The objects can have a gradient so you should set `body.main_color` and `body.grad_color`.
See this for documentation: https://littlevgl.com/basics#styles

1. Circle: `body.radius = LV_RADIUS_CIRCLE`

2. To convert tumbers to text: 
```c
int num = 100;
char buf[32];
sprintf(buf, "Value: %d", num);
lv_label_set_text(label, buf);
```

**Comment by epikao** [comment]
> The objects can have a gradient so you should set body.main_color and body.grad_color.
> See this for documentation: https://littlevgl.com/basics#styles

thanks, I already tried that, but then the object disappears (see code above which is excluded with // )...

**Comment by kisvegabor** [comment]
It's because the fields of `style_obj1` variable are not initialized. You should give it an initial value from a built-in style.
E.g. `lv_style_copy(&style_obj1, &lv_style_plain_color)`;

**Comment by epikao** [comment]
> E.g. lv_style_copy(&style_obj1, &lv_style_plain_color);

ok thanks, it works now. I needed to define min. two colors to get the square with one color (body + gradient)

**Comment by kisvegabor** [comment]
Yes, `main_color` and `grad_color` should be set as well.
