### ISSUE TITLE
Layer move objects don't work

### ISSUE THREAD

**Issue by Satnet** [lvgl/lvgl#3918]
The functions lv_obj_move_up(obj) and lv_obj_move_down(obj) are documented here: https://docs.lvgl.io/8.3/overview/layer.html?highlight=layers but they do not actually exist in LVGL.

Functions to move layers is really important. If an object that is created after another object needs to be on top in terms of layers, there's no way of doing it.

Thanks

**Comment by kisvegabor** [comment]
Thank you for pointing it out. I've just fixed it here. https://github.com/lvgl/lvgl/commit/9faca8a8d4125e21dedbf6e46aa1586a6b57e5b8
