### ISSUE TITLE
Memory leak in lv_fs_open if there is an error from drv->open

### ISSUE THREAD

**Issue by DavidCozens** [lvgl/lvgl#396]
Hi,

I noticed a memory leak when loading images from an SDCard, basically loading the images worked fine, however if I removed the SDCard I found that my system fell over having run out of memory.

I've tracked the issue down to lv_fs.c, after a few initial checks lv_mem_alloc is called to allocate space for file_d, if there is any error beyond this point then the memory is leaked.

I have fixed it locally by moving the check for open being implemented up, and then where res is checked after the call to open freeing the memory. It would be great if a fix could be rolled into the next release.
```

   if(file_p->drv->open == NULL) {
        return LV_FS_RES_NOT_IMP;
    }
    file_p->file_d = lv_mem_alloc(file_p->drv->file_size);
    if(file_p->file_d == NULL) {   
        file_p->drv = NULL;
        return LV_FS_RES_OUT_OF_MEM;  /* Out of memory */
    }        
    
    const char * real_path = lv_fs_get_real_path(path);
    lv_fs_res_t res = file_p->drv->open(file_p->file_d, real_path, mode);
    
    if(res != LV_FS_RES_OK) {
        lv_mem_free(file_p->file_d);
        file_p->drv = NULL;
        file_p->file_d = NULL;
    }

    return res;
}
```
Thanks David

**Comment by kisvegabor** [comment]
Hello David,

Thank you for pointing this out. 
I fixed it in `dev-5.2` branch so it will be part of the next release.
