### ISSUE TITLE
Improvement in memory management

### ISSUE THREAD

**Issue by ajaybhargav** [lvgl/lvgl#4]
If a system already provide malloc/free functions then there is no need to use misc/mem module. This will save lot of code space. You can move memory management to HAL instead so people can either write their own dm_* functions or enable USE_DYN* flag if system does not have malloc/free function.

Create a separate dm_mem.h file to define only the function prototypes of needed functions:

dm_init()
dm_alloc()
dm_free()
dm_realloc()

**Comment by kisvegabor** [comment]
In version 2.1 it be configured in misc_conf.h
