### ISSUE TITLE
Disable touch functionality for some objects

### ISSUE THREAD

**Issue by robrochta** [lvgl/lvgl#401]
Is there a way to disable touch functionality for specific objects?
For example, I have a roller object with a button on the same screen.
I want to control selected position of the roller object with an encoder (and not to respond to a touch), and then select an action with a button. What would be the easiest way to do it?

**Comment by kisvegabor** [comment]
Hi,
You can use `lv_obj_set_click(roller, false)`. However to the roller is compounded object you should disable the touch of the scrolling part too: `lv_obj_set_click(lv_page_get_scrl(roller), false)`

**Comment by robrochta** [comment]
Thank you Gabor!
lv_obj_set_click(lv_page_get_scrl(roller), false) was the missing ingredient. Works exactly the way I wanted it to work.

**Comment by seyyedemadmo** [comment]
this function dos not exist for me i use lvgl 8.2.0

**Comment by kisvegabor** [comment]
In v8 you can use: `lv_obj_clear_flag(obj, LV_OBJ_FLAG_CLICKABLE);`

**Comment by seyyedemadmo** [comment]
Its works thanks for your help
