### ISSUE TITLE
roller looses it's value after changing focus 

### ISSUE THREAD

**Issue by IronCaterpillar** [lvgl/lvgl#409]
Roller widget is restoring its value to default after switching focus to another component. How to avoid this behavior? Maybe there is another option to save the value of roller?

**Comment by BrianPugh** [comment]
Was this fixed? I change focus in the roller callback, and this causes the roller value to reset.

**Comment by kisvegabor** [comment]
I've just pushed a fix for it to `master`.

**Comment by IronCaterpillar** [comment]
Thank you! Excuse me for not letting you know. I've switched to the branch dev-5.2 and it worked for me.

**Comment by kisvegabor** [comment]
@IronCaterpillar No problem :)

**Comment by BrianPugh** [comment]
works now! thanks!
