### ISSUE TITLE
hide list

### ISSUE THREAD

**Issue by ali-rostami** [lvgl/lvgl#410]
I need to display a list which should be shown when we press a button object and it should be hidden when we touch the out of the list areas, except places we have other buttons.
After looking to the 'write' tab of demo code, I concluded that I can create a button(or maybe a page) and make it the parent of all buttons on the page and set its size equal to the whole screen and also make it transparent. after doing this in its press action I should delete the list object.
Am I right or is there any better solution?

**Comment by kisvegabor** [comment]
Hi,

It's correct, I'd do the same way!
