### ISSUE TITLE
lv_group_del function is not decleared in lv_group.h file

### ISSUE THREAD

**Issue by mrkvtrs** [lvgl/lvgl#414]
lv_group_del function is not decleared in lv_group.h file and this causes a 
`warning: implicit declaration of function 'lv_group_del' `

As the function is global it has to be added to the header file.

**Comment by kisvegabor** [comment]
Hi,

Thank you for pointing this out!

It already fixed in `dev-5.2`: https://github.com/littlevgl/lvgl/blob/dev-5.2/lv_core/lv_group.h#L76
