### ISSUE TITLE
Is there a way to rotate a image?

### ISSUE THREAD

**Issue by mianhuacar** [lvgl/lvgl#418]
Hi,
Is there a way to rotate a image? I want to make a knob like below :)
![xn0](https://user-images.githubusercontent.com/3974849/45811367-71661d00-bcff-11e8-8536-02790b3a1540.png)

And i want to make clock too :)
![timg](https://user-images.githubusercontent.com/3974849/45811556-f8b39080-bcff-11e8-937b-386eb4d08f93.jpg)

Thank you

**Comment by kisvegabor** [comment]
Hi,

Unfortunately, image rotation is not supported now. 

It would be required for the clock indeed. However, why is it required for the knob? You can have the whole knob as an image except the little "circle". The little "circle" can be an other image which just needs to be positioned on the background knob.

**Comment by mianhuacar** [comment]
Oh, thank you.
I will waiting the day lvgl can rotate the image :)

**Comment by kisvegabor** [comment]
Me too. :)

I have an intention to add an image rotate feature once but unfortunately, I can't promise anything about right now.

Anyway, I leave open this issue as a reminder.

**Comment by mianhuacar** [comment]
Thanks a lot

**Comment by kisvegabor** [comment]
As adding image rotate is not planned in the near feature, to keep the list of issues I close it.

Image rotate and image zoom is the two missing advanced features so I'm sure they won't be forgotten. :)
