### ISSUE TITLE
how do I center the text in a TextArea

### ISSUE THREAD

**Issue by gjohnson0720** [lvgl/lvgl#421]
I've tried everything I can think of.  I must be missing something.

**Comment by kisvegabor** [comment]
Hi,

It should work:  (tested on `dev-5.2` branch):
`lv_label_set_align(lv_ta_get_label(ta), LV_LABEL_ALIGN_CENTER);`

**Comment by kisvegabor** [comment]
It's really not trivial ho to align the label in one line mode.
I added a function to do it: `lv_ta_set_text_align(ta, LV_LABEL_ALIGN_CENTER)` 

It supports `LV_LABEL_ALIGN_RIGHT` too.

Please test it and let me know how it works.
