### ISSUE TITLE
a small need，can lvgl rotate all things 90 degree?

### ISSUE THREAD

**Issue by mianhuacar** [lvgl/lvgl#424]
Hi，
I change the display degree, but can't change the touch erea... haha
![no touch](https://user-images.githubusercontent.com/3974849/45936963-d9ae4a80-bfee-11e8-904e-91e4cd3e1bc4.png)
![touch](https://user-images.githubusercontent.com/3974849/45936966-ddda6800-bfee-11e8-8eec-e5a2528a0007.png)

**Comment by mianhuacar** [comment]
I solved the problem,swap the input x and y.

**Comment by kisvegabor** [comment]
Great!
I general you need to provide the coordinates according to the display's orientation.
