### ISSUE TITLE
button descriptor with variable

### ISSUE THREAD

**Issue by epikao** [lvgl/lvgl#425]
Hello, I want make a button-matrix, but I need to use values from a variable for the button description.

follow code does not work, why?:

```
  int num = 1984;
  char buf[32];
  sprintf(buf, "%d", num);

static const char * btnm_map[] = {"1", "2", "3", "4", "5", "\n",
                           "6", "7", "8", "9", "0", "\n",
                           "\202Action1", buf, ""};
```

**Comment by kisvegabor** [comment]
Hi,

`buf` should be global or static to remain "alive" when the function exits.

**Comment by epikao** [comment]
thank you :-) now it works

**Comment by kisvegabor** [comment]
Great :)
