### ISSUE TITLE
manually set Button to release or pressed status

### ISSUE THREAD

**Issue by epikao** [lvgl/lvgl#426]
Hello, quickly another question... I've created now a Button Matrix.
Now I want manually set some Buttons to a release or pressed status. How do that?

**Comment by kisvegabor** [comment]
You can toggle only one button at once using: `lv_btnm_set_toggle(btnm, 3)`. It toggles the third button.
Using this function the whole button matrix become "toggle-able". 
Only it is supported right now by the Button matrix. If you need something specific I suggest createing normal buttons.

**Comment by epikao** [comment]
thank you, it works.
lv_btnm_set_toggle(btnm1, 1, 3);
