### ISSUE TITLE
Freeze touch?

### ISSUE THREAD

**Issue by Moo2017** [lvgl/lvgl#432]
Hi All,
I was wondering if there is any way to freeze touch on a specific object ? for example there is a message box with tow options and I want to make user select one of the options otherwise can't select other objects on the screen.

**Comment by PalantirWielder** [comment]
Perhaps you're looking for something similar to what's discussed in issue #401?

**Comment by kisvegabor** [comment]
Have a look at this: https://github.com/littlevgl/lvgl/issues/383 as well.

**Comment by Moo2017** [comment]
Thanks All. I have both hardware keypad and touch, I can't disable click since my application has to work with both hardware keypad and touch pad. If I disable click , I can't select it using hardware keypad, am I right?

**Comment by Moo2017** [comment]
@kisvegabor I have created a list , I added an action to each btn in the list, when user scrolling on the list, btns are clicked and action is run while I don't want that. I need the action be run ( btn call back function) only if user presses that btn and not when scrolling the screen. Do you have any idea or maybe I'm doing something wrong.

**Comment by kisvegabor** [comment]
For "freeze touch" you can use `lv_group_focus_freeze` the prevent focusing to an other object.

The buttons shouldn't call their action when they was scrolled. Please test in the PC simulator. Maybe something is wrong with your input device driver. If it's still not working please open a new issue for it.

**Comment by kisvegabor** [comment]
> Thank you I did that but still I was able to select another object using touch and it worked only for hardware keypad.

Have you checked this?  #383 

> Would you please let me know if long press action works only for touch input or it works for hardware key as well?

Noe only lv_btn uses the long press but it should call the long press action when you press the LV_GROUP_KEY_ENTER long.

**Comment by Moo2017** [comment]
@kisvegabor Thank you , that works , good idea!!!

**Comment by kisvegabor** [comment]
As the issue is solved I close this issue.
