### ISSUE TITLE
Bugs: checkbox & drawing etc.

### ISSUE THREAD

**Issue by turoksama** [lvgl/lvgl#438]
Hi there,
     I modified a theme from "theme_material" and tested with "**lv_test_theme_1(th);**", some bugs appeared as follows:
     1. when setting **style.body.radius=0;** , drawing one dot more in every 90' angle as below:
![default](https://user-images.githubusercontent.com/19869728/46323589-a0df2880-c621-11e8-83b6-2a331f68cc9d.jpg)
I pointed out 2 for example. Both in "pc_simulator" & hardware board.
I tried to fix that but "xxx_design" is more complicated than what i thought to be.
Use an "if" condition before drawing may higher efficiency?
     2.knob in slider: a square will be drawn when **style.body.radius=0;**
I modified these lines in "lv_slider_design()" : line 327-328
```c
if(slider_w >= slider_h)
       {
            if(ext->knob_in == 0) {
                knob_area.x1 = area_indic.x2 - slider_h / **4**;
                knob_area.x2 = knob_area.x1 + slider_h **/2**;
            } else {
                knob_area.x1 = (int32_t) ((int32_t)(slider_w - slider_h) * (cur_value - min_value)) / (max_value - min_value);
                knob_area.x1 += slider->coords.x1;
                knob_area.x2 = knob_area.x1 + slider_h;
            }

            knob_area.y1 = slider->coords.y1;
            knob_area.y2 = slider->coords.y2;
        }
```

 

     3.when i try to merge to beta version, check box error in simulator: wrong size ,no caption and check 
will crash and have no effects after reverting back (ver 5.1.0 is fine before that), acts normal in hardware 
board(5.2.0 beta earlier version about 3-4 months ago)

     4. no effects on tab text font size:
```c
lv_style_t tb;

    lv_theme_set_current(th);
    lv_obj_t *scr = lv_cont_create(NULL, NULL);
    lv_scr_load(scr);
    lv_cont_set_style(scr, th->bg);

   tv = lv_tabview_create(scr, NULL);
   lv_style_copy(&tb, th->tabview.bg);
   tb.text.font = &muli_latin_regular_40;
   lv_tabview_set_style(tv, LV_TABVIEW_STYLE_BG, &tb);
```     
     

![2](https://user-images.githubusercontent.com/19869728/46324392-d7b73d80-c625-11e8-8d7b-23b195747984.jpg)

by the way, my font usage is it a problem?

**Comment by turoksama** [comment]
i don't know why the page looks so messy 

check box is normal when i remove ### **tab text font size** code.

**Comment by kisvegabor** [comment]
Hi,

please put your code blocks between 
` ```c`
code block
` ``` `
tags

**Comment by turoksama** [comment]
@kisvegabor 
Hi, I found that ddlist & list & roller are much alike, commonly an downward arrow on the right by the ddlist, maybe more user friendly? What do you think?

**Comment by kisvegabor** [comment]
Thank you for updating your comment!

1. radius: I fixed it in `dev-5.2` branch. Can you verify if it works well?
2. square knob in slider: yes, the knob can be only square (or circle with LV_RADIUS_CIRCLE radius)
3. crash: your style declaration should be: `static lv_style_t tb;` because only the style pointers are saved.
4. To set the text size on tabs you should set the styles like this:
```c
   /*The released button is transparent so it will inherit the background's style*/
   static lv_style_t tb_bg;
   lv_style_copy(&tb_bg, th->tabview.btn.bg);
   tb_bg.text.font = &muli_latin_regular_40;
   lv_tabview_set_style(tv, LV_TABVIEW_STYLE_BTN_BG, &tb_bg);

   /*The toggled released (active tab) is not transparent. Set it directly*/
   static lv_style_t tb_tgl_rel;
   lv_style_copy(&tb_tgl_rel, th->tabview.btn.tgl_rel);
   tb_tgl_rel.text.font = &muli_latin_regular_40;
   lv_tabview_set_style(tv, LV_TABVIEW_STYLE_BTN_TGL_REL, &tb_tgl_rel);
``` 

I pushed a minor fix to `dev-5.2` related to tabview styling.

5. Yes, an arrow on ddlist would be great. The contribution is welcome.

**Comment by turoksama** [comment]
@kisvegabor 
Thanks a lot for your advise.
First,
We have a major problem here: hardware board have a lot of glitches on the screen with 5.2.0 beta(new architecture on drawing) and is much slower than 5.2.0 beta earlier version. So, i am not sure which file should be replaced to solve the radius problem.
Second,
We have a new situation here:
![3](https://user-images.githubusercontent.com/19869728/46414325-7abaa500-c755-11e8-8a88-bceb7ae6f98d.jpg)
Alignment of labels are not the same when using animation(the containers of labels using "lv_cont_set_layout(t_inf, LV_LAYOUT_ROW_M);" ) :
first one not using long mode.
second one using LV_LABEL_LONG_ROLL long mode.
I think the animation have bugs : perhaps layout style is not inherited? including .padding style
![3](https://user-images.githubusercontent.com/19869728/46414995-ebae8c80-c756-11e8-8992-b1bfe2c2c047.jpg)

**Comment by kisvegabor** [comment]
Hi,

Please update to the `dev-5.2` branch and test with that.

**Comment by kisvegabor** [comment]
If it's not working please provide an example code to test your code.

**Comment by turoksama** [comment]
Thanks for your advise.
We will looking forward to testing the new beta.

**Comment by turoksama** [comment]
@kisvegabor 
Hi,
We update to the latest dev-5.2 branch and test with that, and make efforts to optimize for speed. Alignment of labels are not the same when using animation problem is still there.

[mframe.zip](https://github.com/littlevgl/lvgl/files/2444833/mframe.zip)
regards!

**Comment by kisvegabor** [comment]
Hi,

I checked your code and modified one line to make it work:
```c
lv_obj_set_width(t_inf_label, INFO_LANE_LABEL_W);
```

Originally you set the label and the conatainer height to the same value. The label objcet was really cenered vertically  due to the layout. However, the text always begins at the top of the label.

See the difference:

Your version:
![image](https://user-images.githubusercontent.com/7599318/46518708-e4ca6b80-c875-11e8-9972-9eaf92f2c0ec.png)

My version:
![image](https://user-images.githubusercontent.com/7599318/46518725-00357680-c876-11e8-8f11-97ae3e00dfd3.png)

So I just let the height to set automatically when setting the text with `lv_label_set_text` and later only modifed the width.

**Comment by turoksama** [comment]
Hi,
Your code works fine.Thanks a lot.
Regards!

**Comment by kisvegabor** [comment]
Your welcome!
