### ISSUE TITLE
Where can i get the pc_simulator _5.2

### ISSUE THREAD

**Issue by mianhuacar** [lvgl/lvgl#440]
Hi,

Where can i get the pc_simulator _5.2. I had tried changed pc_simulator _5.1 to pc_simulator _5.2 myself, but fail. After changed, it cannot show png image(convert by lv_utils-dev-5.2) correctly.
I should be
![one_min_release](https://user-images.githubusercontent.com/3974849/46340197-5b454e80-c667-11e8-8c7e-ce281ba7b270.png)
but
![16bit](https://user-images.githubusercontent.com/3974849/46340304-a5c6cb00-c667-11e8-92cf-a5737d225dc3.png)
or
![32bit](https://user-images.githubusercontent.com/3974849/46340309-a9f2e880-c667-11e8-9e8e-3b3f1c309857.png)

Thank you:)

**Comment by turoksama** [comment]
hooray! 5.2 is coming…

**Comment by mianhuacar** [comment]
Hi,
I change #if LV_COLOR_DEPTH == 24 ->#if LV_COLOR_DEPTH == 32, and ok now :)
