### ISSUE TITLE
lv_theme_material_init() not found when compiling

### ISSUE THREAD

**Issue by PalantirWielder** [lvgl/lvgl#444]
Using v5.1.1 of lvgl, every other theme init function was working fine, but lv_theme_material_init() wasn't found.

Traced the problem back to lv_themes/lv_theme.h:
```

/**********************
 *     POST INCLUDE
 *********************/
#include "lv_theme_templ.h"
#include "lv_theme_default.h"
#include "lv_theme_alien.h"
#include "lv_theme_night.h"
#include "lv_theme_zen.h"
#include "lv_theme_mono.h"
```

the addition of `#include "lv_theme_material.h"` resolved the issue

**Comment by PalantirWielder** [comment]
v5.2 has the issue resolved
https://github.com/littlevgl/lvgl/blob/41695bf9ac758ae3276424e06308e1bb89c4c019/lv_themes/lv_theme.h#L302

**Comment by kisvegabor** [comment]
Thank you anyway! :)
