### ISSUE TITLE
Get window from its child

### ISSUE THREAD

**Issue by Moo2017** [lvgl/lvgl#452]
Hi All,
I created a window and then I created a list inside the window and I made the window parent of the list. How can I get the window from list? I tried lv_obj_get_parent(list) but it didn't give me the window object. 
Also I want to know if there is anyway to get window control btn from window object?

**Comment by fallstool** [comment]
Hi， 
current  version you can use **lv_obj_get_parent(lv_obj_get_parent(lv_obj_get_parent(list)))** , is is a bug?
becuse list is a page container ,and page is create by lv_cont_create(), so first call lv_obj_get_parent(list) only give the address of the  lv_cont_create() address.
Here is the test code.
lv_obj_t * win1 = lv_win_create(lv_scr_act(), NULL);
    lv_obj_set_size(win1, LV_HOR_RES / 2 - LV_DPI / 20, LV_VER_RES / 2 - LV_DPI / 20);
    lv_obj_t * list = lv_list_create(win1, NULL);
    lv_list_add(list, SYMBOL_FILE, "File", NULL);
    lv_list_add(list, SYMBOL_DIRECTORY, "Directory", NULL);
    lv_obj_t *win = lv_obj_get_parent(lv_obj_get_parent(lv_obj_get_parent(list)));
    lv_win_set_title(win, "test");

**Comment by Moo2017** [comment]
Hi @fallstool thanks it worked
