### ISSUE TITLE
test lv_test_tabview_1 new program

### ISSUE THREAD

**Issue by chenshijianworkgit** [lvgl/lvgl#456]
Hi,
I found a new little problem，the second button on the first tab is grayed out, but can be dragged to the second button.

**Comment by kisvegabor** [comment]
Hi,

Disabling tabs is not a supported feature. It just remained in the code from a test.

As a workaround, you can disable the sliding of a tab view: `lv_tabview_set_sliding(tabview, false)`

**Comment by chenshijianworkgit** [comment]
Yes, you are right
