### ISSUE TITLE
How can set Label position and size with parent of Page?

### ISSUE THREAD

**Issue by fallstool** [lvgl/lvgl#468]
Hi
When I create label with the page container, can not set the correct postion and size. Is there some wrong with my code? thank you.
Here is the test code:

lv_obj_t * page1 = lv_page_create(lv_scr_act(), NULL);
    lv_page_set_scrl_layout(page1, LV_LAYOUT_OFF);
    lv_obj_set_size(page1, 320, 240);
    lv_obj_t * label = lv_label_create(page1, NULL);
    lv_obj_set_pos(label, 50, 50);
    lv_obj_set_size(label, 150, 50);
    lv_label_set_text(label, "First line of a text\n"
                      "Second line of a text\n"
                      "Third line of a text\n");

**Comment by BrianPugh** [comment]
Do the notes at the bottom of the following link help?

https://littlevgl.com/object-types/page-lv_page

It may have to do with enabling/disabling scrolling with autofit.

**Comment by fallstool** [comment]
Hi @BrianPugh 
I test with     lv_page_set_scrl_fit(page1, false, false);
It is not work for me .

**Comment by kisvegabor** [comment]
Try this:
```c
    lv_obj_t * page1 = lv_page_create(lv_scr_act(), NULL);
    lv_obj_set_size(page1, 320, 240);
    lv_page_set_scrl_fit(page1, false, false);
    lv_page_set_scrl_height(page1, 200);

    lv_obj_t * label = lv_label_create(page1, NULL);
    lv_obj_set_pos(label, 30, 60);
    lv_label_set_text(label, "First line of a text\n"
    "Second line of a text\n"
    "Third line of a text\n");
```

![image](https://user-images.githubusercontent.com/7599318/47601116-0d083e80-d9cc-11e8-99f0-7f97a22c5f87.png)

**Comment by fallstool** [comment]
@kisvegabor thank you.

**Comment by kisvegabor** [comment]
Your welcome!
If it worked please close the issue.
