### ISSUE TITLE
Online Font Converter 

### ISSUE THREAD

**Issue by DeonMarais64** [lvgl/lvgl#470]
Hi Gabor,
I picked up what looks to me like unintended behaviour when using your online font converter.

https://use.fontawesome.com/releases/v5.4.1/fontawesome-free-5.4.1-web.zip

From the link above, fa-solid-900.ttf has glyphs defined from 0xf000 to 0xf7f2f (61440 to 63279) 
However if you put any value larger than 63149 in the upper range then the conversion yields incorrect bitmaps for the glyphs.

I do not know if this is something which only occurs with this particular ttf file or 63149 is an upper limit. 
Thought I would let you know about it.

**Comment by kisvegabor** [comment]
Hi,

There is no upper limit intentionally.  I was able to reproduce the issue but I don't know what causes it. I will check it once I will have some free time. (Probably next week) You can also try to find the issue in the source code: https://github.com/littlevgl/lv_utils/blob/master/font_conv_core.php

**Comment by DeonMarais64** [comment]
Thanks, 
But it is not a problem for me as I do not need any of the glyphs in that range, The main thing was to find the point of failure, once done I just wanted to give a heads up on the behaviour to save anyone else going through the same troubleshooting process.

**Comment by kisvegabor** [comment]
I've checked it again and unfortunately, I think I can't do anything with this because it seems an issue/limitation of PHP functions.

Anyway, thank you for reporting the issue.
