### ISSUE TITLE
lv_img_draw_core line buffer size

### ISSUE THREAD

**Issue by kdkirmse** [lvgl/lvgl#479]
lv_img_draw_core

#if LV_COMPILER_VLA_SUPPORTED
        uint8_t buf[(lv_area_get_width(&mask_com) * (LV_COLOR_SIZE + 1))];
#else

LV_COLOR_SIZE is 8/16/32 in standard build

Line buffer is much bigger then needed,

**Comment by kisvegabor** [comment]
Thank you, fixed!
https://github.com/littlevgl/lvgl/commit/4f11ad7adb8f6abbf9f3a4cb2c6835fb54063405
