### ISSUE TITLE
how to use ttf font?

### ISSUE THREAD

**Issue by baidxi** [lvgl/lvgl#496]
in my project need to display chinese font ,i want to use ttf font for chinese font

**Comment by kisvegabor** [comment]
Just create a C array from the TTF font using: https://littlevgl.com/ttf-font-to-c-array

**Comment by baidxi** [comment]
> Just create a C array from the TTF font using: https://littlevgl.com/ttf-font-to-c-array

no no no ,I'm want use freetype2 library for use ttf font,not create a C array for it.

**Comment by embeddedt** [comment]
In that case you need to create a custom `lv_font_t` structure. See https://github.com/littlevgl/lvgl/issues/107#issuecomment-371821673.

**Comment by embeddedt** [comment]
@baidxi Be warned, however, that this is pretty inefficient on a small embedded system. I don't know what the specs of your system are but I advise you to also look at #473 .

**Comment by kisvegabor** [comment]
As #473 is very similar, let's continue the discussion there.
