### ISSUE TITLE
Suggestion - Whether line meter can support colors and size for a selected portion?

### ISSUE THREAD

**Issue by ajithpv** [lvgl/lvgl#497]
To understand the idea in a better way, I'm using the below image:
![after-effects-round-audio-spectrum](https://user-images.githubusercontent.com/6222267/47649282-ca4c8f00-dba2-11e8-9137-4da02988296c.gif)

I would like to know how to achieve this kind of feature using LittleVGL. I hope using the "[line meter widget](https://littlevgl.com/object-types/line-meter-lv_lmeter)" is close to the solution but, really don't know whether this supports the color and size adjustment to individual blocks or portion of the meter.

It would be good to add this feature to the LittleVGL to enhance the GUI for audio, automotive solutions etc.

**Comment by kisvegabor** [comment]
Hi,

It looks very impressive! However, unfortunately, you can't do it with the line meter. Are you interested in adding this new object type?

**Comment by ajithpv** [comment]
I must say that, I'm new to littlevgl. However, I will definitely give a try.

**Comment by kisvegabor** [comment]
Great! :)

Feel free to ask if you stuck somewhere!
