### ISSUE TITLE
Missing function to reset points in a serie and to remove a serie from a chart

### ISSUE THREAD

**Issue by AloyseTech** [lvgl/lvgl#498]
A function like lv_chart_remove_serie would be useful to remove a serie from a chart. In the same idea, a function to remove the data from a serie would be useful, like lv_serie_remove_reset and/or lv_serie_remove_point( * serie, uint32_t pointIndex). At the moment the only way I found to reset the serie is to set every points to zero, but this lead to unwanted effects.

**Comment by kisvegabor** [comment]
Hi,

It sounds reasonable! A PR is welcome.

> At the moment the only way I found to reset the serie is to set every points to zero, but this lead to unwanted effects.

What "unwanted effects" did you experience?

**Comment by AloyseTech** [comment]
The unwanted effect is that the first line drawn between two point will start at 0. Which will appear as a step on the chart.

![chart_step_response](https://user-images.githubusercontent.com/13847288/47719570-e0625a00-dc4b-11e8-930f-56a82016247f.PNG)

**Comment by AloyseTech** [comment]
See my PR here : #507

**Comment by kisvegabor** [comment]
As the PR is merged I close this issue!

Thank you very much for the contribution!
