### ISSUE TITLE
static inline is not supported by compiler

### ISSUE THREAD

**Issue by hotpeperoncino** [lvgl/lvgl#50]
FYI..
I'm using gcc-arm-none-eabi-6-2017-q2-update/bin/arm-none-eabi-gcc.
It causes  "sorry, unimplemented: Thumb-1 hard-float VFP ABI" message.

**Comment by hotpeperoncino** [comment]
inline is not unrelated. there is another problem.

**Comment by kisvegabor** [comment]
Have you solved it finally? As I googled it, it is not related to littlevgl. Or?

**Comment by hotpeperoncino** [comment]
Hi. it's solved. maybe my dev env is broken. thanks.
