### ISSUE TITLE
bug with VDB allocation

### ISSUE THREAD

**Issue by ImmortalBuka** [lvgl/lvgl#501]
it impossible to define LV_VDB_ADR as variable address.

**Comment by embeddedt** [comment]
See https://github.com/littlevgl/lvgl/blob/04239f92872cfec584af548633f7092488eb8112/lv_conf_templ.h#L47

> LV_VDB_ADR_INV: to replace it later with `lv_vdb_set_adr()`

**Comment by embeddedt** [comment]
You can then use `lv_vdb_set_adr` to set the address as you wish. However I doubt that the VDB address can be changed while the GUI is running.

**Comment by ImmortalBuka** [comment]
thanks.
and one more question
when i tried to place work_mem_int into external RAM, it caused to crash system (stm32f429), but work with internal RAM
what i do change? (LV_MEM_ATTR i'd set __attribute__ ((section (".sdram"))) )

**Comment by kisvegabor** [comment]
`LV_MEM_ATTR` is used only by the array of `lv_mem_alloc` to allocate memory in it.

Try to add `attribute ((section (".sdram"))) )` in `lv_vdb.c` dircetly where `vdb_buf` is declared.

**Comment by ImmortalBuka** [comment]
but in this case lv_mem_alloc returned wrong address (after 5 or 6 execute times).

**Comment by kisvegabor** [comment]
Sorry, I misread it. 
So you would like to move the work memory to SRAM (which is used by `lv_mem_alloc`). I understand now. In this case you really should use `LV_MEM_ATTR`.

To place the work memory to a specific address you need to modify `lv_mem.c`: https://github.com/littlevgl/lvgl/blob/master/lv_misc/lv_mem.c#L82

Replace this line with `work_mem = (uint8_t*)SDRAM_ADDRESS_TO_USE`
You can delete the declaration of `work_mem_int` array.

I didn't test it but is should work.

**Comment by ImmortalBuka** [comment]
It works, thx for help)
