### ISSUE TITLE
Scrollbar is gone?

### ISSUE THREAD

**Issue by turoksama** [lvgl/lvgl#508]
Hi there,
when i modify these lines in lv_style.c :
```
lv_style_scr.body.padding.ver = 0;
lv_style_scr.body.padding.hor = 0;
lv_style_scr.body.padding.inner = 0;
```
scrollbar of list is gone.
what's the problem?

**Comment by fallstool** [comment]
Hi
lv_style_scr.body.padding.inner = 0;
means the the scrollbar width value is 0

**Comment by turoksama** [comment]
hi
yes,indeed.
and i just set sb styles standalone.

**Comment by kisvegabor** [comment]
@turoksama If the issue is solved please close it.
