### ISSUE TITLE
Circular list support

### ISSUE THREAD

**Issue by robertvxt** [lvgl/lvgl#511]
As I have a circular list of options (A,BC,D): D <-> A <-> B <-> C <-> D <-> A
With help from lv_roller, I created a list: A <-> B <-> C <-> D but seems it does not support for circular

Please consult me...

Thanks,
Robert

**Comment by kisvegabor** [comment]
Hi,

I made some experiments to see how complicated it is to improve lv_roller this way. Unfortunately, I found only odd and buggy "solutions". So I'd rather say that lv_roller doesn't support circular scrolling. :(

**Comment by embeddedt** [comment]
This is kind of a hack, but maybe this would work (I haven't tried):

Your current list is: A, B, C, D

1. Make blank items on both ends of the list.
2. When the roller detects that the blank item is selected, it jumps to the opposite end of the list.

**Comment by BrianPugh** [comment]
Here's a hacky solution that I'm currently using:

https://github.com/joltwallet/jolt_gui/blob/esp32/jolt_gui_entry.c#L195

Basically my roller contains the numbers 0-9 three times, and whenever i reach a certain index, I reset the position after the animation takes place. So its a hacky infinite loop that works for me.

**Comment by kisvegabor** [comment]
@embeddedt  I think it won't work properly when you drag fast and a big "drag throw" is applied. In this case, the roller with e.g. 4 items can turn around multiple times. 

@BrianPugh It seems a good solution if you use only buttons a to navigate. I found more difficulties with the handling of animations and dragging.

**Comment by embeddedt** [comment]
@kisvegabor I agree that turnaround could occur multiple times. However, could this be desired behavior?

**Comment by kisvegabor** [comment]
> I agree that turnaround could occur multiple times. However, could this be desired behavior?

I thought the intended behavior is to make the roller "infinite". So the support of multiple turnarounds is critical. Or?

**Comment by embeddedt** [comment]
@kisvegabor Exactly.

>  I think it won't work properly when you drag fast and a big "drag throw" is applied. In this case, the roller with e.g. 4 items can turn around multiple times.

Why wouldn't it work properly if the roller is supposed to be infinite? I think I'm not understanding something.

**Comment by kisvegabor** [comment]
@embeddedt  The roller is like a page with a scrollable part which is not infinite. With a big drag, you can easily reach the top/bottom position. So the roller needs to reposition itself while the drag happens to look like infinite. And this repositioning didn't work well for me.

**Comment by robertvxt** [comment]
Hi,
Thank you all for your attention, I was busy in other stuffs.

I based on @BrianPugh 's idea then it worked properly and of course, I just used buttons to navigation.

**Comment by embeddedt** [comment]
@robertvxt Great to hear that it's working! If the issue is resolved please close it.

**Comment by robertvxt** [comment]
BTW, @embeddedt , I saw for the first display of roller, there are only 2 options which be displayed while 
the visible row count was set upper than 2. i.e. lv_roller_set_visible_row_count(roller, 3);

Can we change to always display row count per setting lv_roller_set_visible_row_count?

**Comment by embeddedt** [comment]
@robertvxt If you adjust the roller size yourself (by disabling `lv_roller_set_hor_fit` and changing the height) I think this behavior might occur. Can you send a code sample so I can reproduce this?

**Comment by robertvxt** [comment]
@embeddedt , we can see easily in https://github.com/littlevgl/lvgl/wiki/Roller

**Comment by embeddedt** [comment]
@robertvxt Whoops, my mistake there. I don't know how I thought that `hor_fit` was related to height. I'll test the roller issue now.

**Comment by embeddedt** [comment]
@robertvxt I tested the roller in the `pc_simulator` and it worked properly. I don't think I can find the issue without more details.

**Comment by robertvxt** [comment]
@embeddedt , Please refer to the attachment, there are only 2 rows:
![roller](https://user-images.githubusercontent.com/5064485/48683905-dfd13980-ebe1-11e8-8103-f5a8908bfa93.PNG)
-> only "Apple" and "Broccoli" displayed. So my question is: can we display 3 row in the initial (first) display of roller (i.e. "**Apple**" and "**Broccoli**" and "**Cabbage**" displayed). I'm not sure this is bug, just clarify the use case!

**Comment by kisvegabor** [comment]
@robertvxt As you can see the height of the roller is set to display 3 rows. But the top row is empty because the roller is not circular and "Apple" is the first element.

To see 3 rows of options you need to select the second element. `lv_roller_set_selected(roller, 1, anim_en)`

**Comment by embeddedt** [comment]
@robertvxt To build on what @kisvegabor said, I believe the selected element will always be in the middle, so it's not possible to see three options and have the first or last element selected.

**Comment by robertvxt** [comment]
Agree, let it be a limitation at this use case
Thanks @kisvegabor  & @embeddedt
