### ISSUE TITLE
How to get & modify the text in button ('s lable) when button action arrived?

### ISSUE THREAD

**Issue by charles-lyc** [lvgl/lvgl#520]
Hi, I create a label obj from a button obj, and it displays well. (The label is "-" or "+")
Then, I add a button action function, which handles all the buttons pressing.
I tried to get the button's label string to detected which button was hit, but how to get this obj's obj's string?
BTW, I think it should be more reasonable to get the obj's ID, is there any ID info in obj's arguments?

**Comment by kisvegabor** [comment]
Hi,

To set an ID you can use `lv_obj_set_free_num(btn, 1 or -1)` and then in the action function `if(lv_obj_get_free_num(btn) < 0) {...} else {...}`

**Comment by embeddedt** [comment]
I forgot about `lv_obj_set_free_num`. Much simpler!

**Comment by turoksama** [comment]
@kisvegabor Hi, if it is a button matix object, how to set IDs for the matrix?

**Comment by charles-lyc** [comment]
@kisvegabor Yes, I just found that also.
Then, is that possible to get the text above the button?  That means getting the button's label's text.

**Comment by kisvegabor** [comment]
@turoksama `lv_obj_set/get_free_num` works for every object type. But not for the buttons of the button matrix individually because they are not real, unique objects. They are just drawn.

@YipCharles 
Try:
```c
    lv_obj_t * label = lv_obj_get_child(btn, NULL);
    const char * txt = lv_label_get_text(label);
```

**Comment by charles-lyc** [comment]
@kisvegabor 
Got it, and if I need to access it in button action, I have to lv_obj_set_free_num() from the button to the label before, then use this free num as the label handler in button action callback. 
Thanks! This q can be closed.
