### ISSUE TITLE
 Calendar font setting problem

### ISSUE THREAD

**Issue by qwert1213131** [lvgl/lvgl#524]
The default font of the system is lv_font_dejavu_30. When the style part is set to lv_font_dejavu_20, an exception is displayed.
Can you check it out for me? Thank you！

![tim 20181105104645](https://user-images.githubusercontent.com/3905169/47975288-2bff8280-e0e8-11e8-970d-4c8cc221fc98.png)
![tim 20181105104700](https://user-images.githubusercontent.com/3905169/47975294-302ba000-e0e8-11e8-9dcd-68e5066c723d.png)

@kisvegabor

**Comment by turoksama** [comment]
[](https://github.com/littlevgl/lvgl/wiki/Calendar)   may help.

**Comment by turoksama** [comment]
[https://github.com/littlevgl/lvgl/wiki/Calendar](url) may help.

**Comment by kisvegabor** [comment]
@turoksama 
I don't know why but your link to the documentation shows the issues page. Although the link seems correct.

Maybe this?
https://github.com/littlevgl/lvgl/wiki/Calendar

EDIT:
I check your post in plain text and you used the link like this: `[https://github.com/littlevgl/lvgl/wiki/Calendar](url)`

But it works like to opposite: `[url](https://github.com/littlevgl/lvgl/wiki/Calendar)`
[url](https://github.com/littlevgl/lvgl/wiki/Calendar)

**Comment by qwert1213131** [comment]
@kisvegabor @turoksama
I am using the release 5.2-rc version and the calendar font cannot be set successfully.
  calendar = lv_calendar_create(scr,NULL);

/*Create a style for the current week*/
static lv_style_t style_week_box;
lv_style_copy(&style_week_box, &lv_style_plain);
style_week_box.body.border.width = 1;
style_week_box.body.border.color = LV_COLOR_HEX3(0x333);
style_week_box.body.empty = 1;
style_week_box.body.radius = LV_RADIUS_CIRCLE;
style_week_box.body.padding.ver = 3;
style_week_box.body.padding.hor = 3;
style_week_box.text.font = &lv_font_dejavu_10;

/*Create a style for today*/
static lv_style_t style_today_box;
lv_style_copy(&style_today_box, &lv_style_plain);
style_today_box.body.border.width = 2;
style_today_box.body.border.color = LV_COLOR_NAVY;
style_today_box.body.empty = 1;
style_today_box.body.radius = LV_RADIUS_CIRCLE;
style_today_box.body.padding.ver = 3;
style_today_box.body.padding.hor = 3;
style_today_box.text.color= LV_COLOR_BLUE;
style_today_box.text.font = &lv_font_dejavu_10;

/*Create a style for the highlighted days*/
static lv_style_t style_highlighted_day;
lv_style_copy(&style_highlighted_day, &lv_style_plain);
style_highlighted_day.body.border.width = 2;
style_highlighted_day.body.border.color = LV_COLOR_NAVY;
style_highlighted_day.body.empty = 1;
style_highlighted_day.body.radius = LV_RADIUS_CIRCLE;
style_highlighted_day.body.padding.ver = 3;
style_highlighted_day.body.padding.hor = 3;
style_highlighted_day.text.color= LV_COLOR_BLUE;
style_highlighted_day.text.font = &lv_font_dejavu_10;

/*Apply the styles*/
lv_calendar_set_style(calendar, LV_CALENDAR_STYLE_WEEK_BOX, &style_week_box);
lv_calendar_set_style(calendar, LV_CALENDAR_STYLE_TODAY_BOX, &style_today_box);
lv_calendar_set_style(calendar, LV_CALENDAR_STYLE_HIGHLIGHTED_DAYS, &style_highlighted_day);

**Comment by turoksama** [comment]
@kisvegabor 
i don't know why neither, cursor moved to the middle of () automatically.😅

**Comment by turoksama** [comment]
maybe you would like to try this out too: 
LV_CALENDAR_STYLE_INACTIVE_DAYS text properties are used to adjust the style of the visible days of previous/next month.

**Comment by qwert1213131** [comment]
@turoksama
Thank you!
Already working fine.
This error is caused by forgetting to set other style types.
