### ISSUE TITLE
Disable specific indev temporarly

### ISSUE THREAD

**Issue by AloyseTech** [lvgl/lvgl#528]
Hi,

There is already a way to enable/disable a given type of input device. However, it could be interesting to be able to enable/disable specific input device whatever their type.
The existing API is confusing : lv_indev_enable is used to enable/disable device by type.
Maybe it should be changed to lv_indev_enable_type and lv_indev_enable could be used to disable a given input device.

**Comment by embeddedt** [comment]
@AloyseTech Such a change would have to be guarded by a macro for backwards compatibility.

**Comment by AloyseTech** [comment]
Yes, or it could only make it on 6.0.0. But it seems to be a feature that could be useful before the next major version is available

**Comment by embeddedt** [comment]
As per https://github.com/littlevgl/lvgl/issues/543#issuecomment-438566272 the `dev-6.0` branch was removed. Please use `#if LV_API_V6` to guard API-breaking changes.

**Comment by kisvegabor** [comment]
In `dev-6.0` I'll change `lv_indev_enable` to disable/enable an input device instead of a type.

**Comment by kisvegabor** [comment]
Added in `dev-6.0`.
If you have come comments feel free to add them here and reopen this issue.
