### ISSUE TITLE
build on win pc_simulator err

### ISSUE THREAD

**Issue by helezh** [lvgl/lvgl#53]
i using qt_mingw build err,and correct "int main(viod)"to "int winmain(int a,char *arg)" build ok and runing ok!

**Comment by kisvegabor** [comment]
Hi,
Thanks!

It is specific to *qt_mingw* that you need to use *winmain* instead of *main* ?

**Comment by helezh** [comment]
qt used cygwin gcc

**Comment by kisvegabor** [comment]
And in other applications you also have to use winmain instead of main ?

**Comment by helezh** [comment]
yes ,i pragraming pc-soft on win,the entry is winmain.now i have new problem,that is i used your lv-utils the    "fnt2c.py",but get many err.
"D:\Users\Administrator\Desktop\N3290x\lv_proj_pc_v4_2_0\lv_utils-master>python f
nt2c.py -f cjk -o cjko >ii
Traceback (most recent call last):
  File "fnt2c.py", line 444, in <module>
    main(sys.argv[1:])
  File "fnt2c.py", line 440, in main
    processConfig(conf)
  File "fnt2c.py", line 371, in processConfig
    source += makeFontSource(conf);
  File "fnt2c.py", line 326, in makeFontSource
    img, glyphs = loadFont(config)
  File "fnt2c.py", line 290, in loadFont
    font = minidom.parse(config.input_file)
  File "D:\Python27\lib\xml\dom\minidom.py", line 1918, in parse
    return expatbuilder.parse(file)
  File "D:\Python27\lib\xml\dom\expatbuilder.py", line 924, in parse
    result = builder.parseFile(fp)
  File "D:\Python27\lib\xml\dom\expatbuilder.py", line 207, in parseFile
    parser.Parse(buffer, 0)
xml.parsers.expat.ExpatError: not well-formed (invalid token): line 3, column 14
"

**Comment by helezh** [comment]
i have sloved the problem,that is save as the *.fnt file to new *,fnt files(utf8 format, linux dont have the problem)

**Comment by helezh** [comment]
using the fnt2c must install python27 pip pillow dom to support

**Comment by helezh** [comment]
a new suggestion,many cjk fonts is NxN square,the "static const uint8_t cjko_width[] =  32,............." can not do this!

**Comment by helezh** [comment]
here is chinese,example "你好！"

**Comment by kisvegabor** [comment]
Hi,
thank you for the suggestions!

It means the max width (255) is not enough for CJK characters?

**Comment by kisvegabor** [comment]
Or the width table is not required because all characters have the same width?

**Comment by helezh** [comment]
yes,all the cjk character have the same height and width,the width table is not required! and all of cjk symbol much as 20,000 symbols! and the lv_utils can not conv cjk_0.png+cjk_1.png+cjk_2.png+cjk_3.png+cjk_4.png

**Comment by helezh** [comment]
here is the files!

**Comment by helezh** [comment]
cjk symbols unicode  0x4e00 to 0x9fbb is the base symbols

**Comment by kisvegabor** [comment]
I see. You can increase the texture size in bmfont/export options to get 1 file.

**Comment by kisvegabor** [comment]
As this issue already contains a lot of different topics I close it now.
If you have any new questions or ideas just open a new issue!
Thank you!
