### ISSUE TITLE
Typo causing compile error

### ISSUE THREAD

**Issue by kaythe** [lvgl/lvgl#530]
Hi,

I've noticed that commit d86f8a898110dac0f2c3ecc9b8cb280c364b7c8e introduced a typo (missing semicolon in lv_objx/lv_ta.c at line 768) which causes a compiler error.

**Comment by embeddedt** [comment]
@stheil Looks like that slipped through from @C47D's work fixing compiler errors. I've made a pull request that should fix this.

**Comment by C47D** [comment]
My bad, thanks @embeddedt for the fix.

**Comment by kisvegabor** [comment]
Merged, thank you!
