### ISSUE TITLE
[suggestion]  Whether to consider adding a T-9 input keyboard in lv_kb ？

### ISSUE THREAD

**Issue by qwert1213131** [lvgl/lvgl#534]
@kisvegabor
it is friendly to small touch screens.
![cgmnilbxesiabx8laahzpj3r-ru698](https://user-images.githubusercontent.com/3905169/48042538-e82a7d00-e1bc-11e8-9756-67e0745b88b7.png)

**Comment by embeddedt** [comment]
Probably the simplest logical method to achieve this would be to get a long press action (without repeat) from `lv_btnm`, then in that action function create another `lv_btnm` object with the options.

This would only work, however, if LittlevGL's button matrix lets you slide over buttons to choose one.

**Comment by simonchen007** [comment]
@qwert1213131 
have you done that ?

**Comment by kisvegabor** [comment]
@simonchen007 
You can also open a topic in the Forum in "Feature request" category:
https://forum.littlevgl.com/c/feature-request

**Comment by simonchen007** [comment]
@kisvegabor 

![kb_t9](https://user-images.githubusercontent.com/24845666/80301911-6c215c00-87d9-11ea-92b1-e21e7ee720f7.png)


I have finish that type of keyboard, is that possible to add it into the main lib ?
if yes, I can share the code here.

**Comment by kisvegabor** [comment]
@simonchen007 
> I have finish that type of keyboard, is that possible to add it into the main lib ?

Yes, but probably we'd have some comments so I suggest opening an issue to discuss the details.
