### ISSUE TITLE
Touch callibrate

### ISSUE THREAD

**Issue by yennhan1211** [lvgl/lvgl#536]
Hello,

Firstly I want to say thanks. This is very interesting project.

I would like to ask that there is any support about touch calibrate. How can I read the raw value from touch sensor?

**Comment by embeddedt** [comment]
There is an example touch calibration app available.

https://github.com/littlevgl/lv_examples/tree/master/lv_apps/tpcal

There are some comments in it that can help to find the calibration offsets:

https://github.com/littlevgl/lv_examples/blob/088c9db7680764c9a8c9fdd40d0854968c64bd73/lv_apps/tpcal/tpcal.c#L349

**Comment by yennhan1211** [comment]
Thanks for your relpy @embeddedt
