### ISSUE TITLE
Recolor question

### ISSUE THREAD

**Issue by chenshijianworkgit** [lvgl/lvgl#538]
Hi，
I don't know if this is a problem. After clicking the recolor wallpaper, the brushing time increases a lot.

I am driving the 800*480 screen of the mpu interface under STM32H743, the normal loading screen is 9.2ms, the screen with wallpaper is 12.6ms, and the wallpaper recolor is 62.4ms.

I am running the official benchmark_create routine

![20181108103859](https://user-images.githubusercontent.com/21272962/48174919-cd831000-e344-11e8-9eeb-fe77ace2846a.jpg)

![20181108103907](https://user-images.githubusercontent.com/21272962/48174926-d70c7800-e344-11e8-9bb4-4914011a28c6.jpg)

![20181108103918](https://user-images.githubusercontent.com/21272962/48174948-e5f32a80-e344-11e8-8e0a-5c1fdc93dc45.jpg)

**Comment by AloyseTech** [comment]
I think this is normal since the recolor takes time. It is a per pixel process IFAIK handled by the CPU. So it should take around `800*480*[instructions per pixel recolor]/[instruction per seconds]` seconds to recolor the screen. Which is around 45ms for the STMH7 with 856DMIPS at 400MHz if we estimate 100 instruction for recoloring a pixel: `800*480*100/856000000 = 45ms`.

See here the recolor code section : https://github.com/littlevgl/lvgl/blob/master/lv_draw/lv_draw_vbasic.c#L473

**Comment by AloyseTech** [comment]
This was a rough estimation. The actual instruction count could be analyzed with a disassembly of the function.

**Comment by embeddedt** [comment]
STM32F746G-DISCO with Cortex-M7, compiled with GCC 7.3.1 and full optimization.

- 326 bytes of code
- Most instructions were 2 bytes with some being 4 bytes so I used an average instruction size of `2.4`
- roughly 136 instructions

Haven't actually done any performance testing but those are the stats from my disassembly.

**Comment by kisvegabor** [comment]
The target of the image recolor features is the small icons. For example, if you have a green pipe icon, you can add a little black to it when it pressed. The drawing of small icons should be fast. So it's not a real-life scenario to recolor the whole background.

Anyway, I can imagine 100 instructions. If recolor is not used then the image's pixels are copied with `memcpy` line by line. It is very fast. 
In the case of recolor, every pixel needs to check one-by-one. If the image has:
- alpha channel
- chroma key
- recolor
the same routine is used.  Although the alpha channel and chrome key calculations are skipped if they are not present in the image (and they are not present on the benchmark's background) it takes some time to check the flags.

We could achieve a minor speed up to check only what is really required but it would result in 8 algorithms. For example, we would need a separate algorithm for:
- chrome key: no
- alpha channel: yes
- recolor: yes
 
And it would break the simplicity, clearance and maintainability for a minor speed up.

**Comment by embeddedt** [comment]
@kisvegabor I don't think it's worth it to split the algorithm in this way. I doubt the overhead is very much especially with all the optimization GCC can do.

**Comment by kisvegabor** [comment]
@embeddedt I agree.

**Comment by embeddedt** [comment]
@chenshijianworkgit Glad to help! If this issue is solved please close it.

**Comment by chenshijianworkgit** [comment]
@embeddedt 
The questions are let to kissvegabor to close, forming a closed loop. 
Or let him see if there is any possibility of optimization.

**Comment by kisvegabor** [comment]
IMO the current implementation has a good balance between complexity and optimization.
Anyway, this examination was interesting to see what is really happening in assembly level.
