### ISSUE TITLE
Has any low level interface in this LIB?

### ISSUE THREAD

**Issue by charles-lyc** [lvgl/lvgl#54]
LittlevGL is nice.
I figured it using some object drawing interface, but when I wana just draw a simple line or rectangle or just for testing the hardware, the Lib just stop in lv_refr_areas(), seems like I should enbale the area firstly?

**Comment by kisvegabor** [comment]
Hi!

Maybe you know that there are two drawing methods: buffered and unbuffered. Learn more here: http://www.gl.littlev.hu/basics#drawing-and-rendering

In buffered mode (LV_VDB_SIZE > 0) you can't draw to the display directly because the buffering is controlled by the library.

In unbuffered mode (LV_VDB_SIZE == 0) you can draw to the display directly but your drawing might be "overdrawn"  when a refresh occurs.

I recommend rather to create and `lv_line` object to draw a line, or an `lv_obj` to create a simple rectangle.

In general lvgl not thinking in drawing (from the user side) but thinking in graphical objects. This way the library will know the graphical objects and can draw them correctly.

**Comment by charles-lyc** [comment]
That means I can create anything I want after create a object? (Such as an oscilloscope or a multi-meter.)

**Comment by kisvegabor** [comment]
For an oscilloscope you can create a line object or a chart and set the point's values. See http://www.gl.littlev.hu/object-types

**Comment by charles-lyc** [comment]
Yep, I know that.
But if I want to redesign my oscilloscope, (will be more complex) , how?

**Comment by kisvegabor** [comment]
If you mean you would like to add e.g. Volt/div or trigger mode just create drop down lists for them or for AC/DC coupling create button.

**Comment by charles-lyc** [comment]
Well, I mean there are lot of point and line, that I have to draw directly into the background, and the style just diff from LVGL, how about that?

**Comment by kisvegabor** [comment]
I just don't understand why would you like to draw directly to the background. Please tell a little bit more details about your goals.

What kind of style do you need? Please tell it too.

**Comment by charles-lyc** [comment]
Well, for an example, I saw an Agilent Oscilloscope, I want to design like that. There are some dash line to  mark or measuring, some curve to display the FFT effect, such like those.

**Comment by kisvegabor** [comment]
Well, actually dash line is not supported now but maybe it will in a next release. Or check http://gl.littlev.hu/services to request a new feature or use thin line instead.
But for FFT a chart can be used very well. And the whole GUI of an Agilent oscilloscope can be built from objects. It's much simpler then just drawing. E.g. just create a chart or button and the library will draw or redraw it when it is required. You just need to set the chart's data or a button's click action (a function to call when clicked).

**Comment by charles-lyc** [comment]
Ok. That will be more efficient.  : P
But what if I, whatsoever, want to have my own design object, (I just found "lv_objx_templ.c") Is that right to modify it?

**Comment by kisvegabor** [comment]
Then you have two options:
1. Use lv_objx_templ but copy it like lv_myobj
2. Set a new design function for an object: lv_obj_set_design_func(line1, my_func)

Are you familiar with styles? You can modify the appearances with them.

**Comment by kisvegabor** [comment]
Sorry, closed by mistake :)

**Comment by charles-lyc** [comment]
Fine. 
Well, that will be more expansible.

**Comment by kisvegabor** [comment]
How do you mean?

I forget to say that I recommend the using of styles because they are created for users. The new object type and design function are more complicated and kind of hacks

**Comment by charles-lyc** [comment]
Yes, I know that will be better. I will prior use the objects existing.

BTW, what does "LV_MISC" means?

**Comment by kisvegabor** [comment]
Lv_misc contains  not graphics but general stuffs like memory management,  task handling etc.

**Comment by charles-lyc** [comment]
It seems like a little bit heavy? I just undefined most of objects, anti-aliasing, shadow, but still cost a lot of time to compile and download the firmware. 
Do you have any idea?

**Comment by charles-lyc** [comment]
The flash size I will check latter, not small.

**Comment by charles-lyc** [comment]
For about 130K extra more with LVGL...

**Comment by kisvegabor** [comment]
Have you disabled the unused fonts?

**Comment by charles-lyc** [comment]
I dis the used 40 Fonts, works, thanks.
BTW, it support UTF-8 encode, so does it mean I can display any language I want on the earth?

**Comment by kisvegabor** [comment]
Basically yes. There are some "tricky" languages like Arabic or Thai which needs some things but e.g Chinease, Korean, Greek, Cyrillic etc is fully supported.

Read this to learn how the fonts work: 
http://www.gl.littlev.hu/basics#fonts

And this to see how ta add a new font:
http://www.gl.littlev.hu/font-converter

**Comment by kisvegabor** [comment]
As a lot of question is answered here and we are far from the original question I close this issue.
