### ISSUE TITLE
offline image converter bugs

### ISSUE THREAD

**Issue by nacyzhouw** [lvgl/lvgl#541]
Hi,
   Recently I used the offline image converter, and I found some bugs.
1. when image cf equal to alpha, no output file is generated. And there is no warining or error.
  php img_conv_core.php "name=icon&img=bunny.png&format=c_array&cf=alpha"

2. cannot convert jpg image, there is error:
PHP Fatal error:  Uncaught Error: Call to undefined function imagecreatefromjpeg() in /GUI/lv_utils-master/lv_utils-master/img_conv_core.php:68
Stack trace:
#0 /GUI/lv_utils-master/lv_utils-master/img_conv_core.php(671): Converter->__construct('earthtest.jpg', 'earthtest.jpg', 'earthtest', 'enabled')
#1 {main}
  thrown in /GUI/lv_utils-master/lv_utils-master/img_conv_core.php on line 68

3.sometime cannot convert png image correctly.
before convert: 
![image](https://user-images.githubusercontent.com/44309825/48239794-4351af00-e40b-11e8-813c-ee167fac4a8e.png)
after convert:
![image](https://user-images.githubusercontent.com/44309825/48239913-af341780-e40b-11e8-8966-9386c559bdda.png)

**Comment by nacyzhouw** [comment]
Hi,

Using the online converter, there are no the first and sencond bugs mentioned above. But when the cf=LV_IMG_CF_TRUE_COLOR_CHROMA_KEYED, the image also cannot convert correctly, as mention in the third bug.
I really hope the bugs of the offline image converter can be fixed soon.

**Comment by kisvegabor** [comment]
@nacyzhouw 
I've checked the issues:

1. It was a typo in the readme. I replaced `alpha` with `true_color_alpha`
2. `imagecreatefromjpeg` was working for me with `PHP 7.0.30`.  According to [its documentation](http://php.net/manual/en/function.imagecreatefromjpeg.php) this function exists since PHP 4
3. I've downloaded your battery icon and it worked correctly for me with `LV_IMG_CF_TRUE_COLOR_CHROMA_KEYED`.  See this: [battest.c.txt](https://github.com/littlevgl/lvgl/files/2729978/battest.c.txt)

**Comment by nacyzhouw** [comment]
@kisvegabor 
I found the background of the downloaded battery icon  opaque, which can be worked correctly.
But when the background of PNG image is transparent, it can't convert correctly.

**Comment by kisvegabor** [comment]
Did you use `LV_IMG_CF_TRUE_COLOR_ALPHA`?

**Comment by nacyzhouw** [comment]
I used LV_IMG_CF_TRUE_COLOR_CHROMA_KEYED

**Comment by kisvegabor** [comment]
And is it working with LV_IMG_CF_TRUE_COLOR_ALPHA?

**Comment by nacyzhouw** [comment]
It isn't work with LV_IMG_CF_TRUE_COLOR_ALPHA  also.

**Comment by kisvegabor** [comment]
Please send:
- a test image 
- screenshot about with your settings
- an test C program you used to display the image

**Comment by nacyzhouw** [comment]
![A011_016](https://user-images.githubusercontent.com/44309825/54996362-0ece4080-5004-11e9-806d-849e45f9da85.png)

**Comment by nacyzhouw** [comment]
I am sorry for decribing the question unclearly , and  the  test C program cannot be uploaded successfully.

- You can try this test image .
![A011_016](https://user-images.githubusercontent.com/44309825/54996828-48ec1200-5005-11e9-97ac-ee1a31f83053.png)

- My settings about  Color and Graphics :
![image](https://user-images.githubusercontent.com/44309825/54997715-4be80200-5007-11e9-9850-db21d8c8bf95.png)

**Comment by embeddedt** [comment]
@nacyzhouw If uploading isn't working you can copy and paste the C program into the post.

**Comment by nacyzhouw** [comment]
test

**Comment by nacyzhouw** [comment]
test

**Comment by nacyzhouw** [comment]
@embeddedt I try but it still don't work, maybe so many words cannot support to post

**Comment by kisvegabor** [comment]
Your image had "indexed color profile'. I've changed it to "RGB "in GIMP (Image->Mode->RGB) and now it works.
![sun](https://user-images.githubusercontent.com/7599318/55131350-9ad48b00-511e-11e9-862f-3dba4f201989.png)

**Comment by nacyzhouw** [comment]
Oh，I see.  Thank you very much for your answer!

**Comment by nacyzhouw** [comment]
@kisvegabor  I am sorry for that I still has the similar problem. This PNG image is  RGB fomat, but it still cannot convert rightly. It seem the alpha cannot work.
![heart_test2](https://user-images.githubusercontent.com/44309825/55399921-084d4500-557f-11e9-92bf-2b0af0a676df.png)
