### ISSUE TITLE
Animations on switch control

### ISSUE THREAD

**Issue by embeddedt** [lvgl/lvgl#549]
I'm interested in adding animation to the switch control, somewhat like what you see in this picture.

![kcod](https://user-images.githubusercontent.com/42941056/48426240-5d093400-e734-11e8-9ca3-5dcdfd7bf715.gif)

Would this be a viable feature for `dev-5.3`?

**Comment by kisvegabor** [comment]
Absolutely yes! It looks great!

**Comment by embeddedt** [comment]
@kisvegabor Great! Should I make it an option or just overwrite the existing code?

**Comment by kisvegabor** [comment]
@embeddedt  I usually use an `uint16_t anim_time` variable in `lv_..._ext_t` structure. This way the user can set the `anim_time` to zero to disable this feature.

**Comment by embeddedt** [comment]
@kisvegabor Ok. I'll make a pull request and begin working on this feature right now.

**Comment by embeddedt** [comment]
The discussion will continue in #553.
