### ISSUE TITLE
LVGL : image zoom in & out

### ISSUE THREAD

**Issue by emiem69** [lvgl/lvgl#551]
hi. i use LVGL library .is there any way to zoom in and out on an image.(when i change size of image container , the size of it's image is constant and add an array of that image inside it.) i want to zoom on image itself.

**Comment by embeddedt** [comment]
@emiem69 Unfortunately, LittlevGL does not support image scaling at this time.

This is a workaround, but maybe you could use multiple images of different sizes to give a similar effect in your application?
