### ISSUE TITLE
RGB LED controller GUI

### ISSUE THREAD

**Issue by InfiniteYuan** [lvgl/lvgl#564]
How long does littlevgl provide RGB color rings?

**Comment by AloyseTech** [comment]
I'm working on a colorpicker : 
![lv_colorpicker](https://user-images.githubusercontent.com/13847288/48706413-80345780-ebfc-11e8-91a2-fb32a939a139.PNG)

**Comment by AloyseTech** [comment]
See PR #565 for status.

**Comment by InfiniteYuan** [comment]
OK, Thank you.

**Comment by kisvegabor** [comment]
Let's continue the discussion in the PR.
