### ISSUE TITLE
Feature request: RTL support

### ISSUE THREAD

**Issue by amirgon** [lvgl/lvgl#566]
RTL (Right To Left) support is required for languages such as Hebrew, Arabic, Persian, Urdu and others which are written from right to left and aligned to the right.  
RTL languages cover over a billion people overall.  

What does it take to add RTL support to lvgl?

**Comment by kisvegabor** [comment]
Your question is just came in the perfect time. We just received a PR with this improvement:  https://github.com/littlevgl/lvgl/pull/559

Please test it and continue the discussion there!
