### ISSUE TITLE
Is there any checkbox objects?

### ISSUE THREAD

**Issue by charles-lyc** [lvgl/lvgl#57]
And, can we just change the button object item's background to a image?

**Comment by kisvegabor** [comment]
Yes, it is. You find all the object types here: https://littlevgl.com/object-types

There is no option to set an image as button's background. You can create a button and an image on it. 
It looks a useful feature! I will add this option in the next release.

**Comment by charles-lyc** [comment]
Yep, I mean, drawing a button by some lines and curves was good, but some times putting 2 pic on it (another for pressed status) will be easier and redesignable, making it possible to change the button looking on different modes.

**Comment by kisvegabor** [comment]
I will add this feature in the next release. A good name could be `lv_icon`. It is a clickable image with 2 image sources: one for released one for pressed

**Comment by kisvegabor** [comment]
The idea of lv_icon  was also mentioned in #144.
It will added in an upcoming release.
