### ISSUE TITLE
This GUI library is very cool, I hope you can continue to update

### ISSUE THREAD

**Issue by jason-sophia** [lvgl/lvgl#58]
thank you very much for sharing your code

**Comment by kisvegabor** [comment]
Hi,
thank you very much. I'm glad to hear that you like it!

Maybe you know there is a Donation opportunity on https://littlevgl.com 
Even a few dollars could help to buy new dev boards to test and extend the library and bring new feature for you!

**Comment by jason-sophia** [comment]
OK，I will certainly make a donation, but first I have to apply for a visa or Matercard

**Comment by kisvegabor** [comment]
Thank you in advance!

You just need a PayPal account. If you don't have an appropriate credit card  a friend or family member can send money there. 
Having a PayPal account is cool thing anyway to order from Ebay, Amazon etc.

**Comment by jason-sophia** [comment]
OK

**Comment by jason-sophia** [comment]
@kisvegabor I have made a donation, have you got it?

**Comment by kisvegabor** [comment]
Hi,
I got a Donation from HO KIT MING. Was it you?

**Comment by jason-sophia** [comment]
@kisvegabor Yes, she is my friend

**Comment by kisvegabor** [comment]
@jason-sophia Thank you very mush then! I also wrote an e-mail to her to say thank you!
Now you are listed here: https://littlevgl.com/donors
If you want I can change the name.

**Comment by kisvegabor** [comment]
I close this thread to keep the list of issues clear!

Thank you very much for the support!
