### ISSUE TITLE
Drag window using titlebar

### ISSUE THREAD

**Issue by embeddedt** [lvgl/lvgl#583]
Hi,

I'm wondering if LittlevGL can support dragging the `lv_win` objects on the screen like a standard desktop environment. I tried using `lv_obj_set_drag` and `lv_obj_set_drag_parent` in various places but I had no success.

**Comment by kisvegabor** [comment]
Hi,

It worked me like this:
```c
    lv_obj_t * win = lv_win_create(lv_scr_act(), NULL);
    lv_obj_t * win_header = ((lv_win_ext_t*) win->ext_attr)->header;
    lv_obj_set_drag_parent(win_header, true);
    lv_obj_set_drag(win, true);
    lv_win_set_style(win, LV_WIN_STYLE_CONTENT_BG, &lv_style_pretty);
```

So when you set `drag_parent` then the parent's drag property will be taken into account.

**Comment by embeddedt** [comment]
@kisvegabor Thanks! That worked perfectly. Would you like me to add an API that handles this transparently so the user does not need to access `lv_win_ext_t` themselves?

**Comment by kisvegabor** [comment]
@embeddedt That would be great! Thank you!

**Comment by embeddedt** [comment]
@kisvegabor See #586.
