### ISSUE TITLE
Compile warning

### ISSUE THREAD

**Issue by chaos4284** [lvgl/lvgl#595]
I am porting in raspbian. 
I got the following warning during compilation:
lvgl/lv_misc/lv_mem.h:37:20: warning: "__ppc64__" is not defined [-Wundef] # if __x86_64__ || __ppc64__
How can I solve the above problem?

**Comment by kisvegabor** [comment]
Hi,

Changing that line to `# if defined(__x86_64__) || defined(__ppc64__)` solves the issue?

**Comment by chaos4284** [comment]
Yes, I've solved the above issue. Thank you.
