### ISSUE TITLE
[Help]Besides of LvGL: Struct member naming conflict?

### ISSUE THREAD

**Issue by turoksama** [lvgl/lvgl#602]
Hi,
 I have a little bit confused about a struct member naming conflit(i think so).
Recently, I defined a struct that looks like this:
```
typedef struct
{
	struct
	{
		struct
		{
			lv_obj_t *tabv;			//Tabview
			lv_obj_t *kb;			//Keyboard
			lv_obj_t *ta;			//Text area
			lv_obj_t *cur_obj;
			lv_obj_t *list;		//List obj, !!!Strange behavior!!!: conflict with "lv_obj_t *list"
			lv_obj_t *item_sel;	//Selected item of the list
		} obj;    	//System params objects

		lv_obj_t *abs;
	}sp;
	lv_obj_t *list;			//List obj2
	lv_obj_t *item_sel;		//Selected item of the list
} MFX_CONFIG;
```

if defined a struct variable ```MFX_CONFIG mfx;```
And found:
**mfx.sp.obj.list is conflict with mfx.list**

After changing definition of the struct to a different name:

```
typedef struct
{
	struct
	{
		struct
		{
			lv_obj_t *tabv;			//Tabview
			lv_obj_t *kb;			//Keyboard
			lv_obj_t *ta;			//Text area
			lv_obj_t *cur_obj;
			lv_obj_t *list_usr;		//List obj1
			lv_obj_t *item_sel_usr;	//Selected item of the list
		} obj;    	//System params objects

		lv_obj_t *abs;
	}sp;
	lv_obj_t *list;			//List obj2
	lv_obj_t *item_sel;		//Selected item of the list
} MFX_CONFIG;
```
No conflicts.
**SUPER EMBARRASSING**: What is going on?

**Comment by kisvegabor** [comment]
It compiles for me without error (gcc). I think it's a compiler specific if it could handle nested structures with the same name.

I also found this: https://stackoverflow.com/questions/13242401/a-reused-named-struct-as-a-nested-struct-triggers-a-redefinition-error-in-gcc

**Comment by turoksama** [comment]
Hi,
Thanks for your test & suggestion.
It compiles without any error(gcc), but it can't be located correctly.
In my work:
```
...
mfx_cfg.sp.obj.list = lv_list_create(cont_usr, NULL);
...
```
The list will be created and works fine except ```mfx_cfg.sp.obj.list```
When I put a value to  ```mfx_cfg.sp.obj.list``` manually, and  ```mfx_cfg.list``` will change to that value at the same time, it looks that they are the same one.

![default](https://user-images.githubusercontent.com/19869728/49341517-5a419500-f689-11e8-9a42-f592af1d96d0.jpg)

**Comment by kisvegabor** [comment]
It's interesting. I also didn't know about it. According to the stackoverflow link above, C doesn't support namespaces so the two `list` are the same somehow. Anyway, I think we can't do anything with it as it's a limitation of C.

**Comment by turoksama** [comment]
U'r right. Changing that name in nested structure should be fine.
