### ISSUE TITLE
How to update interface data in real time?

### ISSUE THREAD

**Issue by as564335sa** [lvgl/lvgl#608]
Hi:
 How can i update the interface data in real time? I created a task for a second, but the data couldn't change in time，Do you have any good idea?

**Comment by embeddedt** [comment]
@as564335sa 

Please explain your issue in more detail. I'm not sure what you're trying to accomplish. If you mean changing the LittlevGL data in more than one thread, you would need one thread to call lv_task_handler repeatedly (i.e. every 10 ms) and one thread to change the data.

> If you need to use other task or threads you need one mutex which should be taken before calling lv_task_handler and released after it. In addition, you have to use to that mutex in other tasks and threads around every LittlevGL (lv_...) related code. This way you can use LittlevGL in a real multitasking environment. Just use a mutex to avoid concurrent calling of LittlevGL functions.

**Comment by effeci** [comment]
what's this mutex ?

**Comment by embeddedt** [comment]
@effeci You have to create it using your OS and make sure that you lock it and unlock it around LittlevGL related code.

**Comment by kisvegabor** [comment]
The Mutexes are a basic element of every OS. You can Google on it to learn how it (and Operating systems in general) works.

**Comment by teaalltr** [comment]
Could you provide an example of this?
