### ISSUE TITLE
lv_fs_dir_open() uses wrong member for directory state info

### ISSUE THREAD

**Issue by shoggoth77** [lvgl/lvgl#61]
lv_fs_dir_open() should probably use member rddir_size rather than file_size. If rddir_size is bigger than file_size, bad things happen.

Offending line:
rddir_p->dir_d = lv_mem_alloc(rddir_p->drv->file_size);

Suggestion:
rddir_p->dir_d = lv_mem_alloc(rddir_p->drv->rddir_size);

**Comment by kisvegabor** [comment]
Thank you! 
Fixed in `beta` branch.
