### ISSUE TITLE
Text area cursor is drawn incorrectly when LV_TXT_UTF8 is 0

### ISSUE THREAD

**Issue by upbeat27** [lvgl/lvgl#624]
Here is an example of how the cursor looks with `#define LV_TXT_UTF8 1`.
The size of the cursor appears to match the letter size:
![image](https://user-images.githubusercontent.com/32659164/49887152-6ac3df00-fdf0-11e8-8acf-c313bc85a124.png)
![image](https://user-images.githubusercontent.com/32659164/49887183-83cc9000-fdf0-11e8-903f-fa58b25c891a.png)

Here is what it looks like with `#define LV_TXT_UTF8 0`, with no other changes.
Things do not line up, and you can't tell what letter you are actually on:
![image](https://user-images.githubusercontent.com/32659164/49886354-4830c680-fdee-11e8-979f-8dd256cc1c24.png)
![image](https://user-images.githubusercontent.com/32659164/49886400-626aa480-fdee-11e8-9eca-72c5414d3a4a.png)

This affects the block and outline cursor types as well (it looks even worse than these examples with the underline cursor).
The line cursor works, interestingly enough.

Using release 5.2.0.
Font is unscii.

**Comment by kisvegabor** [comment]
Hi,

I fixed it in `dev-5.3`. Please test it!

**Comment by upbeat27** [comment]
Tested with `dev-5.3`, can confirm it works correctly now.
