### ISSUE TITLE
Can the btn event be triggered by code?

### ISSUE THREAD

**Issue by as564335sa** [lvgl/lvgl#626]
Hi,
Sometimes I need to trigger button events through code instead of keypad or touch，but I didn't find the "API".

**Comment by embeddedt** [comment]
@as564335sa Why not just call your callback directly, passing it the button object pointer?

**Comment by embeddedt** [comment]
@as564335sa I see. You could try using `lv_task_create` from another thread (making sure to use a mutex) and the function you pass to that would then be invoked on the context of the lvgl thread. Another option would be to add your own logic in the `while(1)` loop.

(Please note that I have not tested the above ideas but they should work.)
