### ISSUE TITLE
Possible feature: disable wrapping in lv_group

### ISSUE THREAD

**Issue by upbeat27** [lvgl/lvgl#627]
Is anyone else interested in the ability to disable wrapping with lv_group?
Right now if you get to the last object of a group, it will wrap back and focus on the first object.
I think it would be useful to to be able to disable wrapping, so that when you get to the last item it won't go any further (and similarly, the first item won't go to the last).

Would just be a matter of adding a function like `void lv_group_set_wrap(lv_group_t * group, bool wrap)` and tweaking `lv_group_focus_next` and `lv_group_focus_prev`, I think.

It should be relatively easy to implement. If this seems like a useful feature to others, I will do it when I have the time.

**Comment by kisvegabor** [comment]
Hi,

It sounds good! 

> It should be relatively easy to implement. If this seems like a useful feature to others, I will do it when I have the time.

Great, thank you in advance!
