### ISSUE TITLE
how to set tabview's label height

### ISSUE THREAD

**Issue by 3038922** [lvgl/lvgl#628]
how to set tabview's label height?
The automatic label is too high. I want to change it to a smaller size.

**Comment by kisvegabor** [comment]
You can set it int the `LV_TABVIEW_STYLE_BTN_REL`, `LV_TABVIEW_STYLE_BTN_PR` etc styles.

```c
style.text.font = &my_small_font;
lv_tabview_set_style(tabview, LV_TABVIEW_STYLE_BTN_REL, &style);
```

**Comment by 3038922** [comment]
thank you!

> You can set it int the `LV_TABVIEW_STYLE_BTN_REL`, `LV_TABVIEW_STYLE_BTN_PR` etc styles.
> 
> ```c
> style.text.font = &my_small_font;
> lv_tabview_set_style(tabview, LV_TABVIEW_STYLE_BTN_REL, &style);
> ```
thank you.but :

    lv_style_t style = *lv_tabview_get_style(displayObj[OBJ_SYSINFO], LV_TABVIEW_STYLE_BTN_REL);
    style.text.font = &ncrfont10;
    lv_tabview_set_style(displayObj[OBJ_SYSINFO], LV_TABVIEW_STYLE_BTN_REL, &style);

This is invalid.No change in size.

    lv_style_t style;
    style.text.font = &ncrfont10;
    lv_tabview_set_style(displayObj[OBJ_SYSINFO], LV_TABVIEW_STYLE_BTN_REL, &style);

So there is no tabview attribute.

**Comment by kisvegabor** [comment]
Here is a full example:
```c

    static lv_style_t style_tv_btn_rel;
    lv_style_copy(&style_tv_btn_rel, &lv_style_btn_rel);
    style_tv_btn_rel.text.font = &lv_font_dejavu_10;
    /*The vertical padding of the released button is applied to all buttons*/
    style_tv_btn_rel.body.padding.ver = 5;                

    lv_obj_t * tv = lv_tabview_create(lv_scr_act(), NULL);
    lv_tabview_set_style(tv, LV_TABVIEW_STYLE_BTN_REL, &style_tv_btn_rel);
    lv_tabview_add_tab(tv, "First");
    lv_tabview_add_tab(tv, "Second");
```

![tv](https://user-images.githubusercontent.com/7599318/50090923-2b3f2d80-020a-11e9-952e-0efa2bcb88c7.gif)

**Comment by 3038922** [comment]
> Here is a full example:
> 
> ```c
>     static lv_style_t style_tv_btn_rel;
>     lv_style_copy(&style_tv_btn_rel, &lv_style_btn_rel);
>     style_tv_btn_rel.text.font = &lv_font_dejavu_10;
>     /*The vertical padding of the released button is applied to all buttons*/
>     style_tv_btn_rel.body.padding.ver = 5;                
> 
>     lv_obj_t * tv = lv_tabview_create(lv_scr_act(), NULL);
>     lv_tabview_set_style(tv, LV_TABVIEW_STYLE_BTN_REL, &style_tv_btn_rel);
>     lv_tabview_add_tab(tv, "First");
>     lv_tabview_add_tab(tv, "Second");
> ```
> 
> ![tv](https://user-images.githubusercontent.com/7599318/50090923-2b3f2d80-020a-11e9-952e-0efa2bcb88c7.gif)

thank you .I tested it. It worked.

**Comment by kisvegabor** [comment]
Great!

**Comment by zhangshengping** [comment]
if I do not want the label, How can I do it?

**Comment by kisvegabor** [comment]
You can use `void lv_tabview_set_btns_hidden(lv_obj_t *tabview, bool en)`.

---

We just started a [Forum](https://forum.littlevgl.com/) for LittlevGL. Please use it to ask questions.
The GitHub issues should be about development related things.

See: https://github.com/littlevgl/lvgl/issues/906
