### ISSUE TITLE
Group input not updating slider

### ISSUE THREAD

**Issue by BrianPugh** [lvgl/lvgl#629]
All the proper callbacks are triggering (object is calling code from the button as it should), but the `lv_slider` value isn't updating (dev-5.3). It used to work; investigating.

Debugging hints:

* within `lv_slider`, the value after `lv_slider_set_value` is the same as before.

* within `lv_slider_set_value`, `lv_bar_set_value` is working as intended.

* `lv_slider_get_value` appears to be called every tick and `ext->drag_value != LV_SLIDER_NOT_PRESSED`

**Comment by kisvegabor** [comment]
Hi,

Thank you for the report. I found the root of the issue. In the near past `indev_keypad_proc` was updated to send `LV_SIGNAL_PRESSED` on `LV_GORUP_KEY_ENTER` to make possible to use of the button's press action. However, it broke the slider.

I fixed it in https://github.com/littlevgl/lvgl/commit/6f1d0ef97b9ee993d16420d94585ba5a1b195bf6

Does it work there too?

**Comment by kisvegabor** [comment]
Have you updated to latest version with my fix?

**Comment by BrianPugh** [comment]
yes, commit 6f1d0ef97 seems to have fixed the slider updating issue, but it introduced a new issue where i cannot set range or values.

**Comment by embeddedt** [comment]
@BrianPugh What is the value of the `lv_obj_t *` argument inside `lv_obj_get_ext_attr`? If it's NULL maybe you are passing a NULL object pointer around.

Can you send a minimal testcase to reproduce the issue?

**Comment by BrianPugh** [comment]
I'll be back with more info/test-case this evening.

**Comment by kisvegabor** [comment]
I tested it with `lv_test_group_1` in PC simulator and it worked. Please test it with a very minimal example with only one slider to exclude every other error possibilities.

**Comment by BrianPugh** [comment]
naively, it seems like somewhere in my code a `NULL` pointer got introduced; I'm sure this is fixed, but I'll try and double confirm it soon.

**Comment by kisvegabor** [comment]
Great! Thanks for the feedback! :)
