### ISSUE TITLE
Object group focus？has a problem

### ISSUE THREAD

**Issue by longdadouzi** [lvgl/lvgl#630]
[When I use the object group to move the focus, it will make my control no longer complete, I need to re-screen the screen, is it necessary?
![2](https://user-images.githubusercontent.com/33568295/49986957-a73c3a00-ffac-11e8-9a81-d6a0940836e5.jpg)
![22](https://user-images.githubusercontent.com/33568295/49986964-adcab180-ffac-11e8-8812-c8729799a858.png)

When I call these two functions：
 lv_group_focus_prev(group);
lv_group_focus_next(group);

**Comment by kisvegabor** [comment]
Hi,

`lv_group_focus_prev` and `lv_group_focus_next` should work. Please send a **minimal** code example to reproduce the issue.

**Comment by longdadouzi** [comment]
This is the code for the callback function，
```c
static lv_res_t btn_Connect_clicked(lv_obj_t *btn)
{/*--Connect--*/
  switch(lv_indev_get_key(input_device_dvrive))
  {
  case LV_GROUP_KEY_UP:
    lv_group_focus_prev(Firstgroup);
  break;
  case LV_GROUP_KEY_DOWN:
    lv_group_focus_next(Firstgroup);
  break;
  case LV_GROUP_KEY_LEFT:
    lv_scr_load(scr_Maininterface);
    break;
  case LV_GROUP_KEY_RIGHT:
  
    break;
  case LV_GROUP_KEY_ENTER:

    break;
  }
  /*The button is not deleted*/
  return LV_RES_OK; 
}
```

**Comment by longdadouzi** [comment]
How can I hide one page in the screen and display another page?

**Comment by embeddedt** [comment]
@longdadouzi If you have two `lv_page` objects, you can literally hide one and show the other with two calls to `lv_obj_set_hidden`.

**Comment by kisvegabor** [comment]
I tested `lv_group_focus_next` again and it seems working. 
Your issue seems like a driver issue. 
Do you have a touchpad? If yes, clicking buttons via touchpad do break the screen?

**Comment by longdadouzi** [comment]
@kisvegabor 
Not quite sure what the problem is, and I found out if a screen object src would be created
When using lv_obj_set_size(src,50,240) to set the size, the image will be incomplete as described above.
The size of my screen is 320*240

**Comment by longdadouzi** [comment]
@embeddedt 
Whether this function is valid for all classes
Thank you, I will try to do this.

**Comment by kisvegabor** [comment]
@longdadouzi You couldn't set the size of the screens. If you need a container create:
```c
    lv_obj_t bg = lv_obj_create(lv_scr_act(), NULL);
    lv_obj_set_size(bg, 50, 240);
    lv_obj_set_style(bg, &lv_style_transp);
``` 

Or use [lv_cont](https://docs.littlevgl.com/#Container) if you need more features.

**Comment by longdadouzi** [comment]
The problem mentioned above, as long as I call lv_scr_load (src) can solve, but I found that it is not fast enough, it seems very slow when changing pages

**Comment by longdadouzi** [comment]
How to exit a list object group when an input device is assigned to a list object group. . It seems that it can only be active in the list object group. . . help me......

**Comment by embeddedt** [comment]
@longdadouzi Maybe you should increase your VDB size. Calling `lv_scr_load` is always very fast for me.

**Comment by longdadouzi** [comment]
Hi
list=lv_list_create (page,NULL);

lv_group_add_obj(group_1,list);
......
  case LV_GROUP_KEY_ENTER:
    lv_indev_set_group(input_device_dvrive,group_1);
      break;
.....
....
Where should I go?
    lv_indev_set_group(input_device_dvrive,group1);
....
When I assign a group of objects belonging to the list to the input device, I will no longer be able to control the input device.

The list seems to have a built-in callback function. I only call the callback function I wrote when I press OK. How do I assign the previous object to the input device when I press left?

**Comment by kisvegabor** [comment]
@longdadouzi To keep the issues clear, please talk about one topic in one issue. 

So here let's talk about the original question: _the screen's image become broken._
and please open a new issue for the group related question.

So is there any updates about the display issue?

**Comment by longdadouzi** [comment]
Ok， Ok, that question I called lv_scr_load (src)，Seems to be able to solve

**Comment by kisvegabor** [comment]
> Ok， Ok, that question I called lv_scr_load (src)，Seems to be able to solve

According to this let's close this issue and continue in other issues if you have further questions.
