### ISSUE TITLE
How to use Chinese font examples

### ISSUE THREAD

**Issue by hjjoe1213123** [lvgl/lvgl#631]
The first step is to get this tool https://debugdump.com/t_1350.html LvglFontTool_V0_1.rar
![_20181214171846](https://user-images.githubusercontent.com/13696132/49994435-79fb8600-ffc4-11e8-8c16-3b55f1b10146.png)

The second step is to enter the text you want.
Step 3 Click the Start Conversion button
Step 4 Click Save and define your file name.

like this:
![_20181214172646](https://user-images.githubusercontent.com/13696132/49994806-74eb0680-ffc5-11e8-92fd-7014a33ae800.png)

then you must make you project like this:
![_20181214172516](https://user-images.githubusercontent.com/13696132/49994731-40774a80-ffc5-11e8-9895-7514fe6202d0.png)

**Comment by BesitzeRuf** [comment]
Hi **hjjoe1213123** , are there source files somewhere?

**Comment by kisvegabor** [comment]
Hi,

Thank you for sharing this!

I tried it with the text "hi" and got a strange result. Although I tried it in Linux with Wine I think the issue was not because of it  
![image](https://user-images.githubusercontent.com/7599318/50051230-9e637980-010e-11e9-84e7-165f12ff6ce6.png)

**Comment by hjjoe1213123** [comment]
I'm using Windows 10, and I haven't tried Linux Wine

**Comment by hjjoe1213123** [comment]
@BesitzeRuf You mean the source file of LvglFontTool? This is written by one of our colleagues in alibaba. Next time, ask him if he has it

**Comment by kisvegabor** [comment]
@hjjoe1213123 
> I'm using Windows 10, and I haven't tried Linux Wine

Andon Widows the above mentioned use case is working?

**Comment by hjjoe1213123** [comment]
@kisvegabor yes no problem
