### ISSUE TITLE
Pressing Ok on lv_kb adds Ok symbol to TA

### ISSUE THREAD

**Issue by fpw** [lvgl/lvgl#634]
I'm using a virtual keyboard (lv_kb with an assigned text area and an Ok action. Pressing the Ok key on the virtual keyboard adds the Ok symbol to the textarea and there seems to be no way to prevent this. Returning LV_RES_INV from the action is not a workaround because the button stays pressed visually.

This didn't happen in lvgl 5.1. Since the Ok action has access to the keyboard and thus to the textarea, I suggest that neither the cancel nor the ok action keys should add symbols to the textarea. If the user desires that, they can add the symbols in the respective action.

**Comment by embeddedt** [comment]
@fpw Try the `kb_fix` branch.

**Comment by fpw** [comment]
Works as expected there, thanks!

**Comment by kisvegabor** [comment]
@embeddedt I think the issue was a missing `return`. See: https://github.com/littlevgl/lvgl/commit/3b81dc2a557423e5802f13f5cafb6b87745383f1

@fpw Is it still working with the update?

**Comment by fpw** [comment]
@kisvegabor Yes, this also works.

**Comment by embeddedt** [comment]
@kisvegabor You are correct; it's a better solution.

**Comment by embeddedt** [comment]
@fpw I have merged the fix into `dev-5.3` and `master`.
