### ISSUE TITLE
Bug: lv_label child of lv_bar will not draw

### ISSUE THREAD

**Issue by BrianPugh** [lvgl/lvgl#637]
Creating a `lv_label` with a parent of `lv_bar` causes the label to not be displayed.

**Comment by kisvegabor** [comment]
It works for me:
```c
    lv_obj_t * bar = lv_bar_create(lv_scr_act(), NULL);
    lv_bar_set_value(bar, 30);
    lv_obj_align(bar, NULL, LV_ALIGN_CENTER, 0, 0);
    lv_obj_t * label = lv_label_create(bar, NULL);
    lv_obj_align(label, NULL, LV_ALIGN_CENTER, 0, 0);
```

![image](https://user-images.githubusercontent.com/7599318/50052652-7af8f880-0127-11e9-9606-72a731094390.png)

Maybe the label's color is the same as the background color of the bar?

**Comment by BrianPugh** [comment]
I think my issue is the inhereted style of the label from the bar. I haven't solved this yet, but I think its my problem rather than an lvgl problem. Thanks!

Edit: Yep, this was a theming issue on my end.

Edit2: My actual problem was that I forgot a child isn't visible outside of it's parents boundaries 😭
