### ISSUE TITLE
issue with font

### ISSUE THREAD

**Issue by himsha** [lvgl/lvgl#643]
Hi,
i am facing error in changing font style

this one is working
`    
    /*Create a new style for the label*/
    static lv_style_t style;
    lv_style_copy(&style, &lv_style_plain);
    style.text.color = LV_COLOR_BLUE;
    style.text.font = &lv_font_dejavu_20;
`

but when i change font from lv_font_dejavu_20 to lv_font_dejavu_10 its shows error
`  
    /*Create a new style for the label*/
    static lv_style_t style;
    lv_style_copy(&style, &lv_style_plain);
    style.text.color = LV_COLOR_BLUE;
    style.text.font = &lv_font_dejavu_10; // here its shows error
`

**Comment by kisvegabor** [comment]
Hi,

Please copy here the error messasge?

**Comment by BrianPugh** [comment]
is `lv_font_dejavu_10` enabled in your `lv_conf.h` ? Also try a `make clean`, just to be sure.

**Comment by kisvegabor** [comment]
> 'lv_font_dejavu_10' undeclared (first use in this function)	welcome_screen.c 

It should be what @BrianPugh said. Enable the font in `lv_cong.h`

**Comment by himsha** [comment]
i had declared as below, is this be fine? or how to enable it in lv_cong.h

LV_FONT_DECLARE(lv_font_dejavu_10);

**Comment by kisvegabor** [comment]
You need `#define USE_LV_FONT_DEJAVU_10              4` in `lv_conf.h`. The number means the bit-per-pixels. It can be 1/2/4/8
