### ISSUE TITLE
XPT2046 pins connection??

### ISSUE THREAD

**Issue by miki105** [lvgl/lvgl#650]
Hi,
I'm trying to find documentation about the hardware connections, between 2.8" ILI9341 display with driver touch XPT2046 and esp32 wroom32 that is used by your libraries, but after few days I decide to ask to you if you could post those information.
many thanks

**Comment by kisvegabor** [comment]
Hi,

do you mean this project? https://github.com/littlevgl/lv_projects/tree/master/esp32_ili9341

If yes, unfortunately, the touchpad is not added to this project yet. :(
If you are interested in and would like to add it I'd kindly help.

**Comment by miki105** [comment]
Hi Gabor,
yes, I meant that project
If you could help it will be very kind. I have seen on your libraries under lv_drivers\indev that, XPT2046 is implemented but there are not IO map.
many thanks for the support.

**Comment by miki105** [comment]
Could you do for me or it's a long time job for you?, or could you send an example how to do it.
Sorry I'm beginner on your libraries.

Many thanks

**Comment by kisvegabor** [comment]
You just need to use [this file](https://github.com/littlevgl/lv_drivers/blob/master/indev/XPT2046.c) and replace the SPI related things with ESP SPI functions.

**Comment by miki105** [comment]
I'm stuck at begin again, no IO map ,however
Many thanks.

**Comment by miki105** [comment]
Hi Gabor,
many thanks really appreciated.
Merry Christmas

**Comment by InfiniteYuan** [comment]
@miki105 You can refer [iot-solution](https://github.com/espressif/esp-iot-solution/tree/master/examples/hmi), there are some example with xpt2046 on esp32

**Comment by kisvegabor** [comment]
I've added the driver to https://github.com/littlevgl/esp32_ili9431

If it's not working properly, please open an issue in its repo.
