### ISSUE TITLE
about label set pos.

### ISSUE THREAD

**Issue by 3038922** [lvgl/lvgl#652]
My lvgl version is 5.1.0.
I have some problems with the location of LABEL.
If I don't do anything, his order is reversed. That's understandable.
![2](https://user-images.githubusercontent.com/33926386/50265164-48b60680-0459-11e9-9f27-7c94d5cee4d9.jpg)
![img_20181220_130836](https://user-images.githubusercontent.com/33926386/50265176-523f6e80-0459-11e9-8607-d447e15f15ec.jpg)

If I use lv_obj_set_y or other sort functions, his sort is disorderly.
Maybe it needs an algorithm.
![1](https://user-images.githubusercontent.com/33926386/50265240-a5b1bc80-0459-11e9-9f9e-3c4f241eb218.jpg)

![img_20181220_131004](https://user-images.githubusercontent.com/33926386/50265183-57042280-0459-11e9-80d0-70c85146474a.jpg)

**Comment by embeddedt** [comment]
@3038922 Could you highlight where you are calling the sort functions? I am having troubles finding it even though I read your screenshots multiple times.

**Comment by 3038922** [comment]
![image](https://user-images.githubusercontent.com/33926386/50291064-6d859a80-04a8-11e9-96b2-f8c6feca415d.png)
I am a novice, thank you very much. I use C++ STL. to create objects.

**Comment by kisvegabor** [comment]
@3038922 What is the parent of the label? If it's a page (or window) have a look at this: https://docs.littlevgl.com/#Page (Notes section)

**Comment by 3038922** [comment]
![image](https://user-images.githubusercontent.com/33926386/50347779-d2f18e00-0571-11e9-9d15-f9d6138b55b6.png)
lv_tabview_add_tab()

**Comment by kisvegabor** [comment]
`lv_tabview_add_tab()` also craetes a page. 

If still not working please provide a minimal example to see what happens and tell what you expect to happen.

**Comment by 3038922** [comment]
> `lv_tabview_add_tab()` also craetes a page.
> 
> If still not working please provide a minimal example to see what happens and tell what you expect to happen.

Thank you for your patience. We are VEX users of educational robots. https://www.vexrobotics.com/vexedr  
We come from all over the world. We use LVGL in the open source free IDE PROS.
https://github.com/purduesigbots
 We are not professional programmers. We are all junior high school and high school students. So we ask amateur questions. Because of language problems, documents are often not carefully read. I'm very sorry.

**Comment by kisvegabor** [comment]
Thank for the introduction! 

If you are interested, you can contribute to the library by translating the documentation.

Anyway, I suppose you were able to solve the issue using the documentation. If it's still not working, comment here.
