### ISSUE TITLE
How to rotate an object?

### ISSUE THREAD

**Issue by 3038922** [lvgl/lvgl#653]
My lvgl version is 5.1.0
I want to visualize robots in maps. I use a green OBJ to represent robots, but I can't find a function to rotate OBJ.
![image](https://user-images.githubusercontent.com/33926386/50272264-2da3c080-0472-11e9-8701-b9836a8d43f9.png)
![mmexport1545289764540](https://user-images.githubusercontent.com/33926386/50272265-309eb100-0472-11e9-93a4-82b4071499f6.jpg)

**Comment by embeddedt** [comment]
@3038922 As far as I know, rotating objects is not supported at this time. If you are just making a rectangle you could switch the width and height.

**Comment by 3038922** [comment]
@embeddedt  ok thank you!
