### ISSUE TITLE
Horizontal lv_btnm has ugly line on right

### ISSUE THREAD

**Issue by embeddedt** [lvgl/lvgl#657]
I confirmed this was introduced by #622.

![screenshot from 2018-12-20 10-28-35](https://user-images.githubusercontent.com/42941056/50293659-1947cf80-0442-11e9-91f2-bf517f5ba9e7.png)

**Comment by turoksama** [comment]
I think it's maybe a LV_BORDER_RIGHT thing.
Please check #622.

**Comment by embeddedt** [comment]
@turoksama As mentioned above I have already tested and found the problem was introduced when #622 was merged.

**Comment by turoksama** [comment]
It won't show in my case, of course because it's a LV_NONE_BORDER.

**Comment by embeddedt** [comment]
@kisvegabor That sounds like a good compromise.

**Comment by kisvegabor** [comment]
@embeddedt Ok, I will implement it after Christmass!

**Comment by embeddedt** [comment]
@kisvegabor Of course! Merry Christmas to you!

**Comment by kisvegabor** [comment]
@embeddedt Merry Christmas to you too (if you celebrate it :)  )

**Comment by embeddedt** [comment]
@kisvegabor Great! Will test it soon.

**Comment by embeddedt** [comment]
@kisvegabor The button matrix is working normally now. Thanks for the fix!

**Comment by kisvegabor** [comment]
@embeddedt Great, thank you for the feedback!
