### ISSUE TITLE
find error

### ISSUE THREAD

**Issue by caoliuchao** [lvgl/lvgl#663]
Hello! I am a college student from China. I am really glad to find littleVGL, which is a very good GUI. However, when I studied littleVGL, I found some problems. In version 5.2, the return value of "lv_arc_get_angle_end(lv_obj_t * arc)" function in the source code is" ext->angle_start", maybe there is something wrong with the source code, maybe I don't understand it. I hope you can tell me.

**Comment by embeddedt** [comment]
@caoliuchao Good catch! `ext->angle_end` is definitely used in other places like `lv_arc_set_angles` so it belongs in `lv_arc_get_angle_end` as well. This problem is in `v5.3` as well.

**Comment by kisvegabor** [comment]
@caoliuchao Thank you for pointing this out!
And @embeddedt thank you for the fix :)

**Comment by kisvegabor** [comment]
@embeddedt 
The notification above says: 
![image](https://user-images.githubusercontent.com/7599318/50386815-867f8d00-06ee-11e9-8a46-8f3e9cc9471b.png)

How did you close a PR in a commit? Or did I miunderstand something?

**Comment by embeddedt** [comment]
@kisvegabor When you put `Fixes #<issue-number>` in a commit, it will automatically close the related issue once the commit is pushed to `master`. I didn't make a PR for this change.

https://help.github.com/articles/closing-issues-using-keywords/

**Comment by kisvegabor** [comment]
@embeddedt I see, thanks! Good to know. It's a really useful feature!
