### ISSUE TITLE
typo in documentation

### ISSUE THREAD

**Issue by MrMoszk** [lvgl/lvgl#664]
> Porting the library
.
.
.
lv_disp_drv_t disp_drv;
lv_disp_drv_init(&disp_drv); /*Basic initialization*/
disp_drv. ...=...; /*Initialize the fields here. See below.*/
**disp_drv_register**(&disp_drv); /*Register the driver in LittlevGL*/

should be
lv_disp_drv_register(&disp_drv); /*Register the driver in LittlevGL*/ 

> Unbuffered drawing
.
.
.
voidmy_disp_fill(int32_t x1,int32_t y1,int32_t x2,int32_t y2,lv_color_t color)
{
  /*TODO Fill the specified area with 'color'*/
}

missing space

**Comment by embeddedt** [comment]
See littlevgl/docs#6.
