### ISSUE TITLE
Learning littlevgl library source code

### ISSUE THREAD

**Issue by CHTUZKI** [lvgl/lvgl#668]
Since I learned about littlevgl, I feel that this library is really great. I want to know more about it and contribute code to it. So I try to read the source code of littlevgl, but my level is not enough. I feel very difficult. Is there any good suggestion or help for this problem?

**Comment by embeddedt** [comment]
@CHTUZKI I think your question is too broad. I recommend reading all of the documentation and then asking about a specific area you don't understand.
