### ISSUE TITLE
How to get font range?

### ISSUE THREAD

**Issue by InfiniteYuan** [lvgl/lvgl#672]
Hi,
 I've a tft file contain chinese font,but i don't konw unicode range?
 How should we find this range?

[wt006.zip](https://github.com/littlevgl/lvgl/files/2709242/wt006.zip)

**Comment by kisvegabor** [comment]
Have a  look at this site: https://www.compart.com/en/unicode/U+6211
It tells you the Unicode block if you type a character

**Comment by InfiniteYuan** [comment]
Thanks.I close this issue
