### ISSUE TITLE
[Bugs]Drawing bugs in object table.

### ISSUE THREAD

**Issue by turoksama** [lvgl/lvgl#674]
Hi,
 Cell style of object table when set

	bg.body.border.width = 1;
	bg.body.border.part = LV_BORDER_FULL;

	cell.body.border.width = 1;
	cell.body.border.part = LV_BORDER_FULL;

![image](https://user-images.githubusercontent.com/19869728/50441316-20387b80-0935-11e9-8db0-67f7c434e6ec.png)

**buttom & right** side of cell will not be drawn.

 when set lv_style_pretty, it looks like this:

![image](https://user-images.githubusercontent.com/19869728/50444542-f3d82b80-0943-11e9-9096-ffe8706bc177.png)

when:
	bg.body.empty = 1;

![image](https://user-images.githubusercontent.com/19869728/50444851-b6749d80-0945-11e9-9162-eb6cfc4fa4c5.png)

**Comment by kisvegabor** [comment]
Hi,

I fixed it. Is okay now?

**Comment by turoksama** [comment]
Hi,
 It's ok now. Thanks!
