### ISSUE TITLE
lv_roller.h: (supposed) unintentional recursion problem (typo?)

### ISSUE THREAD

**Issue by shoggoth77** [lvgl/lvgl#68]
My compiler thinks this is a bad idea:
warning: all paths through this function will call itself [-Winfinite-recursion]

```
static inline void lv_roller_get_selected_str(lv_obj_t * roller, char * buf)
{
    lv_roller_get_selected_str(roller, buf);
}
```

lv_roller_get_selected_str() -> lv_roller_get_selected_str() -> lv_roller_get_selected_str() -> lv_roller_get_selected_str() ... -> infinite recursion. Boom.

**Comment by kisvegabor** [comment]
Hi,
It's a typo. I fixed it in `beta` branch. 
Thank you.
