### ISSUE TITLE
Userdata associated with ddlist

### ISSUE THREAD

**Issue by ridams** [lvgl/lvgl#680]
I've tried the demo and tutorials, it is a great library, just I wander if there is a possibility to associate userdata with ddlist for example, I know I can get the selected index from the ddlist, but I want to get a pointer to the selected element, say for example when i fill the ddlist from a database table CITY (ID, NAME) of a person when I select the city I want the real ID.

**Comment by kisvegabor** [comment]
Hi,

You can use `free_ptr` to assign an array to the ddlist:
```c

    static uint32_t city_id_array[] = {1, 22, 43, 2, 55, 45, 55};
    lv_obj_set_free_ptr(ddlist, city_id_array);

    /*In this action*/
    uint32_t * id_array = lv_obj_get_free_ptr(ddlist);
    uint32_t sel_id = lv_ddlist_get_selected(ddlist);
    uint32_t city_id = id_array[sel_id];
```

Can it work in your case?
