### ISSUE TITLE
Feature implementation questions.

### ISSUE THREAD

**Issue by chaos4284** [lvgl/lvgl#683]
I am currently implementing a panel designer.
I want to implement the following functionality, but I need an example.
![image](https://user-images.githubusercontent.com/42568458/50554831-9a864880-0d05-11e9-93d5-b101dc323aaa.png)

1. Button Created and Clicked.
2. Button remains pressed state.
3. Click the object3 area with the touch or the mouse.
4. If mouse or touch input coordinates are with in the object3 area, a button is created at the corresponding position.
5. Button remains released state.

**Comment by kisvegabor** [comment]
Hi,

> 1. Button Created and Clicked.
> 2. Button remains pressed state.

The button should be a toggle button (`lv_btn_set_toggle()`). It will toggle between toggled/not toggled states on click.

> 3.  Click the object3 area with the touch or the mouse.
> 4. If mouse or touch input coordinates are with in the object3 area, a button is created at the corresponding position.

Object 3 should be a button to add an action and handle the click. To get the clicked coordinate use this in the action function:
```c

    lv_indev_t * indev = lv_indev_get_act();
    lv_point_t p;
    lv_indev_get_point(indev, &p);
```

> 5. Button remains released state.

Manually, set back the released state for button `lv_btn_set_state(btn, LV_BTN_STATE_RELEASED)`
