### ISSUE TITLE
Initialization return

### ISSUE THREAD

**Issue by caoliuchao** [lvgl/lvgl#689]
Can I suggest some external hardware-related porting code? Let it have a return value. Not all peripheral initialization is successful. You can ask it to return a variable of type bool to determine whether it is true or false.

**Comment by embeddedt** [comment]
@caoliuchao The way LittlevGL is set up right now you call the hardware initialization yourself, before registering your display and input drivers and entering the main `while(1)` loop.

What exactly are you suggesting we should change in that model?

**Comment by caoliuchao** [comment]
@embeddedt  But it seems that in the migrated initialization function, the hardware initialization function is used, not just the registered function. You're looking at these documents.

**Comment by embeddedt** [comment]
@caoliuchao Here's an example from `pc_simulator`:

https://github.com/littlevgl/pc_simulator/blob/ee54670755fd67f4f666dc476db538fa661c496a/main.c#L123

If you look in that file, you can see that the SDL library is initialized (in `monitor_init`) before the display driver is registered.

I think I'm not understanding exactly what you mean.

**Comment by caoliuchao** [comment]
/**********************
 *   STATIC FUNCTIONS
 **********************/
/* Initialize your display and the required peripherals. */
static void disp_init(void)
{
    /*You code here*/
}

**Comment by embeddedt** [comment]
@caoliuchao Yes, I think I know what you mean now. :smile: You are saying that the current porting templates do not account for a potential error during initialization of the peripheral(s).

**Comment by caoliuchao** [comment]
This function is what I feel is asking us to add external hardware initialization, but external hardware initialization, not necessarily successful initialization, so we need a bool type return value

**Comment by caoliuchao** [comment]
yes very good

**Comment by caoliuchao** [comment]
I've probably modified it

/**
 * @file lv_port_disp_templ.c
 *
 */

 /*Copy this file as "lv_port_disp.c" and set this value to "1" to enable content*/
#if 0

/*********************
 *      INCLUDES
 *********************/
#include "lv_port_disp_templ.h"

/*********************
 *      DEFINES
 *********************/

/**********************
 *      TYPEDEFS
 **********************/

/**********************
 *  STATIC PROTOTYPES
 **********************/
static bool disp_init(void);

static void disp_flush(int32_t x1, int32_t y1, int32_t x2, int32_t y2, const lv_color_t * color_p);
static void disp_map(int32_t x1, int32_t y1, int32_t x2, int32_t y2, const lv_color_t * color_p);
static void disp_fill(int32_t x1, int32_t y1, int32_t x2, int32_t y2,  lv_color_t color);
#if USE_LV_GPU
static void mem_blend(lv_color_t * dest, const lv_color_t * src, uint32_t length, lv_opa_t opa);
static void mem_fill(lv_color_t * dest, uint32_t length, lv_color_t color);
#endif

/**********************
 *  STATIC VARIABLES
 **********************/

/**********************
 *      MACROS
 **********************/

/**********************
 *   GLOBAL FUNCTIONS
 **********************/

bool lv_port_disp_init(void)
{
    /*-------------------------
     * Initialize your display
     * -----------------------*/
    if (disp_init() != true)
    {
	   return false;
    }

    /*-----------------------------------
     * Register the display in LittlevGL
     *----------------------------------*/

    lv_disp_drv_t disp_drv;                         /*Descriptor of a display driver*/
    lv_disp_drv_init(&disp_drv);                    /*Basic initialization*/

    /*Set up the functions to access to your display*/

    /*Used in buffered mode (LV_VDB_SIZE != 0  in lv_conf.h)*/
    disp_drv.disp_flush = disp_flush;

    /*Used in unbuffered mode (LV_VDB_SIZE == 0  in lv_conf.h)*/
    disp_drv.disp_fill = disp_fill;

    /*Used in unbuffered mode (LV_VDB_SIZE == 0  in lv_conf.h)*/
    disp_drv.disp_map = disp_map;

#if USE_LV_GPU
    /*Optionally add functions to access the GPU. (Only in buffered mode, LV_VDB_SIZE != 0)*/

    /*Blend two color array using opacity*/
    disp_drv.mem_blend = mem_blend;

    /*Fill a memory array with a color*/
    disp_drv.mem_fill = mem_fill;
#endif

    /*Finally register the driver*/
    lv_disp_drv_register(&disp_drv);
}

/**********************
 *   STATIC FUNCTIONS
 **********************/

/* Initialize your display and the required peripherals. */
/*true:successful initialization; false: initialization failed*/
static bool disp_init(void)
{
    /*You code here*/

    return true;
}

/* Flush the content of the internal buffer the specific area on the display
 * You can use DMA or any hardware acceleration to do this operation in the background but
 * 'lv_flush_ready()' has to be called when finished
 * This function is required only when LV_VDB_SIZE != 0 in lv_conf.h*/
static void disp_flush(int32_t x1, int32_t y1, int32_t x2, int32_t y2, const lv_color_t * color_p)
{
    /*The most simple case (but also the slowest) to put all pixels to the screen one-by-one*/

    int32_t x;
    int32_t y;
    for(y = y1; y <= y2; y++) {
        for(x = x1; x <= x2; x++) {
            /* Put a pixel to the display. For example: */
            /* put_px(x, y, *color_p)*/
            color_p++;
        }
    }

    /* IMPORTANT!!!
     * Inform the graphics library that you are ready with the flushing*/
    lv_flush_ready();
}


/* Write a pixel array (called 'map') to the a specific area on the display
 * This function is required only when LV_VDB_SIZE == 0 in lv_conf.h*/
static void disp_map(int32_t x1, int32_t y1, int32_t x2, int32_t y2, const lv_color_t * color_p)
{
    /*The most simple case (but also the slowest) to put all pixels to the screen one-by-one*/

    int32_t x;
    int32_t y;
    for(y = y1; y <= y2; y++) {
        for(x = x1; x <= x2; x++) {
            /* Put a pixel to the display. For example: */
            /* put_px(x, y, *color_p)*/
            color_p++;
        }
    }
}


/* Write a pixel array (called 'map') to the a specific area on the display
 * This function is required only when LV_VDB_SIZE == 0 in lv_conf.h*/
static void disp_fill(int32_t x1, int32_t y1, int32_t x2, int32_t y2,  lv_color_t color)
{
    /*The most simple case (but also the slowest) to put all pixels to the screen one-by-one*/

    int32_t x;
    int32_t y;
    for(y = y1; y <= y2; y++) {
        for(x = x1; x <= x2; x++) {
            /* Put a pixel to the display. For example: */
            /* put_px(x, y, *color)*/
        }
    }

    (void)color; /*Just to avid warnings*/
}

/*OPTIONAL: GPU INTERFACE*/
#if USE_LV_GPU

/* If your MCU has hardware accelerator (GPU) then you can use it to blend to memories using opacity
 * It can be used only in buffered mode (LV_VDB_SIZE != 0 in lv_conf.h)*/
static void mem_blend(lv_color_t * dest, const lv_color_t * src, uint32_t length, lv_opa_t opa)
{
    /*It's an example code which should be done by your GPU*/

    uint32_t i;
    for(i = 0; i < length; i++) {
        dest[i] = lv_color_mix(dest[i], src[i], opa);
    }
}

/* If your MCU has hardware accelerator (GPU) then you can use it to fill a memory with a color
 * It can be used only in buffered mode (LV_VDB_SIZE != 0 in lv_conf.h)*/
static void mem_fill(lv_color_t * dest, uint32_t length, lv_color_t color)
{
    /*It's an example code which should be done by your GPU*/

    uint32_t i;
    for(i = 0; i < length; i++) {
        dest[i] = color;
    }
}

#endif  /*USE_LV_GPU*/

#endif

**Comment by embeddedt** [comment]
@caoliuchao Can you make a pull request?

**Comment by caoliuchao** [comment]
I try

**Comment by caoliuchao** [comment]
Now I live in xi 'an, China, so I have time difference with him, about 12 hours. He couldn't answer my questions in time, and I couldn't give him advice or feedback in time.

**Comment by turoksama** [comment]
@caoliuchao 
He is a hard-working dude, trust me, he is online almost anytime, and will surprise you.

**Comment by fallstool** [comment]
@caoliuchao  same place. XD

**Comment by kisvegabor** [comment]
@caoliuchao Sorry for the delay. Besides of my work and family, unfortunately, sometimes I can respond only one day later.
@embeddedt is the other main maintainer of LittlevGL and he has every right to make decisions. So if he says something is good, I'm sure it really is! 
For straightforward updates like this, it's better to [create a Pull request](https://blog.littlevgl.com/2018-12-06/contributing#how-can-i-send-fixes-and-improvements). This way it would be easier to see what is your idea. 

Anyway, I agree, it's a reasonable update. So please create a Pull request! :)
