### ISSUE TITLE
how to define the  LV_DPI value?

### ISSUE THREAD

**Issue by qwert1213131** [lvgl/lvgl#69]
such as 1.54 inch   240X240

how to define LV_DPI value?
thanks!

**Comment by kisvegabor** [comment]
Hi,

In this case you have 240 pixels in 1.54". So you have got 240/1.54 pixels in 1" -> LV_DPI 155

Keep in mind the purpose of LV_DPI is to set the initial sizes and spaces to the same on every screen. 
For example a default width (for something) can be LV_DPI to make 1 inch wide on every screen.
However if you want smaller objects you can decrease LV_DPI to cheat LittlevGL.

**Comment by qwert1213131** [comment]
hi,
Thank you so much, and I finally got it.
I'm studying version 5.
If you can share some of the wearable UI designs or other design routines, you can attract more people to join.
This project is really great.

**Comment by kisvegabor** [comment]
Great! Thank you, glad to hear that you like it! :)

Do you mean share some examples for wearable UI?

**Comment by qwert1213131** [comment]
Yes, share some wearable design examples and share more video.
I'm getting started, and I'll share some video or pictures if I'm going to make a progress.
Thank you！

**Comment by kisvegabor** [comment]
Great, thank you in advance!

The offer on my hompeage is real: if you have a LittlevGL based GUI which looks impressive I kindly put it to my homepage!

**Comment by qwert1213131** [comment]
I'm going to use this GUI actively.
It will be shared at the same time.
Thank you very much.
I've been trying to learn some examples today, and this hardware button mapping is very useful.
![2018_01_11_17_59_34](https://user-images.githubusercontent.com/3905169/34819943-26b8b748-f6fa-11e7-825f-d13e50bcc73b.gif)

**Comment by kisvegabor** [comment]
Oh, looks nice! :) Keep this great work!
I'm waiting for the updates!

**Comment by kisvegabor** [comment]
As the question is answered I close this issue.
