### ISSUE TITLE
Auto scroll the page when focus change

### ISSUE THREAD

**Issue by DefEmmanuel** [lvgl/lvgl#692]
I want to use lvgl in a 128*64 oled screen.
Due to it's very small,so i want to scroll the page when i change the focus by press the keys.
Now when i press keys,the focus chaged,but the page not scroll with the focus
![scoll](https://user-images.githubusercontent.com/32035420/50598387-90bb3b80-0ee5-11e9-8e18-e58a794c8994.gif)
Is there any way to fix it?

**Comment by fallstool** [comment]
void lv_page_scroll_ver(lv_obj_t * page, lv_coord_t dist);
try this function.

**Comment by kisvegabor** [comment]
I suggest to [lv_list](https://docs.littlevgl.com/#List) instead. It supports it by default.

**Comment by upbeat27** [comment]
Alternatively:
See issue #94 
Use the group focus callback to scroll the page to bring the object into view with `lv_page_focus`.

**Comment by DefEmmanuel** [comment]
Thanks 
I used the callback to do it, it is very flexible.

**Comment by misimik** [comment]
I followed this tip, and I managed to get this working, but I was shocked to discover that the page is a grandparent to the focused object and not a parent.

```c
void focus_cb(lv_group_t * group) {
  static lv_obj_t * oldFocused = NULL;
  lv_obj_t * newFocused = lv_group_get_focused(group);
  if (newFocused != oldFocused) {
    lv_page_focus(lv_obj_get_parent(lv_obj_get_parent(newFocused)), newFocused, LV_ANIM_ON);;
  }
  oldFocused = newFocused;
}
```
