### ISSUE TITLE
[dev-5.3] may be used uninitialized in this function

### ISSUE THREAD

**Issue by InfiniteYuan** [lvgl/lvgl#695]
There are some error at [349](https://github.com/littlevgl/lvgl/blob/dev-5.3/lv_objx/lv_spinbox.c#L349) and [565](https://github.com/littlevgl/lvgl/blob/dev-5.3/lv_objx/lv_table.c#L565) when compile on esp32 platform.

I suggest that:

1. add initialized value

**Comment by embeddedt** [comment]
See #696.
