### ISSUE TITLE
Keep size of table cells fixed with long text

### ISSUE THREAD

**Issue by turoksama** [lvgl/lvgl#717]
Hi,
 Is there any way to solve this issue since cell text are not actually a label object?
 Cell will change its height automaticlly with long text value.
Regards.

**Comment by kisvegabor** [comment]
Hi,
It's not supported now but it might be added. 
What would you expect if the text is longer? Just crop it?

**Comment by turoksama** [comment]
I suggest to crop it with dots followed but not to delete the rest, simply not display in that line, should look like oneline mode.
Because we may need them for future use.

**Comment by kisvegabor** [comment]
I update the table with `lv_table_set_cell_crop`. Adding dots would be quite complex so it just crops the text outside of the table

Can you share the case where you need this crop feature?

**Comment by turoksama** [comment]
Hi,
 Sorry for the delay because of email related issues.
 I'll test it and share my case when available.Thanks.
Regards.

**Comment by turoksama** [comment]
Hi,
 It works fine except get_row_height. Thanks!

![default](https://user-images.githubusercontent.com/19869728/51123458-1bd9f100-1857-11e9-99c2-d146036542f5.jpg)

 Due to the layout, its height has to be fixed. But it is not ideal in this way neither. I suggest to use row height variable directly instead of padding.ver . What do you think?

 Please review the PR for that bug fix.

**Comment by embeddedt** [comment]
@turoksama Merged, thanks for catching that!
