### ISSUE TITLE
hi, how to set different font for the button in num or text keyboard? 

### ISSUE THREAD

**Issue by HinsunRan** [lvgl/lvgl#720]
e.g.
the point button in the number keyboard is not very clear，so i want only to set the point button's font,
making sure the point look clearly.
thanks very much!

**Comment by kisvegabor** [comment]
You can only recolor a text on a button. Would it help?

**Comment by HinsunRan** [comment]
hi, kisvegabor, the way you said is a good idea for attention.
But, the point (" . ') is very small in a button in keyboard, so for eye-catching，the better way is make the point char bigger in button. 
This is why i want to set the point button's font in the number keyboard.
In littleVgl，the number keyboard is created by lv_btnm_set_map(kb, kb_map_num),
i find no way to get the pointer of the point(" . ') button,so how to set different font for the button in num or text keyboard?
thanks very much!

**Comment by kisvegabor** [comment]
I see. There is no way to set the font of the button's text separately.
I suggest creating a new font and  editing the font by hand to make the `.` larger.

**Comment by kisvegabor** [comment]
For example:

Modfify `0xC0` to `0xE0`: 
https://github.com/littlevgl/lvgl/blob/master/lv_fonts/lv_font_dejavu_20.c#L350

And set the width to `3`:
https://github.com/littlevgl/lvgl/blob/master/lv_fonts/lv_font_dejavu_20.c#L8781

Note that the font in the example contains 1, 2, 4 and 8 bpp too so you need to edit the part you are using.

**Comment by embeddedt** [comment]
@kisvegabor I think adding a feature like this would be implemented similarly to image support. Maybe we could use an ID system for button fonts as well.

**Comment by kisvegabor** [comment]
@embeddedt Good idea! We can have let's say 4 (2 bit) type of buttons with 5 images + and 5 styles for each type.

**Comment by kisvegabor** [comment]
@embeddedt I agree. 

The control byte is getting difficult to manage by setting bits. We should use a macro somehow to help the use of control bytes. However, I don't know (and didn't find) a way to convert a number to string value, like:
```c
LV_BTNM_CTRL(LV_BTNM_WIDTH_2 | LV_BTNM_HIDDEN)"my_btn"  -> "\x43" "my_btn"
```

**Comment by embeddedt** [comment]
@kisvegabor Maybe we should find an alternative way of storing the same data, but in a more user-friendly way. I don't think it is possible to turn a number into a string with the C preprocessor.

**Comment by kisvegabor** [comment]
> Maybe we should find an alternative way of storing the same data, but in a more user-friendly way.

I agree

Let's figure it out when we get there in `v6.0`. There are other questions too related to Button matrix (e.g. store the data from a simple string).

**Comment by HinsunRan** [comment]
> For example:
> 
> Modfify `0xC0` to `0xE0`:
> https://github.com/littlevgl/lvgl/blob/master/lv_fonts/lv_font_dejavu_20.c#L350
> 
> And set the width to `3`:
> https://github.com/littlevgl/lvgl/blob/master/lv_fonts/lv_font_dejavu_20.c#L8781
> 
> Note that the font in the example contains 1, 2, 4 and 8 bpp too so you need to edit the part you are using.

@kisvegabor 
This solution solves the point( . ) display problem, and the point shows bigger.
But this solution lead that all points( . ) in other string is also bigger.
Looking forward to the v6.0. Thanks very much.
And thank @embeddedt @hydra @MCF, too.

**Comment by kisvegabor** [comment]
@HinsunRan You can generate a new font with only the required characters and use this font in the style.
But, yes, in v6.0 we will have better solution for the issue.

**Comment by HinsunRan** [comment]
@kisvegabor When does the v6.0 come out?

**Comment by kisvegabor** [comment]
@HinsunRan  Probably in this summer
