### ISSUE TITLE
Support for not listed drivers

### ISSUE THREAD

**Issue by danielkjellstrom** [lvgl/lvgl#722]
Hi, I just started reading the documentation all information needed to use the littlevgl library. As I understood it, the library is an abstract layer which needs of a hardware-specific implementation of the driver used, so that would mean that any driver could be used right? I would like to use a display with the FT81X driver from ftdi which is not listed in the "lv_drivers" site. By implementing the specific communication protocol described by the manufacturer I should be able to use the littlevgl library without a problem right?

Thanks in advance!

**Comment by embeddedt** [comment]
@danielkjellstrom You can use your existing driver; just write some glue code. There is no need to reimplement everything from scratch.
