### ISSUE TITLE
Consider adding .editorconfig file to enforce coding style

### ISSUE THREAD

**Issue by manison** [lvgl/lvgl#731]
Consider adding [.editorconfig](https://editorconfig.org/) file to your project to enforce [formatting](https://github.com/littlevgl/docs/blob/master/Coding-Style-Guide.md#formatting) of source codes in editors (Visual Studio, Eclipse etc.).

Simple setting may have the following contents:

```
[*.{c,h}]
indent_style = space
indent_size = 4
```

**Comment by kisvegabor** [comment]
I didn't know `editorconfig` but seems like an easy to use tool to apply at least a minimal formatting.

I added it to `dev-5.3`: https://github.com/littlevgl/lvgl/blob/dev-5.3/.editorconfig

Thank you!
