### ISSUE TITLE
Whether to increase the API of getting the button id for the btnm?

### ISSUE THREAD

**Issue by lepustse** [lvgl/lvgl#736]
hello,
I now need to use the btnm to design a calculator. In the callback function, I need to determine which button is pressed. If I can judge with id at this time, it is much more convenient. 
There is a function to get the id in the btn.`uint8_t id = lv_obj_get_free_num(btn);`
Therefore, I also want to use a similar API in the btnm, but I don't have this API yet.
Can I add this function to send a PR if I can?

**Comment by neverxie** [comment]
@liangyongxiang

**Comment by lepustse** [comment]
@embeddedt

**Comment by embeddedt** [comment]
@neverxie See my comment in the pull request.
