### ISSUE TITLE
Regarding LED object in Littlevgl.

### ISSUE THREAD

**Issue by TejaswiGunti** [lvgl/lvgl#737]
Can we increase the size of the LED or is it constant? If we can increase the size of the LED, where can I find it? I also want to know if I can change the shape of the LED to Oval? Could you please help me with this?

**Comment by embeddedt** [comment]
@TejaswiGunti You change the size of `lv_led` with `lv_obj_set_size`, like pretty much any LittlevGL object.

I don't think there is a way to draw oval objects at this time though.

**Comment by kisvegabor** [comment]
As @embeddedt said `lv_obj_set_size` should work. You can set different width and height to get rounded rectangle shape (no elliptic):

```c
 lv_obj_set_size(led2, 60, 30);
```
![image](https://user-images.githubusercontent.com/7599318/51453467-e4c87b80-1d3f-11e9-90eb-66c2c198bf81.png)

**Comment by TejaswiGunti** [comment]
Thank you so much for the help.. I got the shape rounded rectangle...

**Comment by TejaswiGunti** [comment]
I have one more question if you can help I can complete my task.. I want the display(output) screen same as the size of my desktop.. I have successfully changed the resolution and it worked fine but the part of the screen is hiding behind the launcher(menu bar).. What should I do to get the output screen?
