### ISSUE TITLE
how to get tabs name?

### ISSUE THREAD

**Issue by 3038922** [lvgl/lvgl#740]
I don't want to create a new container to save the name of each TAB. That's too inefficient.
example:
```
     tabview = lv_tabview_create(parent, nullptr);
     lv_tabview_add_tab(tabview , "tab1"); 
```
and how to get this tab's name? "tab1"
![image](https://user-images.githubusercontent.com/33926386/51441267-d3b14780-1d0a-11e9-9a8e-2ddfc97ae117.png)
i don't konw which one saved `lv_tabview_ext_t`

**Comment by kisvegabor** [comment]
You can add a function similarly to `lv_tabview_get_tab_act` but return `const char *` from 
`ext->tab_name_ptr`.

**Comment by 3038922** [comment]
![image](https://user-images.githubusercontent.com/33926386/51481391-b8a80b80-1dce-11e9-882f-5c531503c1e3.png)
`
    std::string name = (lv_tabview_ext_t*)(lv_tabview_get_tab(tabview, index)->ext_attr)->tab_name_ptr;
`
There seems to be some problem. I don't know if I should force a switch.

**Comment by kisvegabor** [comment]
Try this way: `
    const char * name = ((lv_tabview_ext_t*) tabview)->tab_name_ptr[id];`

**Comment by 3038922** [comment]
> ((lv_tabview_ext_t*) tabview)->tab_name_ptr[id];

3q
