### ISSUE TITLE
Output Display screen..

### ISSUE THREAD

**Issue by TejaswiGunti** [lvgl/lvgl#742]

**Comment by TejaswiGunti** [comment]
My questions is I want the display(output) screen same as the size of my desktop.. I have successfully changed the resolution and it worked fine but the part of the screen is hiding behind the launcher(menu bar).. What should I do to get the output screen?

**Comment by embeddedt** [comment]
@TejaswiGunti You'll need to provide more details. Are you using the PC simulator, or an embedded display?

**Comment by TejaswiGunti** [comment]
I am using PC simulator.. When I run my code the output screen comes up showing my application, I have changed the resolution in lv_conf.h and I am getting the size of output screen same as my desktop but some part of the screen is hiding behind the menu bar on the left side..

**Comment by kisvegabor** [comment]
Then it should be an SDL setting in monitor.c
https://wiki.libsdl.org/SDL_WindowFlags
Try to add `SDL_WINDOW_ALWAYS_ON_TOP ` instead of the last `0` [here](https://github.com/littlevgl/lv_drivers/blob/master/display/monitor.c#L291).

**Comment by TejaswiGunti** [comment]
Please do not close the issue, I am working on it.. I will update you the status..

**Comment by TejaswiGunti** [comment]
Thanks for letting me know about SDL_WindowFlags.. This helped me.. I used SDL_WINDOW_FULLSCREEN in my application...

**Comment by kisvegabor** [comment]
Great! :)
