### ISSUE TITLE
Monochrome theme with orange colors

### ISSUE THREAD

**Issue by MichaelVLV** [lvgl/lvgl#749]
Hi,

I have initialized monochrome theme and create couple screenes (with buttons and lv_list).

But I see that there are orange border present and non-monochrome backgroung.

Buttons::
![image](https://user-images.githubusercontent.com/31571833/51631239-d43d1e80-1f54-11e9-8dac-2ab6fb700240.png)

LV_LIST:
![image](https://user-images.githubusercontent.com/31571833/51631354-28e09980-1f55-11e9-8728-af33929c32d3.png)

Could you please advice which parts of style I should check? Why it is orange and brown/grey in mono theme?

**Comment by embeddedt** [comment]
@MichaelVLV Are you using any group features?

**Comment by MichaelVLV** [comment]
yes, all buttons in one group and elements of list in another

**Comment by kisvegabor** [comment]
You should set LV_COLOR_DEPTH to 1 in lv_conf.h. This way littlevgl will set a monochrome style instead of the orange by default.

**Comment by MichaelVLV** [comment]
> You should set LV_COLOR_DEPTH to 1 in lv_conf.h. This way littlevgl will set a monochrome style instead of the orange by default.

I suppuse I cant show colored images it this case? 
I changed LV_COLOR_DEPTH to 1 and now I got crash when trying to load picture.

My operete order: load and show colored image, then load screen#1 with buttons in monochrome style and use this style futher.

Is it possible? Can I change orange checkbox and list background to some another colors (white/black at least) manually? Dont think its possible dynamically change LV_COLOR_DEPTH parameter.

**Comment by kisvegabor** [comment]
I don't know what caused the crash but you can change the orange color. You need set a new `style mod callback` with `lv_group_set_style_mod_cb`.

Here is default orange style mod. function as  reference: https://github.com/littlevgl/lvgl/blob/master/lv_core/lv_group.c#L419

**Comment by MichaelVLV** [comment]
@kisvegabor Thanks, thats hepled 👍
