### ISSUE TITLE
Issue in with lv_task

### ISSUE THREAD

**Issue by Moo2017** [lvgl/lvgl#755]
Hi All,
I have an issue that sometime happens, since it doesn't happen all the time it's hard to find it . It happens mostly once I am trying to switch between  the menus ( using touch) . I'd appreciate if you can help me with that, here is some screenshot when problem arises and CPU crashes  ( I am using ESP32) .
![6](https://user-images.githubusercontent.com/34062463/51693013-1786a400-1fcc-11e9-9a5b-616b41bbc31c.JPG)
![5](https://user-images.githubusercontent.com/34062463/51693032-22d9cf80-1fcc-11e9-914c-7af9ed159b2f.JPG)
![5](https://user-images.githubusercontent.com/34062463/51693145-5ddc0300-1fcc-11e9-81b2-8fa81b0b9e7b.JPG)

Any idea what can cause this or how I can debug this? I should add that I am using lvgl 5.1beta and haven't updated yet.

**Comment by BrianPugh** [comment]
could be a multitude of things. Try updating to dev-5.3 if possible first to see if that solves your problem.

**Comment by kisvegabor** [comment]
There were some bugfixes related to `lv_task` in `dev-5.3` so it definitely worth a try. 

I suggest trying the same UI in PC simulator because there you will have better debug opportunities. E.g. you will see where the code halts exactly.

**Comment by Moo2017** [comment]
Hi all,
Thanks, I'll try dev-5.3 and see if problem is solved.
