### ISSUE TITLE
lv_sw background cannot be smaller than knob.

### ISSUE THREAD

**Issue by BrianPugh** [lvgl/lvgl#765]
I think at some point a bug was introduced into the bar/slider/switch code (or I'm just using the code wrong) on master and dev-5.3. I cannot get the non-indicator portion of a switch to be smaller than the knob by messing with `bg.body.padding` values. No amount of fiddling in `lv_test_sw_1` results in a switch like the first one in [the example png](https://github.com/littlevgl/lv_examples/blob/088c9db7680764c9a8c9fdd40d0854968c64bd73/lv_tests/lv_test_objx/lv_test_sw/lv_test_sw_1.png).

Some debugging steps I have taken:
1. `lv_slider` still works exactly as expected.
2. The style is properly being fed to `lv_slider_set_style` for `LV_SLIDER_STYLE_BG`

**Comment by embeddedt** [comment]
@BrianPugh I think you're looking for `lv_slider_set_knob_in` (the switch is really a slider). We should probably add a wrapper function to the switch so that is more clear.

**Comment by embeddedt** [comment]
@BrianPugh It appears to work for me with `lv_slider_set_knob_in(sw, false)`. 

I did test `lv_test_sw_1` now though and setting the padding doesn't work properly, so I think you have found a bug. I will investigate it tomorrow.

**Comment by embeddedt** [comment]
@BrianPugh I tried again with the latest `dev-5.3` version and it looks like `lv_test_sw_1` is working properly now. Can you give it another try?

**Comment by BrianPugh** [comment]
also your commit fixed the switch issue, thanks!

**Comment by embeddedt** [comment]
@BrianPugh See #766.

**Comment by luto65** [comment]
@BrianPugh I am getting that error now ...

**Comment by kisvegabor** [comment]
Please open a new issue and add a code snippet to show how to reproduce to problem.
