### ISSUE TITLE
big font lib store

### ISSUE THREAD

**Issue by helezh** [lvgl/lvgl#77]
gui and font can stored in diff device,because many east asia language has huge sigmbols,it has the same size,you can make a api or private date pointe for others to ext the function,thanks!

**Comment by helezh** [comment]
i like the style in 4th,it has desktop，5th is canced?

**Comment by kisvegabor** [comment]
You mean store in external flash?

Yes the desktop is cancelled because it wasn't practical and well usable. Maybe if a similar but better concept is raised it can be added again.

**Comment by helezh** [comment]
yes，big font lib stored in ext flash,ascii can buildin

**Comment by kisvegabor** [comment]
Good idea! Thank you!
I add it the todo list and will implement in the next release!

**Comment by xiaoleizii** [comment]
I wrote a GUI to achieve a similar function, the idea is very simple, only need to write a bitmap driver to get the data. Add an if statement to lv_font_get_bitmap () in lv_font.c to determine the range of Unicode encoding that needs external read. If the current character is within this range, the dot matrix data of the word is directly read from the external memory into the buffer And return to the first address of the cache can.

**Comment by kisvegabor** [comment]
Please continue the discussion about font system improvements  here:
https://github.com/littlevgl/lvgl/issues/78
