### ISSUE TITLE
lvgl is top trending C repository

### ISSUE THREAD

**Issue by kisvegabor** [lvgl/lvgl#771]
I've just found GitHub's list about the [top trending repositories](https://github.com/trending/c?since=daily).

In C language lvgl is among to top trending repos of GitHub! https://github.com/trending/c?since=daily

So congratulations to everybody! :)

![github_trending](https://user-images.githubusercontent.com/7599318/51884178-66468c00-2386-11e9-9d87-b78133fb6150.png)

**Comment by kisvegabor** [comment]
Top trending today! https://github.com/trending/c?since=daily
![image](https://user-images.githubusercontent.com/7599318/52133078-eef05100-2640-11e9-912f-adad6daa9ea8.png)

It's incredible!

**Comment by embeddedt** [comment]
We're trending once again as of right now! https://github.com/trending/c?since=daily

![image](https://user-images.githubusercontent.com/42941056/107597970-61aa4480-6bea-11eb-945a-dff7053f6dcc.png)

**Comment by kisvegabor** [comment]
Cool! :slightly_smiling_face: 

Actually, it's top trending quite often. When I need some motivation I check the list and almost every time I can find LVGL in either daily, weekly or monthly lists.
