### ISSUE TITLE
Background

### ISSUE THREAD

**Issue by TejaswiGunti** [lvgl/lvgl#774]
Hello,

I have created a screen with container.. Now the page looks white(default).. I would like to change the background with two or three colors.. I see that we have main color, grad color and border color.. 
lv_obj_t *scrn = lv_cont_create(NULL, NULL);

![index](https://user-images.githubusercontent.com/44599627/51979965-9724df00-24b4-11e9-87c7-d51408e62a6c.jpeg)

I wan to create background like this(as in the link/above picture).. Please help me with the code.. so that I can change my background colorful..

**Comment by embeddedt** [comment]
@TejaswiGunti Have a look at https://docs.littlevgl.com/#Styles.

You'll want to get **a pointer** to the existing style of `scrn` with `lv_obj_get_style` and use `lv_style_copy` to copy that into **a new lv_style_t**. Then you can adjust the `body.main_color` and `body.grad_color` values to get the gradient you desire. Lastly, apply the new style to `scrn` with `lv_obj_set_style(scrn, &<your new style object>)`.

**Comment by TejaswiGunti** [comment]
Yeah thanks so much.. I have tried this earlier and I got it afterwards I edited it so it was gone.. Now with your help I have done it.. I appreciate your help..
