### ISSUE TITLE
Values for LV_GROUP_KEY_XXX

### ISSUE THREAD

**Issue by MiSimon** [lvgl/lvgl#777]
Hello,

while adding some new values to the LV_GROUP_KEY_XXX macros, i noticed that some of the existing macros have values different from the ascii codes i expected.
-DEL is defined with 28 but has ascii code 127
-BACKSPACE is defined with 29 but has ascii code 8

is there a special reason for this or could this macros be changed to their ascii values?

**Comment by kisvegabor** [comment]
Hi,

There is no reason for. A PR would be welcome to fix them! :)
