### ISSUE TITLE
Odd behavior while dragging window

### ISSUE THREAD

**Issue by embeddedt** [lvgl/lvgl#779]
When dragging a window that is a child of the page object, the page seems to be picking up the drag events as well.

To reproduce, add `lv_win_set_drag(win, true)` below [line 267](https://github.com/littlevgl/lv_examples/blob/06b952e564af4c114846d7ff048a2a279efdec00/lv_tests/lv_test_theme/lv_test_theme_1.c#L267) in `lv_test_theme_1.c`. When you try to drag the window you'll notice the page scrolling as well for a while. Eventually it seems to lock on to the window, but the scroll bar sometimes keeps moving.

I'll try to find the root cause.

**Comment by kisvegabor** [comment]
I tried it and it seems it's because of `fit` property of the page.

Try to add:
```c
    lv_page_set_scrl_fit(parent, false, false);
    lv_page_set_scrl_height(parent, LV_VER_RES);
```

**Comment by embeddedt** [comment]
@kisvegabor That appears to have worked. Is this caused by the container fit issue mentioned in the documentation?

> You **can't set the child position with hor/ver fit enabled**. Let's imagine what happens. If you change the position of the only child when fit is enabled the the container will move/fit "around" the new position. If you have more objects on a container then you can align them relative to each other. As a workaround you can create a small transparent object on the container. It will fix the container to not "follow" the children.

**Comment by kisvegabor** [comment]
Exactly!

**Comment by embeddedt** [comment]
@kisvegabor Alright, that makes sense. It's not really a bug so I'll close this issue now.
