### ISSUE TITLE
spinbox issue

### ISSUE THREAD

**Issue by ScarsFun** [lvgl/lvgl#798]
Hi,
I'm testing spinbox object with stm32 and ili9341, but results are the same with simulator.
In spinbox digit count and decimal format settings lv_spinbox_set_digit_format:
setting "separator_position" to 0, decimal point is always shown and cursor don't wraps from last digit to first.

**Comment by kisvegabor** [comment]
@AloyseTech can you have look at it?

**Comment by kisvegabor** [comment]
@ScarsFun 
I pushed some fixes to `master` for the spinbox. It is working well now?

**Comment by AloyseTech** [comment]
Hi guys,
Sorry I’m not able to help right now. I have a lot of work on my side.

**Comment by kisvegabor** [comment]
@AloyseTech No problem, thank you for the feedback!

**Comment by ScarsFun** [comment]
by setting "separator_position" to 0 decimal point is no more showed but cursor stay fixed on less significative digit.
There is a problem with ranges too: by setting, for example, min to -99 and max to 999, I'm able to set the most significative digit to -1 turning the encoder with cursor on hundreds digit and decreasing from a positive value.

**Comment by kisvegabor** [comment]
I reviewed the spinbox's core code and made some updates and fixes. I tested with several different settings and it seemed good to me.

The updates are in the `master` branch.

**Comment by ScarsFun** [comment]
Works well now.
Thanks!

**Comment by kisvegabor** [comment]
Awesome!

**Comment by AloyseTech** [comment]
Thanks @kisvegabor for dealing with this
