### ISSUE TITLE
[Suggestion]  adjust the btn position of tabview 

### ISSUE THREAD

**Issue by qwert1213131** [lvgl/lvgl#80]
The following contents are done with the translation tool. Please forgive me where the expression is not clear.
Can the BTN of tabview be adjusted to other locations, such as left, bottom, and right;
Whether the size of the BTN can be adjusted, sometimes the character is not fully displayed
![_lv_dev_5_20180120170459](https://user-images.githubusercontent.com/3905169/35181824-191664da-fe04-11e7-991d-62380e5c2941.png)

**Comment by kisvegabor** [comment]
Now only top position is possible.

I'm not sure I understand well. Do you mean the height of the BTN area is sometimes small and the text on the buttons are not fully visible?

**Comment by qwert1213131** [comment]
hi , 

1. put the btn to the bottom position,  is it possible?

2.if there are more BTNs on the tabview, text isn't fully visible

thank you

**Comment by kisvegabor** [comment]
Hi,
1. Now bottom position is not possible, but it's no so difficult to implement in the next release.
2. I see. And you mean put the BTNs to right or left could give a lot of space for the texts?

**Comment by qwert1213131** [comment]
Hi，
     Yes, indeed.
     There is a similar situation in the EMWIN of segger company, as follows：
![tim 20180122094514](https://user-images.githubusercontent.com/3905169/35201832-8d3bbc10-ff59-11e7-832b-fa86f946945a.png)
![tim 20180122094610](https://user-images.githubusercontent.com/3905169/35201833-8d6c2274-ff59-11e7-8bfb-f3dd4b115e20.png)
![tim 20180122094708](https://user-images.githubusercontent.com/3905169/35201834-8d996554-ff59-11e7-9b1c-5546dd0a9760.png)

**Comment by kisvegabor** [comment]
Thanks for the images.
In my opinion it would be better to keeps text horizontal when they are on the left or right. Because this way we really earn some extra space.

**Comment by qwert1213131** [comment]
yes，the horizontal text is better option.
Top and bottom alignment can be used as an option.
Thank you !

**Comment by kisvegabor** [comment]
Thank you for the idea!
I will add it in v5.1

**Comment by kisvegabor** [comment]
There are some news in #147 
Let's continue there!
