### ISSUE TITLE
收集一些关于littlevGL的论坛帖子讨论 Some forum discussions on LittlevGL 

### ISSUE THREAD

**Issue by qwert1213131** [lvgl/lvgl#81]
**有很多的人开始对这个GUI感兴趣了，感谢作者的无私奉献和努力。
特收集一些帖子，也方便大家为自己的板子做对应的学习研究。
喜欢的可以star这个项目一下并做相应的代码修改提交。
同时感谢下面帖子中愿意分享出来心得和移植过程的作者们！**

There are a lot of people who are interested in this GUI, thanks to the author's selfless dedication and effort.
Special collection of a number of posts, it is also convenient for your own board to do the corresponding study.
If you like it，you can star this project and make the corresponding code modification to submit.

### 分享开源免费的LittleV GUI，麻雀虽小五脏俱全，自带OS，文件系统，动态内存管理等，极具项目使用价值
- http://bbs.armfly.com/read.php?tid=29381&page=e
- http://forum.armfly.com/forum.php?mod=viewthread&tid=82301&highlight=LITTLE
### GUI LittlevGL V5.0版本移植
- http://www.stmcu.org/module/forum/forum.php?mod=viewthread&tid=614534&fromuid=394920
### 给大家介绍一个非常不错的GUI ---- littlevgl
- https://debugdump.com/t_687.html
### 开源GUI LittlevGL 移植分享
- http://www.openedv.com/forum.php?mod=viewthread&tid=264861&highlight=LITTLE

### 一步一步分享在Windows QtCreator/Mingw平台编译运行调试LittleVGL

- https://debugdump.com/t_714.html

**Comment by kisvegabor** [comment]
Hi,
Thank you for sharing this post! 
It's very good to see that people are discussing about LittlevGL and trying it on their own hardware! :)

**Comment by kisvegabor** [comment]
I close this issue to keep list of issues clean.

Thank you again for sharing these links! :)
