### ISSUE TITLE
I want design a screen like Grid

### ISSUE THREAD

**Issue by TejaswiGunti** [lvgl/lvgl#814]
![image001](https://user-images.githubusercontent.com/44599627/52463091-a209fe80-2b9b-11e9-9ac6-2193ae5d0c9e.png)
I want to design a screen like above picture.. Could you please help me in this.. I have tried using Button Matrix but could not get the view.. What objects I should use to get the above view..

**Comment by kisvegabor** [comment]
have you tried to build it simply from `lv_obj` and `lv_label` objects?

**Comment by TejaswiGunti** [comment]
Yeah, @kisvegabor.. I have done it through labels and objects.. But what I actually want is the grid view with all the information in single box. Is there any option to design in such a way?

**Comment by kisvegabor** [comment]
You create an `lv_cont` parent and use `LV_LAYOUT_PRETTY` to arrange the items automatically.
More info: https://docs.littlevgl.com/#Container

**Comment by TejaswiGunti** [comment]
Thank you.. Can we dynamically change the values in the above picture by using container object? Meanwhile I will try your suggestion..

**Comment by kisvegabor** [comment]
> Can we dynamically change the values in the above picture by using container object?

You can change the text of the labels in the boxes. It's not related to the container or the layout.

**Comment by TejaswiGunti** [comment]
This worked.. Thank you for your help..

**Comment by kisvegabor** [comment]
Great! :)
