### ISSUE TITLE
Issue when performing a vertical scroll in a page (Animations disabled)

### ISSUE THREAD

**Issue by tehkillerbee** [lvgl/lvgl#815]
Hey fellow developers,

There is a bug when performing a vertical scroll in a page when animations are disabled (USE_LV_ANIMATION=0). In this case, the page does not scroll more than one "step" before getting stuck. The fix is simple, there appears to be a typo in the below line:

https://github.com/littlevgl/lvgl/blob/e2c0e58af91008e051c0c9fb60837e955658adc2/lv_objx/lv_page.c#L570

The line should be changed to 
`lv_obj_set_y(scrl, lv_obj_get_y(scrl) + dist);`

The issue can be reproduced easily if you follow the page example listed in https://docs.littlevgl.com/#Page and attempt to scroll with animations disabled.

**Comment by embeddedt** [comment]
Nice catch! I've fixed it in https://github.com/littlevgl/lvgl/commit/32017ff6590882c17ada80242ae5a6bb8db418ee.
