### ISSUE TITLE
option for lv_chart_set_next

### ISSUE THREAD

**Issue by ali-rostami** [lvgl/lvgl#818]
Hi
As we know, when we use the  ```lv_chart_set_next``` function, it will shift the whole chart to the left and then add the new value to the most right of the chart. I don't want to update my chart like this.
I want to draw the next value without shifting the whole chart to the left. the x of new point will start from 0 to the mx_x and then start again from point 0. to do this I change this function to this:
```
void lv_chart_set_next(lv_obj_t * chart, lv_chart_series_t * ser, lv_coord_t y)
{
	lv_chart_ext_t * ext = lv_obj_get_ext_attr(chart);
#if 0
	ser->points[ser->start_point] = y;  /*This was the place of the former left most value, after shifting it is the rightmost*/
	ser->start_point = (ser->start_point + 1) % ext->point_cnt;
#else
	static uint16_t i = 0;
	ser->points[i] = y;  /*This was the place of the former left most value, after shifting it is the rightmost*/
	i = (i + 1) % ext->point_cnt;
#endif

	lv_chart_refresh(chart);
}
```
so what do you think about it? I think it would be good to add an option in defines or maybe a parameter to set and define how the ```lv_chart_set_next``` act.

**Comment by kisvegabor** [comment]
Instead of a `define` I can imagine a function to change the display mode: `lv_chart_set_mode(chart, LV_CHART_MODE_CIRCULAR/SHIFT)`. This way it can be different for each chart.

**Comment by ali-rostami** [comment]
Yep, that's great.
And AFAIK now every time we add new data the whole chart is redrawn again. Although it is necessary for shift mode I think there is no need for this whole refresh in circular mode. Am I right?

**Comment by kisvegabor** [comment]
> And AFAIK now every time we add new data the whole chart is redrawn again. Although it is necessary for shift mode I think there is no need for this whole refresh in circular mode. Am I right?

Yes, good idea! Instead of `lv_obj_invalidate` `lv_inv_area` can be used for the affected area.

**Comment by ali-rostami** [comment]
Dear Gabor, do you have any plan for implementing these?
PS: I'm a little bit busy these days but I think I can help If you want.

**Comment by kisvegabor** [comment]
Right now, I'm working on the new features of `v6.0` so don't have time to add this. :(

However, seems quite straightforward. Would you like to try it? I can help if you stuck somewhere.

**Comment by ali-rostami** [comment]
OK, I will work on it as soon as possible. Of course, I need your help. I will notify you about the parts I couldn't understand here.
 thanks

**Comment by kisvegabor** [comment]
@ali-rostami 
Were you able to make some progress with it?

**Comment by ali-rostami** [comment]
not yet, I will get to this soon.

**Comment by kisvegabor** [comment]
Okay. 
Can I assign you this issue?

**Comment by ali-rostami** [comment]
yep, no problem.

**Comment by kisvegabor** [comment]
Done, thank you!

**Comment by ali-rostami** [comment]
> Yes, good idea! Instead of `lv_obj_invalidate` `lv_inv_area` can be used for the affected area.

Do you mean to use it in lv_chart_refresh function?

**Comment by kisvegabor** [comment]
I mean instead if `lv_chart_refresh` you can call `lv_inv_area` in `lv_chart_set_next` to invalidate only a small area.

**Comment by ali-rostami** [comment]
Yeah, but the problem is I have no idea how to get the coordination of the area.
How can I get them? How can I get the mask area?

**Comment by kisvegabor** [comment]
I suggest adding the feature first and optimize it later.

**Comment by kisvegabor** [comment]
Let's continue this in the PR: #951
