### ISSUE TITLE
Alternative draw on error

### ISSUE THREAD

**Issue by Zaltora** [lvgl/lvgl#82]
Idea:
Add a return error (int) to GPU and flush function.
When a error occured (-1) on advanced draw, lvgl will swap to basic draw (map and fill ).

if map and fill fail too, the handler return an error to inform app user (or an other way).

**Comment by kisvegabor** [comment]
In my opinion if you properly configure your hardware ad-hoc errors can not be occurred. Or what do you think which circumstances  can cause error?

**Comment by Zaltora** [comment]
GPU already used with other interfaces for examples. ( esp32 got 2 core )

**Comment by kisvegabor** [comment]
So do you suppose GPU as a shared resource?

**Comment by Zaltora** [comment]
Yeah. Can be an option ? Or you think it is useless ?
I like the idea of integrating an error feedback for the user if needed.

**Comment by kisvegabor** [comment]
For me a general error screen with a simple text if a critical error occurs seems more useful. For example a black screen with red error text.
It can be triggered from a lot of sources like:
- Out of memory
- GPU error
- Parameter error in a function 
- etc.

User should enable or disable this feature to lower overheads.

What do you think?

**Comment by hreichert** [comment]
Good idea. The error text should be customizable (maybe a #define).

**Comment by kisvegabor** [comment]
What about a function like:
`lv_error("my error text")`

or with printf like parameters:
`lv_error("Parameter 2 was too big: %d", param2)`

Then you can easily raise an error from application code too.

**Comment by Zaltora** [comment]
Send a global IHM error to the screen is a good idea. (hoping the screen still work ). I agree
I suggest a function to retrieve this error too for user application. ( the last error occurred for example like libc)
It will allow user to know if we need reset the screen or send the information to others devices to know if the device screen work. Usefull with IoT project.

**Comment by kisvegabor** [comment]
Indeed. 
Even a callback can be assigned by the user. It seems to me much simpler because user don't need to check the global flag.

**Comment by Zaltora** [comment]
I suggest to change prototype "void fill/map/flush()" to "int fill/map/flush()" to retrieve possible transmission error.
I forget a case that the I2C/SPI or other transmission can fail if the resource is busy or the device didn't answer properly.
i had added  transmission error in drivers but this features is optional and can be remove with a define set to 0 (by default)

**Comment by kisvegabor** [comment]
It sounds useful!
The only problem is that you can't see the return value of fill/map/flush functions because they are called internally.
Or do you mean LittelvGL should call the error function if these functions return with error?

**Comment by Zaltora** [comment]
Exactly, lvgl need call the error callback function set by user if it exist.
Then lvgl will inform as parameter of this function the error type:
-    Out of memory
-    GPU error
-    Parameter error in a function
-    Transmission (EIO)
-    busy (EBUSY)
-    etc.

**Comment by kisvegabor** [comment]
Good idea! Thank you!

It seems to me an `lv_error_t` enum should introduced. Let's collect the possible errors. So far we have:
* LV_ERROR_OK
* LV_ERROR_NO_MEM
* LV_ERROR_PARAM
* LV_ERROR_GPU
* LV_ERROR_IO (Busy and Transmisson together)

Please tell your remarks and error ideas.

**Comment by Zaltora** [comment]
use error system is a user choice. If user won't use it for performance reason, he can disable it. He can decide to ignore just a small part too. e.g for "LV_ERROR_IO", i got a macro like this one that i will use for each driver:
```c
#if SSD1306_TRANSMISSION_CHECK
#define verify_send(fn) do { int err; if((err = fn)) return err; } while (0)
#else
#define verify_send(fn) (fn)
#endif
```

**Comment by kisvegabor** [comment]
Hi,

I added the `lv_log` module to `dev-5.2` branch. In `lv_conf.h` choose from these log level options:
- LV_LOG_INFO
- LV_LOG_WARN
- LV_LOG_ERROR
- LV_LOG_USER

You can register a callback with `lv_log_register_print` and add log like: 
`lv_log_add(LV_LOG_LEVEL_INFO, __FILE__, __LINE__, "log text...");`

Your callback can be not only a "print". It can reset the MCU on `LV_LOG_LEVEL_ERROR` or write the warnings to the screen etc.

**Comment by Zaltora** [comment]
Great, i got a problem with lvgl and know it will help !

When power-up, i load a picture on my screen. Sometimes (i don't now why) this picture is not loaded.
this picture is on a flash and i use virtual filesystem from lvgl.
You think i will retrieve  this kind of error ? IT will help me to draw again if this happen.

**Comment by kisvegabor** [comment]
I hope so!

However, the `log_add`s still not placed in LiittlevGL, you can do it to test the issue. (which is a strange issue, by the way) Please, let me know what was the solution to it or what caused it

**Comment by kisvegabor** [comment]
As using `lv_log` you have the opportunity to add an "alternative draw on error" feature I close this issue.

Thank you for thinking together :)
