### ISSUE TITLE
Tabview action error when update to v5.3

### ISSUE THREAD

**Issue by turoksama** [lvgl/lvgl#834]
Hi, 
 Tabview action not corresponde when btnm pressed, it's fine in v5.3-dev few weeks back.

**Comment by turoksama** [comment]
Well, it is due to the API change of function ```tab_load_action```: from ```typedef void (*lv_tabview_action_t)(lv_obj_t *, uint16_t);``` to ```typedef lv_res_t (*lv_tabview_action_t)(lv_obj_t *, uint16_t);```
So, return LV_RES_OK to load the tab.

**Comment by kisvegabor** [comment]
It seems like a minor backward incompatibility. Sorry about that...
