### ISSUE TITLE
Switch callback function only called once

### ISSUE THREAD

**Issue by harteware07** [lvgl/lvgl#835]
Hello again :)

i notice a bug in `lv_sw_set_action(sw[i], cb_options);`
The callback function is only called once and then never again! To fix this for now, in the callback function i call ``lv_sw_set_action(btn, cb_options);`` again. then it works. Is the value cleared when callback is called maybe?

also the return value of `lv_sw_get_state()` seems to be the wrong way i.e. inverted.

**Comment by kisvegabor** [comment]
It's working for me

```c
    lv_obj_t * sw = lv_sw_create(lv_scr_act(NULL), NULL);
    lv_sw_set_action(sw, sw_action);
```
```c
lv_res_t sw_action(lv_obj_t * sw)
{
    printf("Switch!\n");
    return LV_RES_OK;
}
```

Is this minimal example working there?

**Comment by harteware07** [comment]
yes the minimal example works. however my problem is still happening. i create the switches here:
`	for(uint8_t i = 0; i < SCENE_EDIT_BUTTONS_CNT; i++) {
		sw[i] = lv_sw_create(bg_edit, NULL);
		lv_obj_set_size(sw[i], 42, 22);
		lv_sw_set_style(sw[i], LV_SW_STYLE_BG, &bg_style);
		lv_sw_set_style(sw[i], LV_SW_STYLE_INDIC, &indic_style);
		lv_sw_set_style(sw[i], LV_SW_STYLE_KNOB_ON, &knob_style);
		lv_sw_set_style(sw[i], LV_SW_STYLE_KNOB_OFF, &knob_style);
		lv_obj_set_free_num(sw[i], (1 << i));
		lv_sw_set_action(sw[i], gui_scenes_edit_options);

		lv_obj_align(sw[i], NULL, LV_ALIGN_IN_TOP_LEFT, 405, 55 + (i * labels_y_pad));
	#if LVGL_VERSION_MAJOR == 5 && LVGL_VERSION_MINOR >= 3
		lv_sw_set_anim_time(sw[i], 150);
	#endif
	}`
then in the cb function i have to set it again or it wont work.
`lv_res_t gui_scenes_edit_options(lv_obj_t * btn) {

	uint8_t id = lv_obj_get_free_num(btn);

	if(lv_sw_get_state(btn) == 0) {
		sceneTmp.settings.options |= id;
	} else {
		sceneTmp.settings.options &= ~id;
	}
	lv_sw_set_action(btn, gui_scenes_edit_options);
	return 0;
}`

any ideas?

**Comment by embeddedt** [comment]
@harteware07 Can you put a `printf` or a breakpoint in the callback to verify that the callback isn't called a second time?

I tried a minor variation of this code just now and it worked properly.

**Comment by harteware07** [comment]
i will do and report back!

**Comment by harteware07** [comment]
So i checked and the callback function is only called once, when the slider is first moved.
I updated to 5.3 but same problem

**Comment by embeddedt** [comment]
@harteware07 Hmm. This is odd behavior; I haven't seen it before. Can you create a minimal example that I can try in the `pc_simulator`? It will help me reproduce the issue.

**Comment by kisvegabor** [comment]
In the past few days [LittlevGL's Forum](https://forum.littlevgl.com) has launched to discuss questions there. See this [Announcment](https://forum.littlevgl.com/viewtopic.php?f=3&t=5).

If the issue still persists please open a topic for it on the Forum.

**Comment by embeddedt** [comment]
Appears to have been reported on the forum: https://forum.littlevgl.com/viewtopic.php?p=138#p138

I'll investigate when I get a chance.

**Comment by kisvegabor** [comment]
I've tested it with `lv_test_group1()` using, mouse, keyboard and encoder but all worked well for me.

**Comment by embeddedt** [comment]
I haven't run into the problem during my testing.

@harteware07 Is it still broken for you with the latest `master` branch?

**Comment by kisvegabor** [comment]
I close this issue in lack of activity. If someone investigated it feel free to comment here and reopen the issue.

**Comment by embeddedt** [comment]
It's been reported again.

https://forum.littlevgl.com/viewtopic.php?p=745#p745

With three reports I'm now pretty sure there must be an issue.

**Comment by kisvegabor** [comment]
Certainly yes. But we need to able to reproduce it.

**Comment by kisvegabor** [comment]
Probably it caused the issue: https://forum.littlevgl.com/viewtopic.php?p=756#p756

**Comment by harteware07** [comment]
I will check if it fixes it and report back!

**Comment by harteware07** [comment]
I created a simple array of sliding switches. the callback is only called if you click the switches slowly. 
I then added "return LV_RES_OK;" to the end of my callback and that fixed it! was always returning 0 in my callbacks.

**Comment by embeddedt** [comment]
@harteware07 Ah, that makes sense. 0 is defined as `LV_RES_INV`, which should only be returned if the object was deleted.
