### ISSUE TITLE
Screen bad SSD1963

### ISSUE THREAD

**Issue by autoprog** [lvgl/lvgl#837]
Hi,
problems scren, LCD 7" with SSD1963, 16bits interface/color.
based it: https://www.elecfreaks.com/wiki/index.php?title=7.0%22_Width_800*480_TFT_LCD_Module

![20190213_162911](https://user-images.githubusercontent.com/5191545/52735297-68c3fb00-2fae-11e9-8c75-eebb2beddff0.jpg)

![20190213_162958](https://user-images.githubusercontent.com/5191545/52735406-b476a480-2fae-11e9-9ddc-66f780028693.jpg)

infos:
#define LV_COLOR_DEPTH     16 
 ssd1963_cmd(0xf0);            //SET pixel data I/F format=16bit
 ssd1963_data(0x03);
ssd1963_cmd(0x3a);      //RGB pixel format
ssd1963_data(0x50);
 ssd1963_cmd(0x36);     	 //SET address mode=flip vertical
 ssd1963_data(0x00);

thanks,
Carlos.

**Comment by embeddedt** [comment]
@autoprog Do the screen dimensions in `lv_conf.h` and your driver match?

**Comment by autoprog** [comment]
Hi, yes 800x480.
thanks,
Carlos.

**Comment by autoprog** [comment]
Hi,
Solved problems!
write array length.

void lv_par_write_array( uint16_t* data_out, uint16_t len ){
from
for ( i = 0; i < (len+1); i++) {....

to
for ( i = 0; i < len; i++) ....

}

thanks,
Carlos.

**Comment by kisvegabor** [comment]
Great! :)
