### ISSUE TITLE
Enhancement of `lmeter` obj

### ISSUE THREAD

**Issue by as564335sa** [lvgl/lvgl#840]
Hi,
 In my interface, I need a scale, but the `lmeter` obj is round, so I simply modified it. I think sometimes it's very useful. Do you consider adding this function and can rotating flexibly?

like this:
![12323](https://user-images.githubusercontent.com/35949162/52775064-b9ecf100-3079-11e9-8b97-55a592b375fc.jpg)

**Comment by embeddedt** [comment]
@as564335sa That looks like a great feature! Please send a pull request!

**Comment by cron1c** [comment]
Is it possible to get the code of a flat lmeter?

**Comment by kisvegabor** [comment]
The flat line meter (like above) is not implemented yet.
