### ISSUE TITLE
[bug] lv_list not remembering it's last position

### ISSUE THREAD

**Issue by BrianPugh** [lvgl/lvgl#845]
I'll investigate this later today, but it seems like in `dev-6.0`,  `lv_list` no longer remembers it's last position. I'm willing to bet it's related to commit f5b8dd17b81eebae6fdd53dd581e2f5075c7e08f .

**Comment by kisvegabor** [comment]
I also suspect that. Without the fix in https://github.com/littlevgl/lvgl/commit/f5b8dd17b81eebae6fdd53dd581e2f5075c7e08f `lv_list_set_btn_selected` was not working.

**Comment by BrianPugh** [comment]
Fixed in #888
