### ISSUE TITLE
If label uses y offset then not correctly drawn by lv_draw_label

### ISSUE THREAD

**Issue by rrroonn** [lvgl/lvgl#854]
Probably a bug that is not readily visible but came up during my rehash of labels.

If a y offset is used by the label, it may only be partly drawn during a screen refresh.  The fix is to include the y offset as shown below.

Ron

```
    /*Go the first visible line*/
    while(pos.y + line_height /*rwb*/ + offset->y /**/ < mask->y1) {
        /*Go to next line*/
        line_start = line_end;
        line_end += lv_txt_get_next_line(&txt[line_start], font, style->text.letter_space, w, flag);
        pos.y += line_height;

        if(txt[line_start] == '\0') return;
    }

```

**Comment by kisvegabor** [comment]
Thank you for the report.
I pushed a fix to that `master`. Please verify if it works.
