### ISSUE TITLE
Help with FT6206 or STMPE610 drivers

### ISSUE THREAD

**Issue by pekalicious** [lvgl/lvgl#855]
Hi,

I have an ESP32 and would like to use the [Adafruit 2.8'' TFT Capacitive touchscreen](https://www.adafruit.com/product/2090) with LittlevGL. Unfortunately, that screen has a FT6206 Capacitive Chip. Can somebody help me with a driver for that chip?

I also own an [Adafruit 2.4'' TFT Resistive touchscreen](https://www.adafruit.com/product/3315). That one uses a STMPE610 Resistive Chip, which is also not available for LittlevGL. I am able to run the hello world example by commenting out the touch related code.

Any help would be really appreciated.

Thank you.

**Comment by embeddedt** [comment]
See https://docs.littlevgl.com/en/html/porting/index.html. You can adapt an existing driver to work with LittlevGL.

**Comment by paulpv** [comment]
@pekalicious Did you ever get this working?

**Comment by embeddedt** [comment]
The link I posted is broken. Here's the updated version: https://docs.littlevgl.com/en/html/porting/index.html

**Comment by paulpv** [comment]
Thanks! I got up and running fairly easily within a few hours of posting that.

**Comment by momosh13** [comment]
Hi 
I have a same situation, 2.4" TFT with FT6206 Capacitive Touch, and i like to use it with lv_arduino, example " ESP32_TFT_eSPI_Slider ", please help me with this project, or maybe you have some working code so i can use it.
Thank you

**Comment by kisvegabor** [comment]
Let's continue this on the [Forum](https://forumtest.littlevgl.com/) to make it visible for a larger community. You can simply log in with your GitHub account.
