### ISSUE TITLE
Text Area Keyboard input is slow.

### ISSUE THREAD

**Issue by chaos4284** [lvgl/lvgl#857]
I current developed littlevgl Designer(https://github.com/chaos4284/lvgl_designer)
I want to ask a few questions.
I  applied Text Area of " lv_examples/lv_tests/lv_test_group/".
However, I found that the keyboard input response of the text area is slow.
How can I improve the response speed of Text Area keyboard input?

**Comment by kisvegabor** [comment]
I might look slow because the letters are added when you release the key. It's not the "natural" way. You can tweak the `keyboard` driver to emulate a press and release on key press.

```c
bool keyboard_read(lv_indev_data_t * data)
{
    data->state = state;
    data->key = keycode_to_ascii(last_key);

    /* Tell there is more data when pressed. The next data will the releases state. */
    state = LV_INDEV_STATE_REL;
    return data->state == LV_INDEV_STATE_PR ? true : false;
}
```

As it really looks more natural I'll add this working mechanism. 

Is it work better there?

**Comment by chaos4284** [comment]
I will test it after work.

**Comment by chaos4284** [comment]
Code is well operate. Thanks.

**Comment by embeddedt** [comment]
@chaos4284 I would recommend using submodules for `lvgl`, `lv_drivers`, and `lv_examples`. It would make the library easier to update.

**Comment by chaos4284** [comment]
I reopend current issue.
When typing keyboard input quickly, it is not as smooth as typing in the search box on the Internet browser, and some characters are missing.

**Comment by kisvegabor** [comment]
Try to lower `LV_INDEV_READ_PERIOD` in `lv_conf.h`.

**Comment by chaos4284** [comment]
No Effect.  The problem is still the same.

**Comment by kisvegabor** [comment]
Please send a video about how it looks like now.

**Comment by chaos4284** [comment]
Here is the source code at the https://github.com/chaos4284/lvgl_designer.

It exist total three screen.

From the left, It is  component screen, draw screen, property screen.

If you click the button component on the component screen and then click on the Draw screen, the textarea appears on the Property screen.

After selecting textarea with MOUSE, enter  the value with the keyboard.

**Comment by kisvegabor** [comment]
I tested you project and I have some tips:
- Call `lv_tick_inc()` in a task. Similarly to the original PC simulator example
- Set `SDL_REFR_PERIOD` to 10 in `monitor.c`
- Set `LV_INDEV_READ_PERIOD` to `10` in `lv_conf.h`

Still not perfect but much better for me

**Comment by chaos4284** [comment]
When I modified 'SDL_REFR_PERIOD' to a value of 10, then I confirmed Key Input  are smooth. 
Thanks.

**Comment by kisvegabor** [comment]
Great! As LittlevGL polls the key presses  (and not event-driven) I think that all we can do.
