### ISSUE TITLE
Led Blink [ HardFault_Handler ]

### ISSUE THREAD

**Issue by autoprog** [lvgl/lvgl#861]
Hi,
my test SSD1963, 800x480, Lv5.3.
infos:
 LV_VDB_SIZE     (42 * 1024), color 16bits,

Win_800x480 = ok
Chart_780x320 =  ( update = 100ms) = ok
Led blink = failure.....init ok, blinks x...stoped with(  HardFault_Handler)
reset processor.
led size(10,10)
lv_led_off(led1); lv_led_on(led1); or  lv_led_toggle(led1);

if case problems the memory size.
how to set memory internal address?.
my memory banks
0x00000000 = 64k
0x20000000 = 64k
0x20200000 = 128k

thanks,
Carlos.

**Comment by embeddedt** [comment]
@autoprog 

> how to set memory internal address?

https://github.com/littlevgl/lvgl/blob/62195b7cc7c9c9dc643985c11f4f4de6571b530c/lv_conf_templ.h#L24

**Comment by autoprog** [comment]
Hi,
not solved,
see:
#define LV_MEM_SIZE    (128U * 1024U)   
#define LV_VDB_SIZE         (128U * 1024U) 
#define LV_VDB_ADR    0x80000000  sram

problems no is not ram size.
with led blink timer 50~200ms = error.

thanks,
Carlos

**Comment by embeddedt** [comment]
@autoprog Does the LED work at all? Please describe exactly what you've tried and what isn't working.

**Comment by autoprog** [comment]
Hi,
I do update new Lvg 5.3 02/19/19.
yesterday led blink x, will ( HardFault_Handler).

my test  today:  led not blink (It seems to me that it burned, kkkkkk),excuse me.

see code ( in thread freertos):
   lv_init();
   ssd1963_init();
      vTaskDelay(1000);
   PRINTF("\r\n LCD inilializado ok .\r\n");
//Register the display drier in LittlevGL
		                lv_disp_drv_t disp_drv;
		                lv_disp_drv_init(&disp_drv);
		                disp_drv.disp_flush = ssd1963_flush;
		                disp_drv.disp_fill = ssd1963_fill;
		                disp_drv.disp_map = ssd1963_map;
		                lv_disp_drv_register(&disp_drv);
      //--------------------------------------------------------
         //sysmon_create();
                               static lv_style_t style_led;
		                lv_style_copy(&style_led, &lv_style_pretty_color);
		                style_led.body.radius = LV_RADIUS_CIRCLE;
		                style_led.body.main_color = LV_COLOR_MAKE(0xb5, 0x0f, 0x04);
		                style_led.body.grad_color = LV_COLOR_MAKE(0x50, 0x07, 0x02);
		                style_led.body.border.color = LV_COLOR_MAKE(0xfa, 0x0f, 0x00);
		                style_led.body.border.width = 3;
		                style_led.body.border.opa = LV_OPA_30;
		                style_led.body.shadow.color = LV_COLOR_MAKE(0xb5, 0x0f, 0x04);
		                style_led.body.shadow.width = 10;
  	                   
                               lv_obj_t * led1  = lv_led_create(lv_scr_act(), NULL);
		                lv_obj_set_style(led1, &style_led);
		                lv_obj_align(led1, NULL, LV_ALIGN_IN_BOTTOM_RIGHT, -50, -50);
		                lv_led_on(led1);
		             

print led ok, will   ( HardFault_Handler), with/without Sysmon.

                              while(1){
  		       vTaskDelay(5);
  		      lv_task_handler();

		      if(++ t > 100/5){              // sample Sysmon
		          	 t =0;
		                                                       // or	sysmon_task(NULL);

							                      	 // lv_led_toggle(led1);
							                      	//  lv_led_toggle(led2);
							  		         //  lv_led_on(led1);
                       		                PRINTF("Dbug sysmon running \r\n");

		                }
	   }
//--------------------------

thanks,
Carlos.

**Comment by embeddedt** [comment]
@kisvegabor Do you have any ideas?

**Comment by kisvegabor** [comment]
I tested your code in the PC simulator and it worked.

1. Which MCU do you use?
2. Can you debug the MCU? If yes, please find where the hard fault occurs. If no, use `printf`s inside the lvgl functions to narrow the issue.

**Comment by autoprog** [comment]
Hi,
my MCU RT1021 (RT1020-EVK, NXP). Eclipse.
see:  led example not modifier.
![20190220_145928](https://user-images.githubusercontent.com/5191545/53113883-53f0e580-3521-11e9-8316-676c58b75f56.jpg)
othes runnig ok, Sysmon...

how to print Log in my printf  Tera term?

thanks,
Carlos.

**Comment by kisvegabor** [comment]
> how to print Log in my printf Tera term?

I don't know your system but even a UART would do the job to see where the hardfault occurs.

Can you debug the MCU? It'd be much easier that way.

**Comment by embeddedt** [comment]
@kisvegabor I'm pretty sure he's using a debugger; I can see a backtrace in the top right corner of his screenshot.

**Comment by autoprog** [comment]
Hi,
see other test ( your canvas_2 ) simple retangle.

void lv_test_canvas_2(void)
 {
     lv_color_t bg_color = LV_COLOR_MAKE(0xec, 0xf0, 0xf1);
     lv_color_t fill_color = LV_COLOR_MAKE(0xbc, 0xa0, 0xa1);
     static lv_color_t cbuf[sizeof(lv_color_t) * 100 * 100];
     uint32_t i;
     for(i = 0; i < sizeof(cbuf) / sizeof(cbuf[0]); i++) {
         cbuf[i] = bg_color;
     }
    lv_obj_t * canvas = lv_canvas_create(lv_scr_act(), NULL);
    lv_canvas_set_buffer(canvas, cbuf, 100, 100, LV_IMG_CF_TRUE_COLOR);   here ok
     lv_point_t points3[4] = {
       {.x=10, .y=10},
       {.x=50, .y=10},
       {.x=50, .y=50},
       {.x=10, .y=50}
     };

     lv_canvas_draw_rect(canvas, points3, LV_COLOR_RED); here ok, running forever...

    lv_canvas_fill_polygon(canvas, points3, 4, LV_COLOR_RED, fill_color); <----reset system
 }
//------------------------------------------------------------
see debug:
![debug 01](https://user-images.githubusercontent.com/5191545/53189847-21112500-35e7-11e9-9749-b851890b767d.png)

note vars it ok value.


I use Debud printf onboard (usb cdc com) receiver pc tera Term.
PRINTF("Hello world! \r\n");

thanks,
Carlos.

**Comment by kisvegabor** [comment]
The LED is a more simple object, so please debug it in the same way to sing the offending line.

**Comment by autoprog** [comment]
Hi,
see test with Leds.

![dbug_led](https://user-images.githubusercontent.com/5191545/53254337-ed470580-36a1-11e9-9d25-47a1a6ba45b4.png)

now use memory internal 64k.
canvas2 fill pollygon error.
Sysmon ok.

thanks.
Carlos.

**Comment by seyyah** [comment]
> static lv_color_t cbuf[sizeof(lv_color_t) * 100 * 100];

@autoprog please try to run/compile and report for `lv_test_canvas_2`'s orginal version. The piece of code you share contains some changes.

https://github.com/littlevgl/lv_examples/blob/9a40c22dab372b960acf16b961c1b5b24d1c4b8a/lv_tests/lv_test_objx/lv_test_canvas/lv_test_canvas.c#L108-L114

**Comment by autoprog** [comment]
Hi,
testd: static 
lv_color_t cbuf[sizeof(lv_color_t) * 100 * 100]; and 100 *80
lv_canvas_set_buffer(canvas, cbuf, 100, 80 or 100, LV_IMG_CF_TRUE_COLOR);

memory size not is, test 64k and 128k.
memory size not is.
can it other problems here.
thanks,
Carlos.

**Comment by seyyah** [comment]
Do you receive an error message when you run only the original `lv_test_canvas_2` test code in your configuration?

Can you create a minimal example that I can try in the `pc_simulator`? It will help me reproduce the issue.

**Comment by kisvegabor** [comment]
In the LED example please try to narrow the place of the issue with the debugger. You should find the most "atomic" line where it halts (not a function)

**Comment by autoprog** [comment]
hi,
see
lv_refr_area_with_vdb();
lv_refr_area_with_vdb(const lv_area_t * area_p)
in lv_refr_area_part_vdb(area_p);
disp flush  started
active->driver.disp_flush: x1:0,y1:0, x2:799,y2:162, corlor:2147483648

see debug log: win + chat ok

[log_win_chart ok.txt](https://github.com/littlevgl/lvgl/files/2902465/log_win_chart.ok.txt)

log: led error
[LOG_led.txt](https://github.com/littlevgl/lvgl/files/2902473/LOG_led.txt)

thanks,
Carlos.

**Comment by autoprog** [comment]
hi,
new test,

code: https://github.com/littlevgl/lvgl/issues/885 = ok

code for comparison:
```c
  //-------------------------not run
/*                                                 
                                                    static lv_style_t style_led;
		                lv_style_copy(&style_led, &lv_style_pretty_color);
		                style_led.body.radius = LV_RADIUS_CIRCLE;
		                style_led.body.main_color = LV_COLOR_MAKE(0xb5, 0x0f, 0x04);
		                style_led.body.grad_color = LV_COLOR_MAKE(0x50, 0x07, 0x02);
		                style_led.body.border.color = LV_COLOR_MAKE(0xfa, 0x0f, 0x00);
		                style_led.body.border.width = 3;
		                style_led.body.border.opa = LV_OPA_30;
		                style_led.body.shadow.color = LV_COLOR_MAKE(0xb5, 0x0f, 0x04);
		                style_led.body.shadow.width = 10;



		                lv_obj_t * sensor1_led  = lv_led_create(lv_scr_act(), NULL);
		                lv_obj_set_style(sensor1_led, &style_led);
		                lv_obj_align(sensor1_led, NULL, LV_ALIGN_IN_TOP_MID, 40, 40);
		                lv_led_on(sensor1_led);


		                lv_obj_t * sensor2_led  = lv_led_create(lv_scr_act(), sensor1_led);
		                lv_obj_align(sensor2_led, sensor1_led, LV_ALIGN_OUT_BOTTOM_MID, 0, 40);
		                lv_led_set_bright(sensor2_led, 190);


		                lv_obj_t * sensor3_led  = lv_led_create(lv_scr_act(), sensor1_led);
		                lv_obj_align(sensor3_led, sensor2_led, LV_ALIGN_OUT_BOTTOM_MID, 0, 40);
		                lv_led_off(sensor3_led);


		                lv_obj_t * label = lv_label_create(lv_scr_act(), NULL);
		                lv_label_set_text(label, "LED On");
		                lv_obj_align(label, sensor1_led, LV_ALIGN_OUT_LEFT_MID, -40, 0);

		                label = lv_label_create(lv_scr_act(), NULL);
		                lv_label_set_text(label, "LED half");
		                lv_obj_align(label, sensor2_led, LV_ALIGN_OUT_LEFT_MID, -40, 0);

		                label = lv_label_create(lv_scr_act(), NULL);
		                lv_label_set_text(label, "LED Off");
		                lv_obj_align(label, sensor3_led, LV_ALIGN_OUT_LEFT_MID, -40, 0);
*/
      //------------------------- running ok

		                int led_size = 24;
		                static lv_style_t style_speedbox_label;
		                lv_style_copy(&style_speedbox_label, &lv_style_pretty);
		                style_speedbox_label.text.font = &lv_font_dejavu_20;



		                	static lv_style_t style_led;
		                	lv_style_copy(&style_led, &lv_style_pretty_color);
		                	style_led.body.radius =  12;
		                	style_led.body.main_color = LV_COLOR_MAKE(0xff, 0x3f, 0x3f);
		                	style_led.body.grad_color = LV_COLOR_MAKE(0xa0, 0x50, 0x50);
		                	style_led.body.border.color = LV_COLOR_MAKE(0xfa, 0x0f, 0x00);
		                	style_led.body.border.width = 2;

		                	lv_obj_t * sensor1_label = lv_label_create(lv_scr_act(), NULL);
		                	lv_obj_align(sensor1_label, NULL, LV_ALIGN_IN_TOP_LEFT, 0, 10);
		                	lv_label_set_text(sensor1_label, "Sensor 1");
		                        lv_label_set_align(sensor1_label, LV_LABEL_ALIGN_CENTER);
		                        lv_label_set_style(sensor1_label, &style_speedbox_label);

		                	lv_obj_t * sensor1_led = lv_led_create(lv_scr_act(), NULL);
		                	lv_obj_set_size(sensor1_led, led_size, led_size);
		                        lv_obj_align(sensor1_led, sensor1_label, LV_ALIGN_OUT_BOTTOM_MID, 0, 10);
		                	lv_obj_set_style(sensor1_led, &style_led);
		                	lv_led_on(sensor1_led);

		                	lv_obj_t * sensor1_status = lv_label_create(lv_scr_act(), NULL);
		                	lv_obj_align(sensor1_status, sensor1_led, LV_ALIGN_OUT_BOTTOM_MID, 0, 10);
		                	lv_label_set_text(sensor1_status, "OK");
		                        lv_label_set_align(sensor1_status, LV_LABEL_ALIGN_CENTER);
		                        lv_label_set_style(sensor1_status, &style_speedbox_label);

		                        lv_obj_t * sensor2_label = lv_label_create(lv_scr_act(), NULL);
		                	lv_obj_align(sensor2_label, sensor1_label, LV_ALIGN_OUT_RIGHT_MID, 15, 00);
		                	lv_label_set_text(sensor2_label, "Sensor 2");
		                        lv_label_set_align(sensor2_label, LV_LABEL_ALIGN_LEFT);
		                        lv_label_set_style(sensor2_label, &style_speedbox_label);

		                	lv_obj_t * sensor2_led = lv_led_create(lv_scr_act(), NULL);
		                	lv_obj_set_size(sensor2_led, led_size, led_size);
		                        lv_obj_align(sensor2_led, sensor2_label, LV_ALIGN_OUT_BOTTOM_MID, 0, 10);
		                	lv_obj_set_style(sensor2_led, &style_led);
		                	lv_led_on(sensor2_led);

		                	lv_obj_t * sensor2_status = lv_label_create(lv_scr_act(), NULL);
		                	lv_label_set_align(sensor2_status, LV_LABEL_ALIGN_CENTER);
		                        lv_obj_align(sensor2_status, sensor2_led, LV_ALIGN_OUT_BOTTOM_MID, 0, 10);
		                	lv_label_set_text(sensor2_status, "OK");
		                        lv_label_set_style(sensor2_status, &style_speedbox_label);

		                	lv_obj_t * sensor3_label = lv_label_create(lv_scr_act(), NULL);
		                	lv_obj_align(sensor3_label, sensor2_label, LV_ALIGN_OUT_RIGHT_MID, 15, 00);
		                	lv_label_set_text(sensor3_label, "Sensor 3");
		                        lv_label_set_align(sensor3_label, LV_LABEL_ALIGN_LEFT);
		                        lv_label_set_style(sensor3_label, &style_speedbox_label);

		                	lv_obj_t * sensor3_led = lv_led_create(lv_scr_act(), NULL);
		                	lv_obj_set_size(sensor3_led, led_size, led_size);
		                        lv_obj_align(sensor3_led, sensor3_label, LV_ALIGN_OUT_BOTTOM_MID, 0, 10);
		                	lv_obj_set_style(sensor3_led, &style_led);
		                	lv_led_on(sensor3_led);

		                	lv_obj_t * sensor3_status = lv_label_create(lv_scr_act(), NULL);
		                	lv_obj_align(sensor3_status, sensor3_led, LV_ALIGN_OUT_BOTTOM_MID, 0, 10);
		                	lv_label_set_text(sensor3_status, "OK");
		                   lv_label_set_align(sensor3_status, LV_LABEL_ALIGN_CENTER);
		                   lv_label_set_style(sensor3_status, &style_speedbox_label);
       //--------------------------------------------------------------------

i=0;
               while(1){
                  vTaskDelay(5);
	 lv_task_handler();
           
	      if(++ t > 100/5){
         	 t =0;

	if( ++i >=3){i=0; }
                  switch(i){
	case 0: lv_led_toggle(sensor1_led); break;
	case 1: lv_led_toggle(sensor2_led); break;
	case 2: lv_led_toggle(sensor3_led); break;
	}
             }
         }
//----------------------------------------------------------------------------
```
note:
#define MY_MEM_SIZE (128U * 1024U)   128x2 = 256k ( uint16_t ) <----
0x80000000~ 0x8003F480  sram extern

thanks,
Carlos.

**Comment by kisvegabor** [comment]
Form this it seesm the issue is in your driver:
```c
lv_refr_area_with_vdb();
lv_refr_area_with_vdb(const lv_area_t * area_p)
in lv_refr_area_part_vdb(area_p);
disp flush started
active->driver.disp_flush: x1:0,y1:0, x2:799,y2:162, corlor:2147483648
```

Send you `lv_conf.h` please.

**Comment by kisvegabor** [comment]
And please use shorter example codes with only the really required parts.

**Comment by autoprog** [comment]
Hi Gabor,
code source test, led ok
use Eclipse(by NXP).

thanks,
Carlos.
________________________________
De: Gabor Kiss-Vamosi <notifications@github.com>
Enviado: quinta-feira, 28 de fevereiro de 2019 04:29
Para: littlevgl/lvgl
Cc: Carlos Candido; Mention
Assunto: Re: [littlevgl/lvgl] Led Blink [ HardFault_Handler ] (#861)


Form this it seesm the issue is in your driver:

lv_refr_area_with_vdb();
lv_refr_area_with_vdb(const lv_area_t * area_p)
in lv_refr_area_part_vdb(area_p);
disp flush started
active->driver.disp_flush: x1:0,y1:0, x2:799,y2:162, corlor:2147483648

Send you lv_conf.h please.

Send you lv_conf.h: see

[lv_conf.txt](https://github.com/littlevgl/lvgl/files/2915273/lv_conf.txt)

**Comment by kisvegabor** [comment]
I don't understand, what happened?
