### ISSUE TITLE
Multiple semicolons ";"

### ISSUE THREAD

**Issue by ironiron** [lvgl/lvgl#875]
In file lv_font.h macro on line 174 states:
`#define LV_FONT_DECLARE(font_name) extern lv_font_t font_name;`
and macro in file lv_font_builtin.h states:
`LV_FONT_DECLARE(lv_font_dejavu_10);`

This results in ` extern lv_font_dejavu_10;;`
In file lv_style.h also has simple typo: `extern lv_style_t lv_style_btn_tgl_pr;;`

This additional semicolons cause compiler warnings: 

> extra ';' [-Wpedantic]

**Comment by embeddedt** [comment]
@ironiron Feel free to send a PR!

**Comment by ironiron** [comment]
Ok, I did this [https://github.com/littlevgl/lvgl/pull/876](url)
Thanks
