### ISSUE TITLE
Related to mouse input coordinates.

### ISSUE THREAD

**Issue by chaos4284** [lvgl/lvgl#878]
I am trying to represent a region of area2 that is large than area1 in fixed area area1.

That is, the horizontal and vertical areas exceeding area 1 are displayed with a scroll bar as follows.
![image](https://user-images.githubusercontent.com/42568458/53150956-34c38800-35f5-11e9-95b6-d6d6aac584fa.png)

Next Step, I clicked the mouse on area2 and confirmed that the coordinates change according to the scroll bar.

But the change was over. As shown in the following figure,
![image](https://user-images.githubusercontent.com/42568458/53151178-d34fe900-35f5-11e9-9226-c0e8b405c65b.png)

When mouse input occurs in area2, I get the coordinates of area2 through the following code.
## Code
    lv_res_t lv_design_property_process_callback(lv_obj_t * obj_property, lv_signal_t sign, void * param)
    { 
         if(sign == LV_SIGNAL_PRESSED)
         {
            indev = lv_indev_get_act();
            lv_indev_get_point(indev, &pos);
         }

    }

How do I calculate the coordinates with the scroll bar applied?

In addition, How do I create horizontal scroll bar?

**Comment by embeddedt** [comment]
@chaos4284 Here's a working example with `dev-6.0`:

```c
        lv_theme_set_current(lv_theme_night_init(210, NULL));
	lv_obj_t *area1 = lv_page_create(lv_scr_act(), NULL);
	lv_cont_set_fit(lv_page_get_scrl(area1), true, true);
	lv_page_set_sb_mode(area1, LV_SB_MODE_ON);
	lv_obj_set_size(area1, LV_HOR_RES, LV_VER_RES);
	lv_obj_t *area2 = lv_obj_create(area1, NULL);
	lv_obj_set_size(area2, 800, 400);
	lv_obj_set_click(area2, false);
```

**Comment by kisvegabor** [comment]
The returned point is absolute i.e. not relative to the clicked object. If you click the same point of the screen you will get the same point regardless to the objects coordinates. 


You can calculate the relative coordinates like this:
```c
lv_coord_t x = pos.x - obj_property->coords.x1;
lv_coord_t y = pos.y - obj_property->coords.y1;
```

**Comment by chaos4284** [comment]
code is well operate. Thanks.
