### ISSUE TITLE
Can you provide an example of `log. h`?

### ISSUE THREAD

**Issue by 3038922** [lvgl/lvgl#886]
I looked for the document. You did not see how to use the built-in `lv_log_xx`.

**Comment by embeddedt** [comment]
@3038922 `lv_conf_templ.h` gives enough information to get started:

https://github.com/littlevgl/lvgl/blob/374dfcd60a12ef0127a25a0a8bae4a5fbacf8bd4/lv_conf_templ.h#L151-L164

**Comment by 3038922** [comment]
> @3038922 `lv_conf_templ.h` gives enough information to get started:
> 
> https://github.com/littlevgl/lvgl/blob/374dfcd60a12ef0127a25a0a8bae4a5fbacf8bd4/lv_conf_templ.h#L151-L164

Is there any specific writing?

```c
LV_LOG_TRACE（“helloworld”）; //Would that be all right? Is the path of output file not initialized and not configured?
```

**Comment by embeddedt** [comment]
@3038922 If you enable `LV_LOG_PRINTF`, it calls `printf` behind the scenes and you can just do that. Otherwise you have to register a callback with `lv_log_register_print`.

**Comment by 3038922** [comment]
> @3038922 If you enable `LV_LOG_PRINTF`, it calls `printf` behind the scenes and you can just do that. Otherwise you have to register a callback with `lv_log_register_print`.
What if it's std:: cout?
I set up a `label` to read `log.txt` records. Does he automatically distinguish by color?

**Comment by embeddedt** [comment]
@3038922 Then register a callback that prints the values to `std::cout`. The documentation of `lv_log_register_print` should be self-explanatory:

https://github.com/littlevgl/lvgl/blob/374dfcd60a12ef0127a25a0a8bae4a5fbacf8bd4/lv_misc/lv_log.c#L40-L48

> I set up a `label` to read `log.txt` records. Does he automatically distinguish by color?

If you mean the recoloring system, you have to enable it with `lv_label_set_recolor(label, true)`.

**Comment by 3038922** [comment]
I'll do the experiment first. Thank you.
