### ISSUE TITLE
Is it possible to detect clicks on containers or LEDs?

### ISSUE THREAD

**Issue by fovea1959** [lvgl/lvgl#891]
Title line says it all; I have a container with other widgets inside it, and want to detect if they click anywhere in the container. I'm not seeing a way to do it....

**Comment by embeddedt** [comment]
@fovea1959 At the moment, you'll need to use a custom signal handler. See https://blog.littlevgl.com/2018-12-13/extend-lvgl-objects.

This feature will be added in `v6.0`, which is planned to be released at the end of June.

**Comment by kisvegabor** [comment]
Alternatively, you can create the LED on a transparent button.  
You need to set `lv_obj_set_click(led, false)` to make the LED not clickable.
