### ISSUE TITLE
How to use "lv_label_set_txt()"parsing escaped characters?

### ISSUE THREAD

**Issue by 3038922** [lvgl/lvgl#893]
```
#define RESET "\033[0m"
#define BLACK "\033[30m"              /* Black */
#define RED "\033[31m"                /* Red */
#define GREEN "\033[32m"              /* Green */
#define YELLOW "\033[33m"             /* Yellow */
#define BLUE "\033[34m"               /* Blue */
#define MAGENTA "\033[35m"            /* Magenta */
#define CYAN "\033[36m"               /* Cyan */
#define WHITE "\033[37m"              /* White */
#define BOLDBLACK "\033[1m\033[30m"   /* Bold Black */
#define BOLDRED "\033[1m\033[31m"     /* Bold Red */
#define BOLDGREEN "\033[1m\033[32m"   /* Bold Green */
#define BOLDYELLOW "\033[1m\033[33m"  /* Bold Yellow */
#define BOLDBLUE "\033[1m\033[34m"    /* Bold Blue */
#define BOLDMAGENTA "\033[1m\033[35m" /* Bold Magenta */
#define BOLDCYAN "\033[1m\033[36m"    /* Bold Cyan */
#define BOLDWHITE "\033[1m\033[37m"   /* Bold White */
```
I add an escape character before each output text to set the color.
```
  fprintf(_data, "%s%s\n", GREEN , "hellowrold");//saveTo txt
```
it saved like this.
![image](https://user-images.githubusercontent.com/33926386/53299414-9fcec200-3874-11e9-85ec-db3c4cee19ec.png)

i use fopen, it  have colors.
![image](https://user-images.githubusercontent.com/33926386/53299410-8c235b80-3874-11e9-988d-2cce5776d408.png)

```
lv_obj_t * debugLab=lv_label_create(parent,NULL);
 lv_label_set_text(debugLab, logData);//logData is my saved txt file.
 lv_label_set_recolor(debugLab, true);
```
He can't parse escaped characters directly
![image](https://user-images.githubusercontent.com/33926386/53299443-2388ae80-3875-11e9-9cd2-448fdbe78e3d.png)

**Comment by BesitzeRuf** [comment]
Hi @3038922, 
it is terminal (or your application) job to parse input text and when escaped character \033 was found, apply coorect color to the following text.

**Comment by 3038922** [comment]
> Hi @3038922,
> it is terminal (or your application) job to parse input text and when escaped character \033 was found, apply coorect color to the following text.

How can I create a label that automatically parses and configures colors based on escaped characters in a simple way?

**Comment by BesitzeRuf** [comment]
@3038922, I think, with a single label it is not possible... First you need to parse your input text and dynamically create labels for each substring you will parse between escape sequences.

**Comment by embeddedt** [comment]
@3038922 @BesitzeRuf You need to use the recoloring interface. The label documentation explains it here: https://docs.littlevgl.com/#Label

**Comment by kisvegabor** [comment]
> You need to use the recoloring interface.

I also think it should be used to convert your color codes to embedded text coloring for LittlevGL labels.

**Comment by 3038922** [comment]
how can i know the color's code?
```
   lv_color_t mycolor = LV_COLOR_RED;
    std::cout << mycolor.full << std::endl;
```
terminal result:
```
4294901760
```
it seem's wrong.

**Comment by 3038922** [comment]
It's easier for me to make a console page `DEBUG'.
