### ISSUE TITLE
How to adjust start position for LV_LABEL_LONG_SCROLL? (Possible bug?)

### ISSUE THREAD

**Issue by MichaelVLV** [lvgl/lvgl#900]
Hi. 

I have some long label, which comes after another label:
![image](https://user-images.githubusercontent.com/31571833/53414701-fb659080-39d7-11e9-955c-c42a4a8a8351.png)

If I set

```C
lv_label_set_long_mode(label, LV_LABEL_LONG_SCROLL);
```

for "List header too long" label, I'm getting overlaying:
![image](https://user-images.githubusercontent.com/31571833/53414810-47183a00-39d8-11e9-943d-00c18f076316.png)

Looks like animation goes for whole display width, not by coordinates of label.

Can I set somehow start position for scrolling animation of  label?

test code:

```C
static void list_menu()
{
	lv_obj_t * scr = lv_obj_create(NULL, NULL);
	lv_scr_load(scr);

	lv_obj_t * label_wifi = lv_label_create(lv_scr_act(), NULL);
	lv_label_set_text(label_wifi, SYMBOL_WIFI);
	lv_obj_align(label_wifi, NULL, LV_ALIGN_IN_TOP_LEFT, 0, 0);

	lv_obj_t * label = lv_label_create(lv_scr_act(), NULL);
	lv_label_set_text(label, "List header too long");
	lv_obj_align(label, label_wifi, LV_ALIGN_OUT_RIGHT_MID, 5, 0);
	lv_label_set_long_mode(label, LV_LABEL_LONG_SCROLL);
}
```

My lv_conf.h resolution and DPI settings:
```C
#define LV_HOR_RES          (160)
#define LV_VER_RES          (128)
#define LV_DPI              116
```

**Comment by embeddedt** [comment]
@kisvegabor

**Comment by kisvegabor** [comment]
Do you use the `v5.3`? (the latest `master`)

**Comment by MichaelVLV** [comment]
I'm using this version (its 5.3, but possible not latest master):
https://github.com/littlevgl/pc_simulator_sdl_visual_studio

I will try update to latest master and report if issue still occures

**Comment by MichaelVLV** [comment]
@kisvegabor I have updated lvgl to latest master (deleted **lvlg** folder and cloned latest master branch in VS project) and results are same, label animation covers wifi label.

**Comment by kisvegabor** [comment]
Oh, I got it!

Have look at this: https://docs.littlevgl.com/#Label

`SCROLL` scrolls the whole object ob the parent.  
`ROLL` scrolls only the text on the label

I know it's a little bit misleading. I'm planning to remove `SCROLL` in `v6.0`.

**Comment by MichaelVLV** [comment]
@kisvegabor for some reason this setting
```C
lv_label_set_long_mode(label, LV_LABEL_LONG_ROLL);
```
doing nothing - no animations at all.

I have tried all possible options in enum - only _SCROLL_ is working (at least some animation begins)

```C
static void list_menu_test()
{
	lv_obj_t * scr = lv_obj_create(NULL, NULL);
	lv_scr_load(scr);

	lv_obj_t * label_wifi = lv_label_create(lv_scr_act(), NULL);
	lv_label_set_text(label_wifi, SYMBOL_WIFI);
	lv_obj_align(label_wifi, NULL, LV_ALIGN_IN_TOP_LEFT, 0, 0);

	lv_obj_t * label = lv_label_create(lv_scr_act(), NULL);
	lv_label_set_text(label, "List header too long");
	lv_obj_align(label, NULL, LV_ALIGN_IN_TOP_LEFT, 25, 0); // removed dependence from wifi_label
	lv_obj_set_size(label, 100, 20); // set at least some size
	//lv_label_set_long_mode(label, LV_LABEL_LONG_SCROLL); // animation over whole screen
	//lv_label_set_long_mode(label, LV_LABEL_LONG_EXPAND); // nothing
	//lv_label_set_long_mode(label, LV_LABEL_LONG_BREAK); // nothing
	//lv_label_set_long_mode(label, LV_LABEL_LONG_DOT); // nothing
	lv_label_set_long_mode(label, LV_LABEL_LONG_ROLL); // nothing
	//lv_label_set_long_mode(label, LV_LABEL_LONG_CROP); // nothing
}
```

Result for _ROLL_ is static image (no animation): 
![image](https://user-images.githubusercontent.com/31571833/53568300-41525e00-3b6a-11e9-88b3-a3a0373867b3.png)

**Comment by kisvegabor** [comment]
It's because after setting `ROLL` you have to set a smaller width to the label. It will be aminated on this smaller area.

**Comment by MichaelVLV** [comment]
Oh, now this is working :)

Really, problem was in order. With _ROLL_ its mandatory to set size **after** enabling mode
```C
. . .
	lv_label_set_long_mode(label, LV_LABEL_LONG_ROLL); 
	lv_obj_set_size(label, 50, 20); 
. . . 
```

@kisvegabor 
May I suggest to make note about this in documentation?
As for me, this nuance is not obvious.

**Comment by kisvegabor** [comment]
Great! :)

It's stated here: https://github.com/littlevgl/lvgl/blob/master/lv_objx/lv_label.h#L139

Mentioning it in the documentation would be really useful. Can you add a PR? 
https://github.com/littlevgl/docs

**Comment by kisvegabor** [comment]
Meanwhile, I updated the documentation:  [commit](https://github.com/littlevgl/docs/commit/3a20dc72f23220135da35824f00f7ecd72c5796c#diff-5a17fda50367924e1aaee1b56a4e3713L10)

**Comment by MichaelVLV** [comment]
Sorry not be able to get it earlier and thanks for update !

**Comment by kisvegabor** [comment]
No problem :)
