### ISSUE TITLE
Button matrix, message box: new API proposal

### ISSUE THREAD

**Issue by manison** [lvgl/lvgl#901]
### Button matrix
**New API**
`void lv_btnm_set_pressed(uint16_t btn_id)`
There is `lv_btnm_get_pressed` function but not the setter.

### Message box
**New API**
`lv_obj_t * lv_mbox_get_btnm(lv_obj_t *mbox)`
Returns button matrix object contained in the message box.

### Motivation
To be able to set the default button in message box. E.g. in Yes/No message box I want the 'No' button to be the default, not the first ('Yes') one.

```c
static const char *buttons[] = {"Yes", "No", ""};
lv_mbox_add_btns(mbox, buttons, action);
lv_obj_t *btnm = lv_mbox_get_btnm(mbox);
lv_btnm_set_pressed(btnm, 1); /*Preselect the 'No' button*/
```

I'm going to implement these APIs if there are no objections.

**Comment by embeddedt** [comment]
@manison I don't see any issue with this feature. Go ahead! :)

**Comment by kisvegabor** [comment]
@manison 
There was a big update on `lv_btnm` here: https://github.com/littlevgl/lvgl/pull/825/
Please be sure to use the last `dev-6.0` branch to avoid conflicts.

This API  function is really missing, so waiting for the PR :)

**Comment by puzrin** [comment]
Could anyone explain, how button matrix fit into Material UI guideline?

Is it a some kind of local grid layout? What is need of special goupping for buttons, instead of generic one?

**Comment by embeddedt** [comment]
@puzrin The button matrix was created to consume less memory for large layouts. If you have a keyboard, you can create one button matrix object instead of creating 30+ buttons. By using styles, there is no visible difference between button matrixes and buttons themselves.

**Comment by puzrin** [comment]
Ah, ok. Seems "local hack" with no potential problems for future migrations to UI guideline. Thanks for explanations.

**Comment by manison** [comment]
PR #917 merged, closing.

**Comment by kisvegabor** [comment]
Great, thank you!
