### ISSUE TITLE
PLEASE READ: The Forum has launched

### ISSUE THREAD

**Issue by kisvegabor** [lvgl/lvgl#906]
The [Forum](https://forum.littlevgl.com/) has opened to separate user questions from development. It should be the place where you can ask about
- getting started with your board/MCU
- PC simulator
- how-to solve something
- something is not working

GitHub issues should be about
- bugs
- new features

Before reporting a bug on GitHub be sure it's really a bug and open a topic here first.

**Comment by puzrin** [comment]
Create `.github` with issue/pr configs instead of pinned "PLEASE READ". This will be more effective.

**Comment by embeddedt** [comment]
@puzrin If @kisvegabor is alright with it I'll do that as soon as I get a chance.

**Comment by kisvegabor** [comment]
@embeddedt It would be great! Thank you!

**Comment by jedie** [comment]
URL?

**Comment by kisvegabor** [comment]
@jedie Added, thank you!

**Comment by embeddedt** [comment]
Not stale.

**Comment by embeddedt** [comment]
https://github.com/littlevgl/lvgl/issues/975#issuecomment-475720784

**Comment by kisvegabor** [comment]
@embeddedt I think we can close this issue because:
1. almost 1 month has elapsed to let people know that we have a forum
2. the issue template will direct people to the forum
