### ISSUE TITLE
BUG about 'kb' obj or 'btnm' obj with new release v5.3

### ISSUE THREAD

**Issue by as564335sa** [lvgl/lvgl#908]
Hi,
 I found a strange bug about 'kb' obj or 'btnm' obj ?
the code:
```
lv_res_t action(lv_obj_t *obj)
{
	lv_obj_t * kb1 = lv_kb_create(lv_scr_act(), NULL);
	lv_obj_align(kb1, NULL, LV_ALIGN_IN_BOTTOM_MID, 0, 0);
	lv_kb_set_ta(kb1, obj);
	return LV_RES_OK;
}
void lv_test_kb_1(void)
{

    lv_obj_t * ta = lv_ta_create(lv_scr_act(), NULL);
    lv_obj_align(ta, NULL, LV_ALIGN_IN_TOP_MID, 0, 30);
    lv_ta_set_action(ta,action);
    /* Default object*/
    lv_obj_t * kb1 = lv_kb_create(lv_scr_act(), NULL);
    lv_obj_align(kb1, NULL, LV_ALIGN_IN_BOTTOM_MID, 0, 0);
    lv_kb_set_ta(kb1, ta);
}
```
the picture:
![1](https://user-images.githubusercontent.com/35949162/53480365-0abb0b80-3ab6-11e9-8914-8460d025409e.jpg)
![2](https://user-images.githubusercontent.com/35949162/53480383-0f7fbf80-3ab6-11e9-9e6b-da245813a1e8.jpg)
![3](https://user-images.githubusercontent.com/35949162/53480385-14447380-3ab6-11e9-9016-550a81b315e6.jpg)
![4](https://user-images.githubusercontent.com/35949162/53480396-17d7fa80-3ab6-11e9-9c32-447f0e2c5bdb.jpg)

you can see,the normal pictures are the first run of the program, then press the symbol 'X' to colse the 'kb',click the ‘ta’ obj and reload the 'kb'；
Then it was found that the ‘’#‘’ symbol and only the ‘’#‘’ symbol was not displayed, but there was no error in clicking on the button with the '#'

**Comment by as564335sa** [comment]
I found it was due to a problem with the `recolor` command.How to fix it？

**Comment by embeddedt** [comment]
@as564335sa It's probably because `#` is the character used for recoloring.

@kisvegabor Please comment.

**Comment by kisvegabor** [comment]
I examined it and found the issue. The recolor feature was not initialized in `lv_btnm_craete` therefore it got random value (from memory garbage).

Fixed in `master`. Is it working now?

**Comment by as564335sa** [comment]
Great! It is working now.
