### ISSUE TITLE
[feature] animated slider on group input

### ISSUE THREAD

**Issue by BrianPugh** [lvgl/lvgl#911]
Currently the `lv_slider` object just snaps to discrete positions on button input. However, it'd be nice if it did this with an animation. Adding the animation functionality is trivial (just change the `lv_slider_set_value` to `lv_slider_set_value_anim`), I'm just making this issue to discuss how to implement the API. Should it just be animated by default, and setting animation time to 0 would result in the current behavior? Should there be a function like `lv_slider_enable_anim` and `lv_slider_disable_anim` to set a flag? I can make a pull request, just curious about how it should be approached.

**Comment by embeddedt** [comment]
@BrianPugh I would implement it the same way I animated `lv_sw`. But let's get @kisvegabor's opinion too.

**Comment by BrianPugh** [comment]
EDIT: sorry what i said below was wrong, I'm just using a switch in a little less than conventional way.

```
so that was my initial though, but `lv_sw` is a bit different since you have to manually toggle the switch in your callback, while in `lv_slider` its automatic.

actually, as a sidenote; the switch toggling should probably be automatic, similar to `lv_slider`
```

**Comment by embeddedt** [comment]
@BrianPugh Are you sure? It should be automatic with `lv_sw` as well.

**Comment by BrianPugh** [comment]
You're right; I'll make a pull request for it to behave similar to a `lv_sw`. I think it's a good solution and it's good to be consistent.

**Comment by kisvegabor** [comment]
@BrianPugh Good idea to animate the slider if used via keyboard. A similar interface to `lv_sw` seems good to me:
- `lv_slider_set_anim_time`.
- `lv_slider_set_value(slider, 23)`
- `lv_slider_set_value_anim(slider, 23)`  (no anim time specified here)

 `lv_sw` can use `lv_slider`'s `anim_time` attribute.

**Comment by BrianPugh** [comment]
closing to continue conversation in #912
