### ISSUE TITLE
Can I dynamically configure information such as screen resolution?

### ISSUE THREAD

**Issue by tianyoung** [lvgl/lvgl#919]
Hi~
When my device screen changed, I had to recompile lvgl, which was very troublesome. Can I dynamically configure the information on the screen? For example, resolution and other information related to it?

**Comment by embeddedt** [comment]
@tianyoung This feature will be made available in `v6.0`, which is a backwards-incompatible release scheduled for June.

A development version  is available in the `dev-6.0` branch.

**Comment by tianyoung** [comment]
@embeddedt thank you.
