### ISSUE TITLE
How to associate common types with parent objects?

### ISSUE THREAD

**Issue by 3038922** [lvgl/lvgl#921]
```
lv_obj _t * father=lv_tabview_create(parent, nullptr);
int * a=new int;
*a=5;
//lv_obj_set_parent(father,static_cast<lv_obj_t *>(a));  //I want to associate * a with faher and realize the automatic release of * a.
 lv_task_create(task, 100, LV_TASK_PRIO_LOW, a);
```
Because task exists, it has to be set as a global variable, but it takes up too much memory.I want to build it when he needs it.,leave the page, automatically release.

**Comment by kisvegabor** [comment]
I suggest reading this post about how to add custom data to an object and how to extend their signal functions to react on `CLEAN_UP` signal: https://blog.littlevgl.com/2018-12-13/extend-lvgl-objects

--- 

In the past few days [LittlevGL's Forum](https://forum.littlevgl.com) has launched to discuss questions there. See this [Announcment](https://forum.littlevgl.com/viewtopic.php?f=3&t=5).

If the issue still persists please open a topic for it on the Forum.
