### ISSUE TITLE
Why do `btn` obj respond to "LV_GROUP_KEY_UP/DOWN/LEFT/RIGHT" click event?

### ISSUE THREAD

**Issue by as564335sa** [lvgl/lvgl#925]
Hi,
I find when press these keys : "LV_GROUP_KEY_UP/DOWN/LEFT/RIGHT" the `btn` obj will respond to click event,what's the purpose of this?

**Comment by embeddedt** [comment]
The LittlevGL forum was launched to handle questions. Please post a new topic there. See #906.
