### ISSUE TITLE
How can generate font in  same width size 

### ISSUE THREAD

**Issue by crazyuav** [lvgl/lvgl#929]
Hello kisvegabor,
Thanks for your great lib!

I try to generate font using [https://littlevgl.com/ttf-font-to-c-array](url),but font width(example:0-9) is diffrent. 

There is any way can generate same width font?

Best Regards,

**Comment by seyyah** [comment]
You can use the `Monospace` parameters,

> Optional for monospace fonts specify width [px]

**Comment by crazyuav** [comment]
It works.Thanks!

**Comment by AloyseTech** [comment]
Hi @kisvegabor ,
Sorry to comment on this old issue, but the monospace parameter is not available with the latest online TTF font converter. Is there any plan to add it?

**Comment by embeddedt** [comment]
As far as I know, if you convert a monospaced font, it will automatically be handled (and displayed in monospace). I don't think you have manual control over the setting anymore, because treating a regular font as monospace won't look right on a screen.

(cc @puzrin)

**Comment by puzrin** [comment]
There is NO way to CORRECTLY convert proportional font to monospace. New convertor produces result exactly as source designed. If you need monospace output - use monospace input.

The only "right" way to get predictable result is to find proper TTF font as source. That's possible, including case of pixel-perfect TTF fonts, designed for specific size.

**Comment by AloyseTech** [comment]
I often use regular font to render digits only, but in a monospaced format. Monospaced font with good looking digits are rare IMO.

Thanks anyway :)

**Comment by embeddedt** [comment]
It might be possible to modify your regular font so that all the digits have an equal width. That way, it really would be a monospaced font and the converter would treat it as such.

**Comment by puzrin** [comment]
By historic reason, font conversion had many kludges, caused by missunderstanid how font renderers work. I understand pain of development process change - nobody likes that. But it really worth to drop all those ancient magic in favour of more modern and correct font generation.

Of cause, you can edit digits in fontforge, but i think finding nice monospase font will take less time.

**Comment by kisvegabor** [comment]
@AloyseTech 
I've found cool monospaced digit fonts here: https://www.1001fonts.com/monospaced-fonts.html?page=1&items=10

I hope it helps.
