### ISSUE TITLE
[6.0] Slider is clipped at edges

### ISSUE THREAD

**Issue by embeddedt** [lvgl/lvgl#953]
My guess is that this is related to the recent padding changes. This screenshot is from `lv_test_theme_1` with the material theme, but the problem is also present on another theme, so I don't think it's necessarily theme-specific.

![Screenshot from 2019-03-17 20-43-01](https://user-images.githubusercontent.com/42941056/54500666-73e3b100-48f5-11e9-926f-d23ab35c377e.png)

**Comment by embeddedt** [comment]
@kisvegabor

**Comment by kisvegabor** [comment]
It was an issue in `lv_test_theme1`. I fixed by adjusting the paddings. 
See: https://github.com/littlevgl/lv_examples/commit/c1d44cc9f199f7a8878d84e54493f6328c66d078

Is it working well there too?

**Comment by embeddedt** [comment]
@kisvegabor It's working properly now. Thanks!

**Comment by kisvegabor** [comment]
Great! Thank you! :)
