### ISSUE TITLE
[Align]: Can't align object

### ISSUE THREAD

**Issue by peng-fan** [lvgl/lvgl#956]
I cant align two objects , For example:
![align_1](https://user-images.githubusercontent.com/14306529/54509330-2cf0cc80-4984-11e9-8152-56de549d2af9.png)
if I set the **btn1** as the parent of **img_normal** , then the **lv_obj_align** cant work . What's wrong?
![align_res](https://user-images.githubusercontent.com/14306529/54509341-35490780-4984-11e9-9b7b-640599171803.png)

**Comment by kisvegabor** [comment]
The buttons have `LV_LAYOUT_CENTER` by default. Try `lv_btn_set_layout(btn1, LV_LAYOUT_OFF)`.

---

We use GitHub issues for development related discussions.
Please use the [Forum](https://forum.littlevgl.com/) to ask questions.
