### ISSUE TITLE
swipe left/right support for images

### ISSUE THREAD

**Issue by Moo2017** [lvgl/lvgl#961]
Hi All,
I have a gallery menu in my application so user can see the stored photos. Does image object support swipe left/right?

**Comment by embeddedt** [comment]
@Masi2017 No, I think you would need to extend it's functionality with a signal handler.

@kisvegabor wrote a great post about that: https://blog.littlevgl.com/2018-12-13/extend-lvgl-objects

**Comment by Moo2017** [comment]
@embeddedt Thank you I'll have a look. I have one more question, how I can be notified if object is swiping? Because I have the images stored in the SD card and I can't read all the images from SD card in advance and create the objects . I will only get the first image and then once user swipes (right/left) , I'll read the next and draw it.

**Comment by kisvegabor** [comment]
@Masi2017 
You can even use `lv_tabview` where swiping and `tab_load_action`s are supported.

---

We started a [Forum](https://forum.littlevgl.com/) to discuss questions there. GitHub issue should be rather about development related topics. See this [announcement](https://github.com/littlevgl/lvgl/issues/906).

If you have further questions about image swiping please open a topic in the Forum and let's continue there.
