### ISSUE TITLE
What is the minimum resolution that this library supports? Can I use this library to support 64*64 LED full-color dot matrix screen

### ISSUE THREAD

**Issue by chenyang8094** [lvgl/lvgl#962]
RT

**Comment by kisvegabor** [comment]
Yes, you can. There is no minimum resolution ( > 1px)

---

We use GitHub issue's for development related discussions. Please use the [Forum](https://forum.littlevgl.com) to ask questions.

**Comment by xudong8** [comment]
> RT

可以交流学习下吗![Screenshot_2024-06-05-17-35-43-640_com.miui.gallery.jpg](https://github.com/lvgl/lvgl/assets/40586712/0d846c23-2acf-41ec-bc15-d8ce175c5b90)

**Comment by kisvegabor** [comment]
If each byte is mapped to 8 pixels be sure that the bit order is correct.

Also be sure that you set a `rounder_cb` (in v8, example [here](https://docs.lvgl.io/8.4/porting/display.html)) or `LV_EVENT_INVALIDATE_AREA` (in v9, more info [here](https://docs.lvgl.io/9.1/porting/display.html#events)) to be sure that LVGL always redraws an area which start on 8 px boundary.
