### ISSUE TITLE
enhancement request

### ISSUE THREAD

**Issue by fovea1959** [lvgl/lvgl#965]
Please consider adding a SYMBOL_CLOUD to the fonts.

**Comment by embeddedt** [comment]
(cc @kisvegabor)

----------------------
We use GitHub issues for development related discussions.
In the future, please use the [forum](https://forum.littlevgl.com/) to ask questions or suggest enhancements.

**Comment by kisvegabor** [comment]
Personally, I don't think that a Cloud symbol would be commonly used on embedded systems. Anyway, please move this request to the forum. If others will find it useful too we can add it.
