### ISSUE TITLE
Does this library support drawing in vector format?

### ISSUE THREAD

**Issue by sevencheng798** [lvgl/lvgl#968]
Does this library support drawing in vector format? such as: SVG suffix format

**Comment by manison** [comment]
Not right out of the box, but you could possibly integrate [SVG rasterizer](https://github.com/memononen/nanosvg) as [custom image decoder](https://blog.littlevgl.com/2018-10-05/png_converter).

**Comment by kisvegabor** [comment]
We started a [Forum](https://forum.littlevgl.com/) to discuss questions there. GitHub issue should be rather about development related topics. See this [announcement](https://github.com/littlevgl/lvgl/issues/906).

If you have further questions about drawing in vector format please open a topic in the Forum and let's continue there.
