### ISSUE TITLE
creat window prevent serial port receiving.

### ISSUE THREAD

**Issue by relliktei** [lvgl/lvgl#970]
I am using 2 page in my project.
Page1: main.   
![image](https://user-images.githubusercontent.com/41564775/54805888-4f038b00-4cb3-11e9-9940-e8511e8b52fe.png)

Page2:
![image](https://user-images.githubusercontent.com/41564775/54805898-5aef4d00-4cb3-11e9-91d7-588072345b70.png)

I can Click button into second page calling lv_win_create()

I also use one serial port to receive data from remote device to update status in pages.
The realtime data can be shown correctly in page1.

But I notice one problem:
**When I go to Page2, data cannot update in time.**
![image](https://user-images.githubusercontent.com/41564775/54806448-f33a0180-4cb4-11e9-8e57-cf2591b8108d.png)

I also dump data received by serial port as below:
![image](https://user-images.githubusercontent.com/41564775/54806277-81fa4e80-4cb4-11e9-93d2-d4a18a7dba04.png)

**In dump data picture, the only one thing different is that I go to page2 by calling lv_win_create().**

It sounds like serial port receiving goes strange after I create new window.
Does "LV_WIN_CREATE" prevent USART INTERRUPT handler?
I don't know why. How can I fix it?

**Comment by relliktei** [comment]
Sorry, I solved it.
I use lv_task_create to create new task to update page2, then USART can receive data correctly.
I will close this issue.

**Comment by embeddedt** [comment]
Glad you figured it out!

----------------------
We use GitHub issues for development related discussions.
In the future, please use the [forum](https://forum.littlevgl.com/) to ask questions.
