### ISSUE TITLE
[meta] issue and pull request templates

### ISSUE THREAD

**Issue by C47D** [lvgl/lvgl#975]
Hi,

Just found out there are [templates for new issues and pull requests](https://help.github.com/en/articles/about-issue-and-pull-request-templates), do you think this can be useful for this project?

[Create Pull request template](https://help.github.com/en/articles/creating-a-pull-request-template-for-your-repository).
[Create issue template](https://help.github.com/en/articles/creating-issue-templates-for-your-repository).

**Comment by embeddedt** [comment]
@C47D Yes, I intend to add these so that people will know to direct questions and enhancement requests to the forum rather than here. See #906.

**Comment by C47D** [comment]
@embeddedt Great, should we close this issue until the templates are added?

**Comment by embeddedt** [comment]
@C47D I'm working on them right now.

**Comment by embeddedt** [comment]
@kisvegabor Issue templates are added; let me know if you think something needs changing.

**Comment by C47D** [comment]
That was quick!, i don't know how often lvgl receive pull request, if so, do they need an special format?
It might be useful to add a template for them as well.

**Comment by embeddedt** [comment]
@C47D I don't think templates are necessary for pull requests right now, because usually a pull request is only opened after a discussion on the feature (unless it's a bugfix).

In the future it might be something to look into though.

**Comment by C47D** [comment]
I see, you are right, thanks for the quick reply!

**Comment by kisvegabor** [comment]
Looks great! Thank you!

I've just renamed `bug_report.md` to `bug-report.md` for consistency.
