### ISSUE TITLE
lv_ddlist select wrong option on click

### ISSUE THREAD

**Issue by embeddedt** [lvgl/lvgl#979]
When you click in either direction on the "Theme" or "Color" rollers in `lv_test_theme_2`, they usually move by two options instead of one. Not sure exactly what the problem is. This isn't hardware-specific.

**Comment by embeddedt** [comment]
@kisvegabor I'll investigate `lv_label_get_letter_on` today.

EDIT: I had a look but unfortunately I can't seem to find anything.

**Comment by kisvegabor** [comment]
Do you see the incorrect return value?
I mean could you reproduce the issue?

**Comment by kisvegabor** [comment]
I found it. Stupid mistake...  See: https://github.com/littlevgl/lvgl/commit/770d1e08e1e5a94db4749da1b80b5cfe4e4153ac

Probably this line was deleted accidentally. Without it, the x coordinate could be very big and 
the `lv_label_get_letter_on()` found the next line.

Could you verify if it really works correctly now?

**Comment by embeddedt** [comment]
@kisvegabor 

> Stupid mistake... See: 770d1e0

I know how it feels to discover something like that. :wink:

> Could you verify if it really works correctly now?

Works as expected now. Thanks for debugging it!

**Comment by kisvegabor** [comment]
> I know how it feels to discover something like that. wink

That's life :smile:
