### ISSUE TITLE
lv_ll bug

### ISSUE THREAD

**Issue by chenshijianworkgit** [lvgl/lvgl#98]
I found lv_ll_rem function to achieve a problem：

If the linked list has only two nodes, then delete the second node, then n_prev point to the first node, 
n_next will point to NULL, then call node_set_prev (ll_p, n_next, n_prev) will result in an error.

lv_ll_rem
	lv_ll_node_t* n_prev = lv_ll_get_prev(ll_p, node_p);
	lv_ll_node_t* n_next = lv_ll_get_next(ll_p, node_p);
	
	node_set_next(ll_p, n_prev, n_next);
	node_set_prev(ll_p, n_next, n_prev);

**Comment by chenshijianworkgit** [comment]
I was wrong, there are judgments of the head and tail

**Comment by chenshijianworkgit** [comment]
It is best to add a parameter legality judgment

void lv_ll_rem(lv_ll_t  * ll_p, void * node_p) ；       //if  node_p is NULL have a problem
void * lv_ll_get_next(lv_ll_t * ll_p, void * n_act)；   //if  n_actis NULL have a problem
void * lv_ll_get_prev(lv_ll_t * ll_p, void * n_act)；  //if  n_actis NULL have a problem
static void node_set_prev(lv_ll_t * ll_p, lv_ll_node_t* act, lv_ll_node_t* prev)；
static void node_set_next(lv_ll_t * ll_p, lv_ll_node_t* act, lv_ll_node_t* next)

**Comment by chenshijianworkgit** [comment]
I find that all the linked list functions are used directly without parameter judgment.

**Comment by kisvegabor** [comment]
The discussion continues in #101
