### ISSUE TITLE
Text Area: LV_CURSOR_UNDERLINE blink doesn't work

### ISSUE THREAD

**Issue by upbeat27** [lvgl/lvgl#987]
**Describe the bug**

For Text Area object: blink animation for LV_CURSOR_UNDERLINE does not work correctly.
Other cursor types animate correctly.
The cursor will either not blink at all, or it will change size instead of blinking.

**To Reproduce**

Create a Text Area with lv_cursor_type_t set to LV_CURSOR_UNDERLINE

**Expected behavior**

The cursor should blink.

**Additional context**

It used to work as of 92747ec37a19d73402c050e6e4b514254a97e764, I think the culprit may be 7ac12cd07100e7adfcd54a6bc8d876f675101d45

**Comment by embeddedt** [comment]
(cc @kisvegabor)

**Comment by kisvegabor** [comment]
It's working for me on the latest `master`:
```c
    lv_obj_t * ta = lv_ta_create(lv_scr_act(), NULL);
    lv_ta_set_cursor_type(ta, LV_CURSOR_UNDERLINE);
```
![ta](https://user-images.githubusercontent.com/7599318/55132857-171d9d00-5124-11e9-89e4-319a14c09d8f.gif)

**Comment by upbeat27** [comment]
Hmmm... it definitely is not working for me. Maybe it is a combination of my theme and font, but I couldn't figure out what the cause is. Tried changing lots of things, nothing seemed to have an effect.
[theme_and_font.zip](https://github.com/littlevgl/lvgl/files/3023587/theme_and_font.zip)

Some gifs (only difference being which lvgl commit is used):

Current Master:
![lvgl_blink_not_working](https://user-images.githubusercontent.com/32659164/55248345-d8acde80-5206-11e9-9c6c-42ba9ba5311a.gif)

When it used to work, on commit 92747ec37a19d73402c050e6e4b514254a97e764:
![lvgl_blink_working](https://user-images.githubusercontent.com/32659164/55248164-7653de00-5206-11e9-8831-1e0bd4ade349.gif)

**Comment by kisvegabor** [comment]
Still blinking for me.
![ta](https://user-images.githubusercontent.com/7599318/55302193-6293bc00-5440-11e9-8ffd-bdcea4242efc.gif)

Can you send a minimal PC simulator project?

**Comment by embeddedt** [comment]
@upbeat27 As well as sending a project, check whether animations are enabled and whether you are calling `lv_tick_inc` at the appropriate times. Those shouldn't be a problem, but I ask just in case it's related.

**Comment by upbeat27** [comment]
So... I couldn't get it to do it with the simulator, but I knew it was happening!
So I had to dig a little deeper.
The issue is caused by having a round area callback.
The callback doesn't even have to do anything, just setting a callback causes the problem. For example:
```c
static void round_area_cb(lv_area_t* a)
{
// Don't even do anything...
}
// In init:
lv_refr_set_round_cb(round_area_cb);
```

Rather than send the entire project, just add that to your existing test.

**Comment by kisvegabor** [comment]
Thank you, I really found a bug if  `round_cb` is enabled. Pushed the fix into master.

Now the cursor is blinking but I couldn't test it with real hardware where you are rounding to 8. Please verify if it does not break the "normal" rounding behavior.

**Comment by upbeat27** [comment]
@kisvegabor this fixed it for me, blink works fine now. Normal rounding behavior seems to be working on my target with OLED requiring x values to be on a 4 pixel boundary. In my case the rounding is rather simple though. I feel like there could potentially be a problem if someone needs to round up y2, for example (I don't know if any display would require such a thing).

**Comment by kisvegabor** [comment]
> this fixed it for me, blink works fine now. 

Great!

>  I feel like there could potentially be a problem if someone needs to round up y2, for example (I don't know if any display would require such a thing).

Rouning y to 8 is a common scenario for monochrome displays where 1 byte represents 8 pixels in a  column.
