### ISSUE TITLE
I can't receive confirmation mail.

### ISSUE THREAD

**Issue by 3038922** [lvgl/lvgl#992]
Sorry, I can't receive confirmation mail.
my username 3038922
my email 31612534@qq.com
![image](https://user-images.githubusercontent.com/33926386/55333315-9cf56b80-54c9-11e9-9a95-b7b94ea37a80.png)

I want to make a terminal . Like this. I want to ask what module should be used to achieve?
hiden==true
![image](https://user-images.githubusercontent.com/33926386/55333821-9a474600-54ca-11e9-9d47-52e05499a832.png)

hiden==false
![image](https://user-images.githubusercontent.com/33926386/55333908-bf3bb900-54ca-11e9-8a8e-4ed699d1e8d1.png)

**Comment by embeddedt** [comment]
@kisvegabor would have to look into the account problem, as I don't think I have the necessary permissions to access that.

As for the terminal question, I don't quite understand what you mean? Are you trying to replicate that user interface on LittlevGL?

**Comment by 3038922** [comment]
I just want to implement a drop-down animation that can open a terminal.

Now I'm using the button to hide and display the terminal. But he doesn't look cool...

**Comment by embeddedt** [comment]
@3038922 You should build your own animation with `lv_anim_t`. You can move the object's Y position so that it slides off or on to the screen.

If you just want a basic animation you can try `LV_ANIM_IN` or `LV_ANIM_OUT`.

**Comment by 3038922** [comment]
> @3038922 Please, try the "Resend activation mail" link on the login page and check your spam folder too.
I've tried more than ten times. I couldn't get a confirmation email last month. It's the same today.
Can you change it for me in the database?

**Comment by kisvegabor** [comment]
I've activated you manually.
