### ISSUE TITLE
NOT suport multiple spinbox like roller

### ISSUE THREAD

**Issue by crazyuav** [lvgl/lvgl#993]
1. I create three spinbox,and add them to group.
```c
/*create three spinbox*/
app.current.spinbox = lv_spinbox_create(lv_scr_act(), NULL);
app.voltage.spinbox = lv_spinbox_create(lv_scr_act(), app.current.spinbox);
app.power.spinbox = lv_spinbox_create(lv_scr_act() , app.current.spinbox);
..
..
...
/*add to group*/
lv_group_t * g = lv_group_create();
lv_group_add_obj(g, app.current.spinbox); 
lv_group_add_obj(g, app.voltage.spinbox); 
lv_group_add_obj(g, app.power.spinbox); 
lv_group_set_editing(g, false);
lv_indev_set_group(indev_encoder, g);
lv_indev_set_group(indev_keypad, g);
```
2. modify spinbox function **lv_spinbox_signal**
```c
......
else if(sign == LV_SIGNAL_RELEASED) {
    lv_group_t * g = lv_obj_get_group(spinbox);
    bool editing = lv_group_get_editing(g);
    if(editing) lv_group_set_editing(g, false); 
}
.......
```
3. then press encoder
    1. press LV_GROUP_KEY_ENTER  ->edit mode
    2. press LV_GROUP_KEY_ENTER  ->navigate mode
    3. turn right/turn left three times -> generate a bug enter HardFault_Handler
because  the function **focus_next_core** call the **lv_obj_get_hidden**,then generate HardFault_Handler

**Comment by embeddedt** [comment]
(cc @kisvegabor)

**Comment by crazyuav** [comment]
It works，Thanks!

on branch dev-6.0, modified  **lv_group_style_mod_func_t** callback function ,and add a new parameter **group**,but I don't synchronize with callback
